#
# Item.c messages
#
{1}{}{你获得了%d个%s。}
{2}{}{你失去了%d个%s。}
{3}{}{你感觉好多了。}
{4}{}{你因药物过量而心脏病发作致死。}
{5}{}{%s没有剩余的充能。}
{6}{}{%s已开启。}
{7}{}{%s已关闭。}
{8}{}{你用盖革计数器扫描身体。辐射计数显示：%d}
{9}{}{此物品只能从界面栏使用。}
{10}{}{什么也没有发生。}
