#
# 
#
# Text labels and messages used in LOADSAVE.C
#
# (These MUST match "text message" enumeration on the top of LOADSAVE.C)
#
# 

# System
{100}{}{读取游戏}              # Titles {101}{}{选择快速读取槽位}
{102}{}{保存游戏}
{103}{}{选择快速保存槽位}
{104}{}{完成}
{105}{}{取消}
{106}{}{加载存档列表出错！} # Line 1 {107}{}{存档目录：}    # Line 2 {108}{}{不存在或已损坏。} # Line 3 {109}{}{保存游戏}
{110}{}{读取游戏}
{111}{}{- 空 -}
{112}{}{- 损坏的存档文件 -}
{113}{}{- 旧版本 -}
{114}{}{空。}
{115}{}{错误！}
{116}{}{旧版本。}
{117}{}{一月}                            # Months {118}{}{二月}
{119}{}{三月}
{120}{}{四月}
{121}{}{五月}
{122}{}{六月}
{123}{}{七月}
{124}{}{八月}
{125}{}{九月}
{126}{}{十月}
{127}{}{十一月}
{128}{}{十二月}
{129}{}{等级}
{130}{}{描述}
{131}{}{存档已存在，是否覆盖？}
{132}{}{保存游戏出错！}             # Line 1 {133}{}{无法保存游戏。}           # Line 2 {134}{}{加载游戏出错！}            # Line 1 {135}{}{无法加载游戏。}           # Line 2 {136}{}{存档文件为旧版本。}
{137}{}{地图}

{140}{}{游戏已保存。}
{141}{}{游戏已加载。}
#
# Demo versions only
#
{200}{}{抱歉，您无法保存或加载} # 1 {201}{}{在演示版本中。}         # 2
