#
# 
#
# Text labels and messages used in OPTIONS.C
#
# (These MUST match "text message" enumeration on the top of OPTIONS.C)
#
# 

#  Main option panel 
#
# Buttons
{0}{}{保存游戏}
{1}{}{加载游戏}
{2}{}{偏好设置}
{3}{}{退出游戏}
{4}{}{完成}
#
# Preferences
#
{100}{}{游戏偏好设置}
{101}{}{游戏难度}
{102}{}{战斗难度}
{103}{}{暴力等级}
{104}{}{目标高亮}
{105}{}{燃烧效果}
{106}{}{战斗信息}
{107}{}{战斗嘲讽}
{108}{}{语言过滤}
{109}{}{奔跑}
{110}{}{字幕}
{111}{}{物品高亮}
{112}{}{战斗速度}
{113}{}{文字延迟}
{114}{}{主音量}
{115}{}{音乐/电影音量}
{116}{}{音效音量}
{117}{}{语音音量}
{118}{}{亮度等级}
{119}{}{鼠标灵敏度}
{120}{}{默认}
{121}{}{取消}
{122}{}{影响玩家速度}
{123}{}{Pipboy 语音}
#
# Label text
#
{201}{}{开}             # 1 {202}{}{关}            # 2 {203}{}{简单}           #  1 {204}{}{正常}         #  2 {205}{}{困难}           #  3 {206}{}{弱小}          # 1 {207}{}{正常}         # 2 {208}{}{粗暴}          # 3 {209}{}{正常}         #  1 {210}{}{最快}        #  2 {211}{}{详细}        # 1
{214}{}{无}           # 1 {215}{}{最少}        # 2 {216}{}{最大血量}  # 3 {217}{}{慢速}           #  1 {218}{}{快速}         #  2 {219}{}{总是}
{220}{}{大量}
{221}{}{安静}          # 1 {222}{}{响亮}           # 2 {223}{}{更亮}
{224}{}{宽广}


#
# Pause window
#
{300}{}{完成}
{301}{}{暂停}
#
# Demo versions only
#
{1000}{}{抱歉，偏好设置菜单在演示版中不可用。}  # 1 {1001}{}{}      # 2
