{100}{}{皮革护甲}
{101}{}{你最基本的全皮装束。由精心鞣制的辐射牛皮制成。}
{200}{}{金属护甲}
{201}{}{抛光的金属板，粗糙地组成了一套护甲。}
{300}{}{动力装甲}
{301}{}{一套自给自足的先进科技护甲。由微型聚变反应堆供能，燃料足以维持百年。}
{400}{}{刀}
{401}{}{一把锋利的切割和刺击武器。最低力量需求：2。}
{500}{}{棍棒}
{501}{}{一根军用或警用警棍。重木制成。最低力量需求：3。}
{600}{}{大锤}
{601}{}{一把带长柄的大锤。非常受肌肉男群体欢迎。最低力量需求：6。}
{700}{}{长矛}
{701}{}{一把尖锐的长柄武器。木制杆身，钢制尖端。最低力量需求：4。}
{800}{}{10毫米手枪}
{801}{}{一把柯尔特6520型10毫米自动装填手枪。每次扣动扳机都会自动装填，直到弹匣耗尽。仅单发，使用强力10毫米子弹。最低力量需求：3。}
{900}{}{10毫米冲锋枪}
{901}{}{H&K MP9冲锋枪（10毫米版本）。中型冲锋枪，支持单发和连发模式。最低力量需求：4。}
{1000}{}{猎枪}
{1001}{}{一把柯尔特Rangemaster半自动步枪，.223口径。仅单发。最低力量需求：5。}
{1100}{}{火焰喷射器}
{1101}{}{Flambe 450型号火焰喷射器，捕猎者变种。喷射短程高温可燃液体。需要专用燃料才能正常工作。最低力量需求：6。}
{1200}{}{迷你枪}
{1201}{}{一把Rockwell CZ53个人迷你枪。多管链式机枪，以超过60,000转/分钟的速度发射5毫米弹药。最低力量需求：7。}
{1300}{}{火箭发射器}
{1301}{}{一把Rockwell BigBazooka火箭发射器。配有豪华3磅扳机。可发射穿甲或爆炸火箭。最低力量需求：6。}
{1400}{}{爆炸火箭}
{1401}{}{一枚带有大爆炸弹头的火箭。}
{1500}{}{等离子步枪}
{1501}{}{一把Winchester P94型号等离子步枪。工业级能量武器，发射超高温等离子束，通过超导枪管。由微型聚变电池供电。最低力量需求：6。}
{1600}{}{激光手枪}
{1601}{}{一把瓦茨1000型激光手枪。民用型号，所以功率比军用或警用版本低。使用小型能量电池。最低力量要求：3。}
{1700}{}{战斗护甲}
{1701}{}{高科技护甲，由先进的防御聚合物制成。}
{1800}{}{沙漠之鹰 .44}
{1801}{}{一把古老的沙漠之鹰手枪，使用.44马格南弹。由于20世纪末电影的影响，这成为了有史以来最受欢迎的手枪之一。最低力量要求：4。}
{1900}{}{石头}
{1901}{}{这是一块石头。花岗岩公司型号是升级版。最低力量要求：1。}
{2000}{}{撬棍}
{2001}{}{一块非常坚固且沉重的金属，专为施加杠杆而设计。或者用来砸头。最低力量要求：5。}
{2100}{}{指节铜套}
{2101}{}{硬化的指节握把，实际上是由钢制成。在徒手战斗中保护你的手，并造成更多伤害。最低力量要求：1。}
{2200}{}{14毫米手枪}
{2201}{}{一把西格-绍尔14毫米自动手枪。大型单发手枪。工艺精湛。最低力量要求：4。}
{2300}{}{突击步枪}
{2301}{}{一把AK-112 5毫米突击步枪。旧式军用型号，在战争时期已停用。可单发或连发，使用高速5毫米子弹。最低力量要求：5。}
{2400}{}{等离子手枪}
{2401}{}{格洛克86等离子手枪。由加斯顿·格洛克AI设计。发射一小束超高温等离子。由小型能量电池供电。最低力量要求：4。}
{2500}{}{手榴弹（破片）}
{2501}{}{一种普通的破片手榴弹。含有少量高爆炸药，容器本身形成大部分破片伤害。接触即爆。最低力量要求：3。}
{2600}{}{手榴弹（等离子）}
{2601}{}{一种磁封等离子投放装置，带有引爆炸药。接触时产生超高温等离子爆炸。最低力量要求：4。}
{2700}{}{手榴弹（脉冲）}
{2701}{}{一种电磁脉冲手榴弹，爆炸时产生强烈磁场。不影响生物体。接触引信。最低力量要求：4。}
{2800}{}{加特林激光}
{2801}{}{一把H&K L30加特林激光枪。专为军用设计，这些在战争初期处于原型阶段。多管设计允许更长时间射击而不过热。由微聚变电池供电。最低力量要求：6。}
{2900}{}{10毫米 JHP}
{2901}{}{弹药。口径：10毫米，夹套空尖弹}
{3000}{}{10毫米 AP}
{3001}{}{弹药。口径：10毫米，穿甲弹。}
{3100}{}{.44 马格南 JHP}
{3101}{}{一块弹药，.44 马格南口径，空尖弹。}
{3200}{}{喷火器燃料}
{3201}{}{一个装有极易燃液体燃料的圆筒，用于喷火器。}
{3300}{}{14mm 穿甲弹}
{3301}{}{大口径弹药，14mm 穿甲弹。}
{3400}{}{.223 全金属被甲弹}
{3401}{}{一箱弹药，.223 口径，全金属被甲。}
{3500}{}{5mm 中空尖头弹}
{3501}{}{一块小型轻量弹药。口径：5mm，包覆空尖弹。}
{3600}{}{5mm 穿甲弹}
{3601}{}{一块小口径弹药。5mm 穿甲弹。}
{3700}{}{火箭 AP}
{3701}{}{一枚火箭弹，爆炸力较小，但设计用于穿透装甲。}
{3800}{}{小型能量电池}
{3801}{}{一个小型的自供能量储存单元。}
{3900}{}{微型聚变电池}
{3901}{}{一个中型能量生产单元。自供聚变装置。}
{4000}{}{治疗针}
{4001}{}{一种治疗药物。注射后可立即治愈轻微伤口。}
{4100}{}{瓶盖}
{4101}{}{这个袋子装着你的瓶盖。}
{4200}{}{冰箱}
{4201}{}{一个冰箱，冷却剂已耗尽。}
{4300}{}{冰柜}
{4301}{}{一个老式冰柜。铰链运作良好。}
{4400}{}{冰柜}
{4401}{}{一个老式冰柜。铰链运作良好。}
{4500}{}{飞刀}
{4501}{}{一把专为投掷而平衡的刀。由钛制成，激光锐化。最低力量要求：3。}
{4600}{}{袋子}
{4601}{}{一个中等大小的袋子，由辐射牛毛编织而成。}
{4700}{}{急救包}
{4701}{}{一个小型急救包，内含基本医疗设备。绷带、包扎物、消毒喷雾等。}
{4800}{}{辐射清除剂}
{4801}{}{一种化学溶液，可与辐射粒子结合并通过你的系统排出。需要时间生效。}
{4900}{}{解毒剂}
{4901}{}{一瓶自制的解毒剂。乳白色液体，漂浮着蝎子肉碎片。}
{5000}{}{预留物品}
{5001}{}{这是一个预留物品。请勿使用。}
{5100}{}{炸药}
{5101}{}{一种高爆炸物，由硝化甘油与吸收性物质硅藻土混合而成。附带计时器。}
{5200}{}{盖革计数器}
{5201}{}{瓦兹电子C-Radz型号盖革计数器。检测辐射场的存在和强度。}
{5300}{}{记忆增幅药}
{5301}{}{一盒改变心智的药物。提高记忆相关功能，加速其他精神过程。会引发渴望。}
{5400}{}{隐形小子}
{5401}{}{罗博公司隐形小子3001个人隐形装置。生成调制场，将物体一侧的反射光传输到另一侧。}
{5500}{}{水芯片}
{5501}{}{一个水净化控制计算机系统芯片。看起来非常像你的避难所需要的芯片。}
{5600}{}{身份牌}
{5601}{}{一套军用身份牌。名字“暗水”可辨认，但其他信息不清晰。}
{5700}{}{窃听器}
{5701}{}{一个微型麦克风和传输装置。}
{5800}{}{磁带}
{5801}{}{瓦兹电子全息磁带。这盘磁带状况非常糟糕。}
{5900}{}{运动传感器}
{5901}{}{瓦兹电子C-U型号运动传感器。使用调谐雷达装置检测数米范围内生物材料的移动。}
{6000}{}{书架}
{6001}{}{一个木制书架。}
{6100}{}{书架}
{6101}{}{一个木制书架。}
{6200}{}{书架}
{6201}{}{一个木制书架。}
{6300}{}{书架}
{6301}{}{一个木制书架。}
{6400}{}{书架}
{6401}{}{一个木制书架。}
{6500}{}{书架}
{6501}{}{一个木制书架。}
{6600}{}{书桌}
{6601}{}{一个木制书桌。}
{6700}{}{书桌}
{6701}{}{一个木制书桌。}
{6800}{}{衣柜}
{6801}{}{一个木制衣柜。}
{6900}{}{衣柜}
{6901}{}{一个木制衣柜。}
{7000}{}{衣柜}
{7001}{}{一个木制衣柜。}
{7100}{}{水果}
{7101}{}{一块奇怪的水果。没有添加防腐剂和食用色素。}
{7200}{}{公文包}
{7201}{}{一个贴有美国制造标签的公文包。皮质。状况良好，但密码锁坏了。}
{7300}{}{科学大百科}
{7301}{}{一套包含不同科学领域信息的书籍。}
{7400}{}{皮夹克}
{7401}{}{一件黑色厚重的皮夹克。}
{7500}{}{工具}
{7501}{}{一套超级工具，包含各种实用工具。}
{7600}{}{迪恩斯电子学}
{7601}{}{一本关于电子学领域的学习书。封面上的注释写着："每个人都是潜在的年轻电工！"}
{7700}{}{电子开锁器}
{7701}{}{一款沃兹电子微操控指尖电子开锁器。用于破解电子锁和安全设备。}
{7800}{}{模糊画作}
{7801}{}{一幅歌手的画像。显然非常古老。图像表面有一层毡涂层，仍然保持良好状态。}
{7900}{}{信号弹}
{7901}{}{一个信号弹。能在短时间内提供光亮。纸张有些磨损，但总体状况良好。旋转顶部即可激活。}
{8000}{}{急救手册}
{8001}{}{一本关于急救技能概念和实用操作的学习书。}
{8100}{}{蜥蜴串}
{8101}{}{一只烤熟的蜥蜴，连皮一起烤制。}
{8200}{}{钥匙}
{8201}{}{一把钥匙。钥匙可以打开特定的锁。}
{8300}{}{钥匙圈}
{8301}{}{多把钥匙。}
{8400}{}{开锁工具}
{8401}{}{一套锁匠工具。包括所有必要的开锁器和扭力扳手，用于打开传统的销栓锁。}
{8500}{}{塑胶炸药}
{8501}{}{一块Cordex军用品牌的塑胶炸药。高度稳定，破坏力极强。附带定时器。}
{8600}{}{侦察手册}
{8601}{}{一本关于侦察方法和理念的书。提供非常实用的户外生活信息。}
{8700}{}{力量药片}
{8701}{}{高度先进的类固醇。在效果持续期间，能增加力量和反应能力。会引发强烈的渴望。}
{8800}{}{手表}
{8801}{}{一块昂贵的手表。虽然不再运作，但看起来仍然不错。}
{8900}{}{马达}
{8901}{}{一个40马力的电动马达。}
{9000}{}{背包}
{9001}{}{一个基础背包，带有可选的携带肩带。}
{9100}{}{医生的工具包}
{9101}{}{这个黑色包里装有医生用于行医的工具和药物。}
{9200}{}{蝎子尾巴}
{9201}{}{一只辐射蝎的断尾。}
{9300}{}{袋子}
{9301}{}{一个中等大小的袋子。用编织的布拉明牛毛制成。}
{9400}{}{霰弹枪}
{9401}{}{一把温彻斯特“寡妇制造者”双管12号霰弹枪。短枪管，配有红木握柄。最低力量要求：4。}
{9500}{}{12号霰弹枪弹药}
{9501}{}{霰弹枪弹药。此弹药标注为：“12号霰弹，三岁以下儿童禁止使用。”}
{9600}{}{红色通行证}
{9601}{}{一把电子安全钥匙，红色编码。}
{9700}{}{蓝色通行证}
{9701}{}{一把电子安全钥匙，蓝色编码。}
{9800}{}{废品}
{9801}{}{一堆废旧零件。各种各样的东西。}
{9900}{}{金项链盒}
{9901}{}{一个有价值的金项链盒。}
{10000}{}{收音机}
{10001}{}{一台Wattz Electronics公司出品的2043B型无线电通讯器。可靠、坚固且具备伪装功能。配有可选的RS-121接口。}
{10100}{}{打火机}
{10101}{}{一个银色丁烷打火机，状况良好。}
{10200}{}{枪械与子弹}
{10201}{}{一本枪械杂志。专注于枪械的实际使用，偶尔也有偏颇的评论。}
{10300}{}{蜥蜴串}
{10301}{}{一些烤焦的肉和蔬菜串在一根烤串上。}
{10400}{}{录音机}
{10401}{}{一台Wattz Electronics公司出品的“为我播放”录音机。播放和录制标准的30分钟高密度“一次录制”磁带。}
{10500}{}{钥匙}
{10501}{}{某种特殊的钥匙。}
{10600}{}{核子可乐}
{10601}{}{一瓶核子可乐，核战后世界的味道软饮料。温热且无气。}
{10700}{}{骨头}
{10701}{}{一堆奇怪的骨头。}
{10800}{}{骨头}
{10801}{}{一堆奇怪的骨头。}
{10900}{}{抗辐灵}
{10901}{}{在辐射暴露前使用的抗辐射药物。无已知副作用。}
{11000}{}{狂欢}
{11001}{}{一种独特的递药系统，充满了可能军事起源的奇怪化学物质。据称可以提高士兵的战斗能力。}
{11100}{}{.44马格南全金属被甲弹}
{11101}{}{一盒弹药，.44马格南口径，全金属被甲。}
{11200}{}{骨灰坛}
{11201}{}{一个漂亮的金色骨灰坛，正面刻有"Harriet"的名字，里面有骨灰。}
{11300}{}{长袍}
{11301}{}{大教堂之子的长袍。}
{11400}{}{缠斗者的手}
{11401}{}{一个网络机械操作手，形状像一只手。由于拆卸过程粗糙而受损。}
{11500}{}{超级大锤}
{11501}{}{一个由钢铁兄弟会制造的超级大锤，运用了最先进的武器科技。包括动能储存装置，以增加击退效果。最小力量: 5。}
{11600}{}{开膛手}
{11601}{}{开膛手?震动刀。由小型能量电池供电，链刃撕裂目标。最小力量: 4。}
{11700}{}{花}
{11701}{}{一朵美丽的花。}
{11800}{}{激光步枪}
{11801}{}{瓦茨2000激光步枪。使用微型聚变电池以提供更强大的激光，并配有加长枪管以扩展射程。最小力量: 6。}
{11900}{}{项链}
{11901}{}{看起来昂贵的项链，由银、金和压制钻石制成。}
{12000}{}{异星枪}
{12001}{}{一把明显外星起源的奇异武器。看起来能支持小型能量电池。最小力量: 2。}
{12100}{}{9毫米子弹}
{12101}{}{一批古老的9x19毫米子弹。涂有厚重的油脂以防止环境影响。标准子弹。}
{12200}{}{9毫米毛瑟}
{12201}{}{一把毛瑟M/96，使用9x19毫米帕拉贝鲁姆弹药。状态极佳，极其精准。最低力量要求：3。}
{12300}{}{心灵屏蔽器}
{12301}{}{一个奇怪的装置，由一种奇特的技术制造。}
{12400}{}{啤酒}
{12401}{}{某种自酿啤酒。}
{12500}{}{烈酒}
{12501}{}{一种战前时代的古老烈酒。}
{12600}{}{水壶}
{12601}{}{用于储存和保存水或其他液体的容器。}
{12700}{}{绳索}
{12701}{}{一根结实粗壮的绳子，长度约45英尺。}
{12800}{}{脚锁箱}
{12801}{}{普通的脚锁箱。可以存放物品，放在床脚，可以上锁。}
{12900}{}{脚锁箱}
{12901}{}{普通的脚锁箱。可以存放物品，放在床脚，可以上锁。}
{13000}{}{脚锁箱}
{13001}{}{普通的脚锁箱。可以存放物品，放在床脚，可以上锁。}
{13100}{}{脚锁箱}
{13101}{}{普通的脚锁箱。可以存放物品，放在床脚，可以上锁。}
{13200}{}{储物柜}
{13201}{}{一个储物容器。}
{13300}{}{储物柜}
{13301}{}{一个储物容器。}
{13400}{}{储物柜}
{13401}{}{一个储物容器。}
{13500}{}{储物柜}
{13501}{}{一个储物容器。}
{13600}{}{储物柜}
{13601}{}{一个储物容器。}
{13700}{}{储物柜}
{13701}{}{一个储物容器。}
{13800}{}{储物柜}
{13801}{}{一个储物容器。}
{13900}{}{储物柜}
{13901}{}{一个储物容器。}
{14000}{}{通行卡}
{14001}{}{一张安全通行卡。仍然可以正常使用。}
{14100}{}{大教堂之子徽章}
{14101}{}{一个形状如大教堂之子标志的徽章。你注意到一侧有凸起和凹陷，几乎让你联想到钥匙。}
{14200}{}{大教堂之子徽章}
{14201}{}{一个形状如大教堂之子标志的徽章。你注意到一侧有凸起和凹陷，几乎让你联想到钥匙。}
{14300}{}{狙击步枪}
{14301}{}{一把DKS-501狙击步枪。优秀的远程射击武器。原为.308口径，这把改为更常见的.223口径。最低力量需求：5。}
{14400}{}{超级治疗针}
{14401}{}{一种高级治疗化学品。非常强效。由于使用的化学物质性质强烈，超级治疗针在一段时间后会造成少量伤害。}
{14500}{}{书架}
{14501}{}{一个木制书架。}
{14600}{}{书架}
{14601}{}{一个木制书架。}
{14700}{}{书架}
{14701}{}{一个木制书架。}
{14800}{}{书架}
{14801}{}{一个木制书架。}
{14900}{}{书架}
{14901}{}{一个木制书架。}
{15000}{}{书架}
{15001}{}{一个木制书架。}
{15100}{}{书架}
{15101}{}{一组木制书架。}
{15200}{}{书架}
{15201}{}{一组木制书架。}
{15300}{}{书架}
{15301}{}{一组木制书架。}
{15400}{}{书架}
{15401}{}{一组木制书架。}
{15500}{}{书架}
{15501}{}{一组木制书架。}
{15600}{}{书架}
{15601}{}{一组木制书架。}
{15700}{}{工作台}
{15701}{}{一个工作台。是的，就是那种普通的老式工作台。看起来也很不错。}
{15800}{}{工具板}
{15801}{}{这个板子上方悬挂着各种工具，是受欢迎的工作台的标配。}
{15900}{}{燃烧瓶}
{15901}{}{一种自制的燃烧性手榴弹。最低力量要求：3。}
{16000}{}{电击棒}
{16001}{}{瓦兹电子公司出品的农夫好帮手型号电击棒。使用小型能量电池供电。最低力量要求：4。}
{16100}{}{红骑士BB枪}
{16101}{}{一把红骑士BB枪。经典之作。最低力量要求：3。}
{16200}{}{红骑士限量版BB枪}
{16201}{}{红骑士BB枪的限量版。真正的经典。最低力量要求：3。}
{16300}{}{BB弹}
{16301}{}{一包战前的BB弹。状况极佳。不锈钢材质。}
{16400}{}{兄弟会磁带}
{16401}{}{一张关于钢铁兄弟会的全息磁盘。}
{16500}{}{鬣蜥小吃摊}
{16501}{}{鲍勃的鬣蜥肉小吃的家。新鲜烤制的鬣蜥有什么不爱的呢？}
{16600}{}{桌子}
{16601}{}{一张普通的桌子。用来把东西放离地面。}
{16700}{}{桌子}
{16701}{}{一张普通的桌子。用来把东西放离地面。}
{16800}{}{物品}
{16801}{}{这些是杂项物品，也被称为“东西”。}
{16900}{}{物品}
{16901}{}{这些是杂项物品，也被称为“东西”。}
{17000}{}{物品}
{17001}{}{这些是杂项物品，也被称为“东西”。}
{17100}{}{物品}
{17101}{}{这些是杂项物品，也被称为“东西”。}
{17200}{}{物品}
{17201}{}{这些是杂项物品，也被称为“东西”。}
{17300}{}{物品}
{17301}{}{这些是杂项物品，也被称为“东西”。}
{17400}{}{物品}
{17401}{}{这些是杂项物品，也被称为“东西”。}
{17500}{}{物品}
{17501}{}{这些是杂项物品，也被称为“东西”。}
{17600}{}{物品}
{17601}{}{这些是杂项物品，也被称为“东西”。}
{17700}{}{物品}
{17701}{}{这些是杂项物品，也被称为“东西”。}
{17800}{}{物品}
{17801}{}{这些是杂项物品，也被称为“东西”。}
{17900}{}{物品}
{17901}{}{这些是杂项物品，也被称为“东西”。}
{18000}{}{箱子}
{18001}{}{一个装满普通物品的木箱。}
{18100}{}{桌子}
{18101}{}{一张普通的桌子。看过一张桌子，就等于看过所有桌子。}
{18200}{}{桌子}
{18201}{}{一张普通的桌子。}
{18300}{}{桌子}
{18301}{}{一张普通的桌子。}
{18400}{}{桌子}
{18401}{}{一张普通的桌子。}
{18500}{}{桌子}
{18501}{}{一张普通的桌子。}
{18600}{}{桌子}
{18601}{}{一张普通的桌子。}
{18700}{}{桌子}
{18701}{}{一张普通的桌子。}
{18800}{}{储物柜}
{18801}{}{一个储物柜。}
{18900}{}{储物柜}
{18901}{}{一个储物柜。}
{19000}{}{FEV磁盘}
{19001}{}{一张包含医疗信息的全息磁带。可以用来将信息输入到你的PIPBoy中。}
{19100}{}{安全磁盘}
{19101}{}{一张标签上写有“安全日志”的全息磁带。你可以用它将其中的数据传输到你的PIPBoy。}
{19200}{}{阿尔法实验磁盘}
{19201}{}{这张全息磁带的标签上写着：“阿尔法实验日志”}
{19300}{}{德尔塔实验磁盘}
{19301}{}{这张全息磁带的标签上写着：“德尔塔实验日志”}
{19400}{}{Vree的实验磁盘}
{19401}{}{这张全息磁带已更新了来自钢铁兄弟会的Vree的医学证据。可以用来将数据传输到你的PIPBoy。}
{19500}{}{兄弟会荣誉守则}
{19501}{}{一张全息磁带，上面刻有钢铁兄弟会的粗略标志。使用磁带将数据传输到你的PIPBoy。}
{19600}{}{变种人传输}
{19601}{}{这张全息带似乎是用来从无线电录制音频数据的。使用这张磁带将信息传输到你的PIPBoy。}
{19700}{}{盒子}
{19800}{}{盒子}
{19900}{}{盒子}
{20000}{}{盒子}
{20100}{}{盒子}
{20200}{}{盒子}
{20300}{}{盒子}
{20400}{}{盒子}
{20500}{}{信号弹}
{20501}{}{一个信号弹。可以在短时间内产生光亮。纸张有些磨损，但总体状况良好。它已经点燃。}
{20600}{}{炸药}
{20601}{}{一种高爆炸药，由硝化甘油与吸收性物质矽藻土混合而成。包括一个正在滴答作响的定时器。}
{20700}{}{盖革计数器}
{20701}{}{一台瓦茨电子C-Radz型号的盖革计数器。用于检测辐射场的存在和强度。它已开启。}
{20800}{}{运动传感器}
{20801}{}{一台瓦茨电子C-U型号的运动传感器。使用调频雷达设备检测数米范围内的生物材料运动。它已开启。}
{20900}{}{塑胶炸药}
{20901}{}{一块Cordex军用品牌的塑胶炸药。非常稳定，破坏力极强。包括一个正在滴答作响的定时器。}
{21000}{}{潜行者}
{21001}{}{一台罗博公司Stealth Boy 3001个人隐形装置。生成一个调制场，将物体一侧反射的光传输到另一侧。}
{21100}{}{骨骸}
{21101}{}{你看到艾德。艾德死了。}
{21200}{}{坦迪}
{21201}{}{你正在为坦迪的释放进行交易。}
{21300}{}{吉兹莫的遗体}
{21301}{}{吉兹莫，废城的前犯罪头目，已经死了。而且相当臭。}
{21400}{}{桌子}
{21401}{}{一张桌子。经过进一步观察，你决定它仍然是一张桌子。}
{21500}{}{钢铁兄弟会历史}
{21501}{}{一张全息磁带，包含与钢铁兄弟会相关的信息。可以用于将信息输入到你的PIPBoy 2000。}
{21600}{}{马克森的历史}
{21700}{}{马克森的日志}
{21800}{}{轻度治疗}
{21801}{}{如果你想要轻度治疗，可以选择这个选项进行交易。}
{21900}{}{中度治疗}
{21901}{}{如果你想要中度治疗，可以选择这个选项进行交易。}
{22000}{}{重度治疗}
{22001}{}{如果你需要大量护理和重度治疗，可以选择这个选项进行交易。}
{22100}{}{安全卡}
{22101}{}{一张安全等级编码在简单电子设备中的钥匙卡。}
{22200}{}{场地开关}
{22201}{}{一个电子传输设备，带有一个非常简单且大的切换按钮。看起来是为非常大的手设计并最近制作的。}
{22300}{}{黄色通行卡}
{22301}{}{一把电子安全钥匙，颜色编码为黄色。}
{22400}{}{小雕像}
{22401}{}{你认为这可能是“Pip Boy”的雕刻，但不能确定。}
{22500}{}{你完全不知道}
{22501}{}{经过进一步检查，你仍然不知道这是什么。}
{22600}{}{一盒面条}
{22601}{}{你不知道“速食意大利面”是什么意思。}
{22700}{}{某种小而布满灰尘的盒子}
{22701}{}{一个电视晚餐。你不确定，但这绝对不能吃。你不太确定它是否曾经能吃。}
{22800}{}{技术手册}
{22801}{}{一本关于T-51b动力装甲的技术维修手册。}
{22900}{}{小型机械部件}
{22901}{}{你看到一个收缩动机器。这个不寻常的机械部件非常小。}
{23000}{}{避难所记录}
{23001}{}{来自避难所计算机系统的事件和重要记录汇编。可能已损坏。}
{23100}{}{军事基地安全代码}
{23101}{}{}
{23200}{}{强化动力装甲}
{23201}{}{一套T-51b动力装甲。硬化处理提升了这套高科技装甲系统的防御能力。}
{23300}{}{涡轮等离子步枪}
{23301}{}{一把改装的温彻斯特P94等离子步枪。等离子弹室经过改装，加速了弹丸的形成过程。最低力量需求：6。}
{23400}{}{尖刺指节套}
{23401}{}{经典黄铜指节套的改良版。尖刺指节套在徒手战斗中能造成更大伤害，撕裂对手的肌肤。最低力量需求：1。}
{23500}{}{动力拳套}
{23501}{}{来自BeatCo的“大力神”动力拳套。被许多人认为是徒手战斗的终极武器。其他人则感到畏惧。由小型能量电池供电。最低力量需求：1。}
{23600}{}{战斗刀}
{23601}{}{高品质战斗刀，Stallona由SharpWit公司出品。刀刃保证在十年以上的使用中保持锋利！最低力量需求：2。}
{23700}{}{化学期刊}
{23701}{}{一堆关于化学领域的随机文献。分子化学的论文尤为有趣。}
{23800}{}{监管者传输}
{23801}{}{一份音频传输的全息录音带。}
{23900}{}{兄弟会装甲}
{23901}{}{一种高级版战斗装甲。钢铁兄弟会对标准版进行了多项改进。}
{24000}{}{特斯拉装甲}
{24001}{}{这套闪亮的装甲提供了对能量攻击的卓越保护。三根特斯拉吸引线圈棒能分散大部分定向能量攻击。}
{24100}{}{.223手枪}
{24101}{}{一把经过改装并缩短的.223步枪，变成手枪。这是一把独一无二的枪械，显然是用爱与技巧制造的。最低力量需求：5。}
{24200}{}{战斗霰弹枪}
{24201}{}{一把温彻斯特城市杀手12号战斗霰弹枪，牛头犬款。状态极佳，具有可选的沙漠战争环境密封改装，增加可靠性。最低力量需求：5。}
