{100}{}{燃烧的金属桶}
{101}{}{桶里有燃烧的纸张和其他燃烧的废物。}
{200}{}{木门}
{201}{}{一扇木制的门。}
{300}{}{木桌}
{301}{}{一张木制的桌子。}
{400}{}{木桌}
{401}{}{一张木制的桌子。}
{500}{}{金属桶}
{501}{}{一个旧的钢制桶。}
{600}{}{金属桶}
{601}{}{一个旧的钢制桶。}
{700}{}{轮胎堆}
{701}{}{一堆古老的橡胶轮胎。它们因高温硫化变硬。}
{800}{}{安全门}
{801}{}{这扇门看起来非常安全。它能防御外界的元素和危险生物。}
{900}{}{计算机}
{901}{}{一个避难所的计算机终端，连接到主计算机。}
{1000}{}{柱子}
{1001}{}{一个支撑柱，为整个建筑群提供应力缓解。}
{1100}{}{计算机}
{1101}{}{一个避难所的计算机终端，连接到主计算机。}
{1200}{}{计算机}
{1201}{}{一个避难所的计算机终端，连接到主计算机。}
{1300}{}{显示器}
{1301}{}{一个绿色屏幕的显示器，显示各种数据。偶尔会出现几个字节。}
{1400}{}{显示器}
{1401}{}{一个绿色屏幕的显示器，显示各种数据。}
{1500}{}{全息生成器}
{1501}{}{一个大型THT娱乐磁带播放器。80年来没有新电影制作。}
{1600}{}{屏幕}
{1601}{}{一系列的三个显示屏，显示着各种数据。}
{1700}{}{屏幕}
{1701}{}{三个显示屏的组合，展示来自避难所的各种数据。}
{1800}{}{门}
{1801}{}{仔细观察后，它仍然是一扇门。}
{1900}{}{门}
{1901}{}{仔细观察后，它仍然是一扇门。}
{2000}{}{通风口}
{2001}{}{一个通风口，为整个避难所综合体提供经过处理和清洁的空气。}
{2100}{}{通风口}
{2101}{}{一个通风口，为整个避难所综合体提供经过处理和清洁的空气。}
{2200}{}{13号避难所门}
{2201}{}{一个沉重的门，建造时考虑到能承受各种损坏和冲击。}
{2300}{}{13号避难所门}
{2301}{}{一个沉重的门，建造时考虑到能承受各种损坏和冲击。}
{2400}{}{基座}
{2401}{}{一个液压升降装置，用于为监督者的平台提供支持、电力和通信线路。}
{2500}{}{显示器}
{2501}{}{一台显示器看多了，它们都差不多。}
{2600}{}{显示器}
{2601}{}{一个电脑显示器，显示着各种数据。}
{2700}{}{栅格}
{2701}{}{标准避难所科技栅格，为监督者的基座提供基础。}
{2800}{}{管道}
{2801}{}{一些管道。仔细观察后，它们仍然是管道。}
{2900}{}{通风口}
{2901}{}{标准避难所科技通风系统。}
{3000}{}{柱子}
{3001}{}{标准避难所科技柱子支撑系统。}
{3100}{}{柱子}
{3101}{}{标准的避难所科技支柱系统。}
{3200}{}{通风口}
{3201}{}{标准的避难所科技通风系统。}
{3300}{}{通风口}
{3301}{}{标准的避难所科技通风系统。}
{3400}{}{床}
{3401}{}{一张床，经过之前的睡眠环境后，看起来相当舒适。}
{3500}{}{床}
{3501}{}{标准床，看起来很舒服。}
{3600}{}{床}
{3601}{}{标准床，看起来很舒服。}
{3700}{}{床}
{3701}{}{标准床，看起来很舒服。}
{3800}{}{避难所电梯}
{3801}{}{这是电梯，可以在避难所内上下楼层。}
{3900}{}{椅子}
{3901}{}{这是一把椅子。可惜你没有时间坐下来休息。}
{4000}{}{椅子}
{4001}{}{这是一把椅子。可惜你没有时间坐下来休息。}
{4100}{}{椅子}
{4101}{}{这是一把椅子。可惜你没有时间坐下来休息。}
{4200}{}{椅子}
{4201}{}{这是一把椅子。可惜你没有时间坐下来休息。}
{4300}{}{显示器}
{4301}{}{电脑显示器，显示着各种数据。}
{4400}{}{显示器}
{4401}{}{电脑显示器，显示着各种数据。}
{4500}{}{显示器}
{4501}{}{电脑显示器，显示着各种数据。}
{4600}{}{显示器}
{4601}{}{一台电脑显示器，显示着各种数据。}
{4700}{}{显示器}
{4701}{}{一台电脑显示器，显示着各种数据。}
{4800}{}{显示器}
{4801}{}{一台电脑显示器，显示着各种数据。}
{4900}{}{出口网格地图标记}
{4901}{}{出口网格地图标记}
{5000}{}{空气处理单元}
{5001}{}{一个空气处理单元净化旧空气，为设施提供新鲜空气。这个坏了。}
{5100}{}{椅子}
{5101}{}{这是一把椅子。可惜你没有时间坐下来放松。}
{5200}{}{椅子}
{5201}{}{这是一把椅子。可惜你没有时间坐下来放松。}
{5300}{}{椅子}
{5301}{}{这是一把椅子。可惜你没有时间坐下来放松。}
{5400}{}{椅子}
{5401}{}{这是一把椅子。可惜你没有时间坐下来放松。}
{5500}{}{视频显示单元}
{5501}{}{这个视频显示单元有各种电脑显示器和其他屏幕。看起来非常繁忙。}
{5600}{}{视频显示单元}
{5601}{}{这个视频显示单元有各种电脑显示器和其他屏幕。看起来非常繁忙。}
{5700}{}{椅子}
{5701}{}{这是一把椅子。看起来非常舒适。}
{5800}{}{椅子}
{5801}{}{这是一把椅子。看起来非常舒适。}
{5900}{}{椅子}
{5901}{}{这是一把椅子。看起来非常舒适。}
{6000}{}{椅子}
{6001}{}{这是一把椅子。看起来非常舒适。}
{6100}{}{桌子}
{6101}{}{这是一张桌子。在桌子出现之前，人们只能把东西放在地上。}
{6200}{}{桌子}
{6201}{}{这绝对是一张桌子。}
{6300}{}{风滚草}
{6301}{}{这是风滚草。当然，你以前从未见过真正的风滚草。最好密切注意它。}
{6400}{}{仙人掌}
{6401}{}{这个仙人掌看起来没什么特别的。}
{6500}{}{仙人掌}
{6501}{}{这个仙人掌看起来没什么重要的。}
{6600}{}{树}
{6601}{}{一棵枯树。这里什么都长不好。}
{6700}{}{秘密阻挡六边形}
{6701}{}{如果你能看到这个，请责怪技术设计师。}
{6800}{}{避难所楼梯}
{6801}{}{一组楼梯。}
{6900}{}{石笋}
{6901}{}{岩石地面的自然延伸。}
{7000}{}{石笋}
{7001}{}{岩石地面的自然延伸。}
{7100}{}{血迹}
{7101}{}{这个血迹没什么特别之处。当然，除了这里曾有人或东西死去。}
{7200}{}{岩石柱}
{7201}{}{这根厚岩石柱从地面延伸到天花板。}
{7300}{}{岩石柱}
{7301}{}{这根细岩石柱从地面延伸到天花板。}
{7400}{}{岩石}
{7401}{}{你研究了一会儿这些岩石，但它们从未移动。}
{7500}{}{岩石}
{7501}{}{你密切注意这些岩石，以防它们移动攻击你。}
{7600}{}{汽车墙地板}
{7601}{}{已移除}
{7700}{}{汽车墙屋顶}
{7701}{}{已移除}
{7800}{}{岩石}
{7801}{}{一大堆岩石。看起来是这个地区的特产。}
{7900}{}{岩石}
{7901}{}{一小堆岩石。}
{8000}{}{岩石}
{8001}{}{一小堆岩石。}
{8100}{}{岩石}
{8101}{}{一大堆岩石。}
{8200}{}{骨头}
{8201}{}{一大堆漂白的动物骨头。至少，你认为这些骨头都是动物的……}
{8300}{}{骨头}
{8301}{}{一大堆漂白的动物骨头。至少，你认为这些骨头都是动物的……}
{8400}{}{骨头}
{8401}{}{一大堆漂白的骨头。你无法辨认这些死去生物的种类。}
{8500}{}{骨头}
{8501}{}{你觉得这些可能是有角袋鼠的骨头，但不能确定。它们风化得太严重了，无法做出最终判断。}
{8600}{}{骨头}
{8601}{}{你看到一头双头牛的骨头。}
{8700}{}{大门}
{8701}{}{一个木制大门。它开了，又关上，又开了，又关上，反复无常……}
{8800}{}{金属冰箱}
{8801}{}{已移除}
{8900}{}{金属冰箱}
{8901}{}{已移除}
{9000}{}{岩石}
{9001}{}{一大堆岩石。它们就那样放着，看起来很危险。}
{9100}{}{岩石}
{9101}{}{一大堆岩石。仔细看，你能在石头的侧面看到小老头的面孔。}
{9200}{}{岩石}
{9201}{}{岩石，岩石，岩石！到处都是岩石！}
{9300}{}{岩石}
{9301}{}{一小堆岩石。}
{9400}{}{酒吧}
{9401}{}{这个现代版的酒精蒸馏器可以勉强称为微型酿酒厂。}
{9500}{}{椅子}
{9501}{}{一个腐烂的旧椅子，由古老的汽车座椅制成。}
{9600}{}{椅子}
{9601}{}{一个臭烘烘的旧椅子，曾经是汽车座椅。弹簧已经失去了弹性。}
{9700}{}{椅子}
{9701}{}{一个腐烂、臭烘烘的旧椅子，用砖块支撑着。看起来很不舒服。}
{9800}{}{沙发}
{9801}{}{一个腐烂、臭烘烘的旧椅子，用砖块支撑着。看起来很不舒服。}
{9900}{}{沙发}
{9901}{}{一个看起来非常不舒服的坐具，有时被称为沙发。}
{10000}{}{沙发}
{10001}{}{一个看起来非常不舒服的坐具，有时被称为沙发。}
{10100}{}{轮胎}
{10101}{}{一只旧橡胶轮胎，坐落在杂草丛中。}
{10200}{}{灌木}
{10201}{}{某种沙漠杂草。}
{10300}{}{灌木}
{10301}{}{某种沙漠杂草。}
{10400}{}{灌木}
{10401}{}{某种沙漠杂草。}
{10500}{}{灌木}
{10501}{}{某种沙漠杂草。}
{10600}{}{废品}
{10601}{}{这是一个锈迹斑斑的车门，靠在一个锈蚀的金属桶上。满满的都是锈。}
{10700}{}{废品}
{10701}{}{一个破损的马桶，半埋在沙子里。生活就是这么糟糕，然后你就死了。}
{10800}{}{杂草}
{10801}{}{某种沙漠灌木。如果它曾经生长过，现在已经不再生长了。}
{10900}{}{废品}
{10901}{}{一个车胎，埋在沙子里。周围堆着一些小块木头。}
{11000}{}{石头}
{11001}{}{仔细观察后，你认为这些可能实际上是一些石化木头。}
{11100}{}{泥土}
{11101}{}{一小堆泥土，上面长着一根枯死的杂草。}
{11200}{}{泥土}
{11201}{}{一小堆泥土。}
{11300}{}{泥土}
{11301}{}{一小堆泥土。}
{11400}{}{泥土}
{11401}{}{一小堆泥土。}
{11500}{}{杂草}
{11501}{}{一小堆泥土，上面长着一根干枯的杂草。}
{11600}{}{废品}
{11601}{}{一块扭曲的锈蚀金属。}
{11700}{}{废品}
{11701}{}{一些破碎的木块。}
{11800}{}{废品}
{11801}{}{一小堆杂乱的废品。}
{11900}{}{泥土}
{11901}{}{一小堆泥土。}
{12000}{}{泥土}
{12001}{}{一小堆泥土。}
{12100}{}{泥土}
{12101}{}{一小堆泥土。}
{12200}{}{泥土}
{12201}{}{一小堆泥土。}
{12300}{}{泥土}
{12301}{}{一小堆泥土。}
{12400}{}{泥土}
{12401}{}{一小堆泥土。}
{12500}{}{杂草}
{12501}{}{一株普通的沙漠杂草。}
{12600}{}{杂草}
{12601}{}{一株普通的沙漠杂草。}
{12700}{}{杂草}
{12701}{}{一株普通的沙漠杂草。}
{12800}{}{}
{12900}{}{墙壁}
{13000}{}{墙壁}
{13100}{}{墙壁}
{13200}{}{墙壁}
{13300}{}{墙壁}
{13400}{}{墙壁}
{13500}{}{排水口}
{13501}{}{这个下水道口散发出一股恶臭。过了一会儿，气味似乎没那么难闻了。}
{13600}{}{排水口}
{13601}{}{你勉强能看出排水口的格栅后有些动静。你看到一些小红眼睛在盯着你。是老鼠的眼睛。}
{13700}{}{排水口}
{13701}{}{从这个排水口传来汩汩的流水声，还有一股极其恶心的臭味。}
{13800}{}{排水口}
{13801}{}{从这个排水口传来汩汩的流水声，还有一股极其恶心的气味。}
{13900}{}{梯子}
{13901}{}{这是一架旧的、相当摇晃的梯子。看起来它几乎无法承受你的重量。}
{14000}{}{下水道口}
{14001}{}{看起来像是通往下水道系统的入口。}
{14100}{}{光源}
{14200}{}{门}
{14201}{}{这看起来像是一扇标准的避难所门，但已受损，可能被烧过。然而，它仍然可以使用。}
{14300}{}{门}
{14301}{}{这看起来像是一扇标准的避难所门，但已受损，可能被烧过。然而，它仍然可以使用。}
{14400}{}{盖子}
{14401}{}{一个沉重的井盖。看起来状况良好，最近被移动过。}
{14500}{}{洞}
{14501}{}{这扇门上被炸出了一个大洞。}
{14600}{}{洞}
{14601}{}{这扇门上被炸出了一个大洞。}
{14700}{}{防弹玻璃}
{14701}{}{完全无法打破的玻璃。别试了。}
{14800}{}{防弹玻璃}
{14801}{}{完全无法打破的玻璃。别试了。}
{14900}{}{防弹玻璃}
{14901}{}{完全无法打破的玻璃。别试了。}
{15000}{}{防弹玻璃}
{15001}{}{完全无法打破的玻璃。别试了。}
{15100}{}{门}
{15101}{}{这扇门是高科技结构的产物。它通过旋转构成门的三个部分来扩张打开。}
{15200}{}{门}
{15201}{}{这扇门是高科技结构的产物。它通过旋转构成门的三个部分来扩张打开。}
{15300}{}{门}
{15301}{}{这扇门上刻有钢铁兄弟会的标志。}
{15400}{}{门}
{15401}{}{这扇门上刻有钢铁兄弟会的标志。}
{15500}{}{电梯}
{15501}{}{这是一个兄弟会电梯的内部。干净得一尘不染！}
{15600}{}{电梯}
{15601}{}{这是一个兄弟会电梯的内部。干净得一尘不染！}
{15700}{}{标记}
{15701}{}{这是钢铁兄弟会的标志。这个标记告诉废土上的人们这是他们的地盘，立刻离开。}
{15800}{}{显示器}
{15801}{}{你看到一个电脑显示器。它是由兄弟会技术制造的。}
{15900}{}{显示器}
{15901}{}{你看到一个电脑显示器。它是由兄弟会技术制造的。}
{16000}{}{电脑}
{16001}{}{这是一个电脑内存数据库。显然是兄弟会的技术。}
{16100}{}{电脑}
{16101}{}{这是一个电脑内存数据库。显然是兄弟会的技术。}
{16200}{}{电脑}
{16201}{}{一个高科技电脑，使用现代的卷对卷存储设备，而不是过时的打孔卡片。}
{16300}{}{电脑}
{16301}{}{一个高科技电脑，使用现代的卷对卷存储设备，而不是过时的打孔卡片。}
{16400}{}{显示器}
{16401}{}{你看到一个电脑显示器。它是由兄弟会技术制造的。}
{16500}{}{显示器}
{16501}{}{你看到一个电脑显示器。它是由兄弟会技术制造的。}
{16600}{}{电线}
{16601}{}{某种电脑电线。}
{16700}{}{电线}
{16701}{}{某种电脑电线。}
{16800}{}{电线}
{16801}{}{某种电脑电线。}
{16900}{}{柱子}
{16901}{}{一个支撑柱。}
{17000}{}{柱子}
{17001}{}{一个支撑柱。}
{17100}{}{门禁电脑}
{17101}{}{这个电脑控制着大型避难所门。你需要输入特定的访问代码才能使用。}
{17200}{}{赌场招牌}
{17201}{}{看起来是吉兹莫赌场的广告。}
{17300}{}{13号避难所外门}
{17301}{}{这扇大门是避难所与外界的连接。}
{17400}{}{13号避难所外门}
{17401}{}{这扇大门是避难所与外界的连接。}
{17500}{}{赌场招牌}
{17501}{}{招牌的这一部分包含一个电动机，缓慢地旋转着附着的霓虹灯招牌。}
{17600}{}{向下箭头}
{17700}{}{向上箭头}
{17800}{}{箱子}
{17900}{}{箱子}
{18000}{}{箱子}
{18100}{}{电梯顶部}
{18101}{}{你正在看电梯的一部分。}
{18200}{}{电脑终端}
{18201}{}{这是一个哑终端，通过电缆连接到大型计算机。它是兄弟会的技术。}
{18300}{}{电脑终端}
{18301}{}{这是一个哑终端，通过电缆连接到大型计算机。它是兄弟会的技术。}
{18400}{}{徽章}
{18401}{}{这是兄弟会的象征。齿轮代表他们的工程知识，剑代表他们保卫自己的意志，翅膀象征着振奋的希望。}
{18500}{}{徽章}
{18501}{}{这是兄弟会的象征。齿轮代表他们的工程知识，剑代表他们保卫自己的意志，翅膀象征着振奋的希望。}
{18600}{}{“一”层标志}
{18601}{}{你觉得这可能意味着你在兄弟会的一层。}
{18700}{}{“二”层标志}
{18701}{}{你现在在钢铁兄弟会的第二层。}
{18800}{}{第三层标志}
{18801}{}{这意味着你现在在钢铁兄弟会的第三层。}
{18900}{}{第四层标志}
{18901}{}{你现在应该在钢铁兄弟会的第四层。}
{19000}{}{双层床}
{19001}{}{一张军用风格的双层床。看起来非常不舒服。不过床单绷得很紧，能弹起硬币。}
{19100}{}{双层床}
{19101}{}{一张军用风格的双层床。看起来非常不舒服。不过床单绷得很紧，能弹起硬币。}
{19200}{}{双层床}
{19201}{}{一张军用风格的双层床。看起来非常不舒服。不过床单绷得很紧，能弹起硬币。}
{19300}{}{箱子}
{19400}{}{Nuka-Cola 自动售货机}
{19401}{}{这台机器侧面的广告宣传他们的热门汽水。}
{19500}{}{墙壁}
{19600}{}{地板门}
{19601}{}{看起来是个完好的地板门。}
{19700}{}{井盖}
{19701}{}{这个井盖的梯子通向下方的黑暗。哦，好可怕。}
{19800}{}{祭坛}
{19801}{}{这是一个祭坛。}
{19900}{}{讲台}
{19901}{}{人们站在后面讲话。看起来有个小地方可以放准备好的演讲稿。}
{20000}{}{长椅}
{20001}{}{这看起来和你想象的一样。这个长椅没什么特别。}
{20100}{}{路标}
{20101}{}{这个路标上的标志看起来有点生锈。}
{20200}{}{路标}
{20201}{}{这个路标上的标志看起来有点生锈。}
{20300}{}{路标}
{20301}{}{这根柱子上的标志看起来有些生锈了。}
{20400}{}{路标}
{20401}{}{这根柱子上的标志看起来有些生锈了。}
{20500}{}{路标}
{20501}{}{这根柱子上的标志看起来有些生锈了。}
{20600}{}{旧床垫}
{20601}{}{一个破旧的床垫。你觉得里面似乎有某种小虫子在作怪。}
{20700}{}{旧床垫}
{20701}{}{即使你一个人睡在这上面，也不会是一个人。}
{20800}{}{床}
{20801}{}{一个临时拼凑的床。材料是从其他地方捡来的。}
{20900}{}{床}
{20901}{}{一个临时拼凑的床。材料是从其他地方捡来的。}
{21000}{}{床}
{21001}{}{这张床曾经的日子（和夜晚）要好得多。}
{21100}{}{床}
{21101}{}{仔细观察后，你确定这些床单已经很久很久没有换过了。}
{21200}{}{床}
{21201}{}{这个饱经风霜的床具上有几个来源可疑的污渍。}
{21300}{}{床}
{21301}{}{这张床使用过度，损耗严重。似乎有什么东西钻进了床垫中然后死去了。}
{21400}{}{书柜}
{21500}{}{书柜}
{21600}{}{书柜}
{21700}{}{书柜}
{21800}{}{书柜}
{21900}{}{书柜}
{22000}{}{箱子}
{22001}{}{这些木箱已经因为风雨侵蚀而快要散架。}
{22100}{}{箱子}
{22101}{}{你没有发现这些木箱有什么值得一提的细节。}
{22200}{}{箱子}
{22201}{}{你一定很闲，才会仔细查看这些腐烂的垃圾。}
{22300}{}{箱子}
{22301}{}{这些木箱因为风吹日晒已经快要散架了。}
{22400}{}{汽车}
{22401}{}{这辆车状况糟糕透顶。你想不出任何修复的方法。}
{22500}{}{汽车}
{22501}{}{这块锈迹斑斑的废铁无法修复。}
{22600}{}{汽车}
{22601}{}{你确定这辆车再也无法行驶了。真的。}
{22700}{}{汽车}
{22701}{}{这堆废铁永远无法再次启动。}
{22800}{}{汽车}
{22801}{}{即便年度机械师突然出现在你身边，你们也无法修好这堆锈迹斑斑的废铁。}
{22900}{}{椅子}
{22901}{}{一把舒适的椅子。}
{23000}{}{椅子}
{23001}{}{这把椅子看起来经历过更好的时光。}
{23100}{}{椅子}
{23101}{}{这把椅子发霉又恶心。你可以想象，它也很臭。}
{23200}{}{椅子}
{23201}{}{这把椅子正在快速散架。}
{23300}{}{椅子}
{23301}{}{如果有人给你很多瓶盖，并且你穿上钢裤子，你可能会考虑坐在这把椅子上。}
{23400}{}{椅子}
{23401}{}{这看起来像是一把旧办公椅，经过多年仍保持良好状态。}
{23500}{}{椅子}
{23501}{}{这是一把旧办公椅。它甚至可能承受一个人的重量。}
{23600}{}{椅子}
{23601}{}{这把办公椅曾经有过辉煌的日子。现在几乎成了废品。}
{23700}{}{椅子}
{23701}{}{这看起来像是殡仪馆里的椅子——毫无生气。}
{23800}{}{桌子}
{23900}{}{桌子}
{24000}{}{衣柜}
{24100}{}{衣柜}
{24200}{}{衣柜}
{24300}{}{消防栓}
{24301}{}{这是一个消防栓。没有避难所的天花板喷头，你可能需要这个来灭火。}
{24400}{}{灯柱}
{24401}{}{这个灯柱看起来还能正常工作。想象一下，在这里居然还有能用的东西。}
{24500}{}{灯柱}
{24501}{}{这个灯柱再也无法工作了。}
{24600}{}{灯柱}
{24601}{}{这是一个工作的灯柱。夜晚，它散发出淡淡的柔光，让你想不起任何东西。}
{24700}{}{灯柱}
{24701}{}{这是一个损坏的灯柱。无法修复。}
{24800}{}{灯柱}
{24801}{}{这个灯具是可用的。}
{24900}{}{灯柱}
{24901}{}{这个灯柱的灯光已经碎得无法修复。}
{25000}{}{灯柱}
{25001}{}{这是一个功能正常的灯柱。}
{25100}{}{大门}
{25101}{}{这个大门的锁已经卡住了，铁栏看起来非常坚固。}
{25200}{}{废品}
{25201}{}{绝对无用的废品，毫无疑问。}
{25300}{}{废品}
{25301}{}{绝对无用的废品，毫无疑问。}
{25400}{}{废品}
{25401}{}{毫无疑问，这绝对是没用的废品。}
{25500}{}{废品}
{25501}{}{毫无疑问，这绝对是没用的废品。}
{25600}{}{废品}
{25601}{}{毫无疑问，这绝对是没用的废品。}
{25700}{}{邮箱}
{25701}{}{邮箱是空的。你感觉它已经空了一段时间了。}
{25800}{}{门}
{25801}{}{一扇制作精良的木门，状况良好。}
{25900}{}{门}
{25901}{}{一扇制作精良的木门，状况良好。}
{26000}{}{门}
{26001}{}{一扇制作精良的木门，状况良好。}
{26100}{}{门}
{26101}{}{一扇制作精良的木门，状况良好。}
{26200}{}{长椅}
{26201}{}{这张木制长椅正在慢慢解体。}
{26300}{}{长椅}
{26301}{}{这张长椅被忽视了，显示出磨损的迹象。}
{26400}{}{长椅}
{26401}{}{一张木制长椅，已经不堪岁月和使用的摧残。}
{26500}{}{报纸机}
{26501}{}{报纸机是空的。}
{26600}{}{报纸机}
{26601}{}{报纸机是空的。}
{26700}{}{报纸机}
{26701}{}{报纸机是空的。}
{26800}{}{报纸机}
{26801}{}{报纸机是空的。}
{26900}{}{报刊机}
{26901}{}{报刊机是空的。}
{27000}{}{报刊机}
{27001}{}{报刊机是空的，看起来曾经装过成人杂志。}
{27100}{}{废料}
{27101}{}{一张破烂不堪的床垫，连老鼠都不愿意在上面睡。}
{27200}{}{废料}
{27201}{}{一张双人床垫，曾经有过比现在好得多的日子。}
{27300}{}{废料}
{27301}{}{一堆腐烂和风化的木头，连它的重量都不值。}
{27400}{}{废料}
{27401}{}{一堆木头，上面嵌着一些生锈的无用钉子。}
{27500}{}{箱子}
{27501}{}{一堆旧纸板箱。你无法相信它们居然存留了这么久。}
{27600}{}{箱子}
{27601}{}{一堆旧纸板箱。}
{27700}{}{废料}
{27701}{}{一些废料，你觉得可能曾经是床垫，但已经被环境摧毁。}
{27800}{}{石头}
{27900}{}{石头}
{28000}{}{石头}
{28100}{}{瓦砾}
{28101}{}{一小堆碎石和石块。小心脚下！}
{28200}{}{水槽}
{28201}{}{一个瓷制水槽，早已失去功能。}
{28300}{}{水槽}
{28301}{}{一个破损的瓷制水槽。水盆里有一小滩褐色的水，漂浮着一只死老鼠。}
{28400}{}{水槽}
{28401}{}{这个水槽无法使用。你可以从中间的大裂缝看出来。}
{28500}{}{水槽}
{28501}{}{一个破损的瓷水槽。水槽里有一小滩褐色的水，漂浮着一只死老鼠。}
{28600}{}{停车标志}
{28601}{}{一个红色的标志，上面用大写字母写着“STOP”。}
{28700}{}{停车标志}
{28701}{}{一个红色的标志，上面用大写字母写着“STOP”。制造后被加上了一个大弹孔。}
{28800}{}{交通信号灯}
{28801}{}{这是一个古老的汽车交通控制装置。}
{28900}{}{交通信号灯}
{28901}{}{这是一个古老的汽车交通控制装置。}
{29000}{}{交通信号灯}
{29001}{}{这是一个古老的汽车交通控制装置。}
{29100}{}{街灯}
{29101}{}{这个街灯在夜幕降临或黑暗区域提供照明。}
{29200}{}{街灯}
{29201}{}{这个街灯在夜幕降临或黑暗区域提供照明。}
{29300}{}{街灯}
{29301}{}{这个街灯在夜幕降临或黑暗区域提供照明。}
{29400}{}{街灯}
{29401}{}{这个街灯在夜幕降临或黑暗区域提供照明。}
{29500}{}{街灯}
{29501}{}{这个街灯本可以在黑暗区域提供照明，如果它没有完全损坏的话。}
{29600}{}{街灯}
{29601}{}{这个街灯本可以在黑暗区域提供照明，如果它没有完全损坏的话。}
{29700}{}{街灯}
{29701}{}{这个街灯本可以在黑暗区域提供照明，如果它没有完全损坏的话。}
{29800}{}{路标}
{29801}{}{这个标志本应标明所处的街道，但字母已经模糊不清。}
{29900}{}{路标}
{29901}{}{这个标志本应标明所处的街道，但字母已经模糊不清。}
{30000}{}{桌子}
{30001}{}{一张木桌，状况中等。}
{30100}{}{桌子}
{30101}{}{一张木桌，状况中等。}
{30200}{}{桌子}
{30201}{}{一张木桌，状况较差。}
{30300}{}{桌子}
{30301}{}{一张木桌，塑料表面，已经坏了一段时间。}
{30400}{}{桌子}
{30401}{}{一张木桌，涂成了呕吐绿色，无法修复。}
{30500}{}{桌子}
{30501}{}{这看起来像是一张旧咖啡桌，离地很低，适合那些特别矮的变种人。}
{30600}{}{桌子}
{30601}{}{这看起来像是一张旧咖啡桌，离地很低，适合那些特别矮的变种人。}
{30700}{}{厕所}
{30701}{}{座位周围的锋利边缘让这里坐着非常不舒服。}
{30800}{}{厕所}
{30801}{}{这个厕所坏了。}
{30900}{}{厕所}
{30901}{}{恶心！上一个使用者没有冲水！}
{31000}{}{厕所}
{31001}{}{这个厕所坏了，女性绝对无法使用。}
{31100}{}{垃圾}
{31101}{}{一些破损的管道半埋在土里。这里没什么重要的，继续走吧。}
{31200}{}{垃圾}
{31201}{}{一些破碎的玻璃和其他损坏的废品。}
{31300}{}{垃圾}
{31301}{}{一些破碎的玻璃和其他损坏的废品。}
{31400}{}{垃圾}
{31401}{}{一根断成两截的管道。看起来是因为生锈而在自重下坍塌的。}
{31500}{}{垃圾桶}
{31501}{}{一个垃圾桶。你几乎看不清标签：保持城市街道清洁！}
{31600}{}{树}
{31601}{}{这是一棵枯树。}
{31700}{}{树}
{31701}{}{一个树桩。没什么特别的。事实上，这可能是你见过的最无聊的东西。}
{31800}{}{树}
{31801}{}{这是一棵枯树。}
{31900}{}{树}
{32000}{}{树}
{32100}{}{树}
{32200}{}{卡车}
{32300}{}{卡车}
{32301}{}{一辆柴油卡车的残骸。这堆金属再也动不了。}
{32400}{}{卡车}
{32401}{}{这辆柴油卡车无可救药。完全无可救药。}
{32500}{}{浴缸}
{32501}{}{这个浴缸已经破裂损坏。}
{32600}{}{浴缸}
{32601}{}{仔细观察后，你意识到你不可能在这个浴缸里洗澡。}
{32700}{}{小便池}
{32701}{}{这只是一个小便池。}
{32800}{}{小便池}
{32801}{}{这只是一个小便池。}
{32900}{}{小便池}
{32901}{}{这只是一个小便池。没什么特别的。}
{33000}{}{小便池}
{33001}{}{这只是一个小便池。没什么特别的。}
{33100}{}{水箱}
{33101}{}{一个大型储液罐。在这种情况下，你认为它是用来储存水的。}
{33200}{}{门}
{33201}{}{一扇木门。没什么特别有趣的地方。}
{33300}{}{门}
{33301}{}{一扇木门。它提供了这个建筑的出入口。}
{33400}{}{墙灯}
{33401}{}{这盏灯看起来状态良好。}
{33500}{}{墙灯}
{33501}{}{一盏坏掉的灯。它不工作也不足为奇。}
{33600}{}{墙灯}
{33601}{}{这盏灯看起来状态良好。}
{33700}{}{墙灯}
{33701}{}{一盏坏掉的灯。它不工作也不足为奇。}
{33800}{}{墙灯}
{33801}{}{这盏灯看起来状态良好。}
{33900}{}{墙灯}
{33901}{}{一盏坏掉的灯。它不工作也不足为奇。}
{34000}{}{墙灯}
{34001}{}{这盏灯看起来状态良好。}
{34100}{}{墙灯}
{34101}{}{一盏坏掉的灯。它不工作也不足为奇。}
{34200}{}{让路标志}
{34201}{}{这是一个用于控制交通流量的标志。}
{34300}{}{让路标志}
{34301}{}{标志已经褪色，但你仍能辨认出“让路”字样。}
{34400}{}{阻挡六边形自动隐形}
{34401}{}{如果你能看到这个，责怪技术设计师吧。}
{34500}{}{地板}
{34600}{}{门}
{34601}{}{一扇华丽的木门。显然是精工细作。}
{34700}{}{长椅}
{34701}{}{这个座位由大块混凝土砖支撑。这不重要，但你就是想看看。}
{34800}{}{楼梯}
{34801}{}{这段楼梯通向上方。}
{34900}{}{楼梯}
{34901}{}{这段楼梯通向上方。}
{35000}{}{楼梯}
{35001}{}{这段楼梯通向上方。}
{35100}{}{楼梯}
{35101}{}{这段楼梯通向上方。}
{35200}{}{楼梯}
{35201}{}{这段楼梯通向上方。}
{35300}{}{楼梯}
{35301}{}{这段楼梯通向上方。}
{35400}{}{楼梯}
{35401}{}{这段楼梯通向上方。}
{35500}{}{楼梯}
{35501}{}{这段楼梯通向上方。}
{35600}{}{楼梯}
{35601}{}{这段楼梯通向下方。}
{35700}{}{墙壁}
{35701}{}{你正在看大教堂的外墙。}
{35800}{}{墙壁}
{35801}{}{你正在看大教堂的外墙。}
{35900}{}{墙壁}
{35901}{}{你正在看大教堂的外墙。}
{36000}{}{墙壁}
{36001}{}{你正在看大教堂的外墙。}
{36100}{}{帘子}
{36101}{}{这个帘子看起来是用原始的方法制作的，但非常实用。}
{36200}{}{帘子}
{36201}{}{这个帘子看起来是用原始的方法制作的，但非常实用。}
{36300}{}{碗}
{36301}{}{一个精心制作的木碗，看起来是用来碾碎和分离谷物的。}
{36400}{}{碗}
{36401}{}{一个精心制作的木碗。}
{36500}{}{锅}
{36501}{}{一个精心制作的锅。}
{36600}{}{植物}
{36601}{}{在你看来，这像是一颗变异的卷心菜。它似乎在温暖的天气中茁壮成长。}
{36700}{}{植物}
{36701}{}{在你看来，这像是一颗变异的卷心菜。它似乎在温暖的天气中茁壮成长。}
{36800}{}{推车}
{36801}{}{一个粗糙但有效的农用推车。}
{36900}{}{植物}
{36901}{}{一根变异的玉米秆。它似乎在这种环境下茁壮成长。}
{37000}{}{植物}
{37001}{}{一根变异的玉米秆。它似乎在这种环境下茁壮成长。}
{37100}{}{植物}
{37101}{}{一根变异的玉米秆。它似乎在这种环境下茁壮成长。}
{37200}{}{锅}
{37201}{}{一个精心制作的陶罐。}
{37300}{}{耙子}
{37301}{}{这把耙子属于它的主人。你甚至想不出它有什么用。}
{37400}{}{耙子}
{37401}{}{这把耙子属于它的主人。你甚至想不出它有什么用。}
{37500}{}{耙子}
{37501}{}{这把耙子属于它的主人。你甚至想不出它有什么用。}
{37600}{}{地毯}
{37601}{}{一块简单的地毯。编织者显然技艺高超。}
{37700}{}{地毯}
{37701}{}{一块简单的地毯。编织者显然技艺高超。}
{37800}{}{地毯}
{37801}{}{一块简单的地毯。编织者显然技艺高超。}
{37900}{}{铲子}
{37901}{}{这把铲子属于它的主人。你甚至想不出它有什么用。}
{38000}{}{铲子}
{38001}{}{这把铲子属于它的主人。你甚至想不出它有什么用。}
{38100}{}{铲子}
{38101}{}{这把铲子属于它的主人。你甚至想不出它有什么用。}
{38200}{}{花瓶}
{38201}{}{一个非常漂亮的陶制花瓶。}
{38300}{}{水井}
{38301}{}{无论你怎么努力，也想不出把这口井搬到避难所的方法。}
{38400}{}{支柱}
{38401}{}{这根支柱用来支撑帐篷。}
{38500}{}{支柱}
{38501}{}{这根支柱用来支撑帐篷。}
{38600}{}{支柱}
{38601}{}{这根支柱用来支撑帐篷。}
{38700}{}{支柱}
{38701}{}{这根支柱用来支撑帐篷。}
{38800}{}{支柱}
{38801}{}{这根支柱用来支撑帐篷。}
{38900}{}{支柱}
{38901}{}{这根支柱用来支撑帐篷。}
{39000}{}{避难所门}
{39001}{}{这扇避难所门现在只是一块沉重的废金属。}
{39100}{}{墙壁}
{39101}{}{开启和关闭沉重避难所门的机制已损坏，无法修复。}
{39200}{}{支架}
{39201}{}{这个支架用来支撑防御墙。}
{39300}{}{支撑架}
{39301}{}{这个支撑架帮助支撑防御墙。}
{39400}{}{支撑架}
{39401}{}{这个支撑架帮助支撑防御墙。}
{39500}{}{支撑架}
{39501}{}{这个支撑架帮助支撑防御墙。}
{39600}{}{金属桶}
{39601}{}{一个生锈的金属桶。它是空的。}
{39700}{}{金属桶}
{39701}{}{从空洞的声音判断，这个桶可能是空的。}
{39800}{}{金属桶}
{39801}{}{从空洞的声音判断，这些桶可能是空的。}
{39900}{}{金属桶}
{39901}{}{从空洞的声音判断，这些桶可能是空的。}
{40000}{}{圆顶}
{40001}{}{你发现一个小标签，上面写着：“51区财产。若发现请归还。”}
{40100}{}{箱子}
{40101}{}{一个木箱。看起来状况还不错。}
{40200}{}{箱子}
{40201}{}{一个简单的木箱。状况相当好。}
{40300}{}{箱子}
{40301}{}{这个简单的木箱因自身重量而坍塌。}
{40400}{}{桌子}
{40401}{}{一张带有电脑的简单桌子。}
{40500}{}{桌子}
{40501}{}{一张带有电脑的简单桌子。}
{40600}{}{门}
{40601}{}{一扇木门，状况尚可。}
{40700}{}{塌方}
{40701}{}{大量岩石，远超出可轻松移动的范围。}
{40800}{}{汽车}
{40801}{}{这辆被淹没的汽车无法修复。}
{40900}{}{汽车}
{40901}{}{这辆汽车有点湿，无法修复。}
{41000}{}{汽车}
{41001}{}{这辆汽车停放得很糟糕。不幸的是，它已无法修复。}
{41100}{}{废品}
{41101}{}{这些废品被污染的海水毁坏了。}
{41200}{}{废品}
{41201}{}{这些废品几乎被冲走了。}
{41300}{}{废品}
{41301}{}{一堆无用的废品。}
{41400}{}{管道}
{41401}{}{这些管道曾用于将燃料从地下储罐输送到车库。它们已经很久没有使用了。}
{41500}{}{管道}
{41501}{}{这些管道曾用于将燃料从地下储罐输送到车库。它们已经很久没有使用了。}
{41600}{}{管道}
{41601}{}{这些管道曾用于将燃料从地下储罐输送到车库。它们已经很久没有使用了。}
{41700}{}{电梯井}
{41701}{}{电梯系统的一部分。}
{41800}{}{电梯井}
{41801}{}{一个深入地下的电梯井。它已被损坏。}
{41900}{}{电梯}
{41901}{}{一个电梯。用来在各层之间上下移动。}
{42000}{}{电梯井}
{42001}{}{一个深入地下的电梯井。它已被损坏。}
{42100}{}{电梯门}
{42101}{}{这扇门通向电梯车厢。如果你想使用电梯，必须先打开这扇门。}
{42200}{}{管道}
{42201}{}{一根金属管。其他细节不重要。}
{42300}{}{泥土}
{42400}{}{箱子}
{42500}{}{箱子}
{42600}{}{箱子}
{42700}{}{箱子}
{42800}{}{岩石}
{42801}{}{一堆岩石。没什么特别的。}
{42900}{}{岩石}
{42901}{}{一堆岩石。没什么特别的。}
{43000}{}{岩石}
{43001}{}{一小堆岩石。对你来说毫无趣味。}
{43100}{}{岩石}
{43101}{}{一小堆岩石。}
{43200}{}{岩石}
{43201}{}{一小堆岩石。}
{43300}{}{岩石}
{43301}{}{一小堆岩石。}
{43400}{}{岩石}
{43401}{}{一小堆岩石。}
{43500}{}{岩石}
{43501}{}{一小堆岩石。}
{43600}{}{避难所大门}
{43601}{}{这个避难所大门和13号避难所的非常相似。门的机制已被禁用。}
{43700}{}{门}
{43701}{}{一扇精致的木门，配有几乎让人着迷的华丽金属支架。}
{43800}{}{门}
{43801}{}{一扇精致的木门，配有几乎让人着迷的华丽金属支架。}
{43900}{}{池}
{43901}{}{某种复杂的设施。你不太确定，但你能看到装有绿色粘液的大池，看起来似乎很重要。}
{44000}{}{池}
{44001}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44100}{}{容器}
{44101}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44200}{}{容器}
{44201}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44300}{}{容器}
{44301}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44400}{}{容器}
{44401}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44500}{}{容器}
{44501}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44600}{}{容器}
{44601}{}{某种复杂的设施。你不太确定，但你可以看到一些装满绿色粘液的大型容器，看起来似乎很重要。}
{44700}{}{墙壁}
{44800}{}{门}
{44801}{}{一道安全门。看起来装甲很厚。}
{44900}{}{核弹头}
{45000}{}{水井}
{45001}{}{无论你怎么努力，也想不出把这口井搬到避难所的方法。}
{45100}{}{掷骰桌}
{45101}{}{这是一张赌博桌。}
{45200}{}{掷骰桌}
{45201}{}{这是一张赌博桌。}
{45300}{}{掷骰桌}
{45301}{}{这是一张赌博桌。}
{45400}{}{掷骰桌}
{45401}{}{这是一张赌博桌。}
{45500}{}{掷骰桌}
{45501}{}{这是一张赌博桌。}
{45600}{}{掷骰桌}
{45601}{}{这是一张赌桌。}
{45700}{}{掷骰子桌}
{45701}{}{这是一张赌桌。}
{45800}{}{掷骰子桌}
{45801}{}{这是一张赌桌。}
{45900}{}{掷骰子桌}
{45901}{}{这是一张赌桌。}
{46000}{}{掷骰子桌}
{46001}{}{这是一张赌桌。}
{46100}{}{石头}
{46101}{}{一块小石头，在这个故事中毫无趣味。}
{46200}{}{石头}
{46300}{}{石头}
{46400}{}{石头}
{46500}{}{老虎机}
{46501}{}{这是一台赌博机。}
{46600}{}{老虎机}
{46601}{}{这是一台赌博机。}
{46700}{}{门口}
{46800}{}{电梯}
{46900}{}{电梯}
{47000}{}{电梯门}
{47100}{}{窗户}
{47101}{}{这个窗户用的是蜡纸而不是玻璃。}
{47200}{}{窗户}
{47201}{}{这个窗户用的是蜡纸而不是玻璃。}
{47300}{}{窗户}
{47301}{}{这个窗户用的是蜡纸而不是玻璃。}
{47400}{}{窗户}
{47401}{}{这个窗户用的是蜡纸而不是玻璃。}
{47500}{}{门}
{47501}{}{这扇大型金属卷门从内部被卡住了。}
{47600}{}{门}
{47601}{}{这扇大型金属卷门从内部被卡住了。}
{47700}{}{门}
{47701}{}{这扇大型金属卷门从内部被卡住了。上面写着仅供装卸。}
{47800}{}{门}
{47801}{}{这扇大型金属卷门从内部被卡住了。}
{47900}{}{门}
{47901}{}{这扇大型金属卷门从内部被卡住了。}
{48000}{}{门}
{48001}{}{这扇大型金属卷门从内部被卡住了。上面写着仅供装卸。}
{48100}{}{门}
{48101}{}{这扇门看起来很像仓库里的门。}
{48200}{}{门}
{48201}{}{这扇门看起来很像仓库里的门。}
{48300}{}{风向标}
{48301}{}{这个简单的风向标帮助阴影沙地的人们研究天气。}
{48400}{}{祭坛}
{48401}{}{一个由涂漆木头制成的简单祭坛。}
{48500}{}{讲台}
{48501}{}{这个讲台很普通，除了正面刻有大教堂之子的标志。}
{48600}{}{祭坛}
{48700}{}{显示器}
{48701}{}{一个大型显示器，仅有黑白显示。即使在室内没有天线，接收效果也不错。}
{48800}{}{显示器}
{48801}{}{一个大型显示器，仅有黑白显示。穿袍子的人正以狂热的速度背诵宗教教义。}
{48900}{}{力场}
{48901}{}{这是一个强大的能量场。}
{49000}{}{力场}
{49001}{}{这是一股强大的能量场。}
{49100}{}{力场}
{49101}{}{这是一股强大的能量场。}
{49200}{}{力场}
{49201}{}{这是一股强大的能量场。}
{49300}{}{桌子}
{49301}{}{一张相当普通的木桌。}
{49400}{}{桌子}
{49401}{}{一张相当普通的木桌。}
{49500}{}{桌子}
{49501}{}{一张相当普通的木桌。}
{49600}{}{桌子}
{49601}{}{一张相当普通的木桌。}
{49700}{}{桌子}
{49701}{}{一张相当普通的木桌。}
{49800}{}{桌子}
{49801}{}{一张相当普通的木桌。}
{49900}{}{架子}
{50000}{}{架子}
{50100}{}{架子}
{50200}{}{架子}
{50300}{}{架子}
{50400}{}{架子}
{50500}{}{祭坛}
{50501}{}{一个由涂漆木头制成的简单祭坛。}
{50600}{}{祭坛}
{50601}{}{一个由涂漆木头制成的简单祭坛。}
{50700}{}{祭坛}
{50701}{}{一个由涂漆木头制成的简单祭坛。}
{50800}{}{祭坛}
{50801}{}{一个由涂漆木头制成的简单祭坛。}
{50900}{}{瓦砾}
{50901}{}{屋顶塌陷形成了这堆瓦砾。你的绳子通向地面。}
{51000}{}{书架}
{51100}{}{书架}
{51200}{}{书架}
{51300}{}{书架}
{51400}{}{书架}
{51500}{}{书架}
{51600}{}{桌子}
{51601}{}{这张大桌子看起来很重要。也许他们在这里开会？}
{51700}{}{桌子}
{51701}{}{这张大桌子看起来很重要。也许他们在这里开会？}
{51800}{}{桌子}
{51801}{}{这张大桌子看起来很重要。也许他们在这里开会？}
{51900}{}{桌子}
{51901}{}{这张大桌子看起来很重要。也许他们在这里开会？}
{52000}{}{桌子}
{52001}{}{这张大桌子看起来很重要。也许他们在这里开会？}
{52100}{}{桌子}
{52101}{}{这张大桌子看起来很重要。也许他们在这里开会？}
{52200}{}{祭坛}
{52201}{}{一个由钢铁兄弟会设计和使用的祭坛。他们的标志显眼地展示着。}
{52300}{}{祭坛}
{52301}{}{一个由钢铁兄弟会设计和使用的祭坛。他们的标志显眼地展示着。}
{52400}{}{祭坛}
{52401}{}{一个由钢铁兄弟会设计和使用的祭坛。他们的标志显眼地展示着。}
{52500}{}{长椅}
{52501}{}{一个设计精美但看起来极不舒适的长椅。}
{52600}{}{讲台}
{52601}{}{一个漂亮的木制讲台。内置有一个面向演讲者的提词器屏幕。}
{52700}{}{马车}
{52701}{}{一辆由古老汽车残骸改装而成的商队马车。}
{52800}{}{马车}
{52801}{}{一辆由古老汽车残骸改装而成的商队马车。}
{52900}{}{马车}
{52901}{}{一辆由古老汽车残骸改装而成的商队马车。}
{53000}{}{马车}
{53001}{}{一辆由古老汽车残骸改装而成的商队马车。}
{53100}{}{马车}
{53101}{}{一辆由古老汽车残骸改装而成的商队马车。}
{53200}{}{马车}
{53201}{}{一辆由古老汽车残骸改装而成的商队马车。}
{53300}{}{垫子}
{53301}{}{一个训练垫。}
{53400}{}{垫子}
{53401}{}{一个训练垫。}
{53500}{}{垫子}
{53501}{}{一个训练垫。}
{53600}{}{垫子}
{53601}{}{一个训练垫。}
{53700}{}{沙袋}
{53701}{}{这是一个强人牌（StrongMan?）沙袋。}
{53800}{}{踏步机}
{53801}{}{一台健身器材。}
{53900}{}{踏步机}
{54000}{}{跑步机}
{54001}{}{一台健身器材。}
{54100}{}{跑步机}
{54101}{}{一台健身器材。}
{54200}{}{卧推器}
{54201}{}{一台健身器材。}
{54300}{}{卧推器}
{54301}{}{一台健身器材。}
{54400}{}{桥梁}
{54401}{}{一座匆忙搭建的木桥，允许人们穿过绿色发光粘液的护城河。}
{54500}{}{桥梁}
{54501}{}{一座匆忙搭建的木桥，允许人们穿过绿色发光粘液的护城河。}
{54600}{}{轮盘赌桌}
{54601}{}{这是一张赌博桌。}
{54700}{}{轮盘赌桌}
{54701}{}{这是一张赌博桌。}
{54800}{}{轮盘赌桌}
{54801}{}{这是一张赌博桌。}
{54900}{}{轮盘赌桌}
{54901}{}{这是一张赌博桌。}
{55000}{}{轮盘赌桌}
{55001}{}{这是一张赌博桌。}
{55100}{}{桶}
{55101}{}{这个空金属桶上用亮黄色油漆画着核辐射标志。}
{55200}{}{桶}
{55201}{}{这个桶里装着一些绿色发光粘液。核辐射标志暗示了这些粘液的性质。}
{55300}{}{电脑}
{55301}{}{一台非常现代化的电脑。}
{55400}{}{电脑}
{55401}{}{一台非常现代化的电脑。}
{55500}{}{悬浮罐}
{55501}{}{某种医疗或实验设备，看起来可以容纳一个人或更大的物体。}
{55600}{}{破损的悬浮罐}
{55601}{}{一件损坏的设备，无法修复。}
{55700}{}{主机}
{55701}{}{一个大型超级计算机。可能是你见过的最快的计算机。}
{55800}{}{支撑平台}
{55801}{}{这个平台支撑着大型超级计算机，位于冷却槽上方。}
{55900}{}{不要使用}
{56000}{}{不要使用}
{56100}{}{床}
{56101}{}{一张军用风格的双层床。看起来非常不舒服。床单紧绷得可以弹硬币。}
{56200}{}{床}
{56201}{}{一张军用风格的双层床。看起来非常不舒服。床单紧绷得可以弹硬币。}
{56300}{}{床}
{56301}{}{一张军用风格的双层床。看起来非常不舒服。床单紧绷得可以弹硬币。}
{56400}{}{电线}
{56401}{}{看起来像是一种串行电缆。}
{56500}{}{电线}
{56501}{}{看起来像是一种串行电缆。}
{56600}{}{标志}
{56601}{}{标志上写着酒吧。这应该很明显。}
{56700}{}{横梁}
{56701}{}{这根坚固的横梁架在陨石坑上方。}
{56800}{}{横梁}
{56801}{}{有一根绳子牢牢地系在横梁上。看起来你现在可以爬下陨石坑了。}
{56900}{}{货架}
{56901}{}{你看到一些非常空的金属货架。}
{57000}{}{货架}
{57001}{}{你看到一些非常空的金属货架。}
{57100}{}{货架}
{57101}{}{你看到一些非常空的金属货架。}
{57200}{}{货架}
{57201}{}{你看到一些非常空的金属货架。}
{57300}{}{灌木}
{57301}{}{某种沙漠杂草。与这个故事无关。}
{57400}{}{灌木}
{57401}{}{某种沙漠杂草。}
{57500}{}{灌木}
{57501}{}{某种沙漠杂草。}
{57600}{}{地面}
{57601}{}{从这个塔楼层可以看到骨园的美景。你能感受到自己身处高空。}
{57700}{}{地面}
{57701}{}{从这个塔楼层可以看到骨园的美景。}
{57800}{}{墙壁}
{57801}{}{可以清楚地看到大教堂的外部。}
{57900}{}{墙壁}
{57901}{}{可以清楚地看到大教堂的外部。}
{58000}{}{墙壁}
{58001}{}{可以清楚地看到大教堂的外部。}
{58100}{}{门}
{58101}{}{这扇门看起来就像牢房里的门。}
{58200}{}{招牌}
{58201}{}{这个招牌上写着这家店叫做达克沃特。}
{58300}{}{梯子}
{58301}{}{这架梯子通向下面的黑暗。}
{58400}{}{梯子}
{58401}{}{这架梯子通向下面的黑暗。}
{58500}{}{机器}
{58501}{}{看起来像是一台旧印刷机或制造设备。}
{58600}{}{机器}
{58601}{}{看起来像是一台旧印刷机或制造设备。}
{58700}{}{机器}
{58701}{}{看起来像是一台旧印刷机或制造设备。}
{58800}{}{机器}
{58801}{}{看起来像是一台旧印刷机或制造设备。}
{58900}{}{机器}
{58901}{}{看起来像是一台旧印刷机或制造设备。}
{59000}{}{机器}
{59001}{}{看起来像是一台旧印刷机或制造设备。}
{59100}{}{桌子}
{59101}{}{这张金属桌子状况良好。中间有一个排水口。}
{59200}{}{桌子}
{59201}{}{这张金属桌子状况良好。中间有一个排水口。}
{59300}{}{桌子}
{59301}{}{金属桌子上覆盖着某种生物质。}
{59400}{}{桌子}
{59401}{}{金属桌子上覆盖着某种生物质。}
{59500}{}{桌子}
{59501}{}{金属桌子上覆盖着某种生物质。}
{59600}{}{公告板}
{59601}{}{公告板上钉满了招聘信息，看起来使用频繁。}
{59700}{}{警卫室}
{59701}{}{这个警卫室已有百年历史，但仍然状况良好。}
{59800}{}{标牌}
{59801}{}{标牌上写着：杂货店。}
{59900}{}{标牌}
{59901}{}{标牌上写着：杂货店。}
{60000}{}{标牌}
{60001}{}{标牌上写着：市场。}
{60100}{}{粘液池}
{60101}{}{看起来非常不健康。你可能需要穿上防护泳裤再下水。}
{60200}{}{粘液池}
{60201}{}{看起来非常不健康。你可能需要穿上防护泳裤再下水。}
{60300}{}{粘液池}
{60301}{}{看起来非常不健康。你可能需要穿上防护泳裤再下去。}
{60400}{}{桌子}
{60401}{}{一张看起来不错的金属桌子。}
{60500}{}{桌子}
{60501}{}{一张看起来不错的金属桌子。}
{60600}{}{桌子}
{60601}{}{一张看起来不错的金属桌子。}
{60700}{}{桌子}
{60701}{}{一张看起来不错的金属桌子。}
{60800}{}{桌子}
{60801}{}{这张金属桌子没有得到很好的维护。锈迹非常严重。}
{60900}{}{桌子}
{60901}{}{一张看起来不错的金属桌子，除了锈迹。}
{61000}{}{桌子}
{61001}{}{一张看起来不错的金属桌子，除了锈迹。}
{61100}{}{桌子}
{61101}{}{一张看起来不错的金属桌子，除了锈迹。}
{61200}{}{火坑}
{61201}{}{火在燃烧。}
{61300}{}{镜子}
{61301}{}{你看了自己一会儿。}
{61400}{}{镜子}
{61401}{}{你盯着镜中的自己看了一会儿。}
{61500}{}{水槽}
{61501}{}{一个功能齐全的水槽。也很干净。}
{61600}{}{马桶}
{61601}{}{这个马桶非常干净。还能用。}
{61700}{}{小便池}
{61701}{}{这个小便池可以正常使用。}
{61800}{}{厕所}
{61801}{}{如果你有厕所癖好，那这会是个不错的厕所。}
{61900}{}{水槽}
{61901}{}{这个水槽状态完美。}
{62000}{}{小便池}
{62001}{}{这个小便池状态完美。}
{62100}{}{淋浴}
{62101}{}{军用风格的淋浴。不适合害羞的人使用。}
{62200}{}{淋浴}
{62201}{}{军用风格的淋浴。不适合害羞的人使用。}
{62300}{}{淋浴}
{62301}{}{军用风格的淋浴。不适合害羞的人使用。}
{62400}{}{淋浴}
{62401}{}{军用风格的淋浴。不适合害羞的人使用。}
{62500}{}{淋浴}
{62501}{}{军用风格的淋浴。不适合害羞的人使用。}
{62600}{}{淋浴}
{62601}{}{军用风格的淋浴。不适合害羞的人使用。}
{62700}{}{床}
{62701}{}{看起来非常舒适的床。}
{62800}{}{床}
{62801}{}{看起来非常舒适的床。}
{62900}{}{床}
{62901}{}{结构增强的双层床。}
{63000}{}{床}
{63001}{}{结构增强的双层床。}
{63100}{}{床}
{63101}{}{结构增强的双层床。}
{63200}{}{终端}
{63300}{}{终端}
{63400}{}{旗帜}
{63401}{}{这面旗帜是大教堂之子的象征。}
{63500}{}{旗帜}
{63501}{}{这面旗帜是大教堂之子的象征。}
{63600}{}{旗帜}
{63601}{}{这面旗帜是大教堂之子的象征。}
{63700}{}{电脑}
{63701}{}{一台大型电脑。}
{63800}{}{电脑}
{63801}{}{一台大型电脑。}
{63900}{}{电脑}
{63901}{}{一台大型电脑。}
{64000}{}{终端}
{64001}{}{大型电脑的终端。}
{64100}{}{尸体}
{64101}{}{看起来这个人死得非常痛苦。}
{64200}{}{尸体}
{64201}{}{看起来这个人死得非常痛苦。}
{64300}{}{尸体}
{64301}{}{看起来这个人死得非常痛苦。}
{64400}{}{尸体}
{64401}{}{看起来这个人死得非常痛苦。}
{64500}{}{门}
{64501}{}{这扇铁栅门非常适合作为牢房的门。}
{64600}{}{终端}
{64700}{}{终端}
{64800}{}{叉车}
{64801}{}{这台叉车无法操作。}
{64900}{}{叉车}
{64901}{}{这台叉车无法操作。}
{65000}{}{设备}
{65100}{}{医疗台}
{65101}{}{这张医疗台非常生锈。台子中央的排水口堵住了。}
{65200}{}{医疗台}
{65201}{}{这张医疗台非常生锈。}
{65300}{}{大门}
{65301}{}{这扇大门有一个可以升降的横杆。}
{65400}{}{管道}
{65500}{}{管道}
{65600}{}{发电机}
{65601}{}{一台瓦兹电力箱发电机。在战争前作为备用发电机相当常见。}
{65700}{}{水箱}
{65701}{}{一个大型水箱。看起来维护得很好，这可能是个好事。}
{65800}{}{警亭}
{65801}{}{一座来自英国的警亭，大约是1960年的。}
{65900}{}{桌子}
{65901}{}{一张制作精美的桌子。手工制作，但看起来比你见过的任何桌子都要好。}
{66000}{}{桌子}
{66001}{}{一张制作精美的桌子。手工制作，但看起来比你见过的任何桌子都要好。}
{66100}{}{桌子}
{66101}{}{一张制作精美的桌子。手工制作，但看起来比你见过的任何桌子都要好。}
{66200}{}{椅子}
{66201}{}{一把看起来非常不错的椅子。}
{66300}{}{椅子}
{66301}{}{一把看起来非常不错的椅子。}
{66400}{}{椅子}
{66401}{}{一把看起来非常不错的椅子。}
{66500}{}{椅子}
{66501}{}{一把看起来非常不错的椅子。}
{66600}{}{椅子}
{66601}{}{一个非常漂亮的椅子。}
{66700}{}{椅子}
{66701}{}{一个非常漂亮的椅子。}
{66800}{}{椅子}
{66801}{}{一个非常漂亮的椅子。}
{66900}{}{椅子}
{66901}{}{一个非常漂亮的椅子。}
{67000}{}{椅子}
{67001}{}{一个非常漂亮的椅子。}
{67100}{}{椅子}
{67101}{}{一个非常漂亮的椅子。}
{67200}{}{椅子}
{67201}{}{一个非常漂亮的椅子。}
{67300}{}{椅子}
{67301}{}{一个非常漂亮的椅子。}
{67400}{}{椅子}
{67401}{}{一个非常漂亮的椅子。}
{67500}{}{椅子}
{67501}{}{一个非常漂亮的椅子。}
{67600}{}{椅子}
{67601}{}{一个非常漂亮的椅子。}
{67700}{}{椅子}
{67701}{}{一个非常漂亮的椅子。}
{67800}{}{床}
{67801}{}{一张非常漂亮的床。}
{67900}{}{床}
{67901}{}{一张非常漂亮的床。}
{68000}{}{床}
{68001}{}{一张非常漂亮的床。}
{68100}{}{床}
{68101}{}{一张非常漂亮的床。}
{68200}{}{炉子}
{68201}{}{一个功能完好的燃木炉。}
{68300}{}{炉子}
{68301}{}{一个功能完好的燃木炉。}
{68400}{}{炉子}
{68401}{}{一个功能完好的燃木炉。}
{68500}{}{炉子}
{68501}{}{一个功能完好的燃木炉。}
{68600}{}{损坏的柱子}
{68700}{}{被毁的入口}
{68800}{}{岩石}
{68801}{}{一大片岩石，这不是自然形成的。}
{68900}{}{岩石}
{68901}{}{一大片岩石，这不是自然形成的。}
{69000}{}{厕所}
{69001}{}{一个简陋但有效的厕所。洞里放了一些树叶来掩盖气味。}
{69100}{}{山}
{69101}{}{这些山壁看起来非常难以接近。}
{69200}{}{山}
{69201}{}{这些山壁看起来非常难以接近。}
{69300}{}{山}
{69301}{}{这些山壁看起来非常难以接近。}
{69400}{}{山}
{69401}{}{这些山壁看起来非常难以接近。}
{69500}{}{山}
{69501}{}{这些山壁看起来非常难以接近。}
{69600}{}{山}
{69601}{}{这些山壁看起来非常难以接近。}
{69700}{}{粘液}
{69701}{}{你看到一些奇怪的有毒生物黏液。}
{69800}{}{黏液}
{69801}{}{你看到一些奇怪的有毒生物黏液。}
{69900}{}{黏液}
{69901}{}{你看到一些奇怪的有毒生物黏液。}
{70000}{}{黏液}
{70001}{}{你看到一些奇怪的有毒生物黏液。}
{70100}{}{黏液}
{70101}{}{你看到一些奇怪的有毒生物黏液。}
{70200}{}{黏液}
{70201}{}{你看到一些奇怪的有毒生物黏液。}
{70300}{}{黏液}
{70301}{}{你看到一些奇怪的有毒生物黏液。}
{70400}{}{黏液}
{70401}{}{你看到一些奇怪的有毒生物黏液。}
{70500}{}{黏液}
{70501}{}{你看到一些奇怪的有毒生物黏液。}
{70600}{}{黏液}
{70601}{}{你看到一些奇怪的有毒生物黏液。}
{70700}{}{黏液}
{70701}{}{你看到一些奇怪的有毒生物黏液。}
{70800}{}{黏液}
{70801}{}{你看到一些奇怪的有毒生物黏液。}
{70900}{}{黏液}
{70901}{}{你看到一些奇怪的有毒生物黏液。}
{71000}{}{黏液}
{71001}{}{你看到一些奇怪的有毒生物黏液。}
{71100}{}{黏液}
{71101}{}{你看到一些奇怪的有毒生物黏液。}
{71200}{}{黏液}
{71201}{}{你看到一些奇怪的有毒生物黏液。}
{71300}{}{黏液}
{71301}{}{你看到一些奇怪的有毒生物黏液。}
{71400}{}{黏液}
{71401}{}{你看到一些奇怪的有毒生物黏液。}
{71500}{}{黏液}
{71501}{}{你看到一些奇怪的有毒生物黏液。}
{71600}{}{黏液}
{71601}{}{你看到一些奇怪的有毒生物黏液。}
{71700}{}{黏液}
{71701}{}{你看到一些奇怪的有毒生物黏液。}
{71800}{}{黏液}
{71801}{}{你看到一些奇怪的有毒生物黏液。}
{71900}{}{黏液}
{71901}{}{你看到一些奇怪的有毒生物黏液。}
{72000}{}{黏液}
{72001}{}{你看到一些奇怪的有毒生物黏液。}
{72100}{}{黏液}
{72101}{}{你看到一些奇怪的有毒生物黏液。}
{72200}{}{黏液}
{72201}{}{你看到一些奇怪的有毒生物黏液。}
{72300}{}{黏液}
{72301}{}{你看到一些奇怪的有毒生物黏液。}
{72400}{}{黏液}
{72401}{}{你看到一些奇怪的有毒生物黏液。}
{72500}{}{黏液}
{72501}{}{你看到一些奇怪的有毒生物黏液。}
{72600}{}{黏液}
{72601}{}{你看到一些奇怪的有毒生物黏液。}
{72700}{}{黏液}
{72701}{}{你看到一些奇怪的有毒生物黏液。}
{72800}{}{黏液}
{72801}{}{你看到一些奇怪的有毒生物黏液。}
{72900}{}{黏液}
{72901}{}{你看到一些奇怪的有毒生物黏液。}
{73000}{}{黏液}
{73001}{}{你看到一些奇怪的有毒生物黏液。}
{73100}{}{黏液}
{73101}{}{你看到一些奇怪的有毒生物黏液。}
{73200}{}{黏液}
{73201}{}{你看到一些奇怪的有毒生物黏液。}
{73300}{}{黏液}
{73301}{}{你看到一些奇怪的有毒生物黏液。}
{73400}{}{黏液}
{73401}{}{你看到一些奇怪的有毒生物黏液。}
{73500}{}{黏液}
{73501}{}{你看到一些奇怪的有毒生物黏液。}
{73600}{}{黏液}
{73601}{}{你看到一些奇怪的有毒生物黏液。}
{73700}{}{黏液}
{73701}{}{你看到一些奇怪的有毒生物黏液。}
{73800}{}{黏液}
{73801}{}{你看到一些奇怪的有毒生物黏液。}
{73900}{}{黏液}
{73901}{}{你看到一些奇怪的有毒生物黏液。}
{74000}{}{黏液}
{74001}{}{你看到一些奇怪的有毒生物黏液。}
{74100}{}{黏液}
{74101}{}{你看到一些奇怪的有毒生物黏液。}
{74200}{}{黏液}
{74201}{}{你看到一些奇怪的有毒生物黏液。}
{74300}{}{黏液}
{74301}{}{你看到一些奇怪的有毒生物黏液。}
{74400}{}{黏液}
{74401}{}{你看到一些奇怪的有毒生物黏液。}
{74500}{}{黏液}
{74501}{}{你看到一些奇怪的有毒生物黏液。}
{74600}{}{黏液}
{74601}{}{你看到一些奇怪的有毒生物黏液。}
{74700}{}{黏液}
{74701}{}{你看到一些奇怪的有毒生物黏液。}
{74800}{}{黏液}
{74801}{}{你看到一些奇怪的有毒生物黏液。}
{74900}{}{电脑}
{74901}{}{电脑上的黏液太多，难以操作。}
{75000}{}{电脑}
{75001}{}{电脑上的黏液太多，难以操作。}
{75100}{}{电脑}
{75101}{}{电脑上的黏液太多，难以操作。}
{75200}{}{电脑}
{75201}{}{电脑上的黏液太多，难以操作。}
{75300}{}{电脑}
{75301}{}{电脑上的黏液太多，难以操作。}
{75400}{}{电脑}
{75401}{}{电脑上的黏液太多，难以操作。}
{75500}{}{电脑}
{75501}{}{电脑上的黏液太多，难以操作。}
{75600}{}{电脑}
{75601}{}{电脑上的黏液太多，难以操作。}
{75700}{}{电脑}
{75701}{}{这台电脑上覆盖的粘液让访问变得非常困难。}
{75800}{}{电脑}
{75801}{}{这台电脑上覆盖的粘液让访问变得非常困难。}
{75900}{}{电脑}
{75901}{}{这台电脑上覆盖的粘液让访问变得非常困难。}
{76000}{}{电脑}
{76001}{}{这台电脑上覆盖的粘液让访问变得非常困难。}
{76100}{}{显示器}
{76101}{}{由于屏幕上溅满了粘液，你无法读取任何内容。}
{76200}{}{显示器}
{76201}{}{由于屏幕上溅满了粘液，你无法读取任何内容。}
{76300}{}{显示器}
{76301}{}{由于屏幕上溅满了粘液，你无法读取任何内容。}
{76400}{}{显示器}
{76401}{}{由于屏幕上溅满了粘液，你无法读取任何内容。}
{76500}{}{地板}
{76501}{}{你敢肯定地板上有东西在移动。}
{76600}{}{基座}
{76601}{}{这个基座看起来像是在缓慢地呼吸。}
{76700}{}{地板}
{76800}{}{炸弹}
{76801}{}{这是一颗核弹。它静静地放在那里，看起来非常危险。}
{76900}{}{支撑底座}
{76901}{}{这个底座托着上面的核弹。}
{77000}{}{电脑控制台}
{77001}{}{这是一个核弹访问电脑。电脑看起来非常安全。上面有一个奇形钥匙的插槽。}
{77100}{}{电线}
{77101}{}{这些电线将炸弹连接到电脑。}
{77200}{}{椅子}
{77201}{}{这把椅子没有什么特别之处。}
{77300}{}{椅子}
{77301}{}{这把椅子没有什么特别之处。}
{77400}{}{椅子}
{77401}{}{这把椅子没有什么特别之处。}
{77500}{}{椅子}
{77501}{}{这把椅子没有什么特别之处。}
{77600}{}{椅子}
{77601}{}{这把椅子没有什么特别之处。}
{77700}{}{椅子}
{77701}{}{这把椅子没有什么特别之处。}
{77800}{}{椅子}
{77801}{}{这把椅子没有什么特别之处。}
{77900}{}{椅子}
{77901}{}{这把椅子没有什么特别之处。}
{78000}{}{柱子}
{78001}{}{一个支撑柱。}
{78100}{}{柱子}
{78101}{}{一个支撑柱。}
{78200}{}{柱子}
{78201}{}{一个支撑柱。}
{78300}{}{柱子}
{78301}{}{一个支撑柱。}
{78400}{}{床}
{78401}{}{这张床状况极差。}
{78500}{}{床}
{78501}{}{这张床状况非常糟糕。}
{78600}{}{床}
{78601}{}{这张床状况不佳。}
{78700}{}{床}
{78701}{}{这张床状况相当糟糕。}
{78800}{}{监视器}
{78801}{}{这些监视器已损坏，无法使用。}
{78900}{}{监视器}
{78901}{}{这些监视器已损坏，无法使用。}
{79000}{}{监视器}
{79001}{}{这些监视器已损坏，无法使用。}
{79100}{}{监视器}
{79101}{}{这些监视器已损坏，无法使用。}
{79200}{}{通风口}
{79201}{}{这个通风口几乎没有新鲜空气流出。}
{79300}{}{通风口}
{79301}{}{这个通风口几乎没有新鲜空气流出。}
{79400}{}{通风口}
{79401}{}{这个通风口没有新鲜空气流出。}
{79500}{}{通风口}
{79501}{}{这个通风口只有少量新鲜空气流出。}
{79600}{}{桌子}
{79601}{}{这张桌子没什么特别之处，只是几乎被毁坏。}
{79700}{}{桌子}
{79701}{}{这张桌子严重损坏。}
{79800}{}{桌子}
{79801}{}{这张桌子的状况非常糟糕。}
{79900}{}{桌子}
{79901}{}{没有理由去搜查这张桌子。}
{80000}{}{监视器}
{80001}{}{这一排监视器的显示屏已经被毁坏。}
{80100}{}{监视器}
{80101}{}{这一排监视器的显示屏已损坏到无法修复。}
{80200}{}{监视器}
{80201}{}{这台监视器的屏幕已经破裂并损坏。}
{80300}{}{显示器}
{80301}{}{这个显示器因为屏幕损坏而无法使用。}
{80400}{}{电脑}
{80401}{}{这台电脑已经坏了。}
{80500}{}{电脑}
{80501}{}{这台电脑已经坏了。}
{80600}{}{电脑}
{80601}{}{这台电脑已经坏了。}
{80700}{}{椅子}
{80701}{}{这把椅子已经毁坏。}
{80800}{}{椅子}
{80801}{}{这把椅子已经毁坏。}
{80900}{}{椅子}
{80901}{}{这把椅子已经毁坏。}
{81000}{}{椅子}
{81001}{}{这把椅子已经毁坏。}
{81100}{}{通风口}
{81101}{}{这个通风口损坏严重，无法修复。}
{81200}{}{通风口}
{81201}{}{这个通风口损坏严重，无法修复。}
{81300}{}{通风口}
{81301}{}{这个通风口完全无法运作。}
{81400}{}{电脑}
{81401}{}{这台电脑看起来几乎无法运作。}
{81500}{}{电脑}
{81501}{}{这台电脑看起来几乎无法运作。}
{81600}{}{显示器}
{81601}{}{这个显示器几乎无法正常工作。}
{81700}{}{显示器}
{81701}{}{这个显示器几乎无法正常工作。}
{81800}{}{计算机}
{81801}{}{计算机无法运行。}
{81900}{}{计算机}
{81901}{}{计算机无法运行。}
{82000}{}{显示器}
{82001}{}{显示器无法运行。}
{82100}{}{显示器}
{82101}{}{显示器无法运行。}
{82200}{}{门口}
{82201}{}{看起来是个非常不错的门口。它很好地支撑着门。}
{82300}{}{显示器}
{82301}{}{显示器状况良好。}
{82400}{}{显示器}
{82401}{}{显示器状况良好。}
{82500}{}{墙壁}
{82600}{}{银行门}
{82601}{}{一个非常坚固的银行金库门。看起来非常安全。}
{82700}{}{灯光}
{82701}{}{一个安全灯。}
{82800}{}{灯光}
{82801}{}{一个安全灯。}
{82900}{}{柱子}
{82901}{}{这个柱子是阴影镇广场的展示品。它讲述着希望与和平的故事。}
{83000}{}{机器人充电站}
{83001}{}{这是一个机器人充电区。机器人不在服务时，会在这里停靠关闭并充电。}
{83100}{}{机器人充电站}
{83101}{}{这是一个机器人充电区。机器人不在服务时，会在这里停靠关闭并充电。}
{83200}{}{机器人充电站}
{83201}{}{这是一个机器人充电区。机器人不在服务时，会在这里停靠关闭并充电。}
{83300}{}{机器人充电站}
{83301}{}{这是一个机器人充电区。机器人在不工作时会停靠在这里关闭并充电。}
{83400}{}{机器人插槽}
{83401}{}{这是一个机器人充电区。机器人在不工作时会停靠在这里关闭并充电。}
{83500}{}{机器}
{83501}{}{这台机器与机器人服务区有关。看起来并没有特别有趣。}
{83600}{}{机器}
{83601}{}{这台机器与机器人服务区有关。看起来并不是很有趣。}
{83700}{}{条纹}
{83800}{}{条纹}
{83900}{}{条纹}
{84000}{}{条纹}
{84100}{}{条纹}
{84200}{}{条纹}
{84300}{}{条纹}
{84400}{}{条纹}
{84500}{}{条纹}
{84600}{}{条纹}
{84700}{}{条纹}
{84800}{}{门}
{84801}{}{一扇非常普通的木门。}
{84900}{}{门}
{84901}{}{一扇非常普通的木门。}
{85000}{}{门}
{85001}{}{一扇非常普通的木门。}
{85100}{}{标志}
{85101}{}{这个标志代表友好借贷公司。}
{85200}{}{徽章}
{85201}{}{这个徽章是启示录追随者使用的。}
{85300}{}{医疗台}
{85301}{}{这看起来像是一张医疗检查台。}
{85400}{}{标志}
{85401}{}{马耳他之鹰}
{85401}{}{这是马耳他之鹰的霓虹招牌。}
{85500}{}{涂鸦}
{85600}{}{涂鸦}
{85700}{}{涂鸦}
{85800}{}{涂鸦}
{85900}{}{涂鸦}
{86000}{}{涂鸦}
{86100}{}{涂鸦}
{86200}{}{涂鸦}
{86300}{}{涂鸦}
{86400}{}{涂鸦}
{86500}{}{涂鸦}
{86600}{}{涂鸦}
{86700}{}{涂鸦}
{86800}{}{涂鸦}
{86900}{}{标志}
{86901}{}{上面写着：枪械。这里可能出售枪支。}
{87000}{}{标志}
{87001}{}{招牌上写着：警察局。}
{87100}{}{标志}
{87101}{}{这是远航商人的招牌。}
{87200}{}{标志}
{87201}{}{这个标志上写着：枪械跑者。}
{87300}{}{标志}
{87301}{}{这是红色商队公司的标志。}
{87400}{}{标志}
{87401}{}{这个标志上写着：医院。这可能是个好地方。}
{87500}{}{标志}
{87501}{}{这里是撞车旅馆的招牌。}
{87600}{}{招牌}
{87601}{}{这个不太可能的招牌上写着：鲍勃二手车市场。}
{87700}{}{招牌}
{87701}{}{这是水商人的招牌，一个位于商贸城的贸易公司。}
{87800}{}{蛋壳}
{87801}{}{破碎的蛋壳碎片。}
{87900}{}{蛋壳}
{87901}{}{破碎的蛋壳碎片。}
{88000}{}{蛋壳}
{88001}{}{破碎的蛋壳碎片。}
{88100}{}{蛋壳}
{88101}{}{破碎的蛋壳碎片。}
{88200}{}{蛋壳}
{88201}{}{破碎的蛋壳碎片。}
{88300}{}{蛋壳}
{88301}{}{破碎的蛋壳碎片。}
{88400}{}{蛋壳}
{88401}{}{破碎的蛋壳碎片。}
{88500}{}{蛋壳}
{88501}{}{破碎的蛋壳碎片。}
{88600}{}{灯柱}
{88601}{}{一个灯柱，看起来工作状态良好。}
{88700}{}{招牌}
{88701}{}{招牌上写着：汽车旅馆。}
{88800}{}{蘑菇}
{88801}{}{这个桌上种植箱里填满了粪便，蘑菇在里面快乐地生长。}
{88900}{}{蘑菇}
{88901}{}{这个桌上种植箱里填满了粪便，蘑菇在里面快乐地生长。}
{89000}{}{骷髅}
{89100}{}{标牌}
{89101}{}{这个标牌上写着：监狱。}
{89200}{}{标牌}
{89201}{}{这是污秽酒吧和疯人院的标牌。}
{89300}{}{标牌}
{89301}{}{一则刀锋牌剃须刀的广告。}
{89400}{}{淋浴}
{89401}{}{一个相当普通的淋浴间。}
{89500}{}{淋浴}
{89501}{}{一个相当普通的淋浴间。}
{89600}{}{标牌}
{89601}{}{这是友好贷款公司的标牌。}
{89700}{}{标牌}
{89701}{}{这是友好贷款公司的标牌。}
{89800}{}{海报}
{89801}{}{这是一张战前恐怖电影的海报。}
{89900}{}{海报}
{89901}{}{这是一张战前恐怖电影的海报。}
{90000}{}{吧台}
{90001}{}{吧台上放着一个骨灰瓮。瓮看起来有些破旧，但可能很有价值。}
{90100}{}{电梯井}
{90101}{}{井里有一根绳子从上面垂下。}
{90200}{}{电梯井}
{90201}{}{井里有一根绳子从边缘垂下。}
{90300}{}{医疗床}
{90301}{}{这张床配有一个内置显示器，用于监控病人的恢复情况。}
{90400}{}{水泵}
{90401}{}{这是一台从地下抽水的机器。}
{90500}{}{医疗床}
{90501}{}{这张床配有一个内置显示器，用于监控病人的恢复情况。}
{90600}{}{动力装甲零件}
{90601}{}{这些是动力装甲的零件。}
{90700}{}{灯光}
{90701}{}{这个安全灯正闪烁着明亮的红光。}
{90800}{}{灯光}
{90801}{}{这个安全灯正闪烁着明亮的红光。}
