#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{快速代谢}
{101}{}{猛男}
{102}{}{小体型}
{103}{}{单手持}
{104}{}{灵巧}
{105}{}{神风}
{106}{}{重手}
{107}{}{快枪手}
{108}{}{血腥狂欢}
{109}{}{厄运缠身}
{110}{}{良好本性}
{111}{}{药物依赖}
{112}{}{药物抗性}
{113}{}{夜行者}
{114}{}{技艺精湛}
{115}{}{天赋异禀}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{你的代谢率是正常的两倍。这意味着你对辐射和毒素的抵抗力较弱，但身体恢复得更快。}
{201}{}{动作稍慢，但体型更大。你可能不常命中，但命中时敌人会感受到！你的总行动点减少，但力量增加。}
{202}{}{你没有其他避难所居民那么高大，但这从未让你慢下来。你负重较少，但更加灵活。}
{203}{}{你的一只手非常占优势。你在使用单手武器时表现出色，但双手武器会带来麻烦。}
{204}{}{你的攻击展现出极大的灵巧。你造成的伤害较少，但暴击几率更高。}
{205}{}{由于不注意任何威胁，你在一回合中行动得更快。这会降低你的护甲等级到仅限于你穿戴的装备，但你在战斗回合中的顺序更快。}
{206}{}{你挥击得更用力，但不更精准。你的攻击非常凶猛，但缺乏灵巧。你很少造成好的暴击，但总是造成更多的近战伤害。}
{207}{}{你没有时间瞄准目标攻击，因为你攻击得比普通人更快。使用武器时少消耗一点行动点。}
{208}{}{由于某种奇怪的命运扭曲，你周围的人总是死得很惨。你总是看到一个人死去的最惨烈方式。}
{209}{}{好的一面是你周围的人在战斗中更容易出现重大失误，坏的一面是你也是如此！}
{210}{}{在成长过程中，你学习了较少的战斗技能。你的战斗技能起步较低，但急救、医生、演讲和交易技能大幅提升。}
{211}{}{你更容易渴望药物。你渴望药物的几率是正常的两倍，但你从其副作用中恢复得更快。}
{212}{}{药物对你的影响时间只有正常的一半，但你渴望药物的几率也只有正常的50%。}
{213}{}{作为一个夜行者，你在太阳下山后更清醒。夜晚你的智力和感知力提高，但白天会减弱。}
{214}{}{由于你花费了比普通人更多的时间来提升技能，你的技能等级起点更高。代价是你无法获得太多额外能力。你每升四级才能获得一个额外能力。}
{215}{}{你天生能力比大多数人更强，因此没有花太多时间打磨技能。你的主要属性各增加1点，但所有技能初始值减少10%，每级获得的技能点减少5点。}

