{100}{}{你看到安柏，她是追随者的老师。}
{101}{}{现在是我休息的时候。请在晚上再来。}
{102}{}{欢迎，尊贵的旅行者。你是来这里学习的吗？}
{103}{}{不，我只是来这里杀东西的。}
{104}{}{这取决于你想教我什么。}
{105}{}{是的，我愿意学习。}
{106}{}{听到这个我很遗憾。追随者相信和平至上。为此，我已经放弃了暴力。晚安。}
{107}{}{我精通多种语言和艺术。也许你想学其中之一？}
{108}{}{抱歉，但我需要学习能帮助我生存的东西。}
{109}{}{我没时间学这些东西。我要走了。}
{110}{}{也许我可以听一两首歌。}
{111}{}{你能教我别的吗？}
{112}{}{啊，我们这里有一个生活的学生。在这种情况下，我可以教你一些草药学，但训练需要时间而效果不大。}
{113}{}{好吧，就教我吧。}
{114}{}{请教我你能教的东西。}
{115}{}{抱歉，我真的没时间研究植物。再见。}
{116}{}{你不必无礼。现在道歉，否则我不会教你。}
{117}{}{我很抱歉。请教我好吗？}
{118}{}{算了。}
{119}{}{这样好多了。我们将开始你的学习。}
{120}{}{你是一个聪明的学生。愿你的考验轻松。平安离去。}
{121}{}{随你便。愿未来能软化你的心，拓宽你的思维。}
{122}{}{很好，我会教你生存之道。}
{123}{}{你是一个聪明的学生。愿你的考验轻松。平安离去。}
{124}{}{你没有说服我。我认为你想利用我的才能做坏事。晚安。}
{125}{}{啊，艺术的学生在这个世界上很少见。也许你还有希望。每首歌都很长。你想听哪一首？}
{126}{}{《阴影的觉醒》。}
{127}{}{《艾瑞斯的叙事曲》。}
{128}{}{《阿尔忒弥斯的纪念》。}
{129}{}{《黎明战车的崛起》。}
{130}{}{一件惊人的作品。我将给你一个机会。}
{131}{}{我必须休息。这种教学让我精疲力竭。祝你好运。}
{132}{}{一件惊人的作品。我将给你一个机会。}
{133}{}{我必须休息。这种教学让我精疲力竭。祝你好运。}
{134}{}{一件惊人的作品。我将给你一个机会。}
{135}{}{我必须休息。这种教学让我精疲力竭。祝你好运。}
{136}{}{一件惊人的作品。我将给你一个机会。}
{137}{}{我必须休息。这种教学让我精疲力竭。祝你好运。}
{138}{}{我担心我已经过度消耗了自己。很抱歉。}
{139}{}{和平与美是我能教的全部。很遗憾这些对你没有吸引力。祝好。}
{140}{}{我可以教你古代吟游诗人和歌手的方式。}
{141}{}{我很荣幸能听一首歌。}
{142}{}{也许下次吧。谢谢。}
{143}{}{我希望能学到一些对我更有帮助的东西。}
{144}{}{你不需要我的才能。你已经教会了和平的人战争之道。我现在为他们哀悼。}
