{100}{}{你看到安德鲁，监狱的守卫。}
{101}{}{好了，你现在可以走了。}
{102}{}{嘿！你！站住！}
{103}{}{我能帮你吗？}
{104}{}{你是谁？}
{105}{}{你在做什么？}
{106}{}{不用了，谢谢。}
{107}{}{我是安德鲁。我的工作是看守监狱。}
{108}{}{我在看守监狱。我确保那些不法之徒不能进出。}
{109}{}{为什么要阻止人们进入监狱？}
{110}{}{哦。}
{111}{}{祝你有个愉快的一天。别惹麻烦。}
{112}{}{有人可能会留下东西帮助囚犯逃跑。或者有人可能被锁在里面，直到我们能拿到钥匙。}
{113}{}{呃！}
{114}{}{走开，伙计。}
{115}{}{走开，小姐。}
{116}{}{嘿！住手！}
