{100}{}{你看到了交易员。}
{101}{}{你想要交易吗？}
{102}{}{点击交易 -->}
{103}{}{不想。}
{104}{}{我们已经受到辐射蝎的困扰有一段时间了。所有被派去消灭这些怪物的人都没有回来。如果你愿意跟随我的向导前往它们的巢穴并杀死它们，我将提供武器和护甲。}
{105}{}{听起来不错。}
{106}{}{不，谢谢。}
{107}{}{那真是遗憾。请离开。}
{108}{}{非常好。山姆会带你去巢穴。拿上这些东西，它们会派上用场。}
{109}{}{请尽快帮助我们。时不我待。}
{110}{}{我不跟你这种人说话，陌生人。}
