{100}{}{你看到一个刀锋帮成员。}
{101}{}{嗨。}
{102}{}{你好。}
{103}{}{祝你有美好的一天。}
{104}{}{今天天气真不错。}
{105}{}{不知道会不会下雨。}
{106}{}{你见过雨中彩虹吗？}
{107}{}{得回去工作了。}
{108}{}{我们这里不常见到外来者。}
{109}{}{我得走了。}
{110}{}{再见。}
{111}{}{祝你安好。}
{112}{}{谢谢你的帮助。}
{113}{}{我们不会忘记你的。}
{114}{}{很高兴你站在我们这边。}
{115}{}{现在一切都会好起来的。}
