{100}{}{书架上摆满了宗教和哲学书籍。书架上积满了灰尘。}
{101}{}{你拿下一本书，仔细查看后又迅速放回书架。书架本身看起来非常结实。}
{102}{}{你发现了一个隐藏的门闩。}
{103}{}{这没有任何效果。}
{104}{}{书架旁的墙壁悄无声息地滑开了。}
{105}{}{你在书架上摸索了一会儿，但什么也没做到。}
{200}{}{书架上摆满了宗教和哲学书籍。}
{201}{}{门闩纹丝不动。}
