{100}{}{你看到一个男人，他迅速地盯着你的眼睛，然后移开视线。}
{101}{}{你看到的是格雷格。}
{102}{}{什么？你为什么要跟我说话？他们会听到的。}
{103}{}{嗨，你回来了。别说那么大声，他们就在外面。}
{104}{}{好吧，但请小声点，如果你不停止喊叫，他们会来找我们的。}
{105}{}{你是谁？}
{106}{}{你为什么这么紧张？}
{107}{}{我觉得你需要增加药量。}
{108}{}{算了。}
{109}{}{我是……格雷格……但别让其他人知道，否则他们会来找我的。}
{110}{}{紧张，我才不紧张。我只是小心。他们都说我偏执，但当他们来抓我们时，我才是那个能活下来的人。}
{111}{}{来抓你？谁要来抓你？}
{112}{}{你确实有点偏执，我以后再跟你聊。}
{113}{}{他们确实会来的……你知道的……疾病只是个开始。现在他们要来把我们都带走。但你就像其他人一样，你不会相信我，你会被注定。记住我的话。我还会在这里，而这一切，包括你，都会被带走。带走。[格雷格抓住他的头，蜷缩成一团，尖叫着挣扎]}
{114}{}{药物……哦，所以你是他们中的一员，想让我再吃药……但你休想让我吃。我不会吃的，不，我不会。那些声音，不，我不会，你不能逼我。[格雷格紧闭双眼，疯狂地抓住他的头，与只有他能听见的声音对话。]}
{115}{}{你不能逼我！}
{116}{}{你做什么都帮不了！}
{117}{}{一切都结束了！}
{118}{}{他们要来了，你阻止不了他们！}
{119}{}{这将会吞噬你们所有人！}

