{100}{}{你看到一个来自赤色商队的职员。}
{101}{}{你看到一个来自水商的职员。}
{102}{}{你看到一个来自远行商队的职员。}
{103}{}{你好。你在找工作吗？}
{104}{}{是的。}
{105}{}{不是。}
{106}{}{太好了。我们正好需要一名护卫。你有兴趣吗？}
{107}{}{好的。如果你需要工作，随时来找我们，我们会安排的。}
{108}{}{很遗憾听到这个。再见。}
{109}{}{太好了。我们有前往墓园、废城、死城和钢铁兄弟会的商队。你想加入哪个？}
{110}{}{太好了。我们有前往墓园、废城和钢铁兄弟会的商队。你想加入哪个？}
{111}{}{太好了。我们有前往墓园和废城的商队。你想加入哪个？}
{112}{}{墓园。}
{113}{}{废城。}
{114}{}{钢铁兄弟会。}
{115}{}{死城。}
{116}{}{都不去。}
{117}{}{太好了。我们现在就出发。}
