{100}{}{你看到一个阴影沙地的居民。}
{101}{}{欢迎来到阴影沙地，陌生人！}
{102}{}{呃，谢谢。}
{103}{}{这个地方有什么特别之处？}
{104}{}{嗯哼！}
{105}{}{我们是一个真正的社区。大家一起工作和分享。}
{106}{}{你们在这里是怎么生存的？}
{107}{}{你们的领袖是谁？}
{108}{}{我们有农场和灌溉系统，还养殖布拉明。每个人都贡献自己的技能，创造有用的东西。}
{109}{}{阿拉迪什是我们现任的长老。他凭借丰富的经验帮助领导社区。}
{110}{}{嗨。}
{111}{}{你好。}
{112}{}{你好吗？}
{113}{}{很高兴见到你。}
{114}{}{祝你有美好的一天。}
