{100}{}{Doc Morbid的助手，Cougar。}
{101}{}{最近怎么样？}
{102}{}{不错，你呢？}
{103}{}{我需要见医生。}
{104}{}{嗯。}
{105}{}{Cougar一直都很好。}
{106}{}{嘿，我得知道……}
{107}{}{你需要和我的人Flash谈谈，他能帮你。}
{108}{}{哎哟！别说太快，兄弟。你会让Cougar头疼。去找Flash吧。}
{109}{}{又是你，Cougar没什么好说的了。}
{110}{}{Cougar在看着你，兄弟！}
{111}{}{不错的装备，是你自己捡来的？}
