{100}{}{你看到一个高大强壮的壮汉。}
{101}{}{我们不是刚见过吗？你是来杀我的吗？}
{102}{}{我知道父亲不应该拥抱儿子，但我爱你，爸爸！}
{103}{}{主人，这就是我应该成为的样子吗，主人？}
{104}{}{没有什么能比得上丹恩……}
{105}{}{朋友，你最喜欢的颜色是什么？我的是牛奶色！}
{106}{}{你是个白痴，丹恩。他们很快就会杀了你，你活该！懦夫！懦夫！}
{107}{}{妈妈，你以为他们会投下炸弹吗？}
{108}{}{他们做得优雅而从容！}
{109}{}{我叫丹恩，不叫汤姆！}
{110}{}{你的诗真烂，伙计！真烂！烂透了！}
{111}{}{我喜欢亨迪先生！我想和他那可爱的小手……嘿嘿……}
{112}{}{我疯了。我真的疯了。天哪，我完全疯了！想想和平！想想统一！}
{113}{}{我想要一匹马！我需要一匹马！给我带匹马来，见鬼！一匹马！}
{114}{}{他们现在就盯着我们！夜行者先生！菲利克斯和提莫西！猫！狗！夜行者！}
{115}{}{闭嘴！他们会以为你是个疯子！你得振作起来！}
{116}{}{拉舍尔！你得杀了拉舍尔！救救孩子！可怜的小花童。可怜的我。}
{117}{}{闭嘴，你这个混蛋！振作起来！}
{118}{}{[走调唱] 曾经，我迷失，而现在我看见！不再需要洗礼！}
{119}{}{你知道吗，我曾经听到墨菲斯对夜行者挥拳。还是我闻到了？}
{120}{}{你们哭我真傻。别为洒掉的牛奶哭泣……或者损坏的货物。}
{121}{}{有人知道怎么修烤面包机吗？}
{122}{}{当然有人知道，白痴！是你的脑袋修不好，你这个混蛋！}
{123}{}{是枪，你这个混蛋！火药是聪明又邪恶的，它控制你的大脑！火药离你越近，你就越疯狂！砰！砰！砰！}
{124}{}{……我只想点燃世界的火焰！！！}
{125}{}{你想摔跤吗？我以前很擅长……直到夜行者打败了我。不过用了两个。夜行者真的很强！}
{126}{}{他们是变种人，傻瓜！当然很强！}
{127}{}{企鹅也是。还有陀螺水牛。他们用大水牛枪射它们。你得小心那些水牛女人。她们会很快把水牛扔到你身上，你都不知道发生了什么！哈哈！}
{128}{}{我是不是在哪见过你？你的脑袋也疼吗？}
{129}{}{当然你认识他，丹恩，你这个白痴！他是我们的敌人！他必须被消灭！}
{529}{}{当然你认识她，丹恩，你这个白痴！她是我们的敌人！她必须被消灭！}
{130}{}{别理他，他是个混蛋。我爱你。你爱我吗？}
{131}{}{我曾经住在不列颠哥伦比亚的彭蒂克顿。或者我在旧地图上看到过。那是美好的旧时光。真希望我那时活着……}
{132}{}{你不厌倦和我说话吗？这难道不是极其乏味？}
{133}{}{你不厌倦和自己说话吗，你这个精神分裂的混蛋？}
{134}{}{我恨我自己。我想死，但你指望我。指望我说出一些让我的废话有意义的东西！一些重要的东西！}
{135}{}{为什么我不能成为重要的人呢？}
{136}{}{哞！哞！哞！哞！}
{137}{}{哞！哞！哞！哞！}
{138}{}{我无聊了。更糟的是，我被坑了。再也不好玩了。你有没有觉得自己就像线偶，他们懒得挂你？我散落一地！}
{139}{}{哞！哞！哞！哞！}
{140}{}{够了，别再提辐牛了！你会开始闻起来像它们！然后大家都会吐！}
{141}{}{你知道吗，我曾经疯过，直到我经历了仆役过程。我曾经疯过，但现在我只是支离破碎。碎片！碎片！}
{142}{}{混蛋，我是个拼图！你能帮我拼起来吗？}
{143}{}{我真不敢相信还有人在和我说话……}
{144}{}{这都是个游戏，你知道吗。一个游戏，而我是其中的一块。有个孩子非常生气，于是他开始踩我。踩啊踩啊踩，最后我就碎了！}
{145}{}{也许他们会挖出我的大脑！挖出我的大脑，把我变成他们的宠物！来，丹恩！接住球，丹恩！咬他们，丹恩！咬他们，丹恩！咬他们，丹恩！执行他们，你这个脑残的狗！}
{146}{}{你知道他们为什么叫他主人吗？}
{147}{}{生活很糟，但死亡更糟，我们不能回到过去阻止我们的出生，那有什么意义呢？}
{148}{}{我想他们明白了，混蛋！他们知道仆役过程毁了你！他们知道这个‘洗礼机’只是乱搞……}
{149}{}{我叫丹恩。我是个维京人。我喜欢鸭子。我抢劫和掠夺！你愿意和我一起抢劫和掠夺吗？}
{150}{}{哦，天哪！主人，不是上帝！至少我还记得自己的名字。至少我还有这个。大多数其他的失败者在被枪毙前都没有。尸体也不好看。夜行者的靶子！}
{151}{}{然后有些人彻底失去了理智。我希望他们死了。}
{152}{}{我想给我的第一个孩子取名叫辐射。我曾经有个儿子，但辐射在他妈妈的肚子里吞噬了他。}
{153}{}{混蛋！你刚才笑了！你以前根本不在乎他或他的母亲！}
{154}{}{变种人不能繁殖。我们都将成为变种人！你不知道这意味着什么吗！世界将会不育！不育！不育！我们不会繁殖！我们都会死！}
{155}{}{阻止他！阻止他！阻止他！有人让他停下来！}
{156}{}{主人！我不该说什么。我听到夜行者在哭，我为它感到难过。}
{157}{}{什么是邪恶？邪恶就是当善良被彻底搞砸！邪恶就是当勇敢的人不能再勇敢！邪恶是卑鄙的变位词！一定要有道德标准！}
{158}{}{闭嘴，混蛋！道德标准！肯定不在这里！}
{159}{}{你知道吗，我曾经认为宗教是高尚的召唤，也许是；但你不能盲目走进去，否则他们会控制你的大脑。}
{160}{}{……僵尸是对上帝的耻辱，你知道的。}
{161}{}{但为什么上帝要造出如此容易破碎的人？}
{162}{}{我想我现在终于可以回答一些问题了。抱歉花了这么久。}
{163}{}{这个地方是用来干什么的？}
{164}{}{告诉我关于夜行者的事。}
{165}{}{这里发生了什么？}
{166}{}{他们对你做了什么？}
{167}{}{谁是主人？}
{168}{}{你想死吗？我可以让你解脱。}
{169}{}{你听起来真蠢！}
{170}{}{这是洗礼池。他们在这里制造仆役。当信徒被洗脑后，他们把他们带到这里进行过程。少数人能活下来……}
{171}{}{大多数人失去理智，但他们仍然有用。他们把他们扔到楼下，对他们大喊大叫关于主人的事，然后四处游荡。你见过僵尸。很好的奴隶劳动力——和士兵……}
{172}{}{约翰·布朗的尸体在坟墓中腐烂。约翰·布朗的尸体在坟墓中腐烂，约翰·布朗的尸体在坟墓中腐烂，而主人正在坑我们……}
{173}{}{停下。再这样下去我就要崩溃了。}
{174}{}{告诉我关于夜行者的事。}
{175}{}{这里发生了什么？}
{176}{}{他们对你做了什么？}
{177}{}{谁是主人？}
{178}{}{你想死吗？我可以让你解脱。}
{179}{}{哎呀！我再也无法保持完整了！哇！哇！哇！}
{180}{}{他们是变种人。我听过他们说话。我很隐秘。我知道他们所有的秘密。他们恨我。非常恨我。}
{181}{}{我完蛋了，但这只是大教堂坑害计划的第一阶段。当仆役被彻底洗脑后，他们进入第二阶段。那就是主人用FEV-2给他们洗礼的时候！}
{182}{}{大多数人就死在那里。但那些幸存下来的人会变成变种人。大变种人。夜行者！主人认为只有夜行者能活下来。他想让所有人都变成夜行者，因为他们很强！}
{183}{}{你知道所有这些和平与统一的废话吗？对主人来说，这真的不是废话。他真的认为他在拯救世界！}
{184}{}{不育！我们都将成为丑陋的、不育的怪物！不育！不育！不育！我不叫埃罗尔！不育！}
{185}{}{告诉我关于夜行者的事。}
{186}{}{这里发生了什么？}
{187}{}{他们对你做了什么？}
{188}{}{谁是主人？}
{189}{}{你想死吗？我可以让你解脱。}
{190}{}{哞！哞！哞！辐牛夜行者，来了！来点不育的牛奶！}
{191}{}{我们所知的世界末日。变种人大军在避难所，不要怪我，这是主人的错。当我们有了统一，那时主人的乐趣才真正开始。}
{192}{}{告诉我关于夜行者的事。}
{193}{}{什么样的乐趣？}
{194}{}{他们对你做了什么？}
{195}{}{谁是主人？}
{196}{}{你想死吗？我可以让你解脱。}
{197}{}{哎呀！我再也无法保持完整了！哇！哇！哇！}
{198}{}{把我扔进化学品里，给我打满洞，放大声的噪音给我听。就是这种事。试图把我变成我不是的东西。父母总是这样做。}
{199}{}{我真的很痛。}
{200}{}{这个地方是用来干什么的？}
{201}{}{告诉我关于夜行者的事。}
{202}{}{这里发生了什么？}
{203}{}{谁是主人？}
{204}{}{你想死吗？我可以让你解脱。}
{205}{}{你听起来真蠢！}
{206}{}{我以前也很会伤害人。我是个种马！见鬼，我是个神！一个强硬的神混蛋！但这还不够！我是个踏步机战斗机器！但现在我……我……帮帮我……}
{207}{}{你知道吗，夜行者说他比他们还丑。这意味着他一定是个极其丑陋的混蛋。}
{208}{}{他是那个男人！有计划的男人！他计划因为他爱我们！如果世界挡住他的路，那就去他的！因为这就是爱的全部！}
{209}{}{这个地方是用来干什么的？}
{210}{}{告诉我关于夜行者的事。}
{211}{}{这里发生了什么？}
{212}{}{他们对你做了什么？}
{213}{}{你想死吗？我可以让你解脱。}
{214}{}{你听起来真蠢！}
{215}{}{爱是让仙人掌生长的东西！爱是让辐牛哞叫的东西！爱是搞砸，是搞砸你的生活！我恨爱！我爱恨！如果主人恨我们，我们就没事了！}
{216}{}{你的良心在哪里，人？你认为生活应该是没有痛苦的美丽画面吗？生活就是痛苦！痛苦，以及我们决定如何处理它！}
{217}{}{应对！爱！搞砸！恨！冒险！无聊的人！打混蛋！和其他混蛋交朋友！逃避错误！面对错误！辐射！}
{218}{}{生孩子，然后一遍又一遍地做同样的事情，有时更好，有时更糟！}
{219}{}{这就是生活，伙计！就像喝醉了；从一个角度看，它是一个糟糕的尴尬！从另一个角度看，它感觉很棒！但这都是一样的！这就是生活！}
{220}{}{啊哈！哈哈！哈哈！哈哈！你说得对！我们都很蠢！你不明白吗？哈哈！哈哈！哈哈！}
{221}{}{我现在有点苦涩。就像被雨淋湿的橙白毫。哈哈！我喜欢这个说法！我想我会一直重复它！我现在有点苦涩。就像被雨淋湿的橙白毫……}
{222}{}{[更多]}
