{100}{}{你看到一个垂死的变种人。}
{101}{}{这个变种人奄奄一息。}
{102}{}{你看到一个变种人的尸体。}
{103}{}{这个变种人已经死了。}
{104}{}{太快了……我的兄弟们都没了……帮不了他们……}
{105}{}{你是谁？}
{106}{}{我，我是……我记不清了……曾是……的领袖……也许我的全息磁盘…… [变种人虚弱地递给你一个沾满血的全息磁盘]}
{107}{}{你从哪里来？}
{108}{}{我们……我们在寻找优质目标……来自……西北方。}
{109}{}{是谁派你来的？}
{110}{}{父亲……你在哪里，父亲？……是的，主人…… [变种人呼出最后一口气，倒下了]}
{111}{}{呃……啊……}
{112}{}{主人……}
{113}{}{兄弟们……在哪里……？}
