{100}{}{清除废料场的帮派。}
{101}{}{如果你不消灭所有帮派，他们会来报复。}
{102}{}{墓穴帮和傻瓜帮争夺对发电机的控制权。}
{200}{}{为傻瓜帮侦查}
{201}{}{你需要为傻瓜帮侦查墓穴帮的情况。}
{300}{}{为墓穴帮侦查}
{301}{}{你需要为墓穴帮侦查傻瓜帮的情况。}
{400}{}{发电机}
{401}{}{没有发电机，村民的生活会更加贫困。}
{402}{}{发电机是废料场最重要的东西。谁控制了它，谁就控制了废料场。}
{403}{}{有裸露的电线从发电机延伸出去。}
{500}{}{菲尔的狗问题。}
{501}{}{菲尔和一只狗有些麻烦。}
{502}{}{那只狗看起来饿得能吃掉菲尔。}
