{100}{}{你看到一个农民。}
{101}{}{你看到菲尔。}
{102}{}{那不是我的狗！}
{103}{}{没错，干掉那畜生！}
{104}{}{如果我是你，我才不会相信那畜生。那东西是个杀手。}
{105}{}{先生，}
{106}{}{女士，}
{107}{}{如果你能把那该死的狗赶走，我会非常高兴。}
{108}{}{为什么？}
{109}{}{不，我只处理重要的事情。}
{110}{}{它是从哪里来的？}
{111}{}{嗯。}
{112}{}{也许你可以说死它。}
{113}{}{它不让我们回家，这就是原因。}
{114}{}{好吧。}
{115}{}{那不是你的狗吗？}
{116}{}{它是一个旅行者的“宠物”。当旅行者死了，这该死的狗就赖在我家门口不走。已经好几天了。}
{117}{}{哦。}
{118}{}{那个旅行者是谁？}
{119}{}{旅行者长什么样？}
{120}{}{我不知道。就是个家伙。他说他来自东方。就像有人能穿过东方的死地一样。他惹上了Gizmo，试图干涉Gizmo的生意。}
{121}{}{所以，Gizmo让几个手下揍了他一顿，把他从赌场屋顶扔了下来。旅行者摔断了脖子，死了。狗很生气。}
{122}{}{旅行者长什么样？}
{123}{}{哦，那家伙高个子，黑头发，边缘有点灰白。他全身穿着黑色皮衣，就像在沙漠里是个好主意，还带着一把霰弹枪。}
{124}{}{他有个奇怪的口音。狗是他的忠实伙伴，寸步不离。}
{125}{}{感谢你的八卦。}
{126}{}{我讨厌那条狗。}
{127}{}{谢谢你的帮助。}
{128}{}{你获得了50点经验值。}
