{100}{}{[更多]}
{101}{}{[完成]}
{102}{}{混蛋！你又受伤了，你这个蠢货！}
{103}{}{混蛋！你又受伤了，你这个蠢女人！}
{105}{}{混蛋！你就不能听听和平的信息吗！}
{106}{}{嘿，我只是想帮忙！}
{107}{}{我想问几个问题。}
{108}{}{给我治伤吧，医生。}
{109}{}{你的态度真差。}
{110}{}{医生，我需要喝一杯！有酒精吗？}
{111}{}{再这样下去，你就需要医生了。}
{112}{}{哎哟！哎哟！嗯嗯！}
{113}{}{你想干什么？！你们这些混蛋永远学不会吗？我厌倦了把我的才能浪费在失败者身上。下次射准点！别让他们打到你。}
{114}{}{我寡不敌众！}
{115}{}{你是个专治混蛋的医生吗？}
{116}{}{也许我该拿你练练靶。}
{117}{}{无能的混蛋！你又需要治疗了！希望下次他们能干掉你！}
{118}{}{谢谢你的精神支持，医生。}
{119}{}{我也希望他们能抓到你……}
{120}{}{如果他们抓到我，你会先倒下。}
{121}{}{你有什么毛病，混蛋？也许我该让你睡一觉，蠢货！}
{122}{}{医生，你经常让人睡觉吗？}
{123}{}{最好别试。}
{124}{}{我打盹，你就完蛋，混蛋！}
{125}{}{愚蠢的人不会帮助事业！你为什么要打扰我？我可是个很忙的医生，混蛋！你需要我还是不需要？}
{126}{}{是什么让你这么忙？}
{127}{}{当然，医生。}
{128}{}{现在不需要。}
{129}{}{医生，你的诊断是什么？}
{130}{}{我不是图书馆！你去外面找答案！现在出去！}
{131}{}{好吧！总是给你补补补！修修修！混蛋！}
{132}{}{我听说他们对你说了很多坏话……}
{133}{}{大师的敌人会不择手段地诋毁信徒。}
{134}{}{医生，你发过誓的。做好你的工作。}
{135}{}{算了。我不能信任你。}
{136}{}{治好我，否则你就死定了，医生！}
{137}{}{这应该可以……}
{138}{}{哎哟！！}
{139}{}{哈哈哈！}
{140}{}{你叫得像个女人！哈哈哈！}
{141}{}{女人不该在男人的世界里玩！哈哈哈！}
{142}{}{去死吧！你是想治好还是想当个混蛋？}
{143}{}{你这个失败者！为什么不爬到辐光里去舔水坑？愚蠢的醉鬼混蛋！}
{144}{}{也许有一天你需要医生，而医生却不在。疯子混蛋！你想治好吗？也许我还能顺便治治你脑子里的屎！}
{145}{}{好吧——做吧，闭嘴！}
{146}{}{去死吧。}
{147}{}{闭嘴，给我诊断。}
{148}{}{你这个蠢驴！你蠢得感觉不到疼痛。你让我想起低等生物！}
{149}{}{我听说你既疯狂又愚蠢！}
{150}{}{哈哈！你真蠢！我刚给了你致命的毒药！哈哈哈！}
{151}{}{这会很疼！}
{152}{}{啊啊啊！}
{153}{}{你叫得像被阉割的猪！哈哈哈！}
{154}{}{你是个白痴！质量比数量重要！你以为夜行者在寡不敌众时会在乎吗？去找你妈哭诉吧，小宝宝！现在，你想变好吗？}
{155}{}{闭嘴，否则我就割掉你的声带！像狗一样给你去声！哈哈哈！现在你想康复吗？}
{156}{}{我是医生，不是啦啦队长！你需要治疗吗？}
{157}{}{我在发抖，混蛋！现在，你想康复吗？}
{158}{}{做吧。别耍我！}
{159}{}{当然想。这地方肯定有个真正的医生。}
{160}{}{先看看有什么地方坏了。}
{161}{}{夜行者喜欢那样。我有时给他们药。没人注意吴医生。他们都是混蛋！现在，你想治好吗？}
{162}{}{给我补上，医生！}
{163}{}{如果夜行者不信任你，我也不信。我走了。}
{164}{}{白痴！大教堂很忙！统一让吴医生很忙！现在，你想治好吗？}
{165}{}{现在到了有趣的部分！}
{166}{}{这应该可以……}
{167}{}{真是个傻瓜！我听过更多孩子的尖叫声！哈哈哈！}
{168}{}{我让那个女人尖叫了！哈哈哈！}
{169}{}{混蛋！蠢货！我很忙，而你却来烦我！去你的！滚出去，废物！现在！}
{170}{}{你健康得像头辐牛，但不如它聪明！滚出去，你这个疑病症的混蛋！}
{171}{}{你受了些伤。我可以治好，蠢货，只要你保持不动！}
{172}{}{你把身体搞得一团糟。你一定是个真正的白痴。我可以让你解脱，也可以治好你。}
{173}{}{现在不需要。}
{174}{}{好吧。但我希望今天能给你做尸检！}
{175}{}{哎哟！你这个小……}
{176}{}{现在滚出去，别再回来！}
{177}{}{好吧，我治好你！}
{178}{}{这应该能彻底治好你！}
{179}{}{那就滚吧，混蛋！我很快就会对着你的尸体大笑。}
{180}{}{你这个小混蛋！你以为你是谁，敢来打扰吴医生？愚蠢的蠢货！}
{181}{}{你受了些伤。我可以治好，蠢货，只要你保持不动！}
{182}{}{至少有五根骨头断了，你失了很多血。做个白痴对健康有害！你想治好吗？}
{183}{}{这要看“治好”的定义。你可以治疗我，医生。}
{184}{}{我走了。}
