{100}{}{你看到杜根，一个对Nuka-Cola情有独钟的人。}
{101}{}{你看到一个非常高瘦的男人，戴着眼镜。他手里紧握着一瓶Nuka-Cola。}
{102}{}{有什么事吗？}
{103}{}{我只是随便看看，谢谢。}
{104}{}{你在这里做什么？}
{105}{}{你对Nuka-Cola这么着迷是为什么？}
{106}{}{这里谁负责？}
{107}{}{啊，没事了。}
{108}{}{啊，Cola，好喝吗？}
{109}{}{那就别浪费我的时间。}
{110}{}{我经常思考人生，并帮助刀锋帮理解Nuka-Cola的真正意义。}
{111}{}{Nuka-Cola有什么好？}
{112}{}{就这样吗？这好像对别人没什么帮助。}
{113}{}{你每天喝多少这种东西？}
{114}{}{我能再问你点别的吗？}
{115}{}{哦，好吧。再见。}
{116}{}{这是生命的源泉……其实，如果我每小时不喝一瓶，就会头痛欲裂。}
{117}{}{所以呢？[杜根对你挑了挑眉。]}
{118}{}{大约每天5升。}
{119}{}{你应该去找剃刀，她是这里的负责人。}
{120}{}{我是我见过最笨的人——除了你。滚出去！}
{121}{}{我需要再来一瓶Nuka-Cola！}
{122}{}{我的头发去哪了！}
{123}{}{碳酸水、焦糖色、阿斯巴甜、磷酸、苯甲酸钾（保护口味）、天然香料、柠檬酸、咖啡因}
{124}{}{可惜我们没有无糖的了。}
{125}{}{那些矮个子女人去哪了？}
