#
# This is all of the combat messages used by combat.c
# Note: all %d values will be filled with a number greater than 1
#
# Truly Generic strings (no need for gender/number issues)
#
{100}{}{你需要 %d 点行动点。}
{101}{}{弹药耗尽。}
{102}{}{目标超出射程。}
{103}{}{附近有敌对生物时无法结束战斗。}
{104}{}{你的瞄准被阻挡。}
{105}{}{双臂受伤无法使用武器。}
{106}{}{单臂受伤无法使用双手武器。}
{107}{}{你的力量不足以正确使用这件武器。}
{108}{}{ 和}
#
# Combat Flag Strings (all of these happen to you, the MALE player)
#
{200}{}{被击晕}
{201}{}{被击倒}
{202}{}{左腿受伤}
{203}{}{右腿受伤}
{204}{}{左臂受伤}
{205}{}{右臂受伤}
{206}{}{被致盲}
{207}{}{被杀死}
{208}{}{命中}
{209}{}{重击}
{210}{}{着火}
{211}{}{护甲被无视}
{212}{}{武器爆炸}
{213}{}{武器损毁}
{214}{}{武器掉落}
{215}{}{失去下一回合}
{216}{}{击中自己}
{217}{}{失去剩余弹药}
{218}{}{射出哑弹}
{219}{}{伤到自己}
{220}{}{随机命中}
{221}{}{随机肢体受损}
{222}{}{被碎片击中}
#
# Combat Flag Strings (all of these happen to you, the FEMALE player)
#
{250}{}{被击晕}
{251}{}{被击倒}
{252}{}{左腿受损}
{253}{}{右腿受损}
{254}{}{左臂受损}
{255}{}{右臂受损}
{256}{}{失明}
{257}{}{被杀死}
{258}{}{命中}
{259}{}{致命一击}
{260}{}{着火}
{261}{}{护甲被无视}
{262}{}{武器爆炸}
{263}{}{武器损毁}
{264}{}{武器掉落}
{265}{}{失去下回合行动}
{266}{}{击中自己}
{267}{}{失去剩余弹药}
{268}{}{发射哑弹}
{269}{}{伤到自己}
{270}{}{随机命中}
{271}{}{随机肢体受损}
{272}{}{被碎片击中}
#
# Combat Flag Strings (all of these happen to a male)
#
{300}{}{被击晕}
{301}{}{被击倒}
{302}{}{他的左腿受损}
{303}{}{他的右腿受损}
{304}{}{他的左臂受损}
{305}{}{右臂瘫痪}
{306}{}{失明}
{307}{}{被杀死}
{308}{}{命中}
{309}{}{重击}
{310}{}{着火}
{311}{}{护甲被绕过}
{312}{}{武器爆炸}
{313}{}{武器损毁}
{314}{}{武器掉落}
{315}{}{失去下一回合}
{316}{}{击中自己}
{317}{}{失去剩余弹药}
{318}{}{发射哑弹}
{319}{}{伤到自己}
{320}{}{随机命中}
{321}{}{随机肢体瘫痪}
{322}{}{被碎片击中}
#
# Combat Flag Strings (all of these happen to a female)
#
{400}{}{被击昏}
{401}{}{被击倒}
{402}{}{左腿瘫痪}
{403}{}{右腿瘫痪}
{404}{}{左臂瘫痪}
{405}{}{右臂瘫痪}
{406}{}{失明}
{407}{}{被杀死}
{408}{}{命中}
{409}{}{重击}
{410}{}{着火}
{411}{}{护甲被绕过}
{412}{}{她的武器爆炸了}
{413}{}{她的武器被毁了}
{414}{}{她的武器掉落了}
{415}{}{失去了下一回合}
{416}{}{击中了自己}
{417}{}{失去了所有弹药}
{418}{}{射出了哑弹}
{419}{}{伤到了自己}
{420}{}{随机命中}
{421}{}{随机致残了一处肢体}
{422}{}{被碎片击中}
#
# Miscellaneous combat messages (all of these happen to you, the male player)
# Note: the first %s will be replaced by the value of line 506, which
#          should be the language's equivalent to 2nd person male singular,
#          which is "You" in English. The first letter of line 506 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 509
#          where the second %s is the name of another creature
{506}{}{你}
{509}{}{哎呀！%s 被击中而不是 %s！}
{511}{}{%s 在 %s 被重击，造成 %d 点伤害}
{512}{}{%s 在 %s 被击中，造成 %d 点伤害}
{513}{}{%s 被击中，造成 %d 点伤害}
{514}{}{%s 严重失误}
{515}{}{%s 未命中}
{520}{}{%s 被重击，造成 %d 点伤害}
{521}{}{%s 在 %s 被重击，造成 1 点伤害}
{522}{}{%s 在 %s 被击中，造成 1 点伤害}
{523}{}{%s 被击中，造成 1 点伤害}
{524}{}{%s 被重击，造成 1 点伤害}
{525}{}{%s 在 %s 被重击，没有造成伤害}
{526}{}{%s 在 %s 被击中，没有造成伤害}
{527}{}{%s 被击中，没有造成伤害}
{528}{}{%s 被重击，没有造成伤害}
{533}{}{%s 严重失误并受到 1 点伤害}
{534}{}{%s 严重失误并受到 %d 点伤害}
#
# Miscellaneous combat messages (all of these happen to you, the female player)
# Note: the first %s will be replaced by the value of line 556, which
#          should be the language's equivalent to 2nd person female singular,
#          which is "You" in English. The first letter of line 556 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 559
#          where the second %s is the name of another creature
{556}{}{你}
{559}{}{糟糕！%s 被击中而不是 %s！}
{561}{}{%s 在 %s 受到重创，损失 %d 点生命值}
{562}{}{%s 在 %s 受到攻击，损失 %d 点生命值}
{563}{}{%s 受到攻击，损失 %d 点生命值}
{564}{}{%s 严重失误}
{565}{}{%s 未命中}
{570}{}{%s 受到重创，损失 %d 点生命值}
{571}{}{%s 在 %s 受到重创，损失 1 点生命值}
{572}{}{%s 在 %s 受到攻击，损失 1 点生命值}
{573}{}{%s 受到攻击，损失 1 点生命值}
{574}{}{%s 受到重创，损失 1 点生命值}
{575}{}{%s 在 %s 受到重创，但未造成伤害}
{576}{}{%s 在 %s 受到攻击，但未造成伤害}
{577}{}{%s 受到攻击，但未造成伤害}
{578}{}{%s 受到重创，但未造成伤害}
{583}{}{%s 严重失误并损失 1 点生命值}
{584}{}{%s 严重失误并损失 %d 点生命值}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: the first %s is the name of the male creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 609
#          where the second %s is the name of another creature
#
{608}{}{糟糕！%s 被击中而不是你！}
{609}{}{糟糕！%s 被击中而不是 %s！}
{611}{}{%s 在 %s 受到重创，损失 %d 点生命值}
{612}{}{%s 在 %s 受到攻击，损失 %d 点生命值}
{613}{}{%s 受到攻击，损失 %d 点生命值}
{614}{}{%s 严重失误}
{615}{}{%s 未命中}
{620}{}{%s 受到重创，损失 %d 点生命值}
{621}{}{%s 在 %s 受到重创，损失 1 点生命值}
{622}{}{%s 在 %s 受到攻击，损失 1 点生命值}
{623}{}{%s 受到攻击，损失 1 点生命值}
{624}{}{%s 受到重创，损失 1 点生命值}
{625}{}{%s 在 %s 受到重创，但未造成伤害}
{626}{}{%s在%s被击中，但没有造成伤害}
{627}{}{%s被击中，但没有造成伤害}
{628}{}{%s被严重击中，但没有造成伤害}
{633}{}{%s严重失误，自己受到1点伤害}
{634}{}{%s严重失误，自己受到%d点伤害}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: the first %s is the name of the female creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 709
#          where the second %s is the name of another creature
#
{708}{}{糟糕！%s被击中了，而不是你！}
{709}{}{糟糕！%s被击中了，而不是%s！}
{711}{}{%s在%s被严重击中，受到%d点伤害}
{712}{}{%s在%s被击中，受到%d点伤害}
{713}{}{%s被击中，受到%d点伤害}
{714}{}{%s严重失误}
{715}{}{%s未击中}
{720}{}{%s被严重击中，受到%d点伤害}
{721}{}{%s在%s被严重击中，受到1点伤害}
{722}{}{%s在%s被击中，受到1点伤害}
{723}{}{%s被击中，受到1点伤害}
{724}{}{%s被严重击中，受到1点伤害}
{725}{}{%s在%s被严重击中，但没有造成伤害}
{726}{}{%s在%s被击中，但没有造成伤害}
{727}{}{%s被击中，但没有造成伤害}
{728}{}{%s被严重击中，但没有造成伤害}
{733}{}{%s严重失误，自己受到1点伤害}
{734}{}{%s严重失误，自己受到%d点伤害}
#
# Hit Locations (by art_num alias)
#
# regular humans
#
{1110}{}{头部}
{1111}{}{左臂}
{1112}{}{右臂}
{1113}{}{躯干}
{1114}{}{右腿}
{1115}{}{左腿}
{1116}{}{眼睛}
{1117}{}{腹股沟}
{1118}{}{未指定}
#
# Brahmin (Mutant 2-Headed Cows)
#
{1150}{}{头部}
{1151}{}{左后腿}
{1152}{}{右后腿}
{1153}{}{躯干}
{1154}{}{右前腿}
{1155}{}{左前腿}
{1156}{}{眼睛}
{1157}{}{乳房}
{1158}{}{未指定}
#
# dogs
#
{1160}{}{头部}
{1161}{}{后腿}
{1162}{}{后腿}
{1163}{}{身体}
{1164}{}{前腿}
{1165}{}{前腿}
{1166}{}{眼睛}
{1167}{}{腹股沟}
{1168}{}{未指定}
#
# Mr. Handy
#
{1170}{}{中央处理器}
{1171}{}{机械臂}
{1172}{}{机械臂}
{1173}{}{框架}
{1174}{}{驱动器}
{1175}{}{驱动器}
{1176}{}{传感器}
{1177}{}{调节器}
{1178}{}{未指定}
#
# Super Mutants
#
{1180}{}{头部}
{1181}{}{左臂}
{1182}{}{右臂}
{1183}{}{躯干}
{1184}{}{右腿}
{1185}{}{左腿}
{1186}{}{眼睛}
{1187}{}{腹股沟}
{1188}{}{未指定}
#
# Mole-Rat
#
{1190}{}{头部}
{1191}{}{左爪}
{1192}{}{右爪}
{1193}{}{身体}
{1194}{}{右腿}
{1195}{}{左腿}
{1196}{}{眼睛}
{1197}{}{腹股沟}
{1198}{}{未指定}
#
# big humans and mutants
#
{1210}{}{头部}
{1211}{}{左臂}
{1212}{}{右臂}
{1213}{}{躯干}
{1214}{}{右腿}
{1215}{}{左腿}
{1216}{}{眼睛}
{1217}{}{腹股沟}
{1218}{}{未指定}
#
# Radscorpion
#
{1220}{}{头部}
{1221}{}{尾巴}
{1222}{}{爪子}
{1223}{}{甲壳}
{1224}{}{前腿}
{1225}{}{后腿}
{1226}{}{眼睛}
{1227}{}{大脑}
{1228}{}{未调用}
#
# Floater
#
{1230}{}{头部}
{1231}{}{嘴巴}
{1232}{}{前嘴}
{1233}{}{身体}
{1234}{}{浮囊}
{1235}{}{尾巴}
{1236}{}{神经节}
{1237}{}{产卵器}
{1238}{}{未调用}
#
# masrat? a rat perhaps?
#
{1240}{}{头部}
{1241}{}{左爪}
{1242}{}{右爪}
{1243}{}{身体}
{1244}{}{右腿}
{1245}{}{左腿}
{1246}{}{眼睛}
{1247}{}{腹股沟}
{1248}{}{未调用}
#
# Centaur
#
{1250}{}{头部}
{1251}{}{左臂}
{1252}{}{右臂}
{1253}{}{身体}
{1254}{}{右腿}
{1255}{}{左腿}
{1256}{}{眼睛}
{1257}{}{腹股沟}
{1258}{}{未指定}
#
# human midgets and children
#
{1270}{}{头部}
{1271}{}{左臂}
{1272}{}{右臂}
{1273}{}{躯干}
{1274}{}{右腿}
{1275}{}{左腿}
{1276}{}{眼睛}
{1277}{}{腹股沟}
{1278}{}{未指定}
#
# Overseer
#
{1460}{}{头部}
{1461}{}{左臂}
{1462}{}{右臂}
{1463}{}{躯干}
{1464}{}{右腿}
{1465}{}{左腿}
{1466}{}{眼睛}
{1467}{}{腹股沟}
{1468}{}{未指定}
#
# Gizmo
#
{1490}{}{头部}
{1491}{}{左臂}
{1492}{}{右臂}
{1493}{}{躯干}
{1494}{}{右腿}
{1495}{}{左腿}
{1496}{}{眼睛}
{1497}{}{腹股沟}
{1498}{}{未指定}
#
# The Master!
#
{1500}{}{头部}
{1501}{}{???}
{1502}{}{???}
{1503}{}{机架}
{1504}{}{???}
{1505}{}{???}
{1506}{}{眼睛}
{1507}{}{中央处理器}
{1508}{}{未指定}
#
# Death Claw
#
{1510}{}{头部}
{1511}{}{左臂}
{1512}{}{右臂}
{1513}{}{躯干}
{1514}{}{右腿}
{1515}{}{左腿}
{1516}{}{眼睛}
{1517}{}{腹股沟}
{1518}{}{未指定}
#
# Mantis
#
{1520}{}{头部}
{1521}{}{捕食足}
{1522}{}{捕食足}
{1523}{}{腹部}
{1524}{}{腿部}
{1525}{}{翅膀}
{1526}{}{眼睛}
{1527}{}{中胸}
{1528}{}{未指定}
#
# Robobrain
#
{1530}{}{中央处理器}
{1531}{}{操控器}
{1532}{}{操控器}
{1533}{}{机架}
{1534}{}{动力装置}
{1535}{}{动力装置}
{1536}{}{传感器}
{1537}{}{调节器}
{1538}{}{未调用}
#
# Eyeball (Robot)
#
{1540}{}{中央处理器}
{1541}{}{操控器}
{1542}{}{操控器}
{1543}{}{框架}
{1544}{}{动力装置}
{1545}{}{动力装置}
{1546}{}{传感器}
{1547}{}{调节器}
{1548}{}{未调用}
#
# Mutant Pig Rat (small Mole-Rat)
#
{1550}{}{头部}
{1551}{}{左爪}
{1552}{}{右爪}
{1553}{}{身体}
{1554}{}{右腿}
{1555}{}{左腿}
{1556}{}{眼睛}
{1557}{}{腹股沟}
{1558}{}{未调用}
#
# Deathclaw Egg
#
{1580}{}{外壳}
{1581}{}{外壳}
{1582}{}{外壳}
{1583}{}{外壳}
{1584}{}{外壳}
{1585}{}{外壳}
{1586}{}{外壳}
{1587}{}{炮弹}
{1588}{}{意外的}

#
# Critical Hit Messages
#
# 5000 series - men (including generics)
#
{5000}{}{，真的很痛}
{5001}{}{。造成了严重的伤口}
{5002}{}{，没有护甲防御}
{5003}{}{。这次攻击让他失去意识}
{5004}{}{。这一击让他倒在地上}
{5005}{}{。对头部的重击使他昏迷}
{5006}{}{。攻击粉碎了太阳穴。晚安，格蕾西}
{5007}{}{，死亡瞬间降临}
{5008}{}{，导致严重的网球肘}
{5009}{}{，把手臂推开}
{5010}{}{，留下一个大淤青}
{5011}{}{，使左臂残废}
{5012}{}{，左臂仅靠皮肤悬挂}
{5013}{}{。那只手臂现在看起来像个血淋淋的断肢}
{5014}{}{，留下一个残废的右臂}
{5015}{}{。他的右臂被这强力一击粉碎}
{5016}{}{在一次猛烈的打击中}
{5017}{}{穿透护甲}
{5018}{}{，造成额外的伤害}
{5019}{}{没有护甲，击倒对手}
{5020}{}{，打掉他的气息，他瘫倒在地退出战斗}
{5021}{}{。不幸的是，他的脊椎现在从正面清晰可见}
{5022}{}{对他的腿造成了重大伤害}
{5023}{}{，像保龄球瓶一样被击倒在地}
{5024}{}{，将他撞翻并使那条腿残废}
{5025}{}{，把膝盖撞到下一个镇。他倒下了}
{5026}{}{。失去一条腿的剧痛让他放弃}
{5027}{}{造成了一些额外的痛苦}
{5028}{}{ 导致失明，对他来说真不幸}
{5029}{}{，而且没有防护，造成剧烈的疼痛}
{5030}{}{，一记重击让他失明}
{5031}{}{。失去一只眼睛对他来说太过沉重，他倒在了地上}
{5032}{}{，可悲的是，他忙于感受脑袋上的风，没注意到死亡的临近}
{5033}{}{。哎哟！这肯定很疼}
{5034}{}{，而且他也没穿护裆}
{5035}{}{，没有防护，他痛苦地倒下}
{5036}{}{。疼痛对他来说太过强烈，他像破布一样倒下}
{5037}{}{。他喃喃道“妈妈”，眼睛翻白}
#
# series 5100 - women
#
{5100}{}{，真的很痛}
{5101}{}{。造成了严重的伤口}
{5102}{}{ 没有护甲}
{5103}{}{。这次重击让她失去意识}
{5104}{}{。这一击把她打倒在地}
{5105}{}{。强烈的头部重击让她昏迷}
{5106}{}{。攻击粉碎了她的太阳穴。晚安，格雷西}
{5107}{}{，死亡瞬间降临}
{5108}{}{，导致严重的网球肘}
{5109}{}{，将手臂推开}
{5110}{}{，留下一个大淤青}
{5111}{}{，致使左臂残废}
{5112}{}{。左臂几乎与肩膀脱离}
{5113}{}{。那只手臂现在看起来像个血淋淋的断肢}
{5114}{}{，留下了残废的右臂}
{5115}{}{。她的右臂被打成了肉酱}
{5116}{}{ 在一次猛烈的打击中}
{5117}{}{，穿透了她的防御}
{5118}{}{，造成额外的伤害}
{5119}{}{ 没有护甲，将女战士击倒在地}
{5120}{}{ 击中要害，她瘫倒在地}
{5121}{}{。不幸的是，她的主要器官暴露在光下}
{5122}{}{ 对她的腿造成了严重伤害}
{5123}{}{，把她撞倒，就像一次糟糕的相亲}
{5124}{}{，将她击倒并使那条腿致残}
{5125}{}{，膝盖被打得远飞。她迅速倒地}
{5126}{}{。她因腿部骨折而痛苦尖叫}
{5127}{}{ 造成额外的痛苦}
{5128}{}{ 导致失明。她痛苦地皱起眉头}
{5129}{}{，没有任何保护，导致剧烈的疼痛}
{5130}{}{。伤口导致严重失明，仿佛还有其他种类的失明}
{5131}{}{。她因致盲攻击而昏厥}
{5132}{}{，遗憾的是，她还没来得及祈祷就见到了她的神灵}
{5133}{}{。她像个男人一样承受住了。也就是说，很痛}
{5134}{}{，将她击倒在地}
{5135}{}{。她的生育能力堪忧，软绵绵地倒下}
#
# series 5200 - children
#
{5200}{}{。小孩开始哭泣}
{5201}{}{。失去意识，小孩倒下}
{5202}{}{。好痛！}
{5203}{}{。一击必中，小孩被打昏}
{5204}{}{，把小孩像破布一样甩来甩去}
{5205}{}{。这孩子的左臂现在疼痛不已}
{5206}{}{，使小孩失去平衡}
{5207}{}{，伴随着一声巨响，打断了那只手臂。泪水开始流淌}
{5208}{}{，轻易地把那只手臂像糖果一样折断}
{5209}{}{。右臂开始肿胀，像个气球}
{5210}{}{，开始哭泣}
{5211}{}{ 在敏感部位}
{5212}{}{。对重要器官的攻击将小孩击倒}
{5213}{}{，把小孩像玩具一样打翻}
{5214}{}{. 这个年轻的孩子将永远无法真正体验生活}
{5215}{}{, 造成了深深的伤口}
{5216}{}{. 攻击将孩子打翻在地，并折断了腿}
{5217}{}{, 对小孩造成了极大的伤害}
{5218}{}{. 年轻的孩子抬头开始哭泣}
{5219}{}{, 使得年轻人失明}
{5220}{}{, 打碎了年轻人的鼻子}
{5221}{}{. 眼睛上方出现了一道伤口，鲜血开始自由流淌}
{5222}{}{, 眼睛像爆裂的葡萄一样炸开。孩子显得困惑}
{5223}{}{ 导致失明。年轻的孩子倒在地上}
{5224}{}{, 打击继续深入小小的脑袋}
{5225}{}{. 孩子看起来困惑且不安}
{5226}{}{, 将这个年轻的目标击倒在地}
#
# series 5300 - Super Mutants
#
{5300}{}{, 伤害了强大的变种人}
{5301}{}{, 击中了要害}
{5302}{}{, 击中了要害并将巨人击倒在地}
{5303}{}{. 巨大的变种人环顾四周片刻，然后瘫倒在地}
{5304}{}{. 头部像巨大的血西瓜一样爆裂}
{5305}{}{, 严重伤害了强大的变种人}
{5306}{}{, 让巨人花了一会儿时间诅咒宇宙}
{5307}{}{, 击中神经迫使巨人抓住他的手臂痛苦不已}
{5308}{}{. 这一击打断了肘部，感觉一定不好受}
{5309}{}{, 打断了粗壮的手臂，变种人的血洒满地面}
{5310}{}{, 让巨人踉跄片刻，然后像被砍倒的树一样倒下}
{5311}{}{, 大量内脏喷涌而出}
{5312}{}{, 将巨人打飞到地上}
{5313}{}{. 变种人踉跄倒下，他的腿几乎无法支撑}
{5314}{}{, 击中要害。变种人在断腿下崩溃}
{5315}{}{. 断腿的痛苦压倒了强大的巨人}
{5316}{}{, 几乎让变种人失明}
{5317}{}{，致盲了现在愤怒的变种人}
{5318}{}{，几乎致盲了变种人，但让他失去平衡}
{5319}{}{。失明的变种人踉跄后退，未能准备好迎接下一次攻击}
{5320}{}{，致盲了现在失去意识的变种人}
{5321}{}{。变种人的眼睛闪烁了一下，然后光芒永远消失了}
#
# series 5400 - Ghouls
#
{5400}{}{。食尸鬼感到惊讶，未能抵挡住这次攻击}
{5401}{}{。这一击埋葬了这个食尸鬼}
{5402}{}{。震惊的食尸鬼手掌猛然张开}
{5403}{}{，穿透他的护甲，击中关键关节}
{5404}{}{，穿透他的护甲，砍掉了手臂}
{5405}{}{。食尸鬼在错误的时机走错了方向，失去了一只眼睛}
{5406}{}{。食尸鬼那里没有穿护甲}
{5407}{}{，没有护甲保护，食尸鬼被致盲}
{5408}{}{，让食尸鬼在最后时刻显得茫然}
#
# series 5500 - Brahmin
#
{5500}{}{，将这头巨兽击倒在地}
{5501}{}{，震晕了两个大脑，击倒了这头巨型动物}
{5502}{}{。变种牛发出一声响亮的惊叫}
{5503}{}{，打断了双头牛的一条腿}
{5504}{}{，严重伤害了变种牛}
{5505}{}{，轻松穿透了巨兽的厚皮}
{5506}{}{，直接穿透了变种牛的两个心脏}
{5507}{}{，一击致盲了两双眼睛}
{5508}{}{，致盲了两个头，震晕了变种牛}
{5509}{}{，完全致盲了双头牛并将其击晕}
{5510}{}{，巨大的变种牛踉跄了一下}
{5511}{}{。双头牛愤怒地颤抖}
{5512}{}{。双头牛痛苦地喷鼻}
{5513}{}{。双头牛对这次彻底的毁灭性攻击感到极为愤怒}
#
# series 5600 - Radscorpions
#
{5600}{}{，将辐射蝎子打翻在地}
{5601}{}{，将头与甲壳分离}
{5602}{}{, 严重伤到尾巴}
{5603}{}{, 给它的钳子造成严重损伤}
{5604}{}{。这一击穿透了辐射蝎坚硬甲壳的缝隙}
{5605}{}{, 毫不停顿地打穿了坚硬的甲壳}
{5606}{}{, 穿透了它的天然护甲，将辐射蝎击倒}
{5607}{}{。辐射蝎无法应对失去内脏的全新感受}
{5608}{}{, 将蝎子打飞，同时打残了几条腿}
{5609}{}{。攻击切入未受保护的腿关节，直接砍断}
{5610}{}{, 严重伤害并致盲这个变种生物}
{5611}{}{, 几乎穿透到大脑。真是碾死了一只大虫子}
{5612}{}{, 几乎穿到大脑，但转而致盲了生物}
{5613}{}{。攻击狡猾且精妙，远超这简单生物的理解}
{5614}{}{。如果它是人，你敢说它肯定很愤怒}
{5615}{}{, 击得这可怜的生物神志不清}
{5616}{}{, 将它的脑袋钉在地上}
#
# series 5700 - Rats
#
{5700}{}{。啮齿类动物的头骨发出几声不健康的响动}
{5701}{}{, 像湿纸袋一样碾碎了啮齿类动物的头骨}
{5702}{}{, 左爪现在看起来有点扁}
{5703}{}{。老鼠的左爪被炸飞}
{5704}{}{。右爪受到重创}
{5705}{}{, 右爪被炸飞}
{5706}{}{。这次攻击重创了老鼠}
{5707}{}{, 严重伤害了老鼠并打得它团团转}
{5708}{}{, 把老鼠的尸体洒了一地}
{5709}{}{, 右腿严重受伤}
{5710}{}{, 在左腿上打出了一个大洞}
{5711}{}{, 由于命中敏感部位造成额外伤害}
{5712}{}{, 让这生物归西了}
#
# series 5800 - Floaters
#
{5800}{}{, 漂浮者掉到了地上}
{5801}{}{, 漂浮者跌到地上，看起来毫无生气}
{5802}{}{，对生物的存续产生严重后果}
{5803}{}{，震慑了这可怕的生物}
{5804}{}{，击中敏感部位，震晕浮游怪}
{5805}{}{。这一击让浮游怪猛烈震动，溅出猩红的血液}
{5806}{}{，这一击在生物体内引发了某种剧烈反应}
{5807}{}{。浮游怪突然燃起熊熊大火}
{5808}{}{，然后疯狂抽搐，像是果冻般颤抖}
{5809}{}{，这一击击中了一个敏感部位}
{5810}{}{。这生物显然非常不安}
#
# series 5900 - Centaurs
#
{5900}{}{，像不良习惯般被推倒，半人马摔倒并被震晕}
{5901}{}{，这一击正中要害}
{5902}{}{，导致重大的神经系统崩溃}
{5903}{}{，你的猛烈攻击震晕了它}
{5904}{}{，使手臂残废}
{5905}{}{，攻击了一处要害，使手臂残废}
{5906}{}{，击倒生物并使其腿部残废}
{5907}{}{，击倒半人马并使其腿部残废，震晕了它}
{5908}{}{，致使头部失明}
{5909}{}{，半人马感到意外。它盲目地踉跄了一会儿}
{5910}{}{，半人马感到意外，轰然倒下}
{5911}{}{，半人马感到意外，它化为一滩血肉模糊的烂泥}
{5912}{}{。攻击的效果不如预期}
#
# series 6000 - Robots
#
{6000}{}{，造成了一些结构性损伤}
{6001}{}{，火花四溅，机器人暂时失去控制}
{6002}{}{，击中关键部件，使机器人失去控制}
{6003}{}{，击中关键部件，导致严重故障}
{6004}{}{。机器人试图进行补偿}
{6005}{}{。机器人竭力进行补偿}
{6006}{}{，命中要害部件，造成严重损伤}
{6007}{}{，造成严重的结构性损伤}
{6008}{}{，击中关键部件，造成严重损伤}
{6009}{}{。机器人在这猛烈的攻击下颤抖}
{6010}{}{，拆解机器人}
{6011}{}{。机器人试图补偿，但失败了，倒在地上}
{6012}{}{。机器人在压力下挣扎，最终倒地}
{6013}{}{，打碎传感器镜片}
#
# series 6100 - Dogs
#
{6100}{}{，把狗打倒在地}
{6101}{}{，正中鼻子}
{6102}{}{。狗倒下了，但仍在呼吸}
{6103}{}{，动物咳出一口血}
{6104}{}{，使腿受伤}
{6105}{}{，使腿受伤。动物试图站立，但失败了}
{6106}{}{。失明的动物痛苦地嚎叫}
{6107}{}{，使可怜的动物失去生育能力}
#
# series 6200 - Manti
#
{6200}{}{，击倒这只变异昆虫}
{6201}{}{，昆虫倒下了}
{6202}{}{。螳螂思考是否继续活下去}
{6203}{}{，使肢体受伤}
{6204}{}{，让螳螂舔舐伤口。它奇怪地握着肢体}
{6205}{}{，绕过甲壳护甲}
{6206}{}{。螳螂发出不似人类的尖叫和颤抖}
{6207}{}{，导致螳螂倒下。一只肢体呈奇怪的形状}
{6208}{}{，撕裂翅膀}
{6209}{}{，绕过甲壳护甲，将螳螂甩来甩去}
{6210}{}{，准确一击使昆虫失明}
#
# series 6300 - Deathclaw
#
{6300}{}{。即便是这头野兽也因这次惊人的攻击而动摇}
{6301}{}{，绕过巨大爪子攻击怪物。死亡爪震动并咆哮}
{6302}{}{。结果是对死亡爪的眼睛造成巨大伤害}
#
# series 6400 - The Master
#
{6400}{}{，突破生物有机防御}
{6401}{}{，给主宰带来严重痛苦}
{6402}{}{，突破生物有机防御，给大师施加压力}
{6403}{}{，用稳固的进攻计划震惊了大师}
{6404}{}{，导致大师系统发生灾难性过载}
{6405}{}{。对大师的攻击似乎没有造成预期的伤害}
{6406}{}{。攻击穿透了生物有机防御，实际上致盲了大师}
#
# series 6500 - The Player
#
{6500}{}{。如果你能活到明天，头痛会伴随你}
{6501}{}{。你的护甲无法抵挡这次精准的打击}
{6502}{}{。你只感受到一瞬间的痛苦，然后陷入黑暗……}
{6503}{}{，穿透了你的护甲。攻击将你击倒在地}
{6504}{}{，震惊让你的视野变黑。片刻后，你发现视力没有恢复}
{6505}{}{。你能清楚地看到自己的身体，而你的头颅在空中飞舞}
{6506}{}{。令人惊讶的是，伤害并没有比平常更严重}
{6507}{}{，让你晕了一下}
{6508}{}{。感受痛苦}
{6509}{}{。攻击让你的手臂失去作用}
{6510}{}{，穿透了你的护甲。攻击如同劈开枯木般折断了你的手臂}
{6511}{}{，穿透了你的护甲。你的手臂现在无力地垂在一旁}
{6512}{}{。淤青看起来不错，也许伤疤会成为聚会的话题}
{6513}{}{，压碎了你的内脏。你只能咯血}
{6514}{}{，让你翻滚不止}
{6515}{}{，将你击飞并折断了你的腿}
{6516}{}{，融化了你的护甲。攻击将你击倒，严重伤害了你的膝盖}
{6517}{}{。断腿的痛苦让你失去意识}
{6518}{}{。这次痛苦的打击让你退缩，但没有其他影响}
{6519}{}{。对你不幸的是，它还导致了立即失明}
{6520}{}{。你花了一会儿才擦掉眼中的血}
{6521}{}{，穿透了你的护甲。你震惊地发现自己再也看不见了}
{6522}{}{。你感到头部有一种奇怪的感觉。你意识到那是即将到来的脑死亡}
{6523}{}{，让你畏缩}
{6524}{}{。你捂住腹股沟，痛苦地倒在地上}
{6525}{}{. 疼痛足以让你失去知觉。哎哟}
{6526}{}{. 此刻的痛苦无法用宇宙中的任何词汇来形容}
