#
# 
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# 
#
#
{100}{}{完成}
{101}{}{选项}
{102}{}{取消}
{103}{}{打印}
{104}{}{年龄}
{105}{}{性别}
{106}{}{姓名}
{107}{}{男性}
{108}{}{女性}
{109}{}{额外能力}
{110}{}{业力}
{111}{}{击杀}
{112}{}{技能点}
{113}{}{等级:}
{114}{}{经验值:}
{115}{}{下一级:}
{116}{}{角色点数}
{117}{}{技能}
{118}{}{你必须在开始游戏前使用所有角色点数}  # 1
{119}{}{！}  # 2
# {120}{}{角色点数}
{121}{}{可用于增加基础属性的自由角色点数。}
{122}{}{下一级}
{123}{}{升级到下一级所需的经验值。}
{124}{}{额外能力}
{125}{}{业力}
{126}{}{击杀}
{127}{}{额外能力提供额外的能力。每升三级，你可以选择一个额外能力。}
{128}{}{这些是你在游戏中做出的选择所产生的效果。}
{129}{}{一个统计你屠杀或目睹在你面前被杀的生物类型和数量的计数器。}
{130}{}{技能点}
{131}{}{使用自由技能点来提升技能等级。}
#
{132}{}{已达最大等级。}  # 1
{133}{}{无法增加。}  # 2
{134}{}{已达最小等级。}  # 1
{135}{}{无法减少。}  # 2
{136}{}{没有可用的技能点。}
{137}{}{基础：}
{138}{}{标记技能}
{139}{}{可选特性}
{140}{}{你已经拥有最多的}  # 1
{141}{}{三个标记技能！}  # 2
{142}{}{你必须在开始游戏前选择所有标记技能！}  # 1
{143}{}{标记技能}
{145}{}{标记技能是你角色专精的技能。每个标记技能获得+20%，并且提升速度加倍。你必须选择三个标记技能。}
{146}{}{可选特性}
{147}{}{可选特性更详细地描述你的角色。所有特性都有正面和负面效果。在创建角色时你可以选择最多两个特性。}
{148}{}{你已经拥有最多的}  # 1
{149}{}{两个特性！}  # 2
{150}{}{技能}
{151}{}{技能是学到的知识。技能可以通过经验或游戏中的特殊事件提升。技能等级越高，你在该技能上的表现就越好。}
#
{152}{}{选择一个额外能力}
{153}{}{选择一个新特性}
{154}{}{失去一个特性}
{155}{}{选择一个新标记技能}
{156}{}{特性}
#
{157}{}{所有属性必须在1到10之间}  # 1
{158}{}{才能开始游戏！}  # 2
#
# 基础属性等级缩写
#
{200}{}{极差}  # 非常糟糕
{201}{}{差}  # 糟糕
{202}{}{较差}  # 较差
{203}{}{一般}  # 一般
{301}{}{行动点数}
{302}{}{护甲等级}
{303}{}{徒手伤害}
{304}{}{近战伤害}
{305}{}{伤害抗性}
{306}{}{毒素抗性}
{307}{}{辐射抗性}
{308}{}{先攻值}
{309}{}{恢复速度}
{310}{}{暴击几率}
{311}{}{负重}
{312}{}{中毒}
{313}{}{辐射中毒}
{314}{}{眼部损伤}
{315}{}{右臂瘫痪}
{316}{}{左臂瘫痪}
{317}{}{右腿瘫痪}
{318}{}{左腿瘫痪}

#
# Damage info texts
#
# Poisoned
{400}{}{你的角色中毒了。毒素会在一段时间内持续造成伤害，直到解除或自然消退。}
# Radiation
{401}{}{你的角色受到严重的辐射中毒。辐射伤害越多，效果越致命。}
# Eye Damage
{402}{}{这意味着你的角色在一只或两只眼睛上受到了严重的打击。这会影响你的感知能力。}
# Crippled right arm
{403}{}{右臂严重受伤，无法正常运作。如果一只手臂瘫痪，你将无法使用双手武器。如果两只手臂都瘫痪，你将无法用武器进行攻击。}
# Crippled left arm
{404}{}{你的角色的左臂严重受伤，无法正常运作。如果一只手臂瘫痪，你将无法使用双手武器。如果两只手臂都瘫痪，你将无法用武器进行攻击。}
# Crippled right leg
{405}{}{你的角色右腿瘫痪。}
# Crippled left leg
{406}{}{你的角色左腿瘫痪。}

# Month strings
{500}{}{一月}
{501}{}{二月}
{502}{}{三月}
{503}{}{四月}
{504}{}{五月}
{505}{}{六月}
{506}{}{七月}
{507}{}{八月}
{508}{}{九月}
{509}{}{十月}
{510}{}{十一月}
{511}{}{十二月}

#
# Option menu text
#
{600}{}{保存}
{601}{}{加载}
{602}{}{打印到文件}
{603}{}{删除}
{604}{}{完成}
{605}{}{您确定要删除}      # 第1行 {606}{}{当前角色吗？}                 # 第2行 {607}{}{已成功保存。}
{608}{}{ 已成功加载。}
{609}{}{已存在。}
{610}{}{是否覆盖？}
{611}{}{保存错误}
{612}{}{加载错误}
{613}{}{角色文件无效。}
{614}{}{角色数据无效。}
{615}{}{读取文件列表错误！}
{616}{}{打印}
{617}{}{玩家}
{618}{}{空白.GCD}

#
# ASCII text file printing text
#
{620}{}{辐射}                   # 标题行 1 {621}{}{13号避难所人员记录} # 标题行 2 {622}{}{小时} # 标题行 3 # - # - #{000}{}{      力量: 00        生命值: 000/000          序列: 00}
#{000}{}{    Perception: 00       Armor Class: 000          Healing Rate: 00}
#{000}{}{     Endurance: 00     Action Points: 000       Critical Chance: 000%}
#{000}{}{      Charisma: 00      Melee Damage: 000          Carry Weight: 000 lbs.}
#{000}{}{  Intelligence: 00       Damage Res.: 000%}
#{000}{}{       Agility: 00    Radiation Res.: 000%}
#{000}{}{          Luck: 00       Poison Res.: 000%}
#
{623}{}{ ::: 属性统计 :::}
{624}{}{       力量:}
{625}{}{        生命值:}
{626}{}{        序列:}
# -
{627}{}{     感知:}
{628}{}{       护甲等级:}
{629}{}{        治愈率:}
# -
{630}{}{      耐力:}
{631}{}{     行动点数:}
{632}{}{      暴击几率:}
# -
{633}{}{       魅力:}
{634}{}{      近战伤害:}
{635}{}{         携带重量:}
# -
{636}{}{   智力:}
{637}{}{       伤害抵抗:}
# -
{638}{}{        敏捷:}
{639}{}{    辐射抵抗:}
# -
{640}{}{           幸运:}
{641}{}{       毒素抗性:}
# -
# -
#{000}{}{ Name: 01234567890        Age: 00         Gender: Female}
{642}{}{  名字:}
{643}{}{年龄:}
{644}{}{               性别:}
{645}{}{男}
{646}{}{女}
#-
#{000}{}{ Level: 00                 Exp: 000,000    Next Level: 000,000}
{647}{}{ 等级:}
{648}{}{                经验:}
{649}{}{下一级:}
#-
{650}{}{ ::: 特性 :::           ::: 天赋 :::           ::: 业力 :::}
#-
{651}{}{ ::: 技能 :::                ::: 击杀 :::}
#-
{652}{}{ ::: 背包 :::}
#-
{653}{}{                                      总重量:}

#
# Karma name strings
#
{1000}{}{声望（总体）}
{1001}{}{狂战士}
{1002}{}{冠军}
{1003}{}{杀童者}
{1004}{}{核子可乐瘾}
{1005}{}{力量药瘾}
{1006}{}{智者药瘾}
{1007}{}{狂躁药瘾}
{1008}{}{辐解药瘾}
{1009}{}{酒精瘾}
#
# Karma description strings
#
{1100}{}{这是一个代表你总体声望的范围值。数值越高，你越为人所知和尊重。如果声望为负，你会因邪恶行为被一些人憎恨。}
{1101}{}{你杀了很多人。这通常不是一个好名声。不过，某些不法之徒可能会更喜欢你。}
{1102}{}{你的行为表明你是人民的英雄。你对抗邪恶的事迹广为人知。正直的人会更加尊重你。}
{1103}{}{你杀了废土的孩子们。这被认为是极其恶劣的行为。你这个邪恶的人。}
{1104}{}{你非常喜欢核子可乐，这种后核战争世界的可乐。}
{1105}{}{你渴望力量药。你必须持续服用这种药，否则会遭受停药的影响。}
{1106}{}{你正在遭受智者药瘾。你必须服用这种特定药物，否则会遭受停药影响。}
{1107}{}{你对化学药品上瘾了。如果你不按时服用Psycho，你将会痛苦不堪。如果服用，其他人将会遭殃。}
{1108}{}{你的身体渴望Radaway。虽然这不会危及生命，但你必须定期服用。}
{1109}{}{你有酗酒的问题。实际上，你的饮酒习惯带来了许多麻烦。}
{1110}{}{临时 - 这是什么？}


#
# Special Demo version only text
#
{5000}{}{抱歉，你只能在完整版中打印你的}  # 1
{5001}{}{角色。}  # 2
{5002}{}{抱歉，你只能在完整版中保存你的}  # 1
{5003}{}{角色。}  # 2
{5004}{}{抱歉，你只能在完整版中加载已保存的}  # 1
{5005}{}{角色。}  # 2
{5006}{}{作弊模式}
{5007}{}{在试玩版中不可用。}



