#
# Miscellaneous game engine messages.
#
# Defined in game.h
#
{0}{}{您确定要退出吗？}
{1}{}{演示版本}
{2}{}{将使用默认角色。}
{3}{}{已保存截图。}
{4}{}{快速读取游戏成功。}
{5}{}{快速保存游戏成功。}
{6}{}{演示时间限制已超出。}
{7}{}{战斗中无法使用Pipboy！}
{8}{}{保存截图时出错。}
{9}{}{介绍}
{10}{}{新游戏}
{11}{}{读取游戏}
{12}{}{制作人员}
{13}{}{退出}
{14}{}{版权所有(c) 1997 Interplay Productions。保留所有权利。}
{15}{}{行动点数}
{16}{}{生命值}
{17}{}{未安装运动传感器选项。}
{18}{}{运动传感器已无剩余电量。}
#
# Game config text. Defined in gconfig.c
#
{100}{}{保存游戏配置文件时出错！}
{101}{}{游戏设置未保存。}
#
# Some radiation messages used in critter.c
#
{1000}{}{你感到非常恶心。}
{1001}{}{你感到非常恶心，经过轻微呕吐后，略感疲惫。}
{1002}{}{你非常疲惫，呕吐不止，恢复时间受阻。}
{1003}{}{你在剧烈出血。你病得很重，头发正在脱落。}
{1004}{}{你在持续剧烈出血。呕吐物中带有血迹。你的皮肤正在从骨头上脱落。}
{1005}{}{你的肠道出血并伴有严重腹泻。你感到腹胀并处于剧烈痛苦中。}
{1006}{}{你因辐射病而死亡。}
{1007}{}{你受到了大量辐射。}
{1008}{}{盖革计数器在响。}
{1009}{}{盖革计数器疯狂地响个不停。}
#
# Message used in actions.c
#
{2000}{}{你无法到达那里。}
{2001}{}{锁已经卡住了。}
#
# poison messages from critter.c
#
{3000}{}{你中毒了！}
{3001}{}{你因中毒而受伤。}
#
# from queue.c
#
{4000}{}{由于你的操作失误，炸药提前引爆了。}
#
# from combatai.c
#
{5000}{}{使用}
{5001}{}{没有弹药可供}
{5002}{}{重新装填}
#
# from gdialog.c - new tell me about stuff
#
{6000}{}{问什么？}
