#
#   Messages from perk.c
#
#
#   PERK NAMES
#
{101}{}{警觉}
{102}{}{近战攻击加成}
{103}{}{近战伤害加成}
{104}{}{移动加成}
{105}{}{远程伤害加成}
{106}{}{射击速率加成}
{107}{}{提前行动}
{108}{}{快速治疗}
{109}{}{更多暴击}
{110}{}{夜视}
{111}{}{存在感}
{112}{}{辐射抗性}
{113}{}{坚韧}
{114}{}{强壮背部}
{115}{}{神枪手}
{116}{}{无声潜行}
{117}{}{生存专家}
{118}{}{交易大师}
{119}{}{博学}
{120}{}{治疗者}
{121}{}{财富猎人}
{122}{}{更佳暴击}
{123}{}{同理心}
{124}{}{屠杀者}
{125}{}{狙击手}
{126}{}{无声死亡}
{127}{}{行动男孩}
{128}{}{精神屏障}
{129}{}{生命给予者}
{130}{}{闪避者}
{131}{}{蛇食者}
{132}{}{修理达人}
{133}{}{医疗专家}
{134}{}{盗贼大师}
{135}{}{演说家}
{136}{}{起重机}
{137}{}{友善敌人}
{138}{}{扒手}
{139}{}{幽灵}
{140}{}{人格魅力}
{141}{}{搜寻者}
{142}{}{探险者}
{143}{}{花之子}
{144}{}{探路者}
{145}{}{动物之友}
{146}{}{侦察兵}
{147}{}{神秘陌客}
{148}{}{游骑兵}
{149}{}{快手}
{150}{}{口才伶俐}
{151}{}{快速学习者}
{152}{}{标签！}
{153}{}{变异！}
{154}{}{核子可乐瘾}
{155}{}{健肌激素瘾}
{156}{}{聪颖药瘾}
{157}{}{狂怒药瘾}
{158}{}{辐解剂瘾}
{159}{}{远程武器}
{160}{}{精准武器}
{161}{}{武器穿透}
{162}{}{武器击退}
{163}{}{动力装甲}
{164}{}{战斗装甲}
#
#   PERK DESCRIPTIONS
#
{201}{}{你更容易注意到他人的细节。拥有洞察力后，进行检查时会获得更详细的信息。}
{202}{}{你学会了东方的秘技，或者只是出拳更快。无论如何，你的徒手攻击消耗的行动点减少1点。}
{203}{}{徒手战斗经验让你在伤害方面更具优势。每级该专长使徒手和近战攻击增加2点伤害。}
{204}{}{每级额外移动专长可获得2点仅用于移动的免费行动点。换句话说，每级该专长可让你每回合免费移动2个六边格。}
{205}{}{你在枪械和其他远程武器的训练使你在远程战斗中更具杀伤力。每级该专长使远程武器增加2点伤害。}
{206}{}{该专长让你能更快扣动扳机，同时保持准确度不变。每次远程武器攻击消耗的行动点减少1点。}
{207}{}{由于你的顺序每级增加2点，你在战斗中更可能比对手先行动。}
{208}{}{每级该专长会使你的恢复速度增加1点。因此，你的恢复速度更快。}
{209}{}{如果你拥有该专长，在战斗中更容易造成致命一击。每级更多致命一击专长会增加5%的致命一击几率。这是个好事。}
{210}{}{拥有夜视专长后，你在黑暗中能看得更清楚。每级该专长会降低整体黑暗程度10%。}
{211}{}{你只需走进房间就能吸引注意。每级该专长会使他人对你的初始反应提高10%。}
{212}{}{你更能避免辐射及其带来的不良影响。每级该专长会使你的辐射抗性提高10%。}
{213}{}{当你够强壮时，受到的伤害会减少。每级该专长会增加10%的总体伤害抗性。}
{214}{}{又名骡子。每级该专长可让你额外携带50磅的装备。}
{215}{}{远距离命中目标的天赋。每级该专长会使感知在决定距离修正时增加2点。远距离击杀比以往更容易！}
{216}{}{拥有该专长后，你能快速移动且保持安静。你可以在潜行时奔跑。没有该专长，奔跑时会自动停止潜行。}
{217}{}{你是户外生存的高手。该专长赋予你在恶劣环境中生存的能力。每级该专长会使户外生存技能增加20%。}
{218}{}{你掌握了交易的一项技能——以比普通人更低的价格购买商品。拥有该专长后，购买物品时可享受25%的折扣。}
{219}{}{每级受教育专长会在你获得新经验等级时增加2点技能点。该专长在冒险初期购买效果最佳。}
{220}{}{拥有该专长后，身体的愈合变得更容易。每级会在使用急救或医生技能时多恢复2到5点生命值。}
{221}{}{你有发现金钱的天赋。在沙漠中的随机遭遇中会找到额外的钱。}
{222}{}{你在战斗中造成的致命一击更加毁灭性。你在致命一击表上获得20%的加成，几乎确保造成更多伤害。这不影响致命一击的几率。}
{223}{}{你研究过其他人类，获得了他们对你情感反应的内部知识。当进行深入对话时，你会看到对方的反应等级。}
{224}{}{杀戮者行走于世！在徒手战斗中，你的所有攻击都会升级为致命一击——造成破坏和混乱。}
{225}{}{你已掌握枪械作为痛苦来源的技巧。拥有该专长后，若你在战斗中使用远程武器成功命中，并通过幸运检定，则攻击会升级为致命一击。}
{226}{}{在潜行时，如果你从背后攻击生物，使用徒手攻击会造成双倍伤害。无声死亡就是这种专长。}
{227}{}{每级的行动小子（如果愿意，可以插入女孩）会给你每回合额外的AP。你可以将这些通用AP用于任何任务。}
{228}{}{精神屏障是能够屏蔽任何外界精神干扰的能力。你可能是从某个路过的大师那里学到的，或者是在酒吧熬夜学到的。}
{229}{}{每级此技能，你将获得额外的4点生命值。虽然看起来不多，但积少成多。}
{230}{}{如果你拥有此技能，你在战斗中被击中的可能性会降低。每级会为你的护甲等级增加5%，这额外于任何穿戴护甲的AC加成。}
{231}{}{美味！尝起来像鸡肉。你获得了对毒素的免疫力，毒素抗性增加25%。}
{232}{}{此技能将一次性为你的修理和科学技能增加20%。熬夜学习从未伤害过任何人，尤其是你。}
{233}{}{医护技能将一次性为你的急救和医生技能增加20%。治疗技能是件好事。}
{234}{}{大师盗贼将一次性为你的潜行、开锁、偷窃和陷阱技能增加10%。从富人那里偷，给自己。}
{235}{}{成为演说家意味着你的演讲和交易技能将一次性增加20%。从孩子的口中学到一切。}
{236}{}{每级的投掷高手技能将为你的投掷武器增加2点力量，仅用于决定投掷距离。}
{237}{}{如果你拥有此技能，你的队友在战斗中会被标记为绿色而不是红色。红色标记的角色可能仍然对你没有敌意。}
{238}{}{你比普通的小偷更擅长偷窃。因为有此技能，你在偷窃时可以忽略目标的大小和朝向修正。}
{239}{}{当太阳落山或你处于光线不足的区域时，有了此技能，你的潜行技能在黑暗环境下增加20%。}
{240}{}{你的声誉在他人眼中总是积极的。没有此技能，大量负面声誉会对善良的人产生不良影响。对坏人也同样有效。}
{241}{}{你比普通的末日幸存者能找到更多的弹药。此技能会使你在随机遭遇中找到的弹药量翻倍。}
{242}{}{探险家的标志是寻找新的有趣地点。有了此技能，你更有可能发现特殊的地方或人物。}
{243}{}{有了此技能，你对化学药品的渴望减少50%，并且你承受的化学药品停药时间只有普通人的一半。}
{244}{}{探路者更能找到最短的路线。有了此技能，你在世界地图上的旅行时间每级减少25%。}
{245}{}{动物不会攻击它们的朋友，除非动物先受到威胁或攻击。在这个世界上，什么算是动物尚待商榷。}
{246}{}{你提高了观察远处地点的能力，增加了世界地图上探索区域的大小，每个方向增加一个方格。}
{247}{}{有了此技能，你吸引了一位神秘陌生人的注意，他会不时出现帮助你。如果你的盟友在战斗中失去，不要指望他或她会被替换。}
{248}{}{你更能避免在荒地旅行时引起不必要的注意。每级此技能都会降低你遭遇敌对随机事件的几率。}
{249}{}{你学会了更好地在身上存放装备。每级此技能会减少在战斗中访问物品栏的AP消耗。}
{250}{}{一个圆滑的谈判者学会了在对话中增加选择，而不必理解他们在谈论什么。每级此技能会在对话中增加1点智力。}
{251}{}{有了此技能，你确实是一个快速学习者，因为每级会在你获得经验值时额外增加5%的奖励。最好在早期等级购买。}
{252}{}{你的技能已经提高到可以选择一个额外的标记技能的程度，立即增加该技能20%，并且每花费一个技能点增加2%。}
{253}{}{荒地的辐射改变了你！你的一项特质变异成了其他东西……}
{254}{}{你渴望再来一瓶Nuka-Cola。}
{255}{}{你感到颤抖。}
{256}{}{你感到昏昏沉沉。}
{257}{}{你感到头晕。}
{258}{}{你感到恶心。}
{259}{}{武器远程}
{260}{}{武器精准}
{261}{}{武器穿透}
{262}{}{武器击退}
{263}{}{动力装甲}
{264}{}{战斗护甲}
