#
# 
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#
# 

#
# Special holiday dates
#
{100}{}{新年快乐！}  # 新年
{101}{}{情人节快乐！}  # 情人节
{102}{}{愚人节快乐！}  # 愚人节
{103}{}{发货日快乐！}  # 发货日
{104}{}{独立日快乐！}  # 独立日
{105}{}{万圣节快乐！}  # 万圣节
{106}{}{感恩节快乐！}  # 感恩节
{107}{}{圣诞快乐！}  # 圣诞节
#
# 系统消息
{201}{}{返回}
{202}{}{状态}
{203}{}{当前无任务。}
{204}{}{线索}  # 线索消失
{205}{}{自动地图}
{206}{}{视频档案}
{207}{}{数据}
{208}{}{}
{209}{}{}
{210}{}{状态}
{211}{}{数据}
{212}{}{的}
{213}{}{页}
{214}{}{完成}
{215}{}{此地无法休息！}

#
# Alarm clock
#
{300}{}{闹钟}
{301}{}{生命值}
{302}{}{休息十分钟}
{303}{}{休息三十分钟}
{304}{}{休息一小时}
{305}{}{休息两小时}
{306}{}{休息三小时}
{307}{}{休息四小时}
{308}{}{休息五小时}
{309}{}{休息六小时}
{310}{}{休息到早晨（0600）}
{311}{}{休息到中午（1200）}
{312}{}{休息到傍晚（1800）}
{313}{}{休息到午夜（0000）}
{314}{}{休息直到痊愈}

#
# Holodisk titles
#
{400}{}{FEV实验磁带}
{401}{}{安全磁带}
{402}{}{远古兄弟会磁带}
{403}{}{阿尔法实验磁带}
{404}{}{德尔塔实验磁带}
{405}{}{弗瑞的实验磁带}
{406}{}{兄弟会代码}
{407}{}{变种人传输}
{408}{}{兄弟会磁带}
{409}{}{索菲亚磁带}
{410}{}{马克森日志}
{411}{}{理查德·格雷音频日记}
{412}{}{队长马克森的日记}
{413}{}{FEV研究}
{414}{}{动力装甲规格}
{415}{}{西部科技记录}
{416}{}{避难所位置 v34.129}
{417}{}{监管者传输}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{InterPlay标志}               # 不在Pipboy中显示 {501}{}{MacPlay标志}                 # MacPlay版本，不在Pipboy中显示 {502}{}{介绍}                        # 不在Pipboy中显示 {503}{}{熔池毁灭}
{504}{}{大教堂毁灭}
{505}{}{监督者简报}
{506}{}{13号避难所缺水}   # 死亡 {507}{}{13号避难所入侵}            # 死亡 {508}{}{离开避难所}                # 男性结局 {509}{}{离开避难所}                # 女性结局 {510}{}{浸入熔池}           # 死亡 {511}{}{13号避难所水}
{512}{}{13号避难所水源不足}
{513}{}{雷杀死了主宰}

#
# Things for the Mac version to speak
#
#
{600}{}{状态}
{601}{}{线索}  # 线索消失 {602}{}{自动地图}
{603}{}{档案}
{604}{}{闹钟}
{605}{}{嘟哒嘟哒嘟哒哒哒嘟嘟嘟嘟嘟哒嘟哒嘟哒嘟哒嘟哒嘟哒嘟}
{606}{}{欢迎使用罗博公司Pipboy 2000。}
{607}{}{再见。}
{608}{}{醒来。}


#
# Status thread text
#
# Format:
# 0 City name
# 1 ... 9 thread/quest name
#
{700}{}{13号避难所}
{701}{}{安抚叛乱派系。}
{702}{}{消灭变种人首领。}
{703}{}{摧毁变种人的源头。}
{704}{}{寻找水芯片。}
{705}{}{找到偷水贼。}
#
{710}{}{埋藏的避难所}
#
{720}{}{阴暗沙地}
{721}{}{治愈贾维斯的蝎毒。}
{722}{}{制作毒药解毒剂。}
{723}{}{从掠夺者手中救出坦迪。}
{724}{}{阻止辐射蝎。}
#
{730}{}{废城}
{731}{}{帮助索尔。}
{732}{}{杀掉基利安。}
{733}{}{营救辛西亚。}
{734}{}{拯救特莉丝。}
{735}{}{阻止吉兹莫。}
{736}{}{打击骷髅帮。}
#
{740}{}{掠夺者}
#
{750}{}{死城}
{751}{}{消灭水坝的超级变种人。}
{752}{}{修复死城的水泵。}
#
{760}{}{集散地}
{761}{}{消灭死亡爪。}
{762}{}{处理简。}
{763}{}{处理商人。}
{764}{}{寻找失踪的商队。}
{765}{}{从商人那里偷项链。}
#
{770}{}{兄弟会}
{771}{}{成为一名见习者。}
{772}{}{从枢纽救出见习者。}
#
{780}{}{军事基地}
#
{790}{}{辉光}
{791}{}{为设施拆除陷阱。}
{792}{}{为辉光启动电源。}
#
{800}{}{骨园}
{801}{}{成为刀锋成员。}
{802}{}{为罗梅罗送去项链。}
{803}{}{从枪械跑商那里送包裹。}
{804}{}{在追随者中找到儿童间谍。}
{805}{}{修复阿迪特姆的水培农场。}
{806}{}{营救杰森·齐默尔曼。}
{807}{}{阻止帮派攻击阿迪特姆。}
#
{810}{}{大教堂}


#
# Holodisk text
#

# *** FEV Experiment Disk ***
{1000}{}{ 日志日期 2075年3月21日：}
{1001}{}{巴内特少校下令对批次}
{1002}{}{10-011的全免疫病毒进行实验，该病毒已被}
{1003}{}{重命名为FEV，即强制进化病毒。他}
{1004}{}{主要关注的是四螺旋结构的副作用，而不是其}
{1005}{}{复制稳定性的主要效果。他认为新的}
{1006}{}{结构是哺乳动物细胞核的下一个逻辑步骤。}
{1007}{}{单细胞生物的实验}
{1008}{}{取得了巨大成功。虽然它们的基础代谢}
{1009}{}{似乎没有变化，但它们对感染}
{1010}{}{和辐射的免疫力超出了所有早期预期。}
{1011}{}{而辐射量已超出所有早期预期。}
{1012}{}{附录：叶绿体似乎未受病毒影响。}
{1013}{}{关于植物细胞的进一步实验已被}
{1014}{}{巴尼特少校下令取消。}
{1015}{}{**结束-段落**}
# -
{1016}{}{日志日期 2075年5月9日}
{1017}{}{我们用FEV感染了几种扁虫。}
{1018}{}{数小时内，虫体增大了28%，并且}
{1019}{}{抵抗了39种不同的病毒感染。}
{1020}{}{每个样本都允许继续繁殖几代，}
{1021}{}{新的DNA结构成功传递给了虫体的}
{1022}{}{后代，尽管样本中只观察到无性繁殖。}
{1023}{}{对昆虫的实验成功较少。}
{1024}{}{巴尼特少校已推迟这些实验，}
{1025}{}{直到另行通知。}
{1026}{}{**结束-段落**}
{1027}{}{日志日期 2075年6月30日}
# -
{1028}{}{几种实验室白鼠株成功感染了FEV。}
{1029}{}{同样，数小时内观察到体型增大，}
{1030}{}{9天后，所有白鼠的体型稳定在比}
{1031}{}{对照组大31%。}
{1032}{}{解剖显示，体型增大主要体现在}
{1033}{}{横纹肌组织和某些内脏器官，}
{1034}{}{如肝脏、心脏和肾脏。}
{1035}{}{一个令人惊讶的发现是，感染的白鼠}
{1036}{}{跑迷宫的时间不到对照组的一半。}
{1037}{}{需要更多测试来确认这一发现的}
{1038}{}{重要性。}
{1039}{}{**结束-段落**}
{1040}{}{日志日期 2075年11月9日}
# -
{1041}{}{ 日志日期：2075年11月9日}
{1042}{}{我们用FEV感染了218只兔子。半数}
{1043}{}{实验对象被植入电极以监测}
{1044}{}{感染前后的脑电图活动。在}
{1045}{}{注射后平均3.2秒内观察到脑部}
{1046}{}{电活动增加。再次观察到典型的}
{1047}{}{体型增大。然而，也观察到攻击性}
{1048}{}{和姿态的增加（尤其是雄性）。}
{1049}{}{解剖和灌注显示脑组织中}
{1050}{}{树突连接增加，特别是在}
{1051}{}{边缘系统和额叶皮层。}
{1052}{}{**结束-段落**}
{1053}{}{ 日志日期 2076年1月12日}
# -
{1054}{}{在11-011批次中，我们将有丝分裂}
{1055}{}{周期效率提高了43%。我们用新菌株}
{1056}{}{感染了53只浣熊。除了现在预期的}
{1057}{}{体型增大外，行为测试证实智力和}
{1058}{}{手动灵活性在舒勒-卡普指数上}
{1059}{}{增加了19点。不幸的是，几个实验对象}
{1060}{}{逃出了禁闭，需要被追捕并处理。}
{1061}{}{巴尼特少校下令终止剩余的实验对象。}
{1062}{}{有两对未被找到。}
{1063}{}{**结束-段落**}
{1064}{}{ 日志日期 2076年5月13日}
{1065}{}{我们将巴尼特少校顾问团队提供的}
# -
{1066}{}{几个新基因序列拼接进了FEV。在}
{1067}{}{11-101a批次中，我们感染了23只纯种和}
{1068}{}{混种狗，所有狗几乎立即}
{1069}{}{出现了生长。体型增大伴随着}
{1070}{}{混合品种，几乎立即出现了}
{1071}{}{增长。更大的体型伴随着}
{1072}{}{攻击性增加，但未发现显著的}
{1073}{}{智力提升。我们计划尝试与批次11-011进行92对等位基因的交叉实验。所有}
{1074}{}{实验对象在研究14周后被终止。}
{1075}{}{**结束-段落**}
{1076}{}{ 日志日期 2076年10月4日}
# -
{1077}{}{交叉实验已完成，15只黑猩猩被感染了批次11-111。生长和免疫水平}
{1078}{}{前所未有。通过放射性和化学试剂诱发癌症的尝试未成功。攻击性增加}
{1079}{}{导致实验对象被隔离。两名实验对象因剧烈的癫痫发作而死亡。所有}
{1080}{}{剩余实验对象被终止。}
{1081}{}{**结束-段落**}
{1082}{}{ 日志日期 2077年1月7日}
{1083}{}{巴尼特少校已下令将所有FEV研究转移至马里波萨军事基地。他}
{1084}{}{计划在志愿者身上继续进行项目实验。我对此表示反对，并希望在此记录}
{1085}{}{我和我的团队都不推荐在人类对象上进行研究。}
{1086}{}{**结束-磁盘**}
# -
{1087}{}{安全覆盖码 伽马 奥米克戎 德尔塔。}
{1088}{}{**结束-磁盘**}
{1089}{}{马克森上尉是对的。这个地方就是死亡。}
{1090}{}{我写下这些，以防我们没能回来，}
{1091}{}{将来某天有人能知道我们发生了什么。}
{1092}{}{**结束-段落**}
{1093}{}{我和我的团队都不推荐这样做。}
{1094}{}{**结束-磁盘**}

# *** Security Disk ***
{2000}{}{安全覆盖：伽玛欧米茄德尔塔。}
{2001}{}{**结束-磁盘**}

# *** Ancient Brotherhood Disk ***
{3000}{}{马克森上尉是对的，这地方就是死亡。}
{3001}{}{我写下这些是为了万一我们没能}
{3002}{}{回来，有一天有人能发现}
{3003}{}{我们的遭遇。}
{3004}{}{**结束-段落**}
# -
{3005}{}{我们经过了}
{3006}{}{20天的地狱，终于抵达了西泰克研究设施。但这只是简单的部分。}
{3007}{}{一看到巨大的陨坑，辐射水平就开始飙升。我们检查了补给，}
{3008}{}{认为凭借我们的护甲和抗辐射物资，}
{3009}{}{至少能安全探索一天。我们觉得这是一个经过计算的风险，}
{3010}{}{但可能回收的科技价值值得冒险。}
{3011}{}{**结束-段落**}
{3012}{}{我们爬下陨坑到达第一层，一切似乎都在计划之中。电源关闭，}
{3013}{}{所以我们不需要绕过安保。至少我们是这么想的。}
# -
{3014}{}{这一层没什么有价值的东西，所以我们继续前进。}
{3015}{}{**结束-段落**}
{3016}{}{第二层也是一样。}
{3017}{}{**结束-段落**}
{3018}{}{当詹森降到第三层时，情况彻底失控。前两层的安保传感器已被烧毁，}
{3019}{}{但第三层没有。詹森还没反应过来就被切成了碎片。}
# -
{3020}{}{我们从未见过武器能如此轻易地切穿动力装甲。人们接连倒下，}
{3021}{}{活着的人也失去了理智。我试图重新集结，但只有索托和卡马里洛}
# -
{3022}{}{和我一起回到了第一层。}
{3023}{}{**结束-段落**}
{3024}{}{我能闻到索托烧焦的肉味，他的手臂被切掉了，这意味着我的动力装甲}
{3025}{}{不再密封，所以我正在吸入}
{3026}{}{发生了什么。我们从未见过武器能如此轻易地}
{3027}{}{击穿动力装甲。士兵们一个接一个倒下，}
{3028}{}{幸存者们也失去了理智。我试图重新集结，}
{3029}{}{但只有索托和卡马里洛跟我一起回到了}
{3030}{}{第一层。}
{3031}{}{**结束-段落**}
# -
{3032}{}{ 我能闻到索托烧焦的皮肉味，他的手臂被}
{3033}{}{切断，这意味着我的动力装甲已经不再}
{3034}{}{密封，所以我正在吸入}
{3035}{}{比我计划的辐射量多得多。我正在泄漏}
{3036}{}{液压系统以惊人的速度。我们需要在我的}
{3037}{}{装甲失效之前尽快远离这个地方。}
{3038}{}{**结束-段落**}
# -
{3039}{}{卡马里略身体看起来没问题，但他在一小时}
{3040}{}{前走开了，嘴里嘟囔着什么关于地狱的事。}
{3041}{}{那个混蛋拿走了所有的抗辐射药。}
{3042}{}{**结束-段落**}
# -
{3043}{}{只剩下索托和我。没有抗辐射药我们无法}
{3044}{}{走得足够远，所以我必须在为时已晚之前}
{3045}{}{找到卡马里略。}
{3046}{}{**结束-段落**}
{3047}{}{美国武装部队，D. Allen中士。}
# -
{3048}{}{**结束-磁盘**}
{3049}{}{原型全免疫病毒项目}


#  *** Alpha Experiment Disk ***
{4000}{}{**结束-段落**}
{4001}{}{为了对抗中国政府使用的当前细菌和病毒}
# -
{4002}{}{制剂，我们制造了一种由核糖核酸（RNA）}
{4003}{}{组成的病毒片段，并包裹在蛋白质-脂质}
{4004}{}{外壳中。这个病毒体包含一种特别排列的}
{4005}{}{辐射氨基酸（RAA）序列，能够附着在脱氧}
{4006}{}{核糖核酸（DNA）的非特异性结合位点上，}
{4007}{}{并强制发生非复制性有丝分裂。结果宿主}
{4008}{}{细胞留下四螺旋DNA结构。}
{4009}{}{**结束-段落**}
{4010}{}{早期测试结果令人鼓舞。病毒体轻松}
{4011}{}{发生。结果宿主细胞留下了一个}
{4012}{}{四螺旋DNA结构。}
{4013}{}{**结束-段落**}
# -
{4014}{}{早期测试结果令人振奋。病毒体轻松}
{4015}{}{穿透细胞膜并直接附着在}
{4016}{}{细胞核中的宿主DNA上。结构的有丝分裂}
{4017}{}{几乎立即开始。通过控制在后期}
{4018}{}{动粒纤维的分布来防止胞质分裂。}
{4019}{}{整个有丝分裂周期大约持续2小时，尽管}
{4020}{}{新结构的表型表达可能需要}
{4021}{}{数天或数周才能显现。}
{4022}{}{**结束-段落**}
{4023}{}{除了对细菌和病毒因子的有效免疫外，}
# -
{4024}{}{四螺旋结构几乎完全免疫于}
{4025}{}{复制过程中由于碱基序列多样性}
{4026}{}{而引入的配对错误。受辐射的组织}
{4027}{}{在碱基序列中没有显示出突变，核糖体中的}
{4028}{}{蛋白质合成机制未受损。}
{4029}{}{**结束-段落**}
{4030}{}{超过80%的样本组织含有四螺旋}
{4031}{}{DNA。受影响最大的是肌肉和骨骼组织，}
# -
{4032}{}{以及分泌细胞，因为这些细胞似乎对病毒体}
{4033}{}{最为敏感。感觉细胞受影响最小。}
{4034}{}{令人惊讶的是，即使是通常不复制的}
{4035}{}{神经细胞和非体细胞也被诱导}
{4036}{}{开始有丝分裂。需要进一步的实验}
{4037}{}{来确定这些细胞的结果。}
{4038}{}{**结束-磁盘**}
{4039}{}{军方认为有必要让我们深入研究}
{4040}{}{波技术对生物体的影响。我们以光和声}


# *** Delta Experiment Disk ***
{5000}{}{作为研究的基础。通过操控振幅}
{5001}{}{深入研究波技术对}
{5002}{}{生物体的影响。我们以光和声音为}
{5003}{}{研究基础。通过操控振幅}
{5004}{}{通过光波和放大频率，我们可以}
{5005}{}{获得可以切割数英尺钢铁的激光。不过，}
{5006}{}{执行这样任务所需的动力还未完全开发。我们有其他}
{5007}{}{科学家在研究这一问题。}
{5008}{}{**结束-磁盘**}
{5009}{}{初步观察}


# *** Vree's Experiment Disk ***
{6000}{}{**结束-段落**}
{6001}{}{这真是令人惊奇。一些骑士在巡逻探险中}
# -
{6002}{}{发现了一种不寻常的生物。这种生物}
{6003}{}{看起来像是类人形，很可能曾经是}
{6004}{}{人类状态。然而，这种生物的}
{6005}{}{结构与普通人类有许多不同之处。}
{6006}{}{**结束-段落**}
{6007}{}{在对这种生物的最初调查中，我们发现其}
# -
{6008}{}{细胞结构类似于人类。在任何可能的分解发生之前，}
{6009}{}{我正在记录该主体的统计信息。}
{6010}{}{**结束-段落**}
{6011}{}{主体A的统计信息：}
{6012}{}{**结束-段落**}
# -
{6013}{}{身高：3.2米}
{6014}{}{质量：363.21公斤}
# -
{6015}{}{性别：无法确定}
{6016}{}{肤色：在当前照明系统下，主要为灰色，带有绿色。}
{6017}{}{不确定这种颜色是由于腐坏还是在废土中的暴露。注意：}
{6018}{}{皮肤对于手术刀而言极其坚韧。}
{6019}{}{**结束-段落**}
{6020}{}{质量分解：}
{6021}{}{皮肤相对于手术刀极为坚韧。}
{6022}{}{**结束-段落**}
{6023}{}{质量分解：}
{6024}{}{    肌肉质量: 77.41%}
{6025}{}{    骨骼质量: 10.23%}
{6026}{}{    脂肪质量: 3.02%}
{6027}{}{    组织质量: 9.34%}
{6028}{}{**结束-段落**}
{6029}{}{细胞结构:}
{6030}{}{    细胞以更快的速度进行细胞分裂。}
{6031}{}{    有丝分裂的速度比正常人类快15%。}
{6032}{}{    细胞结构与人类高度相似。}
{6033}{}{    基因结构显示出与智人的强相关性。}
{6034}{}{    可能是战争遗留的核和生化因素导致的变异。}
{6035}{}{    DNA链看起来非常完整。所有隐性疾病基因似乎}
{6036}{}{    已从系统中消除。}
{6037}{}{    RNA链也似乎经过操控，以增强信号传递。}
{6038}{}{**结束-段落**}
{6039}{}{初步假设}
{6040}{}{**结束-段落**}
{6041}{}{基于神经传导物质和突触接收器的增大，我假设}
{6042}{}{该对象具有敏锐的反应能力和高度的感知力。根据}
{6043}{}{骑士们提供的关于发现该对象区域的报告，荒芜、}
{6044}{}{高辐射、极高浓度的化学物质，令人惊讶的是该对象}
# -
{6045}{}{能存活如此之久。正在进行测试}
{6046}{}{**结束-段落**}
# -
{6047}{}{根据神经传导器和突触接收器的增大尺寸}
{6048}{}{我推测该对象拥有敏锐的反应能力和高度发达的感官。根据}
{6049}{}{骑士们对发现该对象地区的报告，那里荒无人烟，辐射极高，}
{6050}{}{化学剂浓度极高，简直是个奇迹，}
{6051}{}{该对象还能存活那么长时间。目前正在进行测试}
{6052}{}{**结束-段落**}
{6053}{}{**结束-段落**}
{6054}{}{以确定可能的死亡原因。}
{6055}{}{**结束-段落**}
# -
{6056}{}{ 对A对象进行的测试结果：}
{6057}{}{**结束-段落**}
# -
{6058}{}{目视检查：}
{6059}{}{    黑色火药烧痕靠近区域，可能是}
{6060}{}{    子弹造成的。}
{6061}{}{    右腿小腿有1.2厘米的撕裂伤，}
{6062}{}{    似乎是被牙齿咬伤。将进行}
{6063}{}{    狂犬病测试。}
{6064}{}{    皮肤干燥脱屑。可能是暴露所致。}
{6065}{}{**结束-段落**}
# -
{6066}{}{测试结果：}
{6067}{}{    辐射计数：12拉德。}
{6068}{}{    狂犬病测试：无感染。}
{6069}{}{    盐酸气体：无残留}
{6070}{}{    氯含量：0.07%}
{6071}{}{    硫含量：0.02%}
{6072}{}{    相位转移病毒：无感染}
{6073}{}{    伽玛回旋病毒：无感染}
{6074}{}{    强制进化病毒II：严重过量}
{6075}{}{**结束-段落**}
# -
{6076}{}{ 假设}
{6077}{}{**结束-段落**}
# -
{6078}{}{根据我的观察，我假设测试对象是在}
{6079}{}{至少两人和三只狗大小的动物的激烈战斗中被杀。}
{6080}{}{真正令人震惊的是对象体内的病毒感染程度。}
{6081}{}{我曾读到过一些战前科学家进行的实验，}
{6082}{}{他们在研究}
{6083}{}{}
{6084}{}{这种病毒，但所有的研究笔记都已}
{6085}{}{被销毁。}
{6086}{}{**结束-段落**}
# -
{6087}{}{对这种病毒的研究带来了许多有趣的}
{6088}{}{发现。实验对象因病毒的过量感染而}
{6089}{}{获得了许多变异。这可以解释其增强的}
{6090}{}{肌肉和骨骼结构。}
{6091}{}{此外，人类常见的隐性基因被以某种方式}
{6092}{}{操控，从而实现了最佳的组合。虽然}
{6093}{}{这种现象的发生过程尚不明确，但确实}
{6094}{}{有一些严重的副作用。最主要的是}
{6095}{}{不育。实验对象将无法与任何生物繁殖，}
{6096}{}{无论是正常生物还是变异生物。}
{6097}{}{其他副作用包括表皮色素的改变。}
{6098}{}{寿命预期增加了10%。}
{6099}{}{智力因这种病毒株下降了30%。}
{6100}{}{**结束-段落**}
{6101}{}{结论}
# -
{6102}{}{**结束-段落**}
{6103}{}{基于这些信息，我推测我们}
# -
{6104}{}{可以简单地比这些变种人活得更久。然而，}
{6105}{}{鉴于这些变种人拥有超高浓度的}
{6106}{}{病毒，合理推测可能有某个地方在}
{6107}{}{制造它们。}
{6108}{}{至于它们可能在哪里，我无法猜测。}
{6109}{}{**结束-磁盘**}
{6110}{}{我父亲曾是南加州沙漠中一个秘密军事基地的}


# *** Brotherhood of Steel Honor Code ***
# *** Maxson's History ***
{7000}{}{保安。作为一个典型的宪兵，我}
{7001}{}{记得他主要是因为他的力量。当时机来临时}
{7002}{}{最让我记忆犹新的是他的力量。当时需要他展示力量的时候}
{7003}{}{革命，我尊重他的信念。他留下来，}
{7004}{}{帮助那些残疾和受伤的人，甚至是科学家。}
{7005}{}{他把我和我母亲的安危托付给他最好的朋友，}
{7006}{}{并命令我们与其他叛军一起进入沙漠。}
{7007}{}{**结束-段落**}
{7008}{}{我们，寥寥无几，踏入荒野。我脑海中唯一的想法}
# -
{7009}{}{就是再也见不到我的父亲了。}
{7010}{}{他知道留下来意味着死亡。即便如此，他}
{7011}{}{还是留下了。他尊重他所佩戴的旗帜、CIC和徽章。}
{7012}{}{**结束-段落**}
{7013}{}{真是个傻瓜。}
{7014}{}{**结束-段落**}
# -
{7015}{}{他为他人的罪孽而死。这种事不会再发生在我们身上。}
{7016}{}{我们将自给自足。我们将成为知识和传说的守护者。}
# -
{7017}{}{我们将生存于文明的终结。我们将为自己的行为负责，}
{7018}{}{并追究他人的行为。}
{7019}{}{**结束-段落**}
{7020}{}{我向你承诺，麦克森，我的儿子。钢铁兄弟会}
{7021}{}{这个名字当之无愧。我们是一个兄弟会。不像}
{7022}{}{我的父亲，我们将与那些分享我们信念和信仰的人并肩作战。}
{7023}{}{我们是钢铁。我们坚硬。我们已被磨砺成锋利的刀刃。}
# -
{7024}{}{**结束-段落**}
{7025}{}{永远记住我们在烈火中锻造的经历。}
{7026}{}{永远不要忘记。}
{7027}{}{这是过去的座右铭，也是我们现在的座右铭。}
{7028}{}{艰难。我们已被磨砺成锋利的刀刃。}
{7029}{}{**结束-段落**}
# -
{7030}{}{永远记住我们在烈火中锻造的经历。}
{7031}{}{永不忘记。}
{7032}{}{过去的座右铭，也是我们现在的座右铭。}
{7033}{}{**结束-磁盘**}

# *** Mutant disk ***
{8000}{}{消息发送：基地，这里是拾荒小队二号，请回答。}
{8001}{}{完毕。}
{8002}{}{**结束-段落**}
# -
{8003}{}{消息接收：收到，你的信号很清晰，请继续。}
{8004}{}{完毕。}
{8005}{}{**结束-段落**}
# -
{8006}{}{消息发送：我们从商队收集了四名男性，两名女性，}
{8007}{}{以及他们的补给品。他们的污染程度不算严重。}
{8008}{}{告诉中尉，我们会把他们送过去，他们可能}
{8009}{}{能承受这个过程。我们会在这里再等几天，}
{8010}{}{尝试拦截另一个商队。完毕。}
{8011}{}{**结束-段落**}
{8011}{}{消息接收：收到。获取过程中有无伤亡？完毕。}
# -
{8012}{}{**结束-段落**}
{8013}{}{消息发送：没有。又一次干净利落的行动。基地，}
{8014}{}{顺便告诉拾荒小队一号，我们遇到了他们}
# -
{8015}{}{同样的问题。我们的一名侦察员在外围巡逻时}
{8016}{}{没有返回。其他几名侦察员报告昨晚在营地附近}
{8017}{}{看到有个又大又快的东西。我会在明天早上}
{8018}{}{0600时亲自去查看。完毕。}
{8019}{}{**结束-段落**}
{8020}{}{消息接收：明白。我们会等待你的报告。}
{8021}{}{如果可能，尝试捕获它。主人会非常高兴。完毕。}
{8022}{}{**结束-磁盘**}
# -
{8023}{}{ 2077年10月10日}
{8024}{}{如果可能，尽量活捉。主人会很高兴。完毕。}
{8025}{}{非常高兴。完毕。}
{8026}{}{**结束-磁盘**}


# *** Military Base Disk***
{9000}{}{ 2077年10月10日}
{9001}{}{我，罗杰·麦克森，上尉，编号072389，已经}
{9002}{}{开始记录这个日志，因为情况对我们所有人来说都不妙，}
{9003}{}{我希望人们能知道这里到底发生了什么。}
{9004}{}{}
{9005}{}{**结束-段落**}
# -
{9006}{}{当我们终于发现那些科学家混蛋在干什么时，}
{9007}{}{一切都乱套了。上校把自己锁在办公室里，}
{9008}{}{似乎精神崩溃了。士兵们都在叫嚣着要复仇。}
{9009}{}{他们都指望我能给出答案，而我也不确定}
{9010}{}{该怎么做。不过，在这个地方陷入无政府状态的血腥混战之前，}
{9011}{}{必须有人采取行动。}
{9012}{}{}
{9013}{}{**结束-段落**}
# -
{9014}{}{2077年10月12日}
{9015}{}{每次我们从上级收到报告，这里的情况就更糟。}
{9016}{}{战争正朝着非常不利的方向发展，这个地方}
{9017}{}{即将全面叛乱，带来无尽的混乱。今天我阻止了}
{9018}{}{一个士兵处决一名科学家，并要求我们审问}
{9019}{}{他们，以弄清他们的命令是什么。}
{9020}{}{}
{9021}{}{**结束-段落**}
# -
{9022}{}{2077年10月13日}
{9023}{}{今天我杀了一个人。我在审问首席科学家安德森时，}
{9024}{}{他详细告诉我他们那些不人道的实验。他说他的命令}
{9025}{}{来自政府，但我不相信。他开始尖叫，说他是在}
{9026}{}{服从命令，说他是个军人，然后我就开枪打死了他。}
{9027}{}{我告诉自己这是为了防止他在士兵中引发全面叛乱，}
{9028}{}{但我不太确定。}
{9029}{}{是为了防止他在士兵中引发全面叛变，}
{9030}{}{但我不太确定。}
{9031}{}{**结束-段落**}
# -
{9032}{}{ 2077年10月15日}
{9033}{}{我再次尝试通过门与上校对话，}
{9034}{}{但他似乎已经完全失去理智。}
{9035}{}{我和几个士兵破门而入，正好看到他}
{9036}{}{自杀的一幕。在扣动扳机前，他说了声抱歉。}
{9037}{}{**结束-段落**}
{9038}{}{ 2077年10月18日}
# -
{9039}{}{杀掉那个书呆子似乎确立了我作为}
{9040}{}{领导者的地位。他们现在毫无疑问地追随我。}
{9041}{}{审讯总是以处决告终。谢尔曼坚持得最久，}
{9042}{}{但结果还是一样。她关于命令的辩解}
{9043}{}{过于具体，似乎并非完全编造。我对}
{9044}{}{这一切将如何收场有种不祥的预感。}
{9045}{}{我甚至不再对自己执行科学家的理由撒谎。}
{9046}{}{**结束-段落**}
{9047}{}{ 2077年10月20日}
{9048}{}{我终于通过无线电回复了外界。}
{9049}{}{我不明白他们为什么从未派人来看看}
# -
{9050}{}{当我们停止回应他们的传输时发生了什么。}
{9051}{}{这毫无道理。好吧，他们现在会来了。}
{9052}{}{我宣布我们脱离联盟独立。}
{9053}{}{杰斐逊·戴维斯，你自愧不如。}
{9054}{}{**结束-段落**}
{9055}{}{ 2077年10月22日}
{9056}{}{到底发生了什么？我们宣布完全}
{9057}{}{脱离军队，不再受其控制}
# -
{9058}{}{ 2077年10月22日}
{9059}{}{到底发生了什么？我们宣布自己完全脱离军队，}
{9060}{}{不再受其约束。}
{9061}{}{政府的命令，然后呢？什么都没发生。}
{9062}{}{有大事要发生了。}
{9063}{}{**结束-段落**}
# -
{9064}{}{ 2077年10月23日}
{9065}{}{真不敢相信那些混蛋终于干了这事。该死的}
{9066}{}{他们。他们终于让原子弹飞了起来。我们正}
{9067}{}{在努力从冯·费尔登那里挖掘真相时，突然}
{9068}{}{完全失去了联系。我感觉研究中心遭受了重创。}
{9069}{}{不知道为什么，只是直觉。我们没有成为目标}
{9070}{}{似乎难以置信。我确信中国很快就会弥补这个}
{9071}{}{疏忽。幸运的是，我们在前天就把家人从外面}
{9072}{}{转移到了设施内。我们还不知道辐射尘是否已}
{9073}{}{经到达这个地区。}
{9074}{}{**结束-段落**}
{9075}{}{ 2077年10月25日}
{9076}{}{普拉特纳中士今天自愿出去测量大气的具体}
# -
{9077}{}{读数。看来辐射还没有扩散到这里。由于他}
{9078}{}{穿着动力装甲，辐射对他没有威胁，但如果}
{9079}{}{他暴露在外，他就必须被流放。我们这里没}
{9080}{}{有足够的去污设施。}
{9081}{}{**结束-段落**}
{9082}{}{ 2077年10月26日}
{9083}{}{我说服了大家，我们应该埋葬那些科学家。}
{9084}{}{不知道为什么……也许是为了减轻我的良心}
{9085}{}{负担。当最后一个科学家临终时，我终于开}
# -
{9086}{}{始相信他们的故事。}
{9087}{}{我说服士兵们，我们应该埋葬那些科学家。}
{9088}{}{我不知道为什么……也许是为了减轻我的良心负担。}
{9089}{}{当最后一个科学家奄奄一息时，}
{9090}{}{我终于开始相信他们的故事。}
{9091}{}{**结束-段落**}
# -
{9092}{}{天啊，我到底变成了什么？}
{9093}{}{**结束-段落**}
# -
{9094}{}{2077年10月27日}
{9095}{}{今天我们要离开这个被诅咒的地方。我将带领}
{9096}{}{大家前往失落山的旧政府地堡。}
{9097}{}{我把这个日志留在这里，等到下一次核打击时}
{9098}{}{被埋葬。谁知道呢，也许有一天会有人找到它.....}
{9099}{}{**结束-磁盘**}
{9100}{}{从这个被诅咒的基地撤离是对}

# *** Sophia Disk ***
{10000}{}{士兵及其家属的严峻考验。虽然没有}
{10001}{}{放射性尘埃需要应对，但他们却频繁遭遇}
{10002}{}{人性的堕落。流窜的疯狂掠夺者多次试图袭击}
{10003}{}{这个高贵的队伍。}
{10004}{}{**结束-段落**}
{10005}{}{队伍本身没有危险，因为他们穿着}
{10006}{}{动力装甲。而他们的家属就没那么幸运了。}
# -
{10007}{}{一旦那些害虫发现他们无法轻易得手，就开始}
{10008}{}{从远处向手无寸铁的平民开火。}
{10009}{}{**结束-段落**}
{10010}{}{他们遭受了大量伤亡，但每当有一名}
{10011}{}{撤离队员被这样击倒，我们高贵的同胞就从荒原中}
{10012}{}{夺走两条生命。}
# -
{10013}{}{**结束-段落**}
{10014}{}{最终，先辈们到达了地堡的安全地带。伟大的}
{10015}{}{拯救者马克森上尉宣布这里为我们的新家，一切}
{10016}{}{都安好了。}
# -
{10017}{}{终于，先辈们来到了安全的}
{10018}{}{避难所。伟大的解救者马克森上尉宣布这里}
{10019}{}{成为我们的新家，一切安好。}
{10020}{}{**结束-段落**}
# -
{10021}{}{随着时间的推移，掩体成为了我们的家园、}
{10022}{}{我们的圣殿，以及我们免受外界恐怖的救赎。}
{10023}{}{我们开始将我们的堡垒建造成辉煌的模样，}
{10024}{}{这种美丽是技术匮乏的世界前所未见的。}
{10025}{}{**结束-段落**}
{10026}{}{然而，仍有一些人不满足。他们这些}
# -
{10027}{}{不安分的灵魂要求我们向东南方寻找}
{10028}{}{据说藏有先进技术的地方。}
{10029}{}{**结束-段落**}
{10030}{}{Maxson上尉警告这些鲁莽的年轻人，}
{10031}{}{研究设施在我们幸存时无疑已被摧毁，}
# -
{10032}{}{但他们不听劝告。他们穿上神圣的盔甲，}
{10033}{}{出发去寻找他们的圣杯，但在此之前，}
{10034}{}{他们还亵渎了Deliverer的名字，质疑他的勇气！}
{10035}{}{**结束-段落**}
{10036}{}{这些人再也没有被听到过。}
{10037}{}{**结束-磁盘**}
{10038}{}{根据我的命令，作为现任指挥官，在}
# -
{10039}{}{Robert Spindel上校不幸去世后，在这危机时刻，}
{10040}{}{全体基地安全队已被部署到失落山的安全掩体。}

# *** Maxson Disk ***
{11000}{}{**结束-段落**}
{11001}{}{这一指令也包括军官和士兵的家属。}
{11002}{}{**结束-段落**}
{11003}{}{除非另有指示，来自适当}
{11004}{}{**结束-段落**}
# -
{11005}{}{此指令也包括军官和士兵的}
{11006}{}{家属。}
{11007}{}{**结束-段落**}
# -
{11008}{}{除非另有指示，否则来自适当}
{11009}{}{战争部代表，此命令}
{11010}{}{将按原文执行。}
{11011}{}{**结束-段落**}
# -
{11012}{}{行动人员1：所有军事人员及其}
{11013}{}{家属须于2077年10月25日0800前撤离基地。}
{11014}{}{所有人员在指挥下前往失落山基地。}
{11015}{}{未获准休假。}
{11016}{}{**结束-段落**}
# -
{11017}{}{行动人员2：所有平民人员须留在基地，}
{11018}{}{等待其合法指挥结构的命令。}
{11019}{}{**结束-段落**}
{11020}{}{行动人员3：被认为对基地军事人员生存必要的设备}
# -
{11021}{}{须立即从仓库中提取。}
{11022}{}{适当的授权将在时间允许的情况下跟进。}
{11023}{}{**结束-段落**}
{11024}{}{行动人员4：所有军事司法代码将严格执行，}
{11025}{}{适用于参与联合军事行动的军事人员和平民人员。}
# -
{11026}{}{**结束-段落**}
{11027}{}{行动人员5：在与战争部建立一致且授权的通信之前，}
{11028}{}{这些命令将优先于任何先前建立的命令。}
{11029}{}{**结束-段落**}
# -
{11030}{}{马克森上尉}
{11031}{}{2077年10月24日}
{11032}{}{**结束-磁盘**}
{11033}{}{                                                    0000 - 0004}
{11034}{}{**结束-段落**}
# -
{11035}{}{马克森上尉}
{11036}{}{2077年10月24日}
{11037}{}{**结束-磁盘**}

# *** Richard Grey audio diary ***
{12000}{}{                                                    0000 - 0004}
{12001}{}{我快不行了。我得赶紧在疼痛压倒我之前记下这些。}
{12002}{}{超过我的忍耐极限。}
{12003}{}{**结束-段落**}
# -
{12004}{}{                                                    0005 - 0020}
{12005}{}{我无法相信我竟然能拖着自己从那个池子里出来。粘液对我没有影响，但我差点溺死。我不知道Harold发生了什么——}
{12006}{}{他就站在我旁边，而吊车把我撞进了池子。他应该是死了，否则他一定会来帮我。Francine死了，被一个机器人杀了。}
{12007}{}{**结束-段落**}
{12008}{}{                                                    0021 - 0027}
{12009}{}{我不知道过了多久。我能破解电脑关闭机器人并记录下这些，但我的意识正在渐渐模糊。}
{12010}{}{痛苦无比……}
{12011}{}{**结束-段落**}
{12012}{}{                                                    0028 - 0043}
# -
{12013}{}{我浸泡的绿色粘液是我们追踪到的所有变异的来源。我的皮肤开始溃烂剥落。在其他地方，它在起泡，}
{12014}{}{开始分泌出绿色的粘液。有时候，痛苦几乎可以忍受。}
{12015}{}{**结束-段落**}
{12016}{}{                                                    0044 - 0057}
{12017}{}{我居然能再次走几步了……难以想象我能拖着自己一路走到这里。}
{12018}{}{奇怪的是，我实际上感觉到了增强，尽管仍旧疼痛难忍。一切}
# -
{12019}{}{                                                    0028 - 0043}
{12020}{}{我浸泡其中的绿色粘液是所有突变的源头}
{12021}{}{我们追踪到这里。我的皮肤开始溃烂和剥落。}
{12022}{}{在其他地方，它正在起泡并开始排出绿色}
{12023}{}{粘液状的物质。有些}
{12024}{}{有些日子疼痛几乎可以忍受。}
{12025}{}{**结束-段落**}
# -
{12026}{}{                                                    0044 - 0057}
{12027}{}{我居然又能走几步了……似乎}
{12028}{}{难以置信我竟然从浸泡室一路爬到这里}
{12029}{}{奇怪的是，我感觉自己更强壮了，尽管}
{12030}{}{仍然疼痛难忍。一切都}
{12031}{}{似乎在变小。}
{12032}{}{**结束-段落**}
# -
{12033}{}{                                                    0058 - 0096}
{12034}{}{我想我吃掉了一个在这里乱窜的变异生物。}
{12035}{}{在我意识到发生了什么之前，}
{12036}{}{某种触须从我的胃里伸出来，}
{12037}{}{包裹住了那可怜的生物。就在它被吸进我肚子里的瞬间，}
{12038}{}{我居然能感受到它的思想。}
{12039}{}{我想。这很可能是我}
{12040}{}{正在慢慢发疯，无法再区分}
{12041}{}{现实和幻觉。}
{12042}{}{也许我还在缓慢地死去，想象了这一切。}
{12043}{}{**结束-段落**}
{12044}{}{                                                    0097 - 0111}
# -
{12045}{}{事情每天都变得更加清晰。}
{12046}{}{这种毒素实际上增强了我的思维。我觉得}
{12047}{}{我能简单直接地理解最复杂的哲学问题。}
{12048}{}{就好像所有的伪装层都被剥去了。我想知道}
{12049}{}{如果我让一只动物长时间浸泡在这些缸里会发生什么？}
{12050}{}{它会获得意识吗？}
{12051}{}{**结束-段落**}
{12052}{}{                                                    0112 - 0134}
{12053}{}{动物身上发生了最奇怪的事情。}
# -
{12054}{}{它们实际上变得更聪明，对周围环境更敏感。}
{12055}{}{今天我同时浸泡了一只狗和一只老鼠，结果它们融合在一起。}
{12056}{}{这不再是两个生物，但也不止是一个。}
{12057}{}{也许这就是未来——一种融合的到来。}
{12058}{}{今天的时间，他们融合在一起。这不再是}
{12059}{}{完全的两个生物，但也不止一个。}
{12060}{}{也许这就是未来——一个融合的}
{12061}{}{不同的生物和谐地统一在一起。}
{12062}{}{我不再以我创造的不同动物作为}
{12063}{}{单纯的食粮 - 我成为了实现}
{12064}{}{统一的工具。我现在已经远不}
{12065}{}{止是一个人类。}
{12066}{}{**结束-段落**}
# -
{12067}{}{                                                    0135 - 0139}
{12068}{}{是时候让其他人也感受到统一的}
{12069}{}{荣耀了。}
{12070}{}{**结束-段落**}
# -
{12071}{}{                                                    0140 - 0153}
{12072}{}{一个迷失的灵魂终于闯入了我的家。我}
{12073}{}{如此惊讶，以至于在浸泡之前就把他吃掉了，}
{12074}{}{这是我不该再犯的错误。他的思维如此原}
{12075}{}{始以至于让我这个精细的智慧感到厌恶。}
{12076}{}{**结束-段落**}
# -
{12077}{}{                                                    0154 - 0172}
{12078}{}{我开始通过向体内注射少量的病毒来调整自己，}
{12079}{}{以更加符合统一体的标准。池中的粘液是一种人}
{12080}{}{工制造的病毒，叫做强制进化病毒。这些信息是}
{12081}{}{我通过新长成的神经链接从基地计算机获取的。}
{12082}{}{**结束-段落**}
{12083}{}{                                                     0173 - 0198}
# -
{12084}{}{那些偶然找到这里的游荡者让我失望。他们似乎}
{12085}{}{不能正确地突变。我能创造的最好的东西不过是}
{12086}{}{一些个头大而愚钝的变种人。多数人甚至记不起}
{12087}{}{在我引导他们进入奇妙的统一体之前的任何事情。}
{12088}{}{我现在只是用他们来作为能量供应。他们的思维}
{12089}{}{对我毫无意义}
{12090}{}{现在以他们为燃料。他们的思想一无是处}
{12091}{}{对我而言，}
{12092}{}{**结束-段落**}
# -
{12093}{}{                                                     0199 - 0236}
{12094}{}{哦，光辉的创造者！我成功地将统一的完全喜悦传播给了另一个灵魂！}
{12095}{}{与其他人不同，他的辐射总量很低。我相信这是我们一直忽视的因素，}
{12096}{}{因为在辐射损伤较少的情况下，转化似乎更为成功。}
{12097}{}{当我将他的思想融入我们时，我从未感受过如此的荣耀。}
{12098}{}{**结束-段落**}
{12099}{}{                                                     0237 - 0281}
{12100}{}{我们开始创建一支致力于统一生命多样性的军队。}
{12101}{}{我们已经训练他们在我们寻找更多人口密集地区以融入我们时继续我们的工作。}
# -
{12102}{}{我们开始感受到一个可移动身体的局限性。}
{12103}{}{我们必须找到一个永久的家园，拥有更丰富的知识储备和稳定的生物质供应。}
{12104}{}{**结束-段落**}
{12105}{}{                                                     0282 - 0303}
{12106}{}{我们已停止自我扩张，直到找到这个新的统一中心。}
{12107}{}{一旦抵达，我们将继续成长和吸收，直到为整个世界带来和平与统一。}
{12108}{}{**结束-磁盘**}
{12109}{}{ 2077年10月10日}
{12110}{}{我，罗杰·马克森，上尉，编号072389，开始记录这个日志，因为对我们任何人来说情况都不妙，}
# -
{12111}{}{我希望人们能知道事情的真相。}
{12112}{}{我们已经停止自我扩张，直到我们找到这个}
{12113}{}{新的统一中心。当我们到达时，我们将继续}
{12114}{}{成长和进食，直到我们为整个世界带来和平}
{12115}{}{与统一。}
{12116}{}{**结束-磁盘**}

# *** Captain Maxson's Diary ***
{13000}{}{ 2077年10月10日}
{13001}{}{我，罗杰·麦克森，上尉，编号072389，已经}
{13002}{}{开始记录这个日志，因为对我们任何人来说}
{13003}{}{情况都不妙，我希望人们能知道真正的}
{13004}{}{这里发生了什么。一切都失控了，当我们终于}
{13005}{}{发现那些科学家混蛋在搞什么鬼。}
{13006}{}{上校把自己锁在办公室里，似乎正在}
{13007}{}{经历某种崩溃。士兵们在}
{13008}{}{怒吼着要复仇。他们向我寻求答案，}
{13009}{}{而我也不知道该怎么办。不过，必须有人}
{13010}{}{采取行动，否则这里将陷入一场}
{13011}{}{无政府状态的血腥混乱中。}
{13012}{}{**结束-段落**}
# -
{13013}{}{ 2077年10月12日}
{13014}{}{每次我们从上级收到报告，情况就}
{13015}{}{变得更糟。战争的局势非常不妙，}
{13016}{}{而这里即将全面叛变，伴随着所有}
{13017}{}{随之而来的混乱。今天我阻止了一个士兵}
{13018}{}{处决一名科学家，并要求我们}
{13019}{}{审问他们，以了解他们的命令是什么。}
{13020}{}{**结束-段落**}
# -
{13021}{}{ 2077年10月13日}
{13022}{}{今天我杀了一个人。我在审问首席科学家}
{13023}{}{安德森，他向我详细讲述了他们}
{13024}{}{非人道的实验。他说他的命令来自}
{13025}{}{政府，但我不相信。他开始尖叫着说}
{13026}{}{他是在执行命令，他是个军人，}
{13027}{}{然后我就开枪打死了他。我告诉自己这是为了}
{13028}{}{防止他在士兵中引发全面叛变，但我不太确定。}
{13029}{}{**结束-段落**}
# -
{13030}{}{ 2077年10月15日}
{13031}{}{我再次尝试通过门与上校交谈，}
{13032}{}{但他似乎完全失去了与现实的联系。}
{13033}{}{我和几个士兵一起破门而入}
{13034}{}{是时候看他崩掉自己的脑袋了。就在他扣动扳机前，他说了声抱歉。}
{13035}{}{**结束-段落**}
{13036}{}{ 2077年10月18日}
# -
{13037}{}{通过杀掉那个书呆子，我似乎确立了自己作为领导者的地位。现在他们毫无疑问地跟随我。审讯无一例外地以处决告终。谢尔曼坚持得最久，但结果还是一样。她关于命令的辩解太具体了，不可能完全是编造的。我对这一切的结局有种很不好的预感。我甚至不再对自己撒谎，关于我处决科学家的理由。}
{13038}{}{**结束-段落**}
{13039}{}{ 2077年10月20日}
{13040}{}{我终于通过无线电回复了外界。我不知道为什么他们从未派人来看看我们在停止回应他们的传输后发生了什么。这完全说不通。好吧，他们现在会来了。我宣布我们脱离联盟。他们记得杰斐逊·戴维斯。历史会如何评价我呢？}
{13041}{}{**结束-段落**}
{13042}{}{ 2077年10月22日}
{13043}{}{到底发生了什么？我们宣布彻底脱离军队，不再受政府指挥，结果呢？什么都没发生。有不好的事情要发生了。}
{13044}{}{**结束-段落**}
{13045}{}{ 2077年10月23日}
{13046}{}{关于我处决那些科学家的原因。}
{13047}{}{**结束-段落**}
# -
{13048}{}{ 2077年10月20日}
{13049}{}{我终于通过我们的无线电回复了外界。}
{13050}{}{我不知道他们为什么从来没有派人来看看}
{13051}{}{当我们停止回应他们的传输时这里发生了什么。}
{13052}{}{这完全说不通。}
{13053}{}{好吧，他们现在会来了。我宣布我们脱离了联盟。}
{13054}{}{他们记得杰斐逊·戴维斯。历史会如何评价我？}
{13055}{}{**结束-段落**}
{13056}{}{ 2077年10月22日}
# -
{13057}{}{到底发生了什么？我们宣布彻底脱离军队}
{13058}{}{不再受政府指挥，然后呢？什么都没发生。}
{13059}{}{有不好的事情要发生了。}
{13060}{}{**结束-段落**}
{13061}{}{ 2077年10月23日}
{13062}{}{**结束-段落**}
# -
{13063}{}{**结束-段落**}
{13064}{}{我真不敢相信那些混蛋终于动手了。该死的他们}
{13065}{}{都下地狱吧。他们终于让原子弹飞了。我们正}
{13066}{}{在试图从冯·费尔登那里挖出真相时，突然完全失去}
{13067}{}{了联系。我感觉研究中心遭受了重创。我不知道}
{13068}{}{为什么，只是直觉。我们没有被锁定目标似乎不可思议。}
{13069}{}{我相信中国很快就会弥补这个疏漏。幸运的是，我们}
{13070}{}{前天已经把家人从外面转移到设施里。我们还不知道}
{13071}{}{辐射是否已经到达这个区域。}
{13072}{}{**结束-段落**}
{13073}{}{ 2077年10月25日}
{13074}{}{普拉特纳中士今天自愿出去测量大气的具体读数。}
{13075}{}{看来辐射还没有扩散到这里。由于他穿着动力装甲，}
# -
{13076}{}{辐射对他没有威胁，但如果他被辐射感染，他就必须被}
{13077}{}{流放。我们这里没有足够的净化设施。}
{13078}{}{我不知道为什么……也许是为了减轻我的良心负担。}
{13079}{}{ 2077年10月26日}
{13080}{}{我说服了士兵们，我们应该埋葬科学家。我不知道为什么...}
{13081}{}{也许是为了减轻我的良心负担。我终于开始相信他们的故事，}
{13082}{}{当最后一个人奄奄一息时。我的天，我变成了什么样的人？}
{13083}{}{当最后一次我终于开始相信他们的故事时}
{13084}{}{ 2077年10月27日}
# -
{13085}{}{我们今天要离开这个被诅咒的地方。我将带领大家前往}
{13086}{}{失落山的旧政府地堡。}
{13087}{}{我不知道为什么……也许是为了减轻我的良心不安。}
{13088}{}{当最后一个故事让我开始相信他们的时候}
{13089}{}{一个人快要死了。天啊，我到底变成了什么?}
{13090}{}{**结束-段落**}
# -
{13091}{}{ 2077年10月27日}
{13092}{}{今天我们要离开这个被诅咒的地方。我将带领}
{13093}{}{大家撤离到失落山的旧政府地堡。}
{13094}{}{我将留下这份日志，等到这个地方}
{13095}{}{在下一次交火中被埋葬。谁知道呢，也许某天}
{13096}{}{有人会发现它.....}
{13097}{}{**结束-磁盘**}


# Computer Download of the FEV project
# Uses the global var COMPUTER_FEV

{14000}{}{FEV摘要:}
{14001}{}{**结束-段落**}
{14002}{}{2073年。随着中国在生物武器上的侵略性日益增强，}
{14003}{}{美国政府认为需要一种应对措施。}
{14004}{}{泛免疫病毒项目（PVP）于2073年9月15日正式成立。}
{14005}{}{**结束-段落**}
{14006}{}{2075年。显然，对抗新型生物武器的最佳方法是改变}
{14007}{}{未感染的DNA，使其不再易受标准病毒感染。}
#
{14008}{}{**结束-段落**}
{14009}{}{2076年。不可预见的副作用在2076年初开始显现，}
{14010}{}{动物实验对象开始表现出异常的生长速度，并伴随}
{14011}{}{脑活动增加。美国政府注意到了这些发现，并出于}
{14012}{}{国家安全的考虑，派遣一个团队进驻现场以确保和}
#
{14013}{}{监督项目，该项目现被称为FEV（强制进化病毒）项目。}
{14014}{}{**结束-段落**}
{14015}{}{2077年。FEV接近完成。实验室动物测试成功率接近}
{14016}{}{100%。体型和肌肉密度增加约60%，潜在智力}
{14017}{}{提高200%。对人类的影响}
{14018}{}{安全部门已派遣一个小组到现场进行保护和监督}
{14019}{}{这个现在被称为FEV（强制进化病毒）项目的工程。}
{14020}{}{**结束-段落**}
{14021}{}{2077年。FEV项目接近完成。实验室动物测试几乎}
#
{14022}{}{达到100%的成功率。体型和肌肉密度}
{14023}{}{增加约60%，潜在智力}
{14024}{}{提高200%。对人类的影响}
{14025}{}{**结束-磁盘**}
{14026}{}{研究对象仍然未知；尽管理论上}
{14027}{}{很有前景。军方希望继续进行更多}
{14028}{}{测试，在加州中部的马里波萨}
{14029}{}{军事基地建造了一个大型设施。在这个}
{14030}{}{新设施中，FEV病毒的测试继续在}
{14031}{}{来自军队的志愿者身上进行。}
{14032}{}{**结束-磁盘**}


# Computer Downlod of the Power Armor Specs
# Uses the global var COMPUTER_POWER_ARMOR

{15000}{}{T-51b动力装甲设计有最新的}
{15001}{}{被动防御功能，适用于民用和}
{15002}{}{军用干扰。背部安装的TX-28}
{15003}{}{微聚变电池提供60,000瓦特的能量，驱动}
{15004}{}{内置于装甲框架中的高流液压系统。}
{15005}{}{T-51b外壳采用最新的聚合复合材料制成，}
{15006}{}{重量轻，能够吸收超过2500焦耳的动能冲击。}
{15007}{}{10微米的银质消融涂层可以反射激光和辐射}
{15008}{}{而不损害复合材料的底层。}
{15009}{}{**结束-段落**}
{15010}{}{罗伯特·安德森}


# Computer Download of the Personel Records
# Uses the global var COMPUTER_RECORDS

{16000}{}{研究助理}
{16001}{}{安全等级：蓝色}
{16002}{}{驻地：马里波萨军事基地}
{16003}{}{**结束-段落**}
{16004}{}{尼克·戴维斯}
#
{16005}{}{西部科技研究NBC部门主任}
{16006}{}{安全等级：蓝色}
{16007}{}{驻地：西部科技研究设施}
{16008}{}{研究助理}
{16009}{}{约翰·艾萨克}
#
{16010}{}{研究助理}
{16011}{}{**结束-段落**}
{16012}{}{安全许可：红色}
{16013}{}{驻扎地：西部科技研究设施}
{16014}{}{**结束段落**}
#
{16015}{}{史蒂夫·雷姆科}
{16016}{}{研究助理}
{16017}{}{安全许可：蓝色}
{16018}{}{驻扎地：马里波萨军事基地}
{16019}{}{**结束段落**}
#
{16020}{}{查尔斯·里格霍尔德}
{16021}{}{激光开发研究负责人}
{16022}{}{安全许可：蓝色}
{16023}{}{驻扎地：西部科技研究设施}
{16024}{}{**结束段落**}
#
{16025}{}{米歇尔·桑托斯}
{16026}{}{实验室技术员}
{16027}{}{安全许可：红色}
{16028}{}{驻扎地：西部科技研究设施}
{16029}{}{**结束段落**}
#
{16030}{}{艾琳·谢尔曼}
{16031}{}{实验室技术员}
{16032}{}{安全许可：蓝色}
{16033}{}{驻扎地：马里波萨军事基地}
{16034}{}{**结束段落**}
#
{16035}{}{莱昂·冯费尔登}
{16036}{}{FEV研究负责人}
{16037}{}{安全许可：蓝色}
{16038}{}{驻扎地：马里波萨军事基地}
{16039}{}{**结束磁盘**}

# Holodisk from the Brotherhood Library
# uses the global var BROTHERHOOD_LIBRARY_DISK

{17000}{}{避难所位置 v34.129 修订版 C（美国西部）}
{17001}{}{**结束段落**}
#
{17002}{}{您好，欢迎阅读最新一期的西部}
{17003}{}{美国避难所位置手册。我们希望您}
{17004}{}{喜欢这本手册，并记住，避难所不仅仅是}
{17005}{}{为上流社会准备的，而是为所有人而设。}
{17006}{}{**结束-段落**}
#
{17007}{}{避难所12号}
{17008}{}{**结束-段落**}
#
{17009}{}{在贝克斯菲尔德这座庞大的城市下，}
{17010}{}{坐落着技术奇迹——避难所12号。为了}
{17011}{}{未来的避难所居民，避难所12号配备了}
{17012}{}{所有设施，并因其准备工作的周到而获得}
{17013}{}{了“熨烫整齐的避难服”奖。深埋地下，}
{17014}{}{避难所居民将获得前所未有的保护。与其他}
{17015}{}{避难所类似，避难所12号配备了最新的}
{17016}{}{避难所水净化系统。即使是贝克斯菲尔德}
{17017}{}{下水道中的废水，这个系统也能处理，}
{17018}{}{每天提供超过15,000加仑的纯净、}
{17019}{}{清爽的饮用水。}
{17020}{}{**结束-段落**}
{17021}{}{避难所13号}
#
{17022}{}{**结束-段落**}
{17023}{}{位于避难所12号西北的风景如画的山区，}
#
{17024}{}{这个避难所为居民提供源源不断的纯净水。}
{17025}{}{关于该地区水源在核战争中可能被污染的}
{17026}{}{传言，已被水电部证实为完全无根据。}
{17027}{}{即使该地区的水源受到污染，尽管这种可能性}
{17028}{}{微乎其微，}
{17029}{}{水电部门完全}
{17030}{}{没有根据。在极少数情况下，如果该地区的水源}
{17031}{}{受到污染，尽管可能性很小，}
{17032}{}{13号避难所已安装政府批准的}
{17033}{}{避难所水净化系统。该系统的额定工作时间超过250,000小时，}
{17034}{}{在此期间不会出现显著性能下降，}
{17035}{}{未来的避难所居民无需担心。}
{17036}{}{**结束-段落**}
#
{17037}{}{15号避难所}
{17038}{}{**结束-段落**}
#
{17039}{}{位于13号避难所正东，15号避难所的建设进展非常顺利。}
{17040}{}{我们对避难所的第三层墙壁进行了大量加固工作，}
{17041}{}{以确保未来的避难所居民在}
{17042}{}{即使发生重大地震时也能安心，}
{17043}{}{避难所的调控计算机将继续正常运作。}
{17044}{}{最近对新建成的避难所的参观，}
{17045}{}{让许多潜在的避难所居民对}
{17046}{}{这个已经令人印象深刻的避难所的改进感到惊叹。}
{17047}{}{**结束-磁盘**}
{17048}{}{监管者的无线电传输日志：}
{17049}{}{**结束-段落**}

#Regulator Disk from Blades

{18000}{}{发送信息：监管者巡逻队呼叫监管者基地，}
{18001}{}{请回答。完毕。}
{18002}{}{**结束-段落**}
{18003}{}{收到信息：这里是监管者基地，首席监管者凯莱布回应。报告？完毕。}
{18004}{}{**结束-段落**}
{18005}{}{发送信息：是的，长官！二级监管者克拉沃塔报告。我们已经逮捕了}
{18006}{}{试图再次潜入我们防线的齐默尔曼男孩，长官。}
{18007}{}{指示？完毕。}
{18008}{}{信息发送：是，长官！二级监管员}
{18009}{}{克拉沃塔报告。我们抓住了齐默尔曼家的}
{18010}{}{小子又试图渗透我们的防线，长官。}
{18011}{}{请指示？完毕。}
{18012}{}{**结束-段落**}
{18013}{}{收到信息：该死！又来了！这是最后一次}
{18014}{}{会发生这种事。干掉他，伪装成刀锋帮干的。}
{18015}{}{明白了吗？完毕。}
{18016}{}{**结束-段落**}
{18017}{}{发送信息：长官？呃……我听清楚了吗，长官？}
{18018}{}{杀了他？完毕。}
{18019}{}{**结束-段落**}
{18020}{}{收到信息：确认，监管者。}
{18021}{}{我要搞得乱一点，把他钉在前面的警卫柱上}
{18022}{}{哦，还有割掉他的舌头，这样他就不能在我们“尝试”}
{18023}{}{救他的时候说话了。}
{18024}{}{完毕？}
{18025}{}{**结束-段落**}
{18026}{}{发送信息：会完成的，长官，完毕。}
{18027}{}{**结束-段落**}
{18028}{}{结束传输。}
{18029}{}{**结束-磁盘**}
{18030}{}{**结束-磁盘**}
