{100}{}{火箭}
{200}{}{等离子球}
{300}{}{爆炸}
{400}{}{血液}
{500}{}{无传输十六进制}
{501}{}{}
{600}{}{刀}
{700}{}{长矛}
{800}{}{电磁脉冲爆炸}
{900}{}{激光射击}
{1000}{}{等离子爆炸}
{1100}{}{爆炸}
{1200}{}{滚动阻挡器}
{1300}{}{电流}
{1400}{}{爆炸}
{1500}{}{爆炸}
{1600}{}{出口网格}
{1700}{}{出口网格}
{1800}{}{出口网格}
{1900}{}{出口网格}
{2000}{}{出口网格}
{2100}{}{出口网格}
{2200}{}{出口网格}
{2300}{}{出口网格}
{2400}{}{照明弹}
{2500}{}{手榴弹}
{2600}{}{石块}
{2700}{}{爆炸}
{2800}{}{爆炸}
{2900}{}{爆炸}
{3000}{}{燃烧瓶}
{3100}{}{出口网格}
{3200}{}{出口网格}
{3300}{}{出口网格}
{3400}{}{出口网格}
{3500}{}{出口网格}
{3600}{}{出口网格}
{3700}{}{出口网格}
{3800}{}{出口网格}
{3900}{}{出口网格}
{4000}{}{出口网格}
{4100}{}{出口网格}
{4200}{}{出口网格}
{4300}{}{出口网格}
{4400}{}{出口网格}
{4500}{}{出口网格}
{4600}{}{出口网格}
