#
#	 Messages from stat.c
#
#
#	 STAT NAMES
#
{100}{}{力量}
{101}{}{感知}
{102}{}{耐力}
{103}{}{魅力}
{104}{}{智力}
{105}{}{敏捷}
{106}{}{幸运}
{107}{}{最大生命值}
{108}{}{最大行动点数}
{109}{}{护甲等级}
{110}{}{徒手伤害}
{111}{}{近战伤害}
{112}{}{负重能力}
{113}{}{先攻顺序}
{114}{}{恢复速度}
{115}{}{暴击几率}
{116}{}{更佳暴击}
{117}{}{伤害阈值}
{118}{}{激光伤害阈值}
{119}{}{火焰伤害阈值}
{120}{}{等离子伤害阈值}
{121}{}{电击伤害阈值}
{122}{}{EMP伤害阈值}
{123}{}{爆炸伤害阈值}
{124}{}{伤害抗性}
{125}{}{激光伤害抗性}
{126}{}{火焰伤害抗性}
{127}{}{等离子伤害抗性}
{128}{}{电击伤害抗性}
{129}{}{EMP伤害抗性}
{130}{}{爆炸伤害抗性}
{131}{}{辐射抗性}
{132}{}{毒素抗性}
{133}{}{年龄}
{134}{}{性别}
{135}{}{当前生命值}
{136}{}{当前中毒等级}
{137}{}{当前辐射等级}
#
#	 STAT DESCRIPTIONS
#
# @ Basic stats @
#
# Strength
{200}{}{原始的体力。高力量对物理型角色有利。影响：生命值、近战伤害和负重。}
# Perception
{201}{}{感知力是看、听、尝和注意异常事物的能力。高感知力对神枪手很重要。影响：先攻值和远程战斗距离修正。}
# Endurance
{202}{}{耐力和身体韧性。高耐力的角色能在其他人无法生存的环境中存活。影响：生命值、毒素和辐射抗性、恢复速度和每级额外生命值。}
# Charisma
{203}{}{外貌和魅力的结合。高魅力对想用言语影响他人的角色很重要。影响：NPC反应和交易价格。}
# Intelligence
{204}{}{知识、智慧和快速思考的能力。高智力对任何角色都很重要。影响：每级新技能点数、对话选项和多种技能。}
# Agility
{205}{}{协调性和良好移动能力。高敏捷对任何活跃的角色都很重要。影响：行动点数、防御等级、先攻值和多种技能。}
# Luck
{206}{}{命运。因果。极高或极低的运气会以某种方式影响角色。事件和情况会因角色的幸运（或不幸）而改变。}
#
# Derived/Non Derived stats
#
# Maximum Hit Points
{207}{}{角色在死亡前能承受的伤害量。如果生命值降至0或更低，你将死亡。}
# Maximum Action Points
{208}{}{角色在一回合战斗中可以进行的动作次数。}
# Armor Class
{209}{}{影响击中该角色的几率。}
# Unarmed Damage
{210}{}{角色在徒手战斗中造成的额外伤害。}
{211}{}{角色在徒手战斗中造成的额外伤害。}
# Carry Weight
{212}{}{角色能携带的最大装备重量，以磅为单位。}
# Sequence
{213}{}{决定角色在战斗回合中能多快反应。}
# Healing Rate
{214}{}{每天结束时，角色每一点恢复速度可恢复1点生命值。休息时，每六小时恢复一次。}
# Critical Chance
{215}{}{提高战斗中造成重击的几率。}
{216}{}{更好的重击}
{217}{}{伤害阈值}
{218}{}{激光伤害阈值}
{219}{}{火焰伤害阈值}
{220}{}{等离子伤害阈值}
{221}{}{电击伤害阈值}
{222}{}{伤害阈值 电磁脉冲}
{223}{}{伤害阈值 爆炸}
# Damage Resistance
{224}{}{受到的伤害将减少此数值。穿戴护甲可以增加伤害抗性。}
{225}{}{伤害抗性 激光}
{226}{}{伤害抗性 火焰}
{227}{}{伤害抗性 等离子}
{228}{}{伤害抗性 电击}
{229}{}{伤害抗性 电磁脉冲}
{230}{}{伤害抗性 爆炸}
# Radiation Resistance
{231}{}{你受到的辐射量将减少此百分比。辐射抗性可以通过不同类型的护甲和抗辐射药剂来改变。}
# Poison Resistance
{232}{}{减少此数值的毒性伤害。}
{233}{}{年龄}
{234}{}{性别}
{235}{}{当前生命值}
{236}{}{当前中毒等级}
{237}{}{当前辐射等级}
#
# STAT LEVEL DESCRIPTIONS
#
{301}{}{非常差}
{302}{}{差}
{303}{}{较差}
{304}{}{一般}
{305}{}{中等}
{306}{}{良好}
{307}{}{非常好}  # 缩略用于角色编辑器
{308}{}{极好}
{309}{}{优秀}
{310}{}{英雄级}
#
#	 PC STAT NAMES
#
{400}{}{未使用技能点}
{401}{}{等级}
{402}{}{经验}
{403}{}{声望}
{404}{}{善恶值}
#
#	 PC STAT DESCRIPTIONS
#
# Unspent Skill Points
{500}{}{通过升级获得的点数。每花费一点可以将一项技能提升1%，或将标记技能提升2%。}
# Level
{501}{}{玩家角色的综合能力。衡量你的经验和能力。}
# Experience
{502}{}{完成特定任务或在战斗中击败敌人后获得的奖励。达到更高等级需要更多的经验点数。}
# Reputation
{503}{}{世界对你行为和事迹的认知。这将影响NPC的反应。}
# Karma
{504}{}{你所采取行动的影响。重要信息将会显示。}

#
#  Experience-gain messages
#
{600}{}{你升级了。}
