#
# Messages for Prototypes
#
# strings
#
{10}{}{<无>}

#
# Material Types
#
{100}{}{玻璃}
{101}{}{金属}
{102}{}{塑料}
{103}{}{木材}
{104}{}{泥土}
{105}{}{石头}
{106}{}{水泥}
{107}{}{皮革}

#
# Item Types
#
{150}{}{护甲}
{151}{}{容器}
{152}{}{药物}
{153}{}{武器}
{154}{}{弹药}
{155}{}{杂项物品}
{156}{}{钥匙}

#
# Scenery Types
#
{200}{}{传送门}
{201}{}{楼梯}
{202}{}{电梯}
{203}{}{梯子底部}
{204}{}{梯子顶部}
{205}{}{通用景物}

#
# Damage Code Types
#
{250}{}{普通伤害}
{251}{}{激光}
{252}{}{火焰}
{253}{}{等离子}
{254}{}{电击}
{255}{}{电磁脉冲}
{256}{}{爆炸}

#
# Caliber Types for weapons
#
{300}{}{无}
{301}{}{火箭弹}
{302}{}{喷火器燃料}
{303}{}{小型能量电池}
{304}{}{大型能量电池}
{305}{}{.223口径}
{306}{}{5毫米}
{307}{}{.40口径}
{308}{}{10毫米}
{309}{}{.44口径}
{310}{}{14毫米}
{311}{}{12号霰弹}
{312}{}{9毫米}
{313}{}{BB弹}

#
# Race Types
#
{350}{}{高加索人}
{351}{}{非洲裔}

#
# Body Types
#
{400}{}{双足动物}
{401}{}{四足动物}
{402}{}{机器人}
#
# Kill Types names
#
{450}{}{男性}
{451}{}{女性}
{452}{}{儿童}
{453}{}{超级变种人}
{454}{}{食尸鬼}
{455}{}{双头牛}
{456}{}{辐射蝎}
{457}{}{老鼠}
{458}{}{漂浮者}
{459}{}{半人马}
{460}{}{机器人}
{461}{}{狗}
{462}{}{螳螂}
{463}{}{死亡爪}
{464}{}{主宰}       # 不显示！# # 杀戮类型信息描述 # {465}{}{此行显示你在冒险过程中杀死的男性人类数量。}
{466}{}{此行显示你在冒险过程中杀死的女性人类数量。}
{467}{}{此行显示你在冒险过程中杀死的年轻人类儿童数量。你这个恶棍。}
{468}{}{你在冒险过程中杀死的超级变种人的数量。}
{469}{}{此行显示你在冒险过程中杀死的男性和女性食尸鬼变种人的数量。}
{470}{}{此行显示你在旅行中宰杀的布拉明（变异牛）数量。}
{471}{}{你在冒险中杀死的变异辐射蝎的数量。}
{472}{}{你杀死的老鼠数量。包括所有鼠类成员。}
{473}{}{你杀死的变种浮游生物的数量。}
{474}{}{你杀死的变种半人马的数量。}
{475}{}{你摧毁或拆解的机器人数量。}
{476}{}{你送往天堂犬舍的狗的总数。}
{477}{}{此行显示你迄今为止拍扁的螳螂，或大型变异螳螂类昆虫的总数。}
{478}{}{此行显示你已杀死死亡爪及其所有后代。}
{479}{}{不显示。错误！}

#
# Use text
#
{480}{}{你看到：%s。}

#
# Use Container text
#
{485}{}{你搜索了%s。}
{486}{}{你关闭了%s。}
{487}{}{它被锁住了。} # 新增 # # 查看文本 # {490}{}{你看到：%s。}
{491}{}{你看到一个死去的：%s。}
{492}{}{你看到：%s的遗骸。}
{493}{}{你没有发现任何异常。}

#
# Examine text
#
{500}{}{死亡}
{501}{}{濒死}
{502}{}{重伤}
{503}{}{受伤}
{504}{}{无伤}

#
# Examine text messages
#
{518}{}{你看起来：%s}
{519}{}{%s %s}
{520}{}{你看起来：%s。}
{521}{}{%s %s。}
{522}{}{他看起来：%s}
{523}{}{她看起来：%s}
{524}{}{它看起来：%s}
# (note: hps are short for hit-points)
{525}{}{%s 生命值：%d/%d。}
# (note: this is for guns that have ammo)
{526}{}{它有 %d/%d 发 %s。}
{530}{}{并且肢体残疾。}  # 这些附加在行 500-504 {531}{}{但肢体残疾。}
{532}{}{并且肢体残疾。}
{533}{}{但肢体残疾。}
# (note: hps are short for hit-points)
{535}{}{他生命值：%d/%d}
{536}{}{她生命值：%d/%d}
{537}{}{它生命值：%d/%d}
{540}{}{它重 %d 磅。}
{541}{}{它重 %d 磅。}
{544}{}{，}
{545}{}{。}
{546}{}{ 并且装备了 %s。}
{547}{}{ 并且装备了 %s，剩余 %d/%d 发 %s。}

#
# Examine text error messages
#
{550}{}{\n错误：lookup_val 超出范围！}
{551}{}{\n错误：obj_examine：proto_ptr 失败！}

#
# Use text messages
#
{580}{}{你使用了 %s。}
{581}{}{你将 %s 用在了 %s 上。}
{582}{}{这没有任何效果。}
{583}{}{令你失望的是，你意识到它已经死了。}
{584}{}{当你弯下身时，你意识到它已经死了。}
{585}{}{唉，你来得太晚了。} # 这与一个生物已经死了有关。 {586}{}{这对死者无效。}
{587}{}{你点燃了信号弹。}
{588}{}{信号弹已经被点燃。}
{589}{}{你设置了计时器。}
{590}{}{计时器已经在倒计时！}

#
# Experience-Point messages
#
{620}{}{你因击杀：%s 获得 %d 点经验值。}
{621}{}{%s 你获得 %d 点经验值。}
{622}{}{为了击败你的敌人，}
{624}{}{你在战斗中取得胜利，}
{625}{}{为了粉碎你的敌人，}
{626}{}{为了毫发无损地消灭敌人，}

#
# Dialog messages
#
{650}{}{[完成]}
{651}{}{[更多]}
{652}{}{更多}
{653}{}{[返回]}
{654}{}{返回}     # 改变编号从 653 {655}{}{继续}    # 新的 {656}{}{呃...}   # 新的 {660}{}{你看不到那里。}
{661}{}{太远了。}

#
# Not Enough AP message
#
{700}{}{你的行动点数不够。}
#
# Book messages
#
{800}{}{你读了这本书。}
{801}{}{你没有学到新东西。}
{802}{}{你学到了新的科学信息。}
{803}{}{你学到了很多关于修理损坏电子设备的知识。}
{804}{}{你学到了新的治疗伤口的方法。}
{805}{}{你学会了更好地使用枪械。}
{806}{}{你学到了很多关于荒野生存的知识。}
#
# Use on messages (and some extra stuff that Jesse needed)
#
{900}{}{医生包里的物资用完了。}
{901}{}{急救包里的物资用完了。}
{902}{}{你无法在战斗中这样做。}
{903}{}{这个人不愿与你交易。}
{904}{}{这个人没有什么可告诉你的。}
{905}{}{你无法捡起那个物品。你已经达到最大负重。}
