{101}{}{}                                               #obj_dude {102}{}{长老。}                                         #elder {103}{}{交易员}                                      #barter {104}{}{保镖}                                      #bguard {105}{}{牛}                                            #cow {106}{}{枪械跑商护卫}                           #MoatGrd {107}{}{阴影沙地护卫}                              #guard {108}{}{失败者}                                          #loser {109}{}{阴影沙地农民}                            #pleasant {110}{}{枪械跑商}                                      #GunRnr {111}{}{地图入口}                                #map_init
