{100}{}{你看到了阿贝尔。}
{101}{}{你看到一个巨大的变种人。}
{102}{}{你不应该在这里。}
{103}{}{哼。}
{104}{}{当然不是。我是来杀你的！}
{105}{}{你为什么这么说？}
{106}{}{哦，是吗？你妈才是！}
{107}{}{皮克！}
{108}{}{如果你再说一次，我就揍你！}
{109}{}{皮克！皮克！}
{110}{}{哦，你这下完蛋了！}
{111}{}{你是人类。我是变种人。变种人杀人类。}
{112}{}{你怎么做到的？那力场怎么办？}
{113}{}{阿贝尔会处理的。然后阿贝尔揍你！}
{114}{}{小孩子不许来这里。这是变种人的地方。走开。}
{115}{}{哼！}
{116}{}{我必须通过这个力场。请你把它关掉。}
{117}{}{不行。}
{118}{}{又是你。阿贝尔要揍你！}

# tell me about name
{970}{}{我是阿贝尔。}

# tell me about generic
{980}{}{哼。}
{981}{}{你为什么这么说？}
