{100}{}{你看到艾莉娅，一个沙漠掠夺者。}
{101}{}{我是可汗的艾莉娅。今天有什么我可以帮你的吗？}
{102}{}{我在找一个叫坦迪的女人。你见过她吗？}
{103}{}{要不要来个吻？}
{104}{}{为什么你们的掠夺者团伙袭击阴影镇？}
{105}{}{不，谢谢。}
{106}{}{再见！}
{107}{}{如果她是阴影镇的女人，也许你该去那里找找。现在走开，我得继续磨我的刀。}
{108}{}{亲这个吧！}
{109}{}{我们没有袭击阴影镇的人。我们和他们来自同一个地方。他们理应与我们分享！}
{110}{}{但你们伤害了他们的牲畜，还让他们害怕。}
{111}{}{这对我来说很公平。}
{112}{}{呃，是的。我想我该走了。}
{113}{}{你听起来和他们一样软弱。听着，如果他们面临饥饿，那是他们自己没计划好。把我们做的看作是一种才能的交换。}
{114}{}{才能的交换？！这怎么能算是才能的交换？你们什么都没给他们。}
{115}{}{当然，鸡还有三条腿呢。}
{116}{}{呃，是的。我想我该走了。}
{117}{}{抱歉，我听不懂你说什么。我正在磨刀，不想被打扰。}
{118}{}{我们给了他们最重要的东西。我们给了他们枯燥生活中的刺激。}
{119}{}{我不认为他们需要你这种刺激。}
{120}{}{我想我要让他们的生活再次无聊起来。就从你开始！}
{121}{}{呃，是的。我想我该走了。}
{122}{}{我没问。但既然你显然不懂得乐趣，我想我会结束你的存在。}
{123}{}{嘲笑我对你没好处。我建议你离开我的视线。}
{124}{}{当然公平。现在从我面前消失。}
{125}{}{我现在很忙，正在为下一次袭击做准备。}
