{100}{}{卡尔诺尔，废城的守卫。}
{101}{}{你最好在这里小心点。}
{102}{}{这可不是个惹麻烦的好地方。}
{103}{}{规矩点，我们就不会对你不客气。}
{104}{}{你没问题。}
{105}{}{继续保持。}
{106}{}{今天天气不错，是吧？}
{107}{}{这里是废城。只要你不惹事，这里是个不错的居住地。}
{108}{}{小心吉兹莫和他的手下。}
{109}{}{我喜欢我的老板。}
{110}{}{你最好把那东西收起来。废城是个友好的地方，朋友，我们希望它一直这样。}
{111}{}{把什么收起来？}
{112}{}{别告诉我该怎么做，废物。}
{113}{}{听起来很合理。顺便问一下，这里的武器法律是什么？}
{114}{}{呃，哦。}
{115}{}{你的武器，笨蛋。基利安不会没收你的武器，但你最好把它们放在枪套里。}
{116}{}{哦，抱歉。}
{117}{}{不可能！我不会为任何人放下我的枪！}
{118}{}{你最好守规矩，因为这是法律，而我是执法者。把你的武器收起来。除非是自卫，不要拔枪，这样你就不会和我们这些守卫有麻烦。违反法律，我们会让你回到无序的荒原——生或死。}
{119}{}{当然，既然你这么说。}
{120}{}{去你的法律！}
{121}{}{嗯，呃，对我来说没问题。但你最好小心点。}
{122}{}{问得好。除非自卫，否则不能拔枪。如果你挑起争斗，那就是你的责任。除此之外，你有权携带武器。只是不要无缘无故拔刀或枪。祝你有个愉快的一天。}
{123}{}{嘿，你，没有武器！我不管你小时候是不是被妈妈摔过。没有武器。}
{124}{}{嘿！你！你在这里鬼鬼祟祟地干什么？}
{125}{}{没什么。}
{126}{}{我没有鬼鬼祟祟。我只是喜欢小心行事。}
{127}{}{呃。}
{128}{}{不管你在干什么，别在这个镇上干。}
{129}{}{嘿！镇上不许有可疑人物！在我们把你赶出去之前，赶紧走！}
{130}{}{嗯，呃，好吧。随便你。只要别做出格的事。}
{131}{}{谢谢，再见。}
{132}{}{当然。我会大胆行事，先生。}
{133}{}{当然。我会大胆行事，女士。}
{134}{}{你最好在这里小心点，因为我们会盯着你。}
{135}{}{欢迎来到废城。我能为你做些什么？}
{136}{}{没什么，谢谢。}
{137}{}{你在这里做什么？这是个什么地方？}
{138}{}{我在哪里可以得到一些补给？}
{139}{}{哇哇！}
{140}{}{我不太清楚。你可以去找基利安问问。他在北边。就是那个方向，好吗？}
{141}{}{看不出来吗？我是个守卫，我在留意像你这样的陌生人。这里叫废城。嘿，别笑。我自己还挺喜欢这个名字的。我们主要做贸易。有时候我们和那些自命不凡的集市混蛋交易。嘿，你不是来自集市吧？}
{142}{}{什么？集市？当然我是！}
{143}{}{我？不，我不是来自集市。}
{144}{}{那你应该知道大部分规矩。祝你有个愉快的一天。抱歉之前说了混蛋，好吗？}
{145}{}{是的！嘿，没问题。再见。}
{146}{}{这会给我造成严重的心理创伤。再见。}
{147}{}{嗯。好吧。我们无权过问。祝你有个愉快的一天，别惹麻烦。}
{148}{}{哦，天哪。补给的地方是达克沃特的。基利安经营的。就在北边一点。基利安有镇上最好的补给。}
{149}{}{谢谢。再见。}
{150}{}{你想让我带你去看看“你的”补给在哪里吗？}
{152}{}{呃，不。抱歉，女士。我这里有工作要做。}
{153}{}{祝你有个愉快的一天。}
{154}{}{别惹麻烦。}
{155}{}{天啊，我真希望我的替班快点来。我感觉我站岗站了一个世纪。}
{156}{}{抱歉，大门晚上关闭了。请早上再来。}
{157}{}{嘿，我需要进去！}
{158}{}{没问题。早上见。}
{159}{}{抱歉打扰您，先生，但我想进入您的城镇。您可以看到我不会造成任何伤害。}
{160}{}{嗯哼！}
{161}{}{回来……白天……}
{162}{}{抱歉，规矩就是规矩。晚上不允许陌生人进入。}
{163}{}{好吧，我本不该这样做，但你看起来是个不错的人。进来吧，但别惹麻烦。}
{164}{}{嘿！是你！进来吧，}
{165}{}{。很高兴再次见到你！}
{166}{}{嘿，你最好立刻转身走出去。}
{167}{}{进去吧。}
