{100}{}{我来这里是为了踢屁股和嚼泡泡糖。可惜泡泡糖已经嚼完了。}
{101}{}{兄弟会在为我们的成功祈祷，长官。}
{102}{}{出发吧。}
{103}{}{保持你的战术姿态，长官。}
{104}{}{我们最好赶紧出发。}
{105}{}{没时间闲聊，长官。}
{106}{}{我来这里是为了踢屁股和嚼泡泡糖。可惜泡泡糖已经嚼完了。}
{107}{}{兄弟会在为我们的成功祈祷，女士。}
{108}{}{出发吧。}
{109}{}{保持你的战术姿态，女士。}
{110}{}{我们最好赶紧出发。}
{111}{}{没时间闲聊，女士。}
{112}{}{很好，你来了。让我们烧掉这个地方。}
{113}{}{这个房间有些不对劲。}
{114}{}{这个地方开始让我毛骨悚然了。}
{115}{}{现在是时候回兄弟会了。}
