{100}{}{你看到一个少年。}
{101}{}{是你！是你干的！等我长大了，我一定会找到你！我要追杀你！你杀了他们所有人！全都杀了！[失控地抽泣]。}
{102}{}{这是唯一的办法。唯一能阻止他们的办法。}
{103}{}{你是怎么在核爆中幸存下来的？}
{104}{}{这是谎言，小孩。我没干这事！}
{105}{}{你最好去找个医生，小孩。你有辐射病。}
{106}{}{你知道吗，小孩，我可不需要二十年后有个硬汉来找我麻烦。晚安，小鬼。}
{107}{}{我听说过你。你在荒野上到处杀小孩！救命！夜行者！}
{108}{}{你搞错了，孩子。我是个好人。}
{109}{}{是啊，如果你不闭嘴，你活不到做噩梦的时候。}
{110}{}{我不是来找你麻烦的，小孩，所以安静点。}
{111}{}{我做了什么？他们不只是小个子吗？}
{112}{}{好吧。我会安静的。但我希望夜行者抓到你！}
{113}{}{夜行者！夜行者！}
{114}{}{也许是别人干的。但如果是你，我长大后一定会找到你，让你付出代价！}
{115}{}{您好，先生。您需要一朵冥想花吗？}
{116}{}{您好，女士。您需要一朵冥想花吗？}
{117}{}{孩子，这里最近有什么有趣的事情发生吗？}
{118}{}{当然，孩子。}
{119}{}{现在不需要。}
{120}{}{花漂亮吗？}
{121}{}{把那杂草从我面前拿开，小鬼！}
{122}{}{我听说摩菲斯神父亲自接待了大师。他现在非常高兴。}
{123}{}{还有别的吗？}
{124}{}{我敢打赌。}
{125}{}{现在不需要。}
{126}{}{花漂亮吗？}
{127}{}{把那杂草从我面前拿开，小鬼！}
{128}{}{拉舍神父说我得闭上我的大嘴巴。他一点都不好玩！}
{129}{}{来吧，小孩。你肯定见过什么！}
{130}{}{拉舍神父？}
{131}{}{好玩是好事。}
{132}{}{听起来他和我有很多共同点。}
{133}{}{太好了！愿大师保佑你。[他递给你一朵花。]}
{134}{}{哎呀！你一点都不好玩。也许我应该告诉夜行者关于你的事！}
{135}{}{夜行者是我的朋友。}
{136}{}{你还太年轻，不明白我有多好玩。}
{137}{}{去吧。我会告诉他们关于你的事。}
{138}{}{你要是敢告诉别人关于我的事，小孩，你就死定了！}
{139}{}{当然是。我自己从城对面的树林里摘的。很高兴见到你。愿大师保佑你。}
{140}{}{我做了什么？我做了什么？！}
{141}{}{你确定不想要一朵花吗？}
{142}{}{如果你告诉我这里发生了什么，我就拿。}
{143}{}{好吧。我拿着。}
{144}{}{抱歉，小孩。我不是那种喜欢花的人。}
{145}{}{抱歉，小孩。你还太小，不能给我送花。}
{146}{}{我不知道。你为什么问？}
{147}{}{我不能告诉你！夜行者会吃了我！}
{148}{}{他是我的老师。他说每次鞭打都让我们更接近大师！}
{149}{}{多么迷人的人。我们真的得聊聊。}
{150}{}{别相信他，小孩。}
{151}{}{这混蛋在哪？我要杀了他。}
{152}{}{老师？需要老师干嘛？}
{153}{}{你还没学会什么时候该闭嘴？你脑子里装的是粪便吗，小孩。}
{154}{}{呃，再见！}
{155}{}{是啊。是的。好吧，再见_呃_愿大师保佑你！}
{156}{}{但夜行者喜欢我！他们告诉我如果有人打扰我，他们会杀了他们。就这样！}
{157}{}{我听说这里有个秘密通道，但我还没找到。据说很危险。只有摩菲斯和夜行者能进去。好吧，我得走了。赞美大师！}
{158}{}{那太糟糕了。愿大师仍然保佑你。}
{159}{}{请不要告诉他我对你说了什么！拜托！}
{160}{}{别担心。我处理完他后，他什么都不会记得。}
{161}{}{我不会的。我保证。}
{162}{}{管好你自己的事，小孩。}
{163}{}{吼！你说什么？}
{164}{}{生活很艰难。学会承受，小孩，别再抱怨了。}
{165}{}{但我必须！我必须！不信就是痛苦！}
{166}{}{请不要！他爱我！他是唯一爱我的人。}
{167}{}{那还好吧，我想。愿大师保佑你。再见。}
{168}{}{谢谢你！哦谢谢你！愿大师保佑你。再见。}
{169}{}{好吧，我会的……（抽泣）也许当大师统治世界后，拉舍神父会对我更好。}
{171}{}{大师什么时候会统治世界？}
{172}{}{告诉我更多关于这个的事，小孩。}
{173}{}{他不会的。他会变得更糟。但如果你聪明，成为她的宠儿，他会让你折磨新来的孩子。}
{174}{}{呃！我喜欢善良。}
{175}{}{很快，他们是这么告诉我的。我们将迎来和平、统一，圣火将被点燃。也许摩菲斯神父不会那么吵了。}
{176}{}{还有别的吗？}
{177}{}{摩菲斯神父？}
{178}{}{吵死了！}
{179}{}{呃，我真的不知道太多。真的。愿大师保佑！再见！}
{180}{}{嗨。你好吗？}
{181}{}{还好，小孩。有什么好消息吗？}
{182}{}{好吧。你有什么小道消息给你的老朋友吗？}
{183}{}{还不错。你呢？}
{184}{}{我不知道。无聊。}
{185}{}{我感觉糟透了。你知道我多久没杀过东西了吗？}
{186}{}{呃，你好。}
{187}{}{你好，小孩。你能告诉我这个地方是干什么的吗？}
{188}{}{嗨，小孩。你在这地方干什么？}
{189}{}{嗨，小孩。你怎么样？}
{190}{}{滚开，小鬼，否则我把你做成腰带！}
{191}{}{你好？和黄色押韵！有趣！}
{192}{}{这是大教堂的儿童大教堂。我不知道为什么他们要说两遍大教堂。我们崇拜大师，并大喊和平与统一。听起来有点蠢，但大师真的很聪明，所以我想这一定没问题。}
{193}{}{告诉我更多关于大师的事。}
{194}{}{听起来也很蠢。你在这里做什么？}
{195}{}{不要那样谈论你的长辈，好吗？}
{196}{}{你是个什么样的被洗脑的小傻瓜？你会长成这些僵尸中的一个！我现在就应该杀了你！}
{197}{}{我发放花朵。每片花瓣代表和平，花茎代表统一。或者是花瓣代表统一，花茎代表和平？哦不，我不记得了！你要一朵吗？}
{198}{}{如果你告诉我这里发生了什么，我就拿一朵。}
{199}{}{当然。}
{200}{}{不用，谢谢。}
{201}{}{去他的和平。去他的统一。把那花从我面前拿开！}
{202}{}{拉舍神父说我不应该和陌生人说话……当然，直到我们有了统一，那时就没有陌生人了。再见！}
{203}{}{我还好。至少在拉舍神父的下一课之前。}
{204}{}{也许如果你更努力学习，课程就不会那么糟糕。}
{205}{}{告诉我更多关于拉舍神父的事。}
{206}{}{什么样的课程？}
{207}{}{别再抱怨了，小鬼，感激有人愿意教你！}
{208}{}{我从来做得不够好！从来没有！}
{209}{}{[结束]}
