{100}{}{你看到一个儿童会的吟唱者。}
{101}{}{主会宽恕你的罪过！加入我们，获得自由！赞美主及其仁慈！}
{102}{}{你好，朋友！主的愿景让我第一次真正活了过来。我可以与你分享这个奇妙的故事吗？}
{103}{}{我在哪里可以见到这位主？}
{104}{}{请继续。}
{105}{}{这里由谁负责？}
{106}{}{主的愿景？比辐射蝎子汁还好吗？}
{107}{}{它会以死亡告终吗？如果不会，我可以改变这一点！}
{108}{}{我喜欢故事！}
{109}{}{主在上方注视！主在下方坐镇！看和平与统一的成长！}
{110}{}{曾经有一个人充满了仇恨，几乎死去。但现在……赞美主！赞美圣焰！赞美生命的葡萄园！哇哦！}
{111}{}{你是负责人，朋友，但主是你的指引者。赞美主！赞美照亮我们道路的圣焰！}
{112}{}{主的愿景远胜于任何饮品，甚至胜过性爱！哦！他超越了恶习与美德！啊！主是我们的父亲，也是我们的爱人！}
{113}{}{只要主在这里保护我们，没有故事会以死亡告终！}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{114}{}{但我必须赞美主！再见，我的朋友！我稍后会讲这个故事！}
{115}{}{但我必须赞美主！再见，我的朋友！我稍后会讲这个故事！}
