{100}{}{你看到面前有一个警觉的侦察兵。}
{101}{}{谁在那里？}
{102}{}{我。我。}
{103}{}{谁去哪里？}
{104}{}{是我！}
{105}{}{死神！}
{106}{}{放心，我是朋友。}
{107}{}{什么？快滚！这里是大教堂之子的领地。}
{108}{}{嗯？我留下！}
{109}{}{嗯？你去死吧！}
{110}{}{我不想走。}
{111}{}{太好了。我拦住的人里竟然有个炮灰。有什么我能帮你的？}
{112}{}{去睡觉吧！}
{113}{}{不不。}
{114}{}{帮我。}
{115}{}{好吧。我建议你赶紧离开这里，以免受伤。}
{116}{}{你想帮我？我怀疑。你有什么？}
{117}{}{不不。}
{118}{}{这个！}
{119}{}{避难所。}
{120}{}{浪费我的时间，滚开！}
{121}{}{避难所。避难所？什么是避难所？}
{122}{}{吃吃。}
{123}{}{不不。}
{124}{}{避难所！避难所！}
{125}{}{哦，你想要糖果。抱歉，我没有。再见。}
{126}{}{哦，避难所。我相信那很不错。也许你可以和我的上级谈谈。我现在有点忙。}
{127}{}{这里非常危险。大怪物占领了这个地方。我们正努力在他们回来之前拯救能拯救的东西。}
{128}{}{不走！不走！}
{129}{}{呃，哦。}
{130}{}{再见。}
{131}{}{好吧。随便你。当他们回来时，你可以成为他们的晚餐。}
{132}{}{我杀！我杀！}
{133}{}{再见。}
{134}{}{你可以试试。不过我不确定你能走多远。祝你好运。}
{135}{}{呃哦没错。他们很可怕。我们在努力让他们理解人类和怪物可以共存。}
{136}{}{哦。好吧。再见。}
{137}{}{在我打爆你的头之前告诉我你是谁。}
{138}{}{我是追随者。大家都去哪了？}
{139}{}{我是你们的人。让我过去。}
{140}{}{我是}
{141}{}{。记住它！}
{142}{}{我不需要。}
{143}{}{去死！！！}
{144}{}{跟我来。我会告诉你其他人去了哪里。}
{145}{}{所以，你是追随者？}
{146}{}{当然！我还能是谁？}
{147}{}{不，我是大教堂之子。}
{148}{}{真傻。我认错人了。跟我来，我会给你指路。}
{149}{}{我不记得你。叫什么名字？}
{150}{}{我是}
{151}{}{。你怎么能忘了我？}
{152}{}{不关你的事。}
{153}{}{我是你最可怕的噩梦。}
{154}{}{抱歉。我还是不记得你。也许其他人会记得你是谁。}
{155}{}{是的，我记得你。我们被告知要找你。复仇将是我的！}
{156}{}{你在我的巡逻区。这是我的事。说话或者死！}
{157}{}{好吧。我是}
{158}{}{。想起来了吗？}
{159}{}{嗯。我想……杀！}
{160}{}{让我想想。}
{161}{}{现在让我看看。是}
{162}{}{。对吧？}
{163}{}{是的，你这个笨蛋。}
{164}{}{是的。}
{165}{}{不，笨蛋。是死神！}
{166}{}{很好。只是为了确保你的墓碑上写对。}
{167}{}{那我就不必让你活着。晚安。}
{168}{}{你是谁？}
{169}{}{我是追随者。大家都去哪了？}
{170}{}{我是你们的人。让我过去。}
{171}{}{我是}
{172}{}{。记住它！}
{173}{}{我不需要！}
{174}{}{去死！！！}
{175}{}{死神，嗯？在我看来你更像是虫饵。}
{176}{}{如果你是朋友，那就证明给我看。}
{177}{}{我帮忙杀了追随者。}
{178}{}{我帮忙杀了撕裂者。}
{179}{}{我帮忙杀了那些变种怪物。}
{180}{}{我帮忙杀了大教堂之子。}
{181}{}{真的吗？我想我的老板会想听更多关于这件事的。去找奥菲欧吧。他会奖励你。}
{182}{}{对于一个以和平为名的人，你杀了不少东西。不过那些撕裂者确实制造了不少麻烦。奥菲欧会奖励你的帮助。}
{183}{}{你杀了那些无害的生物，它们是人类破坏性的结果，然后还宣称和平？}
{184}{}{抱歉。它们太丑了，所以我开枪了。}
{185}{}{它们到处伤害人。}
{186}{}{现在我要杀了你。}
{187}{}{我还是让你活着。我想我最好带你去清除这些破坏的思想。}
{188}{}{有趣。我以为我看到他们在街上试图清理帮派。}
{189}{}{他们袭击了刀锋帮？}
{190}{}{阿迪特姆发生了什么？}
{191}{}{去死，渣滓！}
{192}{}{那些失败者现在已经没了。}
{193}{}{那是好事。好吧，再见。}
{194}{}{而现在，你也不会存在了。}
{195}{}{我知道你是谁了。是时候报仇了！}
{196}{}{又是你。我以为你现在应该学会了。太少，太晚了，我猜。}
