{100}{}{你看到大教堂之子的见习者罗纳德。}
{101}{}{你看到大教堂之子的见习者卡罗琳。}
{102}{}{你看到大教堂之子的见习者迈尔斯。}
{103}{}{你看到大教堂之子的见习者艾莉莎。}
{104}{}{你看到大教堂之子的见习者托马斯。}
{105}{}{你看到大教堂之子的见习者加布里埃尔。}
{106}{}{你看到大教堂之子的见习者夏琳。}
{107}{}{你看到大教堂之子的见习者埃克达尔。}
{108}{}{你看到大教堂之子的见习者霍珀。}
{109}{}{你看到大教堂之子的见习者拉德克。}
{110}{}{那些失败者追随者真是轻松就被解决了。}
{111}{}{现在追随者已经不在了，重建工作可以开始了。}
{112}{}{希望这次搜寻结束时，我能成为一名抄写员或学者。}
{113}{}{总有一天我会成为学者，四处宣扬统一。}
{114}{}{奥菲欧是个难以共事的人。}
{115}{}{我仍然被夜行者吓到。}
{116}{}{长老们说夜行者是我们的盟友。}
