{100}{}{你看到一个虔诚的大教堂之子成员。}
{101}{}{我们提供身体的治疗来治愈灵魂。我能帮你吗？}
{102}{}{是的，帮帮我。}
{103}{}{你们是什么人？}
{104}{}{嗯。}
{105}{}{没关系，我的孩子。我们现在就来检查你。}
{106}{}{心灵纯洁者有福了。你没有问题，我的孩子。去玩吧。}
{107}{}{你已经被治愈。以后要小心点。}
{108}{}{你受伤了。}
{109}{}{你没有受伤。那很好。}
{110}{}{我看到你中毒了。}
{111}{}{嗯，有些辐射中毒。不幸的是，我们无法治愈。}
{113}{}{我们需要捐赠 $}
{114}{}{才能治愈你。可以接受吗？}
{115}{}{可以。}
{116}{}{不可以。}
{117}{}{但我没有那么多钱！}
{118}{}{你能接受 $}
{119}{}{吗？}
{120}{}{大教堂之子不讨价还价。现在，你接受我们的价格吗？}
{121}{}{是的，我当然接受}
{122}{}{不，谢谢。}
{123}{}{谢谢你，我的孩子。让我们为你的康复祈祷。}
{124}{}{谢谢你，我的女儿。让我们为你的康复祈祷。}
{125}{}{好了。愿大教堂之子的和平与祝福与你同在。}
{126}{}{你没有足够的钱。如果你捐出所有能捐的，我们会治愈你。可以接受吗？}
{127}{}{可以。}
{128}{}{不可以。}
{129}{}{如果你捐出所有能捐的，我们会治愈你。可以接受吗？}
{130}{}{可以。}
{131}{}{不可以。}
{132}{}{你有足够的钱捐赠。你需要学习数学，我的孩子。}
{133}{}{我们是大教堂之子。我们在废土中生活和工作。如果你有机会到骨园，欢迎来大教堂看看。}
{134}{}{谢谢。}
{135}{}{你们是做什么的？}
{136}{}{我们是和平的治疗者和教师。我们治愈身体以治愈灵魂。我们只需要小额捐赠来购买治疗用品。}
{137}{}{听起来不错。}
{138}{}{听起来像是一派胡言，如果你问我的话。}
{139}{}{我们没有问你。我能看出你对我们的信仰感到厌倦。如果你需要其他帮助，我们会在这里。}
{140}{}{这是最神圣的理念。我们正在努力实现废土的终极和平。所有生物将和谐共处。}
{141}{}{谢谢。祝你有美好的一天。}
{142}{}{我们没有时间交谈。我们要离开了。这个地方对我们很危险。}
{143}{}{你为什么要这样做？我们不会伤害你！}


{1000}{}{大教堂}
{1001}{}{变种人}
{1002}{}{主宰}
{1003}{}{骨园}
{1004}{}{追随者}
{1005}{}{芯片}
{1006}{}{启示录}
{1007}{}{死城}
{1008}{}{塞特}
{1009}{}{水坝}
{1010}{}{大厅}

{1100}{}{那就是我们。}
{1101}{}{他们是受到核辐射影响而变异的人。但他们仍然是好人。}
{1102}{}{我们都有主宰，不是吗？}
{1103}{}{骨园是仇恨的温床。那里有启示录的追随者，还有帮派：撕裂者、刀锋帮和枪械商，还有一个小聚落叫做阿迪特姆。}
{1104}{}{他们是试图破坏主宰所设立的和平的人。}
{1105}{}{我不知道你在说什么。}
{1106}{}{他们是试图破坏主宰所设立的和平的人。}
{1107}{}{这里是古老世界的悲惨遗迹。}
{1108}{}{我相信他是一个食尸鬼。}
{1109}{}{就在东北方向。}
{1110}{}{我对此一无所知。}
