{100}{}{这看起来像是场域控制计算机。}
{101}{}{它似乎有一个用于场域信号的发射器，一个用于远程命令的接收器，以及一个标准的无线电数据通信端口。}
{102}{}{当你启动场域控制计算机时，你能听到整个设施中传来低沉的嗡嗡声。}
{103}{}{你没有正确使用计算机。}
{104}{}{你无法关闭场域控制计算机。所有的控制都被锁定并加密。}
{105}{}{你不理解这个计算机的操作系统。}
{106}{}{力场子系统的防护远不够抵御你的才能。你关闭了这一层的所有力场。}
{107}{}{力场子系统防护严密，但你设法关闭了一半。这是你能做到的极限。}
{108}{}{力场子系统防护严密，抵御电子入侵。你花了一些时间研究，但尚未破解。}
{109}{}{你在21点游戏中大获全胜，并通过结局画面潜入主系统。}
{110}{}{你玩了一局21点，但水平不够，未能破解。}
{111}{}{唯一未受保护的文件夹是娱乐游戏文件夹，可能可以用作后门。}
{112}{}{唯一未受保护的文件夹是娱乐游戏文件夹。}
{113}{}{你厌恶地看着计算机。}
{114}{}{你认为所有文件夹都受保护，但尚未完成搜索。}
{115}{}{你已侵入主系统，现在需要重新编程力场控制。}
{116}{}{由于你独特的黑客手法，你获得了800点经验值。黑杰克！}
{117}{}{你将无线电连接到了力场控制计算机。}
{118}{}{你尝试将无线电接入计算机的尝试失败了。}
