{100}{}{你看到一个饱经风霜的农夫。}
{101}{}{你好。}
{102}{}{你好。}
{103}{}{哈比普。}
{104}{}{又见面了。}
{105}{}{有什么我可以帮你的吗？}
{106}{}{你叫什么名字？}
{107}{}{能告诉我一些关于你们村子的事吗？}
{108}{}{你在做什么？}
{109}{}{没事，谢谢。}
{110}{}{我叫柯蒂斯。}
{111}{}{我们村子很小，但能自给自足。除了袭击我们的掠夺者和偶尔出现的辐射蝎子，我们没有什么问题。阿拉迪什是个好领导。}
{112}{}{我是个农夫。多年前我们在沙漠中开垦了灌溉系统。虽然荒地环境严酷，但只要有耐心和时间，还是能种出东西的。}
{113}{}{我明白了。你们似乎做得不错。}
{114}{}{你们现在所有的田地都种上作物了吗？轮作可能会更好。}
{115}{}{轮作？那是什么？}
{116}{}{没事，算了。}
{117}{}{你只种植部分田地，让其他田地恢复植物消耗的养分。通过翻耕自然生长的植物，让这些田地重新变得肥沃。}
{118}{}{嗯，没想到这个。不过听起来有道理。好主意。}
{119}{}{我可以再问你一个问题吗？}
{200}{}{你获得了500点经验，因为你帮助改善了阴影沙地的农业。}
