{100}{}{发电机被破坏了，无法再运作。}
{101}{}{你看到一个发电机。它是废料场唯一的电力来源。}
{102}{}{你剪断了变压器上的一些电线。发电机无法再运作。}
{103}{}{剪线钳已经没有用了。}
{104}{}{这个物品对发电机没有用。}
{105}{}{你没有注意到发电机有什么特别之处。}
{106}{}{发电机本身看起来相当防篡改；不过你注意到变压器和发电机之间有一组电线。}
{107}{}{你看不出这个大型发电机有什么特别之处。}
{108}{}{你无法进一步了解发电机。}
{109}{}{电线可以修复，但可能需要一段时间，而且成功没有保证。}
{110}{}{你无法看出损坏的发电机有什么特别之处。}
{111}{}{你无法进行进一步的修理。}
{112}{}{没有必要修理发电机。它运作得很好。}
{113}{}{你无法修理这个正常运作的发电机。}
{114}{}{经过几个小时，你修好了发电机。电力恢复后，帮派也离开了，镇上的人们很感激。他们给了你一些有价值的信息。你在废料场的任务完成了，寻找水芯片的任务仍在等待。}
{115}{}{你无法修好发电机。废料场的人们将过上更贫困的生活；但至少帮派离开了，他们还能活下去。你在废料场的任务完成了，寻找水芯片的任务仍在等待。}
{116}{}{进一步篡改发电机没有任何效果。}
{117}{}{这个技能对发电机没有影响。}
{118}{}{发电机已经在运作。}
{119}{}{你无法启动发电机，因为它坏了。}
