{100}{}{你看到副警长弗莱。}
{101}{}{你好，朋友。我是副警长托尼·弗莱，为您服务。}
{102}{}{这里是什么地方？}
{103}{}{让开，否则你就得躺在六尺之下了。}
{104}{}{我没干。}
{105}{}{很高兴见到你。再见。}
{106}{}{呜。}
{107}{}{啊！}
{108}{}{哦，新来的人！欢迎来到集市！我还以为你是和商队一起来的呢。你是跟他们一起来的吗？}
{109}{}{是的。}
{110}{}{不是。}
{111}{}{我不意外。我们城市的大多数新成员都是和商队一起来的，即使我们有一些商队失踪的情况。这里是个不错的城市，但要小心你交往的人。像德克和他的恶棍会给你带来很多麻烦。}
{112}{}{德克是谁？}
{113}{}{商队失踪？}
{114}{}{好的，谢谢。}
{115}{}{这倒是意外。外面情况很糟，尤其是商队失踪的情况下。但你现在安全了，只要远离马耳他之鹰就行。德克和他的人都是麻烦制造者。}
{116}{}{德克是谁？}
{117}{}{商队失踪？}
{118}{}{嗯，我可是很厉害的。}
{119}{}{看来是这样。那么你还有其他问题吗？}
{120}{}{德克是谁？}
{121}{}{关于商队失踪的事是怎么回事？}
{122}{}{就这样，谢谢。}
