{100}{}{你解锁了这扇门。}
{101}{}{你的开锁器坏了！}
{102}{}{你无法打开这个锁。}
{103}{}{你没能打开锁。}
{104}{}{门是锁着的。}
{105}{}{门是开着的。}
{106}{}{门关着但未上锁。}
{107}{}{门是锁着的。}
{108}{}{门发出刺耳的吱嘎声。}
{109}{}{门已经解锁了。}
{110}{}{这个锁超出了你的开锁能力。}
{200}{}{这扇门上没有锁可供撬开。}
{201}{}{你注意到墙上有些不规则之处。}
