{100}{}{你看到骑士法利。}
{101}{}{你好。}
{102}{}{查德拉 处 卡？}
{103}{}{卡佳 处 尼 卡 查克拉 法利。}
{104}{}{法利，nee ko}
{105}{}{ mat'chak o 德雷克。}
{106}{}{啊，德雷克 ko mat'chak。}
{107}{}{如果你再见到我们共同的朋友，请代我问好。}
{108}{}{兄弟会让我想起了家。}
