{100}{}{你看到一名远行商人公司的守卫。}
{101}{}{那些该死的水商正在敲诈我们所有人。}
{102}{}{记得按时支付FLC，他们可是不好惹的。}
{103}{}{你应该去找鲁特格谈谈。}
{104}{}{远行商人公司是最棒的。}
{105}{}{红色商队都是一群白痴和疯子。}
{106}{}{嗯，我突然想吃烤蜥蜴了。}
{107}{}{到底是谁在偷我们的商队？}
{108}{}{我弟弟就在上次失踪的商队里。}
{109}{}{那些水鬼肯定有责任，我知道。}
{110}{}{我听说是变种人劫了商队。真是可怕。}
{111}{}{听说你遇到了变种人。希望你让他们付出代价。}
{112}{}{我以为是死亡爪干的，真该死的变种人。}
{113}{}{我们关门了。明早再来吧。}
{114}{}{嘿，这不是猎鹰酒吧。滚出去。}
{115}{}{你是什么？某种废土流氓？滚出去。}
{116}{}{快滚！}
{117}{}{我们只在白天营业。}
{118}{}{你嗑药了吗？走开。}
{119}{}{你得明早再来。}
