{100}{}{你看到火。}
{101}{}{}
{102}{}{}
{103}{}{你看到一个刀锋帮成员。}
{104}{}{你看到一个刀锋帮成员。}
{105}{}{你觉得那可能是书本。}
{106}{}{你觉得那可能是伤疤。}
{107}{}{你觉得那可能是枪手。}
{108}{}{你觉得那可能是抽搐。}
{109}{}{你觉得那可能是锤子。}
{110}{}{你觉得那可能是剃刀。}
{111}{}{你想要什么，废物？}
{112}{}{呃。}
{113}{}{我想成为刀锋帮的一员。}
{114}{}{我怎样才能让你们和阿迪特姆和平共处？}
{115}{}{这个！*啪*}
{116}{}{没事，打扰了。}
{117}{}{我只是来看看你们的地方。}
{118}{}{太好了，又一个蠢货。你听起来像个撕裂者。}
{119}{}{嗷嗷。}
{120}{}{嗷呜。}
{121}{}{嗷呜？}
{122}{}{你也不太喜欢他们？也许我们可以让你做点“小工作”。}
{123}{}{呜呜。}
{124}{}{呃呃。}
{125}{}{好吧，去找头儿谈谈。剃刀会告诉你该怎么做。}
{126}{}{又蠢又胆小。我现在就让你解脱。}
{127}{}{所以你是个撕裂者！我本该为此感到遗憾，但我早就知道他们很蠢。晚安！}
{128}{}{撕裂者。那些住在镇另一边的近亲繁殖者。算了吧，你太蠢了，什么都不懂。}
{129}{}{你想成为刀锋帮的一员？祝你好运。不过，如果你能找到剃刀，和她谈谈。也许她会让你加入。}
{130}{}{好的，谢谢。}
{131}{}{那我不想加入了！}
{132}{}{你说的“加入”是什么意思？}
{133}{}{你不能直接让我成为刀锋帮成员吗？}
{134}{}{你妈从来不想要你，我们也不想。}
{135}{}{很简单。你得杀个人才能加入。她会告诉你需要杀谁。}
{136}{}{好的，谢谢。}
{137}{}{算了吧。我不想加入你们这个愚蠢的帮派。}
{138}{}{不行。我不负责。我只是让剃刀走正道。}
{139}{}{很简单。屠杀我们的敌人，然后我们会给阿迪特姆一个机会。}
{140}{}{你们的敌人是谁？}
{141}{}{好吧。你能给我证明吗？}
{142}{}{打架是不对的！我不会这么做！}
{143}{}{撕裂者。那些枪械商只是个麻烦，但不重要。他们不过是一群软蛋。}
{144}{}{好吧，我去杀撕裂者。}
{145}{}{算了。}
{146}{}{如果你打算这么做，最好让剃刀知道。否则，她会在你离开之前要了你的命。}
{147}{}{随便你。再见。}
{148}{}{我不做交易。我只是提建议。如果你想交易，去找剃刀。}
{149}{}{那现在杀了你可以让你免受多年的痛苦。}
{150}{}{那就看看这个吧！}
{151}{}{想活命就滚开。}
{152}{}{安静。我们在偷偷接近撕裂者。}
{153}{}{如果你有头，就拿去给剃刀。她还想踢足球。否则，就滚出去！}
{154}{}{嘿，兄弟！}
