{100}{}{你看到一个瘦弱而邋遢的男孩。}
{101}{}{我觉得我不应该和你说话。走开。}
{102}{}{你为什么拿着武器？我们什么都没有，连鱼都没有！}
{103}{}{嗨。你想要什么？}
{104}{}{钓鱼怎么样？}
{105}{}{我物资有点不足……}
{106}{}{最近看到什么异常情况了吗？}
{107}{}{想听我在辐射蝎洞穴的冒险故事吗？}
{108}{}{隆克！}
{109}{}{嗨。你不就是那个到处帮助别人的人吗？你一定有很多有趣的故事可以讲！}
{110}{}{你从哪里来？}
{111}{}{嗨。我看你还不至于蠢到在这里钓鱼。怎么了？}
{112}{}{不太确定。我和爸爸在荒地上流浪了很久。我们有个朋友，一个蝎子猎人，但他疯了，我们不得不杀了他，然后我们……}
{113}{}{嗯，也许我不该谈这个。}
{114}{}{告诉我关于你爸爸的事。}
{115}{}{蝎子怎么样？}
{116}{}{很糟糕。抱歉，我不该用“糟糕”这个词。爸爸认为那些总是说糟糕的人要么是脑残的傻子，要么是表达不清的失败者。爸爸总是想显得聪明。}
{117}{}{我同意你爸爸的看法。}
{118}{}{抱歉。我不是负责物资的人。}
{119}{}{我看到一个像巨型蜘蛛的东西，有两个头，其中一个看起来像人。爸爸认为我吸收了太多辐射。我不知道。被污染的水对大脑有奇怪的影响。}
{120}{}{是啊，比如什么？}
{121}{}{什么是Runk？}
{122}{}{当然！}
{123}{}{猎杀辐射蝎最糟糕的事情就是等它们进入一个好的伏击点。}
{124}{}{猎杀辐射蝎最糟糕的事情就是它们逃跑后追赶它们！}
{125}{}{猎杀辐射蝎最糟糕的事情就是被它们的毒刺刺到脸。}
{126}{}{是啊，你听说过那些掉进辐射蝎巢穴的掠夺者吗？他们全都被蜇了又蜇，活活被吃掉，除了那个逃跑的，他的半张脸被咬掉了！}
{127}{}{天啊，那真是个好故事！}
{128}{}{他有点吵又无聊，我不确定他是不是我亲生爸爸。我觉得他一定是我小时候把我偷来的。但他大多数时候都喂我，所以我想我还是喜欢他的。}
{129}{}{它们又大又凶，已经失控了。爸爸说以前有英雄在荒地上游荡，消灭它们，但现在大多数都死了，我想。}
{130}{}{什么样的英雄？}
{131}{}{是啊，大人们总是互相同意，真是傻透了。}
{132}{}{大亨利以前和我们一起，他比爸爸和我都厉害，直到他精神错乱想掐死我。爸爸不得不开枪打他！}
{133}{}{你爸爸枪法好吗？}
{134}{}{谁是大亨利？}
{135}{}{听起来不错！不过我还是得赶快回去钓鱼，不然我们饿得要吃了你！}
{136}{}{很多英雄。创立钢铁兄弟会的那个家伙，罗杰·马克西姆，他真是个好蝎子杀手。我长大以后一定要找到他们，然后加入他们！}
{137}{}{听起来不错。}
{138}{}{加入兄弟会真的很难，而且路途危险。}
{139}{}{他还算行吧。我倒是看到他射中了七十码外辐射蝎子的眼睛，不过那是走运罢了。}
{140}{}{他是个南方的人。某种试着靠土地生存而不是靠人的掠夺者。他真是个伟大的家伙，但有时候会发疯，有一次他...呃...算了。}
{141}{}{是啊，我要像他一样成为英雄。堵上我的名！}
{142}{}{你以为这样生活容易吗？我不怕艰难，这里没有安全的地方，所以我不会退缩。我只需要长到可以自己闯荡的年纪。}
{143}{}{蝎子和人的战斗怎么样？}
{144}{}{大约十二次吧…}
{145}{}{呃，是的，先生。}
{146}{}{我想这次我会感冒…}
{147}{}{快点！我都快饿死了！}
{148}{}{好久没抓到东西了，我都忘了是什么味道了。}
{149}{}{爸爸，你听到什么声音了吗…}
