{100}{}{你看到副警长弗莱。}
{101}{}{我正盼着碰到你，杀童者。希望你在这里逗留不会太久，我会密切关注你的行动。在我的城市里保持干净，我可是急需一个理由来清除你这样的垃圾。}
{102}{}{你好朋友，我是副警长托尼·弗莱，为您服务。}
{103}{}{这是哪里？}
{104}{}{很高兴见到你。再见。}
{105}{}{呜。}
{106}{}{呃！}
{107}{}{哦，新来的？欢迎来到枢纽！你已经到了海岸线上最大的城市。嘿，也许是我们所知的世界上最大的城市。我还以为你是跟商队来的，你是和他们一起来的吗？}
{108}{}{是的。}
{109}{}{不是。}
{110}{}{我一点也不惊讶。我们城市的大多数新成员都是随着商队来的，尽管最近有商队失踪的情况。这里是个不错的城市，但要注意你结交的人。像德克这样的家伙和他的打手会给你带来很多麻烦。}
{111}{}{那可真是出乎意料。外面的情况很艰难，尤其是商队失踪的情况下。不过你现在安全了，只要远离马耳他之鹰。那是一群麻烦制造者，德克和他的一伙人。}
{112}{}{德克是谁？}
{113}{}{是啊，但我很有一套。}
{114}{}{关于失踪商队是怎么回事？}
{115}{}{在哪里可以赚点钱？}
{116}{}{就是这样，谢谢。}
{117}{}{如果你这么认为。那么，你还有其他问题吗？}
{118}{}{真的是一场灾难。有些商队失踪了。法尔戈商人行的布奇正在为提供信息或其他东西提供奖励。如果你感兴趣，应该去商人市场看看。}
{119}{}{他在商人市场里拥有马耳他之鹰，但如果你想避免麻烦，最好别和他来往。他就是个杀人的畜生，但警长不让我在没有证据的情况下逮捕他。}
{120}{}{没问题。信不信由你，我们的城市相当安全，我们的警方都是训练有素的维和人员。你应该不会有任何问题，只要避开马耳他之鹰就行。}
{121}{}{抱歉，我不明白。也许你需要治愈？教堂的信徒们在南边。从商人市场直走到水商那里，他们就在水商的旁边。}
{122}{}{我还在盯着你，杀童者。}
{123}{}{杀人的畜生！}
{124}{}{我简直无法相信警长死了……}
{125}{}{你在这儿呢，你这个偷东西的家伙！我差点认不出你。卫兵！}
{126}{}{当然。}
{127}{}{有本事就来抓我。}
{128}{}{不。}
{129}{}{啊！}
{130}{}{再次见面。希望你喜欢我们的城镇。像你这样年轻有为的小伙子，总是受欢迎的。如果你决定留下来，我相信你会成为商镇的宝贵成员。}
{131}{}{再次见面。希望你喜欢我们的城镇。像你这样迷人的女士，总是受欢迎的。如果你决定留下来，我相信你会成为商镇的宝贵成员。}
{132}{}{再次见面。我能为你做些什么？}
{133}{}{有什么事吗？我可没一整天的时间。我得看着前门。}
{134}{}{我要报案！}
{135}{}{你们有医院吗？我受伤了。}
{136}{}{商店在哪里？}
{137}{}{这附近哪里有工作？}
{138}{}{再见。}
{139}{}{加罗？}
{140}{}{乌嘎。}
{141}{}{真的吗？呃，你应该去找警长。我现在不能离开岗位。我得……呃，防备可能来的袭击者。而且，我不太擅长写报告。}
{142}{}{哦，抱歉，我没注意到。儿童会在水商旁边经营医院。往南走过商人市场，你会在水商的西北方向看到。希望一切顺利。}
{143}{}{那很容易找到。那是镇上最繁忙的地方。商人市场在这里南边几英里处。你会对北部区域最感兴趣，那是我们大多数本地人买卖的地方。}
{144}{}{那就在商人市场，南边几英里处。两家商队公司在那里，第三家在更南边。我推荐远行商队。他们支付不错，而且不太疯狂。}
{145}{}{死了，他们全都死了……}
{146}{}{噗……呼噜……}
{147}{}{你知道哪里能找到水芯片吗？我们避难所的芯片坏了，我们急需一个新的。}
{148}{}{水芯片？嗯，我从没听说过。不过如果和水有关，你应该去找水商。他们的总部在更南边，经过市中心区域。}
