{100}{}{你看到一个看起来不太正派的墨西哥男人，头发油亮。}
{101}{}{你看到赫尔南德斯，一个狡猾的赌徒。}
{102}{}{嘿，小子，让我自我介绍一下。我是赫尔南德斯，一个非常有品味的人！你看起来是新来的。请允许我为你介绍这家赌场。}
{103}{}{你能告诉我关于赌场的事情吗？}
{104}{}{不用了，谢谢。}
{105}{}{啥？}
{106}{}{当然可以！这家精美的场所是由著名的吉兹莫经营的。他是个真正的梦想家，也是个非常富有的人。}
{107}{}{谢谢。}
{108}{}{你说吉兹莫是个梦想家。他的梦想是什么？}
{109}{}{这里的游戏赔率怎么样？}
{110}{}{我的朋友，我不想打扰你，但也许你可以帮我个忙。我已经开发出一个万无一失的系统，因为我发现了吉兹莫是如何操作他的赌桌的，但我没有筹码去下注。}
{111}{}{ [你感觉他在试图骗你。]}
{112}{}{也许你能借我一些筹码？我保证会成功。}
{113}{}{当然，听起来不错。}
{114}{}{不用了，谢谢。}
{115}{}{我觉得你在撒谎。你在试图骗我。}
{116}{}{抱歉，我的朋友。嘿，让我给你展示一个有趣的游戏……}
{117}{}{非常感谢，我的朋友！几天后我就能连本带利地还你。我的系统比较慢，你知道的，需要很多耐心，但肯定会带来巨大的收益！}
{118}{}{好吧，但我保证会成功！如果你想参与这些等待的财富，快点回来，否则我会找另一个合伙人！}
{119}{}{我的朋友，我看你也是个有品味的人。也许来一局简单的骰子游戏？}
{120}{}{好吧！}
{121}{}{不用了，谢谢，我想试试别的。}
{122}{}{吉兹莫曾梦想建立一个人们可以聚会和享受的地方。他有实现这个梦想的雄心。结果就是你现在看到的这家赌场。}
{123}{}{他给了人们在外面破碎的世界中放松的机会。而且他还为垃圾镇带来了财富！}
{124}{}{听起来是个好主意。}
{125}{}{生活已经够艰难了。我不信任那些鼓励人们输钱的人的动机。}
{126}{}{显然你没有吉兹莫的远见。这个地方是日常生活艰辛中的一个喘息之地。}
{127}{}{嗯，吉兹莫经营得不错，虽然游戏的赔率，怎么说呢，偏向于赌场。不过他的荷官并不作弊。但除非你有像我这样的系统，否则你需要非常聪明。}
{128}{}{谢谢。}
{129}{}{}
{130}{}{你的系统进展如何？}
{131}{}{没什么，谢谢。}
{132}{}{我的系统正在慢慢发展。我有生活开销之类的，你知道的，但它在起作用！}
{133}{}{那太好了！}
{134}{}{我觉得你是个骗子和作弊者。我的钱呢？}
{135}{}{哦，你以为你看穿我了，是吗？哼，你什么也得不到！}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{136}{}{布宜诺斯迪亚斯，我的朋友！今天我能为你做些什么？}
{137}{}{布宜诺斯迪亚斯，我的朋友！今天我能为你做些什么？}
