{100}{}{你看到一个枢纽镇的警察。}
{101}{}{真希望我能被派到离家近些的地方。}
{102}{}{不知道那些商队出了什么事。}
{103}{}{快走吧。}
{104}{}{你最好把武器收起来，陌生人。}
{105}{}{别惹麻烦。}
{106}{}{你有什么要申报的货物吗？}
{107}{}{别在我面前挥舞你的武器。}
{108}{}{把那东西收好，不然你就得待牢里了。}
{109}{}{你是把枪对着我吗？}
{110}{}{我听说过你。小心点。}
{111}{}{我们会盯着你的。}
{112}{}{在我们的城里不准打架，硬汉。}
{113}{}{我们不喜欢杀害孩子的人！}
{114}{}{只要你敢碰孩子，我们就会追捕你。}
{115}{}{我讨厌你这样的人。}
{116}{}{遇到麻烦时别求助。}
{117}{}{嘿，谢谢你替我们干了活。}
{118}{}{在这里不许杀人，即使是正当防卫。}
{119}{}{如果是你杀了死亡爪……谢谢你。}
{120}{}{在我们的城市里别惹麻烦。}
{121}{}{如果我是你，我会离德卡远点。}
{122}{}{祝您在此过得愉快。}
{123}{}{欢迎来到枢纽镇！}
{124}{}{你好，陌生人。}
{125}{}{去马耳他之鹰酒馆喝点清爽的饮品吧。}
{126}{}{想找市场就沿着主路走。}
{127}{}{继续走。}
{128}{}{快走，快走。}
{129}{}{我们是来预防和监察的。}
{130}{}{在我们城市里，控制好你的武器。}
{131}{}{别用那个惹事生非。}
{132}{}{我建议你把武器收起来。}
{133}{}{你最好把那个收起来……我是说你的武器。}
{134}{}{欢迎，骑士，好久不见。}
{135}{}{你就是那个爱惹事的家伙。别再打架了，好吗？}
{136}{}{你最好别再挑起争端！}
{137}{}{是你……控制好你的脾气。}
{138}{}{远行商队被消灭了。我简直不敢相信。}
{139}{}{水商会没了。真是松了一口气。}
{140}{}{红色商队被摧毁了。}
{141}{}{你听说了吗？地下组织终于被剿灭了！}
{142}{}{德克死了！}
{143}{}{德克的问题终于解决了。}
{144}{}{小心点——这里不安全。}
{145}{}{注意你的言行，伙计。}
{146}{}{注意你的言行，女士。}
{147}{}{老哈罗德擅长讲故事。}
{148}{}{你不该在这里，这里不安全。}
{149}{}{老城区真是破败不堪。}
{150}{}{这地方真臭。}
{151}{}{我们应该把这片区域全部拆掉。}
{152}{}{我知道该死的小偷圈子就在这附近。}
{153}{}{可怜的哈罗德——他过得很艰难。}
{154}{}{别惹麻烦。}
{155}{}{嘿。我认识你。别再打架了，好吗？}
{156}{}{你最好别想着再惹事！}
{157}{}{如果我们再抓到你打架，你就要进去了！}
{158}{}{你听说了吗？远行商队被消灭了。}
{159}{}{水商会成为历史了。这是个福音。}
{160}{}{有人干掉了赤焰商队。}
{161}{}{你听说了吗？地下组织终于被消灭了！}
{162}{}{德克死了！}
{163}{}{如果德克不在，这个镇子会更安全。}
