{100}{}{停下！}
{101}{}{去死吧，人类！}
{102}{}{决一死战。}
{103}{}{你会为你的罪行付出代价！}
{104}{}{你不应该在这个区域携带武器，小兄弟。解释一下。}
{105}{}{你不应该在这个区域携带武器，小妹妹。解释一下。}
{106}{}{哼。}
{107}{}{没事，我在这里工作。}
{108}{}{没事，我有通行证。}
{109}{}{我携带武器是中尉批准的。}
{110}{}{这是什么叛逆行为？！}
{111}{}{那就给我看看你的通行证。}
{112}{}{呃，我把它留在另一件长袍里了。}
{113}{}{就在这里，钉在我的枪前面。}
{114}{}{那就快去完成你的任务，但注意，我在盯着你。}
{115}{}{是的，小兄弟。你需要我做什么？}
{116}{}{是的，小妹妹。你需要我做什么？}
{117}{}{哼！}
{118}{}{嗯，这个主人在哪儿？}
{119}{}{赞美统一，兄弟。}
{120}{}{抱歉，你得自己找到通往统一的路。}
{121}{}{你显然是个异教徒！为你的罪行付出代价！}
{122}{}{他在三层，他必须在那里。你为什么问这么愚蠢的问题？}
{123}{}{哦，呃，没什么。}
{124}{}{我要把他的屁股踢到，呃，很远的地方去！}
{125}{}{什么问题？我说的是‘向主人致敬，再见’。}
{126}{}{你侮辱我！去死吧！}
{127}{}{赞美统一。}
{128}{}{你听起来不像是相信你所说的话。是真的吗？还是你偏离了正道？}
{129}{}{你误以为我声音的颤抖是因为恐惧，其实是因为某种感冒。}
{130}{}{我认为你们的种族注定要灭亡。来，让我和我的朋友们来证明这一点……}
{131}{}{当你成为我们的一员时，你将不再畏惧这些小事。滚开。}
{132}{}{这次你想要什么？我没时间跟你闲聊。}
{133}{}{拉博！}
{134}{}{我没时间浪费在你身上……去死吧！}
{135}{}{没什么，对不起。}
{136}{}{赞美统一，兄弟。}
{137}{}{你是谁？让我看看……啊！一个入侵者……}
{138}{}{继续前进。为统一尽一份力，别来烦我！}
{139}{}{快走。}
{140}{}{继续前进。为统一尽一份力。}
