{100}{}{停下！}
{101}{}{去死吧，人类！}
{102}{}{决一死战。}
{103}{}{你将为你的罪孽付出代价！}
{104}{}{我要碾碎你！}
{105}{}{团结万岁！}
{106}{}{为了主宰！}
{107}{}{小兄弟，这个区域不允许携带武器。解释一下。}
{108}{}{小妹妹，这个区域不允许携带武器。解释一下。}
{109}{}{哼。}
{110}{}{没事，我在这里工作。}
{111}{}{没事，我有通行证。}
{112}{}{我持有中尉的许可武装。}
{113}{}{这是什么叛逆行为？！}
{114}{}{那就给我看看你的通行证。}
{115}{}{呃，我把它落在另一件长袍里了。}
{116}{}{就在这儿，钉在我枪的前面。}
{117}{}{那就快去完成你的任务，但要小心——我在盯着你。}
{118}{}{是的，小兄弟。你需要我做什么？}
{119}{}{是的，小妹妹。你需要我做什么？}
{120}{}{哼！}
{121}{}{嗯，这个主宰在哪儿？}
{122}{}{赞美团结，兄弟。}
{123}{}{我不是引导你走向团结之路的人。离开！}
{124}{}{你显然是个异教徒！为你的罪孽付出代价！}
{125}{}{他就在这儿。你为什么问？}
{126}{}{哦，呃，没什么。}
{127}{}{我要把他的屁股踢到，呃，很远的地方！}
{128}{}{什么问题？我说的是‘向主宰致敬，再见。’}
{129}{}{你侮辱了我！去死吧！}
{130}{}{赞美统一。}
{131}{}{听起来你并不相信自己所说的话。这是真的吗？还是你已经偏离了正道？}
{132}{}{你误把我声音的颤抖当作恐惧，其实只是因为感冒。}
{133}{}{我认为你们的种族注定要灭亡。来，让我和我的朋友们来证明这一点……}
{134}{}{当你成为我们的一员时，你将不再惧怕这些小事。走吧。}
{135}{}{这次你想要什么？我没时间和你闲聊。}
{136}{}{拉博！}
{137}{}{我没时间浪费在你身上……去死吧！}
{138}{}{没什么，抱歉。}
{139}{}{赞美统一，兄弟。}
{140}{}{你显然是个入侵者！}
{141}{}{别挡我的路。}
{142}{}{我没空理你。别再烦我。}
{200}{}{你看到一个超级变种人中士。}
{201}{}{嘿，这看起来像是一颗核弹。它为什么在这里？}
{202}{}{这是我们主人的最后手段武器。如果我们遇到无法在战斗中击败的敌人，我们就用这个摧毁他们。但我怀疑这会发生。即使是我们的主人也不想再次释放原子的可怕力量！}
{203}{}{好的，谢谢。}
{204}{}{它能用吗？}
{205}{}{不客气。现在安静点，我需要专心守护这个装置。}
{206}{}{哦，是的，它是可以用的。我们保持它在完美的工作状态，随时可以引爆。统一不会被击败！}
{207}{}{啊，谢谢。}
{208}{}{你不担心有人会偷些长袍混进来引爆它吗？}
{209}{}{不。我们在这里守护它不受入侵者干扰。没有人能在我们不注意的情况下接触到这个装置。而且，引爆装置所需的核武器启动钥匙不在这里。}
{210}{}{哦，这样说得通。谢谢。}
{211}{}{为了我的安全感，你能告诉我钥匙在哪里吗？}
{212}{}{哦，当然，没问题。中尉保管着钥匙。他在军事基地，所以他根本不在这里。这确保了核弹不会在我们敬爱的主人身边被引爆。}
{213}{}{感谢你的时间。}
{214}{}{[这个大个子变种人盯着你看了一会儿，浓密的眉毛扬起] 我觉得你问的问题太多了。}
