{100}{}{指挥部，这里是警卫室。一切正常。完毕。}
{101}{}{去死吧！}
{102}{}{入侵者！}
{103}{}{人类！}
{104}{}{站住。这是禁区。你不该在这里。}
{105}{}{你最好投降。}
{106}{}{你停下。我带你去见中尉。乖乖合作，否则死路一条。}
{107}{}{鲁吉！}
{108}{}{去死吧，地狱的孽种！}
{109}{}{我来找你的主人谈话。}
{110}{}{我是你主人的特派变种人。让我通过，否则后果自负。}
{111}{}{我来自大教堂。让我过去。}
{112}{}{死吧！}
{113}{}{随你的便。}
{114}{}{好吧，那就决一死战。}
{115}{}{很好。跟我来，别搞笑。}
{116}{}{好吧，走吧。}
{117}{}{搞笑？等我把你打包起来，你就好笑了！}
{118}{}{我不相信你。}
{119}{}{我不这么认为。}
{120}{}{不。你是人类。你得死。}
{121}{}{如果你撒谎，我就杀了你。}
{122}{}{哦，好吧。继续前进。}
{123}{}{呃，好吧。我想。也许你最好见见中尉。}
{124}{}{你杀了我的兄弟。我会复仇的！}
{125}{}{去死吧！}
{126}{}{凶手！}
{127}{}{屠杀者！}
