{100}{}{你看到一个食尸鬼守卫。}
{101}{}{走开！这里不欢迎你。}
{102}{}{好吧。很高兴见到你。}
{103}{}{什么？}
{104}{}{我在值班。如果你想见塞特，得进去才能见到。}
{105}{}{门锁住了。你得等到天黑再来。}
{106}{}{谢谢。}
{107}{}{什么？}
{108}{}{我让你离开。这里不欢迎你这种人。}
{109}{}{好的。}
{110}{}{嗯！}
{111}{}{门到天黑才会开。}
{112}{}{我需要进去。有什么办法能帮我吗？}
{113}{}{嗯，好吧。}
{114}{}{唉！}
{115}{}{好吧，我想试试也无妨。}
{116}{}{我希望能帮到你，但如果我这样做，塞特会惩罚我的。你知道的，得听大人物的话……}
{117}{}{是，我明白。谢谢。}
