{100}{}{这是一台老虎机，侧面有一个核爆炸的图案。玩一次需要$20。}
{101}{}{你投入20美元到老虎机中，然后拉下油腻的拉杆。}
{102}{}{叮！叮！叮！}
{103}{}{你得到了三个核弹。太棒了！$}
{104}{}{掉进接币盘里，你立刻捡起来。}
{105}{}{叮！叮！叮！}
{106}{}{你得到了三个炸弹。赢了！$30掉进接币盘里，你立刻捡起来。}
{107}{}{哎呀！你输了。}
{108}{}{你没有足够的钱来继续玩。}
