{100}{}{系统：                                                          主电源：                  离线                            应急电源：               在线}
{101}{}{电源管理}
{102}{}{电*源*管*理}
{103}{}{退出}
{104}{}{电源系统管理}
{105}{}{主电源}
{106}{}{应急电源}
{107}{}{返回}
{108}{}{主电源管理：       离线}
{109}{}{重新初始化主电源}
{110}{}{返回}
{111}{}{主电源管理：                                           错误！错误！错误！                                                主系统初始化失败}
{112}{}{诊断}
{113}{}{返回}
{114}{}{故障：        发电机6级                                        0反馈返回：  不可操作                                           需要维修}
{115}{}{返回}
{116}{}{应急电源管理：     在线}
{117}{}{禁用应急电源}
{118}{}{返回}
{119}{}{系统：                                                          主电源：                  在线                            应急电源：                待命}
{120}{}{电源管理}
{121}{}{退出}
{122}{}{主电源管理：       在线}
{123}{}{禁用主电源}
{124}{}{返回}
{125}{}{系统：                                                          主电源：                  在线}
{126}{}{禁*用*主*电*源}
{127}{}{禁用主电源}
{128}{}{退出}
{129}{}{电*源*系*统*管*理}
{130}{}{主*电*}
{131}{}{*急*电*}
{132}{}{返回}
{133}{}{主*电*管理}
{134}{}{重启主*电*}
{135}{}{返回}
{136}{}{主*电*管理：                                           错误！错误！错误！                                               发电机需要修理}
{137}{}{返回}
{138}{}{*急*电*管理：     离线}
{139}{}{系统：                                                          主电源：                  离线                            紧急电源：               离线}
{140}{}{启用紧急电源}
{141}{}{诊断主*电*}
{142}{}{主*电*评估}
{143}{}{启用紧急电源}
{144}{}{电源管理资源}
{145}{}{退出}
{146}{}{系统错误！                                                          无效用户。请通知管理员。                           系统已停止。}
{147}{}{退出}
{148}{}{禁用紧急电源}

{200}{}{授予我访问主机权限。}
{201}{}{访问被拒绝。终止输入。}
{202}{}{访问已授予。}
{203}{}{主菜单}
{204}{}{退出主机}
{205}{}{终止程序}
{206}{}{选择选项}
{207}{}{基地信息}
{208}{}{安全信息}
{209}{}{研究信息}
{210}{}{电源终端}
{211}{}{西部科技研究设施：                                              成立于2002年，作为美国政府的私人承包商，公司最初由两个部门组成——高级武器研究和生物医学科学部门。}
{241}{}{ 到2069年，西部科技成为美国政府最大的承包商；其最大的合同是动力步兵装甲T-51b型。}
{242}{}{鉴于2076年NBC在全免疫病毒项目上的重大进展，美国国防部因担心国际间谍活动，}
{243}{}{派遣一个团队进驻现场以确保和监督该项目，该项目现被称为FEV（强制进化病毒）项目。}
{212}{}{安全：                                                      安全机器人：激活}
{213}{}{安全：                                                      安全机器人：未激活}
{214}{}{停用安全机器人}
{215}{}{激活安全机器人}
{216}{}{研究：                                                      西部科技研究设施的记录最为完整}
{217}{}{研究部门员工记录}
{218}{}{动力装甲。状态：完成}
{219}{}{FEV（强制进化病毒）。状态：待定}
{220}{}{研究人员记录}
{221}{}{罗伯特·安德森                                                      研究助理                                                  安全许可：蓝色                                     驻地：马里波萨军事基地}
{222}{}{尼克·戴维斯                                                      西部科技研究NBC部门主任                安全许可：蓝色                                             驻地：西部科技研究设施}
{223}{}{约翰·艾萨克                                                      研究助理                                              安全许可：红色                                     驻地：西部科技研究设施}
{224}{}{史蒂夫·雷姆科                                                      研究助理                                              安全许可：蓝色                                     驻地：马里波萨军事基地}
{225}{}{查尔斯·里格霍尔德                                                      激光开发研究负责人                            安全许可：蓝色                                        驻地：西部科技研究设施}
{226}{}{米歇尔·桑托斯                                                      实验室技术员                                                      安全许可：红色                                         驻地：西部科技研究设施}
{227}{}{艾琳·谢尔曼                                                            实验室技术员                                                      安全许可：蓝色                                         驻地：马里波萨军事基地}
{228}{}{莱昂·冯费尔登                                                      FEV研究负责人                                        安全许可：蓝色                                        驻地：马里波萨军事基地}
{229}{}{下载记录到PIPBoy}
{230}{}{返回}
{231}{}{动力装甲规格：                                                      T-51b动力步兵装甲设计有最新的被动防御功能，适用于民用和军事干扰。}
{250}{}{背部安装的TX-28微聚变包产生60,000瓦特的能量，为内置在装甲框架中的高流液压系统供电。}
{251}{}{由最新的聚合物复合材料制成，T-51b外壳轻便，能够吸收超过2500焦耳的动能冲击。}
{252}{}{10微米的银质烧蚀涂层可以反射激光和辐射发射，而不会损坏复合材料的表面。}
{232}{}{FEV摘要：                                                      2073年。随着中国越来越多地使用生物武器，美国政府认为需要对策。全免疫病毒项目（PVP）于2073年9月15日正式成立。}
{233}{}{2075年。很明显，最好的对抗新生物武器的方法是改变未感染的DNA，使其不再易受标准病毒感染。}
{234}{}{2076年。2076年初，PVP项目开始出现意想不到的副作用。动物实验对象开始表现出异常的生长速度，并伴随大脑活动的增加。}
{235}{}{美国政府注意到了这些发现，并出于国家安全的考虑，派遣了一支团队到现场保护和监督这个项目，该项目现在被称为FEV（强制进化病毒）项目。}
{236}{}{2077年。FEV项目接近完成。对实验室动物的测试成功率接近100%。体型和肌肉密度增加约60%，潜在智力提高200%。}
{237}{}{对人类受试者的影响仍然未知；尽管理论上很有前景。}
{238}{}{军方希望继续进行进一步测试，在加利福尼亚中部的马里波萨军事基地建立了一个大型设施。在这个新设施中，FEV病毒的测试继续在军队志愿者中进行。}
{239}{}{命令接收：                            命令执行}
{240}{}{访问被拒绝}
