{100}{}{你看到一个矮胖的侏儒。}
{101}{}{你看到格雷奇，莫比德医生的助手。}
{102}{}{你来这里干什么？}
{103}{}{嗯？}
{104}{}{你老板让我下来的。}
{105}{}{别那样跟我说话，白痴。}
{106}{}{看看你怎么样。}
{107}{}{没事。再见。}
{108}{}{我认识你……对吧？}
{109}{}{不认识。}
{110}{}{认识。}
{111}{}{算了。}
{112}{}{嗯……好吧。}
{113}{}{你在做什么？}
{114}{}{好吧？那是不是快完成了？}
{115}{}{你有点慢，是不是？}
{116}{}{是的，是的，快完成了。}
{117}{}{完成什么？}
{118}{}{早该如此。}
{119}{}{太好了。回头见。}
{120}{}{身体部件快准备好送到集市了。}
{121}{}{为了什么？}
{122}{}{当然了。我就是为这个来的。}
{123}{}{我不想听这个。}
{124}{}{蜥蜴人鲍勃派你来的……他很高兴，有很多好肉……}
{125}{}{他在卖人肉给人吃？}
{126}{}{你这个恶心的小混蛋，我要把你切了卖肉！}
{127}{}{当然……我马上回来。}
{128}{}{给鲍勃卖……吃的……你问我们用来干什么干嘛？}
{129}{}{没什么。再见。}
{130}{}{我不太确定鲍勃是不是从这里弄来的人肉。}
{131}{}{有时候我思考会有点困难。}
{132}{}{我也觉得脑子不好使……我们刚才说什么来着？}
{133}{}{我不记得了。再见。}
{134}{}{你刚才在告诉我你在做什么。}
{135}{}{我们在说你有多蠢。}
{136}{}{不知道。}
{137}{}{我不想再跟你说话了。}
{138}{}{嗯……莫比德医生这儿的人体是最好的。没有比他更好的了。}
{139}{}{呃……我一会儿再回来取那些……尸体……再见。}
{140}{}{我要回去工作了。}
{141}{}{别碰医生的东西！}
