{100}{}{你看到冈瑟。}
{101}{}{你看到一个三十多岁，面容严肃的男人。}
{102}{}{欢迎来到我的寒舍。我能为你做些什么？}
{103}{}{你能告诉我一些关于中心的事吗？}
{104}{}{我可以在哪里找到弹药和武器？}
{105}{}{你在这里做什么工作？}
{106}{}{这里的法律是谁负责的？}
{107}{}{当然，你还想知道些什么？}
{108}{}{这是一个庞大的城市，是我一生中见过最大的。镇中心在南边，其他区域从那里向各个方向延伸。}
{109}{}{我可以在哪里找到补给？}
{110}{}{如果我想找工作，应该从哪里开始？}
{111}{}{我可以再问一个问题吗？}
{112}{}{谢谢你的信息。再见。}
{113}{}{我从马耳他之鹰酒吧的米奇那里得到我需要的一切。只要往南走就行了。}
{114}{}{我偶尔会在从这里出发的商队上做一段时间。如果你想找这种工作，就去找贸易行谈谈。我比较喜欢远行商队，但我和所有的商队都合作过。}
{115}{}{我大多数东西都是从武器店的贝丝那里买的。她的选择相当不错。}
{116}{}{如果我想找一些更“特别”的东西，该怎么办？}
{117}{}{提到你的名字会对价格有帮助吗？}
{118}{}{我听说旧城区有个人卖一些威力更大的东西。}
{119}{}{可能不会，她对她的保镖希德很有好感。不过，你可以试试布奇，他经营远行商队——那家店是他开的。}
{120}{}{我过得去。手头紧的时候，我会跟商队一起工作，或者在南边的农场打工。}
{121}{}{嗯，你可能在来的路上见过弗莱副警长。他的上司是格林警长，你大多数时候可以在警察局找到他。}
{122}{}{饼干！}
{123}{}{抱歉，你说的话我听不懂。也许儿童会的索恩戴克医生能帮到你。}
