{100}{}{你看到了比利。}
{101}{}{嘿！别碰我的东西！}
{102}{}{你好。}
{103}{}{你好，你在做什么？}
{104}{}{我能要一头双头牛吗？}
{105}{}{你好。呃，再见。}
{106}{}{啊！}
{107}{}{再见。}
{108}{}{你为什么想要一头双头牛？你有商队吗？嗯，这不重要。我只是照看它们。丹才是它们的主人，他不会卖的。}
{109}{}{为什么？}
{110}{}{我只是开玩笑。}
{111}{}{因为最近好多商队都失踪了。丹没有多余的牛用来贩卖了，大多数都用来拖商队了。其他的被卖掉做食物。我最好不再多说，丹看到我和陌生人说话会生气的。}
{112}{}{哦，好的。}
{113}{}{没什么，我在照看双头牛。}
{114}{}{那矛是做什么用的？它们危险吗？}
{115}{}{什么是双头牛？}
{116}{}{你在开玩笑吧？双头牛是这附近主要的食物和运输工具之一。它们拖着商队。丹说这工作非常重要，不过这工作很烂。}
{117}{}{哦，我知道的！}
{118}{}{丹说得对。你干得不错。}
{119}{}{嗯，看起来是这样。玩得开心。}
{120}{}{嘿，你是那些流氓中的一员吧？}
{121}{}{真的吗？你这么认为？真的，谢谢。}
{122}{}{你不是这里的人吧。我给你个忠告，别被抓到偷东西！}
{123}{}{当然，谢谢。}
{124}{}{我从没想过偷东西。偷东西是不对的。}
{125}{}{嗯，我觉得我开始同意你的观点了。这工作其实也没那么糟。出于某种原因，它让我感觉良好。好吧，我得走了，不然会惹上麻烦。}
{126}{}{请不要伤害我或我的双头牛。}
{127}{}{别伤害我！}
{128}{}{住手！}
{129}{}{请别烦我。}
{130}{}{你吓到我了。}
{131}{}{嘿，你想干什么？我没有你想要的东西。}
{132}{}{别这样！}
{133}{}{危险？不，倒不算太危险。它们会狠狠地咬人，但其实挺有趣的。它们经常放屁和打嗝，我也不知道为什么。}
{134}{}{那长矛是干什么用的？}
{135}{}{好的，谢谢。}
{136}{}{哦，它们有时候特别倔，我想让它们动的时候就轻轻戳一下。而且我不想靠太近，它们有时候会踢人。}
{137}{}{请别跟我说话，丹又要骂我了。他真的会很生气，我是说恼火，当我不专心的时候。}
{138}{}{他只是想帮忙。努力工作，我相信他会对你更好的。}
{139}{}{来，小鬼，拿着这50块，离这个混蛋远点。}
{140}{}{好的。}
{141}{}{啊啊啊！}
{142}{}{嗯？}
{143}{}{请别这样，我已经够麻烦了。}
{144}{}{我‘有’在努力工作！}
{145}{}{对不起，我不是那个意思。他只是想帮你。}
{146}{}{不，你没有！你这个懒惰的小鬼！}
{147}{}{好的。}
{148}{}{是啊，也许你说得对……其实他挺不错的，但我希望他不要总是对我大喊大叫。}
{149}{}{是啊，当然。}
{150}{}{去你的，老家伙！}
{151}{}{去你的，老太婆！}
{152}{}{哇！我可以靠这个过一辈子！非常感谢，先生！}
{153}{}{哇！我可以靠这个过一辈子！非常感谢，女士！}
{154}{}{哇！谢谢……你只是想让我再次惹上麻烦！}
{155}{}{请别跟我说话，丹真的很生气。}
{156}{}{别担心。我和他谈过了，他会对你更好的。}
{157}{}{他应该生气！你真是个糟糕的孩子！}
{158}{}{哇。}
{159}{}{嗨！}
{160}{}{那边的女孩真笨。}
{161}{}{又见面了。}
{162}{}{辐射牛真酷。}
{163}{}{丹说如果我表现好，就带我去猎鹰酒吧。}
{164}{}{丹总有一天会带我去做商队护卫！}
{165}{}{我长大后要成为一个冒险者。}
{166}{}{真的？哦，好吧。我希望你没伤到他。他其实没那么糟，就是爱吼。}
{167}{}{又见面了。}
{168}{}{你是做什么的来着？}
{169}{}{我能养一头辐射牛吗？}
{170}{}{只是过来看看情况。再见。}
{171}{}{啊！}
{172}{}{再见。}
{173}{}{我得回去工作了。}
{174}{}{那边的女孩真笨。}
{175}{}{又见面了。}
{176}{}{我长大后要成为一个冒险者。}
{177}{}{辐射牛真是呃，便便很多。}
{178}{}{我现在没空说话。}
{179}{}{我不想惹麻烦。}
