{100}{}{你看到一个儿童会的守卫。}
{101}{}{菲利普斯！让我们干掉这个家伙！}
{102}{}{别挡我的路！}
{103}{}{你想要什么？}
{104}{}{告诉我你的工作。}
{105}{}{这里是干什么的？}
{106}{}{你知道哪里能找到水芯片吗？}
{107}{}{你能告诉我关于一个叫德克的人吗？}
{108}{}{你那武器不错啊}
{109}{}{呃，牛奶。}
{110}{}{我是个雇佣兵。如果有人骚扰这些太空学员，我就干掉他们。你有意见吗？}
{111}{}{所以你是保镖}
{112}{}{谁雇的你？}
{113}{}{集市上有什么新鲜事吗？}
{114}{}{你在做什么？}
{115}{}{是的。大问题。}
{116}{}{没问题，朋友。}
{117}{}{叫做圣火的东西。别听这些废话，它会腐蚀你的脑子！}
{118}{}{你怎么看这个圣火？}
{119}{}{天啊，这些人真蠢！}
{120}{}{集市上有什么新鲜事吗？}
{121}{}{这些家伙从哪来的？}
{122}{}{水芯片？你是说冰块吗？可能在山上。}
{123}{}{不，我是指控制水净化系统的计算机芯片。}
{124}{}{不是那种芯片，笨蛋！}
{125}{}{呃，谢谢。我想。}
{126}{}{你去过山里吗？}
{127}{}{是的，我听说过他。他是个混蛋，但他付账。菲利普斯为他工作过几次。}
{128}{}{所以你觉得他是个混蛋？}
{129}{}{菲利普斯？}
{130}{}{你会接受他的工作吗？}
{131}{}{谢谢！}
{132}{}{是啊，这就是我在火拼时唯一想要的。有什么我可以帮你的吗？}
{133}{}{在这里哪里能找到好武器？}
{134}{}{这些大教堂的人有什么古怪的地方？}
{135}{}{在这里哪里能找到刺激的活动？}
{136}{}{你知道哪里能找到水芯片吗？}
{137}{}{你能告诉我关于一个叫德克的人吗？}
{138}{}{抱歉，伙计，我在值班。别闲聊。}
{139}{}{滚开，否则我就宰了你。}
{140}{}{干得好，火箭科学家！我还能是谁，莫比德医生吗？天啊！}
{141}{}{牧师那个贱人。你还以为是谁？天啊！}
{142}{}{不想承认，伙计，但我已经脱离圈子好几周了。你最好问问别人。}
{143}{}{食宿而已，没什么别的。这些宗教人士真小气！}
{144}{}{那就解决它！}
{145}{}{好吧。因为这里没人喜欢麻烦。}
{146}{}{这肯定是个骗局。没人会蠢到相信这些宗教废话。会吗？}
{147}{}{是啊。幸好他们没付我钱让我同意他们的观点。圣火，我呸！}
{148}{}{我不知道。我可以告诉你一件事，不管你怎么说这个宗教，他们不是业余的。他们来这里把事情组织得井井有条。这可不是一群无脑的僵尸。}
{149}{}{天啊，我以为只有避难所才用这种玩意儿！}
{150}{}{注意你的言辞，混蛋。这些人可能相信和平与爱，但我可不信！}
{151}{}{没问题。}
{152}{}{不。你爬得越高，辐射就越严重。}
{153}{}{呃，如果你喜欢精神失常、冷酷无情的混蛋，那他就是你的人。}
{154}{}{我的搭档。就是守着简的人。}
{155}{}{这取决于你喜欢多大的风险。我最近生活有点忙，所以来这里躲躲。但如果你喜欢刺激，当然可以。只要别搞砸，否则你就死定了。}
{156}{}{我听说水商总是有最好的货。但人们会对水商说任何话。反正这里这帮人里是没有的。}
{157}{}{我试着了解这些人好几个星期了。一开始我以为他们是傻子，但现在我不确定了。他们很有组织，而且有计划。我能感觉到！}
{158}{}{我听说德克有些活动，但伙计，那工作很烂，而且如果你搞砸了，就等于死定了。}
{159}{}{水净化芯片？你们不用井水？天哪！我听说在阴影沙地附近有个避难所可能有一个，但那地方完全塌了。我想我帮不了你。}
{160}{}{不能说话。老板不喜欢。抱歉。}
{161}{}{嘿，你！}
{162}{}{嘿！你以为你在干什么！}
{163}{}{为什么上锁？}
{164}{}{嘿，我退后了！}
{165}{}{能帮我一下这扇门吗？它卡住了！}
{166}{}{你看见我了！对你来说真不妙。}
{167}{}{不关你的事！滚开！}
{168}{}{好！现在滚开！}
{169}{}{滚蛋！如果你再敢这样，我会亲手宰了你！}
{170}{}{我们不该跟你说话。走吧，伙计。}
{171}{}{嘿！你以为你在干什么！}
{172}{}{为什么上锁？}
{173}{}{嘿，我退后了！}
{174}{}{能帮我一下这扇门吗？它卡住了！}
{175}{}{你看见我了！对你来说真不妙。}
{176}{}{不关你的事！滚开！}
{177}{}{好！现在滚开！}
{178}{}{滚蛋！如果你再敢这样，我会亲手宰了你！}
