{100}{}{你看到治安官贾斯汀·格林。}
{101}{}{哎呀，是那个屠杀无辜者的人。我听说过你，你得感谢我这枚徽章让我没当场毙了你。我建议你立刻离开我们的城镇——现在就走。别靠近我们的孩子。}
{102}{}{您好，先生！我叫贾斯汀·格林，是这座城市的治安官。今天有什么我可以为您效劳的吗？}
{103}{}{您好，女士！我叫贾斯汀·格林，是这座城市的治安官。今天有什么我可以为您效劳的吗？}
{104}{}{那么，说吧！}
{105}{}{德克雇我去杀一个商人和他的妻子。}
{106}{}{德克试图雇我去杀一个叫简的人。}
{107}{}{没什么，抱歉。}
{108}{}{抱歉，我不能告诉你。我会死的。}
{109}{}{哦，谢谢。我们尽力而为。在这样一个大城市里真的很难，但我们尽量用现有的资源做到最好。当那些暴徒的火力比我们强时，这就更难了。}
{110}{}{再次感谢。}
{111}{}{是时候离开了，杀童者。}
{112}{}{我们不能允许那样发生。不过，如果你改变主意，请告诉我。外面的世界很危险，总得有人挺身而出维护正义。}
{113}{}{太好了！我已经从其他渠道听说了他的计划。你是我采取行动所需的最后确认。这会很艰难，我需要一切可以得到的帮助。我可以支付你1000瓶盖。现在给你200，剩下的等我们结束后再给。你觉得怎么样？}
{114}{}{你来晚了……该死！我知道他有责任，只希望我能及时知道以阻止他。无论如何，你是我采取行动所需的最后证人。我们得“解决”他。这会很艰难，我需要一切可以得到的帮助。我可以支付你1000瓶盖。现在给你200，剩下的等我们结束后再给。你觉得怎么样？}
{115}{}{你来晚了……我怎么知道你不是凶手？德克不可能让知道他计划的人活着。}
{116}{}{我刚收到消息，她已经死了……等一下。我怎么知道你不是凶手？德克不可能让知道他计划的人活着。}
{117}{}{很高兴为您效劳。}
{118}{}{抱歉，我要全部预付。}
{119}{}{不可能！你自己解决吧。}
{120}{}{不行。你看起来很可信，但我不能确定你不会在关键时刻抛下我们。这样的话，我们中至少有一个人活下来确保你得到报酬。这也算是一点“保险”。}
{121}{}{那就干吧。}
{122}{}{治安官，你自己解决吧。}
{123}{}{太好了！你准备好就可以出发。}
{124}{}{我准备好了。}
{125}{}{好吧，再见。}
{126}{}{很遗憾听到这个。如果你改变主意，请告诉我，但我不能等太久。}
{127}{}{好吧，我会做的。等我去准备一些补给。}
{128}{}{你疯了。}
{129}{}{再见。}
{130}{}{太好了！准备好就告诉我。我们会等你，但别拖太久。}
{131}{}{什么？你指望我站在一边看他杀害无辜的人吗？我对这个城市有责任，我不指望你能理解。}
{132}{}{你说得对。现在轮到你了。}
{133}{}{你怎么敢指责我！}
{134}{}{我不在乎你怎么想。}
{135}{}{嗯，他没有采取任何行动。}
{136}{}{我们在猎鹰酒吧，周围有很多人。}
{137}{}{对不起。德克一直在挑拨我们彼此对立多年。我不知道还能信任谁。不过我真的需要你的帮助。这会很艰难，但我会付你1000个筹码。现在给你200，完成后再给800。}
{138}{}{我一闻就知道是个叛徒！你真幸运我没有证据，我建议你在我找到证据之前赶紧离开这个城市。}
{139}{}{这很奇怪。我从没听说过德克离开他的办公室。他一定是胆子大了。那个该死的杀人犯……啊！我总有一天会抓住他的！这样吧，你帮我们，我会付你1000个筹码——现在给你200，全部完成后再给800。你觉得怎么样？}
{140}{}{这是我听过的最大的胡扯。德克从不离开他的办公室。我就知道你有问题。你真幸运我没有证据，我建议你在我找到证据之前赶紧离开这个城市！}
{141}{}{好了，出发吧……}
{142}{}{所以，你是来投案自首的？我很佩服。}
{143}{}{是的，对不起。}
{144}{}{自首？别逗我笑了。}
{145}{}{抓住他！}
{146}{}{抓住她！}
{147}{}{好了，进你的牢房吧。}
{148}{}{坐好。你暂时哪儿也去不了。}
{149}{}{逃犯！抓住他！}
{150}{}{逃犯！抓住她！}
{151}{}{准备好了吗？}
{152}{}{是的。}
{153}{}{不。}
{154}{}{呃。}
{155}{}{我简直不敢相信德克终于死了。我从没想过会有这一天。}
{156}{}{你改变主意了吗？我们仍然需要你来清除我们谈过的那个祸害。}
{157}{}{我去。}
{158}{}{不，抱歉。}
{159}{}{哈？}
{160}{}{我们在盯着你。}
{161}{}{我有罪案要报告！}
{162}{}{你干得不错。}
{163}{}{只是路过。再见。}
{164}{}{哦啦。}
{165}{}{您好，又见面了，先生。今天有什么我能帮忙的吗？}
{166}{}{您好，又见面了，女士。今天有什么我能帮忙的吗？}
{167}{}{您好。我能为您做些什么？}
{168}{}{有什么事吗？}
{169}{}{好好休息一下，行吗？}
