{100}{}{你看到了一名守卫，名叫莱昂。}
{101}{}{你来这里有什么事？}
{102}{}{我必须见海塔先生。}
{103}{}{我是来杀海塔先生的。}
{104}{}{这与你有什么关系？}
{105}{}{好的。但我会盯着你。他在他的办公室。}
{106}{}{谢谢。}
{107}{}{是啊……我敢打赌你会盯着我。}
{108}{}{我不喜欢你的态度。我得请你离开。}
{109}{}{我想走的时候才会走，伙计！}
{110}{}{好吧，我会离开。}
{111}{}{态度？我会让你见识什么叫态度！！！}
{112}{}{不管什么事，你可以告诉我。海塔先生现在很忙。}
{113}{}{你为什么要这么难搞？}
{114}{}{我更愿意亲自告诉他。这是生死攸关的事情。}
{115}{}{德克已经对海塔下了追杀令。}
{116}{}{你可以告诉我，或者你可以离开。}
{117}{}{谁死了让你当上了上帝？}
{118}{}{德克已经对海塔下了追杀令。}
{119}{}{听着，我什么都不会告诉你！}
{120}{}{我会离开。}
{121}{}{又来了？德克真是个傻瓜。嗯？……我猜他还不如他雇来干这活的人傻。看看这，看看我的枪。}
{122}{}{[莱昂给你看他的枪侧面，上面有5个深深的划痕。]}
{123}{}{每一个划痕都是过去对海塔生命的威胁。我每一个都解决了。告诉我……你知道德克这次雇的傻瓜长什么样吗？}
{124}{}{不知道。}
{125}{}{就是我，你这个白痴！}
{126}{}{嘿！哇！你的枪上有划痕！你真酷！}
{127}{}{谢谢你的提前警告，但海塔先生不喜欢陌生人在附近。我得请你离开。}
{128}{}{就这样？没有奖励？你们这些人到底怎么回事？}
{129}{}{不客气。再见。}
{130}{}{海塔先生不见客。现在离开！}
{131}{}{我要走的时候自然会走，伙计！}
{132}{}{好吧，我这就走。}
{133}{}{我真的需要和海塔先生谈谈。}
{134}{}{好吧，伙计。我们走吧。[里昂抓住了你的手臂。]}
{135}{}{把你的脏手从我身上拿开！}
{136}{}{好吧，好吧！我走就是了。}
{137}{}{等等！我还没说完呢！}
{138}{}{呃！}
{139}{}{鲁克！}
{140}{}{我有紧急消息要告诉海塔先生。}
{141}{}{你在这里干什么？我现在下班了。去找别人麻烦。}
{142}{}{我就知道你这家伙会在这里晃悠！警卫！}
