{100}{}{你看到乔治，门卫。}
{101}{}{有什么我能帮忙的吗？}
{102}{}{我想见海塔先生！}
{103}{}{是的。我来见海塔先生。}
{104}{}{我和海塔先生有约，而且我已经很晚了。}
{105}{}{让我进去。}
{106}{}{海塔先生不是谁都见的。}
{107}{}{他想见我。}
{108}{}{我该如何预约见他？}
{109}{}{我可不是随便什么人，笨蛋！}
{110}{}{哦，好吧。再见。}
{111}{}{好的。进去吧。}
{112}{}{我认识海塔先生的所有伙伴，但从没见过你，所以你最好现在就离开。}
{113}{}{哦，你麻烦大了！海塔先生最讨厌别人迟到。我让他亲自训你。进去吧。}
{114}{}{你进不去的。滚开，混蛋！}
{115}{}{我不想在这里惹麻烦，所以你最好现在就离开。}
{116}{}{滚开！}
{117}{}{你进不了这个门。}
{118}{}{你鬼鬼祟祟地在干什么？！守卫！！}
{119}{}{离开那扇门！没有经过我谁也进不去！}
{120}{}{你真有胆量来这里！守卫！！}
