{100}{}{你看到一个车队工人。}
{101}{}{今天会是漫长的一天！}
{102}{}{我真的不想今天上班。}
{103}{}{希望我们不会被袭击……或者更糟。}
{104}{}{抱歉，我们不需要更多的护卫……我想。}
{105}{}{抱歉，我们满员了。}
{106}{}{如果你想找工作，可以去商人市场看看。}
{107}{}{希望我们能卖光所有东西。}
{108}{}{我迫不及待想要结束。}
{109}{}{我准备好大干一场了。}
{110}{}{我们要离开这里了！}
{111}{}{今天真是热啊。}
{112}{}{天哪，我好渴。}
{113}{}{今天星期几？}
{114}{}{一完成我就去猎鹰酒吧！}
{115}{}{抱歉，我们刚从一条路线回来。}
{116}{}{如果你想找工作，可以去商人市场看看。}
{117}{}{今天是发薪日！}
{118}{}{我直奔鲍勃那儿！}
{119}{}{我今天得还贷款！}
{120}{}{我太累了。}
{121}{}{那真是一次漫长的旅程！}
