{100}{}{你看到一个集市守卫。}
{101}{}{需要帮忙吗？}
{102}{}{是的。你能告诉我这里是哪里吗？}
{103}{}{再见。}
{104}{}{呃……呵呵……呃……呵。}
{105}{}{天啊，你比一袋锤子还笨，是吧？快滚吧。}
{106}{}{你在集市的南端。如果你四处看看，会找到水商和一个小医院。}
{107}{}{水商是谁？}
{108}{}{一个医院？}
{109}{}{谢谢。再见。}
{110}{}{那些混蛋。他们以为自己拥有整个集市，只因为他们控制了水塔。}
{111}{}{一个医院？}
{112}{}{谢谢。再见。}
{113}{}{大教堂的孩子们在集市这里经营一个小医院。他们看起来还不错。}
{114}{}{水商是谁？}
{115}{}{谢谢。再见。}
