{100}{}{你看到欧文。}
{101}{}{天啊，你就不能让我一个人待着吗？我已经够烦心的了。}
{102}{}{有麻烦？也许我能帮你。}
{103}{}{好像只有你有麻烦似的。}
{104}{}{好吧，好吧。没必要对我大喊大叫。}
{105}{}{嗯……我不知道。这需要比你更有经验的英雄。听着，等你有更多经验再来找我吧。}
{106}{}{这真是个悲剧，相信我。一切都不如从前了。我在城外有个小农场，几天前一群袭击者突然出现，现在把我家当成了他们的营地。他们杀了我的驴子帕格斯利，还威胁说如果我敢回来就杀了我。}
{107}{}{告诉我地点，剩下的交给我。}
{108}{}{抱歉，欧文，我有更重要的事情要做。}
{109}{}{真的，你愿意帮忙？你知道，我不敢再回去了。等安全了你再回来告诉我，好吗？}
{110}{}{听着，怪胎，我一开始就让你别烦我。现在滚开！}
{111}{}{我就知道你会退缩。每次遇到袭击者大家都是这样。}
{112}{}{那么，你有没有教训那些袭击者？我的家安全了吗？}
{113}{}{当然安全了，伙计。}
{114}{}{我还没来得及处理。}
{115}{}{哦，非常感谢。我很抱歉没有什么值钱的东西给你，但请收下这把步枪，感谢你拯救了我的家。}
{116}{}{你在骗我，对吧？请别拿我开玩笑。等真的安全了再回来告诉我，好吗？}
{117}{}{非常感谢你帮了我。}
{118}{}{格隆克？}
{119}{}{看，我没时间理傻子。等你聪明点再来吧。}
{120}{}{嗯哼，嗯哼，嗯哼。我搞定了。}
{121}{}{我还没修好。}


{300}{}{去见你的造物主吧！}
{301}{}{干掉他……让他死！}
{302}{}{你吃最后一块奶酪面包的日子到了！}
{303}{}{我要把你打成瑞士奶酪！}
