{100}{}{这个男人辗转反侧。}
{101}{}{哦 . . .}
{102}{}{你看到一个面色苍白、瘦弱的年轻人。}
{103}{}{你看到贾维斯，塞斯的弟弟。}
{104}{}{你好。很抱歉，我现在感觉不太好。如果你能找到对抗辐射蝎的方法，请和我哥哥塞斯谈谈。}
{105}{}{非常感谢你帮助我。我叫贾维斯，是塞斯的弟弟。如果你有任何需要了解的事情，请尽管问。}
{106}{}{又见面了。我能帮你什么忙吗？}
{107}{}{你能多告诉我一些关于你哥哥的事吗？}
{108}{}{给我讲讲这个镇子吧。}
{109}{}{只是闲聊，谢谢。}
{110}{}{塞斯是个很好的战士。他非常坚定。有时有点过于执着。不过，他对我们村子的福祉很投入。}
{111}{}{好吧，阴影沙漠是由我们现任领袖阿拉迪什的伟大祖先建立的。他可以告诉你更多的故事。我们有水井和灌溉系统，所以我们过得不错。}
{112}{}{这个人正遭受剧毒的折磨。}
{113}{}{你无法弄清楚这个人受到了什么影响。}
{114}{}{这个人正在遭受辐射蝎毒的折磨。}
{115}{}{你无法弄清楚这个人受到了什么影响。}
{116}{}{这个技能在这里无用。}
{117}{}{在接下来的几分钟里，这个人明显好转。}
{118}{}{塞斯是哥哥？}
{119}{}{这个地方？}
{120}{}{嗯。}
{200}{}{你因治愈贾维斯的中毒获得400点经验值。}
