{100}{}{我们提供身体的治疗以治愈灵魂。我能帮你吗？}
{101}{}{是的，请帮助我。}
{102}{}{你们是什么人？}
{103}{}{之前在这里的人发生了什么事？}
{104}{}{嗯}
{105}{}{没关系，我的孩子。我们现在就来检查你。}
{106}{}{心灵纯净的人是有福的。你没有任何问题，我的孩子。去玩吧。}
{107}{}{你已经痊愈了。以后要小心点。}
{108}{}{你受伤了。}
{109}{}{我看到你中毒了。}
{110}{}{嗯，有些辐射中毒。不幸的是，我们无法治愈这个。}
{111}{}{我们需要捐赠$}
{112}{}{才能治愈你。你能接受吗？}
{113}{}{可以。}
{114}{}{不可以。}
{115}{}{但我没有那么多钱！}
{116}{}{你能接受$}
{117}{}{吗？}
{118}{}{孩子们不讨价还价。你愿意接受我们的价格吗？}
{119}{}{是的，当然可以。}
{120}{}{你可以去死！}
{121}{}{谢谢你，我的儿子。让我们为你的康复祈祷。}
{122}{}{谢谢你，我的女儿。让我们为你的康复祈祷。}
{123}{}{给你。愿孩子们的和平与祝福与你同在。}
{124}{}{你没有足够的钱。如果你捐出所有能捐的，我们会治愈你。你能接受吗？}
{125}{}{可以。}
{126}{}{不可以。}
{127}{}{如果你捐出所有能捐的，我们会治愈你。你能接受吗？}
{128}{}{可以。}
{129}{}{不可以。}
{130}{}{你有足够的钱来捐赠。你需要学习数学，我的孩子。}
{131}{}{我们是大教堂的信徒。我们在荒地中与那些不幸的人们生活和工作。如果你有机会去骨园，欢迎来大教堂看看。}
{132}{}{谢谢你。}
{133}{}{你们是做什么的？}
{134}{}{我们是和平的治疗者和教师。我们治愈身体以治愈灵魂。我们只需要一点小捐赠来支付我们的医疗用品。}
{135}{}{听起来是个不错的主意。}
{136}{}{听起来像是一派胡言。}
{137}{}{我们没有问你。我能看出你已经厌倦了听我们的信仰。如果你需要其他帮助，我们会在这里。}
{138}{}{这是最神圣的理念。我们正在为荒地的终极和平而努力。所有生物将和谐共存。}
{139}{}{谢谢。祝你有美好的一天。}
{140}{}{他们把这所房子捐给了我们，以便我们能传播信仰并履行我们作为治疗者的职责。}
{141}{}{莫比德医生对此不生气吗？}
{142}{}{他们真是太好了。谢谢。}
{143}{}{那个异教徒的感受与我们无关。我们在这里履行我们的职责，这将会完成。}
{144}{}{呃，哦，谢谢。再见。}
{145}{}{你为什么要这样做？我们不会伤害你！}
{146}{}{你没有需要帮助的情况。}
