{100}{}{你看到詹妮弗。}
{101}{}{你看到一位骑士。}
{102}{}{打扰一下，兄弟。你在兄弟会时应该收起武器。我们是一个友好的组织，但如你所知，现在的形势很艰难。}
{103}{}{如果一个陌生人……我是说，一个新的见习者……带着武器接近他们，兄弟会的一些成员可能会感到不快。}
{104}{}{你好，见习者。我能帮你什么忙？}
{105}{}{你好，姐妹，看到这个组织中有女性担任职务真是太好了。我不知道像“兄弟会”这样的名字会有什么样的期待。}
{106}{}{嘿，美女。你看起来真不错。我该什么时候来接你？}
{107}{}{哦哦哦！}
{108}{}{你能告诉我哪里可以找到我们的高阶长老吗？}
{109}{}{谁是这里的负责人？}
{110}{}{那个高阶长老在哪儿？}
{111}{}{咕噜！}
{112}{}{高阶长老马克森在第四层。如果你乘另一部电梯下到四层，他应该在议会厅或长老的房间里。}
{113}{}{你可以问那层的守卫，他们应该知道他现在在哪。}
{114}{}{谢谢你。}
{115}{}{我在哪里可以得到更好的武器？}
{116}{}{你应该去找塔卢斯。他可能能帮你，或者至少告诉你该找谁。}
{117}{}{白天，塔卢斯通常在训练大厅监督。你知道那在哪里吗？}
{118}{}{是的，我知道。谢谢你。}
{119}{}{不知道。}
{120}{}{当然知道！}
{121}{}{训练大厅就在拐角处。沿着这条走廊走，左转，穿过走廊尽头的门，训练大厅就在你右手边的门里。}
{122}{}{你帮了大忙。非常感谢。希望我们能很快再聊。祝你有个好日子。}
{123}{}{训练大厅？你觉得我可以在那里接受训练吗？我现在是兄弟会的一员，对吧？}
{124}{}{谢谢你的帮助，姐妹。看到这个组织中有女性担任职务真是太好了。我不知道像“兄弟会”这样的名字会有什么样的期待。}
{125}{}{谢谢，甜心。你知道吗，你看起来真不错。你觉得我们以后可以互相“检查”一下装备吗？你什么时候下班？}
{126}{}{哦，那个地方。好的，再见。}
{127}{}{打扰一下？有什么问题吗？}
{128}{}{咕噜？}
{129}{}{抱歉，我想我帮不了你。你应该去看医生。她在第二层。}
{130}{}{当然有。在我们的五位长老中，有两位是女性，我们的大抄写员也是女性，并且在各个不同的等级中都有许多其他女性。}
{131}{}{兄弟会的女性成员也被称为兄弟。我们不称呼女性为姐妹。毕竟，这是钢铁兄弟会，而不是钢铁兄弟姐妹会。}
{132}{}{你不觉得称其为兄弟会有些奇怪吗？这暗示着成员仅由男性组成。}
{133}{}{那为什么叫兄弟会呢？}
{134}{}{嗯，这确实有点奇怪。}
{135}{}{我不知道。这是我一生以来的名字。我相信一定有原因。}
{136}{}{我想你说得对。}
{137}{}{嗯，对我来说还是有点奇怪。}
{138}{}{这确实很奇怪。我从没真正想过这个问题。我们一直以来都是钢铁兄弟会。我们的祖先一定有他们的理由。}
{139}{}{但这并不意味着事情不能改变。}
{140}{}{是的，你可能是对的。}
{141}{}{那么，还有什么我可以帮你的吗？}
{142}{}{是的，我在哪里可以找到大长老？}
{143}{}{我在哪里可以获得更好的武器？}
{144}{}{没有了，就这样，再见。}
{145}{}{不，我们在传统方面非常严格。我不认为这会改变。被称为兄弟对我来说一点也不困扰。不过，这确实很有趣。}
{146}{}{我想我会和Vree谈谈。她可能能够解释我们的祖先为什么决定称我们为钢铁兄弟会。}
{147}{}{Vree是谁？是长老之一吗？}
{148}{}{Vree是大抄写员。如果你有任何技术问题，你应该找她谈，但不要在晚上打扰她冥想。}
{149}{}{她几乎总是待在她的房间里，那里也是主机所在的三楼。}
{150}{}{洞穴？你怎么敢这样谈论兄弟会。你现在是我们组织的一员，应该为成为钢铁兄弟会的一员而自豪。}
{151}{}{自豪？为什么？你们只是一群躲避现实世界的机器人迷幻者。没什么值得自豪的。}
{152}{}{对不起。我有时会有点失控。}
{153}{}{是啊，没错。}
{154}{}{嗯，我想我们有时都会这样。}
{155}{}{那么，这里由谁负责？}
{156}{}{是的。嗯，我得走了。}
{157}{}{Maxson，大长老。他在四楼。}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{嗯，你挺可爱的……不过我觉得不行。我觉得和外来者牵扯不清不是个好主意。不过，你确实挺可爱，也有点吸引人。}
{164}{}{我不知道是因为你是外来者，还是因为你极度……缺乏分寸感？那么，“亲爱的”，还有什么我能为你做的吗？}
{165}{}{嗯，我想是的。呃，这里谁负责？}
{166}{}{呃，好吧……那么，武器呢？我能在哪里弄到一些？}
{167}{}{哼！}
{168}{}{不。}
{169}{}{那真是……挺搞笑的。我希望你是在开玩笑？其实……别回答，我不想知道。}
{170}{}{是啊，真搞笑。就像你的脸一样！}
{171}{}{非常感谢。这正是我现在需要听到的。}
{172}{}{我走了。}
{173}{}{抱歉。只是你们外来者有时候说话的方式真奇怪。我能帮你什么忙吗？}
{174}{}{嗯，我想我应该去找那个高级长老谈谈。他在哪儿？}
{175}{}{我想要更好的武器。我该找谁谈这个？}
{176}{}{不。}
{177}{}{你是认真的吗？我这辈子都没听过这么可怜的搭讪！}
{178}{}{是吗？好吧，我不常出门。行吗？}
{179}{}{滚开，你这个行走的垃圾桶！}
{180}{}{呸！}
{181}{}{嗯，是的，你是兄弟会的一员，但长老们暂停了对新入会者的所有训练。}
{182}{}{为什么？}
{183}{}{哦，那真是太好了！我为什么要加入这个愚蠢的组织？门在哪？！}
{184}{}{有传言说有某种军队。我想长老们想集中资源在那些已经训练到足以在大战中有所作为的人身上。}
{185}{}{我们坚信，训练少数战士到极致要比给一群战士提供平庸的训练更好。拯救生命是我们的首要目标之一。}
{186}{}{你可以通过观察获得不少训练经验。托马斯兄弟是我们兄弟会有史以来最好的教官。}
{187}{}{好吧，我是在兄弟会外工作，对吧？外面的世界非常危险，我在外面每一分钟都在冒生命危险。你不觉得如果我想要或需要训练，就应该给我训练吗，还是你们只是“说”拯救生命是你们的首要目标？}
{188}{}{谢谢你的建议，我会去看看。}
{189}{}{你们都是一群傻瓜。}
{190}{}{你能告诉我马克森在哪里吗？}
{191}{}{嗯，我只是重复我听到的。如果你和托马斯或塔勒斯谈谈，他们可能会破例。}
{192}{}{好的，谢谢。}
{193}{}{他们最好这样。我已经为你们跳过足够多的圈套了。}
{194}{}{那么，你能告诉我马克森在哪里吗？}
{195}{}{哦，我的亲爱的。我们什么时候结婚？}
{196}{}{你看起来一如既往地英俊。}
{197}{}{给我一个吻。}
{198}{}{我好想你。}
{199}{}{我会等你回来。}
{200}{}{我整天都在想着你。}
{201}{}{你这样看着我真可爱。}
{202}{}{别这样吓我。我以为再也见不到你了。}
{203}{}{你昨晚没来。}
{204}{}{我有多久没见到你了？感觉像是过了一个世纪。}
{205}{}{我非常想念你。}
{206}{}{来床上吧，亲爱的。}
{207}{}{我们可以早上结婚。}
{208}{}{我觉得我们应该要五个孩子。}
{209}{}{你想去哪里度蜜月？我听说大教堂的孩子们有个很漂亮的地方。}
{210}{}{我父母还在等着见你。}
{211}{}{你好，又见面了。希望你一切都好。希望你和维里谈过了。}
{212}{}{你好，兄弟}
{213}{}{。}
{214}{}{如果你去北边要小心。我们的侦察兵从未回来。}
{215}{}{兄弟}
{216}{}{，很高兴再次见到你。}
{217}{}{你和菱形谈过了吗？他是首席骑士。他就在那间房里。}
{218}{}{我没时间聊天。我很忙。}
{219}{}{抱歉，我没心情和粗鲁的人说话。}
{220}{}{别打扰我。}
{221}{}{怎么了？不能去烦别人吗？}
{222}{}{走开。}
{223}{}{我不想跟你说话。}
{224}{}{学员，回去继续学习。}
{225}{}{没时间聊天，学员。}
{226}{}{快过来，我的小帅哥！}
{227}{}{亲爱的，到这边来！}
{228}{}{我好想你。}
{229}{}{我已经把育婴室准备好了，亲爱的。}
{230}{}{嗨，亲爱的。}
{231}{}{我看到你了。}
{232}{}{你必须见见我的父母。}
{233}{}{呦吼！}
{234}{}{过来，我的小宝贝。}
{235}{}{你在逗我吗？}
{236}{}{是不是在故意让我费劲追你？}
{237}{}{过来，我的大汗淋漓！}
{238}{}{嗨，亲爱的！}
{239}{}{你终于来了，我快担心死了。}
{240}{}{过来给我一个吻，帅哥。}
{241}{}{进来吧，亲爱的。}
