{100}{}{你看到耶利米，他是儿童会的信使。}
{101}{}{你看到一个儿童。他看起来若有所思。}
{102}{}{打扰了，兄弟。你吓到我了。我能为主服务什么？}
{103}{}{妙语！}
{104}{}{你在做什么？}
{105}{}{啊，是的，一个正在训练中的超级变种人。我会回去继续我的任务。}
{106}{}{如果你不知道，那就与你无关。如果你在打听不该知道的事情，我就得向我们的上级报告。你应该知道分寸。}
{107}{}{我是一个重要人物。}
{108}{}{抱歉打扰你了。}
{109}{}{我刚到这里。}
{110}{}{你凭什么来问我问题？！你真幸运我没有把你报告给圣火！！}
{111}{}{当然是在传送报告。}
{112}{}{什么报告？如果可以问的话。}
{113}{}{你做得很出色。}
{114}{}{就这样，谢谢。}
{115}{}{好吧，那么。愿你平安。}
{116}{}{我道歉。我能为您效劳什么？}
{117}{}{你在做什么？}
{118}{}{你可以先回答我的问题。}
{119}{}{你可以去死！}
{120}{}{卫兵！！！}
{121}{}{显然你不属于这里。你是谁？}
{122}{}{其实我是避难所居民，想和主谈谈。}
{123}{}{嗯……多尔菲斯……嗯……莫菲斯派我来的。}
{124}{}{我是洛基，来自南方的新人。}
{125}{}{不，我不属于这里。但我知道这颗子弹属于哪里……在你的脑袋里。}
{126}{}{我传送周边地区的人类纯度报告。但你应该知道这个。[怀疑地看着]你是谁？}
{127}{}{我被莫菲斯派来给主带个消息。}
{128}{}{我的身份与你无关……只需回答我的问题！}
{129}{}{你不该知道我是谁，这是主的意愿。}
{130}{}{你竟敢质疑我是谁？愚蠢，我应该就在这里把你打倒。}
{131}{}{这真是奇怪……我从未听说过你。}
{132}{}{我是被莫菲乌斯派来给大师传话的。}
{133}{}{我是高阶成员。只有大师和莫菲乌斯知道我的存在，以确保我在外界的安全。但我已被大师召回。}
{134}{}{请原谅我。我为质疑您而道歉。请继续您的事务，如果我能帮上忙，请告诉我。}
{135}{}{我不知道你是谁，你不属于这里。卫兵！！！}
{136}{}{你是谁？你在这里做什么？}
{137}{}{我是一个信徒，我迷路了。}
{138}{}{莫菲乌斯派我来给大师传话。}
{139}{}{寻找一个孤独的灵魂送上天堂。}
{140}{}{呃！}
{141}{}{你不被允许进入这个区域。只有侍奉者及以上级别的人才可以进入这里。返回大教堂。}
{142}{}{我为造成的麻烦道歉。}
{143}{}{在我离开之前，我可以问您几个问题吗？}
{144}{}{可以，但不是在我劈开你的脑袋之前。}
{145}{}{莫菲乌斯不会派像你这样的废物执行这样的任务。卫兵！！}
{146}{}{你这个白痴！你不被允许进入这个区域。立刻返回大教堂！}
{147}{}{好吧。}
{148}{}{嗯。}
{149}{}{不。}
{150}{}{我为大师转移记录。你只需要知道这些，孩子。现在，你必须离开。}
{151}{}{我现在就走。}
{152}{}{我只是想再问您几个问题。}
{153}{}{我会走的。我会走的。但不是在我打爆你的脑袋之前。}
{154}{}{你是怎么进来的？！你在这里偷偷摸摸做什么？}
{155}{}{我只是想问您几个问题。}
{156}{}{不，你不能问我任何问题。现在离开。}
{157}{}{停下！你在这里没有正当理由！}
{158}{}{呃？}
{159}{}{抱歉。我迷路了。我这就走。}
{160}{}{但我确实有任务在身。莫菲乌斯派我为主人执行一项任务。}
{161}{}{我跟踪一个可疑的人到了这里。你见过他吗？}
{162}{}{不，杀戮是我的生意，而且生意兴隆。}
{163}{}{没有，我没见过任何人。他长什么样？}
{164}{}{没关系，我想他已经跑掉了。}
{165}{}{是一个矮小的绿色小人。}
{166}{}{他和你差不多高，但穿着皮夹克……你这些长袍下穿的是什么？}
{167}{}{他看起来就像你，蠢货！}
{168}{}{呃……我……我……你不会真的以为是我吧？多荒谬。我从来没有！}
{169}{}{好吧，那我先走了，但如果你看到什么请告诉我……}
{170}{}{是的！我确实认为是你！趴下，别动！}
{171}{}{不，我不认为是你，但我可以问你几个问题吗？}
{172}{}{是的，我的兄弟。我能为你做些什么？}
{173}{}{是的，我的姐妹。我能为你做些什么？}
{174}{}{兄弟，你在这里做什么？}
{175}{}{只为主人服务。这就是我所求的。兄弟。}
{176}{}{抱歉，认错人了。你们穿着这些长袍都看起来一样。}
{177}{}{你可以通过去死来为我服务，你这个疯子！}
{178}{}{我负责传递周边地区的人类纯净报告。}
{179}{}{就这样。谢谢。}
{180}{}{兄弟，我想再问你几个问题。}
{181}{}{是的，这是个非常重要的工作。你明白你对主人和我们所有人的职责的重要性吗？}
{182}{}{当然，我是那个向主人报告未受辐射污染的新纯净人类的人。我是那个向主人报告可能存在的失落避难所的人。那里可能还有纯净的人类。}
{183}{}{是的，我的兄弟。你理解。谢谢。这就是全部。}
{184}{}{我想问你一些其他问题。}
{185}{}{即使一个纯净人类站在你面前，你也认不出来。白痴。}
{186}{}{即使一个纯净人类站在你面前，你也认不出来。白痴。}
{187}{}{你表现得很奇怪。我不相信你是你所说的人。卫兵！}
{188}{}{你问的问题太多了。我不相信你是你所说的人。卫兵！}
{189}{}{嘿！我告诉过你这里不允许进入！卫兵！}
{190}{}{你问的问题太多了。你是谁？}
{192}{}{打扰了，姐妹。你吓到我了。我该如何为主人效劳？}
