{100}{}{你看到招聘公告板}
{101}{}{招聘！需要工作吗？需要钱吗？看这里！}
{102}{}{请不要重复张贴信息。 -治安官格林。}
{103}{}{1       失踪的商队！悬赏！}
{104}{}{2       招募商队护卫。}
{105}{}{8a}
{106}{}{8b}
{107}{}{8c}
{108}{}{8d}
{109}{}{9       退出}
{110}{}{1a      悬赏：失踪的商队。凡能抓住那些洗劫我们商队的混蛋者，奖励500胡币。详情请咨询商人市场东北方的法戈商人布奇·哈里斯。}
