{100}{}{你已经逃出了监狱。现在你在废城绝对是个逃犯了！}
{101}{}{这扇门看起来很坚固，并且有一个结实的锁。不过，锁是可以撬开的，门也是可以被破坏的。}
{102}{}{门被锁住了。}
{103}{}{你打开了门锁。}
{104}{}{你锁上了门。}
{105}{}{你未能打开门锁。}
{106}{}{你未能锁上门。}
{107}{}{你因逃出监狱获得了250点经验值！}
