{100}{}{你看到凯恩。}
{101}{}{工作是什么？报酬多少？}
{102}{}{为这个破地方工作？你一定是在开玩笑。}
{103}{}{没错，看样子我得揍你一顿，仅此而已。}
{104}{}{抱歉，也许以后吧。}
{105}{}{不用了，谢谢。}
{106}{}{图克？}
{107}{}{看来报告有误，滚吧。我们不雇佣废物。}
{108}{}{这不是废物的工作。你需要快速干净地完成“它”。老板会告诉你细节，但这比你在商队一个月赚的还多，前提是你够好。我们不欢迎失败者，你懂我的意思。}
{109}{}{听起来不错。}
{110}{}{我现在不能。稍后再联系你。}
{111}{}{我要杀谁？}
{112}{}{不用了，谢谢。我不需要钱。}
{113}{}{我相信你对我们这种生意很熟悉，所以我只想说，最好把这事烂在肚子里。我们开始吧？}
{114}{}{希望你那只是个玩笑。别惹我们，否则你会后悔的。}
{115}{}{当然。那么这份“工作”涉及什么？}
{116}{}{好吧，随便你，硬汉。}
{117}{}{我想你没听懂我的意思。让我说明一下。如果你不注意你的态度，你会死的，硬汉。}
{118}{}{我想你没听懂我的意思。让我说明一下。如果你不注意你的态度，你会死的，硬妹。}
{119}{}{不，我来说明一下——如果你不注意，我会用你的屁股做鞋。}
{120}{}{好吧。我明白了。现在你想让我做什么？}
{121}{}{我稍后再找你。我得走了。}
{123}{}{哦，请便。我们会屏住呼吸等着。}
{124}{}{当然，祝你愉快。}
{125}{}{不需要钱？你肯定是在开玩笑，不过根据我听到的关于你的事，你可能会喜欢我为你准备的工作。}
{126}{}{真的吗？我可能会感兴趣，带路。}
{127}{}{不用了，谢谢。}
{128}{}{我稍后再联系你。}
{129}{}{是……你愿意跟我下楼吗？这里耳目太多。}
{130}{}{当然。}
{131}{}{没兴趣。}
{132}{}{现在不行，我会再找你的。}
{133}{}{离开，我没耐心。}
{134}{}{你珍惜你的生命吗？}
{135}{}{你已经有机会了，现在滚吧。}
{136}{}{你在找麻烦吗？}
{137}{}{你就是不长记性，是吧？你很快就会学会尊重。}
{138}{}{我听说过你。大家都说你是个狠角色。如果你在找工作，我可以帮你联系个人。你有兴趣吗？}
{139}{}{我听说过你。大家都说你是个狠角色。如果你在找工作，我可以帮你联系个人。你有兴趣吗？}
{140}{}{我听说过你。你就是在垃圾镇干掉基利安的人，干得漂亮。吉兹莫肯定给了你不少钱吧。你来集市有什么事，找工作吗？}
{141}{}{我听说过你。你就是在垃圾镇干掉吉兹莫的人。基利安肯定给了你不少钱吧。你是来找工作的吗？}
{142}{}{我听说过你。你就是那个干掉基利安和吉兹莫的狠角色。解决问题就该这样……那么，你来马耳他之鹰有什么事？找工作吗？}
{143}{}{我听说过你。你就是那个干掉基利安和吉兹莫的混蛋。解决问题就该这样……那么，你来马耳他之鹰有什么事？找工作吗？}
{144}{}{我听说过你。你现在可是小有名气。你来集市有什么事？}
{145}{}{我在找一个水芯片。}
{146}{}{我需要和德克谈谈。}
{147}{}{是你在经营这个地方吗？}
{148}{}{我是来揍你的。}
{149}{}{我想我现在得伤害你了。}
{150}{}{等我解决了你，你就不用担心健康问题了。}
{151}{}{我要净化这个邪恶的世界！}
{152}{}{我得走了，再见。}
{153}{}{就这样，再见。}
{154}{}{图克？}
{155}{}{巴鲁卡！}
{156}{}{水芯片？没听说过，我们只卖饮料。如果你饿了，去找鲍勃的鬣蜥肉吧。}
{157}{}{这是一种电子设备，用于调节水净化器的过滤系统，并监控输出是否有污染。我的坏了，我在找一个替换的。}
{158}{}{不，这是一个用于运行水净化器的小型机械部件。}
{159}{}{我还有个问题要问你……}
{160}{}{好的，谢谢。再见。}
{161}{}{我看起来像个商人吗？别浪费我的时间。}
{162}{}{你可以去找水商人。他们在商人市场的南边。你不会错过的，他们围着一个大水塔。}
{163}{}{你？这是我听过最好笑的事情。}
{164}{}{等我把你的脸重新安排一下，你就知道什么叫好笑了！}
{165}{}{等血流干了，看谁还在笑。}
{166}{}{你以为能打赢我？你可能很强壮，但这帮不了你躲子弹。}
{167}{}{你说得对，我很抱歉。请别开枪。}
{168}{}{我明白了。你得躲在枪后面，是吗？}
{169}{}{你真可怜。也许我现在就该给你脑袋上开个洞，结束你的痛苦。你说呢，想不想多一个洞在你那没脑子的头上？}
{170}{}{对不起。我真的不是故意的。请别开枪。}
{171}{}{你只能用枪对付我？你怕我不用枪就能打败你吗？}
{172}{}{怎么？怕我这个小女孩，非得用枪吗？}
{173}{}{当然。}
{174}{}{够了！如果你以为你知道什么是痛苦和折磨，等我收拾完你再说吧。}
{175}{}{把那条狗管好，不然它就死定了。}
{176}{}{别让你的朋友插手。}
{177}{}{让你的伙伴别插手，不然他们就死定了。}
{178}{}{退后伙计们，他是我的。}
{179}{}{退后伙计们，她是我的。}
{180}{}{你让我失望了，我以为你比这更强。}
{181}{}{躲？我不需要躲在任何东西后面，我也不需要枪来对付你。}
{182}{}{把那条狗管好，不然它就死定了。}
{183}{}{别让你的朋友插手。}
{184}{}{让你的伙伴别插手，不然他们就死定了。}
{185}{}{（对身后的人）退后伙计们，他是我的。}
{186}{}{（对身后的人）退后伙计们，她是我的。}
{187}{}{好大的口气，小子。这样吧，我把玩具收起来，看看谁能站到最后。}
{188}{}{好大的口气，小姑娘。这样吧，我把玩具收起来，看看谁能站到最后。}
{189}{}{对不起。我真的不是故意的。请别伤害我。}
{190}{}{来吧，放马过来。}
{191}{}{好吧，但我可不想让你哭。}
{192}{}{不，谢谢。我没时间，再见。}
{193}{}{你最好小心点，别在背后说这些话。你应该感激我这次如此宽容。希望下次再见。}
{194}{}{我会很享受的。}
{195}{}{把那条狗管好，否则它就死定了。}
{196}{}{让你的朋友别插手。}
{197}{}{让你的伙伴别插手，否则他们就死定了。}
{198}{}{（对着肩膀）退后，伙计们。她是我的。}
{199}{}{（对着肩膀）退后，伙计们。他是我的。}
{200}{}{净化？你真好，不过“邪恶”是很主观的。你认为邪恶的东西或人，别人可能正好相反。}
{201}{}{我同意，但这是否意味着我们因为不确定就什么也不做？}
{202}{}{这太荒谬了。邪恶就是邪恶。任何说不然的人都是愚蠢的。}
{203}{}{随便。我只是开玩笑。}
{204}{}{我当然希望如此。我们已经有足够的问题了，不需要一个盲目的狂热分子到处杀人。}
{205}{}{真遗憾。盲目的狂热分子确实很危险。希望你在集市的逗留不会太久。我们不喜欢未经授权的谋杀……任何形式的谋杀。祝好。}
{206}{}{不。}
{207}{}{好答案，白痴。谁负责？}
{208}{}{谁负责？}
{209}{}{白痴？你知道你在跟谁说话吗？为了你的安全，我希望你不知道。我不“经营”马耳他之鹰，但我是负责人。在我发火之前，你想要什么？}
{210}{}{我知道你是谁，相信我，你就是个白痴。}
{211}{}{哦，对不起。谁在管理这个地方？}
{212}{}{我们走着瞧。祝你“愉快”。}
{213}{}{如果你不知道，就不该问。这对你的健康不利。}
{214}{}{关于什么？}
{215}{}{一份工作。}
{216}{}{这是个秘密。}
{217}{}{这不关你的事。现在带我去见他。}
{218}{}{别得寸进尺，伙计，否则你会见到装在袋子里的德克。这边走，小心点。我会盯着你。}
{219}{}{别得寸进尺，女士，否则你会见到装在袋子里的德克。这边走，小心点。我会盯着你。}
{220}{}{我认为这确实关我的事，我也不认为我会带你去……如果你走运的话。现在滚开。}
{221}{}{抱歉，你要告诉Decker的事情可以直接告诉我。我是他的得力助手，这里发生的任何事情我们都心知肚明。}
{222}{}{关于一份工作。}
{223}{}{抱歉，我发过誓要保密。我只能告诉Decker。}
{224}{}{那么你就见不到他。}
{225}{}{谁派你来的？}
{226}{}{Beth派我来的。}
{227}{}{Lorenzo派我来的。}
{228}{}{Loxley派我来的。}
{229}{}{治安官派我来的。}
{230}{}{没有人。}
{231}{}{哪个Beth？}
{232}{}{你知道的。}
{233}{}{她没说。她经营武器店。}
{234}{}{别烦我。我没时间跟你玩游戏。}
{235}{}{那你谁也见不到。}
{236}{}{告诉我们亲爱的治安官Greene，Decker的日程有点忙，他应该几个月后再来。我很抱歉，但我想你应该离开……永远离开。}
{237}{}{我不认为她派你来的。请离开。}
{238}{}{哦？他们准备接受我们的保护了吗？你是他们中的一员吗？}
{239}{}{我不知道你在说什么。他只是提到Decker可能有工作给我。}
{240}{}{我？为那些小偷工作，绝不。我宁愿提防背后也不愿提防钱包。}
{241}{}{你保护我们？绝不！}
{242}{}{听着，伙计。我只是想找份好工作，干净又诚实的。}
{243}{}{是吗？那么你来错地方了，集市可不是什么诚实的地方。回到你来的地方吧，你会更快乐。}
{244}{}{我同意。那么，跟我来，我们看看你对我们有多大用处。记住，最好把听到的事情都烂在肚子里。}
{245}{}{可能吧。你是他们‘盗贼圈’的一员吗？}
{246}{}{是的。}
{247}{}{不是。}
{248}{}{那么很抱歉，我们不和你的小伙伴们合作。我们勉强容忍他们的存在，但绝不会和他们合作。}
{249}{}{那么，你可能还是有用的。记住，最好把听到的事情都烂在肚子里。}
{250}{}{他可能有。你在找什么样的工作？}
{251}{}{你需要再雇一个保镖吗？}
{252}{}{哦，没什么特别的。我只是好奇。}
{253}{}{任何事。如果报酬丰厚，我就干。}
{254}{}{任何不会让我惹上法律麻烦的事。}
{255}{}{你可以试试找商人。我听说他们的报酬还不错。}
{256}{}{不，我觉得我们够用了。祝你有美好的一天。}
{257}{}{这才是我喜欢听的。我想我们可能会成为朋友。让我带你下去。记住，最好把听到的事情都保密。}
{258}{}{很好，跟我来，但记住，最好把听到的事情都保密。}
{259}{}{当然，他说了，再见……哦，顺便说一句。别再对我撒谎，我不喜欢别人对我撒谎。不是很多人能活着听到这个忠告。}
{260}{}{行动派。我喜欢这一点，即使你脑子有点问题。}
{261}{}{行动派。我喜欢这一点，即使你脑子有点问题。}
{262}{}{是的，你想要什么？最好是有好理由。}
{263}{}{如果你想和我说话，最好把武器收起来。}
{264}{}{你记性不好吗？如果要和我说话，就把武器收起来。}
{265}{}{你的武器？}
{266}{}{不错，真不错，你让我惊讶。我没想到你这么难对付。我通常很会看人，也许你正是我们要找的人。你对工作感兴趣吗？}
{267}{}{该死！那是一场好斗！我很久没有这么好的对手了，我都不记得上次被谁打败了。干得好！你想不想要个工作？}
{268}{}{当然，是什么工作？}
{269}{}{不，谢谢。}
{270}{}{我现在不行。让我再考虑一下。}
{271}{}{这不是小角色的工作。你需要快速干净地完成它。老板会给你细节，但这比你在商队工作一个月赚的钱还多。我想你会做得很好。}
{272}{}{听起来不错，带路吧。}
{273}{}{嗯，我能考虑一下吗？我还有很多其他事情要处理。}
{274}{}{不，我不这么认为。}
{275}{}{当然，但请尽快告诉我。工作完成得越早越好。}
{276}{}{好吧，如果你改变主意就告诉我。我不想看到这样的才能浪费在护送商队上。}
{277}{}{太好了，我想事情会进展得很顺利。只要记住楼下听到的事情不要外传。好，我们走吧。}
{278}{}{我知道你对一位商人和他的妻子的死负有责任。我不知道你和他们有什么争执，我也不在乎。}
{279}{}{谁告诉你的？}
{280}{}{我不知道你在说什么。}
{281}{}{啥？}
{282}{}{这不是你该关心的事情。没有我们的允许，谁也不能对任何人下手。我建议你趁还能走的时候离开我们的城市。}
{283}{}{恐怕你确实知道，如果你为自己好，就该趁还能走的时候离开这个城市。}
{284}{}{我以为你不想接这个工作。我希望这只是个误会。我会付你一半的钱，你应该感激我还给你任何东西。[凯恩给了你1500胡币]}
{285}{}{谢谢。}
{286}{}{哦，抱歉，我以为我得到了这份工作。还有机会为你工作吗？}
{287}{}{现在把剩下的钱给我，否则你会后悔的！}
{288}{}{啥？}
{289}{}{我们走着瞧。楼下，德克想和你谈谈。}
{290}{}{你什么也得不到。}
{291}{}{我不知道你在玩什么把戏，但如果你为自己好，就该趁还能走的时候离开这个城市。}
{292}{}{你说过你不想要这份工作。我很惊讶你还回来。你自己动手是个大错误。我建议你趁还能走的时候离开这个城镇。}
{293}{}{我知道你对高阶祭司简的死负有责任。我不关心你和她有什么争执，但我们非常感激。（凯恩给了你1000胡币）}
{294}{}{谁告诉你的？}
{295}{}{我不知道你在说什么。}
{296}{}{啥？}
{297}{}{这不关你的事，恐怕我们不能和你打交道。你违反了我们的法律，但因为你为我们解决了一个问题，我们不会杀你，但我认为你应该离开。}
{298}{}{恐怕你知道，撒谎可能是个很不健康的习惯。你违反了我们的法律，但因为你为我们解决了一个问题，我们不会杀你，但我认为你应该离开。}
{299}{}{我不知道你在玩什么把戏，但我不觉得好笑。你违反了我们的法律，但因为你为我们解决了一个问题，我们不会杀你，但我认为你应该离开。}
{300}{}{别碰那扇门，如果你想活命。我是唯一能打开那扇门的人。}
{301}{}{商人和他的妻子住在这里的西边。他们住在高地的交易街与雷霆大道的拐角处，他可能会有保镖。尽量安静些，确保没人看到你，但如果有人看到你，确保他们活不下来告诉别人。完成你的任务后回来。还有一件事，别想着去找警察，那是你能犯的最大错误。如果可以，尽量不要在工作时引起他们的注意，他们有时会很麻烦。[凯恩给了你500瓶盖]}
{302}{}{干得好。这是你完成第一个任务的报酬。[凯恩给了你2500胡币]}
{303}{}{商人那边干得不错。我期待你下一个任务也有同样的结果。这是你第一个任务的最后一笔付款和第二个任务的第一笔付款。（凯恩给了你3500胡币）我相信你已经知道了，但大教堂的孩子们在南边，就在水商人北边。再次提醒，没有“活着”的目击者。}
{304}{}{你急着要离开吗？你还没拿到你的报酬。这是你的钱，初始付款和第一个任务的完成奖金。（凯恩给了你3000胡币）}
{305}{}{嘿，干得好！你忘了拿你的初始付款，所以这里是连同完成费用一起的。你证明了自己很有用。}
{306}{}{（凯恩给了你5000胡币）}
{307}{}{这就是你能得到的全部。现在走吧，否则你会后悔的。}
{308}{}{这是你的起始报酬。（凯恩给了你1000胡币）我相信你已经知道了，但大教堂的孩子们在南边，就在水商人北边。再次提醒，没有“活着”的目击者。}
{309}{}{该死，这是一大笔钱。德克真的想要那女人死，这里是你的报酬。（凯恩给了你4000胡币）你证明了自己很有用。}
{310}{}{你到底想要什么？我以为你不想见德克。}
{311}{}{没有，我没见过他，不过你能帮我传个话吗？}
{312}{}{是的，我想见他，然后在他脑袋上开个洞！}
{313}{}{抱歉，我误解你了。}
{314}{}{没错，我为什么要见那种蠢货！}
{315}{}{咕噜。}
{316}{}{塔？}
{317}{}{我们不雇佣废物。现在离开这里，别让我对你感到厌烦。}
{318}{}{这要看是什么消息。}
{319}{}{告诉他，他就是个窝在洞里的胆小鬼。如果他想做个男人，就该出来面对现实世界。}
{320}{}{告诉他开始祈祷奇迹吧，因为等我找到他，他会需要的。}
{321}{}{我忘了。}
{322}{}{告诉他，他是我的偶像，我很欣赏他的工作。}
{323}{}{告诉他，我会对他做和他对上一个掌管这里的人一样的事！}
{324}{}{是吗？那应该会很有趣。}
{325}{}{你是个白痴。}
{326}{}{你是什么怪胎吗？滚出去！}
{327}{}{哦，我一定会告诉他的。我相信他会很感兴趣……你说祈祷？我给你‘保证’，他会收到消息。}
{328}{}{我以为我让你滚蛋了！我的耐心快耗尽了！你到底要不要告诉我你为什么想见德克？}
{330}{}{我没必要告诉你。}
{331}{}{抱歉，我只是想找份工作。}
{332}{}{我告诉过你，这是个秘密！}
{333}{}{不告诉你！}
{334}{}{如？}
{335}{}{等你戒了化学品再来找我。}
{336}{}{我会让你见他，但你最好管好你的嘴……请。}
{337}{}{不，你不需要。再见。}
{338}{}{这是个你要带到坟墓的秘密。德克永远不会跟你这种废物说话。}
{339}{}{那我建议你离开。}
{340}{}{什么事？}
{341}{}{洛伦佐让我来找工作。}
{342}{}{你好！}
{343}{}{我想找份工作。}
{344}{}{没事，再见。}
{345}{}{克鲁。}
{346}{}{你好。}
{347}{}{你怎么样？}
{348}{}{再见。}
{349}{}{很好。}
{350}{}{孩子们怎么样？}
{351}{}{今天天气不错吧？}
{352}{}{你今天看起来很帅。}
{353}{}{再见……（凯恩眯起眼睛，好像在猜测你在打什么主意。）}
{354}{}{我想也是。（凯恩开始用奇怪的眼神看着你）}
{355}{}{你知道现在几点吗？}
{356}{}{婆罗门鞋子很好吃。}
{357}{}{没有……你想要什么？（凯恩似乎对你有些不耐烦）}
{358}{}{是的。}
{359}{}{不是。}
{360}{}{我觉得你需要再喝一杯，伙计。}
{361}{}{我觉得你需要再喝一杯，女士。}
{362}{}{（凯恩等了几秒）那么……是什么事？（凯恩看起来非常恼火）}
{363}{}{什么是什么？}
{364}{}{我忘了。}
{365}{}{哦，没什么。}
{366}{}{（看起来凯恩的耳朵里快冒出蒸汽，脖子上的血管似乎在跳动。）滚出去！ （几秒钟后你才恢复听力。）……这里！你这个白痴！}
{367}{}{（凯恩咬紧牙关，忽视了你。）}
{368}{}{你忘了？（叹气）为什么我一点也不惊讶？（不敢相信地摇头。）现在……滚出去！}
{369}{}{（凯恩看向一个守卫，用手指在耳边转圈。）}
{370}{}{你到底在说什么鬼话？}
{371}{}{这不是正确的回答！}
{372}{}{我明白了……你不是他们中的一员。}
{373}{}{回应……回应什么？（凯恩看起来困惑且略显恼怒。）}
{374}{}{对秘密密码的回应！}
{375}{}{抱歉，我不能谈论这个。再见。}
{376}{}{（凯恩看起来很生气，你不知道为什么。）滚出去，你这个疯子。}
{377}{}{（凯恩看起来很生气。你不知道为什么。）滚出去，你这个疯女人。}
{378}{}{我叫你滚出去，你这个疯子。}
{379}{}{我叫你滚出去，你这个疯女人。}
{380}{}{不，我想不是。现在走吧。（他看起来一点也不高兴。）}
{381}{}{我没有孩子！}
{382}{}{你似乎对此有些不满。你想谈谈吗？}
{383}{}{你应该有，他们是很好的仆人。}
{384}{}{玛丽可不是这么说的。}
{385}{}{真的吗？这很奇怪……非常奇怪……}
{386}{}{什么？你……我……不！我不想谈论这个。你以为你是谁？滚出我的视线。}
{387}{}{我说过，我不想谈论。}
{388}{}{呃，是的。好吧，伙计。你说什么就是什么。}
{389}{}{呃，是的。好吧，女士。你说什么就是什么。}
{390}{}{那么你有要卖的吗？}
{391}{}{那好吧。再见！}
{392}{}{（凯恩看了看他的一名打手，耸了耸肩）}
{393}{}{我没有！现在，离开。}
{394}{}{玛丽？我不认识什么玛丽……我没时间管这个！我甚至不知道你在说谁。如果她想要钱，让她自己来找我！}
{395}{}{（你因为彻底激怒凯恩而获得100点经验。）}
{396}{}{（你一瞬间觉得凯恩脸红了）那是……（他左右看了看）不错。你想要什么。}
{397}{}{约个会怎么样？}
{398}{}{哦，没什么。再见。}
{399}{}{是的，我是说不。我是说我不……我不能。我……（凯恩突然打了他的一名保镖一拳。）你笑什么！ （然后他回头看着你。）你还在这里干什么！}
{400}{}{（凯恩无视你）你想要什么？}
{401}{}{孩子们怎么样？}
{402}{}{天气不错，不是吗？}
{403}{}{这边走。}
{404}{}{你知道路，走吧。}
{405}{}{开门，伙计们。}
{406}{}{好的。}
{407}{}{行。}
{408}{}{你想要什么都行，现在走开。}
{409}{}{你还有其他工作吗？}
{410}{}{嗨！}
{411}{}{没事，再见。}
{412}{}{阿克鲁！}
{413}{}{又见面了。}
{414}{}{什么？你没胆子，对吧？（他低声对你说）别担心，你会习惯的。如果他有保镖，试着等他们走。毕竟他们也得吃饭，对吧？如果可以，分散他们的注意力。不管用什么方法，我们不接受失败。只要完成任务，你就能拿到钱，然后赶紧离开这里。现在……你真的需要什么吗？}
{415}{}{为什么‘它’还没完成。你最好快点完成。我不想再见到你，除非你带来好消息，否则我们会有麻烦。你最好别让我们失望。}
{416}{}{就是这样。你犯了最后一个错误。你最好现在就离开镇子，如果不想被埋在这里……六英尺下。}
{417}{}{那么……你要做这件事吗？他们就在这里。（凯恩再次指向你的PIPBoy城镇地图显示。）你最好快点，老板希望这件事尽快完成。}
{418}{}{这到底是怎么回事……（凯恩环顾四周，然后低声说。）你在这里干什么？你最好把另一个解决掉，而且最好没有‘任何’目击者。}
{419}{}{就是这样。你搞砸了。现在你得为你的错误付出代价。我希望你没打算在这里过夜。}
{420}{}{你还没完成你的任务。（低声）你知道这里的利害关系。完成它你就能发财，我们都会很高兴。失败了就没人会高兴。}
{421}{}{如果你在任务上遇到麻烦，试着等她单独一人。}
{422}{}{你的时间不多了，而我的耐心也快用完了。}
{423}{}{我不干。}
{424}{}{她很快就会死。}
{425}{}{嗯。}
{426}{}{你不干？真遗憾。我们不能让人言而无信。很遗憾我们不能合作。祝你‘愉快’的一天。}
{427}{}{好吧！我会做这该死的工作。但你最好在我完成后准备好钱。}
{428}{}{谢谢。}
{429}{}{哦，我会准备好的。别担心。}
{430}{}{看来你还活着！嗯，你最近一定没交新朋友。我希望你多加小心。}
{431}{}{（凯恩看起来非常得意。他只是站在那里，露出邪恶的笑容。）}
{432}{}{哦！真没想到还能见到你活着回来。你竟然活下来了，真是令人印象深刻。我想我会让你活命，你值得拥有这个机会。现在赶紧走吧。}
{433}{}{别想了。}
{434}{}{我从不失手。}
{435}{}{我让你活命，心存感激吧。}
{436}{}{我想你不想试探我的底线。}
{437}{}{"为了你好，希望你没打算用那个。}
{438}{}{你该离开了。}
{439}{}{别犯傻。}
{440}{}{你会后悔的。}
{441}{}{你要么是勇敢，要么是非常愚蠢才敢在这里露面，不过别担心，我们会找时间来“问候”你的。}
{442}{}{（凯恩只是瞪着你。）}
{443}{}{你居然活着离开了我的告别派对……我不知道你是怎么做到的，我一定是低估了你。离开这里，你或许还能活命。}
{444}{}{（凯恩无视你，但他的武器已准备好射击。）}
{445}{}{好了！快出去！}
{446}{}{我不会再说第二遍。滚出去。}
{447}{}{我警告过你。好了伙计们，给他们点颜色看看！}
{448}{}{我警告过你。好了伙计们，给她点颜色看看！}
{449}{}{别打扰我，去工作。你有任务要做，最好做好。}
{450}{}{赶紧去做。我已经告诉你该做什么了。快去做。}
{451}{}{我知道你完成了该死的任务。你不用告诉我。你需要去找德克谈。}
{452}{}{我告诉过你去找德克！}
{453}{}{（凯恩给了你一个致命的眼神。）好吧……我会尽快安排你见他。我会确保把你“分段”展示给他。}
{454}{}{很遗憾你有这样的感觉。希望你能“享受”在我们这座美丽城市的余下时光。}
{455}{}{（凯恩无视你。）}
{456}{}{（凯恩盯着你看了几秒）好吧。我给你最后一次机会见他。跟我来。}
{457}{}{（凯恩盯着你看了几秒）你错过了机会。滚吧。}
{458}{}{你到底回来干什么？！你比我想象的还要愚蠢。我早就知道德克不该雇佣一个无名之辈。}
{459}{}{你在说什么？}
{460}{}{嗯？}
{461}{}{[凯恩压低声音] 你搞砸了任务，你这个白痴！你本该杀掉所有海塔家的人，而不是让他们受伤！你一离开高地，他们就和保镖一起跑了。相信我，他们连收拾东西都没浪费时间。天知道他们现在在哪！}
{462}{}{唉，我能说什么呢？我很抱歉。}
{463}{}{呃，抱歉。}
{464}{}{道歉没有用。你让德克陷入了不可接受的风险。从现在开始，你就是地下组织的敌人。我再也不想在这里看到你。}
{465}{}{有凯恩在，你无法通过这扇门。}
