{100}{}{你看到一个疲惫的旅行者。}
{101}{}{你看到兰斯，来自阴影沙地的远程巡逻队的守卫之一。}
{102}{}{就待在那儿别动。我们在阴影沙地听说过你，我们不想和你有任何瓜葛。}
{103}{}{我只对你身上的东西感兴趣。脱光。}
{104}{}{我是个爱好和平的人，朋友。}
{105}{}{嘿，我不是救了坦迪，还消灭了你们的辐射蝎子吗？}
{106}{}{我和阴影沙地没有任何纠纷。我还挺喜欢那地方的。}
{107}{}{赫隆？}
{108}{}{我听说过你，我可不会让你杀了我。}
{109}{}{我没什么好对你说的。}
{110}{}{是吗？这次你想要什么？}
{111}{}{你知道哪里能找到水芯片吗？}
{112}{}{有看到坦迪的踪迹吗？}
{113}{}{最近有遇到袭击者的问题吗？}
{114}{}{阴影沙地的情况怎么样？}
{115}{}{嗯哼！}
{116}{}{你好，陌生人。是什么把你带到了荒野？你从哪里来？}
{117}{}{我也可以问你同样的问题。}
{118}{}{抱歉，朋友，但我觉得这是个相当危险的问题。}
{119}{}{知道哪里有好地方可以补给吗？}
{120}{}{我来自一个避难所。幸运的13号避难所！}
{121}{}{哇？}
{122}{}{你好，陌生人。我建议你继续前行，如果你知道对你有好处的话。}
# TRANSLATION NOTE
# After line 123, the player-character's name is inserted by the code, and
# then line 124 or line 131 is added.
{123}{}{你好，}
{124}{}{。我以为你救了坦迪就是我们的朋友，但现在我听到一些关于你的可怕传闻。是真的吗？}
{125}{}{人们说什么都有。谁在乎呢？}
{126}{}{我不是你的朋友。如果你敢乱来，我就让你肠子流一地。明白了吗？}
{127}{}{什么样的传闻？}
{128}{}{是的，都是事实。现在脱光让我拿走你所有的东西。}
{129}{}{也许我做过一些后悔的事，但你应该知道不要相信那些胡说八道。}
{130}{}{. 真高兴是你而不是某个掠夺者！最近怎么样！我是兰斯，阴影沙镇的守卫之一。抱歉你刚来镇上时我们对你态度不好！}
{131}{}{嗨，兰斯，最近怎么样？}
{132}{}{嗨，兰斯。我曾经是个好人，但生活让我变了。现在，把你的东西交出来。}
{133}{}{别介意，兰斯。你一个人在这里做什么？}
{134}{}{好吧。但我会记住这件事的。}
{135}{}{去你的。}
{136}{}{省省你的威胁吧，小子。我睡觉时都能杀掉你这样的孩子。交出你的东西，我可能会让你活命。}
{137}{}{如果你真觉得我是个威胁，那就动手吧。}
{138}{}{来吧，让我们做个错误的决定。我一直想看看我的内脏长什么样。}
{139}{}{那是过去的事了，现在是现在。你最近为我们做了什么？我看你最好离开这儿，免得我发火。}
{140}{}{我们也喜欢这里，尤其是当你不在的时候。现在滚吧！}
{141}{}{伙计，你肯定是在辉光待太久了！}
{142}{}{我不知道水芯片是什么。抱歉。}
{143}{}{那是用于水净化系统的电子设备。}
{144}{}{蝎子的问题怎么样了？}
{145}{}{掠夺者抓走了她。我是搜索队的一员。我想她在阴影沙镇南边的掠夺者营地，但可汗把那里封得像个堡垒。}
{146}{}{你能带我去阴影沙镇吗？}
{147}{}{你能带我去可汗营地吗？}
{148}{}{我们得想办法把她救回来。}
{149}{}{谢谢你的信息。祝你们搜索顺利。}
{150}{}{呃，是的，但自从可汗吃了亏后，我们处理得好多了。我知道这要感谢你。我们很感激。}
{151}{}{我不介意看到一点感激之情。}
{152}{}{谢谢。还有什么我能帮忙的吗？}
{153}{}{如果他们再烦你，告诉我。}
{154}{}{我们还不错。}
{155}{}{你确定吗？}
{156}{}{那太好了。}
{157}{}{我一点头绪都没有。笨蛋。}
{158}{}{好吧，我相信你。我来自阴影沙镇。我们是离这不远的一个社区。}
{159}{}{你能带我去那里吗？}
{160}{}{这个小镇怎么样？}
{161}{}{那里有水芯片吗？}
{162}{}{听起来是个不错的地方。}
{163}{}{好吧，你有你的秘密，我也有我的。再见。}
{164}{}{也许是吧。不过真是可惜。}
{165}{}{我去过废城。我想它在这里的西南方向，但我已经旅行了很多天，很难确定。}
{166}{}{是啊，对。就我所知，所有的避难所都被毁了。再给我编一个吧。}
{167}{}{这不是我想问的……哦，算了吧！}
{168}{}{这不是答案。他们叫你刺客、贼、盗墓者。他们说你会杀掉任何挡路的人。是真的吗？}
{169}{}{好吧，我还没杀你，所以显然有人在撒谎。}
{170}{}{差不多。我也有过不少好时光。}
{171}{}{我也结下了不少仇敌。我留下了足够多的人活着来诽谤我。}
{172}{}{是的，我确实杀过不少人。我总是有理由的。}
{173}{}{他们叫你刺客、贼、盗墓者。他们说你会杀掉任何挡路的人。是真的吗？}
{174}{}{好吧，我会去做。但如果你继续像掠夺者那样行事，你就会像掠夺者一样死去。}
{175}{}{暂且相信你一次。但一个人的价值取决于他的声誉，而你的声誉需要改善。我希望在我们下次见面之前你能有所改变。}
{176}{}{正要回镇上。你想一起吗？我需要个伴。}
{177}{}{当然。}
{178}{}{今天不行。}
{179}{}{稍微搜刮了一下。我们找到了一些还没被清理干净的废弃掠夺者基地；我怀疑他们在互相攻击。我们总是需要更多的弹药和化学药品。}
{180}{}{我会后悔的。}
{181}{}{在我清醒过来之前，赶紧从我眼前消失。}
{182}{}{我们还是能看到一些；他们可能是从高地沙漠或辉光迁徙过来的。但现在比去年好多了，多亏了你。}
{183}{}{听起来不错。再见。}
{184}{}{当然。走吧。}
{185}{}{天啊，我一定是疯了。但我会带你。走吧。}
{186}{}{祝你自杀愉快，朋友。无论如何，祝你好运。}
{187}{}{我要出发了。你自己保重。}
{188}{}{我没有多少东西，但我的就是你的。}
{189}{}{我想不出什么。我要出发了。你自己保重。}
{190}{}{我们会的。我该走了。你自己多保重。}
{191}{}{好吧。我们走吧。}
{192}{}{我不会把可能的敌人带回家。如果你真的去阴影镇，记得安分守己。}
{193}{}{地方很小。我们靠放牧辐射双头牛为生。这里的环境相当艰苦，牧场地非常珍贵。}
{194}{}{在一个放牧辐射双头牛的偏远地区？你一定疯了！方圆两百英里内可能都没有一件能用的电子设备。}
{195}{}{你说得对。我认为我们应该谨慎行事，各走各的路。如果我是你，我会处理那些传闻。除非你喜欢被人憎恨和不信任。}
{196}{}{我现在就该杀了你。下次再让我遇到你，我一定会动手。现在滚。}
{197}{}{走吧。}
{198}{}{让我猜猜，是不是有人告诉你我打呼噜的事。好吧。你自己多保重。}
{199}{}{是的。我该走了。你自己多保重。}
{200}{}{就待在那儿别动。我不知道你是不是和那些变种人一伙的，但如果是，我会杀了你。}
{201}{}{什么变种人？}
{202}{}{你是谁？}
{203}{}{你发生了什么事？}
{204}{}{好吧，没问题。}
{205}{}{呃，什么？}
{206}{}{变种人攻陷了阴影镇。我们大多数人都死了。我想他们迟早会把我们剩下的人也解决掉。}
{207}{}{我不在乎你说什么，问什么。我们都完了！所有人！我还以为袭击者和辐射蝎子已经够糟了……他们根本不算什么！哈！哈哈哈！}
{208}{}{闭嘴！我不想说话！说话什么都解决不了！说话只会让我觉得无聊……}
