{100}{}{你看到劳拉。}
{102}{laura0m}{Hello, my brother. May I be of service this glorious day?}
{104}{laura0f}{Hello, my sister. May I be of service this glorious day?}
{105}{}{你是劳拉吗？}
{106}{}{我可以问你几个关于“儿童会”的问题吗？}
{107}{}{你提供什么样的“服务”？}
{108}{}{妈妈？}
{110}{laura01a}{That's very sweet of you, but no, I'm not.
 I'm sure you can find her somewhere else.}
{112}{laura2}{I most certainly am.  Did you want something?}
{113}{}{妮可让我来找你。}
{114}{}{呃……没什么。算了。}
{116}{laura3}{Nicole? I'm so sorry. I don't believe I know anyone by that name.}
{117}{}{好了，她让我跟你说‘红骑士’。}
{118}{}{当然相信！她派我来的！}
{120}{laura4}{I'm sorry. I . . . I just don't know.
 Follow me to a place where we can talk.}
{122}{laura9}{I'm terribly sorry for your inconvenience. I hope it doesn't upset you.}
{124}{laura10}{Are you . . . certain? Uh . . . excuse my curiosity,
 but you seemed to be looking specifically for me.}
{125}{}{确实是妮可让我来的。}
{126}{}{只是听说过你，想看看你的样子。}
{128}{laura11}{I . . . I'm sorry, but that sort of attention
 makes me a little nervous. Don't know why,
 it's silly of me, I know. Well, enjoy your walk.}
{130}{laura14}{Oh, I'm hardly an authority. You should see Morpheus,
 the High Priest. I'm sure he can help you much more than I.}
{132}{laura15}{But I only meant . . . oh . . . I have to go now.}
{134}{laura16g}{Well, hello again! Are you just walking or may I help?}
{136}{laura16b}{Is there . . . something I can help you with?}
{137}{}{你是劳拉吗？}
{138}{}{我可以问你几个关于“儿童会”的问题吗？}
{139}{}{没什么，谢谢。}
{140}{}{呃，妈妈？}
{142}{laura16a}{No. We already talked about this. You'll have to go
 somewhere else my friend.}
{144}{laura21}{Oh . . . I'm glad you found me. Nicole sent a list with the
 information I was supposed to find.}
{145}{}{你得到了什么？}
{147}{laura22}{Um.  There's so much I'm just . . . I'm not sure what
 you need or where to start. Is there
 something in particular you want to know about?}
{148}{}{教会的内殿有秘密入口吗？}
{149}{}{你对“主宰者”有什么了解？}
{150}{}{“儿童会”的计划是什么？}
{151}{}{像你这样的好女孩怎么会在这种地方？}
{152}{}{没有其他问题了，谢谢。}
{154}{laura24}{It's not the Inner Sanctum you want to enter.}
{155}{}{然后呢？}
{157}{laura25}{I followed Morpheus down a back secret staircase.
 The guy activates a secret door at the bottom.}
{158}{}{然后呢？}
{159}{}{你能带我看看这扇门吗？}
{161}{laura26}{He uses this strange key to open it and
 disappears. I've never tried to follow him.}
{162}{}{你知道这个钥匙在哪里吗？}
{163}{}{为什么不？}
{165}{laura27}{Well, I'd say he keeps it on him.}
{166}{}{你现在能带我去看门了吗？}
{168}{laura28a}{Well, of course.}
{169}{}{太好了。我们走吧。}
{170}{}{我能先再问几个问题吗？}
{172}{laura29}{Follow me.}
{174}{laura30a}{Okay, but we have to hurry.}
{176}{laura30b}{Oh, make it quick.}
{178}{laura31}{Believe me, if you've seen the Nightkin,
 you'd know why. Unless you're stupid.}
{179}{}{可能我是，但我并不害怕。}
{180}{}{我能理解。我们能回到问题上来吗？}
{182}{laura32}{Oh, I see that's real funny. Lookit, I'm in the
 middle of this day in and day out.
 You have a problem with how I do this,
 you just keep it to yourself. Ya got it?}
{183}{}{你打算怎么做，再抱怨一会儿吗？}
{184}{}{如果你想这样的话。}
{185}{}{你说得对，我很抱歉。我们回到正事上来怎么样？}
{187}{laura33}{Uh, not much. The Children worship him, and sometimes
 a huge vision of him appears in the main nave of the church.}
{188}{}{所以他是真的？}
{189}{}{听起来很吓人。}
{191}{laura34}{Yes and no. I snuck up to the front one day
 and found a strange mechanical device with a lens under the altar.}
{192}{}{可能是某种全息投影仪。}
{193}{}{然后呢？}
{195}{laura35}{Huh . . . believe me, it was at first, but then I
 snuck up and looked at the alter when nobody was
 looking. And there's a device underneath with
 wires and a big lens.}
{196}{}{可能是某种全息投影仪。}
{197}{}{然后呢？}
{199}{laura36}{So I'm pretty sure this Master is flesh and blood.
 And I also think I know where he is.}
{200}{}{在哪里？}
{202}{laura37}{Every once in a while, Morpheus will go through a
 secret staircase leading below the Church. And he
 enters a secret door with some kind of key. I think
 the Master is down there.}
{203}{}{你能现在就带我去看这个楼梯吗？}
{204}{}{你知道这个钥匙在哪里吗？}
{206}{laura38}{Now that's scary. Morpheus is preaching that the
 earth should be 'purged of the infidels,' and
 other crap like that. I think they're planning
 to take over everything!}
{207}{}{他们能做到吗？}
{208}{}{他们的第一个目标是什么？}
{210}{laura39}{Now you know, it could be. I mean, they have
 enough members, and the different hospitals
 in the towns are stocked full of weapons and explosives.}
{211}{}{我们必须告诉追随者。}
{212}{}{你打算怎么做？}
{214}{laura40}{I was planning on it. In fact, after we're done,
 I'm heading over there.}
{215}{}{能问个问题吗？}
{216}{}{那我就让你走吧。}
{218}{laura41}{Okay. Good luck!}
{220}{laura42}{Well, I'm going to go warn Nicole.
 And hopefully, the Followers can send help to the other towns.}
{221}{}{我想先问几个问题。}
{222}{}{好吧，那我就让你走吧。}
{224}{laura43}{Adytum, that town doesn't have a chance in hell.}
{225}{}{追随者怎么样了？}
{226}{}{我能帮阿迪图姆吗？}
{228}{laura44}{The Children don't think we're enough of a threat.
 We'll show 'em.}
{229}{}{很好。你打算怎么做？}
{230}{}{我能以任何方式帮助阿迪图姆吗？}
{232}{laura45}{Yeah, you can help 'em by getting to the Master. 'Bite the
 head off the snake and it won't coil around you,' as my grandmother used
 to say. She was kind of a handful.}
{233}{}{我怎么能找到他？}
{234}{}{听起来是。我需要更多答案，然后你再走。}
{235}{}{我这就去。}
{237}{laura46}{They plan to take over all the towns!}
{238}{}{哪些？}
{240}{laura47}{Adytum's already fallen. The Hub is next.}
{241}{}{追随者在这期间做什么？}
{242}{}{该死。我能做些什么？}
{244}{laura48}{We sent a group to help Adytum,
 and they were all wiped out. Nicole sent another
 one to the Hub. I just hope they get there in time.}
{245}{}{该死。我能做些什么？}
{247}{laura49}{They've already taken out the Hub and Adytum!
 I think the Followers are next, so we're preparing our defense.}
{248}{}{那你为什么在这里？}
{249}{}{我能做些什么？}
{251}{laura50}{I'm here to keep an eye on the Children.}
{252}{}{我能做些什么？}
{254}{laura51}{The Children are setting up hospitals all over the place.
 Hmpf. I think they're trying to get people to trust them.}
{255}{}{有效吗？}
{256}{}{有没有办法阻止他们？}
{257}{}{这是我听过最愚蠢的事情！}
{259}{laura52}{Ah, it sure looks that way. I mean, people are flocking to their
 Church. Can't they see it's a fake?}
{260}{}{你确定吗？}
{261}{}{我该如何阻止他们？}
{263}{laura53}{For one thing, people seem to disappear a lot
 around here, while the number of Nightkin are slowly growing.}
{264}{}{为什么？}
{265}{}{情况不妙。但在行动前我需要更多答案。}
{267}{laura54}{I don't know. That's what you're here to find out, right?}
{269}{laura55}{Find the Master and stop him!}
{270}{}{你发现了关于这个Master什么信息？}
{271}{}{我会的。}
{273}{laura56}{Huh, I sure as hell hope so. Now, any more questions? }
{275}{laura57}{Actually, it's a good way to manipulate people,
 and this Master is damn good at it.}
{276}{}{不，我的意思是这是我从你这听过最愚蠢的事情。你是不是有点偏执？}
{277}{}{好吧，我会阻止他的。}
{278}{}{我该如何阻止这一切？}
{280}{laura58}{Excuse me?}
{281}{}{你听到了。}
{282}{}{算了。}
{284}{laura59}{Okay then. Good luck!}
{286}{laura60}{Uh heh . . . Waiting desperately for someone to
 use that pathetic line on me.}
{288}{laura61a}{So, what can I do for you now?}
{290}{laura61b}{Oh, what now?}
{291}{}{我需要再问你几个问题。}
{292}{}{没什么，谢谢。}
{294}{laura62}{What are you doing? Put that down!}
{296}{laura63}{Hey! Get out of here!}
{297}{}{否则呢？}
{298}{}{抱歉，我这就走。}
{300}{laura64}{Stop that!}
{302}{laura65}{What . . . what are you doing in here? You need to leave!}
{303}{}{不，你出去！}
{304}{}{好吧，我走。}
{306}{laura67}{Uh . . . I'm not sure about that. Go talk to Nicole.}
{308}{laura67a}{I'm not sure about that. Go talk to a High Priest.}
{309}{}{嗯，正如我所说……}
{310}{}{我说过……}
{311}{}{嗯，正如我之前所说……}
{312}{}{正如我之前所说……}
{313}{}{嗯，我很确定我已经告诉过你了，但是……}
{314}{}{好吧！我已经告诉过你了……}
{315}{}{再来一次？好吧，我说过……}
{316}{}{又来？我已经说过了……}
{317}{}{哦天哪，这真是令人不安。我绝不会再说了。}
{318}{}{你是……好吧！好吧！你是聋子吗？看我的嘴型，我不会再说了。}
{319}{}{我觉得已经够了。我不会再说了。}
{320}{}{不听是吧？太糟糕了，我不会再说了。}
{321}{}{哦，那些人真是可怕。我根本不想谈论他们！}
{322}{}{妮可可能已经告诉过你关于我们的事。我们正在努力让那些头脑顽固、持枪好斗的蠢货清醒过来……哦，当然不包括在座的各位。}
{323}{}{嗯，我不知道你在说谁。}
{324}{}{她领导着追随者。意志坚定，我信任她。}
{325}{}{其他人都很好！这里太棒了。我们属于这里，我们做有意义的工作……}
{326}{}{哦，他们就像是……世界上的一场灾祸。大多数都是废物，少数则是纯粹的邪恶。}
{327}{}{阿迪特姆，那不是在这里西边的一个镇吗？}
{328}{}{阿迪特姆在这里西边一点。那里的人……嗯，他们有点偏执，所以别指望能受到热情的欢迎。}
{329}{}{哦，他很棒。他领导着我们。你应该去跟他谈谈！}
{330}{}{他宣扬和平和启蒙之类的废话，但他是个败类。毫无疑问。}
{331}{}{哦，我无法形容他。墨菲斯领导着我们。他能回答你的问题。}
{332}{}{啊，是的，主人，他是这些疯子崇拜的神。我个人认为他不是神，只是一个操纵所有人的家伙。}
{333}{}{夜行者？我不知道你在说什么。}
{334}{}{他们是主和墨菲斯的大块头丑陋的执行者。}
{335}{}{什么？}
{336}{}{什么，你看不出来那就是主吗？}
{337}{}{那是教堂北端的大地方，墨菲斯在那里举行所有的仪式。我去过那里，太棒了！}
{338}{}{它在教堂的北端。我看过墨菲斯在那里表演他的那套小把戏。}
{339}{}{哦，你不能去那里。那是墨菲斯沉思的地方。}
{340}{}{那是墨菲斯和他的同伙们闲逛的地方。不过没人被允许上去。}
{341}{}{他们已经向教会证明了自己。我们其他人都渴望达到那样。}
{342}{}{哦对，这些人经历了酷刑和不知道还有什么。完全被洗脑，听命于任何指令。}
{343}{}{他们是高级祭司。}
{344}{}{啊，那些是大祭司。目前我想只有13位，但我不太确定。}
{345}{}{这不重要。}
{346}{}{这不重要。}
{347}{}{抱歉，我实在没有时间处理这个。}
{348}{}{我们没有时间讨论这个！专注于正事。}
{349}{}{我不确定你为什么想谈论这个。}
{350}{}{朋友，请专注于当前的话题。}




#
# Laura Tell-Me-Abouts
#


{1000}{}{追随者}
{1001}{}{妮可}
{1002}{}{大教堂}
{1003}{}{墨菲斯}
{1004}{}{主宰}
{1005}{}{夜行者}
{1006}{}{黑暗}
{1007}{}{礼堂}
{1008}{}{圣殿}
{1009}{}{侍奉者}
{1010}{}{秩序}
{1011}{}{末日}
{1012}{}{神}
{1013}{}{变种人}

{1100}{laura74}{Oh, those are dreadful people. I'm not going to talk about them at all!}
{1101}{laura75}{Well, I don't know who you're talking about.}
{1102}{laura76a}{The others are all so nice! It's wonderful here.  We belong, we do good work . . .}
{1103}{laura78}{Oh, he's wonderful. He leads us. You should talk to him!}
{1104}{laura79}{Oh, I can't begin to describe him. Morpheus leads us.
 He can do justice to your question.}
{1105}{laura80}{Nightkin? I don't know what you're talking about.}
{1106}{laura81}{The what?}
{1107}{laura82}{It's the big place at the north end of the church,
 where Morpheus does all his ceremonies. I've been there, it's wonderful!}
{1108}{laura83}{Oh, you cannot go there. That's where Morpheus contemplates.}
{1109}{laura84}{They have proven themselves to the Church. The rest of us aspire to that.}
{1110}{laura85}{They are the high priests.}
{1111}{laura74}{Oh, those are dreadful people. I'm not going to talk about them at all!}
{1112}{laura81}{The what?}
{1113}{laura80}{Nightkin? I don't know what you're talking about.}