{100}{}{你看到一个食尸鬼领袖。}
{101}{}{谢谢你没有先开枪。我能帮你什么忙吗？}
{102}{}{是的，我在找水。}
{103}{}{当然，你是谁？}
{104}{}{不需要。}
{105}{}{啊，如果你愿意，可以在这里休息，我们不会伤害你。}
{106}{}{啊。}
{107}{}{我是一个简单族群的领袖，因为其他人我们离开了地表。}
{108}{}{是谁逼你们到这里来的？}
{109}{}{天啊，这真蠢。}
{110}{}{嗯。好吧。再见。}
{111}{}{死城的地表和水源由赛特和他的食尸鬼控制。我们是一个更加和平的群体，这让赛特感到厌恶。}
{112}{}{这个赛特是谁？}
{113}{}{好吧，我已经解决了赛特。他不会再打扰你们了。}
{114}{}{那么你们在这里没有水是怎么生存的？}
{115}{}{我也不喜欢一群懦夫，赛特听起来还不错。}
{116}{}{赛特和我们一样是食尸鬼，但在地表世界掌握了一定的权力。他是个笨蛋。}
{117}{}{他听起来比你们这些怪胎有趣多了。}
{118}{}{他为什么让你们在这里生存？}
{119}{}{他没有明说，不过赛特害怕如果死城需要防御时没有足够的人手。所以，他给我们提供所需的水。}
{120}{}{这些水都是从哪里来的？}
{121}{}{我的人需要水！如果你知道他从哪里得到的，快告诉我！}
{122}{}{我在找一个水芯片，给我的人提供所需的水。你知道我可以在哪里找到吗？}
{123}{}{我才不会留你们来守个纸袋子呢。那么关于水的事是怎么回事？}
{124}{}{直到最近我们还在用水源地的泵从地下抽水。}
{125}{}{直到最近？发生了什么改变了情况？}
{126}{}{我怎么去水源地？}
{127}{}{水源地是什么？}
{128}{}{自从我们的泵停止工作后，我们一直从地下的一个地方取水。我听说有一个水计算机在净化水源。}
{129}{}{谢谢。}
{130}{}{那是什么地方？}
{131}{}{水塔在北边。你需要通过下水道才能到达那里。}
{132}{}{你不会是想从我们这里拿走水芯片吧？}
{133}{}{嗯...我？不，我绝不会做那种事。我只是想看看它是如何运作的。}
{134}{}{当然，我的人民需要水芯片才能生存。}
{135}{}{为什么？}
{136}{}{如果你拿走水芯片，我们都会死。我们的水泵坏了，我们需要它才能活下去。}
{137}{}{嗯，我真的不在乎你和你的人。我们需要水芯片来生存。再见。}
{138}{}{你的水泵有可能修好吗？}
{139}{}{如果是这样，我不能让你活着离开。}
{140}{}{我不认为我相信你。}
{141}{}{抱歉，我不是故意要欺骗你。拿走水芯片有什么问题？}
{142}{}{好吧，我真的不在乎。如果你不让开，我就自己动手。}
{143}{}{这可能很困难。修理水泵所需的零件丢失在水塔下的下水道里。}
{144}{}{为什么这么困难？}
{145}{}{你是说这些零件吗？（你向食尸鬼领袖展示你找到的零件）}
{146}{}{那里的下水道充满了怪物，我派去取回零件的人都没有回来。你愿意去取回零件，以便修好水泵吗？}
{147}{}{听起来麻烦太多，我想我还是直接拿水芯片吧。}
{148}{}{是的。}
{149}{}{既然你们自己做不了，我想我得帮个忙。}
{150}{}{谢谢你。当你拿到零件后，回到这里。也许我还能进一步帮助你。}
{151}{}{好的，那我这就出发。}
{152}{}{你找到修理水泵的零件了吗？}
{153}{}{还没有。}
{154}{}{没有。我决定放弃这件事。}
{155}{}{我应该去哪里找来着？}
{156}{}{那么祝你好运。}
{157}{}{你回来了。你拿到修理水泵所需的零件了吗？}
{158}{}{是的，在这里。}
{159}{}{是的，但我决定不修水泵了。}
{160}{}{看起来你可能需要一些零件方面的帮助。这里有一些我们在周围找到的书籍，或许能帮到你。现在请把零件带到水棚去修理水泵。}
{161}{}{很遗憾我无法再帮你更多。祝你修理水泵好运。请把零件带到水棚去修理水泵。}
{162}{}{你修好水泵了吗？}
{163}{}{还没有，但我还在努力。}
{164}{}{没有，而且我现在不打算修。}
{165}{}{是的，这些就是我说的零件。感谢命运你已经有它们了。}
{166}{}{还有什么我应该知道的吗？}
{167}{}{嗯，他们已经尽可能接近水泵了。}
{168}{}{正如我之前告诉你的，它们可以在水棚下方的下水道中找到。从这里向东走，然后向北。你会在那个方向找到水棚。}
{169}{}{谢谢你的指引。再见。}
{170}{}{感谢你的帮助。还有其他想知道的吗？}
{171}{}{你们在这里没有水是怎么生存的？}
{172}{}{那是所有水被储存和分发给我们的地方。}
{173}{}{它位于哪里？}
{174}{}{最近我听说有人接管了水棚的控制。然而，我们的配给仍然在某种原因下被送达。}
{175}{}{我该如何去水棚？}
{176}{}{什么是水棚？}
{177}{}{感谢你修好了水泵，希望你回去时一切顺利。}
{178}{}{谢谢你的帮助。再见。}
{179}{}{你修好了水泵，水流又从深处回来了。然而，我看到你还没有找到你要找的东西。}
{180}{}{是的，我似乎找不到水芯片的位置。}
{181}{}{我听说它位于水棚的深处。祝你好运找到它。}
{182}{}{我看到你找到了你来这里要找的东西。你知道如果你拿走水芯片，我们会死的。}
{183}{}{是的，但我还在努力修理水泵。你说我可以在哪里找到零件？}
{184}{}{我需要水芯片，我没有时间处理你的问题。}
{185}{}{我还有其他选择吗？}
{186}{}{我厌倦了你尖酸的评论。我不想再和你说话。}
{187}{}{我们曾经在水棚有一个泵，从深处抽水。然而，它坏了，修理所需的零件丢失在水棚下方的下水道中。}
{189}{}{你们为什么不自己去取零件？}
{190}{}{你不用害怕我们！}
{191}{}{在你离开之前，我要与你谈谈。}
{192}{}{你没给我选择的余地，我只能亲自阻止你。}
{193}{}{等一下，别开枪！}
{194}{}{你不用怕我们！}
{195}{}{在你离开之前，我要与你谈谈。}
{196}{}{你没给我选择的余地，我只能亲自阻止你。}
{200}{}{运气不佳。}
{201}{}{水泵能修好吗？}
{202}{}{很抱歉，但我的人民需要这个芯片来生存。}
{203}{}{请不要拿走我们的芯片。没有它，我们会死的。}
{204}{}{也许可以，但零件丢失在蓄水池下的下水道里。那里面到处都是怪物，我们根本无法取回。}
{205}{}{抱歉，我真希望能帮上忙。}
{206}{}{我会去找那些零件。}


############ Tell Me Abouts

{1000}{}{赛特}
{1001}{}{主教}
{1002}{}{水源}
{1003}{}{蓄水池}
{1004}{}{大厅}
{1005}{}{死城}
{1006}{}{芯片}

{1100}{}{他试图控制死城，并迫使我们藏身地下。}
{1101}{}{他和变种人有些关系。我也不大清楚更多的细节。}
{1102}{}{我们的水是从蓄水池下的地方取的。可能和那个有关。}
{1103}{}{坏掉的水泵就在那。同时，那也是变种人从他们的新水源分发水的地方。}
{1104}{}{赛特所谓的宫殿。}
{1105}{}{亡者之城，我们想在这里平静生活，如果赛特或变种人允许的话。}
{1106}{}{我们的水是从蓄水池下的地方取的。可能和那个有关。}
