{100}{}{就算你拔出武器，也不代表我会给你想要的东西……}
{101}{}{你打败我了！你还想要什么，见鬼！}
{102}{}{我没什么好说的！说话是弱者的行为！}
{103}{}{我不知道你是谁，但我警告你：惹上可汗的人，死得很惨。}
{104}{}{你知道吗，如果你真的觉得自己更强，就杀了我。}
{105}{}{太糟糕了。我就是要惹你！}
{106}{}{好吧。我们别互相找麻烦，大家都会开心。}
{107}{}{我投降。请不要杀我！}
{108}{}{嗡嗡！}
{109}{}{嗯？}
{110}{}{致敬，可汗兄弟！狩猎如何？今天有多少弱者死去？}
{111}{}{致敬，可汗姐妹！狩猎如何？今天有多少弱者死去？}
{112}{}{我会把我的夸耀留到营火旁，但我有很多故事要讲！}
{113}{}{我见过很多血，也夺取了不少战利品。}
{114}{}{还不错。你呢？}
{115}{}{我做得更好……}
{116}{}{你是可汗的敌人！你攻击我们的战士，抢走我们的女人！给我一个不割掉你心脏的理由！}
{117}{}{少来这套。坦迪在哪？告诉我，否则你就死定了！}
{118}{}{想不出理由。那就打吧！}
{119}{}{因为如果你不动手，我们都能活命。}
{120}{}{我现在没法打。我投降。}
{121}{}{你是他们中的一个吗？一个变种人？}
{122}{}{你对变种人了解多少？}
{123}{}{是的，我是个变种人！}
{124}{}{我看起来像变种人吗？}
{125}{}{不像。}
{126}{}{或许吧。如果你想打，我奉陪。如果你想和平离开，我以可汗的名义保证不会攻击。}
{127}{}{那就打吧。}
{128}{}{我们别打了。}
{129}{}{可汗的承诺？真是个笑话！}
{130}{}{你太强大了，而我在荒地中疲惫不堪。我不想死。虽然这让我感到羞愧，但我投降。}
{131}{}{我同意。只要你不挑衅我，我保证让你平安离开。不要再来打扰我。}
{132}{}{我不想要懦夫的任何东西，包括你的命！从我眼前消失！}
{133}{}{你这个愚蠢的动物。我会很享受杀了你的。}
{134}{}{呃，是的……}
{135}{}{我会很享受听到它们的。再见，兄弟！}
{136}{}{我会很享受听到它们的。再见，姐妹！}
{137}{}{真的吗？那我必须把它据为己有！}
{138}{}{是的，我听说幸运总是眷顾你。正因为如此，我才不与你争夺战利品。再见，我的兄弟！愿我们下次并肩作战。}
{139}{}{是的，我听说幸运总是眷顾你。正因为如此，我才不与你争夺战利品。再见，我的姐妹！愿我们下次并肩作战。}
{140}{}{我疲惫不堪，这趟旅程比我预期的要长得多。辐射蝎子杀死了我的同伴。我渴望营地的舒适和我们女性的治愈抚慰。}
{141}{}{愿好运再次眷顾你。再见，我的兄弟。}
{142}{}{愿好运再次眷顾你。再见，我的姐妹。}
{143}{}{他们摧毁了阴影镇。他们杀死路上的每一个人。我从未想过会有如此凶猛的存在。我们都完了……}
{144}{}{凶残的狗！}
{145}{}{不，但很难说。我听说他们在夜晚隐匿自己，迷惑人心，化身为美丽的女人！我们都完了！}
{146}{}{那很好。我渴望为我们的死者复仇，甚至为阴影镇的死者复仇。任何经过我面前的变种人都得死！去吧，朋友！去吧，杀掉他们！变种人去死！}
{147}{}{你会为这些话付出生命的代价！}
