{100}{}{你看到洛琳，一个来自阿迪特姆的拾荒者。}
{101}{}{你看到一个黑发的年轻女子。}
{102}{}{嗨，你是新来的吗？}
{103}{}{是的，你能给我介绍一下吗？}
{104}{}{是的，我是。我叫}
{105}{}{。}
{106}{}{什么？}
{107}{}{我想可以。你想了解什么？}
{108}{}{你是谁？}
{109}{}{你能告诉我一些关于骨园的信息吗？}
{110}{}{给我介绍一下阿迪特姆的其他居民吧。}
{111}{}{你是做什么工作的？}
{112}{}{没事，谢谢。}
{113}{}{我叫洛琳。}
{114}{}{我可以问你几个问题吗？}
{115}{}{很高兴认识你。再见。}
{116}{}{我是个拾荒者。我和萨梅尔一起从废墟中收集物资，这样我们就可以用来建造或交易。}
{117}{}{听起来很危险，有那些帮派。}
{118}{}{有多少拾荒者？}
{119}{}{我可以问你其他事情吗？}
{120}{}{和你聊天很愉快。}
{121}{}{如果被抓到的话确实很危险。撕裂者对入侵者尤其严厉。所以我们努力不被抓到！}
{122}{}{你能告诉我一些关于帮派的事情吗？}
{123}{}{你们是怎么避免被抓的？}
{124}{}{我可以问你其他事情吗？}
{125}{}{谢谢。再见。}
{126}{}{哦，我们有六个人。萨梅尔是第一个，也是最厉害的。}
{127}{}{我可以问你其他事情吗？}
{128}{}{有趣。谢谢。}
{129}{}{你总能认出刀锋帮，因为他们有那些讨厌的振动刀。而撕裂者则是低科技但非常凶狠。}
{130}{}{那些撕裂者甚至在他们的堡垒周围布置了地雷！真让人想知道朱莉安娜在想什么。}
{131}{}{你指的朱莉安娜是什么意思？}
{132}{}{真是糟糕。我可以问点别的事情吗？}
{133}{}{谢谢你的提醒。}
{134}{}{哦，她前阵子爱上了一个撕裂者。可怜的姑娘当然不能离开镇子，而凯莱布一见到那小伙子就会杀了他。真是悲剧。}
{135}{}{呃……如果你这么说的话。}
{136}{}{我可以问一些其他问题吗？}
{137}{}{嗯，谢谢你的信息。再见。}
{138}{}{我们只在晚上搜寻。而且我们很擅长这个。萨玛尔有个小测试，他喜欢在让人加入拾荒者之前考验他们。}
{139}{}{是什么测试？}
{140}{}{听起来还是很危险。}
{141}{}{我明白了。介意我们回到前面的话题吗？}
{142}{}{有趣。再见。}
{143}{}{萨玛尔让人在白天藏在阿迪顿的某个地方。如果他在一小时内找不到这个人，那么他就让这个人加入下一个拾荒队。}
{144}{}{真是个愚蠢的系统！}
{145}{}{似乎很有效。你还活着。}
{146}{}{嗯。我可以问你一些其他事情吗？}
{147}{}{有趣。再见。}
{148}{}{拜托，你心里就没有一点浪漫的影子吗？真的很遗憾。单相思和这一切。悲剧。}
{149}{}{哼。你知道什么。去告诉萨玛尔吧。如果你能找到他。}
{150}{}{是的，虽然可能很艰难。非常危险，尤其是如果被抓住的话。}
{151}{}{毫无疑问。我可以问点别的事情吗？}
{152}{}{谢谢你的信息。}
{153}{}{哇，我想你有点超出我的帮助范围了。}
{154}{}{这里曾经是一个大城市，叫做洛杉矶。但炸弹打得很重。现在，只剩下天使墓地。我们阿迪顿人只是想在废墟中生存。}
{155}{}{你能多告诉我一些关于洛杉矶的事情吗？}
{156}{}{我明白了。谢谢。}
{157}{}{这里住了很多人，他们做一些重要的事情，比如制作电脑游戏。据我所知，幸存者们躲在一个叫做避难所的大地方，几年后才出来。他们中的一些人建立了阿迪顿，但}
{158}{}{其他人组成了街头帮派，刀锋帮和撕裂者。枪械跑商原本不是这里的人。}
{159}{}{这个避难所在哪里？}
{160}{}{告诉我关于这些帮派的事。}
{161}{}{枪械跑商是从哪里来的？}
{162}{}{制作电脑游戏？听起来不太重要。}
{163}{}{谢谢你的帮助。}
{164}{}{嗯，据说是在这里南边的某个地方，但我不太清楚。我想大家都离开了，因为那里已经废弃了。}
{165}{}{我可以再问几个问题吗？}
{166}{}{嗯，谢谢。}
{167}{}{我不太确定。我想他们是从这里北边的某个地方来的。}
{168}{}{告诉我关于其他帮派的事。}
{169}{}{我可以问一些其他的事情吗？}
{170}{}{谢谢你的信息。}
{171}{}{你想知道谁，齐默尔曼，凯勒布，迈尔斯，泰勒，还是史密蒂？}
{172}{}{乔恩·齐默尔曼。}
{173}{}{凯勒布。}
{174}{}{迈尔斯。}
{175}{}{泰勒。}
{176}{}{史密蒂。}
{177}{}{没有人。}
{178}{}{齐默尔曼负责看管我们的城镇。他确保每个人都有饭吃，并且每个人都有工作。}
{179}{}{凯勒布是治安官的领袖。他的职责是保护阿迪图姆。他非常严格，但他是为大家好。}
{180}{}{啊，我们的化学家。迈尔斯制造子弹，他还建造了水蒸馏器，确保我们从井里得到干净的水。他现在正在研究一个地下农场，但他缺少一些零件。}
{181}{}{泰勒经营商店。就在靠近大门的地堡里。他为我们和集散地的商人交易。}
{182}{}{嗯，史密蒂算是个修补匠。他擅长修理工作。他铸造子弹并修理镇上的破损物品。}
{183}{}{我可以问关于其他人的事吗？}
{184}{}{我们可以谈论不同的话题吗？}
{185}{}{谢谢。}
{186}{}{你在开玩笑吗？没有电脑游戏，你现在就不会玩这个了，不是吗？}
