{100}{}{你看到一个强壮结实的男人，留着浓密的胡子。}
{101}{}{你看到麦克雷。}
{102}{}{你好，小伙子，今天你想找点什么？}
{103}{}{你好，姑娘，今天你想找点什么？}
{104}{}{哎，还有什么是你想知道的？}
{105}{}{你是谁？}
{106}{}{你能告诉我关于刀锋帮的事吗？}
{107}{}{没事，谢谢。}
{108}{}{嗯，我是麦克雷。我帮刀锋帮对付死亡爪和那些监管者。教他们一些自我保护的技巧。}
{109}{}{你教他们什么东西？}
{110}{}{你见过死亡爪吗？}
{111}{}{监管者是怎么回事？}
{112}{}{我可以问你别的事情吗？}
{113}{}{我的专长是用拳头打架，还有比对手多挨几拳。}
{114}{}{听起来像个蠢主意，我宁愿用枪。}
{115}{}{你觉得你能教我点什么吗？}
{116}{}{我可以问你别的事情吗？}
{117}{}{如果你是这么想的，那你可以转身走开了。}
{118}{}{你看起来是个不错的小伙子，但我现在忙着教刀锋帮。如果事情能平息下来，我可能就有时间了。}
{119}{}{好吧，我可以问你别的事情吗？}
{120}{}{谢谢你的信息。}
{121}{}{我见过他们。我当时跑得飞快。如果你想找他们，他们就在那边。[麦克雷指向东边]}
{122}{}{我本以为死亡爪是不自然行为的产物，但那些监管者才是真正的邪恶。他们每个月左右来一次，露出丑陋的面孔，把父亲从孩子身边带走。}
{123}{}{有什么我可以帮忙的吗？}
{124}{}{听起来很糟糕，我可以再问一个问题吗？}
{125}{}{谢谢你的信息。}
{126}{}{你得去找剃刀。她是个好姑娘。}
{127}{}{刀锋帮是一群很好的人。夹在该死的监管者和死亡爪之间，他们的生活并不快乐，但他们活下来了。}
{128}{}{[麦克雷拍了拍你的背] 多亏了你，刀锋帮将过上更好的生活。那么，一个老苏格兰人能为你做些什么？}
{129}{}{你之前说过如果有空闲时间，可以教我一些东西。}
{130}{}{最近在忙些什么？}
{131}{}{你在这里做些什么？}
{132}{}{没问题。}
{133}{}{自从刀锋帮帮忙解决了阿迪顿的监管者问题后，这里就有点安静。我教授的课程需求不大。}
{134}{}{你教些什么？}
{135}{}{很遗憾听到这个，希望事情能变得有趣些？}
{136}{}{你能教我吗？}
{137}{}{听起来很有趣，但我得走了。}
{138}{}{好吧，我确实有时间。不如现在就开始吧。[麦克雷开始向你展示一些战斗姿势，以及如何像真正的苏格兰人一样接招。]}
{139}{}{你学得很快。希望这能在你的旅途中帮到你。}
{140}{}{我以前帮助刀锋帮，教他们一些如何保护自己免受死亡爪和监管者伤害的技巧。现在你解决了这些问题，最近有点无聊。}
{141}{}{很高兴见到你。}

