{100}{}{你看到玛西亚。}
{101}{}{你好，见习者。原来你就是那个从古代命令中活着出来的人。}
{102}{}{什么？}
{103}{}{你是谁？}
{104}{}{抱歉，我以为你是别人。再见。}
{105}{}{我叫玛西亚。我是马克森的助理，但我也在这里确保没有人打扰这位老先生。}
{106}{}{老先生？这听起来有点不敬。}
{107}{}{作为马克森的助理，你负责什么工作？}
{108}{}{很高兴认识你。再见。}
{109}{}{不，不，完全不是。他是个好人。（开玩笑地）而且，我不会在他站在我旁边时说他的坏话。}
{110}{}{那么，作为马克森的助理，你具体负责什么？}
{111}{}{再见。}
{112}{}{我负责所有的文书工作。他完全不擅长处理文书。另外，如果他批准了某位兄弟的武器升级，我会处理订单。}
{113}{}{好的，谢谢你的信息。}
{114}{}{真不敢相信像你这样的笨蛋竟然能让古代命令运转起来。真是难以置信。}
{115}{}{你好，见习者。有什么我能帮你的吗？}
{116}{}{什么？}
{117}{}{抱歉，我忘了你的名字。}
{118}{}{抱歉，我以为你是别人。祝你有美好的一天。}
{119}{}{好吧，走吧。（他抓住你的手臂）}
{120}{}{嗯哼。}
{121}{}{嗯嗯。}
{122}{}{好吧，好吧。我动身了。}
{123}{}{离我远点。我哪儿也不去。}
{124}{}{好的。马克森已经批准了你的武器升级。你想要什么？}
{125}{}{什么？}
{126}{}{狙击步枪。}
{127}{}{火箭发射器。}
{128}{}{激光手枪。}
{129}{}{动力拳。}
{130}{}{撕裂者。}
{131}{}{给你。很高兴你站在我们这边，新兵。}
{132}{}{长老们召开了会议。他们希望你立即去会议室见他们。}
{133}{}{会议室在哪里？}
{134}{}{好的，谢谢。}
{135}{}{就在这一层。东北角，装配大厅的正后方。}
