{100}{}{你看到迈尔斯，阿迪顿的化学家。}
{101}{}{你看到一个穿着白色实验服的瘦弱男子。}
{102}{}{我想我们还没见过。我是迈尔斯。我能为你做些什么？}
{103}{}{我只是随便看看，谢谢。}
{104}{}{那件实验服让你看起来像个科学家。你在研究什么？}
{105}{}{嗯？}
{106}{}{好吧，祝你在我们的小镇过得愉快。}
{107}{}{我是个化学家。主要是制作底火和火药，以便我们可以重复利用子弹的黄铜弹壳。不过我也涉猎一些其他化学品。}
{108}{}{所以你为阿迪顿制造子弹。}
{109}{}{你从哪里得到硫磺、硝酸钾和其他化学品？}
{110}{}{你还研究哪些化学品？}
{111}{}{谢谢你的信息。}
{112}{}{是的，不过真正铸造子弹的是史密蒂。我只是给黄铜弹壳重新装填。}
{113}{}{但是集市的商人从你和小镇身上赚取了利润。}
{114}{}{能遇到一个欣赏化学的人真是少见！不过为了回答你的问题，我们的一些材料是从集市商人那里得到的；其他的我自己制造或在附近找到。例如，布拉明的粪堆是一个不错的来源，还有我培养的一些真菌菌株。}
{115}{}{嗯，我一直在尝试获取一些强酸，以便史密蒂可以用来蚀刻。我也在尝试制作一些永久性的染料和墨水。但没有天然墨水的来源，这很困难。}
{116}{}{随时欢迎。}
{117}{}{哦天哪。恐怕我帮不了你。}
{118}{}{又见面了。我能帮你吗？}
{119}{}{是的，嗯，我们得谋生。由于水培农场无法运作，我们不得不从商人那里购买食物，而子弹是我们唯一能出售的东西。}
{120}{}{我可以尝试获取修理水培农场的零件。}
{121}{}{哦。那真是太糟糕了。}
{122}{}{真的吗？那太好了！我们只缺少一些零件，但我相信如果你能找到合适的部件，我们就能自给自足！萨梅尔可能会帮到你。}
{123}{}{你找到零件了吗？}
{124}{}{是的，这些就是。}
{125}{}{还没有，你说我该问谁来着？}
{126}{}{你需要和萨梅尔谈谈。白天你通常可以在农场附近的帐篷里找到他。}
{127}{}{[迈尔斯检查了这些零件] 就是这些，不过看起来史密蒂还需要做些工作。你能把它们拿给他吗？}
{128}{}{我有其他事情要处理。你能自己去吗？}
{129}{}{当然，我会在他修好后回来。}
{130}{}{当然，我很感激你为我们找到它们。}
{131}{}{而且……}
{132}{}{没问题。}
{133}{}{哦，我差点忘了。这是一些东西，算是对你的麻烦的补偿。[迈尔斯递给你一些瓶盖和治疗针。]}
{134}{}{你能把零件送到斯密蒂那里了吗？}
{135}{}{[迈尔斯从你手中接过修好的零件] 看来斯密蒂干得不错。感谢你的帮助，这是一些东西，算是对你的麻烦的补偿。}
{136}{}{[迈尔斯递给你一些瓶盖和治疗针。]}
{137}{}{如果你有机会再回来，可以找我和斯密蒂。我们可能可以帮你调整一些装备。斯密蒂在某些武器上很有一手，而我可以在某些类型的护甲上帮忙。}
{138}{}{看起来你找到了一些动力装甲。我听说有一种化学工艺可以用来强化装甲的表面。不过，我缺少一些信息来给我最后的线索，找到所需的配方和试剂。我听说在枢纽的图书管理员斯泰普尔顿夫人有一些可能有用的期刊和书籍。如果你能从那里拿到这些，我可能可以在你的装甲上测试这个工艺。}
{139}{}{听起来不错。我去找斯泰普尔顿夫人谈谈。}
{140}{}{我有更重要的事情要做，不想再给你跑腿。}
{141}{}{好吧，如果你改变主意了，就去找斯泰普尔顿夫人，然后再回来找我。}
{142}{}{你有机会去枢纽找斯泰普尔顿夫人了吗？}
{143}{}{是的，这些是书。}
{144}{}{还没有。}
{145}{}{[迈尔斯从你手中接过书，开始翻阅。] 嗯……是的，嗯…… [他自言自语了几分钟。] 好吧，我想我能搞定，但需要整整一天的时间来完成结合。这样可以吗？}
{146}{}{没问题。}
{147}{}{抱歉，我没有时间。}
{148}{}{好吧，当你有时间时，回来找我，我会在你的装甲上进行这个工艺。}
{149}{}{[迈尔斯从你手中接过你的装甲。]}
{150}{}{[迈尔斯把你的装甲还给你，看起来比之前更闪亮了。] 好吧，我想成功了！希望对你有帮助。}
{151}{}{你的动力装甲怎么了？我只能帮你处理动力装甲。}
{152}{}{很高兴见到你，但我正忙于一些研究。}
{153}{}{这种类型的护甲我无能为力。抱歉。}
