{100}{}{你看到两个超级变种人。一个看起来受伤了，另一个正在照顾他。}
{101}{}{现在感觉怎么样？}
{102}{}{[活动肩膀] 啊，还是有点疼。至少流血止住了。}
{103}{}{很好，很好。继续用药，你很快就会恢复如初。}
{104}{}{太好了。当我抓到那个小人类时，我要把他捏碎。}
{105}{}{太好了。当我抓到那个小人类时，我要把她捏碎。}
{106}{}{他上次确实造成了不少破坏。希望他们能快点抓到他。}
{107}{}{她上次确实造成了不少破坏。希望他们能快点抓到她。}
{108}{}{想象一下，如果我们的计划因为一个小人类而泡汤。}
{109}{}{[笑] 是啊，那可真是遗憾。}
{110}{}{[轻笑]}
