{100}{}{这台电脑标记为原子访问计算机。}
{101}{}{有电缆从访问计算机连接到后面的弹头。}
{102}{}{你已启动弹头。一个四分钟的倒计时已经开始。}
{103}{}{你已拆除核弹头的武装。}
{104}{}{轰隆！[你引爆了核弹！]}
{105}{}{这似乎不起作用。}
{106}{}{倒计时仍在继续……也许你应该剪断那根红线。}
{107}{}{也许你还需要使用钥匙。}
{108}{}{这台电脑配备了硬件锁定装置，没有正确的钥匙无法启动炸弹。}
{109}{}{这个高度安全的锁无法用开锁工具打开。}
{110}{}{这台电脑无法修复。}
{111}{}{你无法在这台电脑上使用陷阱技能。}
{112}{}{你的技能不足以破解安全机制。}
