{100}{}{你看到酒保尼尔。}
{101}{}{你看到一个酒保。}
{102}{}{他看起来忙得不可开交。}
{103}{}{嘿！别以为你能逃得掉，小偷！}
{104}{}{我们关门了。四点钟再来吧。}
{105}{}{Zzzz}
{106}{}{欢迎来到污秽之坑。需要点什么？}
{107}{}{呃，来杯酒吧。}
{108}{}{我在找点信息。}
{109}{}{我叫}
{110}{}{。这是个什么地方？}
{111}{}{嘎 嗯嗯！}
{112}{}{好。你想要什么？}
{113}{}{核子可乐，3瓶盖。}
{114}{}{啤酒，5瓶盖。}
{115}{}{烈酒，20瓶盖。}
{116}{}{好吧，你想知道什么？}
{117}{}{这镇上有什么消息？}
{118}{}{角落里那个危险人物是谁？}
{119}{}{那些混蛋是谁？}
{120}{}{[尼尔疑惑地看了你一会儿。] 难道你没见过酒吧吗，陌生人？这是我的地方，污秽之坑。在这里你可以买酒，还要给我小费。}
{121}{}{呃，对。我知道。那么，我能来杯酒吗？}
{122}{}{是的。呃，我能问点别的信息吗？}
{123}{}{哦。谢谢。}
{124}{}{嗯，你也是，伙计。}
{125}{}{架子上的那个奖杯是什么？}
{126}{}{就在我们西边是吉兹莫的赌场。我会很惊讶你不知道它；这里的大多数人都是刚在那里输完钱的。在镇的另一边有基利安的杂货店，还有马塞勒斯的撞击屋。基利安是个好人，经营得很正派，什么都卖。撞击屋是你在这里待太久后休息的地方。[尼尔笑了笑。]}
{127}{}{谢谢。我能来杯酒吗？}
{128}{}{谢谢你的信息。回头见。}
{129}{}{那家伙叫泰克。据说是从东边来的游侠。听说他是个很厉害的战士，但为人正直。}
{130}{}{介意我问几个其他问题吗？}
{131}{}{哦，他们啊。他们是骷髅帮，本地的一个帮派，全是些地痞流氓。有时候他们会惹点麻烦，打个架什么的，不过通常凯利安会把他们管得服服帖帖的。}
{132}{}{给你，慢用。}
{133}{}{嘿！你偷了我的骨灰坛！}
{134}{}{那不是奖杯，是骨灰坛。里面装的是我妻子的骨灰——除了这间酒吧，这是我生命中最重要的东西。}
{135}{}{还有别的事吗？}
{136}{}{想了解更多信息。}
{137}{}{不用，谢谢。}
{138}{}{哦。}
{139}{}{好吧，给我来一杯。}
{140}{}{等你有钱了再来吧。}
{141}{}{想喝点什么，朋友？}
{142}{}{你之前放在那儿的奖杯去哪了？}
{143}{}{谢谢你。你不知道这对我来说多重要。在这家酒吧，你从此以后喝酒永远免费。}
{144}{}{我帮你把骨灰坛拿回来了。}
{145}{}{被些混蛋偷走了。那不是奖杯，是骨灰坛。里面装的是我妻子的骨灰——除了这间酒吧，那是我生命中最重要的东西。}
{146}{}{给我滚出去，你们这群混账！谁再敢碰她一下，我就宰了你们所有人！}
{147}{}{我能应付你们这群小杂碎的日子就是我活着的日子！}
{148}{}{你在搞什么？我们关门了。快滚出去！}
{149}{}{你们这些死小子，我要让你们见识见识！}
