{100}{}{水泵已经修好，运转正常。}
{101}{}{水泵无法运作，因为真空泵损坏。}
{102}{}{水泵无法运作。}
{103}{}{一台机器。}
{104}{}{这个水泵无法运作，因为真空泵损坏。}
{105}{}{可能需要一个新的保险丝。}
{106}{}{水泵无法运作。}
{107}{}{没有替换的真空泵，你无法修理水泵。}
{108}{}{你未能修理水泵。可能需要一个新的保险丝。}
{109}{}{你未能修理水泵。}
{110}{}{这个水泵无法运作，因为真空泵损坏。}
{111}{}{这个水泵可能需要一个新的保险丝。}
{112}{}{水泵无法运作。}
{113}{}{你没有发现任何异常。}
{114}{}{在你成功安装缺失的部件后，巨大的水泵艰难地启动了。}
{115}{}{你不小心破坏了部件，同时割伤了手，造成1点伤害。}
{116}{}{你在让这些部件正常工作时遇到了困难。}
{117}{}{此物品无法用于水泵。}
{118}{}{你因修理水泵获得了1000点经验值。}
