{100}{}{你！站住，面对法律！}
{101}{}{感谢你带回水芯片。这对提升士气很有帮助，也能防止人们违反避难所的法律。}
{102}{}{很高兴再次见到你。有需要我帮忙的吗？}
{103}{}{你是做什么的？}
{104}{}{我需要一些武器。}
{105}{}{为什么避难所里会有上锁的门？}
{106}{}{哎呀！}
{107}{}{嗯。我觉得你应该去别的地方。祝你有美好的一天。}
{108}{}{我负责避难所的安全和法律执行。你可能不知道，如果没有我，避难所就不会运转得这么好。}
{109}{}{嗯，真不错。谢谢。}
{110}{}{听起来很重要。}
{111}{}{确实如此。如果不严格遵守法律，避难所很快就会变得无序，没有方向。这会危及我们所有人的安全。}
{112}{}{既然我已经去过外面，有没有什么特别适用于我的法律？}
{113}{}{我见过外面一些地方因为没有法律而遭受苦难。}
{114}{}{即使在外面的世界需要武器，在这里也不要以威胁的方式展示它们。除此之外，我想不出有什么特别的。}
{115}{}{谢谢。}
{116}{}{你看，我就知道会这样。遵守法律是避难所免于痛苦和毁灭的唯一原因。继续保持。}
{117}{}{监督者没有授权我打开军械库给你更多武器。很抱歉，我帮不了你。}
{118}{}{拜托！我真的需要它们！}
{119}{}{好的。无论如何，谢谢。}
{120}{}{不行。我做不到。}
{121}{}{祝你有美好的一天。}
{122}{}{为了防止那些没有权限的人接触到武器。}
{123}{}{谁有权限？}
{124}{}{这似乎不太公平。}
{125}{}{生活有时不公平。但我们的法律是公平的。祝你有美好的一天。}
{126}{}{监督者、我和我的安全团队。就这些。}
{127}{}{听起来只有有需要的人才能获得权限。}
{128}{}{这名单真小。}
{129}{}{是的，确实如此。我得回去工作了。}
{130}{}{是的，只有有需要的人才能进入。}
{131}{}{嗯，我有需要。请开门。}
{132}{}{抱歉，你的理由不错，但我不能让你进去。}
{133}{}{嗯，现在你提到这点，听起来你确实有需要。来，我给你开门。}
{134}{}{我能为你做些什么，}
{135}{}{？}
{136}{}{我需要更多武器。}
{137}{}{你感觉还好吗？}
{138}{}{嗯哼。}
{139}{}{太好了。你的智力让我惊叹。我简直无法再思考了。}
{140}{}{抱歉，你已经拿走了我们能提供的全部。祝你好运。}
{141}{}{我不喜欢你这种人。煽动者。你应该感到羞愧。}
{142}{}{是啊，好吧，你也是，笨蛋。}
{143}{}{你不觉得你有点苛刻吗？}
{144}{}{注意你的语言，否则我会因为不尊重执法人员而逮捕你。}
{145}{}{好吧，当然。回头见。}
{146}{}{够了。我受够了你对我的骚扰。}
{147}{}{嗯，可能吧。我的工作应该是公正的，但这次我可能越界了。我会努力改进。}
{148}{}{嗯，不。可能还不够苛刻。}
{149}{}{祝你好运。希望你能做好这份工作。}
{150}{}{你最好不要让我失望。}
{151}{}{立刻收起你的武器。}
{152}{}{你以为你在这里干什么？}
{153}{}{只是练习瞄准。}
{154}{}{没什么，抱歉。我不是故意拔出来的。}
{155}{}{挂起。}
{156}{}{注意你怎么称呼我。不要在里面拔出武器。这可是避难所。}
{157}{}{你最好不要在这里练习。如果再这样，我们会有大麻烦。}
{158}{}{我就知道外面的生活会让你惹上麻烦。}
{159}{}{站住！你不被允许进入那里！}

{1000}{}{监督者}
{1100}{}{他是避难所的最高权威。避难所的一切都由他的决定来定夺。}
