{100}{}{你看到一个骑士。}
{101}{}{嘘，看到什么好交易了吗？}
{102}{}{抱歉，我在值班。现在不能聊天。}
{103}{}{多么美好的一天。希望今天不会有袭击。}
{104}{}{你好。}
{105}{}{有些商队的商人有点奇怪。}
{106}{}{嗨，漂亮的。}
{107}{}{见到你，见习者。}
{108}{}{如果你对我们的组织有任何疑问，可以去门边找卡博特。}
{109}{}{你要找的是卡博特，他就是门边的那个年轻人。}
{110}{}{如果你是来交易的，那你找错人了。}
{111}{}{什么？}
{112}{}{别烦我，蠢货。}
{113}{}{我看起来像是对你能提供的东西感兴趣吗。}
{114}{}{哼。真是无礼。}
{115}{}{我在值班，别打扰我。}
{116}{}{见习者，你应该知道值班时不要打扰我们。}
{117}{}{见习者，你难道不该去做些有用的事吗。}
{118}{}{如果你对我们的组织有任何疑问，可以去门边找卡博特。}
{119}{}{我觉得你不该在这里，陌生人。}
