{100}{}{你看到一个农民。}
{101}{}{哦，哎呀，大人物被一只可怕的狗追着跑。菲尔，你真是好样的。是的，你真是好样的。}
{102}{}{你在干什么，菲尔？你是在检查那些运动鞋的鞋底，对吧？}
{103}{}{伙计，那只狗看起来很饿。它肯定想活活吃了你，菲尔。}
{104}{}{对一个可怜无辜的动物来说，这可能有点过头了，你不觉得吗？}
{105}{}{你那只狗真不错。}
{106}{}{如果你能帮菲尔摆脱他的狗，他一定会很感激。}
{107}{}{谢谢你处理掉那只狗。}
