{100}{}{你看到彼得，追随者侦察队的领袖。}
{101}{}{你在这里干什么？没看到我们正忙着吗？}
{102}{}{嗯？}
{103}{}{抱歉。我这就走。}
{104}{}{我能帮你做些什么吗？}
{105}{}{我可以找谁来提供帮助？}
{106}{}{太好了。我正忙着呢，还要被个傻瓜跟着。想找人说话就去找杰克。}
{107}{}{当然。你可以先从我面前消失。}
{108}{}{当然。还有别的吗？}
{109}{}{一定还有别的我能做的。}
{110}{}{不要把我撇在一边。}
{111}{}{有的。你可以离开这里。}
{112}{}{好吧。看来我没法摆脱你。我们似乎有个安全问题。你想帮忙，就去找出问题。}
{113}{}{好的。我会去做。}
{114}{}{算了吧！}
{115}{}{好吧。那就走吧！}
{116}{}{听着，我们的安全有漏洞。我们需要找到这个漏洞并解决它。}
{117}{}{好的。我会去做。}
{118}{}{算了吧！}
{119}{}{我看起来像个向导吗？如果你在找向导，就去找杰克。}
{120}{}{离开。我正忙着完成一点工作。}
{121}{}{我们需要把那个间谍解决掉。快点！}
{122}{}{干得好，解决了希瑟。我早该知道是她。她总是在突袭中消失。来，拿着这个，走吧。}
