{100}{}{你看到Petrox，一个沙漠强盗。}
{101}{}{你好！我是Petrox。我是Garl的首席掠夺者之一。你是谁？}
{102}{}{我是}
{103}{}{。作为一个掠夺者，你都做些什么？}
{104}{}{我的名字现在不重要。你能告诉我一些关于你们营地的事吗？}
{105}{}{嗯？}
{106}{}{作为掠夺者，我可以去废土的许多地方。在我的旅行中，我为营地获取补给。}
{107}{}{换句话说，你从你去的地方偷东西。}
{108}{}{嘿，那真是太好了。我相信Garl一定对你很满意。}
{109}{}{你去过哪些地方？}
{110}{}{好吧，很高兴你觉得自己重要到不需要在这里报上名字。但我至少会告诉你一些关于我们的事。我们是废土中最强悍的人。没有人能与我们抗衡。即便是Shady Sands或Junktown的那些懦夫也不行。}
{111}{}{关于Shady Sands呢？}
{112}{}{Junktown是什么地方？}
{113}{}{抱歉，我没有时间浪费在那些反应慢的人身上。再见。}
{114}{}{我们从不偷窃。我们只是拿走别人多余的东西，并在我们饥饿的人中重新分配。}
{115}{}{所以，基本上，你就是在偷。}
{116}{}{听起来真是个好主意。}
{117}{}{我去过废土的许多地方。我去过最近的地方是Shady Sands和Junktown。那些地方没什么大事发生，但总是充满了信息和补给。}
{118}{}{告诉我关于Shady Sands的事。}
{119}{}{告诉我关于Junktown的事。}
{120}{}{你现在开始让我烦了。我想我会解决这个小问题。}
{121}{}{Shady Sands是一个富饶的社区。他们很乐意，嗯，与我们分享他们的收获。}
{122}{}{你能告诉我关于Junktown的事吗？}
{123}{}{Junktown在这里稍微往南一点。他们有很多好女人。}
{124}{}{Junktown在这里稍微往南一点。他们有很多好女人。说起来……我可以带你四处看看，也许我们可以更好地了解彼此……你觉得怎么样？}
{125}{}{不用了，也许下次吧。}
{126}{}{当然，也许以后吧。}
{127}{}{好吧，也许以后吧。}
{128}{}{我已经告诉你我被允许的所有信息。请走吧。}
