{100}{}{这个掠夺者太害怕加尔，不敢再和你说话。}
{101}{}{你看到一个强壮的沙漠掠夺者。}
{102}{}{是死亡之手！他回来了！}
{103}{}{打扰了，死亡之手。很抱歉打扰您。}
{104}{}{你是回来杀掉你的儿子吗？}
{105}{}{哎呀！鬼啊！}
{106}{}{死人复活了！死亡之手回来了！}
{107}{}{幸会。}
{108}{}{嗨。}
{109}{}{我在等加尔摧毁阴影沙地。我想要一些战利品。}
{110}{}{欢迎，朋友。}
{111}{}{很高兴你能回来拜访。}
{112}{}{除非你想找麻烦，最好把那东西收起来。}
{113}{}{想一起狂欢吗？}
{114}{}{哦，看起来你很硬气，是吗？}
{115}{}{加尔·死亡之手爱他的战士。把那东西收起来，去和他说话。}
{116}{}{所以，你觉得自己很厉害，是吗？惹我试试看，我们都能知道结果。}
{117}{}{我不喜欢你的样子。}
{118}{}{走开！}
{119}{}{你想要什么？}
{120}{}{我在找一个叫坦迪的女人。见过她吗？}
{121}{}{没什么，只是随便看看。}
{122}{}{嗯？？}
{123}{}{哦。你一定是在找工作。去大房间找加尔，别打扰我们。}
{124}{}{那就去别处做。}
{125}{}{没见过她。你为什么问？}
{126}{}{没什么，只是在找我的一个朋友。}
{127}{}{她的头上有赏金。如果我能杀了她，我就能赚不少钱。}
{128}{}{你在撒谎。她在哪儿？}
{129}{}{啊，好吧。}
{130}{}{真的吗？她长什么样？}
{131}{}{大约六英尺高，金发。她来自阴影沙地。}
{132}{}{是的，她在这儿。她在大房子里。你知道，如果我们告诉加尔，他会想要分一杯羹。你可能需要考虑一下。}
{133}{}{你听起来不像是认真的。我觉得你在搞什么鬼。如果你说的是真的，那我就自己去拿赏金。}
{134}{}{我……我不能再说了，否则加尔会杀了我。}
{135}{}{咬我啊！}
{136}{}{我不喜欢你的样子。你最好离我远点。}
{137}{}{什么？走开！}
