{100}{}{你看到一个沮丧的掠夺者囚犯。}
{101}{}{嘿，你！快把我放出去！}
{102}{}{小声点，你会惊动守卫的！}
{103}{}{嘘！你是谁？}
{104}{}{古普}
{105}{}{我不在乎。求你了，快放我出去！}
{106}{}{我叫杰克，来自废城。这些怪物杀了我商队的其他人，把我关在这里。}
{107}{}{好的，我看看能做些什么。}
{108}{}{真倒霉。好好待着吧。}
{109}{}{拜托，帮帮我。}
{110}{}{哎哟！我的腿，受伤了。我觉得可能骨折了。请帮帮我！}
