{100}{}{你看到米奇，全能商店的经理。}
{101}{}{找点什么？}
{102}{}{今天想找点什么？}
{103}{}{需要我帮忙吗？}
{104}{}{我这里应有尽有，你需要什么？}
{105}{}{需要补给吗？}
{106}{}{想买点东西？}
{107}{}{要买什么？}
{108}{}{有好东西要交换吗？}
{109}{}{你有什么？}
{110}{}{给我个价。}
{111}{}{我给你个优惠。}
{112}{}{欢迎再来。}
{113}{}{谢谢，很快再见。}
{114}{}{再见。}
{115}{}{小心你的钱包。}
{116}{}{如果需要什么，尽管告诉我。}
{117}{}{小心脚下。}
{118}{}{找到好东西，记得带回来。}
{119}{}{别做陌生人。}
{120}{}{我这里都是好货。}
{121}{}{什么？}
{122}{}{米奇才是这里的老板，不是我。}
{123}{}{我下班就去猎鹰酒吧！}
{124}{}{别惹麻烦。}
{125}{}{注意点。}
{126}{}{你在看我？}
{127}{}{最好别让我抓到你偷东西。}
{128}{}{欢迎来到全能商店。}
{129}{}{快买点东西吧！}
{130}{}{你想找麻烦吗？}
{131}{}{我们快到了。}
