{100}{}{你看到杰瑞，一个年轻的见习生。}
{101}{}{你看到一位骑士见习生。}
{102}{}{你看到一位抄写员见习生。}
{103}{}{你好！你一定是来自外面的兄弟}
{104}{}{，新的见习生。我叫杰瑞，是你的新室友。我也是个见习生！我一直在努力学习。你是骑士见习生还是抄写员见习生？}
{105}{}{我还没决定。}
{106}{}{骑士。}
{107}{}{抄写员。}
{108}{}{呃。}
{109}{}{是啊，当骑士很棒，他们能参与很多行动，还能建造各种东西。我还没决定，但我自己也倾向于当骑士。我是不是让你觉得无聊了？有些人说我话多，但我觉得他们不理解。我只是有很多话想说。}
{110}{}{不，一点也不。}
{111}{}{我得走了，很高兴认识你。}
{112}{}{是啊，抄写员的工作很有创意。能设计新武器，改造旧武器，还能记录兄弟会每件物品的详细信息。是不是让你觉得无聊了？有些人说我话多，但我觉得他们不理解。我只是有很多话想说。}
{113}{}{是啊，我还在考虑。这真的很难选择，它们都很让人兴奋。对了，如果你想要上铺，告诉我一声，我不介意。}
{114}{}{谢谢，再见。}
{115}{}{你还好吗？也许你需要去看看医生，或者只是需要一些睡眠。好吧，我得回去学习了。再见。}
{116}{}{哦，对了，我很高兴你成为我的新室友。我的上一个室友总是戴着耳塞，我不知道为什么。无论如何，随便放东西在这里，我不占太多空间。你想要上铺吗？如果你想换，我可以换……你不打呼吧？哦，没关系。再见。}
{117}{}{是啊，我也是这么想的。好吧，我很高兴你成为我的新室友。我的上一个室友总是戴着耳塞，我不知道为什么。无论如何，随便放东西在这里，我不占太多空间。你想要上铺吗？如果你想换，我可以换……你不打呼吧？哦，没关系。再见。}
{118}{}{如果我打呼了就告诉我。}
{119}{}{托马斯说我话太多。}
{120}{}{塔卢斯说如果我话少点，我会是个好骑士。}
{121}{}{很高兴再次见到你，室友！}
{122}{}{我昨晚没睡好。}
{123}{}{又见面了。}
{124}{}{我明天要去巡逻。}
{125}{}{几年后我会成为高级见习生。}
{126}{}{这不是你的房间，请离开。}
{127}{}{我想你在杰瑞的房间。}
{128}{}{祝好运，你要和话唠杰瑞同住。}
{129}{}{你在这里干什么？}
{130}{}{你也是新兵吗？}
{131}{}{来参观的？}
{132}{}{你的房间是进门左手边第一个。}
