{100}{}{你看到凯西，这家店的老板。}
{101}{}{抱歉，今天货不多。}
{102}{}{今天想找点什么？}
{103}{}{有什么我能帮忙的吗？}
{104}{}{抱歉，还是没有新货。}
{105}{}{你有护甲出售吗？}
{106}{}{你好。}
{107}{}{您好。}
{108}{}{看到什么喜欢的吗？}
{109}{}{感谢光临。}
{110}{}{很高兴见到你。}
{111}{}{欢迎再来。}
{112}{}{期待很快再见到你。}
{113}{}{再见。}
{114}{}{抱歉，我会尽快补货。}
{115}{}{我想我可能需要多样化经营。}
{116}{}{谢谢。}
{117}{}{感谢你的光临。}
{118}{}{抱歉，如果我没有你需要的东西。}
{119}{}{祝你有美好的一天。}
