{100}{}{你看到一个骑士。}
{101}{}{你看到一个抄写员。}
{102}{}{你在这里做什么？}
{103}{}{你是谁？}
{104}{}{我以前见过你吗？}
{105}{}{这是我的房间，请离开。}
{106}{}{请离开我的房间。}
{107}{}{这不是你的房间。}
{108}{}{新兵的房间在二层。}
{109}{}{你迷路了吗？}
{110}{}{我想你的宿舍在二层。}
{111}{}{我需要一些私人空间。}
{112}{}{你好，很高兴见到你。}
{113}{}{你好。}
{200}{}{嗨}
{201}{}{你好}
{202}{}{日安}
{203}{}{有什么事？}
{204}{}{什么？}
{205}{}{怎么了？}
{206}{}{你想要什么？}
{207}{}{你需要什么？}
{209}{}{走开}
{210}{}{别烦我}
{211}{}{让我一个人待着}
{212}{}{你让我很烦。}
{213}{}{他无视了你}
{214}{}{她无视了你}
