{100}{}{你看到一个醉汉。}
{101}{}{你看到一个顾客。}
{102}{}{你看到一个非常漂亮的女士。}
{103}{}{你看到一个长相奇怪的男人。}
{104}{}{你看到一个赌徒。}
{105}{}{你看到一个女人，她似乎很忙。}
{106}{}{你看到一个女人。}
{107}{}{你看到一个男人。}
{108}{}{你看到一个非常沮丧的赌徒。}
{109}{}{你看到一个佣兵。}
{110}{}{让我一个人沉浸在悲伤中吧。}
{111}{}{你是我最好的朋友。}
{112}{}{你是……（打嗝）我在哪儿？}
{113}{}{你是谁？}
{114}{}{我认识你吗？}
{115}{}{我感觉有点恶心。}
{116}{}{酒水算我的，我是说算你的。}
{117}{}{为什么我看到两个你？}
{118}{}{站住，小子！}
{119}{}{站住，姑娘！}
{120}{}{滚开，废物！}
{121}{}{你降低了这里的档次。}
{122}{}{走开，你会给我带来霉运！}
{123}{}{别打扰我集中精神。}
{124}{}{我一定能赢这个该死的游戏！}
{125}{}{你玩得好吗？}
{126}{}{你看到了吗？那是不可能的！}
{127}{}{我觉得他们在作弊。}
{128}{}{这才是好赔率。}
{129}{}{这绝对没问题。}
{130}{}{什么？我怎么会输？}
{131}{}{这张桌子真倒霉！}
{132}{}{我很忙。}
{133}{}{你没看到我在玩游戏吗？}
{134}{}{下注或者走开。}
{135}{}{别打扰我们，否则我就叫保安了。}
{136}{}{小心点，我和副警长弗莱是好朋友。}
{137}{}{你介意吗？}
{138}{}{不许偷窥！}
{139}{}{我不和人组队。}
{140}{}{我太累了，玩不动了。}
{141}{}{你在做梦，伙计，走开！}
{142}{}{滚出去！}
{143}{}{你以为你在干什么？}
{144}{}{注意你的礼貌！}
{145}{}{我要报警了！}
{146}{}{想都别想！}
{147}{}{滚出去！}
{148}{}{走开！}
{149}{}{你看什么呢？}
{150}{}{你介意吗？}
{151}{}{滚出我们的房间！}
{152}{}{出去！}
{153}{}{你是乐队的一员吗？}
{154}{}{走开，变态！}
{155}{}{你有什么问题？}
{156}{}{趁我生气之前快走。}
{157}{}{自己去找一个。}
{158}{}{她是我的。}
{159}{}{该死！}
{160}{}{你在作弊吗？}
{161}{}{那应该是我的。}
{162}{}{差一点！}
{163}{}{刚刚错过了。}
{164}{}{规则是什么来着？}
{165}{}{我以前很擅长这个。}
{166}{}{一点帮助也没有。}
{167}{}{我不敢相信！}
{168}{}{我就是故意这么做的。}
{169}{}{下注。}
{170}{}{请勿用手触碰，先生。}
{171}{}{赢了！}
{172}{}{抱歉各位，或许下次吧。}
{173}{}{又一个赢家！}
{174}{}{不许动手！}
{175}{}{轮到您了，先生。}
{176}{}{抱歉，这是个无效的赌注。}
{177}{}{就是这样。}
{178}{}{还有人吗？}
