{100}{}{你看到里奇。}
{101}{}{你不该这样做。我得阻止你！}
{102}{}{你不该在这里。你知道我应该杀了你吗？}
{103}{}{你的班结束了。我是来接替你的。}
{104}{}{集散地的避难所检查员。我来检查避难所。让开。}
{105}{}{孩子，抵抗住。现在就结束暴力循环！}
{106}{}{谁告诉你的！先生，如果你攻击我，那将是你一生中最大的错误！}
{107}{}{嗨，孩子！钢铁避难所里有什么？}
{108}{}{太晚了，小子。你死定了。}
{109}{}{呃，是的，runk}
{110}{}{我不该和你说话！快滚！}
{111}{}{终于来了！这里又热又无聊！如果我不需要这份工作养家糊口，我早就让洛伦佐见鬼去了。明天见。}
{112}{}{我不该离开这里，而你不该在这里。快走！}
{113}{}{你们这些集散地官员让我恶心！检查我老板的避难所！接下来是什么，更高的税收？一个人就不能再靠诚实劳动谋生，而不被你们这些官僚控制吗？总有一天我们会反抗的。是的，总有一天普通人会给你们这些肥猫应得的教训。我等不及了。顺便说一句，这不是针对你。我知道你只是做你的工作。我会在你检查时离开。再见。}
{114}{}{别跟我废话！现在就滚出去，否则我就开枪了！}
{115}{}{哦，是吗。没人能欺负里奇·格洛斯特德而不付出代价！}
{116}{}{哦，大约一万集散地币。希望你没打算偷。如果你敢，我就得杀了你。我差点杀过一个人，所以你最好别惹我！}
{117}{}{伙计，你真蠢。哦，抱歉，我不是故意冒犯你。现在我们再试一次。“是”意味着我打爆你的头。“不是”意味着你滚出去。你选哪个？}
{118}{}{啊……是……}
{119}{}{呃，不}
{120}{}{隆克！隆克！}
{121}{}{伙计，我做不到！那就像射杀一只愚蠢的动物。赶紧走，好吗？}
{122}{}{很好。现在快走。我相信你能找到人喂你。}
{123}{}{也许一个runk表示“是”，两个runk表示“不是”。好，“runk”表示我杀了你。“runk，runk”表示你离开。明白吗？}
{124}{}{隆克}
{125}{}{隆克，隆克。}
{126}{}{隆克，隆克，隆克！}
{127}{}{三个runk。该死，这不管用。也许我就无视你，你会自己走开。}
