
#
#	Mountain area random encounter text
#

{100}{}{你差点被雪崩中的一块大石头压扁。}
{101}{}{你毫发无损地逃脱了。}
{102}{}{被移开的岩石带出了一个早已死去的旅行者的遗骸。}
{103}{}{你的腿被落石严重砸伤。}
{104}{}{一些岩石碎片划伤了你的脸和手，但你只是受了轻伤逃脱了。}
{105}{}{辐射蝎子！}
{106}{}{一只特别狡猾的辐射蝎子似乎想要伏击你。}
{107}{}{一只辐射蝎子突然从天而降，袭击了你！}
{108}{}{你偶然发现了一家鼹鼠鼠。}
{109}{}{你差点被雪崩中的一块大石头压扁。}
{110}{}{你毫发无损地逃脱了。}
{111}{}{你毫发无损地逃脱了。被移开的岩石露出了一处金矿。}
{112}{}{你的腿被落石严重砸伤。}
{113}{}{一些岩石碎片划伤了你的脸和手，但你只是受了轻伤逃脱了。}
#
{114}{}{你正在穿越陡峭的悬崖和崎岖的地形。}
{115}{}{幸运的是，你的攀爬技能足以应对。}
{116}{}{你找到一个有小泉水的洞穴，终于得到了久违的好觉。}
#
{117}{}{你从一个岩架上摔下，落在几块尖石上。}
{118}{}{你从悬崖边跌落到下面的岩石地面。}
{119}{}{你偶然闯入了一大群辐射蝎子。}
{120}{}{你发现这里有几只老鼠在觅食。}
{121}{}{你在远处看到一个孤独的旅行者。}
{122}{}{前方地面上满是碎片和尸体，看起来像是一个旧战场。}
{123}{}{你差点被雪崩中的一块大石头压扁。}
{124}{}{你毫发无损地逃脱了。}
{125}{}{你毫发无损地逃脱了。被移开的岩石露出了一处金矿。}
{126}{}{你的腿被落石严重砸伤。}
{127}{}{一些岩石碎片划伤了你的脸和手，但你只是受了轻伤逃脱了。}
{128}{}{你看到一只孤独的辐射蝎子在四处游走。}
{129}{}{巨大的鼹鼠鼠在这里嗅来嗅去。}
{130}{}{你发现这里有几只老鼠在觅食。}
{131}{}{你差点在崎岖的地形上摔倒。这里确实需要一些环境管理。}
{132}{}{你在崎岖的地形上摔倒，痛苦地扭伤了脚踝。}
{133}{}{你在崎岖的地形上摔倒，擦破了皮肤。}
{134}{}{你看到几只老鼠朝你跑来。}
{135}{}{你发现了一些早已死去的旅行者的骨骸。}
{136}{}{你偶然遇到了一群敌对的辐射蝎子。}

