{100}{}{你看到拳击手索尔。}
{101}{}{你看到一个看起来很强壮的肌肉男。}
{102}{}{他有着多年搏斗锻炼出的结实肌肉，步伐轻盈，显然是个技艺高超的拳击手。}
{103}{}{哦。祝你好运。}
{104}{}{朋友，这里不是动武的地方。不过如果你想在拳台上试试我的身手，随时欢迎。}
{105}{}{你想要什么？}
{106}{}{什么事？}
{107}{}{你在这里做什么？}
{108}{}{硬汉啊？我打赌我能打败你。}
{109}{}{我叫}
{110}{}{。只是随便看看。}
{111}{}{[索尔爽朗地笑着。] 我是个拳击手！}
{112}{}{啊，我能揍扁你。}
{113}{}{嗯，有什么事？}
{114}{}{呃，不用了，谢谢。}
{115}{}{索尔失去意识。}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{}
{122}{}{}
{123}{}{}
{124}{}{ [索尔爽朗地笑着。]}
{125}{}{ [索尔威胁性地笑着。]}
{126}{}{好吧，这应该很快。}
{127}{}{要么动手，要么闭嘴。}
{128}{}{嗯，如果你想找人把你那张丑脸打得好看点，你来对地方了。}
{129}{}{我是索尔。}
{130}{}{呃，不用了。我可以问你几个问题吗？}
{131}{}{你在废城住了很久了吗？}
{132}{}{嗯，很高兴认识你。再见。}
{133}{}{是的。}
{134}{}{我在这里住了一辈子。从小就在这长大。}
{135}{}{你能告诉我关于废城的事情吗？}
{136}{}{你是怎么成为拳击手的？}
{137}{}{嗯，陌生人，我为吉兹莫工作。他是那家大赌场的老板。这里的拳手薪水不错！你还想知道什么？}
{138}{}{这里有什么可以做的？}
{139}{}{你能告诉我一些关于吉兹莫和那个赌场的事吗？}
{140}{}{打了几年拳。}
{141}{}{小时候总是和兄弟们打架。有一次，一小队掠夺者袭击了废城，我在他拿枪之前就把他打趴下了。真是运气，不过吉兹莫赞助了有组织的比赛，而我需要钱。从那以后就一直在打拳。}
{142}{}{你的兄弟们怎么样了？}
{143}{}{这个镇上有什么可以做的？}
{144}{}{你能告诉我一些关于你老板的事吗？}
{145}{}{如果你只是想找些补给，可以去东南边的基利安·达克沃特的商店。你也可以在附近的撞击旅馆过夜。如果打算多待一阵子，可以去污泥坑喝一杯，但要小心骷髅帮。}
{146}{}{骷髅帮是谁？}
{147}{}{那么，告诉我更多关于赌场的事。}
{148}{}{吉兹莫的赌场是大家去赌博的地方。有很多游戏，你会玩得很开心！这是中心城这边最好的地方！}
{149}{}{这里还有什么可以做的？}
{150}{}{几年前，我的兄弟詹姆斯在一次掠夺者袭击中被杀。不久之后，我的另一个兄弟达雷尔收拾了一些东西，向南出发去一个叫做辉光的传说之地，寻找古代的宝藏之类的东西。他再也没有回来。}
{151}{}{你为什么留在废城？}
{152}{}{呃，我们能换个话题吗？}
{153}{}{很遗憾听到你的损失。}
{154}{}{你对这个传说中的地方辉光了解多少？}
{155}{}{谢谢。已经好几年了，但我仍然不太愿意谈论它。}
{156}{}{那么，我可以问你几个问题吗？}
{157}{}{我住在这里。我喜欢拳击，和特里什过得很好，没有想去别的地方的念头。}
{158}{}{哦，那很好。介意我们换个话题吗？}
{159}{}{是的，我见过特里什。}
{160}{}{嗯，什么事？}
{161}{}{有什么我能帮忙的吗？}
{162}{}{这里有什么好玩的？}
{163}{}{能给我讲讲你的老板吗？}
{164}{}{[你拍了拍你的武器] 我想让你见见我的小伙伴。}
{165}{}{谢谢你的聊天。回头见。}
{166}{}{Skulz是一群很糟糕的家伙，他们常在Crash House后面和Skum Pitt出没。小心他们，他们喜欢玩刀。}
{167}{}{谢谢你的提醒。我会小心的。}
{168}{}{我明白了。还有其他可以告诉我的吗？}
{169}{}{嗯，记得别乱动手哦。}
{170}{}{她对我来说很重要。}
{171}{}{[Saul皱眉] 但她不喜欢我打拳击。她似乎不明白这是我想做的事。}
{172}{}{她是关心你的安危。她可能不忍心看到你为Gizmo挨打并冒生命危险。如果你们不妥协，你可能会失去她。}
{173}{}{我觉得她是在担心你。}
{174}{}{那么，我们聊点别的吧？}
{175}{}{好吧，回头见。}
{176}{}{我从没这样想过。我以为她只是单纯不喜欢拳击。我想我得和她多谈谈这事。谢谢。}
{177}{}{啊，她只是单纯不喜欢拳击而已。}
{178}{}{那么，我们能聊点别的吗？}
{179}{}{回头见。}
{180}{}{又是你。现在有什么事？}
{181}{}{又见面了。}
{182}{}{我来教你点礼貌。}
{183}{}{我需要和你谈谈Trish的事。}
{184}{}{能告诉我关于Junktown的事吗？}
{185}{}{据我所知，Glow是一个在夜晚发光的大坑。它应该在很远很远的南方，但我不知道具体位置。传说那里住着各种各样的变种怪物，他们守护着战争前的科技。}
{186}{}{我明白了。谢谢你的信息。}
{187}{}{有趣。你能再多告诉我一些吗？}
{188}{}{没了脑袋可就难办了，傻大个。}
