{100}{}{你注意到一个似乎正在运作的监控摄像头。}
{101}{}{你注意到隐藏的枪支正在跟踪你的动作。}
{102}{}{隐藏的枪口开火了！你扭动躲闪，成功避开了伤害！}
{103}{}{隐藏的枪口开火了！你扭动闪避，但还是被擦伤了。}
{104}{}{你受到了}
{105}{}{点伤害。}
{106}{}{隐藏的枪口开火了！你惊慌失措，绊倒摔倒，所幸只受了轻伤。}
{107}{}{你受到了}
{108}{}{点伤害。}
{109}{}{隐藏的枪口开火了！你被击中了！}
{110}{}{你受到了}
{111}{}{点伤害。}
