{100}{}{你看到赛斯，阴影沙地的守卫队长。}
{101}{}{你！你已经困扰我们村庄够久了。我会亲手杀了你！}
{102}{}{你这种人不会带来任何好事。我会杀了你，让废土少一个怪物。}
{103}{}{不太聪明，是吧？小心辐射蝎子，别惹麻烦。}
{104}{}{蝎子！}
{105}{}{再见。}
{106}{}{你看起来像是那些袭击者之一。我们在阴影沙地严密监视。你想要什么？}
{107}{}{我要你所有的钱！}
{108}{}{我想要一些信息。}
{109}{}{咕噜？}
{110}{}{你好，我叫赛斯。我能帮你什么忙？}
{111}{}{我想要一些信息。}
{112}{}{哇哇！}
{113}{}{信息？你想知道什么？}
{114}{}{我能为你做些什么？}
{115}{}{我想了解辐射蝎子。}
{116}{}{我想了解袭击者。}
{117}{}{我想了解这个地方。}
{118}{}{带我去辐射蝎子洞穴。}
{119}{}{洞穴！}
{120}{}{没有其他的了，谢谢。}
{121}{}{你现在想要什么？}
{122}{}{那些该死的辐射蝎子自从我们搬到这里就一直在攻击我们的布拉明。几乎每周都有人在试图把它们赶出围栏时中毒。上周它们抓走了我弟弟贾维斯。我们的医生拉兹洛正在尽快寻找解毒剂。嘿，如果你有办法帮助我们，为什么不去找我们的领袖阿拉德什谈谈。}
{123}{}{有几个袭击者团伙。我组织像伊恩这样的守卫来帮助抵御他们。在这里东南方向有一个团伙。小心他们。}
{124}{}{阴影沙地是一个和平的社区。我们有自己的灌溉系统，所以可以自己种植食物。如果不是受到袭击者和辐射蝎子的困扰，我们就没有问题了。}
{125}{}{你确定要我给你指路去辐射蝎子洞穴吗？我不能去，但我可以告诉你怎么走。}
{126}{}{是的。}
{127}{}{不。}
{128}{}{好的，准备好去洞穴时告诉我。}
{129}{}{[完成]}
{130}{}{嗯哼。}
{131}{}{嗯嗯。}

{200}{}{我们整个镇子都感谢你消灭了蝎子。谢谢你。}
{201}{}{多亏了你，我们现在安全了。}
{202}{}{你确定要回去吗？那是一段漫长的旅程，而且你已经消除了威胁。}
{203}{}{好的。祝你在这里过得愉快。}
{204}{}{欢迎来到阴影镇，陌生人。在这里请收起武器。}
{205}{}{你好，陌生人。欢迎来到阴影镇。}
{206}{}{你应该去找我们的领袖阿拉迪什。他喜欢见所有的访客。他应该在我们南边的市政厅。}

{300}{}{感谢达摩你来了，流浪者。我的女孩……呃，坦迪，阿拉迪什的女儿，被绑架了。我们相信是袭击者抓走了她。}
{301}{}{这些袭击者在哪里？}
{302}{}{哇，真不幸。好吧，回头见。}
{303}{}{抱歉，我希望我能帮上忙。}
{304}{}{这很糟糕，但我得先处理那些蝎子。它们对整个镇子构成了威胁。}
{305}{}{坦迪在哪？你为什么还没救她？}
{306}{}{在对付那些家伙之前，我需要更多的补给。}
{307}{}{我决定那个小丫头不值得冒险。}
{308}{}{我正在处理这件事。}
{309}{}{我想先解决你们的蝎子问题。}
{310}{}{我以为你是个好人。那就这样吧。}
{311}{}{他们在东南方。请快点。我不知道他们会对她做什么。}
{312}{}{好吧，我会把她带回来的。}
{313}{}{我没说过我要帮忙，我有自己的问题要解决。}
{314}{}{这份工作对你来说值多少钱？}
{315}{}{我得帮助我自己的人。对不起。}
{316}{}{我就知道你是个无情的雇佣兵。放心，我们会好好报答你救她的。}
{317}{}{如果你不告诉我你会给我多少，我就不接这活。}
{318}{}{好吧，我会帮你解决的。}
{319}{}{抱歉，我得走了。}
{320}{}{你这个混蛋！}
{321}{}{请快点。只有天知道他们对她做了什么。}
{322}{}{我希望你能先救出坦迪，陌生人，但如果你愿意帮我们对付辐射蝎子，我会带你去。}
{323}{}{好的，带我去辐射蝎子那里。}
{324}{}{我改变主意了。再见。}
{325}{}{太好了。我一会儿回来，到时候你可以带我去。}

{1000}{}{可汗}
{1001}{}{加尔}
{1002}{}{废城}
{1003}{}{阴影镇}
{1004}{}{枢纽}
{1005}{}{水}
{1006}{}{坦迪}
{1007}{}{阿拉戴什}
{1008}{}{赛斯}
{1009}{}{拉兹洛}
{1010}{}{沙地}
{1011}{}{蝎子}
{1012}{}{辐射蝎子}
{1013}{}{蝎子们}
{1014}{}{辐射蝎子们}

{1100}{}{他们是一个无法无天的团伙，假装是来自遥远过去的人。}
{1101}{}{他是可汗的首领。他是曾经在阴影镇出现过的最危险的人之一。他以铁腕统领着掠夺者部落。}
{1102}{}{往西南方向走4到6天。偶尔有不错的交易，但更多时候，他们试图坑我们。}
{1103}{}{你正站在这里。}
{1104}{}{比废城更南边。枢纽是我听说过的最大城市。那里至少有一千人。}
{1105}{}{抱歉，我帮不了你。}
{1106}{}{她是阿拉戴什的女儿。将来她可能会领导我们，但她必须学会磨练自己的方式。}
{1107}{}{他是我们社区的领袖，也是个真正的英雄。你总能在公共大厅找到他。}
{1108}{}{那就是我。我和阿拉戴什一起工作，确保每个人的安全。}
{1109}{}{我们的医生。如果你受伤了，就去找他。}
{1110}{}{你正站在这里。}
{1111}{}{这些讨厌的生物有致命的毒液。}
{1112}{}{这些讨厌的生物有致命的毒液。}
{1113}{}{这些讨厌的生物有致命的毒液。}
{1114}{}{这些讨厌的生物有致命的毒液。}
