{100}{}{你因带回坦迪而获得400点经验值。}
{101}{}{向南望去，你看到一个被土坯墙围绕的宁静村庄。}
{102}{}{这里只剩下一个小棚屋。幸运的是，你的记录显示这里有一个通往15号避难所的次要入口。}
{103}{}{你看到一座小建筑，旁边有一排帐篷。居民看起来又脏又凶。}
{104}{}{你来到一个中等规模的城镇。一堵废弃汽车墙阻挡了轻松进入。城镇上空弥漫着淡淡的烟雾。}
{105}{}{向南你看到一座大城市。外围的农场环绕着城镇。这片沙漠绿洲中充满了生机。}
{106}{}{你走近一座阴暗破败的城市。几乎看不到生命迹象。死亡的气息笼罩着这个地区。}
{107}{}{北边有一座被铁丝网围住的小建筑。穿着重甲的守卫在此巡逻，显得很有威胁性。}
{108}{}{北方有一个巨大的陨石坑。}
{109}{}{在东北方向，你可以看到变种人守卫驻守在山体中的一个加固地点前。}
{110}{}{一座大型华丽的建筑高耸入云。人群在它前面漫无目的地走动。}
{111}{}{你可以看到北边有一个仓库，周围环绕着发光的粘液护城河。}
{112}{}{一座大型加固工厂矗立在前方，墙上涂满涂鸦，枪口威胁地对外。}
{113}{}{在这里，部分重建的夜总会和小型哨所明显显示出帮派活动的迹象。}
{114}{}{在城市的中心，一座伟大的图书馆被加固和修复，以庄严而优雅的姿态矗立着。你感到一丝宁静。}
{115}{}{一个被围栏围住的村庄，守卫在巡逻，南方等待着挑战。}
{116}{}{你看到地上有一个巨大的脚印。你搜索了一番，但没有找到其他踪迹。}
{117}{}{烧焦的痕迹和灰烬覆盖了这个区域。}
{118}{}{这个区域看起来像是被高压燃烧弹袭击过。}
