{100}{}{你看到鲨鱼。}
{101}{}{你看到一个牙齿被磨尖的男人。}
{102}{}{你这个贱人！}
{103}{}{嘿，新鲜的诱饵！那么，是什么把你带到我们的地盘，伙计？来找点乐子吗？当然，是你的代价。}
{104}{}{其实，我是来踢屁股和嚼口香糖的……你可以猜到剩下的。}
{105}{}{你们这里有什么好玩的？}
{106}{}{呃，我只是路过。再见。}
{107}{}{只是过来喝一杯，找点……乐子。}
{108}{}{咕噜！}
{109}{}{我们专打像你这样的冒牌货！}
{110}{}{没那么简单！没有人能不付痛苦税就走进我们的地盘。}
{111}{}{我觉得你不错。伙计们，抓住她。}
{112}{}{让我介绍一下税务员。他叫大锤先生！}
{113}{}{我不这么认为！}
{114}{}{今晚的娱乐节目，我们决定砸了这个地方！嘿，拿走你能带的东西，让我们看看血流成河吧？}
{115}{}{我想我只是喝杯酒。}
{116}{}{砸了抢？算我一个！}
{117}{}{今晚不行，我头疼。}
{118}{}{不，我更想吃点东西……也许烤鲨鱼！}
{119}{}{啊，你这个失败者。快回你妈那里去吧。}
{120}{}{又是你？天啊，有些人就是学不乖！}
{121}{}{只是进来喝一杯。}
{122}{}{只是路过，没事。}
{123}{}{咕噜！}
{124}{}{不错的主意。我也来一杯。当然，喝啤酒总得配点血腥场面！}
{125}{}{我以为你现在应该明白了，快滚。看来我错了。好吧，至少打你会很有趣！}
{126}{}{我们会回来的，老家伙。这事没完。}
