{100}{}{你看到塔卢斯。}
{101}{}{你好，你一定是外来的见习者。很高兴见到你。我能为你做些什么？}
{102}{}{你们组织的领导是谁？}
{103}{}{那么，你是这里的负责人吗？}
{104}{}{我怎样才能获得更好的武器和装备？}
{105}{}{查嘎！}
{106}{}{那是由长老议会领导的。更具体地说，是大长老麦克森。长老们在这里做出所有重大决策。如果你需要和他们交谈，可以在四楼找到他们。}
{107}{}{那么你是做什么的？}
{108}{}{不，我们由长老议会指导。大长老麦克森是负责人。如果你需要和他交谈，可以在四楼找到他。}
{109}{}{我真的需要一些更强大的火力。}
{110}{}{我是高级骑士，罗姆布斯的得力助手。我们负责骑士和武士。目前我在监督训练演习。我们正在为任何情况做好准备。}
{111}{}{你们在为什么做准备？}
{112}{}{我怎样才能获得一些武器和装备？}
{113}{}{有传言说有一支大部队在山里和沙漠中活动。随着失踪的商队和这些传言，我们只是小心行事。}
{115}{}{真的吗？好的，谢谢。}
{116}{}{你很着急吗？作为见习者，你有权获得一些物资。我会为你申请战斗护甲和三份弹药订单，子弹你可以自己选择。去隔壁找迈克尔领取补给。}
{117}{}{我非常感激，但你有没有可能提供一把武器，帮助我在外面提高生存几率？}
{118}{}{谢谢，那高科技武器呢？}
{119}{}{就这些？你一定是在开玩笑！}
{120}{}{我理解，但我真的时间紧迫，急需更强大的火力。}
{121}{}{太好了！我现在该做什么？爬上最高的山？}
{122}{}{听起来不错。你为什么不现在就开始呢。}
{123}{}{好吧，我可能会破例。显然你受过良好的训练。如果没有，你也不会完成大长老交给你的那个疯狂任务。}
{124}{}{有时我不知道他是在寻求外部帮助，还是想淘汰愚蠢的人。无意冒犯。我告诉你，我现在有点麻烦，因为我派出去的侦察兵一直没有回来。}
{125}{}{这是我的主意，我有点因此受到责难。如果你能查明他们的下落，我会让你不虚此行。}
{126}{}{我会考虑的。}
{127}{}{抱歉，见习者。请不要挥舞你的武器。除非你打算使用它，否则请收起来。}
{128}{}{收起你的武器，见习者。你不是在训练演习中，把它收起来。}
{129}{}{你能不能别这样挥舞你的武器？你应该……哦，算了。}
{130}{}{又见面了，兄弟}
{131}{}{. 我能帮你什么吗？}
{132}{}{这里有哪些重要人物？}
{133}{}{能再告诉我关于这些重要人物的事情吗？}
{134}{}{我怎么才能获得更好的装备和武器？}
{135}{}{能不能给我一些更多的弹药？}
{136}{}{没什么，谢谢。}
{137}{}{我可以帮你这个忙。作为新晋成员，你有资格获得一些东西。我会申请战斗护甲的批准，并给你三份弹药订单，你可以选择子弹类型。}
{138}{}{去隔壁房间找迈克尔拿补给。}
{139}{}{你穿的那套金属战斗服呢？}
{140}{}{谢谢，那有没有什么高科技武器？}
{141}{}{我们都很重要，不过我知道你指的是谁。}
{142}{}{那没问题。你应该多了解你的同胞弟兄。虽然我们人数众多，记住所有人可能会有些困难。}
{143}{}{有罗姆布斯，他是我们的首席骑士，号称骑士大师。然后是弗瑞，她是首席抄写员。当然，我们不能忘记尊贵的最高长老，马克森。}
{144}{}{告诉我关于罗姆布斯的事情。}
{145}{}{告诉我关于弗瑞的事情。}
{146}{}{告诉我关于马克森的事情。}
{147}{}{罗姆布斯是我最好的朋友、导师、偶像和父亲般的角色集于一身。他性格可能有点粗鲁，但在他的职位上必须如此。}
{148}{}{如果你需要找他谈话，他通常在他的办公室……哦不，是房间里。这在这个层的另一边，守卫室对面。}
{149}{}{当然有。她在二层，学习室旁边。}
{150}{}{谢谢，再见。}
{151}{}{谢谢。这就是我想知道的全部。}
{152}{}{弗瑞是我所认识过的最聪明的人之一。我认为她天生就对物理和化学有着天然的理解。}
{153}{}{她把每一分每一秒都用于研究或反复分析她能拿到手的任何东西。如果你需要找她谈话，她通常在她的房间里，三楼。}
{154}{}{她在二层。只需下到二楼，左转。刚过学习室你就能看到。我得回去继续工作了。如果你还有其他问题，就问吧。}
{155}{}{如我所说，她在二层。你不会错过的。二楼除了学习室之外就只有她的房间是重要的。}
{156}{}{好的，再见。}
{157}{}{马克森是个硬汉。他是我们的创始人之一的曾曾孙……还是曾曾曾孙？不管怎样，他是我们的最高长老。}
{158}{}{你为自己建立了不错的声誉。我调查过的人对你的评价很高。我认为你不需要任何帮助，你似乎很有能力。不过，如果你帮我解决一个小问题，我或许可以给你一些奖励。}
{159}{}{非常感谢，再见。}
{160}{}{这就够了，谢谢。}
{161}{}{你真让我心烦，小家伙。你现在想要什么？}
{162}{}{没什么，只是想听听你悦耳的声音。}
{163}{}{抱歉，没看到你在那儿。}
{164}{}{查托维罗！}
{165}{}{呃。}
{166}{}{别浪费我的时间！}
{167}{}{你是怎么进来的？从我眼前消失。}
{168}{}{如果你真的需要，我可以给你多一点弹药。我会在你能和迈克尔谈话前批准。}
{169}{}{我刚给了你一些。你应该学会更节省地使用弹药。}
{170}{}{抱歉，你这周已经拿得够多了。你得用现有的凑合一下。我们的弹药不是取之不尽的。}
{171}{}{我听说了你做的一些事情，我们不喜欢杀害儿童的人。长老们似乎认为你能提供一些帮助，但我不想和你有任何瓜葛。}
{172}{}{我只杀了一个。}
{173}{}{你不知道事情的全貌。}
{174}{}{我不需要向你解释。}
{175}{}{你已经为自己建立了相当的声誉。我觉得你不需要任何帮助，看起来你很有能力。不过，我确实有件事情需要调查，如果你能帮我，我可能也能帮你。}
{176}{}{当然。有什么问题？}
{177}{}{不，谢谢。谢谢你的无用之恩。}
{178}{}{抱歉，我不能。不过谢谢你的护甲。}
{179}{}{既然你能独自在废土中生存，我想你应该很有能力。不过，我确实有个问题需要帮助，如果你能帮我，我可能会奖励你。}
{180}{}{不。我觉得你应该离开。}
{181}{}{不久前我派了一名见习者去枢纽，我们还没有收到他的消息。如果你能查明他的下落，我将非常感激。}
{182}{}{我会去查查看。}
{183}{}{我会试试，但不能保证。}
{184}{}{我让你离开。}
{185}{}{只杀一个？我想我们的组织帮不了你。再见。}
{186}{}{我不需要知道事情的全貌。再见。}
{187}{}{谢谢。我会记住这点，当我看到你积累了足够的经验时，我可能会给你一些我们组织的特别奖励。}
{188}{}{真的吗？是什么？}
{189}{}{现在就给我！}
{190}{}{听起来不错。再见。}
{191}{}{我不该说，但这不是武器。这是我们教团中只有精英才能拥有的东西，不过既然你来自外界，可能更需要它，我或许可以破例。}
{192}{}{你不能告诉我吗？}
{193}{}{好吧，再见。}
{194}{}{我想你可能已经有了想法。就到此为止吧。}
{195}{}{不，我不是，我认为你应该离开，‘新兵’。}
{196}{}{只有骑士才能穿动力装甲，总有一天你也能获得穿戴它的资格。}
{197}{}{谢谢，那高科技武器呢？}
{198}{}{看来我们教团里终于有了一个聪明的新成员……[塔卢斯盯着你。] 别在我面前得意忘形，新兵。我没那个心情，也没那个耐心！}
{199}{}{我以为你比这聪明。我没有必要给你任何东西。你很幸运我现在没把你赶出去。我想你应该离开，趁我还没改变主意。}
{200}{}{没关系。你找到的任何东西都会有帮助。}
{201}{}{兄弟}
{202}{}{！我收到了乔纳森兄弟的消息。谢谢你救了他。}
{203}{}{我知道德克已经死了，你比我想象的还要有才干，这可不简单。}
{204}{}{我们会让德克为他的所作所为付出代价，你有我的承诺。}
{205}{}{不客气。}
{206}{}{卢普？}
{207}{}{你好，陌生人！我听说是你让我们失踪的新兵安全归来的。}
{208}{}{我也知道德克已经死了，你对我们的兄弟会是个很大的资产。}
{209}{}{我们这里不容忍化学品使用者。我建议你去看医生，把自己清理干净。}
{210}{}{至于你的奖励，我会给你以下选择之一：}
{211}{}{那么你想要哪个？}
{212}{}{火箭发射器。}
{213}{}{激光手枪。}
{214}{}{超级大锤。}
{215}{}{让我想想。}
{216}{}{我现在就给你授权。去迈克尔那里领取吧。}
{217}{}{，是时候让你穿上你自己的动力装甲了。对于我们教团的新成员来说，这是一个非常特殊的特权。穿上我们的动力装甲，作为你在废土行走时的希望象征，因为总有一天，当世界准备好时，我们将重返地面，恢复我们满目疮痍的地球。恭喜你，你让我们所有人都感到非常自豪。我会把授权发给迈克尔。}
{218}{}{我看到已经有人给了你动力装甲。我本想亲自给你，不过没关系。我希望它能在你的任务中帮助你。}
{219}{}{注意你的动作！}
{220}{}{注意，大家。}
{221}{}{不许偷懒！}
{222}{}{在那边规矩点，否则你就得去夜间巡逻了。}
{223}{}{安静点，别让我把隆布斯叫来。他会揍扁你们的。}
{300}{}{请，如果你需要什么，早上来找我。}
{301}{}{我早上会在训练大厅。到时候来找我。}
{302}{}{你在这里干什么？这不是你的房间。}
{303}{}{晚安，新兵，早上再来找我。没那么急。}
{304}{}{我累了，想去睡觉，请离开。}
{305}{}{你平时也会打扰别人住的地方吗？}
{400}{}{你可以一直……等一下。直视我的眼睛……我就知道。你该少碰化学药品，它们会把你搞得一团糟。如果不注意，你会变得像中心城的瘾君子一样。那么，你需要什么？}
{401}{}{你们有医生吗？我受伤了。}
{402}{}{你们有医生吗？}
{403}{}{我不想再爬那座山了。}
{404}{}{你们的医生在哪里？}
{406}{}{嗯，我不知道。你可能已经证明了自己是个新兵，但这并不意味着我们会把武器交给可能不合格的人，尤其是个外来者，无意冒犯。}
{407}{}{动力装甲。}
{408}{}{你获得了}
{409}{}{经验值，因拯救了新兵。}
