{100}{}{你看到一个高度先进的钢铁兄弟会计算机。}
{101}{}{你被拒绝访问这个终端。}
{102}{}{课程在六小时后结束。你感到筋疲力尽。}
{103}{}{你已经吸收了所有能学到的东西。}
{200}{}{你看到一台计算机。你看到一些可能是人类尸块的东西。}
{201}{}{你摆弄了一会儿计算机，但无法突破安全系统。}
{202}{}{这台计算机运行正常。}
{203}{}{你发现了一个关于西北方秘密基地的有趣数据文件。}
{204}{}{你获得了}
{205}{}{经验值，因为你成功入侵了这台计算机。}
