{100}{}{安保站}
{101}{}{此终端“泰利尔”控制特种部队行动。请提供语音授权。}
{102}{}{努娜！}
{103}{}{帮帮我。我受伤了。}
{104}{}{让我进去。}
{105}{}{我是}
{106}{}{。让我通过。}
{107}{}{你在这里做什么？}
{108}{}{语音未识别。安保系统状态：已武装。}
{109}{}{我是蓝色等级的安保系统。所有系统已武装。}
{110}{}{你能解除系统武装吗？}
{111}{}{战争结束后为什么系统仍然武装？}
{112}{}{谢谢。}
{113}{}{我被编程为在授权人员输入正确语音代码前保持系统武装。}
{114}{}{你能为我解除系统武装吗？}
{115}{}{再见。}
{116}{}{语音覆盖：伽马德尔塔德尔塔。解除所有系统武装。}
{117}{}{你没有授权。访问被拒绝。}
{118}{}{代码无效。访问被拒绝。}
{119}{}{语音覆盖：伽马奥米克戎德尔塔。解除系统武装。}
{120}{}{语音覆盖：奥米克戎德尔塔德尔塔。解除系统武装。}
{121}{}{语音覆盖：阿尔法德尔塔德尔塔。解除系统武装。}
{122}{}{语音覆盖：德尔塔奥米克戎伽马。解除系统武装。}
{123}{}{再见。}
{124}{}{语音覆盖确认。正在解除安保系统武装。}
{125}{}{我没有收到其他命令。网络访问不可用；中央处理器ZAX似乎已被摧毁。}
{126}{}{好吧。语音覆盖：西格玛阿尔法德尔塔。解除系统武装。}
{127}{}{再见。}
{128}{}{安保系统当前已解除武装。}
