{100}{}{你看到一位年迈的女性。}
{101}{}{你看到阿加莎。}
{102}{}{这个女人满脸皱纹，头发灰白，但步伐轻快，性格开朗。}
{103}{}{你是个坏人。我不想和你有任何瓜葛。}
{104}{}{当我们的年轻人受到威胁时，这是件可怕的事情。失去坦迪将是一个巨大的损失。}
{105}{}{嗯。}
{106}{}{好的。}
{107}{}{为什么？}
{108}{}{你是什么意思？}
{109}{}{我知道你会尽力的，亲爱的。找到坦迪，帮助她逃离那些野兽，把她送回阿拉戴什。你将为这个社区做一件好事，同时也会积累善业。}
{110}{}{阿拉戴什非常爱他的女儿。正是这种爱让他成为他现在的样子，并成为这个社区的支柱。没有这种爱，他将迷失，而阴影沙地也会随之衰落……}
{111}{}{我会尽力的。再见。}
{112}{}{我需要一些帮助。}
{113}{}{嗯……我们再看看。}
{114}{}{我感觉她被囚禁了。她是仇恨的目标。那种仇恨在东南方向非常强烈。我相信你会在那里找到她。祝你好运。}
{115}{}{谢谢。}
{116}{}{你还没听说吗？坦迪失踪了。我觉得她被绑架了。阿拉戴什非常痛苦。这真是件可怕的事情……}
{117}{}{我听说你救了坦迪。那是正确的选择。你的业力很强。我对你的未来充满希望。}
{118}{}{听到坦迪的事我很难过。她是个如此聪明的年轻女性。她本可以在生活中有所作为。}
{119}{}{你好。你一定是大家都在谈论的陌生人。[阿加莎叹了口气。]我能帮你什么忙？}
{120}{}{嗯。}
{121}{}{你是谁？}
{122}{}{你看起来很疲惫。有什么问题吗？}
{123}{}{你为什么看起来这么累？}
{124}{}{别跟我说话，老太婆。}
{125}{}{你需要的帮助超出了我能提供的范围，孩子。愿达摩与你同在。}
{126}{}{我叫阿加莎。我是阴影沙地的讲故事者。我的工作是保存历史，以便我们记住并永不遗忘。}
{127}{}{给我讲个故事。}
{128}{}{好吧，随便。}
{129}{}{不忘记是件好事。}
{130}{}{对不起，孩子，我现在很累。我需要休息。请稍后再来。}
{131}{}{非常正确。[阿加莎盯着你看了一会儿。]年轻人记住是好的，但在历史的洪流中行动很难。有时候，我们所走的道路是由很久以前的事件决定的。愿达摩与你同在。我需要休息一会儿。等我恢复了，再来找我，我们再聊。}
{132}{}{谢谢你的关心。我只是老了，仅此而已。我晚上无法入睡。我闭上眼睛……[阿加莎停顿了一下。]但我得不到休息。请原谅，这只是我年迈的疲惫……}
{133}{}{对不起，我很累。你能稍后再来吗？}
{134}{}{爸爸。}
{135}{}{好的。}
{136}{}{你为什么这么累？}
{137}{}{我晚上睡不好觉，孩子。一定是因为我的年纪。}
{138}{}{你好，孩子。你看起来很好。你让我想起了我自己的孩子。}
{139}{}{嗯。}
{140}{}{那我想听个故事。}
{141}{}{很高兴你感觉好些了。}
{142}{}{谢谢。再见。}
{143}{}{你确实让我想起了我的孩子。事实上，就像她几个月大的时候一样。}
{144}{}{谢谢你。达摩总是说，种下礼貌的农夫在季节结束时会走得轻松。}
{145}{}{请给我讲个故事。}
{146}{}{这个达摩听起来像个傻瓜。}
{147}{}{你侮辱了你的长辈。你应该更懂事。}
