{100}{}{你看到全能商店的米奇。}
{101}{}{今天有什么可以帮您的吗？}
{102}{}{我想买点东西。}
{103}{}{我想卖点东西。}
{104}{}{没事，谢谢。}
{105}{}{醉汉。}
{106}{}{好的，这是我有的东西。}
{107}{}{太好了，我一直在寻找新东西。}
{108}{}{抱歉，我听不懂你在说什么。等你脑子清醒点再来吧。}
{109}{}{谢谢，欢迎再来。}
{110}{}{你看到军火商杰克。}
