{100}{}{你看到托恩。}
{101}{}{你看到一个巨大的儿童会成员。}
{102}{}{男人}
{103}{}{女人}
{104}{}{[完成]}
{105}{}{[更多]}
{106}{}{抱歉，伙计，但你已经和我们走到了无法回头的地步。该走了！}
{107}{}{抱歉，女士，但你已经和我们走到了无法回头的地步。该走了！}
{108}{}{我为什么要和一个到处杀小孩的人说话？滚开！}
{109}{}{我听说你挺厉害的。但托恩不吃这一套。你有话要说还是想动手？来吧！}
{110}{}{和平，兄弟！我只是来看看。}
{111}{}{我对让你印象深刻没兴趣。你有聪明的话要说就说吧！}
{112}{}{动手？先生，我可不喜欢瘦弱的小男孩。}
{113}{}{你想要什么？}
{114}{}{你话太多了。}
{115}{}{你想死，我想杀人。正合我意。}
{116}{}{哇！}
{117}{}{伙计，我已经跟你说过了！把你的废话带到别处去！}
{118}{}{男孩}
{119}{}{女孩}
{120}{}{嘿，你以为你的武器能给你赢得尊重？它只会给你挖个坟墓，伙计。收起来吧。}
{121}{}{嘿，你以为你的武器能给你赢得尊重？它只会给你挖个坟墓，姑娘。收起来吧。}
{122}{}{你想要什么，你这个愚蠢的僵尸？滚开，否则我打烂你的脸。}
{123}{}{我在找个聪明人告诉我这里到底发生了什么！}
{124}{}{如果牧师们听到你这么说，他们会怎么想？}
{125}{}{随时奉陪，伙计。我一直在等一场好架！}
{126}{}{嘿，有什么问题？喝几杯我们就是朋友了！}
{127}{}{你知道吗，即使是小孩也能对你的膝盖施加足够的压力让你终生残废？我想你会想知道的。}
{128}{}{你想和托恩说话？可以。但如果我听到“赞美”这个词，我就杀了你。}
{129}{}{你不太喜欢礼拜仪式？}
{130}{}{你有什么问题，伙计？}
{131}{}{我想和负责人谈谈。}
{132}{}{当然。唯一值得我赞美的是一瓶辐射蝎子酒。}
{133}{}{好吧。我们中第一个说那个词的人就得死。成交？}
{134}{}{你好，小姐。我是托恩，2000磅重的主宰最强战士。我也被FEV进化成了你需要了解的东西。来吧，宝贝。}
{135}{}{绝对不可能。}
{136}{}{这有点太快了。我们还是先互相了解一下吧。}
{137}{}{你好。我被FEV进化了，所以任何惹恼我的人都会死。别惹我，小个子。}
{138}{}{去别处看看。托恩不喜欢你的陪伴。}
{139}{}{好吧。你想直说？有时候杀戮是必要的。有时候我甚至喜欢它。但我听说你总是喜欢杀戮。每次我遇到一个疯子，不是他死就是托恩死。托恩还在这里。所以你还是去别处吧。}
{140}{}{伙计，我可能会喜欢你。你要么是个不可思议的混蛋，要么是有胆量。无论哪种情况，只要你不惹我，托恩都没问题。你想加入吗？}
{141}{}{和平与爱去哪了？}
{142}{}{有什么要求？}
{143}{}{绝对不可能，伙计。}
{144}{}{我想干什么就干什么。让我们开始吧！}
{145}{}{看你受苦。来吧，伙计，给我我想要的。}
{146}{}{小心你的愿望。你可能不喜欢得到的东西。}
{147}{}{我宁愿做你的朋友。}
{148}{}{你不值得我浪费时间。}
{149}{}{来吧。先动手吧。最后一招是我的。}
{150}{}{好吧。谈话结束。动手吧。}
{151}{}{我只是想聊聊。}
{152}{}{你死定了……}
{153}{}{该死！你比僵尸还蠢！快滚！}
{154}{}{主宰想要和平，他想让我们为他实现，所以我们要好好享受。明白吗？}
{155}{}{是的，但肯定还有别的事情发生。}
{156}{}{主宰真的想要和平还是他只想要杀戮？}
{157}{}{这个主宰是谁？}
{158}{}{听起来不错。}
{159}{}{去他的主宰！我们杀光他们！}
{160}{}{问错问题可不健康，伙计。他们有所有他们想让你听到的答案。问错问题的人，或者搞砸的人，呃，他们不会在这里待太久。}
{161}{}{我做好我的工作。他们喜欢我做好我的工作。他们喜欢街头垃圾和追随者停止呼吸。这让夜行者可以做其他事情。别惹我……这不健康。}
{162}{}{你穿得像个僵尸干什么？如果你有态度，就得表现出来！}
{163}{}{我不在乎衣服，伙计。我只想知道这里发生了什么！}
{164}{}{如果你看起来不像他们想要转化的对象，他们就不会太烦你。}
{165}{}{不关你的事，伙计。}
{166}{}{我一直在考虑转化。}
{167}{}{这不是态度。这是一种死亡方式。}
{168}{}{我们这里不喝酒。夜行者不喜欢。你最好多了解一些再来找托恩。}
{169}{}{你疯了！我几乎会喜欢你，除了我觉得跟你混在一起的人活不长。快滚。}
{170}{}{你在这里站几个月就会像他们一样疯。你想从托恩这里得到什么？}
{171}{}{这些人怎么变成这样的？}
{172}{}{我想要性和暴力，没有性。你知道哪里能找到吗？}
{173}{}{我在这个僵尸坑里快疯了，不需要你来帮忙。滚开。}
{174}{}{那是墨菲斯。他总是呆在楼上，除了布道。他现在甚至不怎么做布道了。他聪明又成功，这就够了。自己去看看他吧。}
{175}{}{伙计，你得去骨园。这里没有酒，我找过了！}
{176}{}{同意。托恩能为你做什么？}
{177}{}{婊子！你不知道你错过了什么！滚出去！}
{178}{}{生命太短暂了。让我告诉你为什么你不想等。}
{179}{}{但我想要知道发生了什么的人。}
{180}{}{不，谢谢。但我不介意做朋友。}
{181}{}{滚开，你这垃圾。}
{182}{}{当然。}
{183}{}{生命比你想的短。去死吧，混蛋！}
{184}{}{我不是小个子，婊子！}
{185}{}{谁信那种胡扯？他们得给这些傻瓜洗脑才能让他们相信那些东西。}
{186}{}{怎么回事？}
{187}{}{真的？}
{188}{}{真是一群失败者。}
{189}{}{多告诉我一些关于你的团队的事。}
{190}{}{好吧，我加入。}
{191}{}{有人应该让他们解脱。比如我……}
{192}{}{当我们得到命令时，我们出去杀人。像追随者或者一些更危险的帮派类型。}
{193}{}{追随者是个问题吗？}
{194}{}{这听起来很病态。}
{195}{}{谁需要命令？为什么不直接杀了他们？}
{196}{}{好吧。随你便。但我会在这里变得不健康之前离开。}
{197}{}{你这个烦人的小混蛋。你比垃圾镇的人还糟糕，懦夫。滚出去。}
{198}{}{还有什么好知道的？我能吃得好，睡得安稳，还能杀掉一些曾经欺负过我的人。你想从生活中得到更多吗？}
{199}{}{谁知道？谁在乎？我能吃得好，睡得安稳，还能杀掉一些曾经欺负过我的人。你想从生活中得到更多吗？}
{200}{}{嗯，托恩从没想过。但如果他们太烦我，我就打烂他们的脸。然后他们就不再烦托恩了。你想要什么？}
{201}{}{转化？好吧，祝好运。你会需要的。}
{202}{}{我为什么需要运气？}
{203}{}{这听起来不太好。}
{204}{}{谢谢。你是个真正的朋友。}
{205}{}{只要我有弹药，我就不需要运气。}
{206}{}{这些人，这些僵尸，并不总是这样的。我甚至能忍受其中的一些人。然后他们被转化了。有些人变成了这样。有些人根本没出来。托恩不喜欢，但这些人给托恩钱。}
{207}{}{你为什么在第一人称和第三人称之间跳来跳去？}
{208}{}{多告诉我一些关于转化过程的事。}
{209}{}{你经历过转化过程吗？}
{210}{}{这个地方真是低档。}
{211}{}{真的，多少钱？}
{212}{}{没人能这样对我！}
{213}{}{你可以去找墨菲斯或拉舍，或者你可以烦托恩，托恩会给你比你能处理的更多的暴力。}
{214}{}{好吧，宝贝，正在发生的是有很多僵尸在吟唱，很多人在死去，儿童会要接管一切。而只有你和我，其他都不重要！}
{215}{}{但巴拉卡斯，亲爱的，肯定还有别的事情发生……}
{216}{}{哦，托恩！}
{217}{}{算了，怪胎。你不是我的菜。}
{218}{}{其他都不重要？绝对不！我想听听关于死亡的部分！}
{219}{}{不幸的是，这是地球上最糟糕的地方来体验托恩最擅长的东西。太多僵尸限制了我的风格。我会告诉你当我想到更方便的地方……}
{220}{}{你很快就会知道楼上发生了什么。如果你够坚强，你就能挺过去。托恩经历过，托恩很好！}
{221}{}{呃……我什么都没说。你忘了托恩告诉你的，否则托恩会让你永远忘记！}
{222}{}{他们以前是抱怨者。但托恩话太多了。你滚开。}
{223}{}{好吧。你保持低调，直到我给你信号。然后我们就有乐子了。}
{224}{}{他们是懦夫。他们对我们的巡逻队设下埋伏。他们派间谍和破坏者。他们知道他们赢不了真正的战斗。主宰说我们应该为他们感到遗憾，但托恩只想杀了他们。聪明人，托恩。}
{225}{}{我们需要纪律，傻瓜！我们现在是士兵！我们服从命令。杀手会死，但士兵会赢得战斗。我们会打败追随者。我们会打败所有人！}
{226}{}{谁知道呢？也许只是墨菲斯在幕后操控。事情很好，如果这枯竭了，托恩就去别的地方。}
{227}{}{好吧，别太急。即使有夜行者，战斗也很艰难。但如果我们聪明地行动，我们就能领先。这是托恩唯一关心的。}
{228}{}{转化不容易。你看到这些人，所有这些僵尸？他们曾经和你我一样。托恩活下来了。这些人没有。但托恩为什么要关心你？}
{229}{}{你不喜欢托恩的说话方式？那托恩就杀了你！}
{230}{}{托恩经历得很好。我……呃……我……呃……托恩……托恩很好。}
{231}{}{我曾经是死狗帮的成员。总是饿，总是累。这个地方对托恩来说好多了。我为什么要担心别人？从来没有人担心过我。}
{232}{}{你这个贪婪的混蛋！在托恩杀了你之前滚出去！}
{233}{}{那就现在滚出去，趁还来得及。}
{234}{}{没有什么比你我更重要。不幸的是，这是地球上最糟糕的地方来体验托恩最擅长的东西。太多僵尸限制了我的风格。我会告诉你当我想到更方便的地方……}
{235}{}{你这个狡猾的婊子！没有人能这样对托恩！}
