{100}{}{你看到鲍勃，鲍勃鬣蜥肉店的老板。}
{101}{}{好吧，好吧，我有你的钱。}
{102}{}{我的开销增加了，我需要提高付款。}
{103}{}{去你的。我现在要你所有的钱，否则你就死定了，鲍勃。}
{104}{}{我受不了了。我不再支付了。}
{105}{}{我想要关于德克的信息。}
{106}{}{我想要关于莫比德医生的信息。}
{107}{}{给我来一串鬣蜥肉。}
{108}{}{对不起。我不再付钱了。你想对我怎么样就怎么样吧。}
{109}{}{鲍勃，我以为我们是朋友！事实上，我还考虑过在我的组织里给你升职。结果你背叛了我。这让我很失望……}
{110}{}{鲍勃，我为什么要接受你的拒绝？尤其是像你这样的混蛋？}
{111}{}{很高兴看到你为自己挺身而出。}
{112}{}{你的名声完蛋了，鲍勃。完-蛋-了！}
{113}{}{好吧，我稍后再决定怎么处理你。}
{114}{}{嗯，认识你很高兴，鲍勃。替我向撒旦问好。}
{115}{}{你怎么这么快就回来了？还没到付款的时候。}
{116}{}{你真有胆量在这里露面。滚开！}
{117}{}{嘿，我不想惹麻烦！}
{118}{}{嗨！欢迎来到鲍勃的鬣蜥肉店，家庭餐饮场所。我可以为您点餐吗？}
{119}{}{算了。}
{120}{}{是吗？好吧……}
{121}{}{他是个狠角色。你不想惹他。还有别的事吗？}
{122}{}{好吧。你想让我付多少？}
{123}{}{我想要}
{124}{}{每五天支付一次。}
{125}{}{莫比德医生？我只知道他在垃圾镇附近，他是我能找到的最便宜的食物来源。就这些！}
{126}{}{让我看看我有什么库存。}
{127}{}{我有整只鬣蜥，二十瓶盖。}
{128}{}{我有精选上等肉，八瓶盖。}
{129}{}{我要一只真的。}
{130}{}{我现在不吃。我在节食。}
{131}{}{我要一份精选上等肉。}
{132}{}{我现在就想要些精选上等肉。我甚至愿意付钱。}
{133}{}{呃……我现在不饿。}
{134}{}{好吧！拿上你的钱滚吧！}
{135}{}{你可以去死！我永远不会付钱给你！滚开！}
{136}{}{是啊，当然。你为什么不去找别人来坑。}
{137}{}{你不能扔垃圾而不弄脏自己的手。滚出去！}
{138}{}{当然会。滚开！}
{139}{}{抱歉。我们没有鬣蜥肉了。}
{140}{}{我们只有整只鬣蜥串。每串二十块。}
{141}{}{我们只有精选上等肉。不过味道不错。每份八块。}
{142}{}{当然。我们有整只鬣蜥串，二十块一串，还有精选上等肉，八块一份。}
{143}{}{我要一整只鬣蜥。}
{144}{}{我要你的精选上等肉。}
{145}{}{你知道吗，我听说你的精选上等肉尝起来像鸡肉。你喜欢吃胆小鬼吗？}
{146}{}{不要小份的！我要所有的鬣蜥！呃！}
{147}{}{嗯，闻起来不错！我要精选肉！}
{148}{}{从没见过他们在这儿。水商不需要他们。}
{149}{}{水商？}
{150}{}{德克先生是一个在不太光彩的生意中很有声望的商人。还有别的事吗？}
{151}{}{}
{152}{}{什么生意？}
{153}{}{你在说什么？}
{154}{}{你的秘密配料。尸体要多新鲜才会有苦味？你用的是变种人、人类，还是混合的？}
{155}{}{我在莫比德医生的巢穴里发现了一张发票。是尸体的发票……}
{156}{}{如果你失忆了，我可以去找警长谈谈。}
{157}{}{精选上等肉是人肉做的！！是人肉做的！！}
{158}{}{没什么。抱歉提起这事。还有什么我能为你做的吗？}
{159}{}{好吧，他现在死了，我的现金流因此增加了。}
{160}{}{有人杀了德克。我们正在哀悼。[窃笑]}
{161}{}{有人枪杀了格林警长。不过我不知道副警长怎么样了。}
{162}{}{达伦·海塔沃被谋杀了。所有的钱都没能救他。讽刺，不是吗？}
{163}{}{有人从海塔沃家偷了一条项链。天啊，他们真是犯了大错。他们死定了！}
{164}{}{有人在大教堂杀了简。我听说她真是个麻烦精！}
{165}{}{好吧，唯一的新消息是大教堂的孩子们接管了医院。最近这里相当无聊。}
{166}{}{还有别的事吗？}
{167}{}{伙计，我再过一周就要关门了。还有别的事吗，哦高高在上的？}
{168}{}{我不喜欢你的态度。}
{169}{}{抱歉，你买不起。}
{170}{}{一整只鬣蜥来了！还有别的吗？}
{171}{}{你知道它们是用什么做的，你还想要一个？你让德克看起来像个慈善工作者！还有别的吗？}
{172}{}{我不喜欢你的态度。}
{173}{}{抱歉，你买不起。}
{174}{}{一份精选上等肉来了！还有别的吗？}
{175}{}{聪明的选择。你可以减掉几磅。}
{176}{}{什……什么！哦，我明白了，你在开玩笑……}
{177}{}{当然是……}
{178}{}{不，我不是。我会让你为你的罪行付出代价。}
{179}{}{不，我不是。我想要分一杯羹。}
{180}{}{如果你问我关于水商的事，你一定是新来的。水就是生命，没有比生死更有权势的了。}
{181}{}{谁负责水商？}
{182}{}{如果中心有任何涉及痛苦和苦难的事情，德克要么控制着它，要么想要控制它。还有别的事吗？}
{183}{}{我不知道你在说什么，我也不喜欢你的诽谤！我建议你不要再来这里。}
{184}{}{别这样！好吧，我确实用了些有问题的部分。但这不算谋杀吧。莫比德医生的东西本来就是死的，不是吗？}
{185}{}{我相信是的，鲍勃。祝你有美好的一天……}
{186}{}{食人是反人类的罪行，鲍勃。我会让你为此付出代价。}
{187}{}{也许是，也许不是。我不在乎。我想要分一杯羹。}
{188}{}{不要那么大声！我不需要你在整个中心都这么说……}
{189}{}{我想我刚才无礼了。祝你有美好的一天……}
{190}{}{你知道，警察局就在街对面。我可以去散个步。}
{191}{}{我知道我可以更大声。但我也可以闭嘴。噪音便宜，沉默才贵。}
{192}{}{如果你吃光了我的存货，我怎么付钱给你？好吧！再给你一只鬣蜥！希望你噎着！}
{193}{}{我不喜欢你的态度。}
{194}{}{难办。你要钱，我给你。你要吃的，我给你。你想要死，我也可以安排。但“喜欢”不在选项里。}
{195}{}{我想不出还有什么。现在如果你能原谅我，我还有生意要做。}
{196}{}{抱歉，我们的鬣蜥肉卖完了。}
{197}{}{我们只有整只烤鬣蜥。二十块钱。}
{198}{}{我们只有精选上等肉。八块一份。}
{199}{}{又来了？你肯定饿了。我们有整只鬣蜥串，二十块一串，还有精选上等肉，八块一份。}
{200}{}{我要一整只烤鬣蜥。}
{201}{}{我要你的精选上等肉。}
{202}{}{你知道吗，我听说你的精选食材尝起来像鸡肉。你喜欢吃胆小鬼吗？}
{203}{}{不许小份！我要所有的鬣蜥！呃！}
{204}{}{嗯，闻起来不错！我想要精选肉！}
{205}{}{如果你吃光我的存货，我怎么付钱给你？好吧！再给你一只烤鬣蜥！希望你噎着！}
{206}{}{我不喜欢你的态度。}
{207}{}{呃，再见。}
{208}{}{等一下。我们得找到一个互相理解的方法！}
{209}{}{你唯一能让我闭嘴的方法就是杀了我。}
{210}{}{抱歉，没得谈。}
{211}{}{好吧。我能从中得到什么？}
{212}{}{好吧。你想让我付出什么？}
{213}{}{50}
{214}{}{75}
{215}{}{100}
{216}{}{150}
{217}{}{我想我不会改变主意。继续吧。}
{218}{}{如果我是你，我会改变主意。人在中心为了更少的事都死过。}
{219}{}{不可能。我付不起比现在更多的钱。}
{220}{}{好吧。成交。}
{221}{}{块，每五天支付一次。我想五天后再见……}
{222}{}{你能负担得起葬礼吗，鲍勃？}
{223}{}{好吧。暂时按照现在的安排来……}
{224}{}{你知道，我听说你的精选上等肉尝起来像鸡肉。你喜欢吃胆小鬼吗？}
{225}{}{不许小声！我不需要你在整个中心都这么说……}
{226}{}{我想我刚才有点无礼。祝你有美好的一天……}
{227}{}{你知道，警察局就在街对面。我真的应该去找他们聊聊。}
{228}{}{我可以更大声。但我也可以闭嘴。噪音便宜，沉默才贵。}
{229}{}{你是只会唱歌的小鸟，而我是下金蛋的鹅。你不会唱的，因为我是你唯一的鹅。现在滚吧！}
{230}{}{你说的第一件事是明智的。祝你有美好的一天……}
{231}{}{你知道什么关于水芯片的事吗？}
{232}{}{你能告诉我关于德克的什么？}
{233}{}{你知道关于莫比德医生和你的一些秘密配料吗？}
{234}{}{你知道失踪的商队的事吗？}
{235}{}{什么，我有麻烦？你为什么这么认为？}
{236}{}{还有什么吗？}
{237}{}{没什么，再见。}
{238}{}{我现在走了。}
{239}{}{真是可怕的事情。那些可怜的人。哦，那些可怜的人。以如此可怕的方式失去生命！我还能为你做些什么吗？比如给你吃的？}
{240}{}{没什么，再见。}
{241}{}{我现在走。}
