{100}{}{你看到的是兄弟会的医生。}
{102}{}{你好，我能帮你什么忙？}
{103}{}{我受伤了。}
{104}{}{我受到辐射了。}
{105}{}{你们做手术吗？}
{106}{}{再给我讲讲手术的事。}
{107}{}{呃！}
{108}{}{你受伤了吗？让我看看……}
{109}{}{问题解决了。小心点。}
{110}{}{抱歉，如果你不告诉我问题，我无法帮你。}
{111}{}{你看起来没事。}
{112}{}{好了，希望你感觉好些了。}
{113}{}{好了，不过别再惹麻烦了。}
{114}{}{应该修好了。}
{115}{}{焕然一新。}
{116}{}{全都治好了。}
{117}{}{辐射很危险，你应该更小心。}
{118}{}{我没空玩游戏。}
{119}{}{当然可以，但这非常昂贵且耗时。}
{120}{}{细节？}
{121}{}{好吧，算了。}
{122}{}{我可以帮你变得更强壮、更敏锐、增加耐力、提高学习能力和灵活性。你想了解哪方面？每种手术我只能做一次。}
{126}{}{好吧，你想了解哪种手术？}
{127}{}{力量。}
{128}{}{感知。}
{129}{}{耐力。}
{130}{}{智力。}
{131}{}{敏捷。}
{132}{}{算了。}
{133}{}{这很简单，但恢复时间很长。只需2000个筹码，但需要3周恢复。}
{135}{}{我愿意！}
{136}{}{我不做。}
{137}{}{这是一项困难的手术。需要4000个筹码，但恢复时间只有一周。}
{139}{}{这不算太难。大约需要一周，费用是3000个筹码。}
{141}{}{这是最复杂和危险的！需要3周时间，费用是6000个筹码。}
{143}{}{这手术不算太难，但非常昂贵且耗时。需要3周时间，费用是5000个筹码。}
{146}{}{好了，希望泡沫没有刺激到你的皮肤。}
{147}{}{抱歉，如果你没钱，我帮不了你。}
{148}{}{抱歉，你是外来者。等你加入兄弟会十年后，我可以免费为你做手术，但我们有开销，而你还不是兄弟会的正式成员。}
{149}{}{等你有钱了再来找我。}
{153}{}{你想问其他的吗？}
{154}{}{好吧，开始了……开玩笑的。我们可以马上开始。（她给你打了麻醉，你慢慢失去意识。）}
{156}{}{感觉怎么样？（你已经能感觉到不同了。）你在睡梦中还挺健谈的。你可以走了！祝你愉快。}
{159}{}{旧的去，新的来……（你像石头一样坠入深渊。）}
{161}{}{你看起来没变，但感觉如何？（你的感官变得更加敏锐。）好了，你占用了宝贵的床位。快走吧！}
{164}{}{希望你有颗心……（她对你眨眼，你失去意识。）}
{166}{}{嗯，你看起来壮实了些。（你感觉很好！）如果有问题，记得告诉我。}
{168}{}{大脑在哪来着？这东西应该怎么用？（你试图抵抗药物，但无济于事。）}
{170}{}{看起来我把一切都装回去了，而且运行良好。（你的思维路径似乎与大脑各处直接相连，记忆更加清晰。）慢慢来。}
{174}{}{好吧，试试看。（药物，真是……友好。你很快就睡着了。）}
{176}{}{好了，你可以上岗了。（你感受到肌肉的速度和控制力的提升。）我只求你不要破坏我的杰作。}
{200}{}{你看到医生的助手。}
{279}{}{你应该去看医生。}
{280}{}{她是医生，不是我。}
{281}{}{我还在培训中。}
{282}{}{我不能正式帮你。}
{283}{}{Lori是医生。}
{284}{}{你得问医生。}
{285}{}{别担心，她只是开玩笑。}
{286}{}{她只是喜欢逗你，别担心。}
{300}{}{抱歉，这个手术对你没用。}

{400}{}{嗯。如果这里有人需要智力增强，那就是你。事实上，我愿意以3000瓶盖的价格为你做，而不是通常需要的6000瓶盖。我不能保证它会对你有帮助，但我觉得值得一试。恢复时间也需要3周。不过你可能不明白这些，对吧？}
{401}{}{我想变聪明。}
{402}{}{不想。}
{403}{}{你是受辐射了还是受伤了？如果可以，我会帮你。}
{404}{}{我受伤了。}
{405}{}{头发掉了。}
{406}{}{没有。}
{407}{}{好了，你醒了。让我看看。你感觉更聪明了吗？}
{408}{}{嗯？}
{409}{}{是的！}
{410}{}{该死！失败了。好吧，我本来也没什么可用的。抱歉，你就是个笨蛋，而且可能会一直是个笨蛋。我们只能做一次手术，很抱歉。}
{411}{}{成功了！我把你的智商提升到了一个可接受的水平。拥有半个大脑的感觉如何？}
{412}{}{太好了。谢谢，医生。再见。}
{413}{}{好了，完全康复了。}
