{100}{}{你看到一个非常美丽的年轻女子。}
{101}{}{你看到克里斯汀，迈克尔的妻子。}
{102}{}{你好？我能帮你吗？}
{103}{}{你是谁？}
{104}{}{这里谁负责？}
{105}{}{你能告诉我一些关于这个地区的情况吗？}
{106}{}{不用了，谢谢。}
{107}{}{你是我妈妈吗？}
{108}{}{我叫克里斯汀，我和我丈夫迈克尔住在这里。}
{109}{}{剃刀负责管理刀锋帮的大部分事务，并帮助我们组织。}
{110}{}{我和迈克尔刚搬到这里，所以对这个地区还不太熟。我听说南边有个大教堂，但大多只是传闻。}
{111}{}{还有什么我应该知道的吗？}

#
# TRANSLATION NOTE: Do NOT translate the next 4 lines.  They will NOT make any
#					sense in any other language.
#
{112}{}{C D E D B D 鸭子}
{113}{}{M R 不是鸭子}
{114}{}{O S M R                                                                   C D E D B D 翅膀}
{115}{}{Y I B M R 鸭子}

{116}{}{还有什么我可以帮你的吗？}
{117}{}{不，我不是你妈妈。现在去玩吧。}
