{100}{}{你看到了一名商队司机。}
{101}{}{你想回到枢纽吗？我会再付你400瓶盖。}
{102}{}{鲁特格应该会很高兴；我们没有任何伤亡。你想和我们一起回去吗？我们快准备好了。报酬还是400瓶盖。}
{103}{}{这比我预想的要简单。你要和我们一起回去吗？我相信再拿400瓶盖会很有用。}
{104}{}{这还不算太糟。如果你想和我们一起回枢纽，欢迎加入。我们会再付你400瓶盖。}
{105}{}{失去同伴总是令人遗憾。鲁特格不会对此满意，但我们需要你的帮助回去。你有兴趣吗？报酬依然是400瓶盖。}
{106}{}{该死！我讨厌失去优秀的护卫。我们回去的路上必须更加小心。我们得互相掩护，不能再让这种事发生。我会再付你400瓶盖。愿意吗？}
{107}{}{你能和我们一起回枢纽吗？我不能再冒失去护卫的风险了。报酬是400瓶盖。你怎么看？}
{108}{}{我真的需要你的帮助回去。鲁特格会杀了我，我不知道自己能不能独自完成。如果你有兴趣，报酬还是400瓶盖。你怎么看？}
{109}{}{一个人回去会很艰难。你愿意和我一起回枢纽吗？报酬是400瓶盖。}
{110}{}{我真不敢相信我们失去了另外两个护卫。鲁特格和巴奇会找我算账的。}
{111}{}{是的。}
{112}{}{不。}
{113}{}{呃。}
{114}{}{太好了。我们走吧。}
{115}{}{怎么，你害怕了吗？}
{116}{}{啊，你错过了一些刺激的事情。}
{117}{}{没关系。我相信我们能顺利回去。谢谢你帮我们一路平安到达。}
{118}{}{没关系。我理解。只有一个护卫会很艰难，但我们会做到的。}
{119}{}{呃，好吧。我相信我能独自完成。}
{120}{}{你还好吗？这趟旅程对你的影响比我想象的要大。}
{121}{}{你在嗑药吗？}
{122}{}{也许我不想让你加入我的商队。}
{123}{}{那么你改变主意了吗？你想要这份工作吗？}
{124}{}{是的。}
{125}{}{不。}
{126}{}{呃？}
{127}{}{轻松赚钱。那么，你想和我们一起回枢纽吗？报酬是一样的；不过危险也是一样的。}
{128}{}{那么，你愿意再赚600瓶盖吗？我得回枢纽。希望这次也会很轻松。}
{129}{}{我就知道你会和我们一起回去。报酬还是600瓶盖。你有兴趣吗？}
{130}{}{我讨厌失去这样的同伴；这就是我们支付高额报酬的原因。这条路线很危险。德米特尔很快就会等我们回去。报酬不变。你想和我们一起回去吗？}
{131}{}{准备好再来点刺激吗？这次我们连划伤都不会有！我会给你600瓶盖作为回枢纽的报酬。}
{132}{}{我知道。失去同伴很遗憾，但至少是在战斗中。你想再试一次吗？我们要回枢纽。再给你600瓶盖。}
{133}{}{该死，我真不敢相信我们失去了那两个护卫。德米特尔会很生气。报酬不变，但我很快就要出发了。你怎么看？你和我一起大干一场？}
{134}{}{那是一场战斗，真可惜另外两个护卫。德米特尔不会喜欢这些损失，但至少我们成功了。你会和我一起回枢纽吗？当然，报酬是600瓶盖。}
{135}{}{我喜欢战斗的感觉，但讨厌失去我的队员。你觉得你和我能再应付他们吗？我很快就要出发了——唯一的问题是报酬不变。抱歉，没有额外补偿。}
{136}{}{呃。}
{137}{}{好吧。我相信我们能顺利回去。}
{138}{}{我其实只需要一个护卫。}
{139}{}{啊，我可以自己对付他们。}
{140}{}{啊，你回来了！那么你想要这份工作，对吧？}
{141}{}{啊。}
{142}{}{哦，你好。在找工作吗？我们需要有人帮忙护送商队回枢纽。报酬是400瓶盖。}
{143}{}{好的。}
{144}{}{不用了，谢谢。}
{145}{}{呃。}
{146}{}{哦，你好。在找工作吗？我们需要有人帮忙护送商队回枢纽。报酬是600瓶盖，不过要注意，这通常是一趟危险的旅程。}
{147}{}{当然。}
{148}{}{呃。}
{149}{}{如果你改变主意，请告诉我。我们在14:00出发。}
{150}{}{抱歉，你看起来不适合护送商队。}
{151}{}{如果你不能好好说话，我不能雇你。}
{152}{}{如果你想要工作，就别嗑药。}
{153}{}{你改变主意了吗？想要这份工作吗？}
{154}{}{是的。我会加入。}
{155}{}{呃？}
{156}{}{这是你的报酬。如果你要和我们一起回去，请告诉我。}
