{100}{}{你看到一个商队护卫。}
{101}{}{真不敢相信我们失去了老板。你要和我们一起回去吗？我们仍然可以支付你400瓶盖。}
{102}{}{失去司机真是遗憾；鲁特格肯定不高兴。如果你愿意，我们可以支付你同样的报酬，跟我们一起回到枢纽城。}
{103}{}{你要和我们一起回去吗？我来开这辆车。报酬还是一样的。}
{104}{}{嗯，我不知道你怎么想，但我打算再等一个商队。我不想一个人回去。如果你想回去，我会和你一起，但如果我没能活着回去，你就拿不到那400瓶盖。}
{105}{}{刚才真是太糟糕了。如果你真的愿意，我可以再给你400瓶盖，只要你和我一起回到枢纽城。一个人太危险了。}
{106}{}{如果你能安全护送我和商队回到枢纽城，你会再得到400瓶盖，但前提是我得活着。要是遇到麻烦，你得保护我。}
{107}{}{好吧，我会和你一起去。}
{108}{}{不用了，我已经受够了护卫任务。}
{109}{}{图克。}
{110}{}{太好了！我们赶紧离开这里！}
{111}{}{好的，我明白。}
{112}{}{我会应付的。}
{113}{}{好吧。}
{114}{}{你还好吗？}
{115}{}{我觉得你需要休息一下。}
{116}{}{呃，我觉得你应该去找兄弟会的医生看看。}
{117}{}{我们失去了老板。你能和我们一起回去吗？我们仍然可以支付你400瓶盖。}
{118}{}{我们的司机是个好人……真是个巨大的损失。如果你愿意和我们一起回到枢纽城，我仍然可以支付你400瓶盖。}
{119}{}{如果你愿意和我们一起，我会带我们回去。报酬还是一样的。}
{120}{}{哇，我真不敢相信我们是仅剩的两个人。我会和你一起去，但如果我没能活着回去，你就拿不到那400瓶盖。}
{121}{}{刚才真是太糟糕了。如果你真的愿意，我可以再给你400瓶盖，只要你和我一起回到枢纽城。一个人太危险了。}
{122}{}{如果你能安全护送我和商队回到枢纽城，你会再得到400瓶盖，但前提是我得活着。要是遇到麻烦，你得保护我。}
{123}{}{那么，你改变主意了吗？}
{124}{}{是的，我接受这份工作。}
{125}{}{不。}
{126}{}{哈拉？}
{127}{}{抱歉，今天我们不回枢纽城。}
{128}{}{呃，抱歉。我觉得我们不需要你护送回程。}
{129}{}{如果你想加入，去找我们的商队司机谈谈。}
{130}{}{你好。如果你在找工作，去找我们的商队司机。}
{131}{}{你好。}
{132}{}{抱歉，不能说话。}
{133}{}{要和我们一起回枢纽城吗？}
{134}{}{我喜欢商队护卫的工作，既刺激又能赚到瓶盖。}
{135}{}{为远行商人工作真不错。}
{136}{}{我喜欢为远行商人工作，他们不会冒傻风险。}
{137}{}{红色商队的商队是最好的。}
{138}{}{红色商队的薪水很高，我一年后就能退休。}
{139}{}{如果你想和我们一起回去，去找另一个护卫谈谈。}   {140}{}{这是你的瓶盖。如果你能帮忙护送我们回去，我们会很需要你的帮助。}
{140}{}{这是你的瓶盖。如果可以的话，我们需要帮忙回去。}
