{100}{}{你看到一个店主。}
{101}{}{圣火不欢迎小偷和恶棍进入他的礼拜场所。你将受到惩罚！}
{102}{}{哼！}
{103}{}{我没有偷你的东西，真的！}
{104}{}{为什么不等你受罚后再告诉圣火呢。}
{105}{}{我不在乎你的谎言，主人也不会。}
{106}{}{抱歉，商店已经关门了。}
{107}{}{努嘎。}
{108}{}{谢谢，什么也没得到。}
{109}{}{为什么会这样？}
{110}{}{别客气。}
{111}{}{孩子们不需要处理你这样的人。而且你给我们带来了严重的问题。我希望你离开，否则我会叫增援。}
{112}{}{你不必这样做。我是你的朋友。}
{113}{}{随便。}
{114}{}{我拒绝与那些用武器来威胁的人打交道。我们孩子已经超越了简单的枪支和武器。}
{115}{}{控枪的法西斯疯子！}
{116}{}{让我收起武器，我们可以和平交易。}
{117}{}{很好，我喜欢这样。我很乐意和你做生意。}
{118}{}{问候，我的同胞孩子。我能帮你什么忙？}
{119}{}{鲁嘎！？}
{120}{}{你有什么可以交易的？}
{121}{}{谢谢。再见，鳄鱼。}
{122}{}{抱歉。也许我们可以达成交易。}
{123}{}{拜！}
{124}{}{过一会儿，鳄鱼。我真不敢相信我说了这个。}
{125}{}{问候！我能帮你什么忙？我希望你能花点时间考虑一下未来的决定对你的灵魂的意义...}
{126}{}{巴尔塔！}
{127}{}{你有什么可以交易的？}
{128}{}{我在哪里可以得到你们那些华丽的长袍...}
{129}{}{只有大教堂的信任成员才能穿圣紫。}
{130}{}{我想这回答了我的问题，谢谢！}
{131}{}{自命不凡的傻瓜。我想我得拿你的！}
{132}{}{哦，好吧。你有什么可以交易的？}
{133}{}{哦，都是些迎合进门的傻瓜的东西。没什么特别的。随便看看吧。}
{134}{}{谢谢，再见。}
{135}{}{我们有各种特别的物品来纪念你在大教堂的旅行。这些回忆可不是便宜货，你懂的。}
{136}{}{谢谢...}
{137}{}{不客气。愿你余生愉快。}
