{100}{}{这是一台修理得很差的老虎机。玩一次需要花费$10。}
{101}{}{你投入了$10，然后拉下了老虎机的把手。}
{102}{}{叮！叮！叮！}
{103}{}{你得到了三个手雷。太棒了！$}
{104}{}{掉进了托盘，你迅速抓住了它。}
{105}{}{叮！叮！叮！}
{106}{}{你得到了三颗子弹。赢家！$15掉进了托盘，你迅速抓住了它。}
{107}{}{哎呀！你输了。}
{108}{}{你的钱不够，无法继续游戏。}
