{100}{}{你看到大教堂之子的学者赛斯林。}
{101}{}{你看到大教堂之子的学者斯莱特。}
{102}{}{你看到大教堂之子的学者奥纳努特。}
{103}{}{你看到大教堂之子的学者艾肯科夫。}
{104}{}{你看到大教堂之子的学者斯皮卡瓦。}
{105}{}{你看到大教堂之子的学者瓦拉隆。}
{106}{}{你看到大教堂之子的学者奎诺诺斯。}
{107}{}{你看到大教堂之子的学者齐格利夫。}
{108}{}{你看到大教堂之子的学者琼斯。}
{109}{}{你看到大教堂之子的学者史密斯。}
{110}{}{追随者的计划应该就在这附近。}
{111}{}{我确信追随者有他们所有盟友的名单。}
{112}{}{那些蠢货不该招惹我们的神！}
{113}{}{快走，否则你会像那些愚蠢的追随者一样。}
{114}{}{没有人能阻止废土的净化。}
{115}{}{我们给了他们和平，他们却选择了战争。}
{116}{}{那个愚蠢的食尸鬼是从哪里来的？}
{117}{}{一定有一份所有追随者的名单。}
{118}{}{可惜我们只能在白天搜查这个地方。}
{119}{}{我们必须小心夜行者，他们在黑暗时行动。}
{120}{}{愿你生活在有趣的时代！}
