{100}{}{你看到一个小孩。}
{101}{}{嗨！}
{102}{}{你好。}
{103}{}{你父母在哪儿？}
{104}{}{呃。}
{105}{}{我不知道。就在附近吧。}
{106}{}{你真有趣！}
{107}{}{嘿，你要去杀人吗？}
{108}{}{是的。}
{109}{}{不！}
{110}{}{呃。}
{111}{}{我要告诉我妈妈！}
{112}{}{那你就不该拿着那样的武器。}

{980}{}{啊？}
{981}{}{我不知道。问妈妈吧。}
{982}{}{问爸爸。}

{1000}{}{死亡爪}
{1001}{}{掠夺者}
{1002}{}{废城}
{1003}{}{布拉明}
{1004}{}{芯片}
{1005}{}{商人}
{1006}{}{汗帮}
{1007}{}{加尔}
{1008}{}{阴影镇}
{1009}{}{枢纽}
{1010}{}{坦迪}
{1011}{}{阿拉迪什}
{1012}{}{赛斯}
{1013}{}{拉兹洛}
{1014}{}{警察}
{1015}{}{商队}
{1016}{}{商人}
{1017}{}{孩子们}
{1018}{}{死城}
{1019}{}{地点}
{1020}{}{兄弟会}
{1021}{}{骨园}
{1022}{}{塔楼}
{1023}{}{城镇}
{1024}{}{市中心}
{1025}{}{高地}

{1100}{}{哇！噩梦怪物！}
{1101}{}{大坏蛋！}
{1102}{}{我不知道。}
{1103}{}{大臭家伙。}
{1104}{}{问妈妈。}
{1105}{}{有趣的海歌。}
{1106}{}{大坏蛋！}
{1107}{}{坏人。}
{1108}{}{我不告诉你。}
{1109}{}{大城市。}
{1110}{}{我不说。}
{1111}{}{不，我不告诉你。}
{1112}{}{妈妈不让我谈论他。}
{1113}{}{爸爸觉得他很搞笑。}
{1114}{}{大人们。}
{1115}{}{他们有那些臭东西拉着。}
{1116}{}{好人。他们给我糖果。}
{1117}{}{他们不喜欢玩捉迷藏。}
{1118}{}{可怕的地方。}
{1119}{}{恶心的地方。}
{1120}{}{可怕的地方。}
{1121}{}{可怕的地方。}
{1122}{}{妈妈不让我们在那里玩。}
{1123}{}{爸爸总是让我们去那里玩。}
{1124}{}{大人区域。}
{1125}{}{大人区域。}
