{100}{}{你看到一个大教堂之子的技术员。}
{101}{}{放下你的武器，夜行者会让你活命。}
{102}{}{加入我们，不要与我们为敌。}
{103}{}{你将成为统一体的一部分！}
{104}{}{夜行者，把这个傻瓜抓起来。我们的主人会很高兴。}
{105}{}{请不要杀我。我只是个打工的。}
{106}{}{你不会杀一个手无寸铁的人，对吧？对吧？！}
{107}{}{我投降！}
{108}{}{你没有权利在这里。你想要什么？}
{109}{}{嗯。}
{110}{}{你是谁？}
{111}{}{你们这些疯狗！我受够你们的命了！}
{112}{}{这里是什么地方？}
{113}{}{你几乎已经是夜行者了。我希望浸泡不会进一步损害你的智力。}
{114}{}{我是统一体的一部分。我是我们主人的光辉仆人。我将见证你成为统一体的一部分。}
{115}{}{你很快就会知道。}
{116}{}{这是优越种族的诞生地！这是神之军队将要出击的子宫！从弱者的血肉中诞生下一代人类。那些幸存浸泡的人将成为神的战士，凭借他们的双手，我们将塑造统一体。}
{117}{}{你疯了！你简直是个疯子！去死吧！}
{118}{}{它是如何运作的？}
{119}{}{你将被绑在神圣的束缚中。我们会把你降入神之血的缸中，那是最神圣的圣物。FEV会塑造和改变你。你会变得强大。如果你幸运并值得这个荣誉，你将成为夜行者，否则你将承受最痛苦的死亡。很快，我将被授予荣誉。我将变得强大。那时我将无惧任何人。}
{120}{}{你在夜行者身边待得太久了。再见。}
{121}{}{你为什么要告诉我这些？}
{122}{}{你从哪里得到的FEV？}
{123}{}{你只能作为统一体的一部分离开这里，或者成为地狱中的迷失灵魂！[停顿] 另外，我和一群皈依者坐在这里。说出来感觉好多了。}
{124}{}{你从哪里得到的FEV？}
{125}{}{你杀了神的右手。主人会非常生气。现在，是我们加入神圣火焰的时候了！}
{126}{}{你杀了主人。统一体的死亡是你的错。你导致了人类的灭亡。希望你对此感到满意。}
{127}{}{嗯。}
{128}{}{事实上，我确实如此。}
{129}{}{你马上就会加入他。祈祷取代他的神吧。}
{130}{}{我现在就去加入他，在神圣的火焰中！}
