{100}{}{你看到一个肤色黝黑的男人，身上装饰着鲜艳的围巾和饰品。}
{101}{}{你看到吉普赛算命师查克。}
{102}{}{你好，陌生人。我能为你效劳吗？}
{103}{}{呃！}
{104}{}{我只是随便看看，谢谢。}
{105}{}{我在了解阿迪特姆的人。}
{106}{}{你为什么认为我需要什么？}
{107}{}{嗯。别担心，我简单的朋友，你前途无量。}
{108}{}{你觉得我们的小镇怎么样？}
{109}{}{还不错。}
{110}{}{不太喜欢。不太友好。}
{111}{}{在如此敌对的环境下，你做得相当不错。}
{112}{}{我叫查克。欢迎来到阿迪特姆。不过恐怕这里的大多数人对陌生人不太友好。}
{113}{}{是的，我注意到了。}
{114}{}{那么，查克，你的工作是什么？}
{115}{}{回头见，查克。}
{116}{}{旅途愉快，流浪者。}
{117}{}{我们都需要些什么，不是吗？如果你不想要什么，你也不会和我说话，无论是信息、谈话，还是指导。我能看出你经历了很多。你需要什么？}
{118}{}{呃，我不需要什么，谢谢。}
{119}{}{既然你提到了，也许你能给我一些建议。}
{120}{}{[查克拿出一副塔罗牌。]让我来看看牌。[查克洗牌。]}
{121}{}{[查克抽出一张画着穿实验服的人的牌，手里拿着电脑，和一张穿动力装甲的人的牌。]教皇和权杖王子在南方……在南方的某个地方等待着伟大的智慧和高贵。}
{122}{}{[查克抽出一张画着拿着振动刀和旗帜的人的牌。]剑王子在北方……你必须面对一个强大的敌人在遥远的北方。}
{123}{}{[查克抽出一张画着无线电塔的牌，和一张画着拿着权杖的西装男子的牌。]高塔和皇帝……一个强大领袖的手中等待着巨大的变革。是否是死亡，我无法判断。}
{124}{}{[查克抽出一张画着在核弹头上跳舞的人的牌。]愚者。我帮不了你；你必须在这个世界上走出自己的路。}
{125}{}{[更多]}
{126}{}{嗯，谢谢你的建议。}
{127}{}{你真的相信这些东西吗？！}
{128}{}{对我来说有效。如果你不想相信，那就不适合你。}
{129}{}{无意冒犯，但这听起来像是一堆迷信。}
{130}{}{好吧，我想我们每个人都有自己的信仰。}
{131}{}{如果你是这样想的，那我想我们没有更多可谈的了。}
{132}{}{确实如此。你的宇宙由你的信仰塑造，而我的宇宙由我的思想塑造。我们可能不共享信仰，但我祝愿你在你的宇宙中一切顺利。}
{133}{}{这是家。}
{134}{}{呃，是的。回头见。}
{135}{}{这里似乎有点安静。}
{136}{}{我知道你的意思。我见过很多痛苦。}
{137}{}{监管者确保了这一点。阿迪特姆的人有时因为他们严格的规则而受苦。}
{138}{}{我想是的。好吧，回头见。}
{139}{}{你对此没意见吗？}
{140}{}{既然我希望留在这里，我接受监管者作为阿迪特姆的一部分。然而，我尽我所能让他们的生活轻松一些。}
{141}{}{你似乎不同意他们的做法。}
{142}{}{你还能做些什么吗？}
{143}{}{监管者保护他们自己的利益，我必须尊重这一点。}
{144}{}{好吧，随便吧。}
{145}{}{我不一定同意这种观点，但可以理解。}
{146}{}{很高兴和你聊天。回头见。}
{147}{}{好吧，我只是一个人，但尽我所能提供帮助。我建议你为你相信的事情而战，但最重要的是，选择值得战斗的战斗，并找到妥协和希望能赢得更大胜利的时机。}
{148}{}{你还有其他建议吗？}
{149}{}{阿迪特姆的人在正常的一天中有很多事情要做。他们不希望在一天结束时发现自己的工作不尽如人意。}
{150}{}{是的，好吧，随便吧。}
{151}{}{这里似乎有点安静。}
{152}{}{谢谢。这很困难。我们有时会失去一些人给死亡爪，有时冬天很难熬，尤其是当集散地的商人不来的时候。但我们在生存。}
{153}{}{祝好运。}
{154}{}{死亡爪的情况怎么样？}
{155}{}{它们在这里东北方向的一个区域出没，常常夺走负责与枪械跑者交易的人的生命。}
{156}{}{希望你能找到解决办法。}
{157}{}{是的，随便吧。}
{158}{}{也许吧。我认为阿迪特姆会在这里。世界必须像你一样来到我们这里，而不是我们去到世界。}
{159}{}{嗯，我想是的。}
{160}{}{我是个农民。我也喜欢在建筑物上做一些修复工作，保持它们的完整，有时我也会给出一些建议。}
{161}{}{什么样的建议？}
{162}{}{是的，不幸的是。我认为……这是一种考验，通过在这些艰难时期中生存下来，我们学会依靠彼此，并学习生存所需的技能。我认为，最终，人类会因此变得更好。}
{163}{}{我不同意。我在旅行中遇到过很多帮派和掠夺者。他们变成了卑鄙的杀手和小偷。我认为我们最终都面临这种风险。}
{164}{}{也许你是对的。肯定的是，那些生存下来的人会更强大。}
{165}{}{他们最终会自我毁灭。而留下来的人将是那些为了生存而合作的人，就像我们一样。}
{166}{}{我很高兴有些外来者，比如你，有这样的想法。我们需要找到合作的方法来建立新的东西。这不会从这里开始；我们太受限制了，但必须从某个地方开始。}
{167}{}{你好。我能为你做些什么？}
{168}{}{我能帮你吗？}
{169}{}{是吗？}
{170}{}{只是过来打个招呼。}
{171}{}{我在找点建议。}
{172}{}{我可以问问你在这里做什么吗？}
{173}{}{你好，希望你一切都好。}
