{100}{}{你看到一个商队司机。}
{101}{}{抱歉，我不认识你。如果你想找工作，去找鲁特格谈。}
{102}{}{别跟我谈工作，去找鲁特格。}
{103}{}{怎么，你把钱都花在药物上了？再这样下去，你的新家就会在老城区，被流浪汉包围。}
{104}{}{你最好清醒点。准备好并能工作时再回来。}
{105}{}{在找另一份工作吗？}
{106}{}{当然。}
{107}{}{不，也许以后吧。}
{108}{}{卢格。}
{109}{}{洛克！}
{110}{}{准备好了吗？我们今天出发。}
{111}{}{是的！}
{112}{}{不。}
{113}{}{哈鲁拉？}
{114}{}{抱歉，我们不再和你合作。去试试别的商队吧，也许他们能忍受你。}
{115}{}{抱歉，我们不招人。}
{116}{}{你还敢回来，真有胆量。我觉得你该走了。}
{117}{}{我说滚开！}
{118}{}{你想要什么？雇你简直是场灾难。}
{119}{}{请再给我一次机会！我别无选择！}
{120}{}{哦，是吗？我才不在乎。}
{121}{}{没什么。再见。}
{122}{}{卡。}
{123}{}{哞。}
{124}{}{听着，我不知道外面发生了什么，但我们整个商队都没了！如果你不能保护它，就不该回来。}
{125}{}{不行，滚开！}
{126}{}{我说滚开！}
{127}{}{你想要什么？}
{128}{}{啊，闭嘴，别挡路！}
{129}{}{我想要另一份工作。}
{130}{}{没什么。}
{131}{}{祖格。}
{132}{}{乌格。}
{133}{}{什么？你上次抛弃了工作？你真走运，他们活下来了。}
{134}{}{我走运？你走运我没揍你！}
{135}{}{嘿！我有地方要去，有人要见。}
{136}{}{我不知道我不能离开。一切看起来都没问题。}
{137}{}{说清楚点，否则就滚。}
{138}{}{流浪汉。}
{139}{}{我们不雇酒鬼。}
{140}{}{我们不雇药鬼。}
{141}{}{（你被忽视了）}
{142}{}{睡醒了再回来。}
{143}{}{你这个变态。回去畜栏吧。}
{144}{}{看起来没问题？你永远不能离开商队，即使离集合点只有一英里。你是被雇来全程保护它的，否则我们会找别人。}
{145}{}{没人告诉我不能离开！}
{146}{}{对不起，这不会再发生了。}
{147}{}{去你的。}
{148}{}{什么？这是你第一次参加商队吗？你是怎么被雇上的？这是一份非常细致且重要的工作，必须认真对待。生命攸关，包括商队和我们供应的城镇。}
{149}{}{你一定为自己感到骄傲。}
{150}{}{什么？你想要奖章吗？}
{151}{}{让我拯救生命吧！我想帮忙！}
{152}{}{希望如此！这是一份非常细致且重要的工作，必须认真对待。生命攸关！商队和我们供应的城镇都依赖我们！}
{153}{}{你一定为自己感到骄傲。}
{154}{}{什么？你想要奖章吗？}
{155}{}{让我拯救生命吧！我想帮忙！}
{156}{}{当然是。}
{157}{}{那么，我能再找一份工作吗？}
{158}{}{你是个白痴！}
{159}{}{我得走了。再见。}
{160}{}{呃，是的。这是艰苦而肮脏的工作！我们为那些不幸的人冒着生命危险。}
{161}{}{去找点事做吧！}
{162}{}{哦？那你脚下那些不幸的人呢？}
{163}{}{你说得对。我能再找一份工作吗？}
{164}{}{什么？我不知道你在说什么！哦，你是说流浪汉？他们不算。他们选择那样生活。}
{165}{}{我想你是对的。}
{166}{}{你让我恶心。}
{167}{}{我得走了。}
{168}{}{什么？我说了什么？}
{169}{}{当然是。我本质上是个好人……大部分时间。}
{170}{}{当然是。那我能再找一份工作吗？}
{171}{}{我要走了。}
{172}{}{这才是态度！可惜我不能再给你工作。}
{173}{}{什么？说了这么多？哦，拜托！请再给我一份工作吧？}
{174}{}{好吧，那就继续拯救世界吧。}
{175}{}{那很好。但别指望再为我们工作！}
{176}{}{哦，拜托！这不会再发生了！}
{177}{}{我才不想呢！}
{178}{}{好吧，再给你一次机会。我们的下一个商队将于}
{179}{}{今天}
{180}{}{明天}
{181}{}{在}
{182}{}{8号}
{183}{}{18号}
{184}{}{28号}
{185}{}{出发。准备好时告诉我。报酬是标准的400瓶盖。}
{186}{}{抱歉，上次你搞砸了，我已经犯了个大错给你机会。}
{187}{}{太好了，你想走哪条路线？}
{188}{}{你好。商队明天才出发。如果你还想要这份工作，明天再来。}
{189}{}{我不想要这份工作。}
{190}{}{我会尽量赶到。}
{191}{}{好的，到时候见。}
{192}{}{是的。}
{193}{}{你好。你来早了。非常早。下一个商队要到}
{194}{}{8号}
{195}{}{18号}
{196}{}{28号}
{197}{}{才出发。如果你还感兴趣，到时候再来。}
{198}{}{我不想要这份工作。}
{199}{}{我会尽量赶到。}
{200}{}{好的。再见。}
{201}{}{是的。}
{202}{}{好的。对我来说无所谓。}
{203}{}{见鬼，你来不来对我无所谓。每天都有找工作的人。如果你不来，也没关系。}
{204}{}{我已经告诉过你了。别担心。如果你来不了，我可以应付。}
{205}{}{钢铁兄弟会}
{206}{}{骨园}
{207}{}{废城}
{208}{}{算了。我还是不想要这份工作。}
{209}{}{时机不错，我们的商队今天出发。报酬是标准的400瓶盖。你想走哪条商队路线？}
{210}{}{太好了。我们的下一个商队将在}
{211}{}{8号}
{212}{}{18号}
{213}{}{28号}
{214}{}{出发。到时候回来，我们会分配你到一个商队。报酬是标准的400瓶盖。}
{215}{}{好的。}
{216}{}{抱歉，我等不了那么久。}
{217}{}{太好了。我会找来你的司机和其他队员。外面有点危险，小心点。}
{218}{}{队员准备好了。我们马上出发。}
{219}{}{好的。集合队员需要几分钟。}
{220}{}{好的。我们会在我集合好其他队员后出发去钢铁兄弟会。}
{221}{}{好的。等我集合好队员后，你们就会出发去钢铁兄弟会。}
{222}{}{准备出发！一定要远离山区。}
{223}{}{骨园是个危险的地方——小心点。确保每个人都按时值班。}
{224}{}{队员快准备好了。我听说骨园最近有些麻烦——小心点。}
{225}{}{好的，去骨园的商队队员已经准备好了。}
{226}{}{废城通常是个短而简单的旅程——你应该不会有问题。}
{227}{}{好的，去废城的商队队员已经准备好了。}
{228}{}{好的。废城在等我们，出发吧。}
{229}{}{你好。我听说你在找工作。我很惊讶鲁特格雇了你，但我相信他有他的理由。我们的商队每月三次出发：8号、18号和28号。我们定期去三个地方：钢铁兄弟会、废城和骨园。报酬总是400瓶盖，这是单程的。你可以随商队回来，再赚400瓶盖。}
{230}{}{你来的正是时候，因为他们今天都要出发。}
{231}{}{他们明天都要出发。}
{232}{}{他们要}
{233}{}{天后才出发。}
{234}{}{你有兴趣吗？}
{235}{}{那么，你想要这份工作吗？}
{236}{}{他们今天都要出发。}
{237}{}{他们明天都要出发。}
{238}{}{他们要}
{239}{}{天后才出发。}
{240}{}{我猜你想要一份工作。我可能会给你一个。你有兴趣吗？}
{241}{}{当然。}
{242}{}{不。}
{243}{}{你知道你的商队可以插在哪里。}
{244}{}{我不知道。我得再考虑一下。}
{245}{}{乌格。}
{246}{}{你想走哪条路线？}
{247}{}{钢铁兄弟会。}
{248}{}{骨园。}
{249}{}{废城。}
{250}{}{抱歉，我改变主意了。}
{251}{}{那么，}
{252}{}{8号}
{253}{}{18号}
{254}{}{28号}
{255}{}{再来，我们会集合队员。}
{256}{}{你有什么问题？}
{257}{}{你就是问题，而我的拳头就是解决方案。}
{258}{}{你最好小心点。}
{260}{}{是你。}
{261}{}{没问题。}
{262}{}{好的。如果你改变主意再来。}
