
{100}{}{你好！欢迎来到我的二手车展厅。今天你对哪辆车感兴趣？}
{101}{}{你一定在开玩笑。这些车全是破烂。}
{102}{}{呃，没什么，谢谢。}
{103}{}{笨蛋！}
{104}{}{哦，对不起，你看起来负担不起我们的融资利率。}
{105}{}{但是，先生，这些都是优质的机动车。}
{106}{}{女士，这些都是绝佳的车辆。}
{107}{}{它们不可能还能开。}
{108}{}{好吧，随便你。再见。}
{109}{}{这些车都经过我们专门服务部门的100点全面检修。}
{110}{}{你的服务部门在哪儿？}
{111}{}{你是个疯子。}
{112}{}{再见。}
{113}{}{就在那边，先生。[销售员指向空无一物的地方。]}
{114}{}{就在那边，女士。[销售员指向空无一物的地方。]}
{115}{}{哪里？那边什么都没有。}
{116}{}{你疯了。}
{117}{}{你什么意思？他们正在修一辆新买的'56年款Corvega。我还要说这是一笔不错的买卖。}
{118}{}{好吧，随你怎么说。}
{119}{}{你简直疯了。}
{120}{}{再见。}
{121}{}{我们还有很好的保修服务。你可以回来找我们换机油，第一次是免费的。你觉得怎么样？}
{122}{}{如果你能加满一箱油，那就成交。}
{123}{}{你需要帮助。}
{124}{}{我现在要走了。}
{125}{}{抱歉，我们没有汽油。也许下次吧。再见。}
{126}{}{我感到被冒犯了。我不需要从顾客那里听这些。祝你有美好的一天。}
{127}{}{我在喝咖啡，稍后再来。}
{128}{}{去吧，试驾一圈。}
{129}{}{你应该加上防锈漆。}
{130}{}{我可以为你推荐一个汽车报警器吗？}
{131}{}{你好！我是鲍勃。}
