{100}{}{你看到德米特里。}
{101}{}{嘿！你好吗？我叫德米特里，德米特里·罗马拉，是废土上最棒的商队的负责人。你在找工作吗？}
{102}{}{嗯……你看起来不太强壮，不过……你一定很擅长用枪才能在外面活下来！见鬼，当需要的时候你肯定是个狠角色！}
{103}{}{你看起来很健康。}
{104}{}{你看起来很强壮。}
{105}{}{该死，你看起来很强壮！}
{106}{}{该死！你看起来能举起一座山！}
{107}{}{是啊，那又怎么样？}
{108}{}{关你什么事？}
{109}{}{嗯？}
{110}{}{这正是我们需要的！你喜欢战斗的刺激和兴奋，不是吗？！子弹在你头边飞过，把敌人打成两半，看到他们眼中的恐惧！啊，这才是生活！你看起来就是那种能为我们效力的人，而且我们支付得很好！哦，是的，我们确实支付得很好！我们刚刚有几个新职位空缺，如果你有兴趣的话；当然你有兴趣，对吧？！}
{111}{}{工资是多少？}
{112}{}{我会杀掉任何挡路的东西！}
{113}{}{不用了，谢谢。}
{114}{}{我需要一个水芯片。}
{115}{}{你对失踪的商队知道些什么？}
{116}{}{我得走了。}
{117}{}{呃呃呃！}
{118}{}{我们每次任务支付600集市币！这是单程的！见鬼，人们说我们走的都是危险路线，但我说那是最刺激的！你需要生活中有点刺激，对吧？当然对了！}
{119}{}{见鬼，我想这正是我想要的！}
{120}{}{你总是这么大声说话吗？}
{121}{}{危险？}
{122}{}{不用了，伙计。}
{123}{}{当然危险！去找隔壁房间的凯莉，她会告诉你下一个商队什么时候出发。}
{124}{}{伙计？你在说什么鬼话？不过这不关我的事。}
{125}{}{怎么，你害怕大声吗？}
{126}{}{是的。}
{127}{}{只有在晚上。}
{128}{}{不，我只是想知道你是不是聋了还是哑了。}
{129}{}{不，不过我耳朵有点疼。}
{130}{}{哈！可能两者都是！好吧，如果你想要工作，就去找隔壁房间的凯莉。}
{131}{}{你是个聪明的小家伙，不是吗？不过，这对我来说无所谓！只要你能保护商队我就满意了。如果你想要工作，就去找隔壁房间的凯莉。}
{132}{}{哈！这真有趣！好吧，如果你敢面对黑暗，就来找我。}
{133}{}{当然危险——不然我为什么要支付600块？}
{134}{}{哦，好吧。再见。}
{135}{}{我还是要这份工作。}
{136}{}{滚出去，不然我撕了你的头！}
{137}{}{我会把你的头塞进你的屁股里！}
{138}{}{就这样！}
{139}{}{当然会！去找隔壁房间的凯莉，她负责安排时间表。}
{140}{}{见鬼，这真让人失望，不过算了。}
{141}{}{是啊！我喜欢你！你被录用了！去找隔壁房间的凯莉，她会给你分配一个商队。}
{142}{}{水芯片？嗯，从没听说过。你可以去外面的商店看看——他们有很多东西。那么，你想要工作吗？}
{143}{}{那么，工资是多少？}
{144}{}{不，没什么。}
{145}{}{不多，我只丢了两个。我真的不知道为什么他们比其他人更喜欢袭击远行商队。}
{146}{}{有什么怀疑吗？}
{147}{}{关于你的路线和货物呢？}
{148}{}{好的，谢谢。}
{149}{}{无论是谁干的，肯定有一个强大的袭击队伍。我们的商队武装很好，你会认为有人能逃脱的。他们没有留下任何痕迹。}
{150}{}{那么，那份工作的工资是多少？}
{151}{}{关于你的路线和货物呢？}
{152}{}{好的，谢谢。}
{153}{}{见鬼，我们去的地方比他们更危险，而且我们的货物更好！}
{154}{}{你的货物怎么更好？}
{155}{}{只是看看，谢谢。}
{156}{}{你满嘴胡扯！}
{157}{}{好吧，好吧——也许不更好，但我们确实比他们携带更多种类。}
{158}{}{好的，谢谢。}
{159}{}{你知道吗，贝丝一直在说什么死亡爪。如果我是你，我会去查查！我从其他来源听到一些关于晚上在西北方向有东西在徘徊的传闻。}
{160}{}{抱歉，但我们支付了高额报酬确保工作完成！我们只雇佣最好的！我们必须在那些商队上有可靠的人！}
{161}{}{好像我真的想要这份工作似的，你这个大嗓门的白痴！}
{162}{}{抱歉打扰你了。}
{163}{}{请，我能再要一份工作吗？}
{164}{}{胡塔？}
{165}{}{我说过我们不会雇佣你！}
{166}{}{抱歉，我不再冒险和你合作了！}
{167}{}{你在这里浪费时间！}
{168}{}{请不要再打扰我！}
{169}{}{滚开。}
{170}{}{德米特里无视你。}
{171}{}{见鬼，我不雇佣那些嗑药的瘾君子！如果你想要工作，最好清醒过来！}
{172}{}{我不是嗑药者……我是说……啊！}
{173}{}{呸！}
{174}{}{嗑药吗？见鬼，幸好我们不再雇佣你了！}
{175}{}{见鬼，不！我不认为你意识到到底有多少风险！我们无法承担这个风险！见鬼，我不知道远行商队怎么还能在那些失踪的商队中维持生意！}
{176}{}{抱歉，你得看看其他商队是否愿意冒险雇佣你。我不能再冒险了。}
{177}{}{滚出去，你让我恶心！}
{178}{}{嘿！你以为你在干什么？}
{179}{}{那通向我们的仓库。}
{180}{}{只能从另一边打开。}
{181}{}{你真是个怪人。}
{182}{}{你在浪费时间。}
{183}{}{他无视你。}
{184}{}{那么？你想要工作还是怎样？我给你一个绝佳的机会，既刺激又能赚大钱！这两样东西永远不嫌多！}
{185}{}{哦，是的。那是多少来着？}
{186}{}{我会杀掉任何挡路的东西！}
{187}{}{不用了，谢谢。}
{188}{}{我需要一个水芯片。}
{189}{}{你对失踪的商队知道些什么？}
{190}{}{我得走了。}
{191}{}{鲁克鲁克？}
{192}{}{嘿，你上次商队的工作干得不错——干得好！你需要什么吗？}
{193}{}{是的，我想要另一份工作。}
{194}{}{我需要一个水芯片。}
{195}{}{你对失踪的商队知道些什么？}
{196}{}{没有。只是过来打个招呼。}
{197}{}{没事，再见。}
{198}{}{我们失去了所有的货物！恐怕我们不能再雇佣你了，抱歉。}
{199}{}{你真幸运，我们差点失去了你逃跑的那个商队！恐怕我们不能再雇佣你了，抱歉。}
{200}{}{我们不在招聘，所以你想要什么？}
{201}{}{滚开！我们不在招聘。}
{202}{}{我需要一个水芯片。}
{203}{}{告诉我你对失踪的商队知道些什么。}
{204}{}{我想让你的丑脸从我面前消失！}
{205}{}{我想要你的头插在棍子上！}
{206}{}{算了。}
{207}{}{鲁克鲁克？}
{208}{}{你以为你很厉害吗？别让我笑掉大牙！}
{209}{}{好吧，你应该和我女儿凯莉谈谈；她负责所有这些！她在隔壁房间。}
{210}{}{我已经告诉过你了。去找隔壁房间的凯莉。}
{211}{}{你女儿？}
{212}{}{那个丑东西是你女儿？这就解释了一切！}
{213}{}{好的。}
{214}{}{是的，她是我的骄傲和喜悦！她不是很漂亮吗？当你想要另一份工作时，就去找她。有一天……希望很快，我能退休，她会接替我。}
{215}{}{你不能，如果你们都死了！}
{216}{}{好的，谢谢。}
{217}{}{你敢侮辱别人的家人？我应该撕了你的心！}
{218}{}{对不起，我只是开玩笑！}
{219}{}{我会做的不仅仅是侮辱你！}
{220}{}{道歉太晚了！[他的脸变得非常红……然后用平静、控制的声音说。]滚，不然我就兑现我的威胁！}
{221}{}{这是你可怜的威胁尝试吗？}
{222}{}{这不是威胁！你快死了！}
{223}{}{是啊，我尽力了！}
{224}{}{不，我很抱歉。我得走了。再见！}
{225}{}{好吧，我得承认，我听过更好的。}
{226}{}{是的，我知道。再见。}
{227}{}{好吧，你还是要死！}
{228}{}{呃，好吧。}
{229}{}{那么，你还在等什么？商队要出发了！}
{230}{}{他们还没准备好出发。}
{231}{}{我还有些事情要先做。}
{232}{}{我需要一个水芯片。}
{233}{}{告诉我你对失踪的商队知道些什么。}
{234}{}{好的，再见。}
{235}{}{里克洛克？}
{236}{}{罗罗？}
{237}{}{该死！你错过了一些好戏！我敢肯定有很多人、怪物和东西在等着袭击商队！没有什么比一场激烈的枪战更刺激的了！这里——拿着这个，它会给你一些乐子，直到下一个商队准备好出发。[他递给你一个手榴弹。]}
{238}{}{该死！我们的商队什么时候出发？}
{239}{}{你的船呢？}
{240}{}{别花太长时间。}
{241}{}{凯莉，我们订满了吗？}
{242}{}{你得在敌人干掉你之前干掉他们！}
{243}{}{没有什么比掐死你的敌人更爽的了！}
{244}{}{你才不是！}
{245}{}{该死，我的枪呢！}
