{100}{}{你看到戴安娜，一个沙漠掠夺者。}
{101}{}{我是戴安娜。今天有什么我可以帮你的吗？}
{102}{}{我在找一个叫坦迪的女人。你见过她吗？}
{103}{}{没事了，谢谢。}
{104}{}{要不要约个会？}
{105}{}{你在这里做什么？}
{106}{}{你能告诉我关于这个营地的情况吗？}
{107}{}{呃？}
{108}{}{如果她是阴影沙地的人，你应该去那里找。我只是个打工的。}
{109}{}{哦。无论如何，谢谢你。}
{110}{}{你能帮我修理装备吗？}
{111}{}{如你所见，我现在太忙了，无法满足你的请求。}
{112}{}{加尔让我现在修理营地设备。我没有时间修理我们的装备，更别说每个进来的陌生人的了。抱歉。}
{113}{}{我是这个营地的军械师。我是唯一一个有能力修理和维护加尔手下武器和装备的人。}
{114}{}{你能帮我修理装备吗？}
{115}{}{你能告诉我关于这个营地的情况吗？}
{116}{}{这里由加尔·死亡之手管理。他是一个可怕且无情的领袖。他确保我们在沙漠的严酷现实中生存下来。}
{117}{}{我在找一个叫坦迪的女人。你见过她吗？}
{118}{}{你能帮我修理装备吗？}
{119}{}{我现在很忙。请去别处。}
{120}{}{你是加尔的新朋友，对吧？你想要什么？}
{121}{}{嗯。你的装备看起来运转正常。我有更重要的任务。}
