{100}{}{你看到蛇。}
{101}{}{你看到多尔根。}
{102}{}{}
{103}{}{}
{104}{}{你看到刀锋帮的一员。}
{105}{}{你看到刀锋帮的一员。}
{106}{}{你觉得那可能是书本。}
{107}{}{你觉得那可能是伤疤。}
{108}{}{你觉得那可能是枪手。}
{109}{}{你觉得那可能是抽搐。}
{110}{}{你觉得那可能是锤子。}
{111}{}{你觉得那可能是剃刀。}
{112}{}{滚开！这里只欢迎真正的战士。}
{113}{}{所以，你觉得你能对付唐格勒和他的废物们？来，我教你怎么用刀。}
{114}{}{现在你的刀技稍微好了一点。去帮我把唐格勒揍到明年去吧。}
{115}{}{干得好，搞定那些撕裂者。有什么我能帮你的吗？}
{116}{}{你能教我更多的刀技吗？}
{117}{}{我怎么才能进入枪械跑者的地盘？}
{118}{}{没事，谢谢。}
{119}{}{当然可以。但这需要大半天时间来稍微提升一下。你还想要吗？}
{120}{}{是的。}
{121}{}{不。}
{122}{}{好了。你有了一点进步。祝你好运。}
{123}{}{当然。想要更多训练时再来找我。}
{124}{}{看来我们放进来一个傻瓜。好吧，如果你想进入他们的地盘，他们的护城河有个小缺口。找找看，然后拼命跑。也许你能成功过去。}
{125}{}{谢谢。}
