{100}{}{你看到一个亚裔的流浪商人。}
{101}{}{你看到杜克，一个流浪商人。}
{102}{}{你好，流浪者。我叫杜克，我正前往阴影沙地进行交易。也许我能让你对一些商品感兴趣？}
{103}{}{你有什么东西出售？}
{104}{}{你经常去阴影沙地吗？}
{105}{}{呃！}
{106}{}{让我给你看看。}
{107}{}{是的，阴影沙地是我常规贸易路线的一部分。如果你愿意，可以和我们一起去，那样更安全。}
{108}{}{当然，听起来不错。}
{109}{}{不，谢谢。}
{110}{}{哦，抱歉——没意识到你这么愚蠢。}
{111}{}{只需要一天左右的时间。我们走吧！}
{112}{}{ShadyW.map}
{113}{}{很少有人敢独自穿越荒野。你是谁？}
{114}{}{不关你的事。}
{115}{}{我是}
{116}{}{。}
{117}{}{呃！}
{118}{}{又见面了！我能为你做些什么？}
{119}{}{我可以加入你们去阴影沙地的队伍吗？}
{120}{}{你有什么东西出售？}
{121}{}{不用了，谢谢。}
{122}{}{你想要什么？}
{123}{}{没什么，抱歉。}
{124}{}{你有什么东西出售？}
{125}{}{呃！}
{126}{}{如果你独自旅行，应该小心。最近有些人从阴影沙地失踪了。}
{127}{}{嘿，我听说你救了阴影沙地的那个女人。干得好。}
