{100}{}{你看到酒吧招待。}
{101}{}{是啊，你想要什么？}
{102}{}{水。}
{103}{}{啤酒。}
{104}{}{烈酒。}
{105}{}{给我最快能醉的东西。}
{106}{}{什么都不要。}
{107}{}{嗯？}
{108}{}{如果你没有瓶盖，就滚出去！}
{109}{}{随便你。}
{110}{}{我觉得你喝得够多了，伙计。}
{111}{}{我觉得你喝得够多了，女士。}
{112}{}{是啊……那就走吧。}
{113}{}{那是两个瓶盖。}
{114}{}{好的。}
{115}{}{不用了，谢谢。}
{116}{}{那是五个瓶盖。}
{117}{}{当然。}
{118}{}{那是十个瓶盖。}
{119}{}{嗯，对于你这样的体型……}
{120}{}{}
{121}{}{ 十个}
{122}{}{ 二十个}
{123}{}{ 三十个}
{124}{}{ 四十个}
{125}{}{ 五十个}
{126}{}{ 六十个}
{127}{}{ 七十个}
{128}{}{ 八十个}
{129}{}{ 九十个}
{130}{}{ 一百个}
{131}{}{ 瓶盖应该够了。}
{132}{}{太好了！那是}
{133}{}{ 瓶盖，再来一次。}
{134}{}{继续来。}
{135}{}{算了。}
{136}{}{给你。（酒保递给你一个装满浑浊水的脏锡杯。}
{137}{}{ 喝完水后，你嘴里有一种奇怪的味道。}
{138}{}{给你。（酒保又递给你一个装满同样浑浊水的杯子，喝完后，你想起上次喝时的奇怪味道……}
{139}{}{这应该很有趣……（酒保继续倒酒，你失去了计数。过了一会儿，你听到一声闷响，然后}
{140}{}{ 你意识到自己趴在地板上，脸朝下……}
{141}{}{又来了……（酒保把酒排好，周围的人开始喊……}
{142}{}{ ……}
{143}{}{ ……}
{144}{}{ ……}
{145}{}{ （很快一切开始模糊……）}
{146}{}{没想到你看起来不像能喝酒的人。}
{147}{}{真可惜。我们都期待着再次看到你的“表演”。}
{148}{}{哎……你不打算再给我们展示一下你的“本事”吗？好吧，给你啤酒。还要别的吗？}
{149}{}{你确定能抵挡住诱惑吗？你上次的表现可不一般。好吧，给你。（酒保递给你一瓶烈酒。）还要别的吗？}
{150}{}{给你。（酒保递给你一瓶啤酒。）还要别的吗？}
{151}{}{再给我来一杯！}
{152}{}{给你。（酒保递给你一瓶烈酒。）}
{153}{}{ 还要别的吗？}
{154}{}{你嘴里有很不好的味道。}
{155}{}{你觉得你的头快要爆炸了。}
{156}{}{你看到一个掷骰子的人。}
{157}{}{你看到一个轮盘赌庄家。}
{158}{}{你看到一台老虎机。}
{159}{}{你注意到赔率似乎不太对。}
{160}{}{你觉得骰子被做了手脚。}
{161}{}{你觉得桌子被动了手脚。}
{162}{}{请下注。}
{163}{}{5个瓶盖。}
{164}{}{15个瓶盖。}
{165}{}{25个瓶盖。}
{166}{}{50个瓶盖。}
{167}{}{不用了，谢谢。}
{168}{}{呃。}
{169}{}{抱歉，你现在的状态不适合下注。（你看着游戏，完全糊涂了。}
{170}{}{抱歉，下次好运。}
{171}{}{赢了！（你推了。）}
{172}{}{赢了！（你得到双倍的钱。）}
{173}{}{赢了！（你得到三倍的钱。）}
{174}{}{你得有钱才能玩，伙计。}
{175}{}{你得有钱才能玩，女士。}
{176}{}{你注意到赔率似乎差不多对。}
{177}{}{（你投入多少钱？）}
{178}{}{1个瓶盖。}
{179}{}{2个瓶盖。}
{180}{}{3个瓶盖。}
{181}{}{4个瓶盖。}
{182}{}{5个瓶盖。}
{183}{}{什么都没有。}
{184}{}{（你不知道该怎么用它，但它看起来很漂亮。）}
{185}{}{（你输了。）}
{186}{}{（你推了。）}
{187}{}{（你得到双倍的钱。）}
{188}{}{（你得到三倍的钱。）}
{189}{}{（你没有足够的钱。）}
{190}{}{你现在有}
{191}{}{ 瓶盖。你想下注多少？}
{192}{}{  你想再玩吗？}
{193}{}{4 瓶盖。}
{194}{}{5 瓶盖。}
{195}{}{什么都没有。}
{196}{}{（你不知道怎么用它，但它看起来确实很漂亮。）}
{197}{}{（你输了。）}
{198}{}{（你推动。）}
{199}{}{（你获得双倍奖金。）}
{200}{}{（你获得三倍奖金。）}
{201}{}{（你没有足够的钱。）}
{202}{}{你目前有}
{203}{}{ 瓶盖。你想下注多少？}
{204}{}{  你想再玩一次吗？}

