{100}{}{你看到一个农夫。}
{101}{}{你好，陌生人。喜欢我的庄稼吗？}
{102}{}{早上好！}
{103}{}{下午好！}
{104}{}{晚上好，朋友！}
{105}{}{天气不错，是吧？}
{106}{}{这片土地比看起来要肥沃得多。}
{107}{}{我正在努力拯救这些树，我觉得已经见效了。}
{108}{}{应该有个化肥商队。那可是笔好买卖。}
{109}{}{进来吧，这里有的是地方。}
{110}{}{外面有点冷，坐下休息一下吧。}
{111}{}{务农很适合我。}
{112}{}{你知道吗？对植物友好，它们长得更好。}
{113}{}{我希望能有更多的土地。}
{114}{}{你知道以前有大量可饮用的水体吗？}
{115}{}{我读过关于河流的书。我真希望我的田地旁边有一条。}
{116}{}{我希望白天能长一点，还有好多事情要做。}
