{100}{}{你看到法戈商队的车队司机。}
{101}{}{嗨，如果你想在商队找份工作，你应该去找鲁特格。他就在那边。}
{102}{}{你得去找鲁特格谈谈。}
{103}{}{所以你签约了。听到这个消息真好。我们每十天左右出发，也就是每月的8号、18号和28号。现在我们正往钢铁兄弟会、废城和洛杉矶墓园跑。}
{104}{}{那么薪水是多少？}
{105}{}{嗯。}
{106}{}{你会得到400个中心币。你可能会说这不多，但我们经常出发，而且你不会轻易丢掉性命。不过你来回都能拿到这笔钱，不是说你必须来回跑，但如果你都跑了，总共能拿到800。}
{107}{}{我们今天出发。你有兴趣吗？}
{108}{}{我们将在}
{109}{}{空}
{110}{}{}
{111}{}{出发。你有兴趣吗？}
{112}{}{我还是会给你工作，尽管……算了。你有兴趣吗？}
{113}{}{当然。}
{114}{}{不。}
{115}{}{可能吧。}
{116}{}{好吧。}
{117}{}{怎么说？}
{118}{}{好的，没问题。如果你改变主意，告诉我。}
{119}{}{你能不能快点决定？}
{120}{}{如果你最后找不到事情做，就回来吧。那是8号、18号和28号。再见。}
{121}{}{呃，如果你连左右脚都分不清，那就不行了。抱歉，大块头。}
{122}{}{感觉好些的时候再回来吧。}
{123}{}{伙计，你看起来不太好。你应该吃点东西，不过别去鲍勃那儿。}
{124}{}{快滚出去！}
{125}{}{不能就这么放过我的东西，是吧？你为什么要这么做？}
{126}{}{因为我是来自外太空的绿色恶霸，我……很“坏”！}
{127}{}{我不想这样，但我快饿死了，还有孩子要养。}
{128}{}{我会用勺子挖出你的心！}
{129}{}{（投降）}
{130}{}{（攻击）}
{131}{}{所以你就是在我脸上吐口水，是吧？我猜唯一能让你明白的办法就是把你的脑袋从脖子上摘下来。}
{132}{}{好吧，但这并不代表你是对的。你还是得离开这里。}
{133}{}{你觉得我会相信这种鬼话吗？卫兵！}
{134}{}{也许把你关进牢里会让你学会礼貌。你是愿意乖乖跟我走，还是我们得来硬的？}
{135}{}{地狱见！}
{136}{}{是的。我很抱歉。}
{137}{}{所以你是个硬汉，是吧？又想找麻烦？}
{138}{}{如果你不离开，我就报警！}
{139}{}{卫兵！警察！}
{140}{}{我觉得你该离开了。}
{141}{}{抱歉，我不能给你工作。}
{142}{}{我很想给你工作，但这不可能。}
{143}{}{离开。}
{144}{}{挺可爱的，但我对你这种人不感兴趣。}
{145}{}{好吧！薪水是400个中心币。你想选哪条路线？}
{146}{}{听到这个消息真好。回来吧，}
{147}{}{8号}
{148}{}{18号}
{149}{}{28号}
{150}{}{}
{151}{}{}
{152}{}{钢铁兄弟会}
{153}{}{。到时候你就出发。和往常一样，薪水是400个中心币。}
{154}{}{好的。}
{155}{}{抱歉，等不了。}
{156}{}{不知发生了什么，整个商队都没了。这样的事情发生真是奇怪，而你却是唯一幸存的人？事情通常不会这样。我想我不能再雇你了，希望你理解原因。}
{157}{}{废城}
{158}{}{洛杉矶墓园}
{159}{}{嗯，现在不行。也许下次吧。}
{160}{}{听到这个消息真好，我会召集其他人。}
{161}{}{太好了。}
{162}{}{快滚出去。祝好运！}
{163}{}{尽量避免麻烦，别主动去找。}
{164}{}{你在外面要小心，墓园不是个安全的地方。}
{165}{}{那很好。那些黑色走道真的很奇怪，但它们很适合旅行。}
{166}{}{那边确实有些不良分子。我建议你在那边的时候注意和谁打交道。}
{167}{}{太好了。废城不是个坏地方。}
{168}{}{哦，顺便去找基莱恩，替我问声好。我们以前在商队上度过了很多美好时光。}
{169}{}{听说那边有个怪医生。据说他和死人打交道。}
{170}{}{你到底在想什么，离开了那个商队。它安全回来，但那纯粹是运气。}
{171}{}{我能再有一次机会吗？}
{172}{}{没什么。}
{173}{}{我才不在乎！}
{174}{}{伊格 瓦 尼卡 罗拉？}
{175}{}{利格。}
{176}{}{你又搞砸了。你似乎无法胜任这项工作。}
{177}{}{我为什么要这样做？}
{178}{}{你不应该。}
{179}{}{因为如果你不这样做，我就会在你脑袋上打个洞。}
{180}{}{我有更好的事情要做，而不是在某个愚蠢的商队上闲逛。}
{181}{}{我不知道我不能离开。一切看起来都没问题。}
{182}{}{我明白了……你在嗑药。好吧，如果你愿意过这种生活。}
{183}{}{很遗憾你这么想。}
{184}{}{令人惊讶的是你以前没这样做过。既然如此，我给你另一个机会也无妨。}
{185}{}{你干得不错。你想再签约吗？}
{186}{}{当然。}
{187}{}{不。}
{188}{}{可能吧。}
{189}{}{哎呀！}
{190}{}{鲁布。}
{191}{}{拿好你的装备了吗？我们今天出发。}
{192}{}{是的。}
{193}{}{不！}
{194}{}{哎呀！}
{195}{}{否则我就把工作给别人，别担心。在你跟商队出发之前，你没有义务……对吧？}
{196}{}{下次商队出发是}
{197}{}{8号}
{198}{}{18号}
{199}{}{28号}
{200}{}{}
{201}{}{}
{202}{}{}
{203}{}{。如果你还想要这份工作，就回来吧。}
{204}{}{一月}
{205}{}{二月}
{206}{}{三月}
{207}{}{四月}
{208}{}{五月}
{209}{}{六月}
{210}{}{七月}
{211}{}{八月}
{212}{}{九月}
{213}{}{十月}
{214}{}{十一月}
{215}{}{十二月}
{216}{}{钢铁兄弟会，我们来了！虽然我不跟你去，但你懂我意思。}
{217}{}{好吧，快从我面前消失。那些兄弟会狂热分子在等你。}
{218}{}{希望你喜欢山！你将直接进入它们。那里应该会有很多行动。}
{219}{}{准备出发，你将直接穿越山脉！这应该会很刺激！}
