{100}{}{小心点对待医生，否则我就要对你不客气了。}
{101}{}{我们关门了。请稍后再来。}
{102}{}{我得见医生。}
{103}{}{好的，我会的。}
{104}{}{我必须见医生，非常重要。}
{105}{}{嗯。}
{106}{}{今天天气不错吧？}
{107}{}{真不巧。快走，天亮前别回来。诊所晚上不营业。}
{108}{}{等一下，我得去问问医生。}
{109}{}{你现在想要什么？}
{110}{}{我得见医生。}
{111}{}{医生在吗？}
{112}{}{嗯！}
{113}{}{不行。医生在休息。请稍后再来。}
{114}{}{我不知道，你自己去问他吧。}
{115}{}{好吧，出去。}
{116}{}{嘿，这是私人领地。你最好现在就离开。}
{117}{}{吃屎去吧。}
{118}{}{如果你不让开，你就会需要医生来处理私人问题了。}
{119}{}{你不知道女人是弱者吗？}
{120}{}{觉得我弱？那就看看这个……}
{121}{}{我这就走。}
{122}{}{把你那可笑的威胁收起来，回家找妈妈吧。你在跟一个真男人说话。}
{123}{}{觉得我弱？那就看看这个……}
{124}{}{我这就走。}
{125}{}{哇！如果你真的想见他，那就去吧。}
{126}{}{那医生什么时候在？}
{127}{}{医生接诊时间是8点到5点。现在走吧。}
{128}{}{医生什么时候在？}
