{100}{}{你看到夜行者的卢。}
{101}{}{你看到夜行者的苏。}
{102}{}{你看到夜行者的德鲁。}
{103}{}{你看到夜行者的库尔特。}
{104}{}{你看到夜行者的伯特。}
{105}{}{你看到夜行者的泰克。}
{106}{}{你看到夜行者的迈克。}
{107}{}{你看到夜行者的查尔。}
{108}{}{你看到夜行者的蕾恩。}
{109}{}{你看到夜行者的达加斯。}
{110}{}{我被告知要带你去做点事。关于普通人的事。我不记得是什么了。}
{111}{}{我觉得普通人很愚蠢。}
{112}{}{所有普通人都该死！}
{113}{}{乌瑟恩是个聪明的家伙。嗯哼。}
{114}{}{老板说普通人什么都不是。}
{115}{}{不知道老板为什么要这些书。}
{116}{}{我很高兴那些愚蠢的普通人不在。他们很丑。}
{117}{}{我比你强！我比你强！}
{118}{}{我现在就把你压扁！}
