{100}{}{我们不是来聊天的。}
{101}{}{我会追随你直到死亡。}
{102}{}{这可是个相当重要的任务，对吧？}
{103}{}{妮可说我们必须尽可能地造成破坏。}
{104}{}{下一个我能杀谁？}
{105}{}{我们在这儿闲聊干什么？}
{106}{}{我很不喜欢这些穿棕色长袍的混蛋，非常感谢。}
{107}{}{这可能会很危险。}
{108}{}{该走了。}
{109}{}{这地方看起来像墙上的一坨屎。}
{110}{}{我觉得我要吐了。}
{111}{}{妮可告诉我们，一旦你离开大教堂就立刻返回。}
{112}{}{很高兴见到你。让我们开始吧。}
