{100}{}{你看到追随者的见习者沃尔特。}
{101}{}{你看到追随者的见习者尼古拉斯。}
{102}{}{你看到追随者的见习者威廉。}
{103}{}{你看到追随者的见习者马修。}
{104}{}{你看到追随者的见习者约翰。}
{105}{}{你看到追随者的见习者梅勒妮。}
{106}{}{你看到追随者的见习者珍妮。}
{107}{}{你看到追随者的见习者洛莉。}
{108}{}{你看到追随者的见习者莎拉。}
{109}{}{你看到追随者的见习者克里斯汀。}
{110}{}{愿和平在这片恐怖的废土中引导你。}
{111}{}{我迫不及待想和孩子们战斗。}
{112}{}{如果我不能成为学者，那我想成为抄写员。}
{113}{}{我最终想成为一名学者。}
{114}{}{那些帮派真的应该停止争斗。}
{115}{}{我想知道和平的世界会是什么样。}
{116}{}{我听说有人把我们的知识传给了孩子们。}
{117}{}{那些夜行者让我害怕。}
{118}{}{只有侦察员可以在日落后外出。}
{119}{}{我想知道学者们从哪里得到新书。}
{120}{}{因为那个间谍，我们失去了很多人。}
{121}{}{我听到尼尔说间谍可能是新来的人。}
{122}{}{请尽快找到间谍。}
{123}{}{我想知道妮可会不会让我们真正使用这种战斗技巧。}
{124}{}{如果安柏现在看到我们，她会很生气。}
{125}{}{尼尔很高兴你愿意教我们。}
{126}{}{现在我可以一个人对付所有的孩子们！}
