{100}{}{你看到一个全副武装的壮汉。}
{101}{}{你看到加布里埃尔，枪械跑商的领袖。}
{102}{}{我们这儿不常有访客，我能帮你什么忙？}
{103}{}{为什么你们这儿不常有访客？}
{104}{}{你们在这里做什么？}
{105}{}{我们工厂外面有一窝该死的死亡爪，这地方不太好进。}
{106}{}{你们看起来武装得不错，为什么不去消灭它们？}
{107}{}{我们去过几次，干掉了一些，但它们总是会回来。再说了，我们是机械师，不是战士。}
{108}{}{如果我帮你们解决它们，你们会给我什么？}
{109}{}{我们制造武器和弹药。我们已经做了30年了，但过去的10年简直是地狱。}
{110}{}{为什么这么说？}
{111}{}{我们已经把工厂周围的战后废金属都用光了。现在我们得依靠阿迪特姆来供应原材料。}
{112}{}{阿迪特姆供应你们材料有什么不好？}
{113}{}{一开始还不错。他们供应我们原材料，我们制造并出售武器。但三年前，齐默曼雇佣了一些雇佣兵来保护阿迪特姆免受死亡爪和偶尔袭击的掠夺者的攻击。那些监管者是冷血的混蛋，榨取我们所有的东西。我们制造枪支，他们却大发横财。}
{114}{}{你们为什么不干脆离开，去别的地方安顿呢？}
{115}{}{这真是艰难。你们会给我什么来解决死亡爪的问题？}
{116}{}{如果可以我们早就走了。但搬迁是个大工程，所有的车床和铣床都不是轻易能搬走的东西。我们可以搬，但死亡爪让这变得不可能。}
{117}{}{你们看起来武装得不错，为什么不去消灭它们？}
{118}{}{如果你能彻底解决死亡爪的问题，你可以开出你的价码。}
{119}{}{我要武器和弹药，而且要很多。}
{120}{}{}
{121}{}{如果你清理了那个区域，我们会离开，但会留下比你能用的更多的武器和弹药。}
{122}{}{好，成交。}
{123}{}{我得考虑一下。}
{124}{}{那些能解决你在阿迪特姆所有问题的人。}
{125}{}{你清理掉所有的死亡爪，就成交。}
{126}{}{好，我去做。}
{127}{}{我得考虑一下。}
{128}{}{又见面了。}
{129}{}{你们在这里做什么？}
{130}{}{再见。}
{131}{}{}
{132}{}{一切还算顺利。}
{133}{}{我想我已经杀光了所有的死亡爪。}
{134}{}{我们需要确认。过去两年我们杀了超过20只，但它们总是会回来。我们一直搞不清楚原因。再等几天，如果它们真的不再出现，我们会看看能为你做些什么。}
{135}{}{好的，谢谢。}
{136}{}{解决了死亡爪后通知我们。}
{137}{}{嗯，也许会再见。}
{138}{}{我知道，跟我说说吧。}
{139}{}{也许会再见。}
{140}{}{我们这儿不常有访客，我能帮你什么吗？}
{141}{}{为什么你们这儿没什么访客？}
{142}{}{你们在这里做什么？}
{143}{}{这个地方不太好进，工厂外面就有一窝该死的死亡爪。}
{144}{}{我已经杀光了所有的死亡爪，连那些该死的蛋也不放过。}
{145}{}{如果可以我们早就搬了。但搬迁对我们来说是个大工程，所有的车床和铣床都不是说搬就能搬的。我们可以搬，但死亡爪让这变得不可能。}
{146}{}{我已经杀光了所有的死亡爪，连那些该死的蛋也不放过。}
{147}{}{}
{148}{}{我要武器和弹药，越多越好。}
{149}{}{}
{150}{}{不用付我钱，你们的感谢就足够了。}
{151}{}{没问题——随便拿你想要的。我们一两天内就会撤离，但会留下比你现在能带走的更多的武器和弹药。随时回来取用。}
{152}{}{}
{153}{}{}
{154}{}{谢谢。}
{155}{}{}
{156}{}{不客气。}
{157}{}{}
{158}{}{}
{159}{}{你们不是要离开吗？}
{160}{}{我只是来拿点东西。今天有什么货？}
{161}{}{没什么。无论如何，谢谢。}
{162}{}{}
{163}{}{太好了。你们今天有什么货？}
{164}{}{好吧，那我待会儿再来。}
{165}{}{}
{166}{}{我只是来拿点东西。今天有什么货？}
{167}{}{没什么。无论如何，谢谢。}
{168}{}{抱歉，我现在没空和你聊，我很忙。}
{169}{}{枪，我喜欢枪！}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{170}{}{我有些朋友真的需要你们的武器。}
{171}{}{我有些朋友真的需要你们的武器。}
{172}{}{最近怎么样，我的朋友？}
{173}{}{最近怎么样，我的朋友？}
{174}{}{你说什么？！你把他们全干掉了？感谢上天！现在我们可以搬到能自己获取材料的地方，不用再依赖阿迪特姆的那些蛇了。你想要什么就拿什么，我的朋友。}
{175}{}{你说什么？！你把他们全干掉了？感谢上天！现在我们可以搬到能自己获取材料的地方，不用再依赖阿迪特姆的那些蛇了。你想要什么就拿什么，我的朋友。}
{176}{}{好吧。和你做生意很愉快，朋友。}
{177}{}{好吧。和你做生意很愉快，朋友。}
{178}{}{没问题。告诉你的朋友，他们的武器到手了。}
{179}{}{没问题。告诉你的朋友，他们的武器到手了。}
{180}{}{谢谢你，我的朋友。}
{181}{}{谢谢你，我的朋友。}
{182}{}{抱歉，我没法和你聊，朋友，我们正忙着打包搬家。你需要什么就拿什么吧。}
{183}{}{抱歉，我没法和你聊，朋友，我们正忙着打包搬家。你需要什么就拿什么吧。}
{184}{}{既然你的朋友已经解决了那些该死的监管者，我们就没理由离开了。}
{185}{}{既然你的朋友已经解决了那些该死的监管者，我们就没理由离开了。}
{186}{}{欢迎，朋友。我能帮你什么忙？}
{187}{}{欢迎，朋友。我能帮你什么忙？}

#
# Following Line is just to be translated normally.
#
{188}{}{你需要找扎克谈谈买东西的事。}
