{100}{}{你看到面前的是加尔，掠夺者的首领。}
{101}{}{你以为你能不受挑战地来到这里？这是你最致命敌人的巢穴！我们会让你死无葬身之地。我会亲手从你胸口撕出你的心脏，在我骄傲的战士面前吃掉它！}
{102}{}{我杀了你！}
{103}{}{我不明白。}
{104}{}{是的，你杀了我。我是来缠你的幽灵。}
{105}{}{你不该这么做。}
{106}{}{我杀了你！}
{107}{}{我不明白。}
{108}{}{是的，你杀了我。我是来缠你的幽灵。}
{109}{}{你不该这么做。}
{110}{}{如果你是我父亲，你会的，但你不是。你看起来像他，但行为不同。至今没有他的影像留下。你只能被除掉。}
{111}{}{我不相信！我无法相信！}
{112}{}{相信吧，伙计，你马上就要和我一起下地狱了！}
{113}{}{别告诉我该做什么，父亲。我现在统治着可汗，而你不过是虫子的食物。}
{114}{}{我还活着。}
{115}{}{我应该在你小时候就杀了你。}
{116}{}{别告诉我该做什么，父亲。我现在统治着可汗，而你不过是虫子的食物。}
{117}{}{我还活着。}
{118}{}{我应该在你小时候就杀了你。}
{119}{}{你应该的。现在太晚了。我是加尔·死亡之手。我统治着可汗。你应该死在坟墓里，而你将再次如此！}
{120}{}{我能看到你站在我面前，但我不相信这是真的。你想要什么？}
{121}{}{我要那个女孩被释放。现在。}
{122}{}{我要你退位。}
{123}{}{我要财富来买通天堂的门票。}
{124}{}{发誓你会回到坟墓，那就会实现。}
{125}{}{我发誓我会离开。}
{126}{}{那就这样吧。释放阴影沙地的女人，并护送这个人离开这里……}
{127}{}{你不统治这里。你不属于这里。让行尸走肉去死吧！}
{128}{}{绝不！}
{129}{}{这就是我喜欢的。主动性。但你不该在没有我命令的情况下杀了他们。我不喜欢过多的主动性。}
{130}{}{你想要什么？}
{131}{}{我希望你放了那个女孩。}
{132}{}{我希望你去死。}
{133}{}{我带着和平的意图来谈判释放坦迪。}
{134}{}{哼！}
{135}{}{你凭什么认为她在我这儿？}
{136}{}{我知道你有她。我跟踪你到这儿的。}
{137}{}{你的一名手下告诉我的。}
{138}{}{我知道。}
{139}{}{我讨厌他们这样做。我得让那个多嘴的人为他的罪行付出代价。不过得等我先解决了你。}
{140}{}{嗯。那么，你打算用什么来换她的自由？}
{141}{}{我代表着一种你无法理解的威胁。你真的想冒险激怒我们吗？}
{142}{}{我会给你同等价值的东西。}
{143}{}{这对你的灵魂永恒有益。}
{144}{}{你的血，洒在地上。}
{145}{}{嗯，出于某种原因，我相信你。你可以带走那个女孩，但不要再回来，除非你想激怒我们。}
{146}{}{哈！你不该威胁比你强大的人。}
{147}{}{它一定非常有价值。给我看看。}
{148}{}{这让我很满意。你可以带走那个女孩，但不要再回来。}
{149}{}{你的贿赂不值得我浪费时间。杀了他。}
{150}{}{你以为像我这样的人会相信来世吗？这个世界正在死去，我会拿走我想要的！你永远无法理解做出这种决定所需的力量！}
{151}{}{你现在想要什么？}
{152}{}{没什么。}
{153}{}{我要那个女孩。}
{154}{}{洛克。}
{155}{}{那你打扰我了。离开。}
{156}{}{我们勉强容忍你。为什么要把我们最珍贵的东西给你？}
{157}{}{这是理所应当的。}
{158}{}{我有同等价值的东西。}
{159}{}{你可以活命。}
{160}{}{对吗？！这里是我说了算。你是在冒险踩在危险的边缘。}
{161}{}{抱歉。}
{162}{}{我凭什么要在乎？我带走这个女孩了。}
{163}{}{没错，你确实是。 我不容忍没有骨气的狗杂种。我们不容忍的，就会摧毁，杀了他。}
{164}{}{你愿意为了她和我较量吗？}
{165}{}{不，我是个情场高手，不是打手。}
{166}{}{当然。现在，就你和我。}
{167}{}{我会单挑你和你的整个帮派。}
{168}{}{好吧。我们来一场没有武器的对决吧。打晕我，你就可以带女人走。要是我打晕你，你就空手离开。}
{169}{}{成交。}
{170}{}{这会很有趣，但不太有体育精神。好吧，我们开始吧。}
{171}{}{好。}
{172}{}{嗯，你打得比我预料的好。我自从被我爸甩得满地找牙之后就没挨过这么痛快的打。你当之无愧地赢得了沙地村的女人。带她走吧。我劝你最好别再回来。}
{173}{}{带着你那条落魄的尾巴滚吧。要是再敢回来，我可不会这么仁慈。}
{174}{}{你想要什么？}
{175}{}{我是个探险者。}
{176}{}{我想加入。}
{177}{}{我们不喜欢这种人。我们不允许那种人存在。杀了他。}
{178}{}{你？想加入我们？为了什么？}
{179}{}{为了好好地干一架。}
{180}{}{我喜欢你们。我想和你们打成一片。}
{181}{}{掠夺者只接受最凶狠最强悍的家伙。你必须要嗜血、暴力、极端。我看你撑不住，你能做到吗？}
{182}{}{能。}
{183}{}{不能。}
{184}{}{那你最好离开。别再回来了。}
{185}{}{我对这些女人感到厌烦了。杀了她们。}
{186}{}{不！}
{187}{}{好。}
{188}{}{你证明了我的观点。只有掠夺者才有生存的意志！而你没有。杀了他。}
{189}{}{你证明了我的观点。只有掠夺者才有生存的意志！而你没有。杀了她。}
{190}{}{混蛋！你会为此付出代价！}
{191}{}{哈！我喜欢你的风格。有点粗糙，但管用。把你当作掠夺者的朋友吧。现在从我眼前消失。}
{192}{}{你现在想要什么？}
{193}{}{没什么。}
{194}{}{我想要一些武器和护甲。}
{195}{}{咕噜。}
{196}{}{你得自己想办法。}
{197}{}{你竟敢再出现在我面前？杀了他！}
{198}{}{你竟敢再出现在我面前？杀了她！}
{200}{}{我来跟你们一起狂欢！}
{201}{}{那就去弄些酒和女人来参加我们的派对。}
{203}{}{我愿意单挑你来换取坦迪。}
{204}{}{你不是掠夺者，你不配得到荣誉。}
{205}{}{你的贿赂不值得我浪费时间。杀了她。}
{206}{}{我们不喜欢这种人。我们这里容不下她。杀了她。}
{207}{}{哇啊！}
{208}{}{好吧，你赢了。带走那个女孩，快滚。}

{1000}{}{可汗}
{1001}{}{加尔}
{1002}{}{废城}
{1003}{}{阴影镇}
{1004}{}{枢纽}
{1005}{}{水}
{1006}{}{坦迪}
{1007}{}{沙地}
{1008}{}{芯片}

{1000}{}{就是我们，你这个走狗。}
{1101}{}{我是可汗的首领。我是废土中最令人畏惧的人。}
{1102}{}{他们在西南方。我们有时会在抢劫辛苦一天后去那里放松。}
{1103}{}{可怜的小蚂蚁社区。我可以轻易摧毁他们。}
{1104}{}{他们在南边。我们和他们做交易。主要是水和弹药，有时也交易武器。}
{1105}{}{我为什么要关心这个？}
{1106}{}{我不认识这个名字的人。}
{1107}{}{可怜的小蚂蚁社区。我可以轻易摧毁他们。}
{1108}{}{什么？}
