{100}{}{你看到了加勒特。}
{101}{}{你不应该在白天来这里。这会让赛特不高兴。晚上再来吧。}
{102}{}{哦，好吧。}
{103}{}{他应该学会自己解决问题。}
{104}{}{这不重要。重要的是我需要和他谈谈。}
{105}{}{你应该去找赛特。}
{106}{}{你获得：一把霰弹枪，10发霰弹枪子弹，4个信号弹，4瓶可乐和200美元。}
{107}{}{你获得：一把霰弹枪，10发霰弹枪子弹和100美元。}
{108}{}{你获得：4个信号弹，4瓶可乐和50美元。}
{109}{}{你最好现在离开。}
{110}{}{回头见。}
{111}{}{就这些吗？我应该得到更多，你最好给我！}
{112}{}{耶格。}
{113}{}{你需要立刻离开这里……}
{114}{}{跟我来。我会给你奖励。}
{115}{}{希望不是为了你好。赛特对不得不使用你并不太高兴。或许你应该尽快离开死城……}
{116}{}{我告诉过你离开。}
{117}{}{随便。}
{118}{}{也许吧。嗯，这个也拿去。}
{119}{}{你获得100美元。}
{120}{}{现在离开。}
{121}{}{嗯，冰箱里少了些东西。看来我们被偷了。}
{200}{}{加勒特无视了你。}
{201}{}{这是你的奖励。}
{202}{}{你获得了一大笔奖励。}
{203}{}{你获得：}
{204}{}{一把霰弹枪}
{205}{}{一些霰弹枪子弹}
{206}{}{一些信号弹}
{207}{}{一个信号弹}
{208}{}{一些可乐瓶}
{209}{}{一个可乐瓶}
