{100}{}{你看到一个来自圣子会的吟唱者}
{101}{}{主会宽恕你的罪过！加入我们，获得自由！赞美主及其仁慈！}
{102}{}{你好，朋友！愿意和我一起唱赞美歌吗？……曾经我在盲目中徘徊，行走在无情的土地上……}
{103}{}{我不想打断你的赞美诗，但我在哪里可以见到主？}
{104}{}{别辞掉你的日常工作。}
{105}{}{这里谁负责？}
{106}{}{……但现在我亲吻主的背影……}
{107}{}{快乐！快乐！我唱歌好听！}
{108}{}{他会在你最意想不到的时候和地方找到你！赞美主！赞美圣火！赞美世界！}
{109}{}{多么精彩的笑话！我以前没有幽默感，但感谢主，我现在充满了欢乐！赞美主！}
{110}{}{坐在上面的那位。坐在下面的那位。安息其中的那位。赞美主，赐予如此清晰的视野！}
{111}{}{哦，要是我也能如此幸运就好了！也许有一天主会让我亲吻他的身体部位。赞美主！赞美圣火！}
{112}{}{嗯，这不是我想要的。你最好多练习，朋友。赞美主！赞美圣火！}
{113}{}{[完成]}
