{100}{}{谢谢你。}
{101}{}{再见。}
{102}{}{你好。}
{103}{}{你获得了}
{104}{}{ 点经验值。}
{105}{}{糟糕！}
{106}{}{咔嚓！}
{107}{}{哎呀！}
{108}{}{哎哟！}
{109}{}{回头见。}
{110}{}{慢走不送。}
{111}{}{很高兴认识你。}
{112}{}{给你。}
{113}{}{还有别的吗？}
{114}{}{是的。}
{115}{}{不是。}
{116}{}{你获得了}
{117}{}{ 点小型枪械技能点。}
{118}{}{ 点大型枪械技能点。}
{119}{}{ 点能量武器技能点。}
{120}{}{ 点徒手格斗技能点。}
{121}{}{ 点近战武器技能点。}
{122}{}{ 点投掷技能点。}
{123}{}{ 点急救技能点。}
{124}{}{ 点医生技能点。}
{125}{}{ 点潜行技能点。}
{126}{}{ 点偷窃技能点。}
{127}{}{ 点开锁技能点。}
{128}{}{ 点陷阱技能点。}
{129}{}{ 点科学技能点。}
{130}{}{ 修理技能点数。}
{131}{}{ 口才技能点数。}
{132}{}{ 交易技能点数。}
{133}{}{ 赌博技能点数。}
{134}{}{ 野外生存技能点数。}
{135}{}{你获得了一个小型武器技能点。}
{136}{}{你获得了一个重型武器技能点。}
{137}{}{你获得了一个能量武器技能点。}
{138}{}{你获得了一个徒手战斗技能点。}
{139}{}{你获得了一个近战武器技能点。}
{140}{}{你获得了一个投掷技能点。}
{141}{}{你获得了一个急救技能点。}
{142}{}{你获得了一个医疗技能点。}
{143}{}{你获得了一个潜行技能点。}
{144}{}{你获得了一个偷窃技能点。}
{145}{}{你获得了一个开锁技能点。}
{146}{}{你获得了一个陷阱技能点。}
{147}{}{你获得了一个科学技能点。}
{148}{}{你获得了一个修理技能点。}
{149}{}{你获得了一个口才技能点。}
{150}{}{你获得了一个交易技能点。}
{151}{}{你获得了一个赌博技能点。}
{152}{}{你获得了一个野外生存技能点。}
{153}{}{你的力量增加了}
{154}{}{你的感知增加了}
{155}{}{你的耐力增加了}
{156}{}{你的魅力增加了}
{157}{}{你的智力增加了}
{158}{}{你的敏捷增加了}
{159}{}{你的运气增加了}
{160}{}{点数。}
{161}{}{你的力量增加了一点。}
{162}{}{你的感知增加了一点。}
{163}{}{你的耐力增加了一点。}
{164}{}{你的魅力增加了一点。}
{165}{}{你的智力增加了一点。}
{166}{}{你的敏捷增加了一点。}
{167}{}{你的运气增加了一点。}
{168}{}{谢谢你的帮助。}
{169}{}{什么忙也没帮上，谢谢。}
{170}{}{阿拉戴什怒不可遏，拒绝再与你交谈。}
{171}{}{我相信主人想要与你谈话。}
{172}{}{你将为你的亵渎付出代价！}
{173}{}{这个机器人似乎无法运作，可能是因为缺乏电力。}
{174}{}{你没有发现这个机器人有什么特别之处。}
{175}{}{这个刀锋拒绝与你交谈。}
{176}{}{手提箱被封住，无法打开。}
{177}{}{请，我们必须快点。我们没有时间交谈。}
{178}{}{只有墨菲斯有这扇门的钥匙。我现在必须离开，去告诉妮可这里发生的事情。}
{179}{}{请，我必须在他们发现我是谁之前离开这里。}
{180}{}{你没能偷到任何东西，并怀疑自己是否被发现。}
{181}{}{兄弟会成员抓住了你偷窃。}
# Mysterious Stranger messages
{182}{}{让我们开战吧！}                                # 0 {183}{}{看来你需要一些帮助。} # 1 {184}{}{我会帮助你。}                         # 0 {185}{}{我不太爱说话。}                        # 1 {186}{}{你听到广播：警告！入侵者警报。}
{187}{}{粘液减缓了你的按键响应。}
{188}{}{辐射蝎子现在被封在洞穴里。}
{189}{}{洞口引诱你深入辐射蝎子的巢穴。}

{200}{}{你看到一个严重损坏的发射场。}
{201}{}{发射器损坏得无法使用。}
{202}{}{发射器损坏得无法修复。}
{203}{}{你注意到力场损坏得足以让你穿过。}
