{100}{}{你看到面前有一个全息磁盘。}
{101}{}{小子显示：正在从磁盘下载数据。}
{102}{}{这似乎是一个包含某种娱乐内容的磁盘。}
{103}{}{磁盘损坏得太严重，无法读取任何内容。}
{104}{}{这个磁盘似乎提到另一个磁盘上的某个通行码。}
{105}{}{你看到一个小屏幕显示出一些二战电影的残片。}
{106}{}{这个磁盘似乎是空的。}
{107}{}{你丢弃了这个毫无价值的磁盘。}
