{100}{}{你想要什么？}
{101}{}{别烦我。}
{102}{}{什么？}
{103}{}{别碰我的东西。}
{104}{}{嗨。}
{105}{}{啊啊啊！}
{106}{}{咕噜！}
{107}{}{呃嗯。}
{108}{}{呃。}
{109}{}{嘿，你听说Set被干掉了吗？}
{110}{}{Set死了。Set死了。Set死了……}
{111}{}{水够大家用的。Set确保了这一点。}
{112}{}{我听说变种人被赶出城了。}
{113}{}{自从变种人离开后，这里好多了。}
{114}{}{你好。}
{200}{}{你检查了这个可怜的东西，但无法弄清是什么让它变成这样。}
{201}{}{它似乎曾经是人类，或者至少是人类的后代。你猜测身体的恶化很可能是由于酸或辐射。}
{202}{}{这个类人生物的身体似乎受到了高度辐射，但仍在运作。虽然它曾经是人类，但似乎已经退化到更具动物性的生活方式。}
{203}{}{这个类人生物的身体似乎受到了高度辐射，许多肌肉和脑组织似乎已经退化。然而，基因指标让你相信它和你一样，是从进入避难所的人类后代演化而来的。}
