{100}{}{你看到一个赌徒。}
{101}{}{啊！这是抢劫！}
{102}{}{我不想惹麻烦。}
{103}{}{他有枪！}
{104}{}{她有枪！}
{105}{}{哦，是你啊。}
{106}{}{我听说过很多关于你的坏事。真不错。}
{107}{}{你开局不太顺利，是吧？}
{108}{}{你这个可怕的人。竟然杀了那些孩子。我简直不敢相信。}
{109}{}{我听说有些赏金猎人在追你。你也把他们干掉了吗？}
{110}{}{别跟我说话。}
{111}{}{天哪，你干掉了市长，对吧？}
{112}{}{哦，以前基利安在的时候，我不喜欢这个地方。现在来这里还不错。}
{113}{}{走开。}
{114}{}{嘿，今天过得怎么样？我还不错。}
{115}{}{嘿，今晚过得怎么样？我还不错。}
{116}{}{别烦我，我正走运呢。}
{117}{}{宝贝，那些老虎机是我的。}
{118}{}{给我来点喝的，行吗，伙计？}
{119}{}{呃！这个地方真糟糕！}
{120}{}{我现在赚大钱了。}
