{100}{}{你好！我能为你做些什么？}
{101}{}{你是谁？}
{102}{}{你在做什么？}
{103}{}{好吧，把你所有的东西都给我。}
{104}{}{卢布！}
{105}{}{我是洛克斯。我是个商人。}
{106}{}{我是特伦斯。我是个交易商。}
{107}{}{我是朱利安。我是个修补匠。}
{108}{}{我是戴尔。我买卖小商品。}
{109}{}{我正在去阿迪特姆的路上，准备卖些货物。}
{110}{}{我正在去废城的路上，准备做些交易。}
{111}{}{我正在去枢纽的路上，准备交换货物。}
{112}{}{我正在去死城的路上，准备探索一番。}
{113}{}{啊！}
{114}{}{你介意我加入你们吗？}
{115}{}{当然，来吧。有个伴儿挺好的。}
{116}{}{抱歉，这个队伍已经满员了。}
{117}{}{抱歉，我觉得我不能信任你。}
