{100}{}{这个掠夺者太害怕加尔，不敢再和你说话。}
{101}{}{你看到一个强壮的沙漠掠夺者。}
{102}{}{是死手！他回来了！}
{103}{}{打扰了，死手。很抱歉打扰您。}
{104}{}{你是回来杀你的儿子的吗？}
{105}{}{哎呀！鬼啊！}
{106}{}{死人又活过来了！死手回来了！}
{107}{}{很高兴见到你。}
{108}{}{嗨。}
{109}{}{我在等加尔摧毁阴影沙镇。我想要一些战利品。}
{110}{}{欢迎，朋友。}
{111}{}{很高兴你能回来拜访。}
{112}{}{除非你想找麻烦，否则最好把那东西收起来。}
{113}{}{想一起狂欢吗？}
{114}{}{哦，挺硬气的嘛？}
{115}{}{加尔·死手爱他的战士。把那东西收起来，去找他说话。}
{116}{}{所以，你觉得自己很厉害，是吧？惹我试试，我们都能见识见识。}
{117}{}{我不喜欢你的样子。}
{118}{}{走开！}
{119}{}{你想要什么？}
{120}{}{我在找一个叫坦迪的女人。见过她吗？}
{121}{}{没什么。只是随便看看。}
{122}{}{嗯？}
{123}{}{哦。你一定是在找工作。去大房间找加尔，别打扰我们。}
{124}{}{那就去别处做。}
{125}{}{没有。我没见过她。你为什么问？}
{126}{}{没什么。只是找我的一个朋友。}
{127}{}{她的脑袋上有赏金。如果我能杀了她，我能赚不少钱。}
{128}{}{你在撒谎。她在哪儿？}
{129}{}{啊，好吧。}
{130}{}{真的吗？她长什么样子？}
{131}{}{大约六英尺高，金发。她来自阴影沙地。}
{132}{}{是的，她在这里。她在那栋大房子里。你知道，如果我们告诉加尔，他会想要分一杯羹。你可能需要考虑一下。}
{133}{}{你听起来不像是认真的。我觉得你在打什么主意。如果你说的是真的，那我就自己去拿赏金。}
{134}{}{我……我不能再说了，否则加尔会杀了我。}
{135}{}{去你的！}
{136}{}{我不喜欢你的样子。你最好离我远点。}
{137}{}{什么？走开！}
