{100}{}{你看到一个骷髅帮的成员。}
{101}{}{嘿！你以为你在干什么？！}
{102}{}{这里是骷髅帮的地盘，陌生人。你最好离开。}
{103}{}{有多余的瓶盖吗？}
{104}{}{你在看什么？}
{105}{}{滚出去。}
{106}{}{呼呼大睡}
{107}{}{今天真热啊。}
{108}{}{我饿了。}
{109}{}{我们找点事情做吧。}
{110}{}{为什么不找个人揍一顿呢？}
{111}{}{我想找点乐子。}
{112}{}{哈欠 . . .}
