{100}{}{你看到一个斯卡格。}
{101}{}{这里真不错！比我以前的地方好多了。}
{102}{}{我喜欢这里！}
{103}{}{这里空间好大。如果我有东西的话，会有很多地方可以放。}
{104}{}{我的狗在哪儿？}
{105}{}{我渴了。}
{106}{}{有吃的吗？}
{107}{}{我饿了。}
{108}{}{现在是我睡觉的时间了吗？}
{109}{}{你可以去我以前的地方。}
{110}{}{我累了，你来这里干什么？}
{111}{}{这是我的家！你走开！}
{112}{}{这是我的家！你走开！}
{113}{}{我的枕头在哪儿？}
{114}{}{我困了。}
{115}{}{别伤害我。}
{116}{}{你就是那个伤害别人的人！}
