{100}{}{你看到了一位抄写员。}
{101}{}{Vree是我的偶像。}
{102}{}{Vree真漂亮。}
{103}{}{Sophia真好。}
{104}{}{Derek很酷。}
{105}{}{宇宙会继续膨胀还是最终会崩溃回自身?}
{106}{}{我喜欢那些旧书和杂志，但它们太难找了。}
{107}{}{知识就是力量。}
{108}{}{笔比剑更强大。}
{109}{}{技术必须被保存。}
{110}{}{科学真有趣。}
{111}{}{我见过外星飞船。}
{112}{}{你知道太阳其实是一个巨大的核反应吗?}
{113}{}{你知道黑洞其实是通往另一个宇宙的入口吗?}
{114}{}{你知道氢原子有99.9843425%的空间是空的?}
{115}{}{有一天时间旅行会成为可能，我们或许可以阻止过去毁灭世界的灾难。}
{116}{}{研究是我最喜欢的事情之一。我感觉自己像是在解开一个谜团。}
{117}{}{做抄写员是最棒的。你可以研究所有旧技术并尝试开发新技术。}
{118}{}{这些终端需要改进。也许我们应该把显示屏放在这里。}
{119}{}{抱歉，我正处于可能的突破中。现在不能说话。}
{120}{}{嘿，新兵。如果你还没决定，可以考虑训练成为抄写员。}
{121}{}{我们抄写员设计所有的设备、武器和补给。这非常令人兴奋。}
{122}{}{请不要打扰我，我正在完成我的研究。}
{123}{}{那就是Vree，她也是一位抄写员。}
