{100}{}{你看到一个避难所居民。}
{101}{}{我真不敢相信你背叛了我们！}
{102}{}{叛徒！}
{103}{}{我讨厌你。你为什么还要回来？！}
{104}{}{希望你被自己的恶行噎死！}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{谢谢你拯救了我们。}
{110}{}{起初我有点不相信你能做到，但现在我信任你了。}
{111}{}{谢谢！谢谢！}
{112}{}{你是个英雄。我儿子说长大后想像你一样。我不知道该不该高兴。}
{113}{}{你是个女英雄。我女儿说长大后想像你一样。我不知道该不该高兴。}
{114}{}{你真是个好小伙！}
{115}{}{你真是个好姑娘！}
{116}{}{你确定你需要带那个进来吗？}
{117}{}{那是武器！}
{118}{}{你真的用那个对付过别人吗？}
{119}{}{你为什么觉得在这里要带武器？}
{120}{}{很高兴再次见到你。}
{121}{}{我很高兴你一切都好。}
{122}{}{在我看来你看起来挺好。那些传言一定是假的。}
{123}{}{嗨}
{124}{}{。继续保持好工作。}
{125}{}{希望外面的情况一切顺利。我们真的需要水。}
{126}{}{我们的水快用完了。这太可怕了！}
{127}{}{请快去找到那个芯片。我们需要你。}
{128}{}{我很高兴你一切都好。继续保持好工作。}
{129}{}{我不想这么说，但如果你不快点找到水芯片，我们都会死。}
{130}{}{我的小宝贝总是在半夜哭着要水喝，但我却什么也给不了她。}
{131}{}{我们是撑不下去了，对吗？}
{132}{}{水配额快要用完了。}
{133}{}{水培区已经关闭了。这意味着我们的食物供应也快耗尽了。}
{134}{}{嗯。你看起来还是人类。外面应该没有那么糟糕。}
{135}{}{你好}
{136}{}{。}
{137}{}{希望你的任务进展顺利。}
{138}{}{回头见。}
{139}{}{你最近和监督者谈过吗？}
{140}{}{监督者对你的任务状态非常担忧。}
{141}{}{你需要加快速度。我们不能承受你的失败。}
{142}{}{希望你尽力而为。}
{143}{}{现在不是休息的时候，赶快出去。}
{144}{}{这不是你该做的事，对吗？}
{145}{}{我们会死的，这都是你的错。}
{146}{}{别站在这儿，赶快出去！现在就去！}
{147}{}{如果我们死了，那就是你的错。}
{148}{}{外面的世界腐蚀了你，是不是？}
{149}{}{别烦我。}
{150}{}{我觉得你应该离我和我的家人远一点，}
{151}{}{。这样对大家都好。}
{152}{}{你应该感到羞愧。}
{153}{}{想想我以前还喜欢过你。}
{154}{}{避难所居民拒绝与你交谈。}
{155}{}{一个空洞的眼神回应了你的交谈请求。}
{156}{}{我后悔选了你去外面。}
{157}{}{水很难喝，但你的陪伴更糟。}
{158}{}{走开。离开。找到那个水芯片，你才能赎罪。}
{159}{}{希望你满意。}
{160}{}{避难所居民拒绝与你交谈。}
{161}{}{都是你造成的！可能一开始就是你弄坏了水芯片！}
{162}{}{我恨你。我真的，真的很恨你。}
{163}{}{避难所居民只是抽泣，泪如雨下。}
{164}{}{你的交谈请求只得到一个冷冷的注视。}
{165}{}{谢谢你。}
{166}{}{太晚了。改天再来吧。}
{167}{}{避难所居民正在休息。}
