{100}{}{你看到一个食尸鬼守卫。}
{101}{}{我们要带你去见赛特。我想他会想亲自和你谈谈。}
{102}{}{你不该在这里……}
{103}{}{加雷特告诉我没问题。他让我去赛特的房间帮他拿点东西。你知道在哪吗？}
{104}{}{好吧，那我就离开了。}
{105}{}{嗯？}
{106}{}{听起来不太对。你最好跟我走一趟。}
{107}{}{我不这么认为。}
{108}{}{好的。}
{109}{}{我觉得你不想去那个房间。}
{110}{}{为什么不？}
{111}{}{好吧，我不想进那个房间。那现在怎么办？}
{112}{}{我觉得你最好还是离开。}
{113}{}{我们在这里是为了确保不该进赛特房间的人不会进去。其实不是为了赛特的安全，而是为了他们的安全。还有别的事吗？}
{114}{}{嗯，你的鞋带松了。}
{115}{}{不，谢谢。}
{116}{}{我在值班，走开。}
