{100}{}{嘿！}
{101}{}{这里不准带武器！}
{102}{}{小心点！}
{103}{}{抓住他们！}
{104}{}{别鬼鬼祟祟的！}
{105}{}{这里不准偷偷摸摸的！}
{106}{}{喂，你！别再藏了，要么滚出去！}
{107}{}{什么事？}
{108}{}{嘿，我能问你几个问题吗？}
{109}{}{能给我几个瓶盖吗？}
{110}{}{算了，抱歉。}
{111}{}{嗯？}
{112}{}{我在值班，快说。}
{113}{}{不行，走开。}
{114}{}{能告诉我关于你老板的事吗？}
{115}{}{这镇上还有什么别的地方？}
{116}{}{你是傻了吗？走开。}
{117}{}{不行，去别处乞讨吧。}
{118}{}{滚开。}
{119}{}{我们这里不需要穷光蛋。}
{120}{}{Gizmo是个公正的人。工资不错，工作轻松。别惹麻烦，大家都会开心。}
{121}{}{去Skum Pit喝几杯。好酒，四点开门。现在别烦我。}
{122}{}{去Killian的店逛逛吧。他的店在东南边。现在快走。}
{123}{}{去找那些商贩聊聊。}
{124}{}{嘿，想找点乐子的话，去Crash House找Sinthia。她值得一试。}
{125}{}{不准作弊。}
{126}{}{欠债者格杀勿论。}
{127}{}{哎，我的脖子好疼。}
{128}{}{这工作真让人受不了。}
{129}{}{我爱这个地方。}
{130}{}{今晚我打算去找辛西亚。}
{131}{}{滚出去，你这个蠢货。}
{132}{}{这里禁止携带武器！}
{133}{}{喂！你！把武器收起来！}
