{100}{}{你看到赌场老板吉兹莫。}
{101}{gizmo_1}{Get your butt in here and sit down.
 We got some business to discuss.}
{102}{}{看起来这里已经够拥挤了……}
{103}{}{我已经知道了。你想要什么？}
{104}{}{什么生意？}
{105}{}{呃。}
{106}{gizmo_1b}{Get outta here, ya' idiot!}
{107}{gizmo_2}{You kiss your mother with that mouth? Show some respect.}
{108}{}{你除了吃还会干别的吗？}
{109}{}{你说得对，我很抱歉。那么我们谈正事吧。}
{110}{gizmo_4}{All right, [Gizmo snorts] here's the deal. Junktown, it
 ain't what it used to be. The only reason
 it's still here is because of my gambling establishment.  Even so,
 Killian's been breathing down my neck, and I'm starting to take it
 personal. [Gizmo snorts] And that's where you come in, slick.}
{111}{}{你想让我做什么？}
{112}{}{如果你以为我会帮你，那你真是又胖又蠢。}
{113}{gizmo_4a}{Funny.}
{114}{gizmo_5}{What I think is you're going to take him out for me, you know? No
 witnesses, just in, over, out.}
{115}{}{你为什么不派你自己的打手去？}
{116}{}{就算你给我这破地方所有的钱，我也不会为你工作。}
{117}{}{当然。我需要钱。}
{118}{}{我不这么认为。不过还是谢谢。}
{119}{}{你愿意付多少？}
{120}{gizmo_6}{I would, but there must be no connection between me and Killian's
 unfortunate demise.}
{121}{}{有道理。当然，我会做的。}
{122}{}{好吧，我会做的。}
{123}{}{真是个懦夫。怕别人不喜欢你？太晚了。}
{124}{}{你愿意付多少？}
{125}{}{绝对不可能。}
{126}{}{我不这么认为。不过还是谢谢。}
{127}{gizmo_7}{[Gizmo wheezes.] I knew you'd see it my way. As proof, I want the dog tags Killian
 wears around his neck. Ya' get them, ya' get your money. Now, just get.
 And don't cross me. I still got the kneecaps from the last one
 who tried.}
{128}{gizmo_8}{Thousand caps. No more, no less.}
{129}{}{听起来不错。我会做的。}
{130}{}{你把这叫奖励？如果我要干掉那家伙，我需要更多。}
{131}{}{差得远呢。我不想参与这笔交易。}
{132}{}{我信不过你，就算两个人能把你扔多远。算了吧，瘦子。}
{133}{gizmo_9}{[Gizmo laughs and coughs] Maybe you're right.
 I think you're worth more. 1500.}
{134}{}{这才像话。}
{135}{}{那是什么，按你体重算一美元一磅？算了吧。}
{136}{}{谢谢，但我还是不想。}
{137}{}{绝对不可能。}
{138}{gizmo_10}{Sorry you feel that way. Not as sorry as you're gonna be,
 though. Can't let word of this get out. Izo, show our
 new friend what we do with people who say no to me.}
{139}{gizmo_11}{One is okay. Two is too much. And that was two.
 Izo, get me a set of kneecaps.}
{140}{gizmo_13}{Did ya' finish the job yet?}
{141}{}{是的，确实如此。}
{142}{}{不，还没有。}
{143}{gizmo_14}{Let's see the tags.}
{144}{gizmo_15}{Oh, yeah. Oh, yeah! Izo's got your money. Oh, this is good!
 Hey, hey, uh . . . you should leave town for a while.
 You know, just in case.}
{145}{}{好吧，我走了。}
{146}{}{你别想命令我，胖子。明白了吗？}
{147}{}{如果我不呢？}
{148}{}{当然，我会走。记住你欠我一个人情。}
{149}{gizmo_16}{You don't leave town, you end up under it. You got me?}
{150}{}{好吧，好吧。我走了。}
{151}{}{谁会干掉我？你吗？你连动动你的肥屁股去拿个三明治都懒，更别说杀我了。}
{152}{}{好吧，没问题。记住你欠我一个人情。}
{153}{gizmo_17}{Then give me the dog tags?}
{154}{}{嗯……那个……我……呃，弄丢了。}
{155}{}{如果我不想给你呢？}
{156}{}{我撒谎了。我没有。}
{157}{}{我有过，但后来弄丢了。}
{158}{gizmo_18}{[Gizmo laughs.] You know, you're a crummy liar.  Now go get the tags. I don't
 want to see your face until you've offed Killian.}
{159}{gizmo_19}{No problem, I take them off your dead body.}
{160}{}{呃……其实，我有点撒谎了。我没有。}
{161}{}{是吗？你要雇人替你弯腰吗？}
{162}{}{我弄丢了。}
{163}{}{嗯，我有过，但被偷了。}
{164}{gizmo_20}{No tags, no money. You come back without the tags again and
 Izo gets creative with your anatomy. Now get out!}
{165}{gizmo_21}{What do you want? I'm a busy man.}
{166}{}{我来告诉你，你的刺客失败了。}
{167}{}{其实没什么。我现在就走。}
{168}{}{我想知道像你这么蠢的人怎么还活着。}
{169}{}{我来谈谈对基利安的刺杀企图。}
{170}{gizmo_22}{I don't know what you're talking about.}
{171}{}{当然是你。你雇人去杀基利安，但他搞砸了。}
{172}{}{你不记得雇人去杀基利安了吗，你这个蠢货？}
{173}{}{好吧，让我们假设一个情况……}
{174}{}{你是个骗子！}
{175}{}{你说得对。再见。}
{176}{gizmo_23}{I don't know who you are, but I don't take kindly to strangers
 walking into my office and accusing me of things they know nothing about.}
{177}{}{啊，但你错过了重点，Gizmo。我不是来指责的。我是来帮你的。}
{178}{}{我全都知道。快招吧！}
{179}{}{你说得对。我走了。}
{180}{gizmo_24}{Really? [Gizmo chuckles.] He's gonna help me?
 What kinda help are we talking about?}
{181}{}{简单。你派人去杀基利安。他失败了。你需要一个能更好完成任务的人……}
{182}{}{没什么。忘了我提过这事。}
{183}{gizmo_25}{And let me guess. You're that someone?}
{184}{}{很好……当然是有代价的。}
{185}{}{我能比你吐口水还快地干掉他。}
{186}{gizmo_26}{Well, how can I trust you?}
{187}{}{我来了。你需要一个外地人来替你干脏活，对吧？}
{188}{}{你不能……我是说你可以……我是说……}
{189}{}{因为我见多识广，我以前杀过人。}
{190}{gizmo_27}{Hmm . . . all right. We can do this. But you work for me, you better know
 that nobody ever double-crosses Gizmo and lives to talk about it. You got me?}
{191}{}{哦，我可以骗过你……只是没人能绕过你。}
{192}{}{当然。但首先我需要知道你为什么想让他死。}
{193}{gizmo_28}{Huh. That's easy. I want him dead because he cramps my business. So,
 will you do him for me?}
{194}{}{这就是我来的原因。他会在日落前死掉。}
{195}{}{当然，这是个工作。}
{196}{}{你能再说一遍吗……这次对着我的口袋？}
{197}{}{嗯，呃……不，我不能。}
{198}{gizmo_29}{Good. Return with the dog tags he wears around his neck as proof.
 And we never had this conversation, you
 don't mention this to anyone. No one double crosses me. No one.}
{199}{gizmo_30}{You're either real stupid . . . or a real stupid spy. Doesn't matter,
 because now Izo's gonna make you real dead.}
{200}{gizmo_32}{I don't like people who waste my time. Don't come back again soon!}
{201}{gizmo_33}{Such as?}
{202}{}{好吧，假设你试图杀掉基利安，而你的刺客失败了。这意味着你需要一个新的刺客来完成任务。}
{203}{}{嗯？哦，算了。}
{204}{gizmo_34}{You know, [Gizmo sighs] I don't like it when people insult me
 in my own place. Izo, escort our guest out . . . through the window.}
{205}{gizmo_35}{You're back. You know, I had to hire someone else to do your work.
 That didn't make me happy. In fact, Izo will show you just how unhappy I am. I hope
 you had a nice day. It was your last.}
{206}{gizmo36a}{[Gizmo grunts.] Killian's the mayor of this town.
 Thinks he knows everything . . . well, we'll just see how much he knows, won't we?}
{207}{gizmo_37}{[Gizmo coughs.] That's me, stupid. I run the . . . gambling establishment here.}
{208}{gizmo_38}{That's Killian's place the north end of town. He sells crap.}
{209}{gizmo_39}{Well, most people gamble here. You ask stupid questions.}
{210}{gizmo_42}{Wouldn't you like to know?}
{211}{gizmo_43}{You don't need to concern yourself with that.}
{212}{gizmo_44}{[Gizmo sniffs.] I uh . . . I don't feel like talking about that right now.}
{213}{gizmo45m}{Hey, what the hell do you think you're doing? Izo, tear his arms off!}
{214}{gizmo45f}{Hey, what the hell do you think you're doing? Izo, tear off her arms!}
{215}{gizmo_47}{What, are you deaf? I said . . .}
{216}{gizmo_48}{Hey, I won't repeat myself again!}
{217}{}{你因击败吉兹莫获得600点经验值。愿这混蛋碎尸万段。}
{218}{}{这是你见过的最肥胖的人。}
{219}{}{你知道吗，我在你上次来之后发现了一些非常有趣的东西。如果有一件事比糟糕的意大利辣香肠披萨更让我受不了，那就是告密者。伙计们！}
{220}{}{事情就这样了，基利安。好吧，我从来受不了你的臭味，现在我要结束它！}
{221}{}{我解决了基利安。听说你可能会欣赏这一点。}
{222}{}{哦，真的吗？}
{223}{}{嘿，好吧，如果你不想让他死，没关系。我只是想帮忙。}
{224}{}{我在想也许是背后捅刀或者一枪爆头。}
{225}{}{明白了。你想让他死的原因是什么？}
{226}{gizmo_24}{Really? [Gizmo chuckles.] She's gonna help me?
 What kinda help are we talking about?}

# Gizmo's Tell-Me-Abouts generic responses
{980}{gizmo_42}{Wouldn't you like to know?}
{981}{gizmo_43}{You don't need to concern yourself with that.}

#
# Gizmo's Tell-Me-Abouts
#

{1000}{}{基利安}
{1001}{}{吉兹莫}
{1002}{}{黑水}
{1003}{}{吉兹莫的}
{1004}{}{黑水}
{1005}{}{吉兹莫的}
{1006}{}{赌场}
{1007}{}{废城}

{1100}{gizmo36a}{[Gizmo grunts.] Killian's the mayor of this town.
 Thinks he knows everything . . . well, [Gizmo laughs] we'll just see how much he knows, won't we?}
{1101}{gizmo_37}{[Gizmo coughs.] That's me, stupid. I run the . . . gambling establishment here.}
{1102}{gizmo_38}{That's Killian's place the north end of town. He sells crap.}
{1103}{gizmo_39}{Well, most people gamble here. You ask stupid questions.}
{1104}{gizmo36a}{[Gizmo grunts.] Killian's the mayor of this town.
 Thinks he knows everything . . . well, [Gizmo laughs] we'll just see how much he knows, won't we?}
{1105}{gizmo_39}{Well, most people gamble here. You ask stupid questions.}
{1106}{gizmo_39}{Well, most people gamble here. You ask stupid questions.}
{1107}{gizmo_39}{Well, most people gamble here. You ask stupid questions.}
