{100}{}{你看到一扇带有蓝色标记的电梯门。}
{101}{}{你被安全系统电击，但没有受伤。也许你应该尝试用某种东西来绕过安全系统。}
{102}{}{你被安全系统电击，受到一点伤害。也许你应该尝试用某种东西来绕过安全系统。}
{103}{}{你被安全系统电击，受到}
{104}{}{点伤害。也许你应该尝试用某种东西来绕过安全系统。}
{105}{}{你解除门上的安全系统。}
{106}{}{这个物品对门没有效果。}
