{100}{}{你看到一个地下的食尸鬼。}
{101}{}{我们只想被留下来不被打扰。}
{102}{}{赛特是个无能的傻瓜，他会害死我们的。}
{103}{}{超级变种人总有一天会杀了我们，而赛特却无所作为。}
{104}{}{我们藏在这里，请不要告诉任何人我们的所在。}
{105}{}{我不喜欢你的样子。}
{106}{}{走开，别打扰我们。}
{107}{}{我听说过关于你的坏话。这些都是真的吗？}
