{100}{}{你看到圭多。}
{101}{}{我说你就用蛮力吧。打碎一个膝盖用不了多少力气。}
{102}{}{谁在乎什么震撼效果？我们不是艺术家，我们是专业人士。呃，莱昂，有人想跟我们说话。我们不是应该在这种情况下干掉他们吗？}
{103}{}{我说你就用蛮力吧。打碎一个膝盖用不了多少力气。}
{104}{}{我拿钱不是来聊天的。}
{105}{}{谁在乎什么震撼效果？我们不是艺术家，我们是专业人士。呃，莱昂，有人想跟我们说话。我们不是应该在这种情况下干掉他们吗？}
{106}{}{我说你就用蛮力吧。打碎一个膝盖用不了多少力气。}
{107}{}{谁在乎什么震撼效果？我们不是艺术家，我们是专业人士。呃，莱昂，有人想跟我们说话。我们不是应该在这种情况下干掉他们吗？}
