{100}{}{嘿！你以为你在做什么？！}
{101}{}{嘿，你有核子可乐吗？}
{102}{}{生意不错。}
{103}{}{加布里尔是个好老板。}
{104}{}{天气不错，是吧？}
{105}{}{如果你在找装备，去找扎克谈谈。}
{106}{}{扎克卖武器。}
{107}{}{把你的武器收好。}
{108}{}{别耍花招。}
{109}{}{我们可以在这里抵挡一支军队。}
{110}{}{有个家伙曾经掉进护城河里。真是个可怕的死法。}
{111}{}{该死的护城河，烟雾让我眼睛疼。}
{112}{}{我讨厌这份工作。}
{113}{}{别挡我的路！}
{114}{}{别烦我。}
{115}{}{你看不出我正忙着吗？}
{116}{}{你看到一个典型的枪械行者。}
