{100}{}{抱歉，今天没有拳击比赛。}
{101}{}{嗯。}
{102}{}{呃，好吧。}
{103}{}{下一场比赛是什么时候？}
{104}{}{你可以试着去找Gizmo报名。我听说他总是在找新的选手上场。}
{105}{}{明天再来试试。Saul明天会比赛。}
{106}{}{你刚错过了。过几天再来。Saul每三天比赛一次。}
{107}{}{谢谢。}
{108}{}{Saul是谁？}
{109}{}{Saul是本地的冠军，也是Gizmo目前的宠儿。}
{110}{}{嘿，今天没有拳击比赛。}
{111}{}{ 明天再来试试。}
{112}{}{ 后天再来试试。}
{113}{}{那么！想下注吗？}
{114}{}{我有更好的事情要用我的钱。再见。}
{115}{}{赔率是多少？}
{116}{}{不，谢谢。不过我可以问几个问题吗？}
{117}{}{}
{118}{}{抱歉，今天的比赛已经结束了。}
{119}{}{哦，那算了。}
{120}{}{你想赌谁，Saul还是挑战者？赔率是Saul胜。下注25瓶盖；如果赌Saul赢，你赢50，如果赌挑战者赢，你赢100！}
{121}{}{我赌Saul。}
{122}{}{我赌挑战者。}
{123}{}{好吧，我想也是。}
{124}{}{拳击手是谁？}
{125}{}{谁负责这些比赛？}
{126}{}{呃，算了。}
{127}{}{抱歉，我没时间。也许以后吧。}
{128}{}{Saul，Junktown最快的拳头！他是男性肌肉的奇迹！一个充满力量的拳击手！}
{129}{}{他也是个好人。}
{130}{}{嗯，是的。那么，谁负责这些比赛？}
{131}{}{谢谢。回头见。}
{132}{}{赌场老板吉佐莫雇佣了索尔。他偶尔喜欢看一两场比赛，但主要是因为这能赚很多钱——人们会在打斗上下注很多。而且没人会死，不像据说在中心城有的那些死亡比赛。}
{133}{}{死亡比赛？}
{134}{}{谢谢。}
{135}{}{嗯，这只是个传言。但他们说那里有个地下搏斗场，你可以花钱看人打生死斗。这可不是我喜欢的比赛。}
{136}{}{嗯，谢谢。}
{137}{}{嘿，你在干什么？}
{138}{}{呃，没什么。}
{139}{}{你想找麻烦吗，废物？}
{140}{}{请别这样。}
{141}{}{呃，不。算了。忘了我说的。}
{142}{}{哦，看起来你赢了！这是你的瓶盖。}
{143}{}{等你有足够的瓶盖再来下注！}
{144}{}{你想在这里等到比赛在2:00开始吗？}
{145}{}{当然，没问题。}
{146}{}{不，我有事要做。稍后再来。}
{147}{}{好的，但如果你错过了比赛，你的赌注就作废了！}
{148}{}{比赛开始！}
{149}{}{比赛进行中，请不要打扰我。}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{150}{}{好吧，你不可能每次都赢，朋友。下次好运。}
{151}{}{好吧，你不可能每次都赢，朋友。下次好运。}

{152}{}{抱歉，每场比赛只允许下注一次。}
