{100}{}{你看到格温，一个沙漠强盗。}
{101}{}{我是格温，是加尔的顾问之一。你是谁？}
{102}{}{我是}
{103}{}{。你在这里做什么？}
{104}{}{我没什么特别的。你能告诉我关于你们营地的事吗？}
{105}{}{嗯？}
{106}{}{我是那个会让你心动的人，亲爱的。}
{107}{}{作为顾问，我确保没有小混混给加尔惹麻烦。}
{108}{}{你是怎么做到的？}
{109}{}{你和哪支军队？}
{110}{}{我怀疑你能阻止任何人。}
{111}{}{看起来所有的小混混都住在这里。}
{112}{}{哼。如果你没什么特别的，那我就不浪费时间跟你说话了。走开。}
{113}{}{我负责让像你这样的白痴别去打扰加尔。走开！}
{114}{}{我有办法让某些不受欢迎的人消失。}
{115}{}{看来我错了。你可能确实能做好你的工作。再见。}
{116}{}{证明给我看！}
{117}{}{去死吧！}
{118}{}{好久没打一场好架了。可惜你会输。看看我的本事吧！}
{119}{}{你会后悔这句话的。这将是你的最后一句话！}
{120}{}{如果这就是你能做到的最好，那我杀了你就是为世界除害。}
{121}{}{我和这支军队！}
{122}{}{你惹恼我了。离开这里，否则我会真的生气。}
