{100}{}{你看到一个兄弟会守卫。}
{101}{}{保持警惕，新兵！}
{102}{}{看起来不错。继续保持。}
{103}{}{你好，新兵，一切都很安全。}
{104}{}{抱歉，我不该和任何人说话。你知道规矩的。}
{105}{}{如果你有任何问题，可以去找塔鲁斯或马克森。}
{106}{}{如果你有技术问题，白天可以去图书馆找芙蕾。}
{107}{}{罗姆布斯是我的偶像。}
{108}{}{我真希望现在在训练，这守卫工作真是浪费时间。}
{109}{}{芙蕾是我的偶像。}
{110}{}{你好，兄弟。}
{111}{}{。}
{200}{}{只有抄写员和骑士才能进入这个房间。}
{201}{}{你被警告过。现在你将被处理。}
{202}{}{抱歉，只有兄弟会成员可以进入这里。}
