{100}{}{你看到哈罗德。}
{101}{HROLD0}{
Spare change, old friend, old pal?  Can you help a poor mutant down on his luck? [Cough]}
{102}{}{给你25美元，祝你好运。}
{103}{}{那5美元怎么样。}
{104}{}{抱歉，我身上没带钱。}
{105}{}{离我远点！}
{106}{}{呃？}
{107}{HROLD1}{
Geez. You're worse off than I am, friend. Luck to you.}
{108}{HROLD2}{
Oh, kind of ya, friend. Very kind. You know, if I could clear the gunk out of there, you, just might find a tear in Old Harold's eye.}
{109}{}{为什么？}
{110}{}{不客气。}
{111}{HROLD3}{
[Cough] Rest of the Hubbers' been picking on me like a bad booger since I came back to town.  I can't leave, though.  When the deals are done [wheez] it's still my home.}
{112}{}{你发生了什么事？}
{113}{}{胡贝尔人是谁？}
{114}{}{希望情况会好转，再见。}
{115}{HROLD4}{
Well, after the Great War, my Vault was one of the first to open. [Takes a deep breath] Whew.  Long time.}
{116}{}{告诉我更多关于那些日子的事。}
{117}{}{不，我是问是什么改变了你？}
{118}{HROLD5}{
All started with the sirens.  I was young, but ohh, I do remember that.  Lotta terrible years followed.  And I remember walking outta the Vault late one morning.}
{119}{}{那你后来做了什么？}
{120}{}{你的避难所在哪里？}
{121}{}{你意识到这让你有多老了吗？}
{122}{HROLD6}{
You know, [cough] I'm not real sure anymore.  West, I think.  Uh wait - east?  Ooh I don't know.  [Hacking cough]}
{123}{}{那你后来做了什么？}
{124}{HROLD7}{
Well, I was a trader.  Did pretty good making a circuit between survivors.  Lost a lotta good people, though. [Coughs]}
{125}{}{怎么做到的？}
{126}{HROLD8}{
Gangers got'em.  Scavengers attacking the caravans.  And mutants, son of a dog, if they weren't springing up like rabbits with a mission. [cough] Had to have an army of guards with, just to do a deal.}
{127}{}{守卫没有帮忙吗？}
{128}{}{变种人是从哪里来的？}
{129}{HROLD9}{
Course they helped, ya bonehead!  Just too damn many to handle!}
{130}{}{你是怎么在变种人攻击中幸存下来的？}
{131}{HROLD9A}{
Didn't.  Got killed. [Laughing cough] Love that joke.}
{132}{}{呃，是的。}
{133}{HROLD10}{
Everywhere!  Hell, seemed like you couldn't fart without hitting one.  But mostly in the northwest.}
{134}{}{你探索过那个区域吗？}
{135}{}{你为什么不直接避开那个区域？}
{136}{}{你放了个屁往西北方向？}
{137}{hrold10a}{[Laughs] Pretty good...Noo...}
{138}{HROLD11}{
We mounted an expedition.  God, Richard.  Richard Grey.  Led a small group of us up there.}
{139}{}{理查德·格雷？}
{140}{}{你具体去了哪里？}
{141}{HROLD12}{
Needed to see what was there.  Maybe stop whatever was churnin them boogers out.  We thought we were prepared.  Were we wrong.}
{142}{}{你做了什么？}
{143}{HROLD13}{
I can't remember the route or anything.  But I am damn sure it was northwest, though...I think.}
{144}{}{这个故事有更简短的版本吗？}
{145}{}{那你的领袖呢？}
{146}{HROLD14}{
Richard Grey was a doctor.  Little older than me, and friend was he smart.  He found the source.}
{147}{}{那是什么?}
{148}{HROLD15}{
I like telling it my way.  Short version will cost you 25 extra, friend.  Which will it be?}
{149}{}{好吧，长的就长的吧。}
{150}{}{短的。}
{151}{}{短的，但我没钱。}
{152}{}{都不要，你这老家伙。}
{153}{HROLD16}{
Well, you seem like an okay sort.  I'll speed it up a bit.}
{154}{}{谢谢。}
{155}{hrold16a}{Lying to a poor old mutant.  What's the world coming to? [cough]}
{156}{hrold17}{Little light on funds, huh?}
{157}{hrold17a}{My way or walk away.  Your choice, friend.}
{158}{}{走路。}
{159}{}{好的，长的就长的吧。}
{160}{HROLD18}{
Some sort of old military base.  We lost a lotta folks getting in there.}
{161}{}{你怎么知道是这个基地引起的?}
{162}{}{你们遇到了什么麻烦?}
{163}{HROLD19}{
Robots and such.  Lot of'em.  Damn surprised they was still running after all this time, what with the war and all.  Whooa boy they tore us a good one.}
{164}{}{你们越过机器人后做了什么?}
{165}{HROLD20}{
Because it was like someone went bargain shopping at mutantland!  Geez!  Cheaper by the dozens!  Can't figure any other reason except that being the factory.}
{166}{}{你仔细检查过这个基地吗?}
{167}{HROLD21}{
We got pretty far inside.  Wasn't a lot of us left by then.  Grey, me and couple of others.}
{168}{}{然后呢?}
{169}{HROLD22}{
One of them robots got Francine.  Mark was wounded, sent him back to the surface.  Then it was just me and Grey.}
{170}{}{马克后来怎么样了?}
{171}{}{那后来发生了什么?}
{172}{HROLD23}{
To this day, I don't know.  He never made it back here, and...well I...couldn't face the wasteland again, so I...I never looked.}
{173}{}{你和格雷呢?}
{174}{HROLD24}{
We made it to some sort of central core, like a plant of some sort.  That's when it happened.}
{175}{}{什么?}
{176}{HROLD25}{
A robot crane crashed into us.  Last I saw of Grey, he was flying through the air in-into some sort of acid bath.  I was in bad shape and...well I passed out.}
{177}{}{你是怎么活下来的?}
{178}{}{你再也没见过格雷吗?}
{179}{hrold25a}{Didn't.  Got killed...[Laughs then coughs] God, I love that joke.}
{180}{}{是啊，我能看出来。}
{181}{HROLD26}{
Well, I have no idea.  Woke up in the wasteland, barely hanging on.  Got lucky and some traders I knew found me days later.  Good thing, since I was already changing.  They brought me here, and here I've been since.}
{182}{}{你是怎么变异的?}
{183}{}{真是个精彩的故事。谢谢。}
{184}{hrold26a}{Well...Thanks for letting me tell it.}
{185}{}{这就是简短版吗?}
{186}{hrold26a}{Well . . . thanks for letting me tell it.}
{187}{hrold26b}{For me it was.}
{188}{HROLD27}{
No, you idiot!  I just said I never saw him again, didn't I?}
{189}{}{你是怎么活下来的?}
{190}{HROLD28}{
All's I know, is it was something inside that base.}
{191}{}{你觉得可能是辐射吗?}
{192}{}{抱歉，真是个不幸的遭遇。谢谢你的故事。}
{193}{HROLD29}{
How the hell should I know?  Grey would've known if anybody could. [sigh] Anyway, that's how the deal went down.}
{194}{}{谢谢你的故事。}
{195}{HROLD30}{
Yeah, about a century or two in dog years.}
{196}{}{什么?}
{197}{HROLD31}{
Nevermind, that was from my time.  I'm cranky, old and I've been that way ever since I changed.}
{198}{}{在这事发生之前你是做什么的?}
{199}{HROLD32}{
Well, I got mutated.  Sure wasn't born this ugly.  Happened when we tried to find out where all the mutants were coming from.}
{200}{}{发生了什么?}
{201}{HROLD33}{
It's in the past.  Probably should stay that way.}
{202}{}{请告诉我发生了什么，这可能对我有帮助。}
{203}{}{随你的便。}
{204}{HROLD34}{
Well, if you put it that way.  I guess it couldn't hurt.}
{205}{}{谢谢。}
{206}{HROLD35}{
No, no.  It's too painful, even now.  Thanks for the help, friend.  Good luck to you.}
{207}{HROLD36}{
You're in the Hub, right?  People who live in the Hub?  Hubbers.  Get it? [cough] Sheesh!  Thanks for the help and good luck...think you're gonna need it.}
{208}{HROLD37}{
You're as bad as the rest of them. [Wheezing cough]}
{209}{HROLD38}{
Oh well, thanks anyway. [cough]}
{210}{HROLD39}{
Hey, can you help me out, friend?}
{211}{}{给你$25。}
{212}{}{拿去$5。}
{213}{}{别烦我。}
{214}{}{呃？}
{215}{HROLD40}{
Hey, 'preciate it!  Gotta admit, when I first saw you, [cough] I figured you might hassle me.}
{216}{}{你为什么这么说？}
{217}{}{不，不是我！祝你好运。}
{218}{HROLD41}{
Oh, hey, it's you again.}
{219}{}{这里有$20，如果你需要的话。}
{220}{}{嗨。}
{221}{}{呃？}
{222}{hrold42}{Just putting me on, huh?}
{223}{HROLD43}{
Anything I can do for you?}
{224}{}{最近听到什么好消息了吗？}
{225}{}{我需要关于死亡爪的信息，我听说你是专家。}
{226}{}{你的故事是什么？}
{227}{}{没有}
{228}{hrold43a}{The whole thing?  Well...}
{229}{HROLD44}{
Oooh, well thanks.  Hope it wasn't too much of a strain. [coughs]}
{230}{HROLD45}{Oooh, that thing.  Friend, that is nightmare city.  Why the hell you asking about that?}
{231}{}{我要去干掉它。}
{232}{}{如果它追上我，我想知道该怎么办。}
{233}{HROLD47}{Okay.  Well, it's like a damn big man, is what it is.  Got spikes and claws that can cut through the heaviest armor.  But don't let the size fool ya, it's quick.}
{234}{}{有什么弱点吗？}
{235}{HROLD49}{Well, from what I've heard, maybe whack it in the head?  I'd try the eyes.  'Course, there's a problem there.}
{236}{}{什么样的问题？}
{237}{HROLD50}{You can't look at 'em!  It is said the Death Claw can hypnotize just by lookin'.  Then it walks up and "boom", you're et!}
{238}{}{太好了，谢谢。}
{239}{HROLD51}{Good luck to you...you're gonna need it.}
{240}{}{可能吧。}
{241}{HROLD52}{You don't want to know about the Death Claw, and I ain't gonna be the one to tell ya.}
{242}{HROLD53}{Well, heard one of Decker's men has somebody from the Brotherhood of Steel trapped in Old Town.}
{243}{}{谢谢。}
{244}{HROLD54}{I don't believe this one, but some say an army of mutants is on the way. [cough]}
{245}{}{谢谢。}
{246}{HROLD55}{Leave me alone. [cough]}
{247}{}{我想和你谈谈。}
{248}{}{给你一些钱。}
{249}{HROLD56}{Well, I don't wanta talk to you.  Go away!}
{250}{HROLD57}{Don't want your money.  Go away. [cough]}
{251}{hrold200}{As much as I love trading, I don't have anything to exchange. [cough]}
{252}{hrold201}{I need to sleep for a while.  I'm kinda tired.}
{253}{hrold202}{You might want to be more careful. [cough] I've heard that you've wasted several people recently.}
{254}{hrold203}{Umm...Decker's looking for you.  He wants to talk. [cough]}
{255}{hrold204}{All I got is clothes and freedom, and the latter's debatable.}
{256}{hrold300}{Brilliant guy.  A doctor and philosopher.  Long ago he lead the expedition where I got changed into a mutant.}
{257}{hrold301}{Who?  Is he some sort of sex therapist?  I could use one, you know.}
{258}{hrold302}{Mutants.  Doesn't matter what they call themselves.}
{259}{hrold303}{Oh, him.  He leads the Thieves Circle.  Thinks he's Robin Hood. [cough] He's alright, I guess.}
{260}{hrold304}{I've seen religions come and religions go, and I hope this one goes.  Soon.}
{261}{hrold305}{Yeah, I came from a Vault.  Too many people, not enough food and water.  But you wouldn't know anything about that, would you?}
{262}{hrold306}{Horrible.  The world just went insane.  Long ago, but I'll never forget it.  Never.}
{263}{hrold307}{[Cough] Trouble.  Nothing but trouble.}
{264}{hrold400}{Well, like I said...}
{265}{}{没事，谢谢。}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{266}{HROLD0}{Spare change, old friend, old pal? Can you help a poor mutant
 down on his luck? [Cough]}
{267}{HROLD0}{Spare change, old friend, old pal? Can you help a poor mutant
 down on his luck? [Cough]}
{268}{HROLD2}{Oh, kind of ya, friend. Very kind. You know, if I could
 clear the gunk out of there, you, just might find a tear in Old Harold's eye.}
{269}{HROLD2}{Oh, kind of ya, friend. Very kind. You know, if I could
 clear the gunk out of there, you, just might find a tear in Old Harold's eye.}
{270}{HROLD35}{No, no. It's too painful, even now. Thanks for the help, friend.
 Good luck to you.}
{271}{HROLD35}{No, no. It's too painful, even now. Thanks for the help, friend.
 Good luck to you.}
{272}{HROLD39}{Hey, can you help me out, friend?}
{273}{HROLD39}{Hey, can you help me out, friend?}

#
# Harold's Tell-Me-Abouts
#


{1000}{}{理查德}
{1001}{}{主宰}
{1002}{}{食尸鬼}
{1003}{}{洛克斯利}
{1004}{}{大教堂}
{1005}{}{避难所}
{1006}{}{战争}
{1007}{}{德克}
{1008}{}{格雷}

{1100}{hrold300}{Brilliant guy.  A doctor and philosopher.  Long ago he lead the expedition where I got changed into a mutant.}
{1101}{hrold301}{Who?  Is he some sort of sex therapist?  I could use one, you know.}
{1102}{hrold302}{Mutants.  Doesn't matter what they call themselves.}
{1103}{hrold303}{Oh, him.  He leads the Thieves Circle.  Thinks he's Robin Hood. [cough] He's alright, I guess.}
{1104}{hrold304}{I've seen religions come and religions go, and I hope this one goes.  Soon.}
{1105}{hrold305}{Yeah, I came from a Vault.  Too many people, not enough food and water.  But you wouldn't know anything about that, would you?}
{1106}{hrold306}{Horrible.  The world just went insane.  Long ago, but I'll never forget it.  Never.}
{1107}{hrold307}{[Cough] Trouble.  Nothing but trouble.}
{1108}{hrold300}{Brilliant guy.  A doctor and philosopher.  Long ago he lead the expedition where I got changed into a mutant.}
