{100}{}{你看到面前是一个低赌注的骰子桌。玩一次需要40美元。}
{101}{}{你掷出了7点。你赢了！！}
{102}{}{你掷出了一对蛇眼。你输了。}
{103}{}{你掷出了}
{104}{}{！你赢了！！}
{105}{}{你掷出了}
{106}{}{。你输了。}
{107}{}{你掷出了}
{108}{}{，在掷出你的点数之前。你输了。}
{109}{}{你掷出了你的点数。你赢了。}
{110}{}{你掷出了}
{111}{}{。这是你的点数。继续掷骰。}
{112}{}{你因杀死荷官获得70点经验值。}
