{100}{}{你看到一个钢铁兄弟会的长老。}
{101}{}{你好，见习者。我需要和你谈谈。（他示意你靠近。）}
{102}{}{关于什么？}
{103}{}{我现在没时间。}
{104}{}{嗯？}
{105}{}{有件紧急的事情需要你帮忙。是关于马克森的。我们几乎可以确定他已经失去理智了。他一直在胡言乱语，说北方集结了一支军队。}
{106}{}{我不愿意派我们的部队去可能有辐射的区域，除非我有绝对的证据证明这支“军队”存在。}
{107}{}{我需要一个不是老人的朋友的人。我需要一个诚实的报告。你愿意去北方地区调查吗？}
{108}{}{我愿意。}
{109}{}{我现在不能去。我还有其他事情要处理。}
{110}{}{我已经看到北方有一个由变种人军队控制的基地。}
{111}{}{很好。如果你还没和马克森谈过，先去找他。调查完北方地区后再向我报告。之后，我们会决定如何处理马克森。}
{112}{}{祝我好运。}
{113}{}{你探索完北方地区了吗？}
{114}{}{是的。}
{115}{}{没有。}
{116}{}{你有什么报告？}
{117}{}{我发现一个由重武器变种人把守的基地。情况很糟糕。}
{118}{}{我不这么认为。你离开的时间不长。现在，回去继续调查，直到你有完整的报告再回来。}
{119}{}{是，长官。}
{120}{}{我会通知长老们。我们会等待马克森的指示。去把你发现的情况告诉他。谢谢你的帮助，见习者。}
{121}{}{不客气。}
{122}{}{那你就抽时间听我说。}
{123}{}{我在听。}
{124}{}{去死吧，老头。}
{125}{}{算了，我有更重要的事情要做。}
{126}{}{我明白。如果你去那个区域发现了什么，请务必告诉我。}
{127}{}{如果我在北方发现任何类似军队的东西，我会告诉你。}
{128}{}{干得好，解决了那些变种人。我们已经听说你摧毁了他们的生产设施。感谢你帮我们解决了这个问题。}
{129}{}{没问题。}
{130}{}{呃？什么叫呃？这是什么回答？马上离开！}
{131}{}{如果由我决定，你早就被赶出去了。}
{132}{}{我没什么好对你说的。}
{133}{}{你应该学会尊重。}
{134}{}{会议现在开始。所有长老都已到场，并同意听取兄弟}
{135}{}{的陈述。我们将决定采取何种行动。兄弟}
{136}{}{，告诉我们你在北方看到了什么。}
{137}{}{在我的探索中，我发现一个被变种人使用的军事设施。那里戒备森严，定期巡逻。}
{138}{}{诺法？}
{139}{}{那些变种人长什么样？}
{140}{}{他们是大型类人形生物。肌肉质量远超普通人类。似乎有几队有组织的部队在守卫大门。}
{141}{}{他们很大，呈绿色，并携带武器。}
{142}{}{如你所知，我们的首席抄写员弗里曾对一种与你描述的生物非常相似的生物进行过尸检。你认为这些是同一种生物吗？}
{143}{}{是的。对这种生物的描述几乎完全一致。}
{144}{}{你认为这些“变种人”会构成什么威胁？}
{145}{}{正如兄弟会在为战斗做准备，这支“变种人大军”也在准备一些大动作。}
{146}{}{坦白说，你的报告并没有向我们展示他们对我们构成威胁的证据。你能提供什么证明他们有敌意的证据？}
{147}{}{他们已经入侵了墓园城。他们不会就此止步。}
{148}{}{他们正在集结一支重装军队。他们绝不会只是游行展示。他们打算使用这支军队。}
{149}{}{那么，根据他们的这些行动，他们最终可能会来到这里？}
{150}{}{他们可能已经在来的路上了。兄弟会是他们唯一可能遇到的真正对手。}
{151}{}{我不认为这表明敌意。他们可能只是为了防御攻击。即使是我们也要应对偶尔的袭击。}
{152}{}{如果他们攻击，绝不会像你们偶尔遇到的掠夺者袭击。这将是一场屠杀。}
{153}{}{既然他们来自那个旧军事设施，我想他们的武器可能与你们的相当。}
{154}{}{你有什么建议？对他们的军事基地进行先发制人的打击？}
{155}{}{是的。但我不想让他们知道我们要去。一支小队更有可能在不被发现的情况下进入他们的防线。}
{156}{}{这只能解决部分问题。他们由一支来自骨园大教堂的队伍领导。}
{157}{}{就这样吧。我会选派三名骑士与你在军事基地会合，协助你进入。长老们，谢谢你们的时间。祝你好运，见习者。}
{158}{}{如果他们由骨园大教堂的一支队伍领导，那么他们在那边也可能有一支小型军队。}
{159}{}{如果我们在北方消灭他们，那就会让我们的南方侧翼暴露。我只能在这次行动中抽调少数人手。}
{160}{}{给我派几个骑士去摧毁他们在北方的基地。}
{161}{}{给我派几个骑士去摧毁他们在南方的基地。}
{162}{}{就这样吧。我会派我选定的两名骑士在墓园大教堂与你会合。长老们，谢谢你们的时间。祝你好运，新兵。}
{163}{}{就这样吧。我会派我选定的三名骑士在军事基地与你会合，帮助你进入。长老们，谢谢你们的时间。祝你好运，新兵。}
{164}{}{显然我们犯了个错误。长老们，很抱歉浪费了你们的时间。有人能把这个精神畸形带走吗？}
{165}{}{我正忙于制定防御策略。}
{166}{}{你获得了}
{167}{}{ 经验值，因为说服了兄弟会提供帮助。}
