# Guards are all Male. They are akin to mercenaries. brief of words and very aburpt.
# they have a general attitude of don't bother me.

{100}{}{你看到一个海塔卫兵。}
{101}{}{你最好离开。达伦·海塔不接待访客。}
{102}{}{我们不欢迎你。}
{103}{}{离开！}
{104}{}{你不被允许进入这里。}
{105}{}{走开，否则你会后悔的。}
{106}{}{这房子不欢迎你这种人。}
# "You are not permitted to enter the house."

{107}{}{什么  打他们！}
{108}{}{你来这里是个大错误！}
{109}{}{你在这里干什么？你死定了。}
# "You're dead meat" == "i'm going to kill you"

{110}{}{嗯，看起来不错。}
# refering to food

{111}{}{我闻到的是布拉明肉吗？}
# Brahmin is an animal akin to a 2 headed cow. consider Male

{112}{}{快给我注射！}
# referring to getting more alcohol

{113}{}{冰箱里有什么吗？}
# fridge == refridgerator

{114}{}{还要多久？}
# referring to dinner

{115}{}{我饿了。}
{116}{}{快好了吗？}
# referring to dinner.

{117}{}{我要晕倒了！}
