{100}{}{你看到一个上锁的保险箱。}
{101}{}{你看到一个未上锁的保险箱。}
{102}{}{保险箱是锁着的。}
{103}{}{在打开保险箱时，你发现并拆除了一个陷阱。}
{104}{}{在打开保险箱时，你发现了一个陷阱，但不小心触发了它。}
{105}{}{在打开保险箱时，你发现了一个陷阱，但未能成功拆除。}
{106}{}{保险箱已经解锁。}
{107}{}{你成功解锁了保险箱。}
{108}{}{你多次尝试解锁保险箱，结果触发了一个陷阱。}
{109}{}{你无法解锁保险箱，锁已经卡住了。}
{110}{}{你无法解锁保险箱。}
{111}{}{你在保险箱上发现了一个陷阱，并成功拆除。}
{112}{}{你在保险箱上发现了一个陷阱。}
{113}{}{在搜索保险箱的陷阱时，你不小心触发了一个。}
{114}{}{在搜索保险箱的陷阱时，你什么也没发现。}
{115}{}{你成功拆除了陷阱。}
{116}{}{你不小心触发了陷阱。}
{117}{}{你未能成功拆除陷阱。}
