{100}{}{你看到瑞克，一个守卫。}
{101}{}{你想干嘛？}
{102}{}{呃...嗯...}
{103}{}{打扰一下，我可以问你几个问题吗？}
{104}{}{我要把你的脑袋挂在杆子上！}
{105}{}{没事了。}
{106}{}{滚回东区去，你这个瘾君子！}
{107}{}{啥？}
{108}{}{我走了。}
{109}{}{快点问，我不该在上班时聊天。}
{110}{}{这里是哪里？}
{111}{}{你的工作是什么？}
{112}{}{抱歉打扰了，再见。}
{113}{}{你最好注意你的言行，小子！}
{114}{}{不！你才该小心！我要给你脑袋来一颗子弹！}
{115}{}{你不值得我浪费时间。}
{116}{}{如果你不知道，你大概不该在这儿。这是高地，海塔先生住在这里，他只见预约的人。}
{117}{}{你的工作是什么？}
{118}{}{我可以和海塔先生预约吗？}
{119}{}{感谢你的时间。}
{120}{}{我负责确保没人打扰海塔先生。}
{121}{}{其实我对杀掉海塔先生感兴趣。是时候让你赚工资了！}
{122}{}{这里是哪里？}
{123}{}{感谢你的时间，再见。}
{124}{}{不行。}
{125}{}{我不喜欢你的态度。你最好离开。}
{126}{}{好吧，我走了。}
{127}{}{来啊，你这个长发怪胎！}
{128}{}{日落后这里不允许任何人进入。其他守卫甚至不会警告你。如果他们抓到你，他们会攻击。你最好在脑袋还在脖子上时回市区。}
{129}{}{好吧。我走。}
{130}{}{不，我留下。}
{131}{}{我哪儿也不去。}
{132}{}{抱歉，我这就走。}
{133}{}{伙计，你真是笨得可以，赶紧走吧！}
