{100}{}{你看到一个集市居民。}
{101}{}{哇！我听说你杀死了死亡爪，干得好！}
{102}{}{是真的吗？死亡爪真的存在吗？}
{103}{}{我听说你是那个}
{104}{}{男人}
{105}{}{女人}
{106}{}{，杀死了死亡爪。干得好！}
{107}{}{谢谢你消灭了那个噩梦，我们现在都能安心睡觉了。}
{108}{}{希望那个死亡爪真的死透了。}
{109}{}{我希望那些摧毁商队的变种人不要来找我们麻烦。}
