{100}{}{你看到一个嬉皮士。}
{101}{}{你好！你会哦，抱歉}
{102}{}{是你！我听说过你！你杀小孩还吃他们！贾恩妈妈！贾恩妈妈！救命！}
{103}{}{先生，你想要一朵花吗？}
{104}{}{女士，你想要一朵花吗？}
{105}{}{空}
{106}{}{这个地方有什么特别的吗？}
{107}{}{这花有什么特别之处？}
{108}{}{小孩，你卖多少钱？}
{109}{}{当然，小孩！}
{110}{}{不用了，谢谢。}
{111}{}{当然。我可以踩碎它来解气！}
{112}{}{[嗅，嗅]。闻起来不错！}
{113}{}{[嗅，嗅]。闻起来好臭！}
{114}{}{傻瓜！你已经有一朵花了！}
{115}{}{你到底要不要这朵花！}
{116}{}{如果你能告诉我一点关于这个地方的事，我就拿花。}
{117}{}{这花有什么特别之处？}
{118}{}{当然，小孩！}
{119}{}{别再说花的事了。直接回答问题！}
{121}{}{这是团结玫瑰。它是圣焰的颜色，代表着当大教堂的孩子们帮助全世界的人变得友好和强大时，我们将拥有的和平与和谐！呃，你想要一朵吗？}
{122}{}{空}
{123}{}{一朵玫瑰怎么能做到这一切？}
{124}{}{告诉我关于圣焰的事}
{125}{}{小孩，多少钱？}
{126}{}{当然，小孩！}
{128}{}{听着。我不想要你的破花。}
{129}{}{免费的。我们不相信金钱。圣焰满足我们所有的需求！这太美好了！你应该加入我们的幸福大教堂！呃，你想要一朵吗？}
{130}{}{告诉我关于大教堂的事}
{131}{}{告诉我关于圣焰的事}
{132}{}{当然，小孩！}
{128}{}{听着。我不想要你的破花。}
{135}{}{谢谢你，哦谢谢你！我送出了一朵花！这不是很棒吗}
{136}{}{你真坏！我讨厌你！希望你被圣焰吞噬！}
{137}{}{当然啦！拿一朵吧！我送出了一朵花！这不是很棒吗}
{138}{}{你真蠢！希望圣焰在你说更多蠢话之前就灭了你。贾恩妈妈，小心这个蠢人！}
{139}{}{我们是大教堂的孩子。我们受到圣焰的指引，要喂饱饥饿的人，治愈病人。我们要把和平与团结传播到每个地方，一切都会变得非常美好！来，拿你的花吧！}
{140}{}{我觉得你根本不想要花。你在对我凶！}
{141}{}{玫瑰不会那样做，傻瓜！只有人才能改变世界。在圣焰的引导下，我们一定会让一切变得美好特别！那么你想要一朵花吗}
{142}{}{告诉我关于大教堂的事}
{143}{}{告诉我关于圣焰的事}
{144}{}{当然，小孩！}
{145}{}{不用了，谢谢。}
{146}{}{我会让你看看什么是傻，臭小子...}
{147}{}{那是净化世界的火焰，如果我们遵从它，它就不会再这样做了！它希望我们聪明、和平、团结！那么你想要一朵花吗？}
{148}{}{告诉我关于这个团结的事}
{149}{}{当然，小孩！}
{150}{}{不用了，谢谢。}
{151}{}{够了，别再提那破花了！}
{152}{}{那是一个靠近海洋的美妙地方，人们在那里花时间赞美圣焰并做好事。那里的人都很友善，除了可能拉舍神父。呃，你想要一朵花吗？}
{153}{}{告诉我关于拉舍神父的事}
{154}{}{当然，小孩！}
{155}{}{不用了，谢谢。}
{151}{}{够了，别再提那破花了！}
