# Chris Avellone is a male bounty hunter. He has an abrupt attitude and is serious about
# his money. He does not like child killers (which is the only way the player will meet him).

{100}{}{你看到一个肌肉发达的赏金猎人，胸前的按钮上写着：'我是克里斯多夫，你是猎物。'}
# Bounty Hunter is considered Male term

{101}{}{你想干什么？}
{102}{}{一个甜甜圈。}
{103}{}{你在这里干什么？}
{104}{}{只是四处看看。}
{105}{}{没什么。}
{106}{}{我们这里可不欢迎聪明人。滚开。}
# Alternate for "Buzz off" could be "Get lost" or "Get out of here"

{107}{}{这个笑话第一次就不好笑。你即将发现为何我是荒原中最可怕的赏金猎人之一。而我甚至不需要为此收钱。}
{108}{}{不关你的事。}
{109}{}{那就去别处瞎转吧。}
# Alternate for "poke around" could be "Look around"

{110}{}{你知道吗？你因为杀害儿童而被悬赏1500瓶盖。是时候收钱了！}
# 1500 caps is equivalant to 1500 dollars. Children is considered male plural

{1000}{}{亚德顿}
{1001}{}{追随者}
{1002}{}{大教堂}
{1003}{}{撕裂者}
{1004}{}{刀锋}
{1005}{}{枪支}
{1006}{}{枢纽}
{1007}{}{垃圾镇}
{1008}{}{水}
{1009}{}{妮可尔}
{1010}{}{尸骨城}
{1011}{}{奔跑者}
{1012}{}{芯片}

{1100}{}{南边的一个小镇，偶尔有人会来。}
{1101}{}{那些是住在我们附近的爱好和平的怪人。}
{1102}{}{在亚德顿南边和尸骨城其他地方的一个神秘教派。妮可尔说他们有问题。}
{1103}{}{我们西边一个极端暴力的帮派。}
{1104}{}{东边的一个帮派。他们使用震动刀。}
{1105}{}{一个从枢纽来的帮派，卖枪。他们在我们北边。}
{1106}{}{中心城是一个位于东边的大型商贸城市。}
{1107}{}{废城是一个位于中心城北部的小城市。}
{1108}{}{我帮不了你。}
{1109}{}{她是追随者的领袖。}
{1110}{}{这里是天使之骨堆，旧洛杉矶市的遗迹。}
{1111}{}{一个来自中心城的帮派，贩卖武器。位于这里的北边。}
{1112}{}{我帮不了你。}
