{101}{}{商队的商人们毫无还手之力。他们全都死了。}
{102}{}{看起来变种人装备精良。商队的商人在这种火力下毫无胜算。}
{103}{}{他们死了。}
{104}{}{你几乎可以确定这是一个死去的人。}
{105}{}{在所有变异的血肉中，有一个看起来很眼熟。是那个从避难所派出去却从未归来的侦察员之一...}
{106}{}{在所有变异的血肉中，你认出了其中一个变种人是肖恩，他是几个月前从你的避难所派出的侦察员之一。}
{107}{}{所有变种人都死了，但有一个看起来很眼熟，但你无法辨认出这个“面孔”。}
{108}{}{死去的变种人。}
