{100}{}{你看到一个瘦削、愤怒的男人。}
{101}{}{你看到伊斯马克。}
{102}{}{什么？}
{103}{}{是啊，你想要什么？}
{104}{}{嘿，唱得不错。}
{105}{}{你的歌声让我耳朵流血。}
{106}{}{没事。}
{107}{}{哇！}
{108}{}{哦，太好了。你不知道这让我多么满足。走开。}
{109}{}{谢谢。有什么我能帮你的吗？}
{110}{}{你在其他地方也演出吗？}
{111}{}{只是想象征性地投点钱。}
{112}{}{你是在哪学会唱歌的？}
{113}{}{谢谢你的时间。}
{114}{}{什么？！我没时间陪你玩。}
{115}{}{是啊，我有时在商场唱歌，我也跟着商队去过钢铁兄弟会和阿迪特姆。你为什么问？}
{116}{}{你能告诉我怎么去商场吗？}
{117}{}{我需要知道怎么去兄弟会。}
{118}{}{我怎么去阿迪特姆？}
{119}{}{呃，没事，谢谢。}
{120}{}{商场？哦，就在垃圾镇南边不远。还有什么？}
{121}{}{兄弟会在这里往西走几天，再稍微往北一点。不过别去那里，他们不会让你进去，除非你跟着商队。你还需要什么？}
{122}{}{嗯，往商场西南走。阿迪特姆是骨园的一部分。那是个小型半工业化的城镇。我不太喜欢那里。你还想知道什么？}
{123}{}{嘿，谢谢。当个饥饿的艺术家很难。你有什么想知道的，尽管问。}
{124}{}{我很感激你的好意，但你比我还穷。}
{125}{}{啊，我是到处学的。在商场从一个老歌手那里学了一点，在骨园的阿迪特姆从拾荒者那里学了一些音乐。你懂的，只是需要练习。}
{126}{}{一个男人在角落里大声唱歌。}
{127}{}{你的脑袋像个碗！}
{128}{}{圆得像只鼹鼠！}
{129}{}{我宁愿去炸！}
{130}{}{那就付过路费吧！}
{131}{}{我了解你的心思}
{132}{}{它是一座钢铁牢笼}
{133}{}{内心的怒火是……}
{134}{}{死亡爪}
{135}{}{我需要你}
{136}{}{就像需要一剂毒药}
{137}{}{我需要你}
{138}{}{就像需要辐射蝎的毒刺}
