{100}{}{你看到 Jasmine。}
{101}{}{打扰一下，先生，这位是商会的成员。}
{102}{}{让我搞清楚；你在射击我的老板和朋友，还想谈话？去你的吧！}
{103}{}{门在那边。别让它在你出去的时候撞到你。}
{104}{}{你好。欢迎加入盗贼圈。只要表现得当，你就能加入。}
{105}{}{欢迎来到盗贼圈。我是 Jasmine。我会帮你尽可能轻松地潜入达伦·海塔沃尔的庄园。海塔沃尔的庄园位于高地，始终至少有两个守卫。项链可能在一个保险箱里，通常会有一些小陷阱，所以要小心。这是一些开锁工具和几根信号棒，能让你的工作轻松一点。还有一瓶核子可乐。尽量不要杀死海塔沃尔先生。他是我们“最喜欢”的人之一。你都明白了吗？}
{106}{}{你说的“最喜欢”是什么意思？}
{107}{}{开锁工具和信号棒？就这些？}
{108}{}{核子可乐？}
{109}{}{不杀他？不敢保证，女士。}
{110}{}{这工作真烂。找别人吧。}
{111}{}{没问题。我走了。}
{112}{}{隆克！}
{113}{}{打扰一下，先生，你不应该在忙你的任务吗？}
{114}{}{打扰一下，小姐，你不应该在忙你的任务吗？}
{117}{}{又见面了。如果你拿到了项链，你得先交给洛克斯利先生才能得到奖励。}
{118}{}{干得好，小伙子。这是你的奖励。[Jasmine 给了你 3000 块钱]}
{119}{}{干得好，小姐。这是你的奖励。[Jasmine 给了你 3000 块钱]}
{121}{}{顺便说一下，这里有点小东西，帮你在未来的犯罪活动中更顺利。}
{122}{}{又见面了。}
{123}{}{嗯，他在很多情况下都是我们的恩人。如果你杀了他，可能会有更聪明的人取而代之。我们不希望那样。}
{124}{}{呸！真正的小偷靠的是智慧。我们对你已经很慷慨了。现在走吧！}
{125}{}{他们是我们的企业赞助商。洛克斯利口渴了，他们“捐赠”了几十瓶给我们。他们真是太好了。}
{126}{}{嗯，我不太喜欢这种态度。不过，没人是完美的。}
{127}{}{好吧。我想我可以代表洛克斯利先生说，希望我们再也不要见面。滚出去。}
{128}{}{祝好运。钻石是我世界上第二喜欢的东西！}
{129}{}{对。Runk。没错。}
{130}{}{我们警告过你，但你没听。可惜你有听力问题。}
{131}{}{我想你刚刚没通过测试！别再回来。}
{132}{}{打扰一下，先生，这位是商会的成员。}
{133}{}{我们警告过你，但你没听。可惜你的听力有问题。}
{134}{}{呸！真正的小偷靠的是机智。我们对你已经很慷慨了，小姐。现在快走！}
{135}{}{[Jasmine递给你一套电子开锁器]}
