{100}{}{你看到一个面容锐利的年轻人。}
{101}{}{你看到杰森·齐默曼。}
{102}{}{嘿，你是从很远的地方来的吗？你经历过很多冒险吗？}
{103}{}{是的，我来自北方很远的一个避难所。}
{104}{}{其实，我来自火星。想看看我的火焰枪吗？}
{105}{}{我经历过一些冒险。}
{106}{}{其实没做过什么特别的事情。}
{107}{}{呃，远。避难所。}
{108}{}{哦。我以为经历过外面的荒地的人会更聪明。算了。}
{109}{}{迈尔斯说现在你拿到了那些零件，他可以让农场运转起来，这样我们就不用把子弹卖给集市了。我从来没想过这个，直到史密蒂指出他制造的子弹是}
{110}{}{卖给集市，然后集市再卖给帮派。我想你找到了一个不错的解决方案。}
{111}{}{我从没想过我们能停止与帮派的战斗。我父亲告诉我你让他们承诺不再打扰我们。你知道，我一直以为我想去冒险，但我觉得我更喜欢……嗯，现在这里}
{112}{}{的安全感。不再担心帮派突然袭击，也不再担心谁会被杀。}
{113}{}{洛琳说在这里南边有一个避难所，我的很多祖辈都住在那里。在避难所生活是什么样的？}
{114}{}{其实挺无聊的。}
{115}{}{非常刺激。我们有各种你无法想象的科技！}
{116}{}{哦。那么你离开后一定经历过一些冒险，对吧？}
{117}{}{其实没有。}
{118}{}{是的，外面有很多危险。}
{119}{}{正如有人曾写道，‘冒险就是别人远在他方经历非常不愉快的时光。’}
{120}{}{嗯。集市的商人们谈论辐射蝎子之类的东西。}
{121}{}{其实，大部分只是沙漠。}
{122}{}{嗯，实际上外面有各种各样的怪物。}
{123}{}{真的吗？你打过什么样的怪物？}
{124}{}{没什么，只是一些老鼠之类的。}
{125}{}{是啊，集市的守卫说沙漠里有很多放射性变异生物。猎杀怪物一定很刺激吧！}
{126}{}{是的，确实很刺激！}
{127}{}{不；其实挺麻烦的。毒液、咬伤、辐射……都很致命。}
{128}{}{我希望有一天能去冒险。}
{129}{}{我从没想过这个。我倒是挺喜欢有干净的水和一个可以住的地方。}
{130}{}{我原以为在荒原生活会是……你懂的……粗犷、危险，还有各种事情。但我想我们这里也有足够的事情让我们忙碌，比如那些帮派。}
{131}{}{你是什么怪人吗？Caleb根本不应该让你进来！}
{132}{}{真无聊。我们这里只有这个愚蠢的水井，还有Miles一直想让它运作的地下农场。}
{133}{}{是啊，我注意到你没有床垫什么的。在外面一定很脏很不舒服吧。}
{134}{}{你好，又见面了。有趣的故事可以分享吗？}
{135}{}{你想知道什么？}
{136}{}{没有什么特别的。}
{137}{}{好吧，如果你做了什么有趣的事，记得告诉我！}
{138}{}{别烦我！}
{139}{}{谢天谢地你来了！请帮我逃出去！}
{140}{}{嗯。}
{141}{}{别担心，我会带我们出去的。}
{142}{}{抱歉，孩子，你得靠自己了！}
{143}{}{你在这里干什么？}
{144}{}{谢谢你！}
{145}{}{请不要丢下我！}
{146}{}{我以为离开Adytum去探索世界会很有趣。但Rippers抓住了我，一直把我关在这里。请帮帮我！}
{147}{}{好吧，我们赶快离开这里！}
{148}{}{不可能。你自己惹的麻烦，自己解决。}
{149}{}{希望我们能快点离开这里！}
