{100}{}{你看到耶利米，一个为儿童传递消息的人。}
{101}{}{你看到一个儿童。他看起来若有所思。}
{102}{}{打扰了，兄弟。你吓到我了。我能为主人做些什么？}
{103}{}{插科打诨！}
{104}{}{你在做什么？}
{105}{}{啊，是的，一个正在训练的超级变种人。我会回去继续我的任务。}
{106}{}{如果你不知道，那就不关你的事。如果你在打听不该知道的事情，我就得向我们的上司报告你。你应该更清楚才对。}
{107}{}{我是个很重要的人物。}
{108}{}{抱歉打扰你了。}
{109}{}{我刚到这里。}
{110}{}{你凭什么问我问题？！你真幸运我没把你报告给圣火！！}
{111}{}{当然是在传送报告。}
{112}{}{什么报告？如果可以问的话。}
{113}{}{你做得很不错。}
{114}{}{就这样，谢谢。}
{115}{}{好的，那么。愿和平与你同在。}
{116}{}{我很抱歉。我能为你做些什么？}
{117}{}{你在做什么？}
{118}{}{你可以先回答我的问题。}
{119}{}{你可以去死！}
{120}{}{卫兵！！！}
{121}{}{显然你不属于这里。你是谁？}
{122}{}{其实我是一个避难所居民，想和主人谈谈。}
{123}{}{嗯……多尔菲乌斯……嗯……莫菲乌斯派我来的。}
{124}{}{我是洛基。来自南方的新进成员。}
{125}{}{不，我不属于这里。但我知道这颗子弹属于哪里……在你的头上。}
{126}{}{我负责传送周边地区的人类纯净报告。但你应该知道的。[看起来很可疑] 你是谁？}
{127}{}{我是莫菲乌斯派来给主人传话的。}
{128}{}{我是谁不关你的事……只管回答我的问题！}
{129}{}{你不该知道我是谁，这是主人的意愿。}
{130}{}{你竟敢质疑我是谁？愚蠢，我应该在这里就把你击倒。}
{131}{}{这真是奇怪……我从未听说过你。}
{132}{}{我是被莫菲斯派来给大师传递消息的。}
{133}{}{我是高级教团成员。为了确保我在外界的安全，只有大师和莫菲斯知道我的存在。但我已被大师召回。}
{134}{}{请原谅我。我为质疑你而道歉。请继续你的事情，如果我能帮上忙，请告诉我。}
{135}{}{我不知道你是谁，你不属于这里。卫兵！！！}
{136}{}{你是谁？在这里干什么？}
{137}{}{我是信徒，我迷路了。}
{138}{}{莫菲斯派我来给大师传递消息。}
{139}{}{寻找一个孤独的灵魂送上天堂。}
{140}{}{呃！}
{141}{}{你不允许进入这个区域。只有侍奉者及以上才能进入这里。回到大教堂去。}
{142}{}{对我造成的任何麻烦表示歉意。}
{143}{}{离开前我能问你几个问题吗？}
{144}{}{可以，但在我劈开你的脑袋之前不行。}
{145}{}{莫菲斯不会派像你这样的废物执行这样的任务。卫兵！！}
{146}{}{你这个白痴！你不允许进入这个区域。立刻回到大教堂去！}
{147}{}{好的。}
{148}{}{嗯。}
{149}{}{不。}
{150}{}{我为大师传输记录。这就是你需要知道的，孩子。现在，你必须离开。}
{151}{}{我现在就离开。}
{152}{}{我只是想再问几个问题。}
{153}{}{我会离开。我会离开。但在我打爆你的脑袋之前不会。}
{154}{}{你是怎么进来的？！在这里鬼鬼祟祟地干什么？}
{155}{}{我只是想问你几个问题。}
{156}{}{不，你不能问我任何问题。现在离开。}
{157}{}{停下！你不该在这里！}
{158}{}{呃？}
{159}{}{抱歉。我迷路了。我现在就离开。}
{160}{}{但我确实有事在这里。莫菲乌斯派我执行一个关于主宰的任务。}
{161}{}{我跟踪了一个形迹可疑的人到这里。你见过他吗？}
{162}{}{不。杀戮是我的事业，而生意兴隆。}
{163}{}{没有，我没见过任何人。他长什么样？}
{164}{}{没关系，我想他已经跑了。}
{165}{}{是个矮小的绿色小人。}
{166}{}{他大概和你一样高，但穿着皮夹克……你袍子下面穿的是什么？}
{167}{}{他看起来就像你，蠢货！}
{168}{}{嗯……我……我……你不会真的以为是我吧？多荒谬。我从来没有！}
{169}{}{好吧，那我就先走了，但如果你看到什么请告诉我……}
{170}{}{是的！我确实认为是你！趴下，双手摊开！}
{171}{}{不，我不认为是你，但我可以问你几个问题吗？}
{172}{}{是的，我的兄弟。我能为你做些什么？}
{173}{}{是的，我的姐妹。我能为你做些什么？}
{174}{}{兄弟，你在这里做什么？}
{175}{}{只为主宰服务。这就是我所求的。兄弟。}
{176}{}{抱歉，认错人了。你们穿着这些袍子看起来都一样。}
{177}{}{你可以通过去死来为我服务，你这个疯子！}
{178}{}{我负责传递周边地区的人类纯净度报告。}
{179}{}{就这样。谢谢。}
{180}{}{兄弟，我想再问你几个问题。}
{181}{}{是的，这是一个非常重要的工作。你理解你对主宰和我们所有人的职责的重要性吗？}
{182}{}{当然，我是向主宰报告新的、未被辐射污染的人类的消息的人。我是向主宰报告可能存在的失落避难所最终消息的人。那里可能还有纯种人类。}
{183}{}{是的，我的兄弟。你确实理解。谢谢。就这样。}
{184}{}{我想问你几个其他的问题。}
{185}{}{即使一个纯种人类站在你面前，你也认不出来。蠢货。}
{186}{}{即使一个纯种人类站在你面前，你也认不出来。蠢货。}
{187}{}{你行为很奇怪。我不相信你是你所说的人。护卫！}
{188}{}{你问的问题太多了。我不相信你是你所说的人。护卫！}
{189}{}{嘿！我告诉过你不允许到这里来！护卫！}
