{100}{}{你看到鲍勃憔悴的身影。}
{101}{}{请不要杀我！我发誓我会还你钱的！}
{102}{}{呃……}
{103}{}{是啊，你最好赶快还钱。}
{104}{}{我想我找错房间了。}
{105}{}{你在说什么？}
{106}{}{啊！你一定是傻子弗雷德，那个无情的杀手。请不要杀我！}
{107}{}{这里，这里。拿去吧。这是我所有的东西。}
{108}{}{你是说你不是来杀我的？}
{109}{}{没错。今天是你的幸运日。}
{110}{}{不是。谁会威胁你呢？}
{111}{}{谢谢。当你拿着}
{112}{}{走进来的时候，我有点紧张。}
{113}{}{谢谢。当你拿着}
{114}{}{走进来的时候，我有点紧张。}
{115}{}{天啊，我还以为你是赌场派来的呢。我欠他们很多钱，像沙漠里的沙子一样多。}
{116}{}{你为什么欠他们这么多钱？}
{117}{}{你欠赌场的谁钱？}
{118}{}{你欠多少钱？}
{119}{}{嗯，谢谢你的信息。}
{120}{}{他们作弊。我玩了一些老虎机和扑克。但我比那水平高。我发誓那些机器被动了手脚。我输了很多钱。}
{121}{}{你欠赌场的谁钱？}
{122}{}{你欠多少钱？}
{123}{}{嗯，谢谢你的信息。}
{124}{}{一些打手。他们说他们为赌场老板工作，但我从没见过他。一个叫伊佐，我想，还有一个是个看起来像大块头的家伙。真是该死的骗子。}
{125}{}{你为什么欠他们这么多钱？}
{126}{}{你欠多少钱？}
{127}{}{嗯，谢谢你的信息。}
{128}{}{哦，不算太多。几千块吧。我只玩了四五个小时。嗯，也许稍微久一点。他们给了我一些借据，我这里没有足够的钱来还。我得回去商贸城拿些现金。我怕他们会打我如果我试图离开。}
{129}{}{你为什么欠他们这么多钱？}
{130}{}{你在赌场欠了谁的钱？}
{131}{}{嗯，谢谢你的信息。}
{132}{}{哦，又是你。我希望你比我运气好。}
{133}{}{嘿，你在我房间里干什么？你是赌场派来的吗？}
{134}{}{嗯哼！}
{135}{}{是的，我是赌场的。}
{136}{}{不，我只是随便看看。}
{137}{}{赌场有什么问题吗？}
{138}{}{哦，天哪。我还以为你是赌场的人。你吓到我了。}
{139}{}{哦，好吧。再见。}
{140}{}{为什么？}
{141}{}{嗯，我在那里惹上了麻烦。我欠了他们很多钱。}
{142}{}{你为什么欠他们这么多钱？}
{143}{}{你在赌场欠了谁的钱？}
{144}{}{你欠了多少钱？}
{145}{}{嗯，谢谢你的信息。}
{146}{}{哦，又是你。刚才你吓了我一跳。你没看到赌场的人在这附近吧？}
{147}{}{嗯哼！}
{148}{}{没有。}
{149}{}{是的，确实见到了。}
{150}{}{嘿，我有些问题想问你。}
{151}{}{好，好。我只需要再几天时间，我就能把他们的钱赚回来，还能多赚点。我比他们想象的赌术要好。}
{152}{}{啊！天哪！我有麻烦了！再见。}
{153}{}{请问吧，开枪——哦，糟糕的用词，鲍勃。糟糕的用词。}
{154}{}{你为什么欠他们这么多钱？}
{155}{}{你在赌场欠了谁的钱？}
{156}{}{你欠了多少钱？}
{157}{}{嗯，谢谢你的信息。}
