{100}{}{你看到朱莉安娜。}
{101}{}{你看到一个普通的阿迪镇居民。}
{102}{}{你好。}
{103}{}{呃。}
{104}{}{你好。}
{105}{}{我有罗梅罗的消息。}
{106}{}{小姐，我可以问一下您的名字吗？}
{107}{}{我叫朱莉安娜。}
{108}{}{你在这里有工作吗？}
{109}{}{我可以问一下关于你们镇子的一些情况吗？}
{110}{}{我做凯莱布要求的事情。但我实际上只能做一点农活。我没有帮助史密提或迈尔斯的技能。}
{111}{}{告诉我一些你提到的其他人。}
{112}{}{我们生存下来，监管者确保没有事情伤害我们。主要是通过不让我们离开这里。}
{113}{}{嗯，迈尔斯做化学，他制造子弹和其他东西。史密提是个工匠，他制作像锅和刀这样的东西。}
{114}{}{你有罗梅罗的消息？是什么？}
{115}{}{他说他和你完了。}
{116}{}{他说他送上他的爱。}
{117}{}{他送了这个项链作为信物。}
{118}{}{不……这不可能是真的……我……}
{119}{}{他没有做其他事情吗？}
{120}{}{没有，抱歉。}
{121}{}{哦对，他送了这个项链。}
{122}{}{多么浪漫！哦，我一定要想办法见到他！如果……也许……或许洛林可以带个消息给他……}
{123}{}{哦！非常感谢你的帮助！我们决定现在和追随者们一起住在这里，和平共处。感谢你支持我们的爱情。}
{124}{}{我不能没有他活下去！}
{125}{}{朱莉安娜拔出一把刀，刺向自己！}
{126}{}{你获得250点经验，因为你帮助这对命运多舛的恋人把罗梅罗的项链送给了朱莉安娜。}
