{100}{}{你看到治安官贾斯汀·格林。}
{101}{}{哎呀，是那个屠杀无辜者的人。我听说过你，你真幸运我有警徽阻止我当场解决掉你。我建议你立刻离开我们的城镇——现在就走。别靠近我们的孩子。}
{102}{}{您好，先生！我叫贾斯汀·格林，是这座城市的治安官。今天有什么我可以为您效劳的吗？}
{103}{}{您好，女士！我叫贾斯汀·格林，是这座城市的治安官。今天有什么我可以为您效劳的吗？}
{104}{}{好了，说出来吧！}
{105}{}{德克曾试图雇我去杀一个商人和他的妻子。}
{106}{}{德克曾试图雇我去杀一个叫简的人。}
{107}{}{没事，抱歉。}
{108}{}{抱歉，我不能告诉你。我会没命的。}
{109}{}{哦，谢谢。我们尽力而为。在这么大的城市里真的很难，但我们尽量用现有的资源做到最好。当那些暴徒的火力比我们强时，确实很困难。}
{110}{}{再次感谢。}
{111}{}{是时候离开了，杀童者。}
{112}{}{我们不能允许那样的事情发生。但是，如果你改变主意，请告诉我。外面很危险，总得有人挺身而出。}
{113}{}{太好了！我已经从其他渠道得知了他的计划。你是我采取行动所需的最后确认。这会很艰难，我需要所有能得到的帮助。我可以支付你1300瓶盖。现在给你300，剩下的等我们完成后再给。你觉得怎么样？}
{114}{}{你来晚了……该死！我知道他是幕后黑手，只是希望能及时阻止他。不管怎样，你是我采取行动所需的最后证人。我们得“解决掉他”。这会很艰难，我需要所有能得到的帮助。我可以支付你1300瓶盖。现在给你300，剩下的等我们完成后再给。你觉得怎么样？}
{115}{}{你来晚了……我怎么知道你不是凶手？德克不太可能让人知道他的计划还活着。}
{116}{}{我刚得到消息，她已经死了……等一下。我怎么知道你不是凶手？德克不太可能让人知道他的计划还活着。}
{117}{}{很乐意效劳。}
{118}{}{抱歉，我要全部预付。}
{119}{}{不可能！你自己解决吧。}
{120}{}{不行。你看起来很可信，但我不能确定你在事情变得棘手时不会抛下我们。这样的话，我们中至少有一个人能活下来确保你得到报酬。这也算是一点“保险”。}
{121}{}{那就干吧。}
{122}{}{治安官，你自己解决吧。}
{123}{}{太好了！这是你的第一笔报酬。[治安官递给你300瓶盖]}
{124}{}{我准备好了。}
{125}{}{好的，再见。}
{126}{}{很遗憾听到这个。如果你改变主意，请告诉我，但我不能等太久。}
{127}{}{好的，我会做的。等我去准备些补给。}
{128}{}{你疯了。}
{129}{}{再见。}
{130}{}{太好了！这是你第一部分的酬劳。[治安官给了你300瓶盖]}}
{131}{}{什么？你以为我会站在一旁，让他杀掉无辜的人吗？我对这座城市有责任感，这点我不指望你能理解。}}
{132}{}{你说得对。现在轮到你行动了。}}
{133}{}{你竟敢指责我！}}
{134}{}{我不在乎你怎么想。}}
{135}{}{嗯，他什么也没尝试。}}
{136}{}{我们在猎鹰酒吧，周围都是人。}}
{137}{}{对不起，德克欺骗我们相互对抗多年，我已经不知道该信任谁了。但我真的需要你的帮助，情况会很艰难，不过我会支付你1300脚本钞。300脚本纽，现在支付，剩下的1000完成后给。}}
{138}{}{我知道有老鼠出没！你运气好我没有证据，我建议你在我找到之前赶紧离开镇子。}}
{139}{}{那真是太奇怪了，我从未听说过德克离开过他的办公室。他肯定越来越大胆了。那个该死的，杀人的……啊！我迟早会抓到他！听着，你帮我们，我就付你1300脚本钞——现在300，完成后支付剩下的1000。你意下如何？}}
{140}{}{这是我听过的最大的胡扯！德克从不离开他的办公室！我就知道你有问题。你运气好我找不到证据，建议你赶在找到前离开镇子！}}
{141}{}{好了，走吧……}}
{142}{}{所以，你是来自首的？真是让我刮目相看。}}
{143}{}{是的，对不起。}}
{144}{}{自首？别让我笑掉大牙。}}
{145}{}{抓住他！}}
{146}{}{抓住她！}}
{147}{}{好了，进牢房吧。}}
{148}{}{安坐在那里吧。你暂时别想去哪。}}
{149}{}{逃犯！抓住他！}}
{150}{}{逃犯！抓住她！}}
{151}{}{准备好去干掉德克了吗？}}
{152}{}{是的。}}
{153}{}{不。}}
{154}{}{呃。}}
{155}{}{我真不敢相信德克竟然真的死了。我从没想过能看到这一天。}}
{156}{}{你改变主意了吗？我们仍然需要你去解决我们谈论过的那个麻烦。}}
{157}{}{我去。}}
{158}{}{不，抱歉。}}
{159}{}{啥？}}
{160}{}{我们在盯着你。}
{161}{}{我要举报一宗犯罪！}
{162}{}{你们做得很好。}
{163}{}{只是路过。再见。}
{164}{}{哦啦。}
{165}{}{您好，先生。今天有什么可以帮您的吗？}
{166}{}{您好，女士。今天有什么可以帮您的吗？}
{167}{}{您好。我能帮您什么吗？}
{168}{}{有什么事吗？}
{169}{}{去睡一觉，冷静一下，好吗？}
{170}{}{你在开玩笑吧！呃……他……他是亲自找你的吗？}
{171}{}{是的，他亲自找的我。}
{172}{}{伙计，那真是一场恶战！你在里面表现得很出色。现在德克和凯恩都被解决了，地下组织很快就会瓦解。没有领导，这种组织撑不了多久。这里没人聪明到能接替他们的位置。}
{173}{}{这是你剩下的奖励。再次感谢你的帮助。这座城市欠你一份恩情。 [警长递给你1000瓶盖]}
{174}{}{只要你准备好了，我们就可以出发。}
{175}{}{准备好了就告诉我。我们会等你，但别拖太久。}
