{100}{}{你看到一个面容污迹的年轻女子，穿着深色衣服。}
{101}{}{你看到卡佳，小偷。}
{102}{}{你不是本地人吧。你是谁？}

# TRANSLATION NOTE
# The player-character's name is inserted between lines 103 and 104 by the code.

{103}{}{我叫}
{104}{}{。}
{105}{}{我是个旅行者。}
{106}{}{我也可以问你同样的问题。}
{107}{}{那么，我可以问一下，你在废城做什么？}
{108}{}{你问题真多。}
{109}{}{先告诉我你是谁。}
{110}{}{我只是个探险者。}
{111}{}{我在找一个替换我避难所的水芯片。}
{112}{}{在这里你得小心行事。那么你在这里做什么？}
{113}{}{好吧，公平起见。我叫卡佳。这对你有什么关系？}
{114}{}{为什么这么敌对？}
{115}{}{嘿，如果你要这么无礼，那我就不奉陪了。}
{116}{}{我在找信息。你能帮忙吗？}
{117}{}{或许吧，但这里是我的地盘，不是你的。所以要么说点有用的，要么闭嘴。}
{118}{}{这不重要，我只是个旅行者。我需要一些信息。}
{119}{}{水净化芯片？抱歉，我对此一无所知。在废城很少见到这种技术，除了也许是迈尔斯在研究的东西。}
{120}{}{不管怎样，谢谢了。}
{121}{}{迈尔斯？我在哪里能找到他，他能帮忙吗？}
{122}{}{那你能多告诉我一些关于废城的事情吗？}
{123}{}{只是个旅行者。我以前听过这种说法。没有人会来废城，除了那些中心城的商人和想找死的人。你到底来这里干什么？}
{124}{}{你说得对。我在找一个水净化芯片。}
{125}{}{我不需要告诉你任何事情。}
{126}{}{没错。但这是双向的。}
{127}{}{也许吧。你肯定不是那些帮派的刀客。你想要什么？}
{128}{}{我在找一个水净化芯片。}
{129}{}{我需要更多关于废城的信息。}
{130}{}{我需要了解一下这座城市周围的情况。}
{131}{}{你能告诉我关于刀锋帮的事情吗？}
{132}{}{你能告诉我关于裂口帮的事情吗？}
{133}{}{你能告诉我关于枪械跑商的事情吗？}
{134}{}{你能告诉我关于启示录追随者的事情吗？}
{135}{}{你能告诉我关于阿迪特姆的事情吗？}
{136}{}{聊得很愉快，不过我得走了。}
{137}{}{迈尔斯住在阿迪特姆。他是个科学家，主要研究化学。如果有人能找到水芯片或制造替代品，那就是他。}
{138}{}{非常感谢。}
{139}{}{阿迪特姆是我原来的家。不过对我来说有点太无聊了。它是一个被围起来的自给自足的小镇，位于墓园的南端，但还没到大教堂那么远。我们有时会和商场进行交易。}
{140}{}{我以前和他们打过交道。就帮派来说，他们还不算太坏。他们在一个旧俱乐部里有个藏身处，还有一些哨站。如果你小心的话，甚至可以让他们中的一些人和你交谈。}
{141}{}{裂口帮简直就是凶残。他们是一群近亲繁殖的家伙，乐于折磨和杀戮。我远离他们，你也应该。他们甚至在他们的堡垒周围放置了地雷。}
{142}{}{枪械跑商以前是个真正的帮派，但他们变得软弱了。他们开始做起了交易，把从受害者那里得到的武器或从商场购买的武器进行交易。由于这里没人愿意亲自去商场，他们的生意做得不错，尽管价格很高。}
{143}{}{启示录追随者是一群和平传教士，住在墓园中心附近的一个大图书馆里。我不知道他们为什么还没被消灭。他们战斗力很差，对现实世界没有理解，但除此之外，他们很有礼貌且受过良好教育。}
{144}{}{墓园是个相当敌对的地方。我从来没有机会离开，不过我想我会抓住机会。让我想想……就在这里的南边有大教堂。那里有个邪教，但我远离他们。那里有些阴险的事情在发生。另外，我听说过一个叫商场的交易中心，偶尔会有商队出现，但我从没去过。}
{145}{}{我自己也不打算在这个地方待太久。}
{146}{}{谢谢你的信息。}
{147}{}{你能多告诉我一些吗？}
{148}{}{没开玩笑。如果你需要多一个帮手，我愿意加入。总比在这个鬼地方度过余生要好，对吧？}
{149}{}{欢迎加入，不过沙漠也不见得更有趣。}
{150}{}{不用担心。不管怎样，谢谢你。}
{151}{}{我能先问几个问题吗？}
{152}{}{这个地区被三个帮派——刀锋帮、裂口帮和枪械跑商——占据，同时也是启示录追随者和我家阿迪特姆的所在地。}
{153}{}{好吧，看起来我们得去踢点屁股了！}
{154}{}{听着，这个城市里90%的人都属于三种类型之一——强奸犯、杀人犯或小偷。我是个小偷，而你看起来还挺有礼貌，所以这让我有些好奇，明白吗？这叫生存本能。}
{155}{}{抱歉打扰你了。我想我还是走开吧。}
{156}{}{好吧，那我至少能问几个问题吗？}
{157}{}{我不是这里的人，所以我不算。}
{158}{}{好吧，但请快点。}
{159}{}{嗯，看来我无法反驳这个逻辑。那么你想知道什么？}
{160}{}{我能问你几个问题吗？}
{161}{}{我在找一个水净化芯片。你能帮忙吗？}
{162}{}{不管怎样，谢谢你，我要走了。}
{163}{}{有什么事吗？}
{164}{}{你能试试开这个锁吗？}
{165}{}{你能看看这个陷阱吗？}
{166}{}{有什么建议吗？}
{167}{}{谢谢你的帮助。你现在可以走了。}
{168}{}{还没有。不过请继续关注。}
{169}{}{又是你？这次回来有什么事？}
{170}{}{只是想停下来打个招呼。}
{171}{}{如果你有时间，我还有几个问题想问。}
{172}{}{锁开了。}
{173}{}{东墙的那个书架有些可疑。看起来像是藏了什么东西。}
{174}{}{把你的武器收起来。}
{175}{}{我讨厌狗。}
{176}{}{那食物闻起来不错。}
{177}{}{你有什么战斗技能？}
{178}{}{我在骨园学会了怎么当个打手。我擅长使用刀和冲锋枪。当然，我最喜欢的是飞刀。}
{179}{}{好吧，虽然没有好刀我感觉不太自在。}
{180}{}{你因为招募了骨园拾荒者Katja而获得200点经验值。}
{181}{}{你现在想要什么？}
{182}{}{我改变主意了。我还是希望得到你的帮助。}
{183}{}{没什么。算了。}
{184}{}{我真的开始讨厌这个地方了。}
{185}{}{哇。我希望我有一根热狗和一根很长的棍子。}
{186}{}{哦，呃。我想我要吐了。}
{187}{}{嘿，那面墙上的石膏裂缝看起来好像可以移动。}
{188}{}{小心死亡爪！}
{189}{}{哇哦！}
{190}{}{离开！}
{191}{}{抱歉，我实在听不懂你在说什么。再见。}

#
# Katja tell-me-abouts
#

{980}{}{我对此一无所知。}
{981}{}{我好像没听说过这个。}
{982}{}{不，我没听说过这个。}

{1000}{}{水}
{1001}{}{骨园}
{1002}{}{战争}
{1003}{}{阿迪顿}
{1004}{}{追随者}
{1005}{}{大教堂}
{1006}{}{芯片}
{1007}{}{加尔}
{1008}{}{主宰}
{1009}{}{统一}
{1010}{}{塞特}
{1011}{}{水域}
{1012}{}{死城}
{1013}{}{大厅}
{1014}{}{图书馆}
{1015}{}{监督者}
{1016}{}{医疗}
{1017}{}{治疗}
{1018}{}{避难所}
{1019}{}{避难所13}
{1020}{}{避难所13}
{1021}{}{基里安}
{1022}{}{吉兹莫}
{1023}{}{废城}
{1024}{}{阴影镇}
{1025}{}{沙地}
{1026}{}{枢纽}
{1027}{}{赌场}
{1028}{}{商店}
{1029}{}{死亡爪}
{1030}{}{出埃及记}
{1031}{}{新兵}
{1032}{}{骑士}
{1033}{}{抄写员}
{1034}{}{孩子们}
{1036}{}{兄弟会}
{1037}{}{大锅}
{1038}{}{军事}
{1039}{}{基地}
{1041}{}{末日}
{1042}{}{变种人}
{1043}{}{墨菲斯}
{1044}{}{汗族}
{1045}{}{坦迪}
{1046}{}{艾莉娅}
{1047}{}{戴安娜}
{1048}{}{格温}
{1049}{}{佩特罗克斯}
{1050}{}{托利亚}
{1051}{}{酒精}
{1052}{}{化学品}
{1053}{}{塞斯}
{1054}{}{阿拉德什}
{1055}{}{拉兹洛}
{1056}{}{齐默曼}
{1057}{}{治安警}
{1058}{}{拾荒者}
{1059}{}{刀锋帮}
{1060}{}{妮可}
{1061}{}{中尉}
{1062}{}{心灵者}
{1063}{}{实验体}
{1064}{}{警察}
{1065}{}{商人}

{1100}{}{我不知道哪里可以找到那种旧时代的技术遗物。}
{1101}{}{天使骨场就是旧洛杉矶城仅存的一部分，如今被交战的派系所瓜分。}
{1102}{}{战争带来了痛苦与死亡，我真希望这样的事情永远不会重演。但从我所见来看，人类的希望渺茫。}
{1103}{}{亚蒂姆曾是我的家，但那里的人太过多疑和孤立。他们永远无法通过与世隔绝来生存下去。}
{1104}{}{启示录信徒宣扬和平与宽容，只可惜在这个世界这些都不够。}
{1105}{}{大教堂是一座距亚蒂姆约一日步程的宏伟建筑，由一个膜拜黑暗神祇的奇怪教派管理。}
{1106}{}{我不知道哪里可以找到那种旧时代的技术遗物。}
{1107}{}{我对这件事的了解不比你多。}
{1108}{}{我对这件事的了解不比你多。}
{1109}{}{我对这件事的了解不比你多。}
{1110}{}{我对这件事的了解不比你多。}
{1111}{}{我对这件事的了解不比你多。}
{1112}{}{什么，死亡之城？那不是个传说吗？}
{1113}{}{我对这件事的了解不比你多。}
{1114}{}{我对这件事的了解不比你多。}
{1115}{}{我对这件事的了解不比你多。}
{1116}{}{信徒们手上随时都有个医生。}
{1117}{}{如果你需要治疗，应该去找信徒的医生。}
{1118}{}{避难所不就是那种巨大的地下庇护所吗？}
{1119}{}{避难所不就是那种巨大的地下庇护所吗？}
{1120}{}{避难所不就是那种巨大的地下庇护所吗？}
{1121}{}{我知道的也不比你多。}
{1122}{}{我知道的也不比你多。}
{1123}{}{嗯，我想是集市北边的小镇。}
{1124}{}{阴影什么？}
{1125}{}{阴影沙地？没听说过。}
{1126}{}{集市是个巨大的贸易中心，各种商店和商人都有。}
{1127}{}{我知道的也不比你多。}
{1128}{}{枪械行者有卖东西，阿迪特姆也有一家商店。}
{1129}{}{呃！死亡爪到处都是在骨园。我宁愿不去想它们。又大又名副其实。}
{1130}{}{我知道的也不比你多。}
{1131}{}{我知道的也不比你多。}
{1132}{}{我知道的也不比你多。}
{1133}{}{我知道的也不比你多。}
{1134}{}{我不喜欢小孩。}
{1136}{}{我听说他们是某种高科技僧侣。}
{1137}{}{我知道的也不比你多。}
{1138}{}{我知道的也不比你多。}
{1139}{}{我想一定有一些旧军队的遗迹。}
{1141}{}{你是说那场大战？哇，如果你对那一无所知，那你真是过得太与世隔绝了。}
{1142}{}{我曾经见过一只三眼老鼠。这就是我对变种人的全部了解。}
{1143}{}{我想他是大教堂的高级祭司之类的。}
{1144}{}{我知道的也不比你多。}
{1145}{}{我知道的也不比你多。}
{1146}{}{我知道的也不比你多。}
{1147}{}{我知道的也不比你多。}
{1148}{}{我知道的也不比你多。}
{1149}{}{我知道的也不比你多。}
{1150}{}{我知道的也不比你多。}
{1151}{}{不用了，谢谢。}
{1152}{}{呃。不，我还是算了。我曾看着一个朋友因过量使用狂怒药而死。真不堪入目。}
{1153}{}{我对那个事情了解得不比你多。}
{1154}{}{我对那个事情了解得不比你多。}
{1155}{}{我对那个事情了解得不比你多。}
{1156}{}{他是阿迪特姆的市长，是个公正，但有些摇摆不定的人。}
{1157}{}{他们负责监督阿迪特姆并维持秩序。}
{1158}{}{我过去是个拾荒者。我们会在晚上出去，试着在白骨之地的废墟中寻找有用的东西。这份工作非常危险。我腻烦了阿迪特姆。}
{1159}{}{他们是一群被赶出的人，生活在阿迪特姆外面。}
{1160}{}{她是追随者的领袖，是个聪明且善良的女性。}
{1161}{}{我对那个事情了解得不比你多。}
{1162}{}{我偶尔也有些“女性直觉”，如果你想知道的话。}
{1163}{}{我对那个事情了解得不比你多。}
{1164}{}{我对那个事情了解得不比你多。}
{1165}{}{商人偶尔会与阿迪特姆进行交易，并把货物卖给枪炮行家。}
