{100}{}{你看到副警长肯尼。}
{101}{}{如果你有事找集市警察，请和格林警长谈。我只在警长不在时代为处理他的事务。}
{102}{}{我简直不敢相信警长真的死了。}
{103}{}{你来了。我一直在等你回来。我们听说警长在战斗中被杀了。真难以相信他真的走了。他就像我的父亲一样。}
{104}{}{警长给我留下了指示，以备他无法从任务中返回时执行。他让我把剩下的奖励给你。我相信是1000瓶盖。[副警长递给你1000瓶盖]}
{105}{}{这座城市欠你一份感谢。我只希望警长能亲自感谢你。再见。}
{106}{}{天哪！他们杀了肯尼！那些混蛋！}
