{100}{}{骑士}
{101}{}{我很好奇那些旧的涡轮发动机到底是什么样的。}
{102}{}{真希望我们有辆汽车。}
{103}{}{你知道人类曾经登上过月球吗？至少，我想他们是这么说的。}
{104}{}{你能想象没有科技的生活会是什么样子吗？嗯，我猜你可能已经见过类似的情景。}
{105}{}{我找不到我需要的文件。}
{106}{}{总有一天我会成为圣骑士。}
{107}{}{塔勒斯是个技艺高超的战士。我绝不想和他对抗。}
{108}{}{托马斯是兄弟会里最厉害的战士。我敢打赌他能打败菱形。}
{109}{}{我真想亲手抓住那些掠夺者。让他们知道盗贼应有的下场。}
{110}{}{就是这样……什么？哦，抱歉。我现在不能说话。}
{111}{}{我在想如果我……嗯？哦，你让我忘记了我的思路。}
