{100}{}{你看到凯尔。}
{101}{}{你看到一名骑士。}
{102}{}{啊...所以你就是那个人，对吧？}
{103}{}{什么？}
{104}{}{那么，你是谁？}
{105}{}{没什么。只是从来没有人从古代秩序中活着回来。}
{106}{}{你在这里做什么？}
{107}{}{什么？那他们为什么派我去那里？}
{108}{}{虽然困难，但并非不可能。}
{109}{}{嘿嘿，我猜他们只是想摆脱你，对吧？好吧，他们可真是自作自受。}
{110}{}{是啊。说说看，你在这里做什么？}
{111}{}{嗯，我加入的唯一原因就是想要一套动力装甲。}
{112}{}{去你们的。我走了。}
{113}{}{我修东西，做维护检查，诸如此类的杂活。}
{114}{}{你能修理水芯片吗？}
{115}{}{什么样的“东西”？}
{116}{}{听起来真不错。我待会儿见。}
{117}{}{动力装甲和其他需要修理的东西。}
{118}{}{我怎么才能弄到一套动力装甲？}
{119}{}{我本来可以把这套动力装甲给你，但它缺少了收缩压激励器。没有它就没用。}
{120}{}{那我可以从哪里弄到一个？}
{121}{}{不管怎样，谢谢你。}
{122}{}{嗯，供应室里有很多，但迈克尔和他的该死的表格说这套装甲不符合规格。该死的官僚。}
{123}{}{你是什么意思，不符合规格？}
{124}{}{如果我给你带来一个收缩压激励器，你能帮我修好吗？}
{125}{}{你看到这个眼罩了吗？我得重新焊接它，可能看起来不够漂亮，无法通过检查。}
{126}{}{你说得对。看起来真糟糕。我才不会穿着这套动力装甲。}
{127}{}{滚出去，伙计。}
{128}{}{哇，等一下，伙计，那得花好几个小时。我可以借给你一本手册和我的工具，但你得自己修。}
{129}{}{除了迈克尔，还有哪里可以弄到一个？}
{130}{}{这很公平。我会回来的。}
{131}{}{嘿，罗姆布斯有几套。不过我不会去问他要。只有“被尊敬的人”才能穿这些动力装甲。而且，我觉得他对这些装甲有种不正常的依恋。}
{132}{}{嗯。好的，非常感谢。}
{133}{}{我不这么认为。我甚至不知道那是什么。}
{134}{}{无论如何，谢谢。}
{135}{}{你算什么弱鸡技工，连个水芯片都修不好？}
{136}{}{我怎么才能不用学上百年就搞到动力装甲？}
{137}{}{我叫凯尔。我还从没见过传说中的人物。}
{138}{}{那是什么意思？}
{139}{}{你在这里做什么？}
{140}{}{我也没见过。回头见。}
{141}{}{听麦克森的故事，你会觉得那里是地狱的第九层。}
{142}{}{麦克森？麦克森将军？}
{143}{}{不是麦克森将军，是他的祖父，罗杰·麦克森。我听说你带回了一张磁盘，讲述了那些反叛者的下场，他们下去寻找失落的科技。}
{144}{}{是的，我想我是。我是}
{145}{}{，你是谁？}
{146}{}{我不太想谈这个。}
{147}{}{是啊，那些混蛋。我真不敢相信他们就这样把你送下去。}
{148}{}{而他们给我的报酬就只有一把弹药！}
{149}{}{嘿，新兵，有什么给我的吗？}
{150}{}{没有，我告诉他们是你让我去的，他还是不给我零件。}
{151}{}{还没有，我还没开始找。}
{152}{}{还没运气。}
{153}{}{真是的。我还以为你挺聪明的。我告诉过你那家伙脑子里全是官样文章。}
{154}{}{注意你叫谁白痴。}
{155}{}{我只是想从迈克尔那里说服他。}
{156}{}{如果迈克尔不给我，我能怎么办。}
{157}{}{我走了。}
{158}{}{嗯... 这点我得给你点个赞。不过我想你从供应室拿到它的机会已经没了。你得找别的办法拿到它。或者去别的地方找动力装甲。}
{159}{}{好的，回头见。}
{160}{}{那我还能去哪儿找一个呢？}
{161}{}{祝你好运。}
{162}{}{走开，我正忙着呢。}
{163}{}{你好，你找到那个零件了吗？}
{164}{}{找到了。给你。}
{165}{}{找到了，不过我想先留着。}
{166}{}{太好了！让我把它装到设备里。}
{167}{}{好了，一切准备就绪。拿着这本手册。如果你对修理有点天赋，应该不成问题。祝你好运。}
{168}{}{都这样了？好吧，告诉我什么时候需要我安装。然后你就可以开始修理了。}
{169}{}{嗯，我也不知道该怎么说。我想你需要提高一下修理技能。我会帮你保管这个设备。}
{170}{}{好的。谢谢你。再见。}
{171}{}{又见面了。我能帮你吗？}
{300}{}{[更多]}
