{100}{}{你激怒了拉里。}
{101}{}{你看到拉里。}
{102}{}{如果你打扰了老大，他会揍你。}
{103}{}{人类不允许进入死城。跟我走。}
{104}{}{但是……}
{105}{}{绝不！}
{106}{}{哼！！}
{107}{}{去死吧，人类！}
{108}{}{变种人无视了你。}

{1000}{}{水}
{1001}{}{死城}
{1002}{}{塞特}
{1003}{}{水处理厂}
{1004}{}{大厅}
{1005}{}{卢}
{1006}{}{食尸鬼}
{1007}{}{正常人}

{1100}{}{我不知道。}
{1101}{}{你就站在这儿。}
{1102}{}{他是个懦夫。我们应该干掉他和他的食尸鬼。}
{1103}{}{就是这里。}
{1104}{}{我不知道。}
{1105}{}{他是哈里的老板。}
{1106}{}{懦弱的东西。}
{1107}{}{比食尸鬼还懦弱。}
