{100}{}{你看到一个肌肉发达、满脸伤疤的男人，留着胡子。}
{101}{}{你看到拉尔斯，废城守卫的中士。}
{102}{}{他身上有旧伤的痕迹，看起来像个老手。}
{103}{}{他身上有刀伤和枪伤的疤痕。他结实的肌肉显示出他是个历经磨难的人。}
{104}{}{你知道，在废城偷东西可不明智，小子！}
{105}{}{我能帮你什么吗，陌生人？}
{106}{}{这里有什么好玩的？}
{107}{}{能给我讲讲废城的概况吗？}
{108}{}{你是谁？}
{109}{}{呃。}
{110}{}{如果你是这里的守卫头头，我想我有些信息要告诉你。}
{111}{}{嘿！你！我们知道你这个怪物！}
{112}{}{只要你不惹麻烦，事情就多得很。我们有基利安·黑水的商店，你可以在那里交易。还有吉兹莫的赌场，如果你喜欢赌博的话。或者如果你只是想喝一杯，可以去斯卡姆酒吧。只是别太放肆。}
{113}{}{嘿，我喜欢热闹的时光！}
{114}{}{好吧，你最好控制住自己。我们是个自由的城镇，但不容忍踩别人的脚。别惹麻烦，这样我和我的人就不会找你麻烦。}
{115}{}{真是个扫兴的人！}
{116}{}{听着，伙计，我的工作是维持和平，如果我必须打破几个脑袋来做到这一点，那么就会有人受伤。所以小心点。}
{117}{}{我和我的人在这里为基利安·黑水工作。我们在这个城镇维持一些秩序，处理那些从沙漠来的杀人犯、小偷和其他渣滓。如果你想听我的建议，最好也远离吉兹莫。那个胖子经营着一个不正当的生意，但我们一直没能找到证据。他和他的走狗，骷髅帮，迟早会栽跟头，如果基利安说了算的话。}
{118}{}{真扫兴。这里一点乐趣都没有。}
{119}{}{知道这里有人维持和平真好。谢谢。}
{120}{}{那么，是什么让你们这些执法者不能直接抓住吉兹莫和骷髅帮呢？}
{121}{}{嘿，这是我们的工作。但知道有人欣赏这点总是好的。谢谢。}
{122}{}{必须按规矩办事。我们知道吉兹莫经营的是个黑店，但我们需要确凿的证据来扳倒他。骷髅帮也是一样；他们打伤了人，我们抓住一两个，但没有任何变化。我们就是没有直接证据把他们和任何谋杀或抢劫联系起来。}
{123}{}{也许我可以帮你。}
{124}{}{好吧，祝你好运。}
{125}{}{见鬼，如果你能找到他们的把柄，我们会很感激你的帮助。如果你想谈吉兹莫，基利安是你要找的人。但如果你能找到骷髅帮的信息，就回来找我，我和我的人会处理他们。}
{126}{}{谢谢。小心点。}
{127}{}{我是废城的守卫头头，名字叫拉尔斯。那么，你是谁，陌生人？}
{128}{}{我是}
{129}{}{。}
{130}{}{走开，我没必要告诉你任何事情。}
{131}{}{欢迎来到废城，}
{132}{}{。我能帮你什么忙？}
{133}{}{你能给我介绍一下废城吗？}
{134}{}{只是想找点事做。有什么建议吗？}
{135}{}{你好，旅行者。你需要什么吗？}
{136}{}{什么？}
{137}{}{我在找点工作。}
{138}{}{只是过来打个招呼。}
{139}{}{我有关于骷髅帮非法活动的证词。}
{140}{}{是的，我负责这里的守卫。你有什么要告诉我的吗？}
{141}{}{没什么，只是看看。}
{142}{}{我有雪莉的证词，说明骷髅帮参与了一些非法活动。}
{143}{}{所以，你有关于骷髅帮的信息，是吗？你能告诉我什么？}
{144}{}{他们在这里参与了一些抢劫和杀人事件。}
{145}{}{我已经说服他们中的一个，雪莉，作证他们参与了犯罪活动。}
{146}{}{这很好，但我不能仅凭一个人的说法就把他们全抓起来。我需要确凿的证据或内部证词。}
{147}{}{我会尽力而为。}
{148}{}{我有雪莉的证词，她是前帮派成员。}
{149}{}{太好了。我会找她问几个问题，我相信我能得到所有需要的信息来把他们绳之以法。}
{150}{}{听着，这不是游戏。这里的人们正在受伤。如果你找到真正的证据，回来找我，否则不要浪费我的时间！}
{151}{}{如果你不介意做些偷偷摸摸的事，我需要有人拿到骷髅帮参与非法活动的确凿证据。或者你可以去找基里安，他可能有工作给你。}
{152}{}{感谢你的帮助。因为你的帮助，废城现在安全了一些。}
{153}{}{继续走吧，伙计。}
{154}{}{你因冒险对抗骷髅帮而获得300点经验值。}
{155}{}{你准备好帮忙干掉吉兹莫了吗？}
{156}{}{当然。让我们收拾那个家伙。}
{157}{}{不，我改变主意了。}
{158}{}{好吧，那就干吧。}
{159}{}{嗯，你最好在这儿等着，以免被误伤。}
{160}{}{基利安派我来帮忙把吉兹莫赶出城。}
{161}{}{基利安派我来的。我们要搞定吉兹莫。}
{162}{}{谢谢你的帮助。这是500瓶盖。你永远是废城的朋友，欢迎常来。}
{163}{}{什么？嗯，我们看看吧。我会派人去埋伏他们。你会去吗？}
{164}{}{不用了，我今天已经做了好事。}
{165}{}{是的。}
{166}{}{骷髅帮计划杀掉尼尔！}
{167}{}{拉尔斯的人迅速消灭了骷髅帮。}
{168}{}{看起来拉尔斯可能还活着，但他肯定退出了战斗。}
{169}{}{流浪者，你搞砸了。我们需要证据才能合法地搞定吉兹莫。说实话，我很高兴那个胖子不再碍事，但我们不能纵容谋杀。你最好离开废城，永远别回来。}
{170}{}{我们不欢迎你这种人。你还有十五秒钟，不然我就开枪了。}
{171}{}{又见面了！我能为你做些什么？}
{172}{}{嗯哼。}
{173}{}{不行。}
{174}{}{你因协助消灭骷髅帮获得500经验点。}

{1000}{}{吉兹莫}
{1100}{}{他经营赌场，是个骗子。}
