{100}{}{你看到儿童会的鞭笞者。}
{101}{}{我知道你是谁。你是一个邪恶的坏人，必须受到惩罚。}
{102}{}{我知道你是谁。你是化身为女人的恶魔，但你的外形救不了你。}
{103}{}{我知道你是谁。你的邪恶早已声名远扬。你将孩子们的灵魂送往地狱，未能洗净他们的罪孽。你所做的是极其邪恶的事，必须受到惩罚。}
{104}{}{我知道你是谁。你是行走的死亡，人形的瘟疫。你走过之处，血流成河。但正义的灵魂可以终结这样的罪恶！}
{105}{}{你竟敢打扰我！难道你不知道我的职位有多重要吗？滚出去！}
{106}{}{你拿武器对着我是很不明智的。主的护盾庇护着我，冒犯我必遭报应！}
{107}{}{我也不介意有主的护盾。}
{108}{}{从来没人说我聪明过！}
{109}{}{我只是想和负责人谈谈。}
{110}{}{你那根棍子不错！这就是他们叫你“鞭笞者”的原因吗？}
{111}{}{听说你喜欢虐待儿童，是真的吗？}
{112}{}{你想看看什么叫不明智吗？顶撞我就是不明智，臭娘们！}
{113}{}{你为什么说话这么奇怪？}
{114}{}{你为什么来，见习者？你知道我不喜欢被打扰。}
{115}{}{请原谅我，神父，但我心烦意乱。}
{116}{}{我寻求大教堂的指引。}
{117}{}{我来谈谈你对待儿童的方式。}
{118}{}{我只是想聊聊。}
{119}{}{你那根棍子不错！这就是他们叫你鞭笞者的原因吗？}
{120}{}{你想永远不被打扰吗？我可以安排！}
{121}{}{我不知道。我为什么来？你知道吗？}
{122}{}{你竟敢手持武器进入我的圣地！蠢货！滚出去！}
{123}{}{你以为你是谁，竟敢持武器进入我的圣所。滚出去！}
{124}{}{请原谅我，先生。但黑暗势力无处不在，谁也不知道何时需要自卫。}
{125}{}{我寻求大教堂的指引。}
{126}{}{我来谈谈你对待儿童的方式。}
{127}{}{我只是想聊聊。}
{128}{}{你那根棍子不错！这就是他们叫你鞭笞者的原因吗？}
{129}{}{你不喜欢武器出鞘。你会更讨厌我接下来的动作！}
{130}{}{出去？哪边是出口？}
{131}{}{未经神圣仪式的人不得进入我的房间。我必须请你立刻离开。}
{132}{}{请原谅我的冒昧，但我有重要的问题要问。}
{133}{}{我来这里是要谈谈你对儿童们的对待。}
{134}{}{我想问问关于神圣仪式的事情。}
{135}{}{你的长棍真不错！这就是为什么他们叫你Lasher吗？}
{136}{}{这地方看起来不像是神圣的。我还没在这杀过人呢。}
{137}{}{你这个蠢货！我可是经过不少神圣仪式的。}
{138}{}{那是仅由最忠诚的信徒才能获得的特权。只有洗礼比它更为崇高。}
{139}{}{那要如何才能获得洗礼呢？}
{140}{}{我想你是在教导那些孩子并为他们准备洗礼。}
{141}{}{你能帮我接受洗礼吗？}
{142}{}{哇！你一定很特别！}
{143}{}{可惜特权在你死的时候连辐射蝎子尾巴都不值。}
{144}{}{我看没必要和傻瓜交谈。走开。}
{145}{}{你应该去找Morpheus神父。他在塔里，不过夜官是不太可能让你过去的。}
{146}{}{你能说服夜官让我过去吗？}
{147}{}{能告诉我Morpheus的情况吗？}
{148}{}{能告诉我关于夜官的事吗？}
{149}{}{谢谢您，先生。}
{150}{}{我自有办法解决这类问题。}
{151}{}{这长棍是圣器，通过它我可以指导我的学生。痛苦能清除邪念，使他们更好地理解主的荣耀。}
{152}{}{原来如此，是说主就是个痛苦吗？}
{153}{}{对孩子们这么做太可怕了！}
{154}{}{听起来挺刺激的。来试试看对我怎么样？}
{155}{}{我教导这些孩子。这是我的责任。所有孩子都是邪恶的野兽。我必须迫使他们进化为人类。也许你听说过我不容许嬉戏玩乐，没错。我希望他们尽可能多受苦。}
{156}{}{那么变种人比人类更进化吗？}
{157}{}{你这个没良心的混蛋！}
{158}{}{你根本没泡到过妞吧？}
{159}{}{多告诉我些你的教学方法吧。}
{160}{}{但杀戮的快感呢？难道不允许吗？}
{161}{}{你这个肮脏无脑的怪物！竟敢亵渎我的存在！滚出去！出去！现在！}
{162}{}{你是个女人，因此你总是烦恼。这是你们这一类的普遍状况。告诉我你的问题，女士，我会为你解决。}
{163}{}{如果你的心中没有那么多邪恶，先生，你就会心安。正直的心灵无忧无虑。告诉我你的问题，但要快！}
{164}{}{告诉我如何达到正直！}
{165}{}{我想了解更多关于大教堂的事情。}
{166}{}{我想了解关于主宰者的事情。}
{167}{}{你还活着。这就是我的问题，你这个混蛋！}
{168}{}{学会将痛苦视为你最亲密的朋友，因为痛苦是宇宙中最具教育意义的力量。打破自我，直到你不再作为个体存在，然后重塑自己为主宰者的工具。这就是你所有问题的解决之道。}
{169}{}{那么我在哪里可以找到最大的痛苦？}
{170}{}{是的，我想受够脑损伤以至于加入僵尸邪教！继续做梦吧，伙计！}
{171}{}{我从未想到过这一点！}
{172}{}{是吗？那真糟糕，伙计！}
{173}{}{我已经拥抱痛苦了。我只是喜欢和朋友分享。}
{174}{}{野兽无意义地喋喋不休。人类先思考，然后再说话。你必须进化为人类，我才愿意与你交谈。走开。}
{175}{}{你的话很有道理。好吧，我会帮助你。但要快。}
{176}{}{我必须见摩菲斯神父，有紧急事情。}
{177}{}{告诉我关于大教堂的事情。}
{178}{}{我想知道主宰者在哪里。}
{179}{}{我想知道关于孩子们的事情。}
{180}{}{我知道唯一快的事情就是死亡。}
{181}{}{总有一天你必须自己找到生命问题的答案，而那一天就是现在。走开！}
{182}{}{这不是我的职责。现在走开。}
{183}{}{通过忍受痛苦，通过获取智慧，通过服务的表现。痛苦是知识，智慧是服从，服务是勇气。}
{184}{}{[更多]}
{185}{}{你必须拒绝几乎摧毁我们所有人的光明，并承诺自己投入所有人平等的黑暗。现在我告诉了你这件事，去寻找它吧。寻找主宰者及其智慧。}
{186}{}{我没有咨询过他，但我确信他对我带给他的正直灵魂感到满意。这是艰难的工作，但我做得很好。不幸的是，这也非常耗时，所以我必须命令你现在离开。}
{187}{}{谄媚者的舌头在魔鬼的嘴里！像你这样的魔鬼！从我眼前消失！}
{188}{}{你这满嘴污言的畜生！走开！学点礼貌再回来。}
{189}{}{合理的请求。拿着这个标志。当你想通过时，把它给夜行者看。}
{190}{}{我帮不了你。走吧。}
{191}{}{他是我们的领袖，接近大师的顾问，了解他的许多目的。就这些吗？}
{192}{}{你能说服夜行者让我通过吗？}
{193}{}{告诉我更多关于莫菲斯的事？}
{194}{}{你能告诉我关于夜行者的什么？}
{195}{}{谢谢您，先生。}
{196}{}{那你为什么要追随这个莫菲斯呢？}
{197}{}{他们为大师服务，带来治愈的痛苦。夜之天使，通过流血来拯救世界。好奇心是愚蠢的情感，尤其是对夜行者而言。这是你唯一的警告。我现在有很多事要做。走吧。}
{198}{}{你的礼貌值得称赞。也许你有资格与莫菲斯交谈。如果夜行者拦住你，给他们看这个标志。现在，走吧！}
{199}{}{如果你认为小小的诡计能打败夜行者，那你就是个傻瓜。离开这里！}
{200}{}{颓废和安逸阻碍了进化，而进化在这个残酷的世界中是生存所必需的。幸运的是，我是一个不为诱惑所动的人。我看你不同意我。我不在乎你的意见。离开这里！}
{201}{}{变异并不可怕。每一次出生都是我们父母DNA的变异。我们都是变种人。唯一重要的是变种人是否在道德和有益的道路上被引导。这是我的工作。这也结束了我们的讨论。现在离开我。}
{202}{}{我施加痛苦。如果动物值得并能从中学习，它就会进化成正义的灵魂。如果不能，它就不配存在。偶尔，动物会被从基因池中移除，尽管没有我希望的那么频繁。这在失败的成长期动物中更常见。}
{203}{}{大师认可这种教学方法吗？}
{204}{}{你是个怪物！}
{205}{}{我想我该走了。}
{206}{}{你教成人吗？}
{207}{}{成长期动物？}
{208}{}{嘿，我可以帮你清除他们！没人会知道的！}
{209}{}{你是个邪恶的女孩。你最好小心行事。夜行者不喜欢竞争对手。现在走吧！}
{210}{}{你是个邪恶的男人。你最好小心行事。夜行者不喜欢竞争对手。现在走吧！}
{211}{}{正义通过斗争、创伤和恢复来实现。我们是必须不断被打破的动物，直到我们毫不犹豫地接受大师的真理。既然你已经听到了真相，就用你的经历去追寻它。离开这里。}
{212}{}{你的舌头是邪恶的东西，无法救赎。离开我的视线！}
{213}{}{大教堂教授了许多无纪律的头脑无法理解的东西。现在我有其他职责要履行。走吧！}
{214}{}{我也是。看来我们有很多共同点，但不幸的是，你让我无法忍受。离开这里。现在。}
{215}{}{这不是我该评判的。你必须说服夜行者。祝你好运。你会需要的。}
{216}{}{大教堂是人类的避难所。当末日降临这个邪恶的城市时，大教堂幸免于难，从而诞生了大师。因此，一个治愈的黑暗从可怕的光明中出现。}
{217}{}{当我来到这里时，我看到这个地方缺乏道德中心，所以我努力在一个曾经被闲散享乐吞噬的地方施加教学的痛苦。这就是你需要知道的全部。}
{218}{}{据说大师在下方等待，在黑暗中，因为上方的光明背叛了人类，几乎毁灭了我们。但许多人祝福光明，因为他们说它孕育了大师。}
{219}{}{我不确定这些事情，我也从未有幸见到他。现在如果你能原谅我，我还有工作要做。}
{220}{}{你本来就不太受欢迎。走了也好。}
{221}{}{我曾经是的，但许多方法被放弃，转而采用你在礼堂听到的那些嘈杂声。这让我感到苦涩。幸运的是，我仍然可以教导孩子们。现在请原谅，我得准备他们的课程了。}
{222}{}{呃，这当然是罕见的事件，动物会被给予每一个进化的机会。现在离开这里！立刻离开！}
{223}{}{[完成]}
{224}{}{这可能对你有用。拿着这个标志。当你想通过时，把它给夜行者看。它会让你见到摩菲斯神父。}
