{100}{}{你看到一个看起来鬼鬼祟祟的人。}
{101}{}{嘘！过来这边。}
{102}{}{那么，你在集市区干什么呢？}
{103}{}{我觉得这不关你的事。}
{104}{}{为什么？}
{105}{}{找我需要的东西。}
{106}{}{我妈妈在哪儿？！}
{107}{}{不太清楚，大块头。我们改天见。}
{108}{}{啊。}
{109}{}{我无所谓。只是看看能不能友好一点而已。[莱米转身离开]}
{110}{}{嗯，你看起来像个生意人。我也是个生意人，我想我们可以，呃，谈谈生意。}
{111}{}{那么，你在这里做什么？}
{112}{}{我想我要给你点“教训”！}
{113}{}{我不想和你的“生意”有任何关系。}
{114}{}{嗯，我们都有需求。我或许能帮你解决一些。那么你有什么需求呢？}
{115}{}{嗯，我真的在找一个水芯片。我需要把它带回去给我的族人。}
{116}{}{需求，是吧？我理解需求，但你知道怎么满足这些需求吗？}
{117}{}{我需要一些信息。}
{118}{}{我肯定不需要你说的那些东西。}
{119}{}{我做点这个，做点那个。我为人们找东西和信息，不管他们需要什么或者在找什么。}
{120}{}{嗯，我确实需要一些东西。}
{121}{}{有什么具体的可以告诉我吗？}
{122}{}{我在找一个水芯片。你不会刚好有一个吧？}
{123}{}{那我们下次见。}
{124}{}{水芯片，嗯……没听说过这种东西。如果我是你，我会去找水商。他们掌控着这里所有的水。}
{125}{}{那么你在这里做什么？}
{126}{}{那你还知道些什么呢？}
{127}{}{谢谢你的信息。}
{128}{}{不客气。如果你还需要什么，记得先来找莱米。}
{129}{}{所以，你在找信息，对吧？作为一个正经的生意人，我有开销，所以我需要一些瓶盖来告诉你你需要知道的东西。既然我们说清楚了，你想知道些什么？}
{130}{}{所以，你觉得我可能知道一些关于水芯片的事情，是吧？嗯，你可能是对的。不过，这可得花点钱。我想500瓶盖应该够了。}
{131}{}{好吧，信息是什么？}
{132}{}{我给你400怎么样。}
{133}{}{我觉得你现在就得告诉我，不用那些该死的瓶盖！}
{134}{}{这价格太高了。}
{135}{}{现在，现在。如果我以低于价值的价格给出信息，那我就不是我了。等你有瓶盖再来吧。}
{136}{}{想吓唬可怜的老莱米，是吧？好吧，我可不怕你这种人。我们以后再见吧。}
{137}{}{[莱米收下了你的钱]}
{138}{}{嗯，这也算公平。我就收下这个吧。}
{139}{}{好吧，好吧，好吧，看，我刚才只是开个玩笑，说要付钱买信息。好笑吧？}
{140}{}{好吧，我知道的关于水芯片的事情是，我听说它们都来自避难所。所以如果我是你，我会去找找其他避难所的位置。我不太确定所有避难所的具体位置，但我听说这附近大概有四个。}
{141}{}{我想再问你几个问题。}
{142}{}{谢谢。}
{143}{}{当然，你还想知道些什么？}
{144}{}{关于水芯片，你知道的能告诉我吗？}
{145}{}{你对德克知道些什么？}
{146}{}{你知道关于失踪商队的事情吗？}
{147}{}{嗯，我在找某种商品，你懂我的意思吧。}
{148}{}{现在没什么。}
{149}{}{通常我不介意卖信息，但关于德克先生的事情，你从莱米这儿是问不出什么的。}
{150}{}{好吧，但我能问你其他事情吗？}
{151}{}{谢谢。}
{152}{}{失踪的商队，是吧？嗯，我可能知道一些。这得花你300瓶盖。}
{153}{}{好吧，你知道些什么？}
{154}{}{我给你240。}
{155}{}{我觉得你现在就得告诉我，不用那些该死的瓶盖！}
{156}{}{这价格太高了。}
{157}{}{嗯，我不太确定，但我听说事情并不像大家想的那样。有个新人和一些变种人搅和在一起。不过别把这话传出去。}
{158}{}{果然。莱米，有什么是我可以引用的吗？}
{159}{}{我能再问你一个问题吗？}
{160}{}{谢谢。}
{161}{}{你可能在暗示Lemmy不是个正派的人。嗯，你说对了。不过Lemmy可是个活得好好的人。}
{162}{}{好吧，算了。我能再问你一个问题吗？}
{163}{}{好吧，我要让你变成一个躺着不动、没法呼吸的人！}
{164}{}{算了，再见。}
{165}{}{需要东西，是吧？我认识旧城区有个家伙，可能能帮你搞到那些东西。不过你知道吗？在你去找他之前，他得知道你是谁。}
{166}{}{让我猜猜，这个“邀请”要“花钱”吧？}
{167}{}{我知道你要说什么。我自己去找他。}
{168}{}{没错。所以我想……当然只对你……1000瓶盖，这样你就能跟他谈话，而不用担心他先把你脑袋打爆。}
{169}{}{好吧，我付你的价。}
{170}{}{800瓶盖怎么样？}
{171}{}{既然你这么喜欢我，Lemmy，为什么不免费帮我呢？[你展示了一下肌肉]}
{172}{}{我付不起。}
{173}{}{你要做的就是找到去旧城区的路。那里有个叫Vance的家伙。跟他说话。就像我说的，我会通知他你要去。}
{174}{}{你真是个好心人。我能再问你几个问题吗？}
{175}{}{谢谢。}
{176}{}{抱歉，伙计，我有事要忙。不过和你聊天很愉快。}
{177}{}{哦，你回来找你的老朋友Lemmy了，嗯？我能帮你什么忙？}
{178}{}{嗯，你看起来像个生意人。而我也是做生意的，所以我想我们可以，呃，谈谈，呃，生意。}
