{100}{}{你看到一个农民。}
{101}{}{哦，是啊，大人物被一只可怕的狗吓得跑了。菲尔，你真是给它好好上了一课。没错，你确实做到了。}
{102}{}{菲尔，你在干什么？你是在检查那些运动鞋的鞋底吧？}
{103}{}{伙计，那只狗看起来很饿。它肯定想活生生地吃掉你，菲尔。}
{104}{}{对于一个可怜无辜的动物来说，这可能有点过头了，你不觉得吗？}
{105}{}{你那条狗真不错。}
{106}{}{如果你能帮菲尔解决掉他的狗，我相信他会很感激的。}
{107}{}{谢谢你处理掉那只狗。}
{108}{}{你看到莱诺尔。}
