{100}{}{你看到一个食尸鬼哨兵。}
{101}{}{我现在不能说话。我在警戒危险。}
{102}{}{一个人类间谍！}
{103}{}{你在这里干什么？}
{104}{}{嗯，没什么。你在干什么？}
{105}{}{我在四处看看。}
{106}{}{哦。}
{107}{}{为什么，没什么。我住在这里。}
{108}{}{你在这里找不到任何东西。走开。}
{109}{}{[完成]}
{200}{}{没有水我们无法生存。}
{201}{}{请在离开前和我们的领袖谈谈。}
