{100}{}{你看到洛伦佐。}
{101}{}{先生，这是个体面的地方。我们不和你这种人做生意。走开。}
{102}{}{女士，这是个体面的地方。我们不和你这种人做生意。走开。}
{103}{}{你的贷款已经逾期。请现在就还款，否则我会很不高兴。我不喜欢不高兴。}
{104}{}{别威胁我，伙计。你不是唯一有朋友的人。}
{105}{}{我需要更多时间。求你了！}
{106}{}{我想偿还我的贷款}
{107}{}{美元。}
{108}{}{我身上没带。}
{109}{}{你好。你是来还贷款的吗？}
{110}{}{其实我希望你能分享一些信息}
{111}{}{我来是为了再借一笔贷款。}
{112}{}{也许以后吧。}
{113}{}{兰克？}
{114}{}{我警告过你别再来这里。好了，伙计们，你们知道该怎么做！}
{115}{}{哦，这不是潜在的客户吗！我是慷慨的洛伦佐，为您服务。我提供贷款。每天只收百分之十的利息，最多十天还清。你在中心城找不到比这更慷慨的借贷机构了！}
{116}{}{我来借一笔贷款。}
{117}{}{听起来你像个骗子！}
{118}{}{嗯，我想是的。你想了解什么？}
{119}{}{那些失踪的商队怎么回事？}
{120}{}{告诉我关于德克的事。}
{121}{}{当地警察怎么样？}
{122}{}{大教堂的信徒怎么样？}
{123}{}{告诉我关于你自己的事。}
{124}{}{在这里哪里可以找到工作？}
{125}{}{抱歉。我不传谣言。别再问我了。}
{126}{}{我警告过你我不传谣言。如果你以为我只是随便说说，那你错了。滚出去，别再回来，小子。}
{127}{}{抱歉，伙计，但我一次只做一笔贷款。你想要更多，就得开始还款。这是生意，不是慈善。}
{128}{}{好的。很高兴和你做生意。还有别的事吗？}
{129}{}{笨蛋！你没有足够的钱来还清！也许你在想别的什么}
{130}{}{其实我希望你能分享一些信息}
{131}{}{我来是想再借一笔钱。}
{132}{}{也许以后吧。}
{133}{}{当然！随时欢迎光临。我们总是乐于助人。}
{134}{}{你还是去别的地方晃悠吧。滚出去！别再回来。}
{135}{}{嘿，别威胁人！我们这里都是文明人。Guido，Leone，给这位先生展示一下我们的文明。}
{136}{}{嘿，别威胁人！我们这里都是文明人。Guido，Leone，给这位女士展示一下我们的文明。}
{137}{}{时间到了，伙计。Guido，Leone，你们俩给我表演一下吧。}
{138}{}{你运气不错，朋友。}
{139}{}{其实我希望你能分享一些信息}
{140}{}{我想再借一笔钱。}
{141}{}{也许以后吧。}
{142}{}{你不够钱！竟敢骗我！Guido，Leone，把这个失败者埋了。}
{143}{}{好吧。你在我们这里没有未还的贷款。我们以200 Hub Bucks为单位放贷，最高可达1000 Hub Bucks。不过记住，在你证明能偿还小额贷款之前，我不会借给你大笔钱。}
{144}{}{我想要}
{145}{}{1000}
{146}{}{800}
{147}{}{600}
{148}{}{400}
{149}{}{200}
{150}{}{中心币。}
{151}{}{我还是不借了。}
{152}{}{Guido，Leone，给他看看什么叫撕票。先从他的胳膊开始。}
{153}{}{抱歉，伙计，但傻子风险太大。滚出去。}
{154}{}{死亡爪。一定是死亡爪。现在谁都不安全了！}
{155}{}{关于死亡爪呢？}
{156}{}{告诉我关于Decker的事。}
{157}{}{本地警察怎么样？}
{158}{}{大教堂的孩子们怎么样？}
{159}{}{告诉我你的事。}
{160}{}{在这里哪里可以找到工作？}
{161}{}{他是个很棒的人。是偿还我贷款的好工作来源。告诉他是我介绍的，你可能会得到额外奖励！}
{162}{}{那些失踪的商队怎么样了？}
{163}{}{奖励？你是什么意思？}
{164}{}{本地警察怎么样？}
{165}{}{大教堂的孩子们怎么样？}
{166}{}{告诉我关于你自己的事情。}
{167}{}{在这里哪里可以找到工作？}
{168}{}{他们是好人！虽然偶尔有点误会，但我觉得他们对他们的物种是个荣耀 [小声] 不管他们是哪种物种}
{169}{}{那些失踪的商队怎么样了？}
{170}{}{告诉我关于德克的事情。}
{171}{}{误会？比如说什么？}
{172}{}{大教堂的孩子们怎么样？}
{173}{}{告诉我关于你自己的事情。}
{174}{}{在这里哪里可以找到工作？}
{175}{}{我不能说我印象太深。我经营的是一个诚实、受人尊敬的生意，他们却指责我是小偷！这些人的胆子真大。他们以为贫穷的誓言就能让他们有权评判我！}
{176}{}{那些失踪的商队怎么样了？}
{177}{}{告诉我关于德克的事情。}
{178}{}{本地警察怎么样？}
{179}{}{贫穷的誓言？}
{180}{}{告诉我关于你自己的事情。}
{181}{}{在这里哪里可以找到工作？}
{182}{}{我只是一个受人尊敬的商人，仅此而已。我们乔瓦尼家族自大灾变前就是受人尊敬的商人，这就是传统！}
{183}{}{那些失踪的商队怎么样了？}
{184}{}{告诉我关于德克的事情。}
{185}{}{本地警察怎么样？}
{186}{}{大教堂的孩子们怎么样？}
{187}{}{你认为的尊敬是什么？}
{188}{}{在这里哪里可以找到工作？}
{189}{}{你应该去找德克先生。刺激的工作，价格实惠！镇上最好的！而且他就在街对面！没有比这更方便的了！}
{190}{}{那些失踪的商队怎么样了？}
{191}{}{告诉我关于德克的事。}
{192}{}{当地警察怎么样？}
{193}{}{大教堂的孩子们怎么样？}
{194}{}{告诉我关于你自己的事。}
{195}{}{有什么刺激的事？}
{196}{}{算了，你的信用风险太大了。滚出我的视线，别再回来。}
{197}{}{好吧。一千块。你有十天时间还清。}
{198}{}{好吧。八百块。你有十天时间还清。}
{199}{}{好吧。六百块。你有十天时间还清。}
{200}{}{好吧。四百块。你有十天时间还清。}
{201}{}{好吧。两百块。你有十天时间还清。}
{202}{}{真遗憾。欢迎以后再来使用我们的服务。}
{203}{}{伙计，他们说的关于那东西的故事，真是，太有意思了！}
{204}{}{告诉我关于德克的事。}
{205}{}{当地警察怎么样？}
{206}{}{大教堂的孩子们怎么样？}
{207}{}{告诉我关于你自己的事。}
{208}{}{在这里哪里能找到工作？}
{209}{}{好吧，再见！}
{210}{}{也许没有奖金。但他是个好人，相信我！}
{211}{}{那些失踪的商队怎么样了？}
{212}{}{当地警察怎么样？}
{213}{}{大教堂的孩子们怎么样？}
{214}{}{告诉我关于你自己的事。}
{215}{}{在这里哪里能找到工作？}
{216}{}{好吧，再见！}
{217}{}{你能相信有人指控我敲诈吗？幸好，我的好朋友德克帮我澄清了！}
{218}{}{那些失踪的商队怎么样了？}
{219}{}{告诉我关于德克的事。}
{220}{}{大教堂的孩子们怎么样？}
{221}{}{告诉我关于你自己的事。}
{222}{}{在这里哪里可以找到工作？}
{223}{}{好吧，再见！}
{224}{}{我敢打赌他们的领袖，那个叫莫菲斯的家伙，他可不穷！不，先生！我敢打赌在废城，他过得可滋润了！}
{225}{}{那些失踪的商队怎么回事？}
{226}{}{告诉我关于德克的事。}
{227}{}{本地警察怎么样？}
{228}{}{告诉我关于你自己的事。}
{229}{}{在这里哪里可以找到工作？}
{230}{}{好吧，再见！}
{231}{}{你不尊重我们，就会受伤。一个人还能要求多少尊重呢？}
{232}{}{那些失踪的商队怎么回事？}
{233}{}{告诉我关于德克的事。}
{234}{}{本地警察怎么样？}
{235}{}{大教堂的孩子们怎么样？}
{236}{}{在这里哪里可以找到工作？}
{237}{}{好吧，再见！}
{238}{}{冒险，危险。你真的可以大赚一笔！}
{239}{}{那些失踪的商队怎么回事？}
{240}{}{告诉我关于德克的事。}
{241}{}{本地警察怎么样？}
{242}{}{大教堂的孩子们怎么样？}
{243}{}{告诉我关于你自己的事。}
{244}{}{好吧，再见！}
{245}{}{再见，伙计！}
{246}{}{嘿，嘿，嘿……把你的手从那扇门上拿开，怪胎！}
{247}{}{就是这样，怪胎！你会为此付出代价！}
{248}{}{抱歉，我没有时间。如果你不能支付全款，就把你有的钱给我，我们的业务关系将被永久终止。}
{249}{}{好吧，行。你可以拿走我所有的瓶盖。}
{250}{}{哦！我刚想起来！我刚好有足够的钱来还清这笔贷款！}
{251}{}{[试图用}
{252}{}{瓶盖]来糊弄洛伦佐]}
{253}{}{算了！我一瓶盖也不会给你。}
{254}{}{[你把所有的瓶盖都给了洛伦佐]}
{255}{}{[你给了洛伦佐}
{256}{}{瓶盖]}
{257}{}{你满嘴胡说！你一直在隐瞒我！我要把钱从你身上打出来！}
{258}{}{真可惜。我想我们只能把一些瓶盖放进你身体里了。圭多！莱昂！}
{259}{}{好吧。我想这只能勉强接受。你知道我再也不会和你做生意了吧？如果我再看到你，我会被迫对你施加更严厉的惩罚。}
{260}{}{你让我恶心。把钱给我，然后滚！别让我再看到你！}
{261}{}{你钱不够！}
