{100}{}{你看到一个疯狂的科学家。他正在专心致志地研究某个东西。}
{101}{}{晚上好，兄弟。是什么风把你吹到我们这片小天堂的?}
{102}{}{晚上好，姐妹。是什么风把你吹到我们这片小天堂的?}
{103}{}{我来看看你的进展。}
{104}{}{你在这里做什么?}
{105}{}{什么?! 你竟敢质疑我? 要不要我在你的脑子上做个实验，你这扭曲的家伙?!}
{106}{}{呃。}
{107}{}{又是你? 这次你又为什么来打扰主宰的光辉未来?}
{108}{}{主宰对你的失败越来越不耐烦，我对你的无礼也是!}
{109}{}{我想知道你的实验进展如何。}
{110}{}{够了，我现在就要终结你的未来，蠢货!}
{111}{}{哎哟!}
{112}{}{情况不太好。我一直在直接将FEV注入松果体，但没有得到我期望的结果。}
{113}{}{为什么不试着直接注入杏仁核?}
{114}{}{为什么不试着注入延髓?}
{115}{}{你得到了什么结果?}
{116}{}{嗯。然后呢?}
{117}{}{请原谅我，先生。我能为您效劳吗?}
{118}{}{请原谅我，女士。我能为您效劳吗?}
{119}{}{下次请用尊重的态度和我说话，否则你将再也无法和任何人说话!}
{120}{}{主宰的真理被揭示，导致心灵能力增强。[摇头] 但这些可怜的灵魂变得极度疯狂，必须被隔离和消除，以防止他们伤害自己或他人。}
{121}{}{哦，你真是体贴...}
{122}{}{他们被关在哪里?}
{123}{}{你这个无情的屠夫! 我想我会消除你的大脑并把它从你的身体里隔离出来! 去死吧，你这个混蛋!}
{124}{}{在这里西北方向的一个房间里。我还能帮你什么吗?}
{125}{}{谢谢你的帮助。再见。}
{126}{}{嗯，FEV是什么?}
{127}{}{你可以去死!}
{128}{}{我没时间跟你胡闹!}
{129}{}{多么有趣的主意! 我必须立刻试试!}
{130}{}{呃，你们把失败的实验品放在哪儿了？}
{131}{}{不用客气。}
{132}{}{好啊！我们来试试用在你身上！}
{133}{}{文森特！准备好我们的新志愿者！}
{134}{}{什么？这是我听过的最荒谬的事！[怀疑地看着你] 你到底是谁？}
{135}{}{哦，抱歉。我得走了。}
{136}{}{我是个新来的……呃……人……我被派来看看你们的工作进展。}
{137}{}{我已经告诉过你了，我是被主人派来检查你们的。}
{138}{}{我来是为了摘除你的脾脏……不用麻醉！}
{139}{}{好吧。那么进展如何？}
{140}{}{你的态度已经告诉了我一切。再见。}
{141}{}{啊哈！果然是个入侵者！正如我所料。文森特！}
{142}{}{你是谁？为什么穿着那套衣服？[自言自语] 我很久没见过这种衣服了。}
{143}{}{我在伪装。入侵者已经潜入了主人的圣地，我穿成这样是为了取得他们的信任。}
{144}{}{你竟敢质疑主人的特工！}
{145}{}{你什么时候见过这样的衣服？}
{146}{}{这是挤压成型的橡胶，所以在我杀了你之后很容易擦掉你的血！}
{147}{}{哦，你知道的，当我们收到最后一批纯种人类时……我想还有一个在拘留室。你为什么问？}
{148}{}{没什么。实验进展如何？}
{149}{}{我得向主人汇报。我没时间和你废话。}
{150}{}{[摇头] 唉，那些可怜的灵魂变得极度疯狂，必须被隔离和消除，以防他们伤害自己或他人。}
{151}{}{哦，你真是太体贴了……}
{152}{}{你这个无情的混蛋！我想我会消除你的大脑，并把它从你的身体里隔离出来！去死吧，你这个混蛋！}
{200}{}{你看到文森特，一个超级变种人守卫。他看起来很无聊。}
{201}{}{你看到一个超级变种人，显然在守护科学家。他看起来很无聊。}
{202}{}{入侵者！}
{203}{}{我只是看着这些疯子。别跟我说话。}
{204}{}{别烦我。}
{300}{}{你看到一个正在睡觉的疯科学家。}
{301}{}{Zzzzzz}
{302}{}{嗯！什么？[揉眼睛] 文森特，把这个异教徒赶出我们的房间！}
{303}{}{嗯？[打鼾] ...zzzzzzzzz}
{400}{}{你看到文森特。他正在守护沉睡的疯子。}
{401}{}{你看到一个超级变种人守卫。他几乎站在躺着的身体上。}
{402}{}{别打扰他们，快出去。没人允许在他们睡觉时进来。}
{403}{}{又是你！我告诉过你不要打扰科学家！}
{404}{}{你已经待得太久了。}
