{100}{}{你看到玛塞尔。}
{101}{}{你看到一个看起来很强悍的女人。}
{102}{}{谢天谢地你来了！有个疯子把辛西亚劫持了，他威胁要杀了她！你必须帮忙。}
{103}{}{别烦我。}
{104}{}{嗯，我去看看。}
{105}{}{该死！}
{106}{}{哦，天啊，希望你能做到。他在她的房间里。快去帮她！}
{107}{}{你真是个冷酷的人。没有你的帮助，她可能会死。}
{108}{}{没办法，这就是生活。}
{109}{}{好吧，别再唠叨了。我会去看看。}
{110}{}{帮帮辛西亚。她有麻烦了。}
{111}{}{谢谢你帮助了辛西亚。她平时不是个麻烦。你值得一个好觉。我请客。但别再要免费的了。}
{112}{}{哼，恶棍。}
{113}{}{谢谢。}
{114}{}{没问题。1号房。跟我来。}
{115}{}{享受你的住宿。别惹麻烦。}
{116}{}{你本该救辛西亚的。她的死是你的错。希望你对此感到满意。}
{117}{}{好吧，随便。}
{118}{}{哼。}
{119}{}{欢迎来到撞击旅馆。陌生人，我能帮你什么吗？}
{120}{}{我在找点水。}
{121}{}{我需要好好睡一觉。}
{122}{}{我在找点信息。}
{123}{}{哼。}
{124}{}{是的，我们也接待你这种人。住一晚25美元。一周150美元。}
{125}{}{不用了。}
{126}{}{好的。}
{127}{}{好的。一周。}
{128}{}{是的，你也是。祝你有个愉快的一天。}
{129}{}{好的，谢谢。你的房间是1号房。跟我来。别在里面开枪，好吗？}
{130}{}{祝您入住愉快。}
{131}{}{您需要一些钱才能租房间。}
{132}{}{那你应该去试试Skum Pitt。我听说那里的酒里水分很多。}
{133}{}{我不太清楚，不过我可以租房给你。这是个休息和疗伤的好地方。一天$25，或者一周$150。大多数人都选择按周租。如果你问我的话，也应该这样。}
{134}{}{好的，一周。}
{135}{}{就一晚。}
{136}{}{不用，谢谢。}
{137}{}{我只是个酒店经理，伙计。别问我太多。}
{138}{}{给你$50，告诉我你知道的。}
{139}{}{我知道你现在少了$50。我不搞八卦，好吗？想要房间再来找我。}
{140}{}{你以为我是傻子吗？如果要贿赂我，至少要有足够的钱。}
{141}{}{欢迎回来，我能为你做些什么？}
{142}{}{我想租个房间。}
{143}{}{嗯。}
{144}{}{你已经租了1号房间。要我带你去看看吗？}
{145}{}{当然。}
{146}{}{不用。}
{147}{}{是的。}
{148}{}{不。}
{149}{}{这仍然是你的房间。祝您入住愉快。}
{150}{}{你知道规矩。一天$25，一周$150。}
{151}{}{不。}
{152}{}{是的。}
{153}{}{好。}
{154}{}{当然。一天$25，或者一周$150。}
{155}{}{好的，一周。}
{156}{}{就一晚。}
{157}{}{不用，谢谢。}
{158}{}{好的，1号房间是你的了。祝您入住愉快。}
{159}{}{是的，你想要什么？}
{160}{}{我想租个房间。}
{161}{}{嗯。}
{162}{}{不行。走开。}
{163}{}{我不喜欢你的脸。我不打算租房给你。}
{164}{}{我真的需要一个地方住。}
{165}{}{不行。祝你晚上愉快。}
{166}{}{好吧。一晚100美元。}
{167}{}{什么！这太离谱了！}
{168}{}{好吧。}
{169}{}{就这样，要不要。}
{170}{}{不要。}
{171}{}{好吧。}
{172}{}{好的。给你。1号房。祝你晚上愉快，退房时间是11点。}
{173}{}{你杀了基利安，是不是？}
{174}{}{是的，确实是我。}
{175}{}{不，不是我。真的不是。}
{176}{}{嗯。}
{177}{}{滚出去！你太蠢了，根本不知道自己做了什么，但我的生活现在变成了地狱！}
{178}{}{你这个混蛋。我真不敢相信你杀了他。他是个好人，现在我麻烦不断……滚出去，别再回来。}
{179}{}{好吧，随你怎么说，但我听到的不是这样。你最好在这里老实点，否则我会拿出老贝茜，把霰弹枪塞进你屁股里。}
{180}{}{很晚了。我希望你不是在浪费我的时间。}
{181}{}{嘿！那个冰箱是给顾客用的！}
{182}{}{不用了，谢谢。}
{183}{}{马塞尔冲上去对抗袭击者！}
{184}{}{呃，没什么。算了。}
