{100}{}{你看到索隆医生，医学博士。}
{101}{}{你看到护士玛尼。}
{102}{}{你看到一位医生。}
{103}{}{你看到一位护士。}
{104}{}{欢迎光临。今天有什么可以帮您的吗？}
{105}{}{呃……}
{106}{}{我受伤了。你能帮我治疗吗？}
{107}{}{你能教我一些医学知识吗？}
{108}{}{是的，我看到你受了一些伤。这可能需要一些时间。你希望我帮你治疗伤口吗？}
{109}{}{嗯嗯。}
{110}{}{不不。}
{111}{}{是的，拜托了。}
{112}{}{不，谢谢。}
{113}{}{好了。这样应该可以了。请在外面多加小心。}
{114}{}{你很擅长这个。你能教我一些创伤护理吗？}
{115}{}{好的，谢谢。}
{116}{}{我可以教你一点，但需要几个小时。你愿意留下来吗？}
{117}{}{愿意。}
{118}{}{抱歉，太忙了。}
{119}{}{你是个很好的学生。我希望你能继续支持我们。再见。}
{120}{}{如你所愿。祝你好运。}
{121}{}{我可以教你一点，但不多。需要一些时间。你愿意留下来吗？}
{122}{}{愿意。}
{123}{}{抱歉，我没有多余的时间。}
{124}{}{你是个优秀的学生。祝你好运。}
{125}{}{暂时没有什么需要的，不过谢谢。}
