{100}{}{你看到超级变种人的主宰。}
{101}{Mast00}{So, what shall it be?  Do you join the Unity or do you die here?
 Join! Die! Join! Die!}
{102}{}{我无法获胜。我会加入你。}
{103}{}{如果你能证明你的统一是人类的最佳选择，那么我会帮助你。}
{104}{}{要不你死，然后我离开？}
{105}{}{哦，今天会有人死，但不是我。我有个计划。}
{106}{}{呃。李。}
{107}{Mast01}{Excellent. Your talents will be useful. But first, you must tell me
 everything about your Vault.}
{108}{}{为什么？}
{109}{}{好吧。我会告诉你你想知道的一切。}
{110}{Mast02}{I will conquer it and turn all those pure strain humans into mutants.
 They will give me the army I need to bring peace to the entire wasteland.}
{111}{}{抱歉，我不太喜欢这个计划。}
{112}{}{听起来很合理。我们就这么做吧。}
{113}{Mast03}{So be it. You've dug your own grave. Grave! Grave!}
{114}{Mast04}{I don't have to prove anything to you! Prove.}
{115}{}{你的自负要求你告诉我。所有反派都有这种奇怪的冲动去解释一切。}
{116}{}{除非你证明给我看，否则我无法知道你代表着最好的未来。}
{117}{Mast05}{Very demanding for one in your tenuous position. But I can respect
 your needs.}
{118}{}{那就告诉我。}
{119}{Mast06}{The Unity will bring about the master race. Master! Master!
 One able to survive, or even thrive, in the wasteland. As long as there are
 differences, we will tear ourselves apart fighting each other. We
 need one race. Race! Race! One goal. Goal! Goal! One people . . . to
 move forward to our destiny. Destiny.}
{120}{}{当然是指变种人这一族。}
{121}{}{我希望我们不会变得像你一样。}
{122}{Mast07}{Of course. Mutants are best equipped to deal with the world today.
 Who else? The ghouls. Please. Normals. They brought nuclear
 death to us all. This will be the age of mutants. Mutants.}
{123}{}{你的意思是把所有人都变成变种人。}
{124}{}{你真是个偏执狂。}
{125}{}{那些反对你的人怎么办？}
{126}{Mast08}{All that resist, yes. All those that are required for the
 Unity as well. The remainder will be allowed to live out their days,
 but under Unity control and protection. But none shall breed, for they
 will be the last of their race.}
{127}{}{你的宏图大计有个问题。}
{128}{}{听起来你已经掌控了一切。我会加入。}
{129}{}{我觉得你们都疯了，我现在就得阻止你们。}
{130}{Mast09}{And what is that?}
{131}{}{你没考虑到我！我现在就要阻止你！}
{132}{}{你不可能对抗整个世界。}
{133}{}{我知道你的变种人是无生育能力的。}
{134}{Mast10}{I'm not after the world, yet. When I turn your fellow vault-dwellers
 into mutants, my forces will be too strong for any to stand against!
 But don't worry, you won't care. Care! Care!}
{135}{Mast11}{Preposterous! The FEV-2 virus doesn't destroy the reproductive organs
 of those it mutates.}
{136}{}{也许病毒以前不会让人失去生育能力，但现在会。}
{137}{}{你有问过你的变种人吗？}
{138}{}{也许是因为那些额外的辐射。}
{139}{Mast12}{Do you have proof?}
{140}{}{当然，我有证据！就在这里……}
{141}{}{相信我，这确实发生了。}
{142}{}{去问问你自己的变种人。}
{143}{Mast13}{This proves nothing! You will pay for your insolence. Pay!}
{144}{}{我需要消化这些信息。请稍等。}
{145}{Mast14}{I must digest this information. One moment . . . I understand now.
 You made a clever forgery. You made this up to fool me. Fool! Me!}
{146}{}{什么！？我不明白，我以为这是正确的！}
{147}{}{你在撒谎！你在否认眼前的事实！}
{148}{Mast16}{You will pay for what you have done! Pay! Done.}
{149}{Mast17}{But it cannot be. This would mean that all my work has been for
 nothing. Everything that I have tried to . . . a failure!  It can't be.
 Be. Be. Be.}
{150}{}{抱歉，这对你来说不是一个选项。你们的种族将在这一代后灭绝。}
{151}{}{也许可以做些什么。或许你需要更多的测试对象。}
{152}{Mast18}{Yes. More subjects. I think I shall start with you. Do! Do!}
{153}{Mast19}{I . . . don't think that I can continue. Continue? To have done the
 things I have done in the name of progress and healing. It was
 madness. I can see that now. Madness. Madness? There is no hope.
 Leave now, leave while you still have hope . . .}
{154}{Mast20}{I believe I shall. Don't move.}
{155}{Mast21}{My scientists assure me that nothing is wrong.
 What do you say to that? Say! Say!}
{156}{}{你有没有想过问问女性变种人？}
{157}{}{去问问你的副官。}
{158}{}{他们害怕你。你觉得他们会告诉你真相吗？}
{159}{Mast22}{One moment. He cannot be reached. He must be dead and I can
 guess who killed him. Killed! Kill!}
{160}{Mast23}{He denies everything. And he says he knows who started
 this rumor . . .}
{161}{Mast24}{I think I know who the liar is. Liar!}
{162}{Mast25}{Reasonable. One moment. Are you sure? What about the other females?
 It cannot be. Be.}
{163}{}{抱歉，你们的种族注定灭亡。}
{164}{}{请原谅我得意忘形……我早就说过了！}
{165}{Mast26}{Without any proof, I'm afraid I can't believe you. Now, you will join
 my army as a mutant or you will die! Die! Join!}
{166}{}{死也比变成你这样好。}
{167}{}{这意味着放弃我所知道的一切，但我会加入。}
{168}{Mast27}{Your humor will not save you now. Do you accept my offer, or not? Not!
 Accept!}
{169}{}{不。}
{170}{}{好吧，总比死好……}
{171}{Mast28}{Radiation has no effect on us. The FEV virus makes us immune.
 Your argument is weak, and so are you.}
{172}{Mast29}{Oh, I think you are wrong. But just to be sure, I will order
 this matter researched. After I have taken care of you. Care. Care!}
{173}{Mast30}{My only problem is you. Now, will you work for the Unity, or not?}
{174}{}{不。}
{175}{}{当然。}
{176}{Mast31}{They will be punished for their insolence.}
{177}{}{你的意思是要杀光他们？}
{178}{}{那我现在必须阻止你！}
{179}{Mast32}{Of course not. Most will be offered a chance to become
 a mutant. Those who deny this opportunity will be sterilized and let go.
 Those that resist will be executed.}
{180}{}{你真是个病态的家伙。该让你安息了。}
{181}{}{嗯，我不太喜欢被处决……我加入。}
{182}{Mast33}{We are all biased, are we not?  We each care more about
 our individual communities than other people. We haven't changed, and
 I'll tell you something else . . .}
{183}{}{那是什么？}
{184}{Mast34}{We won't change. Not unless we are of one people. One. One. One. One
 race. One. One. One. The Unity will allow us to move beyond these
 petty concerns and deal with the major problems at hand.  You want to
 be a part of that, don't you? Part. Don't.}
{185}{}{你说服了我。我会加入统一体。}
{186}{}{我想要你的一部分……你的头！}
{187}{Mast35}{Of course! The mutants will survive! The mutants will rebuild this
 world! And only as a mutant, will you be allowed to live! Live. Die!}
{188}{}{活下去！}
{189}{}{去死吧！}
{190}{}{你只关心你的变种人和他们的统一体。}
{191}{Mast36}{I am no villain. You have no idea what I, or the Unity is about.}
{192}{}{那就告诉我你的目的是什么。}
{193}{}{你是个恶棍。你只是在否认自己的内心感受。}
{194}{Mast37}{I don't have to prove myself to you. Using your logic, that must,
 prove I am not a villain. It would be a hopeless cause to explain it to you. }
{195}{Mast38}{Oh? Please, what sort of plan might that be?}
{196}{}{我要在这个避难所引爆核装置。它很快就会爆炸，把你们全部送入地狱！}
{197}{}{我会杀了你，那样你就很难继续下去了，对吧？}
{198}{}{我已经说服了钢铁兄弟会，如果我被抓住并且没有被释放，他们会来这里进攻。 他们随时可能出现。}
{199}{Mast39}{You might be telling the truth. It doesn't matter, but I will let
 you go for now.}
{200}{Mast40}{You are lying. It will be the last lie that you tell. }
{201}{Mast41}{One moment while I check out your story. You might be telling the
 truth. Guards! Take this human to the reactor core. Deal with the
 problem before it's too late.}
{202}{Mast42}{I doubt even the FEV will help you. Why am I talking? It's
 unlikely you even understand . . .}
{203}{Mast43}{You must be joking. }
{204}{Mast44}{My patience is almost at an end with you. Now, will you join the
 Unity or not? Join. Not!}
{205}{}{是的。}
{206}{}{不是。}
{207}{Mast45}{Fine. Then you can die here and now!}
{208}{Mast46}{You have disarmed the device. Excellent. Tell me, is there
 anything you wanted to say before I kill you?}
{209}{}{是的，我现在可以加入你们吗？}
{210}{}{即使死了，我看起来也比你好。}
{211}{Mast47}{No. No. No. No.}
{212}{Mast200}{I am the Master. I don't have to answer to you.}
{213}{Mast201}{I am not here to answer your questions. You are here to answer mine.}
{214}{Mast202}{Once I have the location of your vault, I will fulfill my destiny!
 Destiny! Destiny! Destiny!}
{215}{Mast203}{You think you can destroy me!? Destroy! Me?}
{300}{}{呃！}


# Master Tell-Me-Abouts generic response
{980}{Mast200}{I am the Master. I don't have to answer to you.}

#
# Master Tell-Me-Abouts
#


{1000}{}{统一}
{1001}{}{主宰者}
{1100}{Mast200}{I am the Master. I don't have to answer to you.}
{1101}{Mast201}{I am not here to answer your questions. You are here to answer mine.}
