{100}{}{你看到马克森将军。}
{101}{}{兄弟会的真正目的是什么？}
{102}{}{我猜你一定知道很多关于兄弟会的历史。}
{103}{}{听到什么好传闻了吗？}
{104}{}{我有一些信息要报告。}
{105}{}{就这样，谢谢。}
{106}{Gen_1}{Hello, youngster. Cabbot said you wanted to talk. Look I'm uh . . .
 I'm pretty stacked up right now, so I'll uh . . . I'll help you out as long
 as you don't start flappin' your gums too much. You know, outsiders are like that,
 always jawin' . . . Hehehe. Kinda like me, huh?}
{107}{}{外来者？你指的是什么？}
{108}{}{那我能问几个问题吗？}
{109}{Gen_2}{I can't. I just moderate these endless damn meetings. There's four Elders,
 and me, you see? I break up fights and tie votes. Now, if all four vote to pick our
 noses while an army rolls in here and kicks our collective butt, there's not a helluva
 lot I can do about it.}
{110}{}{哦，好吧。}
{111}{}{这真糟糕。你们为什么不采取行动呢？}
{112}{Gen_2a}{Tradition. It's hard to change our ways. Now, maybe if the Elders had some real info, they'd get off their brains and do something.}
{113}{Gen_3}{An Initiate not born here. You're the first Outsider we've let join in
 a long, long time. Well, near on twenty years now. }
{114}{}{为什么是我？}
{115}{}{我很荣幸。现在能问几个问题吗？}
{116}{Gen_4}{Because we need to do something. An army's gatherin', Hub-caravans are
 disappearin', and our scouts sure as hell ain't gettin' the job done.
 So the Elders actually did something once and figured the right
 Outsider might have something to offer. That Outsider is you... We hope.}
{117}{}{什么军队？}
{118}{}{那些失踪的商队怎么回事？}
{119}{}{嗯，我想我还有一些问题要问。}
{120}{}{侦察兵有什么问题？}
{121}{}{我有一些你可能感兴趣的信息。}
{122}{Gen_5}{When we heard about the missing caravans, we sent out a few
 scouts east and the north. The ones who went north never returned. One came
 back from the east. He talked about a score of strange beings, all muscle
 with burnin' eyes. The Elder's aren't doin' squat, but I'm getting ready
 just the same.}
{123}{}{二十人不算军队。你为什么担心？}
{124}{}{听起来你的人在太阳下晒太久了。}
{125}{}{我会尽力而为。}
{126}{}{他说过向东的具体位置吗？}
{127}{}{我有一些你可能感兴趣的信息。}
{128}{Gen_6}{They may or may not be good scouts, but don't question
 the truthfulness of my men. We can revoke your Initiate status at any time.}
{129}{}{听起来你们更需要我。}
{130}{}{抱歉。}
{131}{Gen_7}{That's it. I warned the Elders that bringin' in an Outsider could be trouble. (shouting aside) Guards! There's an Initiate here who needs some quiet time to discover some manners. }
{132}{Gen_8}{You're an Outsider, but I expect you to learn our ways. I'll be watching. Now, ask your questions. }
{133}{Gen_9}{Good. Anything else you need to ask? }
{134}{Gen_10}{Deep in the mountains. He couldn't be more specific.}
{135}{}{真遗憾。我能再问几个问题吗？}
{136}{}{那北边呢？}
{137}{}{请说。}
{138}{Gen_11a}{Yeah, Fire away.}
{139}{Gen_11b}{Sure.}
{140}{Gen_11c}{Shoot.}
{141}{Gen_12}{I got a gut feeling there's a small force in the east and
 a much bigger one in the north. The Elders are collecting dust because
 none of the scouts returned from the north. I can't do anything but watch.}
{142}{}{好吧，我会尽力而为。}
{143}{}{你们为什么不采取行动呢？}
{144}{}{我觉得这超出我的能力范围了。我退出。}
{145}{}{我有一些关于那件事的情报。}
{146}{Gen_13}{Well the Merchants from the Hub told us a bunch of caravans
 disappeared on their way up north. I think there's an army in the mountains,
 but the Elders, well, they don't want to act until they're sure. }
{147}{}{他们是在哪里失踪的？}
{148}{}{你不是大长老吗？为什么不采取行动？}
{149}{}{你什么都没做吗？}
{150}{}{我有一些关于那件事的情报。}
{151}{Gen_14}{The word I got was that the caravans disappeared around the
 southern tip of the mountains to the east. I imagine the Hub merchants can probably
 tell you more.}
{152}{}{谢谢。如果可以的话，我还有一些问题。}
{153}{}{谢谢。我们以后再聊。}
{154}{}{我有一些关于那件事的情报。}
{155}{Gen_15g}{See you around, Initiate. You're not so bad...for an Outsider.}
{156}{Gen_15n}{Goodbye, Initiate.}
{157}{Gen_15b}{Goodbye!}
{158}{Gen_16}{I grew up too isolated here. Can you imagine spending your whole life inside one small place, then having to go out into the world? }
{159}{}{嗯，事实上……}
{160}{}{看来我注定要成为你的侦察兵了。}
{161}{}{所以因为他们没能出来，我就得替你干脏活。算了吧。}
{162}{Gen_17}{Then you understand the problem. To survive, we need someone who knows the outside. Like you. }
{163}{}{好吧，我会去做的。}
{164}{}{我有自己的问题。算了。}
{165}{Gen_18}{Well . . . with what I guess is coming, we don't have time for anyone
 who's gonna . . . not contribute. Now, you either work with us, or you take a hike.}
{166}{}{如果你这么说的话，那我加入。}
{167}{}{看起来是个散步的好天气。}
{168}{Gen_19}{Your choice. Hope you can live with it. }
{169}{Gen_20}{What? It's who we are and what we live for. It's ideals. As you spend
 more time with us, hopefully, you'll understand.}
{170}{}{是啊，但你实际上做什么呢？}
{171}{}{我对此不太确定。}
{172}{Gen_21}{Our main goal is to survive. The Scribes copy old plans for weapons or design new ones, and the Knights make the guns from 'em. Most guns come from us.}
{173}{}{你把武器交易给枢纽？}
{174}{}{这就是你们的全部工作？}
{175}{}{有道理。我还有几个问题要问。}
{176}{Gen_22}{That's the way we get our supplies.}
{177}{}{好吧，我明白了。我还有几个问题要问。}
{178}{}{好的。不过我现在得走了。}
{179}{}{我对此不太确定。}
{180}{Gen_23}{All? It's damn important. It's critical to our survival.}
{181}{}{随便吧。我还有几个问题要问。}
{182}{}{是啊，不过这很愚蠢。}
{183}{}{好的，谢谢。不过我真的该走了。}
{184}{Gen_26}{Then you need to get sure. Because being unsure is bound to get you killed.}
{185}{}{我知道得越多，就越有把握。}
{186}{Gen_28}{Look I don't have time for a story that long right now. Here. All of us grew up on this. }
{187}{Gen_29n}{There's rumors concerning the missing caravans in the Hub, as well as the strange army brewing in the eastern mountains. }
{188}{}{好的。}
{189}{}{什么军队？}
{190}{}{那些失踪的商队怎么回事？}
{191}{}{我有一些关于那件事的信息。}
{192}{Gen_29b}{I don't take stock in rumors. }
{193}{Gen_30}{Ahh . . . Hello again, Initiate. Are things going well? }
{194}{}{还不错。我可以再问几个问题吗？}
{195}{}{其实，挺糟糕的。}
{196}{}{谢谢，不过我得走了。}
{197}{Gen_32}{I'm sorry we're not what you're used to but you could show a little self-discipline. }
{198}{}{抱歉。我可以再问几个问题吗？}
{199}{}{为什么？这个地方是个笑话吗？}
{200}{}{我得走了。再见。}
{201}{Gen_34}{What the hell do you want now? }
{202}{}{我想知道为什么这里由一个白痴负责。}
{203}{}{我需要再问几个问题。}
{204}{}{没事，谢谢。}
{205}{Gen_35}{Whaddya got? }
{206}{}{抱歉，其实我没有什么信息。}
{207}{}{中心城的商队被巨大的绿色变种人袭击了。他们正在集结一支军队。}
{208}{}{北方有一支大军，由一个叫“主宰”的人控制。}
{209}{Gen_36}{You've seen 'em? This might actually get the Elders to do something.
 I'm gonna get on this, thanks!}
{210}{Gen_38}{Uh . . . What's he plan to do with this . . . army of his? }
{211}{}{他计划接管兄弟会、中心城、废城……所有人。}
{212}{}{你打算为这些信息付多少钱？}
{213}{Gen_39}{Finally! Well this'll get the Elders  off their butts. We'll fortify the Fortress and surprise those damn mutants.}
{214}{}{不！你不明白。他们正在把人变成变种人，并将他们加入军队。}
{215}{}{好的。}
{216}{Gen_40}{So?}
{217}{}{所以，到他们到达这里时，他们将势不可挡。而且他们有像你们一样的先进武器。你们没有胜算。}
{218}{}{好吧，也许固守是对的。}
{219}{Gen_41}{So what's your alternative?}
{220}{}{帮我攻击主宰的基地。我知道它在哪里。}
{221}{Gen_42}{Hmmm. Not a bad plan. Tell you what, let me go try and beat it into the Elders. No guarantees, but I'll try.}
{222}{Gen_43}{Then get out. I have work to do.}
{223}{Gen_44}{Pretty interesting set of priorities and loyalties you got there.}
{224}{}{忠于我。500个中心城币。要么接受，要么放弃。}
{225}{}{哦……好吧，我告诉你。他计划接管所有人和一切。}
{226}{Gen_44a}{I'll take it. We need the information to save lives.}
{227}{}{很简单。他在把人类变成变种人，并且拥有先进武器。他计划接管一切。}
{228}{Gen_44b}{Well, if he does, hope you find a place to use your scripts.}
{229}{Gen_45}{Well, how about nothing! Guards, kick this fool out. By God!
 We'll defend the Brotherhood without your damn help.}
{230}{Gen_46}{What do you think you're doing? Put that down. Put it down now!}
{231}{Gen_47}{That's it. Guards! Take this idiot away!}
{232}{Gen_48}{Hey, hey, hey, hey! Hold on now. Stop that. Stop it right now!}
{233}{Gen_49}{Like I said...}
{234}{Gen_50}{I said...}
{235}{Gen_51}{I am not in the habit of repeating myself. So open your ears.}
{236}{Gen_52}{Look I told ya' already. It's not my fault if you didn't get it.}
{237}{Gen_52a}{That's where you are. You want the long version, go talk to Vree.}
{238}{Gen_52b}{Mathia's my assistant.}
{239}{Gen_53}{Oh, he's a good kid, even if he does want to be a Scribe.}
{240}{Gen_54}{Vree's the head Scribe.  She's usually in the Library, she always likes to talk. }
{241}{Gen_55}{We keep weapon specs and history there.}
{242}{Gen_56}{Rhombo's been here a long time. A bit stiff, but a helluva soldier.}
{243}{Gen_58}{Hehehe. A fine, handsome, upstanding man. The High Elder position is to mediate the meetings between the Elders. You see, two years ago I got talked into it. If I'd of known then...}
{244}{Gen_59}{Well you see there's four of them and that's about all they can ever agree on. They can't even agree if they want to piss, much less pick a pot to piss in.}
{245}{Gen_60}{Well that's what you are. Initiates train and learn to become knights or scribes.}
{246}{Gen_61}{Well, Scribes copy down the weapon specs. We've got information all the way back to
 my granddad. Sometimes a scribe comes up with a new idea for a weapon. Hehehe. Doesn't happen too often.
 They all answer to Vree.}
{247}{Gen_62}{The Knights make the weapons. And when he's good enough, a Knight can advance to become a Paladin and then an Elder and so forth. Right now Rhombus is the head of the Knights.}
{248}{Gen_63}{Paladins are in charge of all security and outside activities. I remember tradin' with the Hub, goin' on scouting missions for the Elders. Ah man, those ware a good times.}
{249}{Gen_64}{The Hub's down to the southeast. They trade us food and things for the weapons we make here. Now if you're ever down there, you talk to Butch Harris.}
{250}{Gen_65}{Butch is the head of the Far Go Traders. He's a little slimy, but he's not a total waste. Unlike those Water Merchants. Bunch of damn vultures, all of 'em.}
{251}{Gen_66}{They're the main ones we trade with. Not totally trustworthy, but not as bad as the others. }
{252}{Gen_67}{You can't trust them. A few years ago, they offered us Water for a huge stockpile of weapons. We told them no, and you know what they did? Sent in thieves to steal the weapons! We caught 'em, but the Elders voted down going to the Hub to teach the merchants a lesson.}
{253}{Gen_68}{Holo discs? Hmm? I haven't seen those in a while.}
{254}{Gen_69}{Vree has it someplace in the Library.}
{255}{Gen_70}{Roger Maxson huh? Well he led our people here in the great Exodus, started the Brotherhood from scratch. Quite a leader.}
{256}{Gen_71}{Well that was when my granddad, Roger Maxson, led his soldiers here and started the Brotherhood. He never mentioned where they came from, but it  doesn't really matter, 'cause...well, this is our home now.}
{257}{Gen_72}{Well I believe there's an army massing to the north and in the mountains to the east, but I don't have any way to prove it. The Elders, they won't even listen. }
{258}{Gen_73}{A bunch of religious whackos, if you ask me. I think their main church is in the Boneyard.}
{259}{Gen_75}{Well I don't know a lot. There's a bunch of gangs around there, as well as Adytum and the Children of the Cathedral. Not much else. It's pretty damn desolate.}
{260}{Gen_76}{Well, there's not much to tell. I never ran into any of them. I've heard they're a problem for the people of Adytum, though.}
{261}{Gen_77}{That's a settlement down in the Boneyard. I went there...oh...a long time ago. I was on a scouting mission for the Elders.}
{262}{Gen_78}{Oh. Just another stupid rumor. Some people say it's a huge fanged monster and others say it's a vampire.}
{263}{Gen_79}{Oh, I don't know anything about that.}
{264}{Gen_80}{What was that? No. I don't believe I've ever heard of it.}
{265}{Gen_81a}{Hell if I know.}
{266}{}{看到我很惊讶吗？怎么能让你一个人享受乐趣？}
{267}{}{你是怎么说服长老们的？}
{268}{Gen_82a}{Oh wasn't hard at all.  I just calmly explained the situation. And bingo here we are. Lead on, my friend.}
{269}{Gen_83}{What are you doing in here? This is for Elders.}
{270}{}{抱歉，我这就离开。}
{271}{}{我不在乎，我留下。}
{272}{Gen_84}{Good, now shut the door on the way out.}
{273}{Gen_84a}{I'm telling you, Do not interfere.}
{274}{Gen_85}{Ha! You forget. I used to teach this stuff.}
{275}{Gen_86}{Contrary to opinion, we don't want soldiers will no brains whatsoever.}
{276}{Gen_87}{Well, I suggest you talk to my assistant, Mathia, about that.}


{300}{}{也许你能告诉我？这里的每个人似乎都很紧张。就像你们准备要打仗，但没人知道对手是谁。}
{301}{}{你有没有关于商队失踪的线索？}
{302}{}{我会去北方侦查，然后汇报我发现的情况。}
{303}{}{给我500瓶盖，我就去看看北边发生了什么。}
{304}{}{给我1000瓶盖，我就去调查北方的情况。}
{305}{}{我不确定现在是否想参与其中。}
{306}{}{我能不能弄到一些更好的武器？}
{307}{}{先问几个问题。}
{308}{}{不，我会在查明情况后再见你。}
{309}{}{好的，再见。}
{310}{}{你怎么知道你的侦察兵没有逃跑？}
{311}{}{我想我遇到过你描述的这些生物。它们不容小觑。}
{312}{}{请原谅我。你认为失踪的原因是什么？}
{313}{}{去吧，撤销它。看看我在不在乎。}
{314}{}{抱歉，但现在上去太冒险了。}
{315}{}{好吧，我会去，但能先给我一些更好的武器吗？}
{316}{}{好的，我愿意为1000瓶盖去做。}
{317}{}{要么接受，要么放弃。}
{318}{}{算了。}
{319}{}{好吧，好吧，我免费去做。}
{320}{}{好的，我回来后再见。}
{321}{}{我找到了证据，正是这支军队导致了商队的失踪。这是一支变种人军队。你有充分的理由担心。他们看起来非常强大。}
{322}{}{显然需要有人去那里查看情况。}
{323}{}{仅凭“直觉”还不足以让我冒生命危险去那里。}
{324}{}{我认为我的生命是相当重要的优先事项。}
{325}{}{我只是觉得我还没准备好承担这个任务。}
{326}{}{我只忠于一个人。}
{327}{}{我可以。}
{328}{}{呃？}
{329}{}{为什么这里的每个人都显得紧张不安？每个人似乎都很紧张。就像你们在准备打仗，但没人知道对手是谁。}
{330}{}{我需要和你谈谈商队失踪的事。你对此有什么见解吗？}
{331}{}{算了。}
{332}{}{我需要问你几个问题。}
{333}{}{呃?}
{334}{}{我有一些关于北边地区的信息。}
{335}{}{我可以问你一些问题吗?}
{336}{}{没事。}
{337}{}{抱歉，我其实没有什么要说的。}
{338}{}{我看到了他们的基地，到处都是变种人。}
{339}{}{我看到了北方的变种人基地。他们追随一个叫做“主宰”的领袖。}
{340}{}{你不能在这件事上采取防守态度，Maxson。}
{341}{}{很明显，我们需要采取行动。最好是在变种人攻击我们之前先发制人。我们需要长老们的支持。}
{342}{}{我现在不太确定该怎么做。让我收集更多信息，然后再告诉你。}
{343}{}{他计划占领任何他能找到的人类聚居地。}
{344}{}{你能告诉我一些关于兄弟会的历史吗?}
{345}{}{兄弟会的主要目的是什么?}
{346}{}{谁是长老?}
{347}{}{你知道关于死亡爪的事情吗?}
{348}{}{没事。}
{349}{}{我可以再问一个问题吗?}
{350}{}{谢谢你。}
{351}{}{你获得了}
{352}{}{经验点数，因为侦查了北方地区。}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{353}{Gen_3}{An Initiate not born here. You're the first Outsider we've let join in
 a long, long time. Well, near on twenty years now. }
{354}{Gen_3}{An Initiate not born here. You're the first Outsider we've let join in
 a long, long time. Well, near on twenty years now. }
{355}{Gen_6}{They may or may not be good scouts, but don't question
 the truthfulness of my men. We can revoke your Initiate status at any time.}
{356}{Gen_6}{They may or may not be good scouts, but don't question
 the truthfulness of my men. We can revoke your Initiate status at any time.}
{357}{Gen_15n}{Goodbye, Initiate.}
{358}{Gen_15n}{Goodbye, Initiate.}
{359}{Gen_30}{Ahh . . . Hello again, Initiate. Are things going well? }
{360}{Gen_30}{Ahh . . . Hello again, Initiate. Are things going well? }

{400}{}{我去过北方的变种人基地。可以说，他们不再是威胁了。}


# General Maxson Tell-Me-Abouts generic responses
{980}{Gen_79}{Oh, I don't know anything about that.}
{981}{Gen_80}{What was that? No. I don't believe I've ever heard of it.}
{982}{Gen_81a}{Hell if I know.}

#
# General Maxson Tell-Me-Abouts
#


{1000}{}{兄弟会}
{1001}{}{玛西亚}
{1002}{}{卡博特}
{1003}{}{维里}
{1004}{}{图书馆}
{1005}{}{菱形}
{1006}{}{长老}
{1007}{}{长老们}
{1008}{}{新兵}
{1009}{}{抄写员}
{1010}{}{骑士}
{1011}{}{圣骑士}
{1012}{}{集散地}
{1013}{}{布奇}
{1014}{}{商队}
{1015}{}{商人}
{1016}{}{磁盘}
{1017}{}{玩家}
{1018}{}{罗杰}
{1019}{}{出埃及记}
{1020}{}{军队}
{1021}{}{大教堂}
{1022}{}{天使的}
{1023}{}{帮派}
{1024}{}{阿迪特姆}
{1025}{}{爪牙}
{1026}{}{哈里斯}
{1027}{}{马克森}
{1028}{}{天使}
{1029}{}{骨园}
{1030}{}{主宰}
{1031}{}{战争}
{1032}{}{商队}
{1033}{}{芯片}

{1100}{Gen_52a}{That's where you are. You want the long version, go talk to Vree.}
{1101}{Gen_52b}{Mathia's my assistant.}
{1102}{Gen_53}{Oh, he's a good kid, even if he does want to be a Scribe.}
{1103}{Gen_54}{Vree's the head Scribe.  She's usually in the Library, she always likes to talk. }
{1104}{Gen_55}{We keep weapon specs and history there.}
{1105}{Gen_56}{Rhombo's been here a long time. A bit stiff, but a helluva soldier.}
{1106}{Gen_58}{Hehehe. A fine, handsome, upstanding man. The High Elder position is to mediate the meetings between the Elders. You see, two years ago I got talked into it. If I'd of known then...}
{1107}{Gen_59}{Well you see there's four of them and that's about all they can ever agree on. They can't even agree if they want to piss, much less pick a pot to piss in.}
{1108}{Gen_60}{Well that's what you are. Initiates train and learn to become knights or scribes.}
{1109}{Gen_61}{Well, Scribes copy down the weapon specs. We've got information all the way back to
 my granddad. Sometimes a scribe comes up with a new idea for a weapon. Hehehe. Doesn't happen too often.
 They all answer to Vree.}
{1110}{Gen_62}{The Knights make the weapons. And when he's good enough, a Knight can advance to become a Paladin and then an Elder and so forth. Right now Rhombus is the head of the Knights.}
{1111}{Gen_63}{Paladins are in charge of all security and outside activities. I remember tradin' with the Hub, goin' on scouting missions for the Elders. Ah man, those ware a good times.}
{1112}{Gen_64}{The Hub's down to the southeast. They trade us food and things for the weapons we make here. Now if you're ever down there, you talk to Butch Harris.}
{1113}{Gen_65}{Butch is the head of the Far Go Traders. He's a little slimy, but he's not a total waste. Unlike those Water Merchants. Bunch of damn vultures, all of 'em.}
{1114}{Gen_66}{They're the main ones we trade with. Not totally trustworthy, but not as bad as the others. }
{1115}{Gen_67}{You want to hear about the Water Merchants. Hehehe, well you can't trust them. A few years ago, they offered us Water for a huge stockpile of weapons. We told them no, and you know what they did? Sent in thieves to steal the weapons! We caught 'em, but the Elders voted down going to the Hub to teach the merchants a lesson.}
{1116}{Gen_68}{Holo discs? Hmm? I haven't seen those in a while.}
{1117}{Gen_69}{Vree has it someplace in the Library.}
{1118}{Gen_70}{Roger Maxson huh? Well he led our people here in the great Exodus, started the Brotherhood from scratch. Quite a leader.}
{1119}{Gen_71}{Well that was when my granddad, Roger Maxson, led his soldiers here and started the Brotherhood. He never mentioned where they came from, but it  doesn't really matter, 'cause...well, this is our home now.}
{1120}{Gen_72}{Well I believe there's an army massing to the north and in the mountains to the east, but I don't have any way to prove it. The Elders, they won't even listen. }
{1121}{Gen_73}{A bunch of religious whackos, if you ask me. I think their main church is in the Boneyard.}
{1122}{Gen_75}{Well I don't know a lot. There's a bunch of gangs around there, as well as Adytum and the Children of the Cathedral. Not much else. It's pretty damn desolate.}
{1123}{Gen_76}{Well, there's not much to tell. I never ran into any of them. I've heard they're a problem for the people of Adytum, though.}
{1124}{Gen_77}{That's a settlement down in the Boneyard. I went there...oh...a long time ago. I was on a scouting mission for the Elders.}
{1125}{Gen_78}{Oh. Just another stupid rumor. Some people say it's a huge fanged monster and others say it's a vampire.}
{1126}{Gen_65}{Butch is the head of the Far Go Traders. He's a little slimy, but he's not a total waste. Unlike those Water Merchants. Bunch of damn vultures, all of 'em.}
{1127}{Gen_70}{Roger Maxson huh? Well he led our people here in the great Exodus, started the Brotherhood from scratch. Quite a leader.}
{1128}{Gen_75}{Well I don't know a lot. There's a bunch of gangs around there, as well as Adytum and the Children of the Cathedral. Not much else. It's pretty damn desolate.}
{1129}{Gen_75}{Well I don't know a lot. There's a bunch of gangs around there, as well as Adytum and the Children of the Cathedral. Not much else. It's pretty damn desolate.}
{1130}{Gen_80}{What was that? No. I don't believe I've ever heard of it.}
{1131}{Gen_71}{Well that was when my granddad, Roger Maxson, led his soldiers here and started the Brotherhood. He never mentioned where they came from, but it  doesn't really matter, 'cause...well, this is our home now.}
{1132}{Gen_65}{Butch is the head of the Far Go Traders. He's a little slimy, but he's not a total waste. Unlike those Water Merchants. Bunch of damn vultures, all of 'em.}
{1133}{Gen_81a}{Hell if I know.}