{100}{}{关闭}
{101}{}{关闭}
{102}{}{开启}
{103}{}{关闭}
{104}{}{剩余时间：}
{105}{}{ 秒。}
{106}{}{这是你被判定死亡的地方。}
{107}{}{开启}
{108}{}{剩余时间：}
{109}{}{ 秒。}
{110}{}{这是你被判定死亡的地方。}
{111}{}{剩余时间：}
{112}{}{ 秒。}
{113}{}{这是你被判定死亡的地方。}
