{100}{}{关闭}
{101}{}{剩余时间：}
{102}{}{ 秒。}
{103}{}{这里是你被判定为死亡的地方。}
{104}{}{关闭}
{105}{}{开启}
{106}{}{关闭}
{107}{}{剩余时间：}
{108}{}{ 秒。}
{109}{}{这里是你被判定为死亡的地方。}
{110}{}{剩余时间：}
{111}{}{ 秒。}
{112}{}{这里是你被判定为死亡的地方。}
