{100}{}{你想要什么？}
{101}{}{嘿，你要吃那只死老鼠吗？}
{102}{}{什么？}
{103}{}{你看到我的狗埃尔维斯了吗？它就在附近。}
{104}{}{嗨。}
{105}{}{啊啊啊！}
{106}{}{咕噜咕噜！}
{107}{}{我要啃你的骨头！}
{108}{}{死亡！死亡！死亡！}
{109}{}{嘿，你听说赛特被干掉了吗？}
{110}{}{赛特死了。赛特死了。赛特死了……}
{111}{}{水够大家用的。赛特确保了这一点。}
{112}{}{我听说变种人被赶出城了。}
{113}{}{自从变种人离开后，一切都变得更好了。}
{114}{}{你好。}
