{100}{}{你看到梅菲斯托，一个愤怒的商人。}
{101}{}{你看到一个名叫哈姆斯的商人。}
{102}{}{你看到一个心烦意乱的商人，名叫福勒。}
{103}{}{你看到迪克森，一个愤怒的商人。}
{104}{}{你看到摩根，一个商人。}
{105}{}{你看到马可，一个愤怒的商人。}
{106}{}{你看到乔尔尼尔，一个商人。}
{107}{}{你看到马尔岑，一个商人。}
{108}{}{你看到约书亚，一个心烦意乱的商人。}
{109}{}{你看到安东尼，一个商人。}
{110}{}{你看到克拉克，一个商人。}
{111}{}{你看到马兰蒂克，一个心烦意乱的商人。}
{112}{}{你看到奥兰多，一个商人。}
{113}{}{你看到一个名叫伊利亚的商人。}
{114}{}{你看到特蕾西，一个心烦意乱的商人。}
{115}{}{你能相信这种混乱吗？}
{116}{}{排队去。}
{117}{}{你不是这个商会的。}
{118}{}{你的商队也被延误了吗？}
{119}{}{祝你好运，能办成点事。}
{120}{}{你见过高塔吗？}
{121}{}{如果我是你，我会去找远行商人。}
{122}{}{找主商人吗？她就在那边。}
{123}{}{如果我的货物再不出发，就有大麻烦了。}
{124}{}{玛莎就在那边。}
{125}{}{你不是商人，滚开。}
{126}{}{警卫宿舍在另一边。}
{127}{}{我不会给你钱，走开。}
{128}{}{我的货物永远不会离开。}
{129}{}{别想侵占我的地盘。}
{130}{}{为什么我的货物还没发走？}
{131}{}{我的补给在哪儿？}
{132}{}{你的价格太糟糕了！}
{133}{}{海塔沃尔在哪儿？}
{134}{}{我应该享有优先权！}
{135}{}{我的货物已经晚了两周！}
{136}{}{我要退款！}
{137}{}{我要见海塔沃尔。}
{138}{}{我要把生意转给赤色商队。}
{139}{}{你们这些人怎么回事？}
{140}{}{我等得不耐烦了！}
{141}{}{我受够了借口！}
{142}{}{我的货物比他的更重要！}
{143}{}{你不明白什么？}
{144}{}{办好，否则我就去别处！}
