{100}{}{你看到迈克，旧城区的守卫。}
{101}{}{嗯，你想要什么？}
{102}{}{呃...嗯...嗯...}
{103}{}{我不是本地人。这是哪一片城区？}
{104}{}{你知道哪里能找到水芯片吗？}
{105}{}{呃...再见。}
{106}{}{哈，又一个瘾君子。去别的地方混吧，瘾头。}
{107}{}{是啊，你肯定迷路了。大多数人都不愿意来这片地方。这是东区，或者有人叫它旧城区，废土中的废土。}
{108}{}{你知道哪里能找到水芯片吗？}
{109}{}{谢谢你的信息。再见。}
{110}{}{水芯片？你是嗑药了吗？一个用水做的芯片？}
{111}{}{别跟我顶嘴，小子。现在我得把你埋了。}
{112}{}{我不是本地人。我在哪个城区？}
{113}{}{算了。再见。}
