{100}{}{你看到一个衣衫褴褛的人。}
{101}{}{谢谢你，陌生人！我不知道这些恶棍把我关在这里多少周，也许是几个月了。我非常感激你的帮助，我相信钢铁兄弟会也会感激不尽。}
{102}{}{钢铁兄弟会？}
{103}{}{能帮上忙我很高兴。}
{104}{}{你没事吧？}
{105}{}{我来自钢铁兄弟会。我一直在找你。}
{106}{}{不客气，再见。}
{107}{}{呃。}
{108}{}{你没听说过我们？我真的很惊讶。你一定不常离开市集。你应该多出去走走。我们在这里的西北面，山脉的西侧。}
{109}{}{我非常感激你帮了我，但你为什么要对我撒谎？你是不是觉得我不认识我们组织的每一个成员？}
{110}{}{是塔鲁斯派我来的。}
{111}{}{嗯，你不认识我是因为我才刚加入。}
{112}{}{你显然不知道你在说什么。}
{113}{}{再次感谢！如果你路过钢铁兄弟会，我很感激你能告诉塔鲁斯我没事了。我相信他一定很担心。再见，保重。}
{114}{}{哦，我现在没事了，谢谢。我有一些朋友在这里，我可以和他们住在一起恢复体力。我会尝试向钢铁兄弟会传信，让他们知道我现在安全了，多亏了你。再见}
{115}{}{怎么 哦，抱歉。你一定通过了长老们设下的那个“测试”。我完全忘记了。嗯，我的谢意更加深沉。我很高兴你从未放弃。我的生命随时可能面临危险。找到我一定花了你不少时间。这城市太大了，还有那么多障碍在你们面前。}
{116}{}{嗯，你知道我就是这么厉害。}
{117}{}{实际上，这相当容易。塔鲁斯知道你去了哪里。}
{118}{}{我想只是运气好吧。}
{119}{}{嗯，不管怎样，谢谢你。我很高兴找到了你。}
{120}{}{哦 不过，我还是非常感激。}
{121}{}{我想是的。你真是干了一手漂亮活计。}
{122}{}{能帮上忙我很高兴。}
{123}{}{你没事吧？}
{124}{}{嗯，再次感谢。我打算和我的一些朋友待在一起直到恢复体力。顺便说一句，在这里要小心。我听到我的主人谈论了一些盗贼的圈子。我猜我们离他们的地盘很近。我想这可能是为什么他们谈论搬到其他地方。再见。}
{125}{}{嗯，我很高兴你的运气一直不错。我听说了一些关于旧城区的坏消息。那些流浪者让人毛骨悚然，我觉得是另有隐情。}
{126}{}{不管你怎么说，我只是很感激再次获得自由。我可受不了折磨。}
{127}{}{不，真的，是塔鲁斯派我来的。}
{128}{}{嗯，能帮上忙我很高兴。}
{129}{}{你没事吧？}
{130}{}{也许不是。我最近记忆有些问题。我想这可能是他们给我吃的东西导致的。}
{131}{}{不，真的，塔鲁斯派我来的。}
{132}{}{很高兴我能帮上忙。}
{133}{}{你会没事吧？}
{134}{}{又见面了。}
{135}{}{我很快就要离开了。只是需要积攒一些力气。}
{136}{}{再次感谢。}

// Tell me abouts
{1000}{}{兄弟会}
{1001}{}{钢铁}
{1002}{}{塔鲁斯}

// Answers
{1100}{}{这是这个受苦星球和它的人民唯一的救赎。没有他们，人类必将灭亡。}
{1101}{}{这是这个受苦星球和它的人民唯一的救赎。没有他们，人类必将灭亡。}
{1102}{}{他是我的导师，也是个伟大的人。我期待再次见到他。}
