{100}{}{你脖子后的汗毛竖起。你感受到前方走廊传来的某种东西。当你认出前方墙壁上的肉块是人类的部分时，胃里一阵翻腾。最糟糕的是，它在动，仿佛在呼唤你。}
{101}{}{你的鼻子开始流血。你听到脑海中有声音在呼唤你的名字。黑暗短暂地笼罩了你的视线，但你恢复了过来。}
{102}{}{一个声音在呼唤你。你转过头，看到一个已被遗忘的朋友的影像，显然已经死去。她腐烂的下颚掉下蛆虫，而你的头痛愈发剧烈。}
{103}{}{前进变得越来越困难。你的脚似乎被粘在了地板上。你低头一看，地板的肉块正在爬上你的腿。牙齿在啃咬你的膝盖。与此同时，你的头痛更加严重。}
{104}{}{某样东西引起了你的注意，天花板上有一闪而过的动作，然后一片骨头刺入了你的眼睛！随之而来的是死者和受折磨者的思绪！}
{105}{}{你头部的疼痛让人发狂。你感受到他人的罪孽洗刷着你的灵魂。而且情况更糟，因为你的罪孽也在回应它们。就像疯子一样，它们在你的精神中争斗，并在过程中撕裂了你的个性。}
{106}{}{你的头随着他人的侵入性思绪而跳动。疼痛不断加剧。突然间，仿佛从未存在过，疼痛消失了。你倒在地上哭泣。但总觉得哪里不对劲。}
{107}{}{你头部的疼痛似乎没有之前那么严重。这个奇怪走廊的影响似乎没有那么强烈。}
