{100}{}{你看到一个技术员。他正在为统一体和主宰勤奋工作。}
{101}{}{我们为主宰效力。}
{102}{}{我们为主宰效力，不能被打扰！}
{103}{}{主宰！有入侵者！}
{200}{}{你看到维西厄斯，一个超级变种人首领。他看起来很凶。}
{201}{}{你看到一个凶神恶煞的超级变种人。}
{202}{}{主宰的意志不可违抗。你有什么消息带给我？}
{203}{}{哼！}
{204}{}{呃，战争进展顺利。}
{205}{}{我有一条来自中尉的消息要传达给主宰。我必须立刻见到主宰。}
{206}{}{我唯一的消息就是你马上要变成肥料了。}
{207}{}{有入侵者！}
{208}{}{你的举止出卖了你，入侵者。我将在此终结威胁。}
{209}{}{你不可能是认真的。事实上，你一定是在撒谎。}
{210}{}{呃，是啊，那又怎样？}
{211}{}{我没有。中尉不能信任常规方法传递这条消息。我必须立刻见到主宰！没有时间可以浪费！}
{212}{}{那么用门吧，小心走廊。我假设你已经做好了防护准备？}
{213}{}{当然。谢谢。统一体必胜。}
{214}{}{没有，真的没有。我应该吗？}
{215}{}{当然！没有它你无法通过走廊。你的屏蔽器放哪了！}
{216}{}{我把它留在了另一件长袍里。}
{217}{}{中尉没时间给我一个。}
{218}{}{啊，幽默，我喜欢。[停顿] 显然我没有。你需要去二层从那些脑袋空空的家伙那里拿一个。统一体必胜。}
{219}{}{那么他是个傻瓜，或者你并非看起来的那样。怎么回事？}
{220}{}{显然，他是个傻瓜。}
{221}{}{后者。}
{222}{}{独自行动，继续你的任务。我没时间理你。}
{300}{}{房间角落里有一小堆烟蒂。}
{301}{}{超级变种人走到房间的一侧，点燃了一支烟。}
{302}{}{你看到一个嘴里叼着香烟的超级变种人。}
{303}{}{超级变种人将烟蒂弹进角落。}
