{100}{}{你看到一个肮脏邋遢的囚犯。}
{101}{}{第二个牢房里的一个囚犯与众不同。他站得笔直，直视着你的眼睛。}
{102}{}{囚犯呆呆地盯着墙壁。}
{103}{}{囚犯无视你的交谈尝试。}
{104}{}{他疯狂地看了你一眼，然后转过身去。}
{105}{}{她看了你一会儿，然后流下了口水。}
{106}{}{你没有得到任何回应。}
{107}{}{我们自由了！我们自由了！}
{108}{}{你这种人真让人厌恶。别跟我说话。}
{109}{}{奎布！}
{110}{}{你没有资格这样对我说话。}
{111}{}{你不明白。我是来救你的。}
{112}{}{不要嘲笑我。}
{113}{}{我没有权利，也不在乎。走开，别打扰我们。}
{114}{}{我拒绝告诉你任何信息。别烦我。}
{115}{}{哼！！}
{116}{}{我真的是来救你的。我是个普通人类。}
{117}{}{如果你愿意这样。好吧。再见。}
{118}{}{什么？没有斗篷可以隐藏？你的背叛本性昭然若揭。}
{119}{}{你还记得上周你试过那招吗？我当时没上当，现在也不会。}
{120}{}{我是来救你的。}
{121}{}{那么，再见。}
{122}{}{你太残忍了。别打扰我们。}
{123}{}{我不会出卖我的同胞。你不能强迫一个人背叛自己，只能逼他停止活下去。}
{124}{}{你真的不明白。我是个来救人的人类。}
{125}{}{我甚至不需要强迫你下地狱。你自己就做得很好。}
{126}{}{你还是在嘲笑我。}
{127}{}{从一个人口中吐出蛇的语言。}
{128}{}{对，我能猜到。走开，别打扰我们。}
{200}{}{囚犯看起来又脏又累。他们脖子上的项圈闪闪发亮，显然是新的。}
{201}{}{囚犯用空洞的目光回望着你。你注意到他们脖子上戴着一个项圈。}
{300}{}{墙上的标志写着：'禁止入内。安全区域。仅限囚犯管理人员！'}
{301}{}{你获得了}
{302}{}{点经验值，因为你让囚犯摆脱了痛苦。}
