{100}{}{机器人无法运作。上面的灰尘层表明它最近没有被启用。}
{101}{}{机器人已修复，但仍无法运行。}
{102}{}{硬件没有问题，问题出在软件上。}
{103}{}{你无法访问机器人的功能，因为它已被禁用。}
{104}{}{你尝试修理故障组件，但需要更多时间来完成修复。}
{105}{}{你重启了机载计算机，并成功重新启动了机器人。你注意到机器人的无线电损坏了。}
{106}{}{你花了一些时间在机器人的计算机上工作，但无法重新启动它。}
{107}{}{单元#462上线。自检。调整单元位置数据。已修复。重建内存文件。已修复。错误 - 任务未完成。}
{108}{}{罗加。}
{109}{}{你的未完成任务是什么？}
{110}{}{好吧，快去做完然后让开！}
{111}{}{[点击] 好的！重新启动任务。}
{112}{}{单元#462是清洁型号。必须完成这一层的清洁和维护。}
{113}{}{去吧！}
{114}{}{你还剩下什么要清理的？}
{115}{}{控制室。[点击] 列表结束。}
{116}{}{嘿。完成你的任务。}
{117}{}{你因做了一点清理工作而获得1000经验值。}
