{100}{}{你看到了一位大师商人}
{101}{}{抓住这个小偷！}
{102}{}{……我不管他们怎么说。我们需要新的零件……哦，对不起。我能为你做些什么？}
{103}{}{我想找份工作。}
{104}{}{你有水芯片吗？}
{105}{}{没什么，再见。}
{106}{}{谢克。}
{107}{}{当然，太好了。你被录用了。等等，什么职位？哦，护送商队，对吧？好的，你可以为我们工作。你看起来不错。还有别的事吗？}
{108}{}{没有。}
{109}{}{有，你有水芯片吗？}
{110}{}{什么？}
{111}{}{抱歉，没时间胡闹！}
{112}{}{水芯片……嗯。哦，那些旧的避难所净化控制芯片。嗯，我可以代表整个镇子告诉你，你在这里找不到。没有合适的设备，它们毫无用处。只有避难所，或者可能是死城才会需要它们。你为什么问？}
{113}{}{死城？他们为什么需要一个？}
{114}{}{我的避难所的芯片坏了，我在找一个替换的。}
{115}{}{只是好奇。}
{116}{}{我不能说。}
{117}{}{真的吗？好吧，正如你可能听说的，我们在整个地区供应大量的水。我相信我们可以安排一个商队去你的避难所，不过要收费。}
{118}{}{我们谈的是多少钱？}
{119}{}{我不知道我能不能信任你。}
{120}{}{不用了，谢谢。}
{121}{}{好吧，如果你这么说。}
{122}{}{那我很抱歉，我想我帮不了你。}
{123}{}{不信任我？！我经常被信任去给比你更偏执的人送水！你以为我们是什么？恐怖分子？}
{124}{}{好吧，行。你想要多少钱来启动商队。}
{125}{}{对不起。我不是故意暗示什么，但我不能冒这个险。}
{126}{}{好吧，如果你改变主意，请告诉我。我现在很感兴趣。}
{127}{}{又见面了。}
{128}{}{我需要一个水芯片。}
{129}{}{我还在找一个水芯片。}
{130}{}{我想找份工作。}
{131}{}{再见。}
{132}{}{当然，太好了。你被录用了。等等，什么职位？哦，护送商队对吧？没问题，你可以为我们工作。你看起来还不错。}
{133}{}{我们已经讨论过这个了。你愿意支付启动水商队的费用吗？}
{134}{}{你之前提到死城可能有一个水芯片。他们为什么需要一个？}
{135}{}{我们在谈多少？}
{136}{}{不，还没有。}
{137}{}{嗯，这只是个猜测。我们曾试图开辟一条去死城的商队路线，但他们拒绝与我们交易。如今除非有可靠的水源，否则没有人会拒绝水。我猜他们一定有自己的净水器，否则早就灭亡了。那么你是想让我们去你们的避难所吗？}
{138}{}{是的，这要花多少钱？}
{139}{}{不用了，谢谢。}
{140}{}{嗯，距离相当远。2000瓶盖应该能覆盖初始商队费用，我相信你们的避难所会有东西可以交易以维持一段时间。不过根据我们目前的储备，我估计我们只能让你们的避难所多撑100天左右。}
{141}{}{好的，这是钱。}
{142}{}{避难所应该能支付你大部分的初始费用。为什么我不给你1000瓶盖作为开始。}
{143}{}{距离确实很远，但避难所有足够的物资来补偿你的预付款。那么，500瓶盖怎么样？}
{144}{}{我没有现金，我会有钱的时候再来。}
{145}{}{看起来你没有足够的钱，有钱的时候再来。记住你需要}
{146}{}{瓶盖。}
{147}{}{好的，我今天就可以开始派商队去你们的避难所。不过你应该知道，商队在沙漠中非常显眼。所以，派商队过去会让任何寻找你们避难所的人很容易找到。你还确定要这样做吗？}
{148}{}{我想还是算了。}
{149}{}{是的，避难所需要水。}
{150}{}{听起来很合理。避难所的技术在这里的商场能卖个好价钱。}
{151}{}{抱歉，我只能接受全额付款。}
{152}{}{听起来很合理。避难所的技术在这里的商场能卖个好价钱。}
{153}{}{抱歉，我只能接受全额付款。}
{154}{}{你打算支付我要求的金额来启动水商队吗？}
{155}{}{好的，他们会在几个小时内出发。}
{156}{}{抱歉，水商人不再与你合作。}
{157}{}{你有}
{158}{}{瓶盖让我们启动去你避难所的水商队吗？}
