{100}{}{你看到尼尔，追随者的警卫队长。}
{101}{}{你看到尼尔，追随者的警卫队长。}
{102}{}{如果你想找人谈话，去找彼得。我正想睡觉。}
{103}{}{你来这里干什么？}
{104}{}{嗯。嗷嗷？}
{105}{}{不不。}
{106}{}{杀！！}
{107}{}{我是}
{108}{}{。我是被派来找你的。}
{109}{}{我是}
{110}{}{。而你已经死了。}
{111}{}{你能告诉我关于追随者的事情吗？}
{112}{}{我来是为了提供帮助。}
{113}{}{我在寻找能给这片荒芜废土带来和平的方法。}
{114}{}{抱歉，我听不懂你说什么。现在，你在这里干什么？}
{115}{}{不不。}
{116}{}{我杀！！}
{117}{}{帮。我帮。}
{118}{}{如果你无事可做，我建议你现在离开。}
{119}{}{你想帮忙？也许我可以用到你。}
{120}{}{是的。我帮！我帮！}
{121}{}{不。不帮！}
{122}{}{你足够简单，能找到那些聪明人找不到的人。这里有个间谍在向孩子们泄露我们的秘密。找到间谍。杀掉间谍。去吧。}
{123}{}{我早就这么想了。你走吧。}
{124}{}{看来杰克不认为我能把事情做好。只有他会派你来。那么你知道间谍的事。}
{125}{}{不是杰克派我来的。是你的一名警卫派我来的。}
{126}{}{我知道一些。杰克说得很少。}
{127}{}{关于间谍的事是什么？也许我能帮忙。}
{128}{}{我的警卫不是傻子。他们把你送到了正确的人这里。这里有个漏洞，我们需要找出它并封住。}
{129}{}{有任何线索吗？}
{130}{}{我是个战士，不是水管工。如果你有漏水问题，找别人吧。}
{131}{}{我觉得你才是内鬼。去死吧！！}
{132}{}{算了吧，我不是谁的走狗。}
{133}{}{目前我们只知道那个人必须能进入儿童大教堂。我觉得可能是我们的侦察员之一。}
{134}{}{好的，我马上去调查。}
{135}{}{你确定不是守卫吗？}
{136}{}{那就太不走运了。你永远抓不到那个人了。}
{137}{}{我很确定。他们只能进入追随者大厅，不被允许外出。}
{138}{}{那我就不知道会是谁了。}
{139}{}{那我去查查侦察员。}
{140}{}{我觉得这里有掩盖。你去死吧！}
{141}{}{这就是我请你四处看看，看看能不能找到什么人的原因。你愿意帮忙吗？}
{142}{}{愿意。}
{143}{}{不愿意。}
{144}{}{谢谢。这对我们意义重大。}
{145}{}{那我必须扣留你，以防你警告任何人。}
{146}{}{我真搞不懂他是怎么成为副指挥的。既然他话不多，我来告诉你。我们有个内鬼在向儿童泄露我们的行动路线。}
{147}{}{有任何线索吗？}
{148}{}{我是个战士，不是水管工。如果你有漏水问题，找别人吧。}
{149}{}{我觉得你才是内鬼。去死吧！！}
{150}{}{算了吧，我不是谁的走狗。}
{151}{}{你都不知道吗？我猜你不会知道；这里大多数人都不知道。有人在偷偷把我们的行动信息泄露给儿童。我们需要除掉那个人。}
{152}{}{有任何线索吗？}
{153}{}{我觉得你才是内鬼。去死吧！！}
{154}{}{算了吧，我不是谁的走狗。}
{155}{}{你愿意出多少？}
{156}{}{我没多少钱。200瓶盖怎么样？}
{157}{}{抱歉，我没钱。}
{158}{}{你的命。}
{159}{}{听起来挺合理的。}
{160}{}{现在我将结束追随者中的这个漏洞！}
{161}{}{那真是不幸。}
{162}{}{你想知道些什么？}
{163}{}{谁是领袖？}
{164}{}{你们为什么攻击孩子们？}
{165}{}{我在哪里可以得到急救？}
{166}{}{没什么。只是看看。}
{167}{}{没什么。谢谢。}
{168}{}{我们的领袖是妮可。她是个很好的人，但有点心不在焉。还有什么想知道的吗？}
{169}{}{你们为什么攻击孩子们？}
{170}{}{我在哪里可以得到治疗？}
{171}{}{没什么。只是看看。*啪*}
{172}{}{没什么。谢谢。}
{173}{}{孩子们并不像他们看起来那样。他们在隐藏一些东西，与那些夜行者有关。还有别的吗？}
{174}{}{谁是领袖？}
{175}{}{我在哪里可以得到治疗？}
{176}{}{没什么。只是看看。*啪*}
{177}{}{没什么。谢谢。}
{178}{}{有孩子们的治疗师，但我不信任他们。我们这里也有医生或护士值班。还有别的吗？}
{179}{}{谁是领袖？}
{180}{}{你们为什么攻击孩子们？}
{181}{}{没什么。只是看看。*啪*}
{182}{}{没什么。谢谢。}
{183}{}{听到这个我真的很遗憾。愿你安好！}
{184}{}{谁派你来的？}
{185}{}{你的守卫派我来的。}
{186}{}{杰克派我来的。}
{187}{}{我自己来的。}
{188}{}{算了。再见。}
{189}{}{你对自己很有信心。我不需要你。如果你想提供服务，去找妮可谈谈。晚安。}
{190}{}{那么你应该去找妮可。她能更好地帮助你。晚安。}
{191}{}{去找出那个间谍。我们需要继续保密我们的计划。}
{192}{}{干得好，找出并解决了希瑟。她的干预差点害死所有人。真希望我们能做更多。}
{193}{}{也许我还能再帮你一次。}
{194}{}{祝你好运。}
{195}{}{怎么帮？}
{196}{}{我可以训练追随者一些战争技能。也许你的胜算会提高。}
{197}{}{我可以离开。再见。}
{198}{}{那太好了。谢谢你。}
{199}{}{现在你准备得更充分了。晚安。}
{200}{}{感谢你的教导。现在我们有机会击退那些孩子们了。}
