{100}{}{你看到一个水处理控制电脑。由于关键硬件的移除，它发生了故障。}
{101}{}{你在水处理控制电脑中搜索成功。你毫不费力地找到了水芯片。}
{102}{}{你搜索水处理电脑。花了一些时间，但最终你发现了水芯片。}
{103}{}{没有功能正常的水芯片，电脑无法修复。}
{104}{}{你轻松地从电脑中取下了水芯片。你听到城市的水流停止了。}
{105}{}{你与电脑挣扎了一会儿，但无法取下芯片。过了一会儿，你意识到忘记拆除锁定螺栓。}
{106}{}{你没有取下芯片。也许你应该再试一次，这次要更小心些。}
{107}{}{你离水处理电脑太远，无法仔细检查。}
{108}{}{你未能修复电脑。}
{109}{}{你没有从水处理电脑中学到任何特别的东西。}
{110}{}{你将水芯片重新安装到电脑中。电脑在片刻后重启，并恢复正常功能。}
{111}{}{此物品无法用于电脑。}
{112}{}{你看到一个水处理控制电脑。它是正常运行的。}
{113}{}{你获得}
{114}{}{经验值，因为获得了一个水芯片。}
{115}{}{你仔细检查电脑。你的分析头脑发现了一些可以简化水芯片移除的方法。}
{116}{}{你了解到没有重新安装水芯片就无法修复电脑。}
{117}{}{关闭水净化电脑后，你现在可以听到修复后的水泵在远处工作，将水从Necropolis下方的深井中抽上来。}
