{500}{}{在摧毁了主宰者和他制造超级变种人军队的实验室后，你回到了家，却发现自己因为过于破坏性而被赶出了避难所。感谢你游玩《辐射》。}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#      "my name"       #
#      (970-979)       #
#                      #
#                      #
{970}{}{那是我的名字。}
{971}{}{你在跟我说话。}
{972}{}{为什么问这些傻问题。我就是那个人。}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#     "don't know"     #
#      (970-979)       #
#                      #
#                      #
{980}{}{我对此一无所知。}
{981}{}{抱歉。我没有头绪。}
{982}{}{从未听说过。}

# DESERT1.MAP (1000)
# DESERT2.MAP (1600)
# DESERT3.MAP (2200)

#
# HALLDED.MAP
# The Necropolis Hall of the Dead Tell-Me-Abouts
#
{2800}{}{主宰者}
{2801}{}{水芯片}
{2802}{}{死城}
{2803}{}{设置}
{2804}{}{水处理站}
{2805}{}{大厅}
{2900}{}{他不是个很重要的人物吗？}
{2901}{}{我不知道，不过水处理站可能有一个。}
{2902}{}{你正站在这里。这就是它的全部了，这地方正在慢慢死去，毫无疑问。}
{2903}{}{哦，我喜欢他。我确实喜欢。你可以在大厅找到他。}
{2904}{}{在北边。小心那些守卫，他们可是非常认真地对待自己的工作。}
{2905}{}{亡者大厅。Set在这里处理他的事务。就在死城的正中心。}


#
# HOTEL.MAP
# The Necropolis Hotel Tell-Me-Abouts
#
{3400}{}{主人}
{3401}{}{水芯片}
{3402}{}{死城}
{3403}{}{设置}
{3404}{}{水处理站}
{3405}{}{大厅}
{3500}{}{他不是个很重要的人物吗？}
{3501}{}{我不知道，不过水处理站可能有一个。}
{3502}{}{你正站在这里。这就是它的全部了，这地方正在慢慢死去，毫无疑问。}
{3503}{}{哦，我喜欢他。我确实喜欢。你可以在大厅找到他。}
{3504}{}{在北边。小心那些守卫，他们可是非常认真地对待自己的工作。}
{3505}{}{亡者之厅。Set在这里处理事务。就在死城的正中心。}


#
# WATRSHD.MAP
# The Necropolis Watershed Tell-Me-Abouts
#
{4000}{}{主宰}
{4001}{}{水芯片}
{4002}{}{死城}
{4003}{}{设置}
{4004}{}{水域}
{4005}{}{大厅}
{4100}{}{他不是个很重要的人物吗？}
{4101}{}{我不知道，但水域可能有一个。}
{4102}{}{你就站在这里。这就是它的全部，至少是剩下的部分。这个地方正在慢慢地死去。}
{4103}{}{哦，我喜欢他，我喜欢。你可以在大厅找到他。}
{4104}{}{小心那些守卫。他们的工作态度非常认真。}
{4105}{}{亡者之厅。Set在这里处理事务。就在死城的正中心。}


#
# VAULT13.MAP
# Vault 13 Tell-Me-Abouts
#
{4600}{}{避难所}
{4601}{}{水}
{4602}{}{监督者}
{4603}{}{芯片}
{4604}{}{水芯片}
{4605}{}{避难所13}
{4606}{}{避难所13}
{4607}{}{医护}
{4608}{}{治疗}
{4609}{}{图书馆}
{4700}{}{这是我们生活的地方。你应该明白这一点。}
{4701}{}{芯片控制着地下水供应的纯净度。它是无法修复的重要设备。}
{4702}{}{一个好人在做一项艰难的工作。}
{4703}{}{芯片控制着地下水供应的纯净度。它是无法修复的重要设备。}
{4704}{}{芯片控制着地下水供应的纯净度。它是无法修复的重要设备。}
{4705}{}{这是我们生活的地方。你应该明白这一点。}
{4706}{}{这是我们生活的地方。你应该明白这一点。}
{4607}{}{医务人员在一楼的医务室。如果你受伤了，就去那里。}
{4608}{}{医务人员在一楼的医务室。如果你受伤了，就去那里。}
{4609}{}{图书馆在三楼的西翼。研究用的计算机就在那里。}

# VAULTENT.MAP (5200)
# VAULTBUR.MAP (5800)
# VAULTNEC.MAP (6400)

#
# JUNKENT.MAP
# Junktown Entrance Tell-Me-Abouts
#
{7000}{}{基利安}
{7001}{}{吉兹莫}
{7002}{}{废城}
{7003}{}{阴影沙地}
{7004}{}{枢纽镇}
{7005}{}{水芯片}
{7006}{}{赌场}
{7007}{}{商店}
{7008}{}{死亡爪}
{7100}{}{基利安是市长，他经营一家商店。}
{7101}{}{吉兹莫经营一家赌场。他看起来还不错。}
{7102}{}{这里是废城。}
{7103}{}{嗯，我想那是个很小的地方。我从没去过。}
{7104}{}{那是一个更大的城市，在南边的某个地方。}
{7105}{}{什么？抱歉。}
{7106}{}{那是一座位于镇西北部的大建筑。}
{7107}{}{基利安的商店？在镇中心。}
{7108}{}{我不知道，但这个名字让我害怕。}


#
# JUNKCSNO.MAP
# Junktown Casino Tell-Me-Abouts
#
{7600}{}{基利安}
{7601}{}{吉兹莫}
{7602}{}{废城}
{7603}{}{阴影沙地}
{7604}{}{枢纽镇}
{7605}{}{水芯片}
{7606}{}{赌场}
{7607}{}{商店}
{7608}{}{死亡爪}
{7700}{}{基利安是市长。他在他父亲去世后接管了。}
{7701}{}{吉兹莫是废城的大人物。他经营赌场和拳击场。他赚了很多钱，并从枢纽买了很多东西。}
{7702}{}{这里是废城。}
{7703}{}{嗯，那是一个在北方的小社区。住在那里的人大多是农民。我们偶尔会和他们交易，但他们大多希望被独自留下。}
{7704}{}{枢纽是这里的商业中心。几乎所有的商人都来自枢纽。他们那里还有一些公司仍在制造东西。如果你愿意，可以和他们的商队一起回到枢纽。}
{7705}{}{我对此一无所知。}
{7706}{}{吉兹莫经营它。小心老虎机，玩的话可能会输很多钱。}
{7707}{}{暗水？它在镇中心。你可以和他交易，或者用现金支付。}
{7708}{}{我听人们谈论过它，但我从未见过。他们说它在沙漠中游荡，主要在夜间袭击。}


#
# JUNKKILL.MAP
# Junktown Killian's Tell-Me-Abouts
#
{8200}{}{基利安}
{8201}{}{吉兹莫}
{8202}{}{废城}
{8203}{}{阴影沙地}
{8204}{}{枢纽}
{8205}{}{水芯片}
{8206}{}{赌场}
{8207}{}{商店}
{8208}{}{死亡爪}
{8300}{}{基利安是市长。他在他父亲去世后接管了。}
{8301}{}{吉兹莫是废城的大人物。他经营赌场和拳击场。他赚了很多钱，并从枢纽买了很多东西。}
{8302}{}{这里是废城。}
{8303}{}{嗯，那是一个在北方的小社区。住在那里的人大多是农民。我们偶尔会和他们交易，但他们大多希望被独自留下。}
{8304}{}{枢纽是这里的商业中心。几乎所有的商人都来自枢纽。他们那里还有一些公司仍在制造东西。如果你愿意，可以和他们的商队一起回到枢纽。}
{8305}{}{我对此一无所知。}
{8306}{}{吉兹莫经营它。小心老虎机，玩的话可能会输很多钱。}
{8307}{}{暗水？它在镇中心。你可以和他交易，或者用现金支付。}
{8308}{}{我听人们谈论过它，但我从未见过。他们说它在沙漠中游荡，主要在夜间袭击。}


# BROHDENT.MAP  (8800)
{8800}{}{大师}
{8801}{}{战争}
{8802}{}{大迁徙}
{8803}{}{奇怪的军队}
{8804}{}{兄弟会}
{8805}{}{商人}
{8806}{}{失踪的商队}
{8807}{}{集散地}
{8808}{}{大教堂的孩子们}
{8809}{}{新兵}
{8810}{}{抄写员}
{8811}{}{骑士}
{8812}{}{圣骑士}
{8813}{}{水芯片}
{8900}{}{我不知道你在说什么。}
{8901}{}{人类历史上一个极其悲惨的低谷，塑造了我们现在的世界。我们保存着战争的知识，以防止另一场浩劫。}
{8902}{}{一个艰难而悲伤的决定。我们失去了许多选择独自离开的人，而不是与主力一起寻找安全居所的人。}
{8903}{}{我对此了解不多。据我所知，他们正在我们北方某地集结。}
{8904}{}{这就是我们的立场。}
{8905}{}{那些水商是贪婪的混蛋，但对于其他团体，我没有意见。}
{8906}{}{我对此一无所知。}
{8907}{}{那是那些卑鄙商人的泥潭。不过，偶尔我们会让一些较为文明的贸易公司与我们交换货物。}
{8908}{}{他们是一个邪教。}
{8909}{}{他们是兄弟会的未来。}
{8910}{}{他们是知识的守护者。}
{8911}{}{他们是为兄弟会制造武器的人。}
{8912}{}{他们是兄弟会的守护者。}
{8913}{}{我不知道你在说什么。}

# BROHD12.MAP   (9400)

{9400}{}{主宰}
{9401}{}{战争}
{9402}{}{大迁徙}
{9403}{}{奇怪的军队}
{9404}{}{兄弟会}
{9405}{}{商人}
{9406}{}{失踪的商队}
{9407}{}{枢纽镇}
{9408}{}{大教堂的孩子们}
{9409}{}{新兵}
{9410}{}{抄写员}
{9411}{}{骑士}
{9412}{}{圣骑士}
{9413}{}{水芯片}
{9500}{}{我不知道你在说什么。}
{9501}{}{人类历史上一个极其低谷的时期，塑造了我们现在的世界。我们保存战争的知识，以防止另一次浩劫。}
{9502}{}{一个艰难而悲伤的决定。我们失去了许多选择独自离开的人，而不是与主力一起寻找安全的栖身之地。}
{9503}{}{我对此了解不多。据我所知，他们正在我们北方的某个地方集结。}
{9504}{}{这就是我们的立场。}
{9505}{}{那些水商是贪婪的混蛋，但对于其他团体，我没有意见。}
{9506}{}{我对此一无所知。}
{9507}{}{那是那些卑鄙商人的泥潭。不过，偶尔我们会允许一些较文明的贸易公司与我们交换货物。}
{9508}{}{他们是一个邪教。}
{9509}{}{他们是兄弟会的未来。}
{9510}{}{他们是知识的守护者。}
{9511}{}{他们是为兄弟会制造武器的人。}
{9512}{}{他们是兄弟会的守护者。}
{9513}{}{我不知道你在说什么。}

# BROHD34.MAP  (10000)

{10000}{}{主宰}
{10001}{}{战争}
{10002}{}{大迁徙}
{10003}{}{奇怪的军队}
{10004}{}{兄弟会}
{10005}{}{商人}
{10006}{}{失踪的商队}
{10007}{}{枢纽}
{10008}{}{大教堂的孩子们}
{10009}{}{见习者}
{10010}{}{抄写员}
{10011}{}{骑士}
{10012}{}{圣骑士}
{10013}{}{水芯片}
{10000}{}{我不知道你在说什么。}
{10101}{}{人类历史上一个极其低谷的时期，形成了我们现在的世界。我们保存战争的知识，以防止另一场浩劫。}
{10102}{}{一个艰难而悲伤的决定。我们失去了许多选择独自离开的人，而不是与主力部队一起寻找安全的栖身之所。}
{10103}{}{我对此了解不多。据我所知，他们正在我们北方的某个地方集结。}
{10104}{}{这就是我们的立场。}
{10105}{}{那些水商是偷窃的混蛋，但对于其他团体，我没有意见。}
{10106}{}{我对此一无所知。}
{10107}{}{那些卑鄙商人的泥潭。不过，有时我们会让一些较为文明的贸易公司与我们交换货物。}
{10108}{}{他们是一个邪教。}
{10109}{}{他们是兄弟会的未来。}
{10110}{}{他们是知识的守护者。}
{10111}{}{他们是为兄弟会制造武器的人。}
{10112}{}{他们是兄弟会的保护者。}
{10113}{}{我不知道你在说什么。}


# CAVES.MAP    (10600)
# CHILDRN1.MAP (11200)

{11200}{}{圣火}
{11201}{}{统一体}
{11202}{}{大教堂的孩子们}
{11203}{}{莫菲斯}
{11204}{}{变种人}
{11205}{}{主宰}
{11206}{}{启示录的追随者}
{11207}{}{军事基地}
{11208}{}{熔池}
{11209}{}{水芯片}

{11300}{}{圣焰将引领我们进入一个没有仇恨和战争的勇敢新世界。}
{11301}{}{我们都是统一体的一部分。我们将爱与和平传递给我们的同胞，无论是人类还是变种人。}
{11302}{}{这就是我们。}
{11303}{}{摩菲斯是大教堂之子的高阶祭司。通常，他不在为我们布道时就在他的房间里。}
{11304}{}{他们是因核辐射变异的人，但他们仍然是好人。}
{11305}{}{我们都有主人，不是吗？}
{11306}{}{他们是试图破坏主人所努力建立的和平的人。}
{11307}{}{抱歉，从未听说过。}
{11308}{}{抱歉，我不知道你在说什么。}
{11309}{}{我完全不知道你在说什么。}

# CHILDRN2.MAP (11800)

{11800}{}{圣焰}
{11801}{}{统一体}
{11802}{}{大教堂之子}
{11803}{}{摩菲斯}
{11804}{}{变种人}
{11805}{}{主人}
{11806}{}{启示录的追随者}
{11807}{}{军事基地}
{11808}{}{熔池}
{11809}{}{水芯片}

{11900}{}{圣焰将引领我们进入一个没有仇恨和战争的勇敢新世界。}
{11901}{}{我们都是统一体的一部分。我们将爱与和平传递给我们的同胞，无论是人类还是变种人。}
{11902}{}{这就是我们。}
{11903}{}{摩菲斯是大教堂之子的高阶祭司。通常，他不在为我们布道时就在他的房间里。}
{11904}{}{他们是因核辐射变异的人，但他们仍然是好人。}
{11905}{}{我们都有主人，不是吗？}
{11906}{}{他们是试图破坏主人所努力建立的和平的人。}
{11907}{}{抱歉，从未听说过。}
{11908}{}{抱歉，我不知道你在说什么。}
{11909}{}{我完全不知道你在说什么。}

# CITY1.MAP    (12400)
# COAST1.MAP   (13000)
# COAST2.MAP   (13600)
# COLATRUK.MAP (14200)
# FSAUSER.MAP  (14800)

#
# RAIDERS.MAP
# Raiders Tell-Me-Abouts
#
{15400}{}{可汗帮}
{15401}{}{加尔}
{15402}{}{废城}
{15403}{}{阴影沙地}
{15404}{}{枢纽镇}
{15405}{}{水芯片}
{15406}{}{坦迪}
{15407}{}{艾莉娅}
{15408}{}{黛安娜}
{15409}{}{格温}
{15410}{}{佩特罗克斯}
{15411}{}{托利亚}
{15412}{}{酒}
{15413}{}{化学品}
{15500}{}{那就是我们，你这个走狗。}
{15501}{}{他是可汗帮的首领，是废土中最令人畏惧的人。}
{15502}{}{他们在西南方。我们有时会在辛苦掠夺后去那里放松。}
{15503}{}{我不明白为什么我们不彻底消灭他们。}
{15504}{}{他们在南方。我们会和他们交易。主要是水和弹药，有时也能得到更好的武器。}
{15505}{}{我为什么要在乎？}
{15506}{}{我不认识这个名字。}
{15507}{}{她是顾问，负责策划袭击。}
{15508}{}{她是军械师，负责修理我们的装备。}
{15509}{}{她是副指挥官。}
{15510}{}{他负责收集我们的补给。}
{15511}{}{他是厨师。}
{15512}{}{你有吗？}
{15513}{}{你有吗？}


#
# SHADYE.MAP
# Shady Sands East Tell-Me-Abouts
#
{16000}{}{可汗帮}
{16001}{}{加尔}
{16002}{}{废城}
{16003}{}{阴影沙地}
{16004}{}{枢纽镇}
{16005}{}{水芯片}
{16006}{}{坦迪}
{16007}{}{阿拉德什}
{16008}{}{赛斯}
{16009}{}{拉兹洛}
{16100}{}{他们是一个无法无天的团伙，假装自己是来自遥远过去的人。}
{16101}{}{他是可汗的首领。他是曾经踏足阴影沙地的最危险的人之一，他以铁腕统领着掠夺者部落。}
{16102}{}{向西南方向4到6天的路程。偶尔可以做些不错的交易，但更多时候他们会试图坑我们。}
{16103}{}{你正站在这里。}
{16104}{}{比废城更南边。枢纽镇是我听说过的最大的城市，那里至少有一千人。}
{16105}{}{抱歉，我帮不了你。}
{16106}{}{她是阿拉德什的女儿。将来她可能会领导我们，但她必须学会控制自己的方式。}
{16107}{}{他是我们社区的领袖，也是一个真正的英雄。你总能在公共大厅找到他忙碌的身影。}
{16108}{}{他和阿拉德什一起工作，以确保我们的安全。}
{16109}{}{我们的医生。如果你受伤了，就去找他。}

#
# SHADYW.MAP
# Shady Sands West Tell-Me-Abouts
#
{16600}{}{可汗}
{16601}{}{加尔}
{16602}{}{废城}
{16603}{}{阴影沙地}
{16604}{}{枢纽镇}
{16605}{}{水芯片}
{16606}{}{坦迪}
{16607}{}{阿拉德什}
{16608}{}{赛斯}
{16609}{}{拉兹洛}
{16700}{}{他们是一个无法无天的团伙，假装自己是来自遥远过去的人。}
{16701}{}{他是可汗的首领。他是曾经出现在阴影沙地最危险的人之一。他以铁腕统领着掠夺者部落。}
{16702}{}{往西南方向走4到6天。偶尔有不错的交易，但更多时候他们试图坑我们。}
{16703}{}{你就站在这里。}
{16704}{}{比废城更南边。中心城是我听说过的最大城市。那里至少有一千人。}
{16705}{}{抱歉，我帮不了你。}
{16706}{}{她是阿拉迪什的女儿。将来她可能会领导我们，但她必须学会控制自己的方式。}
{16707}{}{他是我们社区的领袖，也是个真正的英雄。你总能在公共大厅找到他工作。}
{16708}{}{他和阿拉迪什一起工作，确保我们的安全。}
{16709}{}{我们的医生。如果你受伤了，去找他。}

# GLOWENT.MAP  (17200)


#
# LAADYTUM.MAP
#
#

#  ======================================================================
#     ADYTUM
# Info Level 1 [People who know nothing]
{17800}{}{阿迪特姆}
{17801}{}{追随者}
{17802}{}{大教堂}
{17803}{}{撕裂者}
{17804}{}{刀锋}
{17805}{}{枪械跑商}
{17806}{}{中心城}
{17807}{}{废城}
{17808}{}{水芯片}
{17809}{}{商店}
{17810}{}{齐默曼}
{17811}{}{死城}
{17812}{}{辉光}
{17813}{}{监管者}
{17814}{}{拾荒者}
{17815}{}{墓园}
{17900}{}{就是这里。}
{17901}{}{他们住在这里的北面。}
{17902}{}{在我们南边一段距离。}
{17903}{}{他们在西边。}
{17904}{}{他们在东边。}
{17905}{}{他们在追随者的北边。}
{17906}{}{我们和他们进行交易。}
{17907}{}{那不是这里北边的一座城市吗？}
{17908}{}{什么？}
{17909}{}{泰恩的商店在靠近大门的地下。}
{17910}{}{他是市长。}
{17911}{}{我听说它在东边。}
{17912}{}{那是个传说。}
{17913}{}{他们保护我们。}
{17914}{}{他们出去获取物资。}
{17915}{}{这里是白骨镇。}


# Info level 2 [People who know something]
{18000}{}{阿迪特姆}
{18001}{}{追随者}
{18002}{}{大教堂}
{18003}{}{裂颅者}
{18004}{}{刀锋帮}
{18005}{}{枪械跑商}
{18006}{}{集散地}
{18007}{}{废城}
{18008}{}{水芯片}
{18009}{}{商店}
{18010}{}{齐默曼}
{18011}{}{死城}
{18012}{}{辉光}
{18013}{}{监管者}
{18014}{}{拾荒者}
{18015}{}{白骨镇}
{18100}{}{你在阿迪特姆，外来者。}
{18101}{}{追随者住在北边的一个旧图书馆里。他们宣扬宽容与和平。}
{18102}{}{大教堂在南边，靠近海湾。孩子们是个和平的宗教团体。}
{18103}{}{他们在西边。他们非常凶狠，还有很多陷阱。}
{18104}{}{他们在东边。他们使用某种高科技刀具。}
{18105}{}{他们在追随者的北边。他们向帮派出售武器。}
{18106}{}{我们与他们进行贸易。他们是我所知最大的城市。}
{18107}{}{他们是我们东北方的一个小城市。}
{18108}{}{没听说过。}
{18109}{}{Tine的商店在靠近大门的地下。他可以卖给你很多补给。}
{18110}{}{他是市长。他干得不错。}
{18111}{}{那是一个死者之城，向东几天的路程。}
{18112}{}{我听说它在很远很远的南方。}
{18113}{}{他们保护我们免受帮派的侵扰，维持治安。}
{18114}{}{他们出去搜寻物资。}
{18115}{}{我们在白骨之地。}


# Info level 3 [People who know more than something but less than everything]
{18200}{}{阿迪顿}
{18201}{}{追随者}
{18202}{}{大教堂}
{18203}{}{撕裂者}
{18204}{}{刀锋}
{18205}{}{枪械跑商}
{18206}{}{集散地}
{18207}{}{废城}
{18208}{}{水芯片}
{18209}{}{商店}
{18210}{}{齐默尔曼}
{18211}{}{死城}
{18212}{}{辉光}
{18213}{}{监管者}
{18214}{}{拾荒者}
{18215}{}{白骨之地}
{18300}{}{我们是曾经位于这个城市南部的一个旧避难所的后裔。}
{18301}{}{追随者是一群博学而和平的人。他们住在这里北边的一座旧图书馆里。}
{18302}{}{孩子们崇拜一个神秘的黑暗之神。他们看似无害，但他们的宗教有些奇怪。大教堂在这里的南边。}
{18303}{}{撕裂者全是近亲繁殖。他们有一座设有陷阱的堡垒，专门用来折磨和杀害囚犯。}
{18304}{}{刀锋帮以其振动刀而臭名昭著。他们是撕裂者的死敌。他们的领袖是一个叫剃刀的女人。}
{18305}{}{他们曾经是一个帮派，但后来在北边的一个仓库里安顿下来，开始向人们交易武器和枪支。}
{18306}{}{中心城是贸易和商业的中心。他们有一些公司实际上在生产东西。他们在我们的东边。}
#{18306 alternate If hydroponic farms aren't fixed:}{We sell bullets to the Hub.}
{18307}{}{废城是一个中等规模的城市，位于这里的东边，中心城的北边。}
{18308}{}{抱歉，帮不了你。}
{18309}{}{泰恩在前门附近经营着一家杂货店。他可以卖给你武器和旅行用品。}
{18310}{}{乔恩是我们的市长。他负责制定贸易协议、政策，并将责任分配给监管者和拾荒者。}
{18311}{}{死者之城？据说是一个由奇怪食人族居住的地方，远在东边。如果我是你，我不会去那里。}
{18312}{}{那是一个很大的放射性区域，远在南方，至少我是这么听说的。}
{18313}{}{他们是阿迪特姆的警察部队。他们保护我们免受帮派的侵害。卡莱布是他们的领袖。}
{18314}{}{拾荒者负责在骨园中寻找有价值的设备。他们由撒玛尔领导。}
{18315}{}{天使骨园是旧洛杉矶城的遗迹。我们正处于骨园的中心。}
#  ======================================================================


#
# LAFOLLWR.MAP  (18400)
#
#

======================================================================
#    FOLLOWERS OF THE APOCALYPSE
# Info Level 1 [People who know nothing]
{18400}{}{阿迪特姆}
{18401}{}{追随者}
{18402}{}{大教堂}
{18403}{}{撕裂者}
{18404}{}{刀锋帮}
{18405}{}{枪械跑商}
{18406}{}{中心城}
{18407}{}{废城}
{18408}{}{水芯片}
{18409}{}{妮可}
{18410}{}{骨园}
{18500}{}{这是一个在这里南边的村庄。}
{18501}{}{我们是末日追随者。}
{18502}{}{一个在南边，经过阿迪特姆的邪教。}
{18503}{}{一个在西边的帮派。}
{18504}{}{东边有个帮派。}
{18505}{}{北边有个帮派。}
{18506}{}{东北方向有个大型贸易城市。}
{18507}{}{在集散地北边有个中等规模的城市。}
{18508}{}{帮不了你，抱歉。}
{18509}{}{她是我们的领袖。}
{18510}{}{这里是白骨镇。}

# Info level 2 [People who know something]
{18600}{}{阿迪顿}
{18601}{}{追随者}
{18602}{}{大教堂}
{18603}{}{裂口帮}
{18604}{}{刀锋帮}
{18605}{}{枪械商}
{18606}{}{集散地}
{18607}{}{废城}
{18608}{}{水芯片}
{18609}{}{妮可}
{18610}{}{白骨镇}
{18700}{}{南边有个小镇，偶尔会有人来访。}
{18701}{}{我们是末日追随者。我们取这个名字是因为我们在战争的风暴之后而来，带来和平的慰藉。}
{18702}{}{在阿迪顿和白骨镇其他地方的南边有个奇怪的教派。妮可说他们在策划些什么。}
{18703}{}{在我们西边有个极度暴力的帮派。}
{18704}{}{东边有个帮派，他们使用振动刀。}
{18705}{}{从集散地来的帮派，卖枪。他们在北边。}
{18706}{}{集散地是个大型贸易和商业城市，在东边。}
{18707}{}{废城是个小城市，就在集散地的北边。}
{18708}{}{这方面我帮不了你。}
{18709}{}{她是我们的领袖。她有一个恢复分裂世界和平的愿景。}
{18710}{}{这里是天使白骨镇，旧洛杉矶城的遗迹。}

# Info level 3 [People who know more than something but less than everything]
{18800}{}{阿迪顿}
{18801}{}{启示录的追随者}
{18802}{}{大教堂}
{18803}{}{撕裂者}
{18804}{}{刀锋帮}
{18805}{}{枪械跑商}
{18806}{}{集市}
{18807}{}{废城}
{18808}{}{水芯片}
{18809}{}{妮可}
{18810}{}{白骨场}
{18900}{}{一个在南方的小镇。他们是好人，只是有点偏执。他们中的一些人会时不时地与我们合作。}
{18901}{}{我们是启示录的追随者。我们的职责是再次为世界带来和平与知识，并确保战争的武器不再伤害大地。}
{18902}{}{大教堂是一座位于白骨场南边的宏伟建筑。教堂的孩子们是一个崇拜黑暗邪神的邪教组织。必须阻止他们通过暴力传播他们的宗教。}
{18903}{}{近亲繁殖者和豺狼。他们攻击视线内任何与他们无关的人。他们住在这里西边的一个被陷阱包围的堡垒中。}
{18904}{}{一个住在东边的极其危险的团体，他们用振动刀战斗。他们的领袖剃刀来自集市，将他们塑造成一个凶猛的家族。}
{18905}{}{他们是一个住在北边仓库的帮派，周围是放射性污泥护城河。他们向其他帮派出售武器。}
{18906}{}{集市是一个在我们东边很远的庞大商业城市。他们向许多地方发送商队，包括阿迪特姆。}
{18907}{}{这是一个位于集市北边的小城市。我听说这是一个适合疲惫旅客停留的好地方。}
{18908}{}{虽然我读过关于避难所技术的资料，但这有点超出我的理解。}
{18909}{}{妮可是我们的领袖。她凭借洞察力和灵性，致力于为被战争破坏的世界带来和平。}
{18910}{}{这是天使白骨场的中心，以旧洛杉矶城命名，也因炸弹后遍布的死者骸骨而得名。}
======================================================================


# MBENT.MAP     (19000)

{19000}{}{主宰}
{19001}{}{中尉}
{19002}{}{大教堂的孩子们}
{19003}{}{启示录的追随者}
{19004}{}{夜行者}
{19005}{}{超级变种人}
{19006}{}{心灵感应者}
{19007}{}{实验}
{19008}{}{水芯片}

{19100}{}{我没有必要告诉你任何事情。}
{19101}{}{这种知识不属于低等生物。}
{19102}{}{你不必为他们操心。}
{19103}{}{你太卑微了，没资格质问我。}
{19104}{}{不关你的事。}
{19105}{}{这与你无关。}
{19106}{}{你太愚蠢了，无法了解他们。}
{19107}{}{你没有权限知道这些。}
{19108}{}{不要为这些玩具打扰我。}

# MBSTRG12.MAP  (19600)

{19600}{}{主人}
{19601}{}{中尉}
{19602}{}{大教堂的孩子们}
{19603}{}{启示录的追随者}
{19604}{}{夜行者}
{19605}{}{超级变种人}
{19606}{}{灵能者}
{19607}{}{实验}
{19608}{}{水芯片}
{19700}{}{我没有必要告诉你任何事情。}
{19701}{}{这种知识不属于低等生物。}
{19702}{}{你不必为他们操心。}
{19703}{}{你太卑微了，没资格质问我。}
{19704}{}{不关你的事。}
{19705}{}{这与你无关。}
{19706}{}{你太愚蠢了，无法了解他们。}
{19707}{}{你没有权限知道这些。}
{19708}{}{不要为这些玩具打扰我。}

# MBVATS12.MAP  (20200)

{20200}{}{主人}
{20201}{}{中尉}
{20202}{}{大教堂的孩子们}
{20203}{}{启示录追随者}
{20204}{}{夜行者}
{20205}{}{超级变种人}
{20206}{}{心灵感应者}
{20207}{}{实验}
{20208}{}{水芯片}
{20300}{}{我不需要告诉你任何事情。}
{20301}{}{这种知识不属于低等生物。}
{20302}{}{你不需要为他们操心。}
{20303}{}{你太卑微了，无法质疑我。}
{20304}{}{不关你的事。}
{20305}{}{这与你无关。}
{20306}{}{你太愚蠢，无法了解他们。}
{20307}{}{你没有权限知道他们的存在。}
{20308}{}{不要拿玩具来烦我。}


# MSTRLR12.MAP  (20800)

{20800}{}{主宰}
{20801}{}{中尉}
{20802}{}{大教堂的孩子们}
{20803}{}{启示录追随者}
{20804}{}{夜行者}
{20805}{}{超级变种人}
{20806}{}{心灵感应者}
{20807}{}{实验}
{20808}{}{水芯片}
{20900}{}{我不需要告诉你任何事情。}
{20901}{}{这种知识不属于低等生物。}
{20902}{}{你不需要为他们操心。}
{20903}{}{你太卑微了，无法质疑我。}
{20904}{}{不关你的事。}
{20905}{}{这与你无关。}
{20906}{}{你太愚蠢了，不配知道他们的存在。}
{20907}{}{你没有被授权了解他们。}
{20908}{}{别拿这些玩具来烦我。}

# MSTRLR34.MAP  (21400)

{21400}{}{主宰}
{21401}{}{中尉}
{21402}{}{大教堂的孩子们}
{21403}{}{末日信徒}
{21404}{}{夜行者}
{21405}{}{超级变种人}
{21406}{}{灵能者}
{21407}{}{实验}
{21408}{}{水芯片}
{21500}{}{我不必告诉你任何事情。}
{21501}{}{这种知识不属于低等生物。}
{21502}{}{你无需关心他们。}
{21503}{}{你太卑微了，没资格质问我。}
{21504}{}{不关你的事。}
{21505}{}{这与你无关。}
{21506}{}{你太愚蠢了，不配知道他们的存在。}
{21507}{}{你没有被授权了解他们。}
{21508}{}{别拿这些玩具来烦我。}


# V13ENT.MAP    (22000)

# HUBENT.MAP    (22600)

{22600}{}{警察}
{22601}{}{水商}
{22602}{}{赤色商队}
{22603}{}{远行商队}
{22604}{}{大教堂的孩子们}
{22605}{}{死城}
{22606}{}{热点}
{22607}{}{废城}
{22608}{}{钢铁兄弟会}
{22609}{}{阴影沙地}
{22610}{}{洛杉矶骨场}
{22611}{}{水塔}
{22612}{}{旧城区}
{22613}{}{市中心}
{22614}{}{高地}
{22615}{}{死亡爪}
{22616}{}{水芯片}
{22700}{}{治安由格林警长负责，以维护中心的法律和秩序。有些人认为他们更多是阻碍而不是帮助。}
{22701}{}{他们控制了中心的所有水资源。他们夺取了水塔的控制权，现在人们必须付费才能获得水。}
{22702}{}{一群疯狂的商人，为了登顶不惜冒险。}
{22703}{}{一群性格温和的商人，他们提供公平的价格，而不需要冒险。}
{22704}{}{一个宗教邪教，他们崇拜一个叫做“大师”的东西。他们在镇的东南侧由水商人经营一家医院。}
{22705}{}{阴森的地方。有些人说那里被变异人类所困扰，他们以正常人的脑子为食。它位于中心的东边。}
{22706}{}{有些故事说在这里的东南方有一个地方被核弹击中。}
{22707}{}{那在我们北边。我们和他们之间有相当多的贸易。据传言，基利安和吉兹莫水火不容。}
{22708}{}{那地方在这里的西北方。他们是一群崇拜科技的技术怪人。非常诡异的人。}
{22709}{}{一个原始的城镇，远在北方。关于他们的情况知之甚少，因为他们没有足够的钱与我们交易。}
{22710}{}{那个鼠患严重的地方充满了帮派战争。若不是与阿迪特姆和枪械跑商的巨大贸易，我怀疑任何商人会冒险去那里。}
{22711}{}{那些是中心的水储存地。水商人控制着这些水塔。}
{22712}{}{旧城区在镇的东北侧。只有流浪汉和变种人在那里活动。我听说那里有个小偷的窝点。}
{22713}{}{那是所有商人出售商品的地方。武器店、军械库、友好借贷公司和马耳他猎鹰都在那个区域。}
{22714}{}{那是所有富有商人居住的地方。水商人的领袖达伦·高塔在那有个大宅。}
{22715}{}{吓唬小孩子听话的神话。}
{22716}{}{我对此一无所知。}

# DETHCLAW.MAP  (23200)

# HUBDWNTN.MAP  (23800)

{23800}{}{警察}
{23801}{}{水商人}
{23802}{}{赤色商队}
{23803}{}{远行商队}
{23804}{}{大教堂之子}
{23805}{}{死城}
{23806}{}{热点}
{23807}{}{废城}
{23808}{}{钢铁兄弟会}
{23809}{}{阴影沙地}
{23810}{}{洛杉矶墓园}
{23811}{}{水塔}
{23812}{}{旧城区}
{23813}{}{市中心}
{23814}{}{富人区}
{23815}{}{死亡爪}
{23816}{}{水芯片}
{23900}{}{警察由格林警长管理，以维持集市的法律和秩序。有些人认为他们更像是阻碍而不是帮助。}
{23901}{}{他们控制着集市的所有水源。他们占领了水塔，现在人们必须付钱才能得到水。}
{23902}{}{一群疯狂的商人，他们冒着极大风险以求出人头地。}
{23903}{}{一群性情温和的商人，他们提供公平的价格，而不需要冒险。}
{23904}{}{一个宗教狂热团体，崇拜所谓的“主人”。他们在镇子的东南角由水商人经营一家医院。}
{23905}{}{一个诡异的地方。有些人说那里被变异人类的幽灵所困扰，他们以正常人的大脑为食。它位于集市的东边。}
{23906}{}{有些传言说在这里的东南方向有一个地方被核弹击中。}
{23907}{}{那在我们北边。我们和他们之间有相当多的贸易。听说基利安和吉兹莫势不两立。}
{23908}{}{那地方在我们西北边。他们是一群崇拜科技的怪胎。非常神秘的人。}
{23909}{}{一个原始的小镇，位于我们北方很远的地方。关于他们的信息不多，因为他们没有足够的钱和我们交易。}
{23910}{}{那个老鼠成灾的地方充斥着帮派战争。如果不是因为与阿迪顿和枪械跑商的贸易繁荣，我怀疑任何商人会去那里。}
{23911}{}{那些是为集市储存水的地方。水商人控制着这些水塔。}
{23912}{}{旧城区在镇子的东北侧。只有流浪汉和变种人会在那里闲逛。我听说那里有一个盗贼巢穴。}
{23913}{}{那是所有商人出售商品的地方。武器店、军械库、友好贷款公司和马耳他之鹰都在那个区域。}
{23914}{}{那是所有富商居住的地方。水商人的领袖达伦·海塔沃在那里有一座大宅。}
{23915}{}{用来吓唬小孩子的神话。}
{23916}{}{我对此一无所知。}

# HUBHEIGT.MAP  (24400)

{24400}{}{警察}
{24401}{}{水商}
{24402}{}{深红商队}
{24403}{}{远行贸易公司}
{24404}{}{大教堂的信徒}
{24405}{}{死城}
{24406}{}{热点}
{24407}{}{废城}
{24408}{}{钢铁兄弟会}
{24409}{}{阴影沙地}
{24410}{}{洛杉矶墓园}
{24411}{}{水塔}
{24412}{}{旧城区}
{24413}{}{市中心}
{24414}{}{高地}
{24415}{}{死亡爪}
{24416}{}{水芯片}
{24500}{}{警察由格林警长管理，以维持集市的法律和秩序。有些人认为他们更多是阻碍而不是帮助。}
{24501}{}{他们控制了集市的所有水源。他们占领了水塔，现在人们必须付钱才能得到水。}
{24502}{}{一群疯狂的商人，他们冒着极大的风险以求出人头地。}
{24503}{}{一群性情温和的商人，他们提供公平的价格，而不需要冒险。}
{24504}{}{一个宗教邪教，崇拜一个叫做“主宰”的东西。他们在城镇东南侧的水商旁边经营一家医院。}
{24505}{}{一个令人毛骨悚然的地方。有些人说那里被变异人类所闹鬼，他们以正常人的大脑为食。它位于集市的东边。}
{24506}{}{有些传言说在这里的东南方向有一个地方被核弹击中。}
{24507}{}{那在我们的北边。我们和他们之间有相当多的贸易。据说基利安和吉兹莫势不两立。}
{24508}{}{那地方在我们的西北方向。他们是一群崇拜科技的技术狂，非常神秘的人。}
{24509}{}{一个原始的小镇，位于我们北方很远的地方。对他们知之甚少，因为他们没有足够的钱与我们交易。}
{24510}{}{那个老鼠成群的地方充满了帮派战争。如果不是与阿迪特姆和枪械商的巨大贸易，我怀疑任何商人会冒险前往那里。}
{24511}{}{那些是集市的水储存地。水商控制着这些水塔。}
{24512}{}{旧城区在镇子的东北侧。只有流浪汉和变种人在那里出没。我听说那里有个贼窝。}
{24513}{}{那是所有商人出售东西的地方。武器店、军械库、友好贷款公司和马耳他之鹰都在那个区域。}
{24514}{}{那是所有富有商人居住的地方。水商的领袖达伦·海塔沃在那里有个大宅子。}
{24515}{}{一个用来吓唬小孩子的神话。}
{24516}{}{我对此一无所知。}

# HUBOLDTN.MAP  (25000)

{25000}{}{警察}
{25001}{}{水商}
{25002}{}{赤色商队}
{25003}{}{远行商队}
{25004}{}{大教堂的孩子们}
{25005}{}{死城}
{25006}{}{热点}
{25007}{}{废城}
{25008}{}{钢铁兄弟会}
{25009}{}{阴影沙地}
{25010}{}{洛杉矶墓园}
{25011}{}{水塔}
{25012}{}{旧城区}
{25013}{}{市中心}
{25014}{}{高地}
{25015}{}{死亡爪}
{25016}{}{水芯片}
{25100}{}{警察由格林警长管理，以维持集市的法律和秩序。有些人认为他们更像是阻碍而非帮助。}
{25101}{}{他们控制着集市的所有水源。他们夺取了水塔的控制权，现在人们必须付钱才能得到水。}
{25102}{}{一群疯狂的商人，他们冒着极大的风险以求出人头地。}
{25103}{}{一群性情温和的商人，他们提供公平的价格，而不必冒险。}
{25104}{}{一个宗教邪教，崇拜一个叫做“主宰”的东西。他们在镇子的东南边由水商经营着一家医院。}
{25105}{}{一个阴森的地方。有些人说那里被变异人类的幽灵所困扰，他们以正常人的大脑为食。它位于集市的东边。}
{25106}{}{有些故事说在这里的东南方向有一个地方被核弹击中。}
{25107}{}{那在我们的北边。我们和他们之间有相当多的贸易。传闻中，基利安和吉兹莫势不两立。}
{25108}{}{那个地方在我们西北边。他们是一群崇拜科技的技术狂。非常诡异的人。}
{25109}{}{一个原始的小镇，位于我们北边很远的地方。对他们知之甚少，因为他们没有足够的钱与我们交易。}
{25110}{}{那个老鼠横行的地方充斥着帮派战争。如果不是因为与阿迪特姆和枪械跑商的贸易往来，我怀疑任何商人都不会冒险去那里。}
{25111}{}{那些是为集市储存水的地方。水商人控制着这些水塔。}
{25112}{}{老城区在镇子的东北侧。只有流浪汉和变种人在那里出没。我听说那里有个小偷的窝点。}
{25113}{}{那是所有商人出售商品的地方。武器店、军械库、友好贷款公司和马耳他之鹰都在那个区域。}
{25114}{}{那是所有富有商人居住的地方。水商人的领袖，达伦·海塔瓦在那有个大宅子。}
{25115}{}{用来吓唬小孩子的神话。}
{25116}{}{我对此一无所知。}

# HUBWATER.MAP  (25600)

{25600}{}{警察}
{25601}{}{水商人}
{25602}{}{赤红商队}
{25603}{}{远行商队}
{25604}{}{大教堂之子}
{25605}{}{死城}
{25606}{}{热点}
{25607}{}{废城}
{25608}{}{钢铁兄弟会}
{25609}{}{阴影沙地}
{25610}{}{洛杉矶墓场}
{25611}{}{水塔}
{25612}{}{老城区}
{25613}{}{市中心}
{25614}{}{高地}
{25615}{}{死亡爪}
{25616}{}{水芯片}
{25700}{}{警察由格林警长管理，以维护集市的法律和秩序。有些人认为他们更多是个阻碍而非帮助。}
{25701}{}{他们控制着集市的所有水源。他们夺取了水塔的控制权，现在人们必须付钱才能得到水。}
{25702}{}{一群疯狂的商人，他们冒着极大的风险以求登顶。}
{25703}{}{一群性情温和的商人，他们提供公平的价格而无需冒险。}
{25704}{}{一个宗教邪教，崇拜一个叫做大师的东西。他们在镇子的东南侧靠近水商人处经营一家医院。}
{25705}{}{阴森的地方。有些人说那里被变异人类的幽灵所困扰，他们以正常人的大脑为食。它位于集市的东边。}
{25706}{}{有些传闻说在这里东南方向有个地方被核弹击中了。}
{25707}{}{那在我们北边。我们和他们之间有不少贸易。据说Killian和Gizmo水火不容。}
{25708}{}{那个地方在这里的西北方。他们是一群崇拜科技的技术狂。非常诡异的人。}
{25709}{}{一个原始的城镇，远在我们北边。对他们知之甚少，因为他们没有足够的钱和我们交易。}
{25710}{}{那个鼠患成灾的地方充斥着帮派战争。要不是和Adytum及枪械商的贸易兴旺，我怀疑任何商人都不敢去那里。}
{25711}{}{那些是为枢纽城储水的塔楼。水商控制着这些塔楼。}
{25712}{}{旧城区在城镇的东北侧。只有流浪汉和变种人在那里活动。我听说那里有个盗贼窝点。}
{25713}{}{那是所有商人出售商品的地方。武器店、军械库、友好贷款公司和马耳他之鹰都在那个区域。}
{25714}{}{那是所有富商居住的地方。水商的领袖Daren Hightower在那里有个大宅。}
{25715}{}{一个用来吓唬小孩子乖乖听话的神话。}
{25716}{}{我对此一无所知。}

# GLOW1.MAP     (26200)
# GLOW2.MAP     (26800)


#
# LABLADES.MAP
#
#

#  ======================================================================
#    BLADES
# Info Level 1 [People who know nothing]
{27400}{}{阿迪特姆}
{27401}{}{追随者}
{27402}{}{大教堂}
{27403}{}{撕裂者}
{27404}{}{刀锋帮}
{27405}{}{枪械商}
{27406}{}{枢纽城}
{27407}{}{废城}
{27408}{}{水芯片}
{27409}{}{剃刀}
{27410}{}{墓园城}
{27411}{}{辉光镇}
{27412}{}{骨园}
{27500}{}{他们是西边的一个城镇。}
{27501}{}{一群懦夫。}
{27502}{}{宗教狂热分子。}
{27503}{}{我们的死敌！}
{27504}{}{就是我们！}
{27505}{}{他们有时会卖枪给我们。}
{27506}{}{我想这是个交易的地方。}
{27507}{}{没听说过。}
{27508}{}{什么？}
{27509}{}{她是我们的领袖，镇上最厉害的女人！}
{27510}{}{死灵什么？真恶心。}
{27511}{}{你在开玩笑吧？}
{27512}{}{这里是尸骨城。}


# Info Level 2 [People who know something]
{27600}{}{亚迪图姆}
{27601}{}{追随者}
{27602}{}{大教堂}
{27603}{}{撕裂者}
{27604}{}{刀锋帮}
{27605}{}{枪械跑商}
{27606}{}{中心城}
{27607}{}{废城}
{27608}{}{水芯片}
{27609}{}{剃刀}
{27610}{}{死城}
{27611}{}{辉光}
{27612}{}{尸骨城}
{27700}{}{他们是西南方一群弱者的村庄。}
{27701}{}{西边那些可悲的和平传教士。如果我们不忙着对付撕裂者，早就把他们击溃了。}
{27702}{}{宗教狂徒。无害且无用。}
{27703}{}{我们在西边的死敌，很快就会被消灭！}
{27704}{}{我们是刀锋帮！永远记住这一点！}
{27705}{}{他们曾经是个帮派，但现在变软了。不过他们卖的枪还不错。}
{27706}{}{商人和贸易者。}
{27707}{}{我听说过那个地方，但对它一无所知。}
{27708}{}{什么？}
{27709}{}{剃刀是我们中最出色的战士。她会带领我们走向胜利。}
{27710}{}{那是关于一个食人族城市的故事，用来吓唬小孩的。}
{27711}{}{这一定是核弹爆炸的地方。}
{27712}{}{这里是白骨镇。}


# Info level 3 [People who know more than something but less than everything]
{27800}{}{阿迪特姆}
{27801}{}{追随者}
{27802}{}{大教堂}
{27803}{}{撕裂者}
{27804}{}{刀锋帮}
{27805}{}{枪械跑商}
{27806}{}{集散地}
{27807}{}{废城}
{27808}{}{水芯片}
{27809}{}{剃刀}
{27810}{}{死城}
{27811}{}{辉光城}
{27812}{}{白骨镇}
{27900}{}{别被愚弄了。阿迪特姆看起来像个小村庄，但他们的监管者很强硬。}
{27901}{}{哼，别让我说起他们。他们没有勇气和胆量去战斗。}
{27902}{}{他们是南边一个大教堂里的邪教徒。看起来无害，但那里有些古怪的事情在发生。}
{27903}{}{撕裂者就像肮脏的狗——凶残、近亲繁殖且愚蠢。}
{27904}{}{看到我的刀了吗？我们自己做的。每个人都做自己的刀，这就是我们名字的由来。}
{27905}{}{他们从集散地下来寻找地盘，但决定成为商人而不是战士。}
{27906}{}{那是东边的一个贸易城市。那里的商人有时会来这里与阿迪特姆和枪械跑商交易。}
{27907}{}{我想它在东北方向。是个小城市。}
{27908}{}{什么？}
{27909}{}{剃刀是我们的领袖和冠军。我毫不怀疑她的经验最终会让我们战胜那些撕裂者。}
{27910}{}{在这里的远东，据说那里住着吃人肉的食尸鬼。我可不想和食尸鬼打架。}
{27911}{}{那应该是某个被核弹直接击中的地方的废墟。我想它在很南边。}
{27912}{}{这里是白骨镇。}
#  ======================================================================


#
# LARIPPER.MAP  (28000)
#
#

#======================================================================
#
#RIPPERS
#
#The Rippers will not engage in dialog, and thus have no
#tell-me-abouts.
#
#======================================================================


#
# LAGUNRUN.MAP  (28600)
#
#

#  ======================================================================
#   GUN RUNNERS
#Info Level 1 [People who know nothing]
{28600}{}{阿迪特姆}
{28601}{}{追随者}
{28602}{}{大教堂}
{28603}{}{裂口帮}
{28604}{}{刀锋帮}
{28605}{}{枪械商}
{28606}{}{集市}
{28607}{}{废城}
{28608}{}{水芯片}
{28609}{}{墓园}
{28700}{}{一个在南边的小村庄。}
{28701}{}{南边的一群嬉皮士。}
{28702}{}{你是指那些穿棕色长袍的人吗？}
{28703}{}{西边的一个火爆帮派。}
{28704}{}{东边的一个狡猾帮派。}
{28705}{}{怎么了？}
{28706}{}{我们从他们那里买枪，然后直接卖给你！}
{28707}{}{是的，集市北边的一个小城市。}
{28708}{}{什么？}
{28709}{}{这里是墓园。}

# Info Level 2 [People who know something]
{28800}{}{阿迪图姆}
{28801}{}{追随者}
{28802}{}{大教堂}
{28803}{}{裂口帮}
{28804}{}{刀锋帮}
{28805}{}{枪械商}
{28806}{}{集市}
{28807}{}{废城}
{28808}{}{水芯片}
{28809}{}{墓园}
{28900}{}{那是南边的一个小村庄。他们防御得很好。}
{28901}{}{一群和平主义者躲在南边。我们应该把他们解决掉。}
{28902}{}{哦，是那些疯狂的老和尚。他们真是疯了。他们的大教堂就在墓园南边。}
{28903}{}{嘿，他们可能很傻，但他们确实买了很多枪！}
{28904}{}{他们总是用那些奇怪的振动刀，我真想弄到一个。不过至少他们也买些枪。}
{28905}{}{你在跟我们说话。}
{28906}{}{这是东边一个大型贸易中心。我们和商场的商人交易，买卖武器和护甲。}
{28907}{}{商场北边的小镇。有点严格。}
{28908}{}{没听说过。}
{28909}{}{我们在墓园的北边。}

# Info Level 3 [People who know more than something but less than everything]
{29000}{}{阿迪坦}
{29001}{}{追随者}
{29002}{}{大教堂}
{29003}{}{撕裂者}
{29004}{}{刀锋帮}
{29005}{}{枪械商}
{29006}{}{商场}
{29007}{}{废城}
{29008}{}{水芯片}
{29009}{}{墓园}
{29100}{}{他们是南边的小镇，不和我们打交道。我一点也不关心他们。}
{29101}{}{他们试图把所有人都转化成他们的和平方式，同时躲在南边的图书馆里。他们对生意没什么帮助！}
{29102}{}{大教堂是墓园南边的一座大教堂，一些奇怪的邪教在那里崇拜黑暗之神。我觉得他们很怪。}
{29103}{}{撕裂者是一大家子，字面意义上的。他们很难打交道，如果他们不认识你，就别试了。他们在我们西南边有个大陷阱堡垒。如果你愚蠢到去拜访，注意地雷。}
{29104}{}{他们把东南边的几个小建筑改造成了他们的家。他们组织得很好，比撕裂者聪明。有时也允许外人加入。他们的领袖，剃刀，是个强悍的女人。}
{29105}{}{就是我们。这里卖枪给刀锋帮和撕裂者赚了不少钱。}
{29106}{}{那是东边的贸易城市，我们在那里拿枪和做交易。他们派出商队到处跑。如果商队在阿迪坦出现，你可能可以跟着一起旅行。}
{29107}{}{这是商场北边的小边境镇。那里有个很棒的赌场，但镇上的警长有点太过严厉。}
{29108}{}{我不知道那是什么。}
{29109}{}{这是墓园的北边。有趣的是，外面的人用它作为诅咒——如果有什么不好，他们就说它“咬骨头”。但一旦习惯了，也没那么糟。}
#  ======================================================================


# CHILDEAD.MAP  (29200)

# MBDEAD.MAP    (29800)

# MOUNTN1.MAP   (30400)
# MOUNTN2.MAP   (31000)
# FOOT.MAP      (31600)
# TARDIS.MAP    (32200)
# TALKCOW.MAP   (32800)
# USEDCAR.MAP   (33400)
# BRODEAD.MAP   (34000)
# DESCRVN1.MAP  (34600)
# DESCRVN2.MAP  (35200)
# MNTCRVN1.MAP  (35800)
# MNTCRVN2.MAP  (36400)
