{100}{}{圣骑士}
{101}{}{保持警惕，新兵！}
{102}{}{看起来不错。继续保持。}
{103}{}{你好，新兵，一切都很安全。}
{104}{}{嗨，兄弟}
{105}{}{。}
{106}{}{抱歉，我不该和任何人说话。你知道的。}
{107}{}{如果你有任何问题，应该去找塔鲁斯或马森。}
{108}{}{如果你有技术问题，白天可以去图书馆找芙蕾。}
{109}{}{菱形是我的偶像。}
{110}{}{我真希望现在在训练。这个守卫任务真是浪费时间。}
{111}{}{芙蕾是我的偶像。}
{112}{}{马可！}
{113}{}{波罗！}
