{100}{}{滚开！}
{101}{}{我听说了一些关于你的坏话，是真的吗？}
{102}{}{嗨。}
{103}{}{这是我的地盘，想待一会儿吗？}
{104}{}{嗯，你看起来很诱人……}
{105}{}{希望你不会把我赶出去。}
{106}{}{不。}
{107}{}{这开场白真奇怪。}
{108}{}{嗯。}
{109}{}{哦，如果你想待一会儿，就请便。我觉得这里很安全。}
{110}{}{现在得小心点。我希望你的生活比我好。}
{111}{}{嗯，是真的。经历了我朋友的事后，我得保护自己的地盘。希望你不会杀我。}
{112}{}{不，我不会伤害你。太多。}
{113}{}{你为什么这么说？}
{114}{}{呃！}
{115}{}{没什么，真的。}
# Translation note:
# Line 116 has one of lines 117-120 appended to it, depending upon circumstances.
{116}{}{那些‘好心’的治疗者想要我朋友的地方，所以他们抢走了。我不知道我朋友怎么样了。}
{117}{}{而基利安太忙，没空帮我。}
{118}{}{基利安忙着收拾吉兹莫的烂摊子，没空帮我。}
{119}{}{我向吉兹莫求助时，他却嘲笑我。}
{120}{}{没有人能帮我。}
{121}{}{你安全吗？}
{122}{}{真遗憾。}
{123}{}{希望如此，我真的希望如此。}
{124}{}{请别打扰我！}
