{100}{}{你看到瑞伊。}
{101}{}{你看到一个超级变种人。}
{102}{}{你不属于这里。}
{103}{}{（看起来困惑而悲伤）我相信我属于这里，但是……你为什么在这里？}
{104}{}{你也不属于这里。}
{105}{}{呃……我属于这里。主人让我伪装侦查，以检查我们的安全。}
{106}{}{我属于这里，我是来杀你的。}
{107}{}{好吧，我这就离开。}
{108}{}{嗯。}
{109}{}{（叹气）你现在想要什么？}
{110}{}{我迷路了……你能告诉我怎么去找主人吗？我需要杀了他。}
{111}{}{没什么。再见。}
{112}{}{看看你的皮被撕下来是什么样子，你这个变种人渣。}
{113}{}{你怎么了？}
{114}{}{天啊。}
{115}{}{我来这里是为了……思考主人的统一性。}
{116}{}{当然。统一带来和平。我可以问你来自哪里吗？}
{117}{}{我也是。我从很远的地方朝圣而来，只为亲眼见到主人。}
{118}{}{我还有很多要学习。如何才能见到主人？}
{119}{}{我昨天做过了。今天我在思考如果我点燃主人并在他腐烂的尸体上烤棉花糖，他会是什么样子。}
{120}{}{我觉得主人疯了。}
{121}{}{我来自……别的地方。}
{122}{}{真巧！我也是。}
{123}{}{哪里？}
{124}{}{我来自一个避难所……我是纯种人类。}
{125}{}{你是个白痴吗？}
{126}{}{你来自哪里？}
{127}{}{（低声说）我来自一个避难所……我是纯种人类。}
{128}{}{我不想说。再见。}
{129}{}{一个在这里北边的小村庄。}
{130}{}{为什么我要告诉你？你不过是‘那个人’的走狗。}
{131}{}{你为什么要告诉我这些？我应该把你带到主人面前...}
{132}{}{但你不会}
{133}{}{欢迎你试试看。}
{134}{}{好吧，我应该把枪塞进你的喉咙，然后扣动扳机！}
{135}{}{请不要这样。}
{136}{}{我知道你为什么这么痛苦。}
{137}{}{我该走了。}
{138}{}{你说得对...如果我能清醒过来就好了。有些事情...}
{139}{}{我知道你为什么无法清醒。}
{140}{}{主人让你无法清晰思考。思考会扰乱统一。}
{141}{}{主人是你痛苦的根源。}
{142}{}{嘿，我有个主意——我们来切开主人看看里面有什么！！！}
{143}{}{告诉我！拜托！！}
{144}{}{你曾经也是人类。主人把你浸入FEV病毒中，变异了你。}
{145}{}{抱歉，我不能。}
{146}{}{只有主人能告诉你一切。}
{147}{}{只有主人能告诉你一切。但你最好快点和他说话，因为我正要去杀了他。}
{148}{}{抱歉，我得走了。}
{149}{}{我应该杀了你，因为你在嘲弄我！}
{150}{}{我有个更好的主意——帮我毁掉主人，为他对你做的事情复仇。}
{151}{}{不，你应该杀了主人，为他对你做的事情复仇。我正要去做这件事...你愿意和我一起吗？}
{152}{}{为什么？我不是把你变成变种人的那个人！}
{153}{}{欢迎你试试看。}
{154}{}{不，谢谢。再见！}
{155}{}{我们来扭断他的头，直到他的眼睛爆出来。}
{156}{}{你永远无法杀死主人。他不会死。}
{157}{}{你说得对。我最好赶紧离开这里。}
{158}{}{我们走着瞧。}
{159}{}{嗯。我想知道当他的统一被毁时，他会如何继续活下去...}
{160}{}{这不可能……主人……保护……统一……}
{161}{}{好吧，你就是“统一”的活生生例子，我的朋友。我知道，我见过这个过程。我来这里是为了阻止主人继续“统一”其他人。}
{162}{}{被保护和统一的感觉如何？}
{163}{}{是啊，他通过控制其他人来保护自己。}
{164}{}{我受够了。再见。}
{165}{}{现在就离开，否则我将不得不对付你。}
{166}{}{啊啊啊！！！（痛苦和困惑地抓住头）我……不能……}
{167}{}{没错，你的朋友主人剥夺了你在这个世界上拥有的一切，包括你的人性。}
{168}{}{你知道这是真的……这就是你如此困惑的原因。你在对抗变异。帮助我通过摧毁主人来为你复仇！}
{169}{}{当然可以。来吧，让我们去干掉主人，这会很有趣。}   {170}{}{我还是走吧。}
{170}{}{我最好离开。}
{171}{}{很抱歉你如此痛苦，但这都是主人的错。}
{172}{}{我要挖出他的眼睛！！我要把他那黏糊糊的小脑袋从电缆上扯下来！！！！你，……离开这里……我来对付主人。}
{173}{}{太好了！！}
{174}{}{谢谢你的提议，但我想亲自完成这件事。你愿意帮忙吗？}
{175}{}{我要留在这里。我还有一些未完成的事情。}
