{100}{}{你看到拉兹洛。}
{101}{}{抱歉，我帮不了你。}
{102}{}{不能还是不愿意？}
{103}{}{拉兹洛看了你一会儿，然后转过身去。}
{104}{}{你看起来很焦虑。需要帮助吗？}
{105}{}{坦迪被绑架了。}
{106}{}{嗯，坦迪宝贝。}
{107}{}{坦迪不见了？这真是件可怕的事。我希望他们能找到她。}
{108}{}{嗯，坦迪不见了？我很难相信，但也许她和塞斯私奔了。我知道他们最近一直互相注视。阿拉德什总是有点古板，也许这对她来说太过分了。}
{109}{}{嗯，我没想到这一点。}
{110}{}{我不这么认为，我觉得她是被绑架了。}
{111}{}{也许吧，我去问问其他人。}
{112}{}{太可怕了！如果真是这样，我希望她没有受伤。谁在找她？}
{113}{}{几乎所有人。}
{114}{}{很多人，包括我。}
{115}{}{我希望能在为时未晚之前找到她。}
{116}{}{如果她受伤了，情况可能会很糟。拿着这些……希望你用不上。}
{117}{}{我希望坦迪能早点回来。阿拉德什现在一定很难受。}
{118}{}{我听说你帮助救了坦迪。恭喜并感谢你。任何时候需要治疗，来找我。}
{119}{}{我的悲伤无以言表。坦迪，我好朋友唯一的孩子，不见了。我现在无法工作。}
{120}{}{我是拉兹洛。我能帮你吗？}
{121}{}{现在不需要，但很高兴认识你。}
{122}{}{我需要治疗。}
{123}{}{嗯哼！}
{124}{}{嗯，我觉得你脑子还不如布拉明多。好吧，让我看看你有没有受伤。}
{125}{}{嗯，你看起来没事。也许以后再说？}
{126}{}{让我看看。}
{127}{}{我已经给了你我能给的。祝好运。}
{128}{}{嗯，我不喜欢你的样子。希望你是来办事的，并且很快就会离开……}
{129}{}{不用防备，我只是随便看看}
{130}{}{救命，我需要治疗。}
{131}{}{你好，又见面了。我能帮你什么忙？}
{132}{}{你好，又见面了。只是路过。}
{133}{}{我需要治疗。}
{134}{}{呃！}
{135}{}{很高兴再次见到你。祝你有美好的一天。}
{136}{}{当然，是你啊。现在有什么事？}
{137}{}{没什么。}
{138}{}{我需要治疗。}
{139}{}{鲁基！}
{140}{}{当然，你需要。}
{141}{}{我能帮你吗？}
{142}{}{没有。}
{143}{}{我需要治疗。}
{144}{}{我中毒了！}
{145}{}{你对辐射蝎了解多少？}
{146}{}{我有一份辐射蝎毒液的样本，你能做些什么吗？}
{147}{}{鲁基！}
{148}{}{抱歉，我无法治疗任何毒素。我没有合适的材料来制作有效的解毒剂。}
{149}{}{来，让我看看。}
{150}{}{没错，正如我所想。让我拿解药。}
{151}{}{你现在看起来没事了。以后小心点。}
{152}{}{再来看看，但下次保持健康。}
{153}{}{不太多。它们似乎是北美皇帝蝎的极大化版本。与我的医学知识相悖，它们的毒性不仅没有减弱，反而更强了。赛斯一直在猎杀它们，这对我的一些测试有帮助。}
{154}{}{至于如此庞大的生物如何可能通过自然进化，甚至是辐射诱导的突变产生，我无法理解。}
{155}{}{谢谢。}
{156}{}{你看起来很有学问。你在这里做什么？}
{157}{}{还有其他事吗？}
{158}{}{它们似乎对光很敏感，是夜行性的。如果我能得到它们毒液的样本，特别是尾部的毒囊，我就能制作解毒剂。}
{159}{}{谢谢。}
{160}{}{垃圾镇的莫比德医生教了我一些。住在石头屋里并不意味着我们就不聪明或没受过教育。祝你有美好的一天。}
{161}{}{让我看看这个囊！是的，我可以用这个做点什么。}
{162}{}{这是免费的样品。它对抗辐射蝎子的毒刺效果很好，当然，也有作为通用解毒剂和毒药治疗的潜力。}
{163}{}{太晚了。明早再来吧。}
{164}{}{但我需要你的帮助。}
{165}{}{我想杀一些辐射蝎子。你有任何能帮上忙的东西吗？}
{166}{}{我在找坦迪。你能帮忙吗？}
{167}{}{嗯。}
{168}{}{嗯？！那是什么？太好了，我被北方的大咕哝兽吵醒了。明早再来吧。}
{169}{}{你受伤了吗？}
{170}{}{是的。}
{171}{}{没有。}
{172}{}{如果你继续打扰我睡觉，你就会受伤。现在明早再来吧。}
{173}{}{伟大的布拉明！你怎么不早说？}
{174}{}{呃，我说了……}
{175}{}{你伤得不重。我建议好好睡一觉，休息一下；你会自然痊愈的。}
{176}{}{你伤得不重，胆小鬼。明早再来吧。}
{177}{}{哎哟，看起来有点疼。这要25美元。}
{178}{}{好的，给你。}
{179}{}{我没有足够的钱。}
{180}{}{哦，伟大的布拉明！这非常非常严重。需要50美元。}
{181}{}{好的，给你。}
{182}{}{我没有足够的钱。}
{183}{}{你怎么还能走？！这看起来非常严重。我们需要一些特别的祈祷和很多运气。更不用说100美元了。}
{184}{}{好的，给你。}
{185}{}{我没有足够的钱。}
{186}{}{你没有足够的钱！很抱歉，但我的职业道德不允许我免费治疗。等你有足够的钱再来吧。}
{187}{}{你能接受以物易物吗？}
{188}{}{谢谢你什么都没做。}
{189}{}{抱歉，今天不行。}
{190}{}{为什么我能帮你杀辐射蝎？我是医生，不是战士。你应该去找阿拉迪什，或者坦迪，甚至她的男朋友赛斯。别来烦我。}
{191}{}{我需要一些解毒的东西。}
{192}{}{如果我有他们毒液的样本，我可以制作解药。}
{194}{}{我不这么认为，我觉得她被绑架了。}
{195}{}{也许，我去找其他人聊聊。}
{196}{}{这需要一点时间。来，去后面放松一下。你可能会因为君佳汁有点头疼。来，来……}
{197}{}{我已经给了你我能给的所有东西。祝你好运。}
{300}{}{你获得了250点经验值，帮助制作了解毒剂。}
{301}{}{好，我给你？}
{302}{}{努加。}
{303}{}{蝎子，蝎子？}
{304}{}{我给这个？}
{305}{}{那用辐射蝎的尾巴怎么样？}
{306}{}{让我看看毒囊！是的，我可以用这个做点什么，并为你治疗，感谢你的馈赠。}
{307}{}{这需要一点时间。来，去后面放松一下，我处理毒囊。你可能会因为君佳汁有点头疼。来，来……}
{308}{}{请不要拿走我的东西。}


{1000}{}{汗帮}
{1001}{}{加尔}
{1002}{}{废城}
{1003}{}{阴影镇}
{1004}{}{枢纽}
{1005}{}{水}
{1006}{}{坦迪}
{1007}{}{阿拉迪什}
{1008}{}{赛斯}
{1009}{}{拉兹洛}
{1010}{}{沙地}

{1100}{}{他们是一个无视法律的团伙，假装是来自远古的人。}
{1101}{}{他是汗帮的首领。他是曾经踏足阴影镇的最危险的人之一。他以铁腕统领掠夺者部落。}
{1102}{}{往西南方向4到6天。偶尔有不错的交易，但更多时候，他们试图坑我们。}
{1103}{}{你正站在这里。}
{1104}{}{比垃圾镇更南边。中心城是我听说过的最大城市。那里的居民至少有一千人。}
{1105}{}{抱歉，我帮不了你。}
{1106}{}{她是阿拉迪什的女儿。将来她可能会领导我们，但她必须学会克制自己。}
{1107}{}{他是我们社区的领袖，也是一个真正的英雄。你总能在公共大厅找到他工作。}
{1108}{}{他与阿拉迪什合作，确保我们的安全。}
{1109}{}{那就是我。我是阴影镇的医生。}
{1110}{}{你正站在这里。}
