{100}{}{你看到：避难所居民。}
{101}{}{你看到：心烦的避难所居民。}
{102}{}{}
{103}{}{}
{104}{}{}
{105}{}{谢谢你拯救了我们。}
{106}{}{我本来有点不确定你能做到，但现在我信任你了。}
{107}{}{谢谢你！谢谢你！}
{108}{}{你是个英雄。我的小鲍比长大后想成为像你一样的人。我不知道我是否喜欢这样。}
{109}{}{你是个女英雄。我的小鲍比长大后想成为像你一样的人。我不知道我是否喜欢这样。}
{110}{}{你真是个好人！}
{111}{}{你真是个好姑娘！}
{112}{}{你确定这里需要这个吗？}
{113}{}{那是武器！}
{114}{}{你真的用这个对付过别人吗？}
{115}{}{你为什么觉得在这里携带武器是必要的？}
{116}{}{你好！搜索进展如何？}
{117}{}{挺顺利的。}
{118}{}{不太好。}
{119}{}{唉。}
{120}{}{嗯，听到这个很高兴。继续努力吧，我想。}
{121}{}{没问题。}
{122}{}{我们知道没有希望。我不认为我们能及时得到新的芯片。我觉得我们中的一些人应该在为时已晚之前搬到外面去。}
{123}{}{我不认为这是个好主意。}
{124}{}{嗯，也许这样最好。}
{125}{}{请快点。}
{126}{}{别担心，我会找到芯片的。}
{127}{}{也许你应该来参加我们的会议。特蕾莎有一些好主意。我们每天晚上五点在她的房间（二层）见面。}
{128}{}{我会考虑的。}
{129}{}{不用了，谢谢。我有工作要做。}
{130}{}{特蕾莎就是这么想的。她已经计划好了。我们打算很快离开避难所。}
{131}{}{祝好运。}
{132}{}{我觉得你们现在还不应该离开。}
{133}{}{监督者为什么选你？显然你连鞋带都找不到，更别提新的水芯片了。算了。}
{134}{}{呃。}
{135}{}{你不是有任务要做吗？快去找芯片吧！}
{136}{}{别告诉我该怎么做，废物！}
{137}{}{好吧！真是有些人。}
{138}{}{咕噜！}
{139}{}{你已经决定了这个避难所所有人的命运，叛徒。希望你对此感到满意。}

{1000}{}{监督者}
{1001}{}{避难所13}
{1002}{}{避难所-13}
{1003}{}{避难所}
{1100}{}{监督者只是想把所有人都控制在这里。我们需要自己走出去看看这个世界。}
{1101}{}{避难所一直是我们的家，但它已经无法再持续下去了。是时候建立一个新家了。}
{1102}{}{避难所一直是我们的家，但它已经无法再持续下去了。是时候建立一个新家了。}
{1103}{}{避难所一直是我们的家，但它已经无法再持续下去了。是时候建立一个新家了。}
