{100}{}{你看到一个治安官，是阿迪特姆的守卫之一。}
{101}{}{}
{102}{}{在这里时，控制好你的武器。}
{103}{}{欢迎来到阿迪特姆，陌生人。小心点，我们会盯着你。}
{104}{}{我想进去。}
{105}{}{我可以问你几个问题吗？}
{106}{}{呃。。。}
{107}{}{齐默曼可能有事需要你做。进来吧，但记住，我们会盯着你。}
{108}{}{欢迎回来！你随时都可以来。}
{109}{}{你不是有工作要做吗？处理完再回来。}
{110}{}{走开！}
{111}{}{你现在想要什么？}
{112}{}{我想进去。}
{113}{}{}
{114}{}{没什么，算了。}
{115}{}{}
{116}{}{不。}
{117}{}{你想了解什么？}
{118}{}{你在这里做什么？}
{119}{}{你能多告诉我一些关于骨园的事吗？}
{120}{}{我怎么才能进去？}
{121}{}{你对大教堂的孩子和启示录追随者了解多少？}
{122}{}{没事，谢谢。}
{123}{}{我是治安官之一。我们的职责是维护阿迪特姆的和平，保护小镇。我们的头儿凯莱布可以告诉你更多。}
{124}{}{我们东边是追随者，他们是一群和平狂。东边还有刀锋帮，如果你问我，他们就是一群流氓。再往南一点是大教堂，孩子们在那里建立了他们的宗教中心。}
{125}{}{抱歉，我们必须对陌生人小心。太危险了。也许你可以为齐默曼做些工作。}
{126}{}{完成你的工作。}
{127}{}{当然，你随时都欢迎来！}
{128}{}{他们都是一群疯子。追随者希望每个人都和平快乐。他们没意识到世界太残酷了。}
{129}{}{孩子们在南边的大教堂里崇拜某种神明。他们有一家医院，但他们有点太古怪了，难以信任。}
{130}{}{警告过你要管好你的武器！}
{131}{}{在这里最好把武器收起来。}
{132}{}{小偷，是吧？让我告诉你我们这里怎么对付你这种人！}
{133}{}{[完成]}

{134}{}{小心点。}
{135}{}{我们在盯着你。}
{136}{}{规矩点。}
{137}{}{看什么呢。}
{138}{}{想要什么。}

{139}{}{看来我们和你没什么好说的了，老头。}

{1000}{}{阿迪特姆}
{1001}{}{追随者}
{1002}{}{大教堂}
{1004}{}{刀锋帮}
{1005}{}{奔跑者}
{1006}{}{枢纽镇}
{1007}{}{废城}
{1008}{}{芯片}
{1009}{}{商店}
{1010}{}{齐默尔曼}
{1011}{}{死城}
{1012}{}{辉光}
{1013}{}{监管者}
{1014}{}{拾荒者}
{1015}{}{骨园}

{1100}{}{就在这里。}
{1101}{}{他们住在这里的东边。}
{1102}{}{在我们南边一段距离。}
{1104}{}{他们在这里的北边。}
{1105}{}{他们在刀锋帮的东边，然后在死亡爪的北边。}
{1106}{}{我们和他们进行交易。}
{1107}{}{那不是这里北边的一个城市吗？}
{1108}{}{什么？}
{1109}{}{泰恩的商店在靠近大门的地下。}
{1110}{}{他是市长。}
{1111}{}{我听说在东边。}
{1112}{}{那是个传说。}
{1113}{}{我们保护阿迪特姆。}
{1114}{}{他们出去获取物资。}
{1115}{}{这里是骨园。}
