{100}{}{你感到后颈的汗毛竖起。你从前方的走廊感受到某种东西。当你认出前方墙壁上的肉块是人类的身体部位时，胃里一阵翻腾。最糟糕的是，它在动，还在呼唤你。}
{101}{}{你的鼻子开始流血。你听到脑海中有声音在呼唤你的名字。黑暗瞬间笼罩了你的视线，但你很快恢复过来。}
{102}{}{一个声音在呼唤你。你转过头，看到一个已被遗忘的朋友的影像，显然已经死去。蛆虫从她腐烂的下颚掉落，你的头痛加剧。}
{103}{}{前行变得愈发艰难。你的脚似乎被牢牢粘在地板上。你低头一看，地板的肉质正在顺着你的腿往上爬，牙齿在啃噬你的膝盖。而你的头痛却愈加剧烈。}
{104}{}{有什么东西吸引了你的注意力，天花板上有一道闪光，接着一根骨刺刺穿了你的眼睛！随之而来的是死者和被折磨者的思绪！}
{105}{}{你感到头痛欲裂，仿佛他人的罪孽在你的灵魂上翻涌。而更糟糕的是，你自己的罪孽也在回应它们。就像疯子一样，它们在你的精神中厮杀，撕扯着你的个性。}
{106}{}{你的头部因他人的入侵性思绪而剧烈跳动。疼痛不断加剧。突然，那种令人难以忍受的痛苦瞬间消失得无影无踪。你跌坐在地，痛哭流泪。然而，总觉得有什么地方不对劲。}
{107}{}{你头部的疼痛感没有之前那么强烈了。这条奇怪走廊的影响似乎减弱了。}
