
#
# Coastal encounter messages
#

{100}{}{你看到几个奇怪的漂浮生物...}
{101}{}{你看到一小群老鼠迅速逼近。}
{102}{}{你看到一群农民正被袭击者攻击！}
{103}{}{你看到几个人在钓鱼。}
{104}{}{附近有一具被部分吃掉的可怕尸体。}
{105}{}{你偶然发现了一些水池...}
{106}{}{因极度口渴，你喝了一些水... 味道不太好。}
{107}{}{水看起来高度辐射且污浊。}
{108}{}{啊...}
{109}{}{啊...}
{110}{}{呸！}
