{100}{}{这看起来像是一个机器人控制终端。}
{101}{}{没有响应。}
{102}{}{重新编程完成。正在初始化语音通信子系统。正在初始化个性子系统。[咔嗒！] 这个终端可以为您提供什么服务？}
{103}{}{嗯。}
{104}{}{你是谁或是什么？}
{105}{}{你的功能是什么？}
{106}{}{显示程序列表。}
{107}{}{输入错误。命令不在集合中。请重新陈述。}
{108}{}{嗯。}
{109}{}{啦啦。}
{110}{}{脑！}
{111}{}{小问题！}
{112}{}{结束通信子系统。结束进程。}
{113}{}{这个终端是一个人工智能。这个终端是一个WLAN矩阵网络的一部分，用于优化远程单元操作。}
{114}{}{谢谢。呃，结束输入。}
{115}{}{你控制的远程单元是什么？}
{116}{}{正在运行什么程序？}
{117}{}{这个终端负责本设施内所有通用原子国际工业机器人的操作。}
{118}{}{请更具体一些。}
{119}{}{正在运行什么程序？}
{120}{}{这种类型的工业机器人通常被称为“机器人脑”。[咔嗒！] 通用原子国际拥有世界上最好的工业机器人。购买两个或更多GAI机器人可享优惠！“管家先生”型号特价！[咔嗒！] 广告小程序终止。}
{121}{}{正在运行什么程序？}
{122}{}{当前应用程序有：设施维护v2.1，移动v4.8b，修理v0.8a，害虫控制v1.4，纸牌v1.0和传感器'76。}
{123}{}{终止移动。}
{124}{}{终止传感器。}
{125}{}{终止害虫控制。}
{126}{}{终止纸牌。}
{127}{}{谢谢。结束输入。}
{128}{}{尝试终止。[咔嗒！] 系统错误。无法终止应用程序。没有删除权限。}
{129}{}{嗯，调整移动参数。}
{130}{}{调整传感器参数。}
{131}{}{修改害虫控制。}
{132}{}{玩红心大战。}
{133}{}{谢谢。结束输入。}
{134}{}{当前应用：移动 v4.8b。当前设置：[最大/半速/最小]。更改为：最大，半速，或最小。}
{135}{}{最大移动。}
{136}{}{半速移动。}
{137}{}{最小移动。}
{138}{}{当前应用：传感器 '76。当前设置：[全开/最小]。更改为：全开，或最小。}
{139}{}{全开传感器。}
{140}{}{最小传感器。}
{141}{}{当前应用：害虫控制 v1.4。当前设置：[咔嚓！] 未授权。更改为：[咔嚓！] 全部，无，小型生物，大型生物，或未授权。}
{142}{}{全部害虫。}
{143}{}{无害虫。}
{144}{}{小型生物害虫。}
{145}{}{大型生物害虫。}
{146}{}{未授权害虫。}
{147}{}{应用红心大战运行中。用户胜利。[咔嚓！] 感谢游戏。}
{148}{}{应用红心大战运行中。此终端胜利。[咔嚓！] 感谢游戏。}
{149}{}{程序参数已更改。当前应用为：设施维护 v2.1，移动 v4.8b，修理 v0.8a，害虫控制 v1.4，红心大战 v1.0 和传感器 '76。}
{150}{}{调整移动参数。}
{151}{}{调整传感器参数。}
{152}{}{修改害虫控制。}
{153}{}{玩红心大战。}
{154}{}{谢谢。结束输入。}
{155}{}{当前应用为：设施维护 v2.1，移动 v4.8b，修理 v0.8a，害虫控制 v1.4，红心大战 v1.0 和传感器 '76。}
{156}{}{调整移动参数。}
{157}{}{调整传感器参数。}
{158}{}{修改害虫控制。}
{159}{}{玩红心大战。}
{160}{}{谢谢。结束输入。}
{161}{}{正在初始化语音通信子系统。正在初始化个性子系统。[咔嚓！] 这个终端有什么可以帮您的吗？}
{162}{}{嗯。}
{163}{}{给我看看你的程序。}
{164}{}{关闭所有力场。}
{165}{}{你知道这里是什么地方吗？}
{166}{}{启动紧急关机。}
{167}{}{结束输入。}
{168}{}{这个终端无法执行该功能。请求被拒绝。}
{169}{}{给我看看你的程序。}
{170}{}{你知道这里是什么地方吗？}
{171}{}{启动紧急关机。}
{172}{}{结束输入。}
{173}{}{这是——机密 [咔嚓！] [咔嚓！]}
{174}{}{中止请求。显示程序。}
{175}{}{覆盖，继续请求。}
{176}{}{[咔嚓！] 这里是FEV生产控制设施。此终端于2074年上线。最终预生产过程于2075年完成。目前正在进行最终施工，计划于2078年开放。[咔嚓！]}
{177}{}{你知道FEV是什么吗？}
{178}{}{你知道今天的日期吗？}
{179}{}{FEV是强制[咔嚓！]进化病毒，由利弗莫尔/布朗森实验室研发。其设计目的是在更短时间内增加DNA/RNA序列的遗传复杂性。}
{180}{}{显示程序。}
{181}{}{结束输入。}
{182}{}{确认。终端日期为2077年2月2日。}
{183}{}{显示程序。}
{184}{}{结束输入。}
{185}{}{该日期不正确。请重新校准。}
{186}{}{正在校正。[咔嚓！] 错误。尝试自我诊断。[咔嚓！咔嚓！] 错误！致命系统错误。系统已损坏，尝试重新编译。[长时间暂停。]}
{187}{}{终端？}
{188}{}{[咔嚓] 重新编译错误...[咔嚓]}
{189}{}{无法处理请求。终止对话。}
{190}{}{确认紧急代码中断。}
{191}{}{已确认。}
{192}{}{终止关闭程序。}
{193}{}{[咔哒！]}
{194}{}{正在处理请求。终止对话。}
{195}{}{此计算机与您的无线电不兼容。它仅使用专用的高频波段供机器人使用。}
{196}{}{您按下了一些按钮，但计算机似乎损坏了。需要一些工作才能操作它。}
{197}{}{计算机没有物理损坏，但数据似乎已损坏。}
