{100}{}{你看到鲁弗斯。}
{101}{}{请不要杀我。}
{102}{}{嘘！我正在玩游戏呢！}
{103}{}{安静！我在玩游戏。《赛博街区：矩阵王子》，真是经典！}
{104}{}{该死！我的角色又被打趴了。罗杰真是个懦夫。}
{105}{}{赛博空间的钥匙在哪儿？我都把克鲁兹大楼翻遍了。}
{106}{}{你不会知道进入马里布斯图的密码吧？哦，算了。}
{107}{}{那个凯拉，真是个尤物！}
{108}{}{别打扰我。我正在解这个该死的鸭子谜题。}
