{100}{}{你看到鲁特格。}
{101}{}{你好，欢迎来到远行商人。我们能为你做些什么？}
{102}{}{你们能运输水吗？}
{103}{}{我来是为了那份发布的工作。}
{104}{}{我在找工作。}
{105}{}{你们在这里是做什么的？}
{106}{}{你不能。再见。}
{107}{}{呃！}
{108}{}{我们不雇佣流浪者！滚出去。}
{109}{}{嗯...真可惜你只有蛮力而没有脑子。我们本可以用得上你这样的人。}
{110}{}{我们‘可以’运输水，但这会花费你不少钱。你需要多少水，要运到哪里？}
{111}{}{我需要足够供应一个避难所的水。它在北边，过了废城，在山里。}
{112}{}{我需要足够供应一个避难所的水。它在北边，在山里。}
{113}{}{我全都要！总有一天，我会改变这个星球的面貌。你会看到的！}
{114}{}{一个整个避难所？你疯了吗？我们没有那么多水的渠道。而且，我也不想进那些山里。我们已经有太多失踪的商队了。}
{115}{}{你们没有？还有其他人能做到吗？}
{116}{}{那么，关于那份发布的工作呢？}
{117}{}{那么，你们有工作吗？}
{118}{}{好吧，什么都没得到，谢谢。}
{119}{}{哦，抱歉，你不是本地人。水商人掌管着这个镇上所有的水。我甚至不想试着和他们打交道。他们就是一群秃鹫。}
{120}{}{我该去哪里找他们？}
{121}{}{好的，谢谢。}
{122}{}{你不会错过他们的。他们在这南边，全都被那该死的水塔围住了。}
{123}{}{那么，你在这里做什么？}
{124}{}{好的，谢谢。}
{125}{}{我负责...我是说，我帮助管理远行商人。如果有人惹我们麻烦，我会让他们付出代价。我们在不同的定居点之间进行货物交易。}
{126}{}{我已经告诉过你了。布奇和我管理远行商人。你想要什么？}
{127}{}{你们交易些什么东西？}
{128}{}{有趣。再见。}
{129}{}{很好。那关于那份发布的工作呢？}
{130}{}{听起来不错。需要帮忙吗？}
{131}{}{我们几乎交易你能想到的一切：化学品、轮胎、枪支、子弹、食物、辐牛、泥土，甚至是金属废料。}
{132}{}{泥土？金属废料？}
{133}{}{呃……这很有趣，但我得走了。}
{134}{}{你会惊讶于外面需求的东西。在一个地方被视为理所当然的东西，可能在十英里外的定居点成为抢手货。}
{135}{}{好了，别再说无聊的商人话了。门在哪儿？}
{136}{}{谢谢，再见。}
{137}{}{你能告诉我关于发布的工作的情况吗？}
{138}{}{你们有工作吗？}
{139}{}{我听说你有点疯狂，但这正是我们现在需要的。你需要去找布奇谈谈。他喜欢见所有的新成员。他就在我后面的房间里。进去吧。}
{140}{}{我不想让一个杀过孩子的人加入我的商队。}
{141}{}{杀孩子？但那是个意外。}
{142}{}{嘿，我不歧视。如果挡了我的路，不管多大年纪，他们都会变成墙上的一滩血迹。}
{143}{}{我想意外确实会发生。外面的世界相当混乱。我还是不太信任你。去跟布奇谈谈吧。他就在那个房间里。}
{144}{}{说什么意外。我了解你这种人。以为可以为所欲为。好吧，这里可不行，伙计。去跟布奇谈谈，但我会盯着你。他就在我后面的门里。}
{145}{}{说什么意外。我了解你这种人。以为可以为所欲为。好吧，这里可不行，女士。去跟布奇谈谈，但我会盯着你。他就在我后面的门里。}
{146}{}{你真是个无情的混蛋。我们可能需要这样的人，但这不代表我同意你的做法。别在我面前碰小孩，否则你就是墙上的一滩血迹。去跟布奇谈谈吧。他就在我后面的办公室里。}
{147}{}{你在找工作？我听说过你的好名声。我们总是需要像你这样的人。进去跟布奇谈谈。他就在我后面的门里。}
{148}{}{你在找工作吗？你看起来还不错。你应该去找布奇谈谈。他就在我后面的门里。}
{149}{}{我以为你不想要这份工作。你想要什么？}
{150}{}{我不想。我只是想再看看你那张丑脸。}
{151}{}{对不起。我真的很想要这份工作。能给我吗？}
{152}{}{没什么。}
{153}{}{格鲁达！}
{154}{}{滚出去，你这个该死的斯卡格！}
{155}{}{好吧。希望你能下定决心，我很忙……让我告诉你细节。}
{156}{}{你满嘴胡扯。滚出去。}
{157}{}{你跟我说什么？我说去跟布奇谈谈工作。如果他喜欢你，我会告诉你细节。}
{158}{}{什么？你还没走吗？}
{159}{}{寻找进展如何？}
{160}{}{我好像找不到任何东西。}
{161}{}{你能再说一遍工作的细节吗？}
{162}{}{你有任何护送商队的工作吗？}
{163}{}{抱歉，我得走了。}
{164}{}{嗯？}
{165}{}{好吧，我没说过这会很简单。否则，我们早就解决这个问题了。到处打听一下。如果需要，可以强硬一点，但别见血。至少不要在公众场合。}
{166}{}{我告诉你，别碰化学品。它们会毁了你。}
{167}{}{当你能告诉布奇最近消失的商队到底发生了什么时，这份工作会支付你500哈勃币。所以，收集任何你可能找到的证据。我个人认为是那些该死的水商人或者钢铁兄弟会的枪械狂。布奇认为是某种死亡之爪之类的东西。去找贝丝，她可能知道更多。}
{168}{}{好的，但我不知道你错过了什么。其实没多少内容。}
{169}{}{我还以为你肯定是从那里来的。我只是测试一下你。如果你不是从那里来的，那你是怎么弄到他们穿的那套钢铁盔甲的？}
{170}{}{哦，这个？我‘找到’的，你懂的。}
{171}{}{我不便透露。}
{172}{}{天哪，你一定很厉害。我很高兴你在我们这边。我不知道你怎么会不知道，但兄弟会是一群崇拜科技的怪人，或者类似的东西。他们就在这里的西北方向。}
{173}{}{什么是钢铁兄弟会？}
{174}{}{我可以保证不是兄弟会干的。}
{175}{}{你对死亡之爪了解多少？}
{176}{}{贝丝在哪儿？}
{177}{}{谢谢，再见。}
{178}{}{好吧，无论如何。我相信你以前见过他们。他们是一群崇拜科技的怪人，或者类似的东西。他们在这里的西北方向。}
{179}{}{他们真的很奇怪。他们崇拜科技或类似的东西。他们有大量的火力，足以轻松摧毁一个商队。他们在西北方向。}
{180}{}{我就知道你一定是他们中的一员。你穿着那套钢铁盔甲就说明了。我希望你是对的，我希望雇用你不是个错误，但你不是我们唯一雇用的人，所以没关系。}
{181}{}{你为什么这么说？}
{182}{}{因为我刚加入他们的组织，我彻底调查过他们。他们只是很安静，独来独往，但没有什么可怕的。}
{183}{}{我进去过他们的地堡。他们不是你要找的人。}
{184}{}{只是直觉。}
{185}{}{好吧，那就放心了。我想。}
{186}{}{希望你是对的。}
{187}{}{直觉不够。我们需要证据。}
{188}{}{贝丝就在那扇门外，右边。她经营我们的武器店。告诉她你是为我们工作，你会得到15%的折扣。}
{189}{}{哦，是的，死亡之爪，随便啦。他们都疯了。只是人们的想象力过于丰富。没有什么鬼怪或怪物之类的东西。只要坚持现实，你就会没事。}
{190}{}{有什么事吗？我能帮你什么忙？}
{191}{}{我知道你的商队发生了什么事。}
{192}{}{没什么。}
{193}{}{什么。}
{194}{}{咕噜。}
{195}{}{真的吗？是谁干的？是水商吗？}
{196}{}{是的，就是他们！他们想对付你。他们……想要你的……辐射牛。}
{197}{}{其实，是一群巨大的变种人。}
{198}{}{是死亡爪。我看到它吃掉了一整个商队。}
{199}{}{我忘了。}
{200}{}{你忘了？真有趣，伙计。现在，滚吧。}
{201}{}{你忘了？真有趣，女士。现在，滚吧。}
{202}{}{我就知道是他们。你带来证据了吗？我要让那些混蛋付出代价。}
{203}{}{呃，没有。我把它弄丢了。不过，你可以相信我。}
{204}{}{其实，不是他们。是一群巨大的变种人。}
{205}{}{抱歉，我得走了。}
{206}{}{好吧，没有证据我什么也做不了。我不想再引发一场商人战争。如果你能带来证据，我会交给法律，我们会消灭他们。}
{207}{}{你满嘴胡说。离我远点。}
{208}{}{什么？怎么可能？这不可能。你在开玩笑吧？你是在开玩笑，对吧？}
{209}{}{是的，抱歉。信不信由你，实际上是一大群变种人。}
{210}{}{太可怕了。它有这些大而尖的牙齿。}
{211}{}{一整个商队？真的吗？我看起来有那么好骗吗？出去查清楚我们的商队到底发生了什么。}
{212}{}{一些巨大的变种人在摧毁我的商队？这几乎和死亡爪的故事一样荒唐。}
{213}{}{我不是在开玩笑。我找到了死亡爪并杀了它，但我在一个超级变种人的尸体上发现了这个全息磁盘。}
{214}{}{看看这个全息磁盘。我从一个袭击的变种人身上拿到的。}
{215}{}{这是真的，我在现场看到了。我会带回证据。}
{216}{}{好吧，不相信就算了。}
{217}{}{我得走了。}
{218}{}{嘿，我知道怎么用这个。布奇很久以前从兄弟会的一个侦察员那里弄到一个可以读取这些东西的小玩意儿。让我们看看。抱歉，我之前不相信你。这对好人来说不是个好兆头。好吧，这是你的500赫巴克。算了，给你800，谢谢你的情报！如果你还需要工作，随时欢迎来找我。}
{219}{}{请不要再增加布奇的偏执了。他对死亡爪的事情有点敏感。告诉我，你真的发现了什么吗？是水商吗？}
{220}{}{是的，就是他们！他们想对付你。他们……想要你的……辐地牛。}
{221}{}{其实，是一群巨大的变种人。}
{222}{}{不，真的是死亡爪。我看到它吃掉了一整支商队。}
{223}{}{我忘了。}
{224}{}{老鼠，是吗？那么，你查到什么了吗？一定是那些该死的水商，我知道的！}
{225}{}{是的，就是他们！他们想对付你。他们……想要你的……辐地牛。}
{226}{}{其实，是一群巨大的变种人。}
{227}{}{是死亡爪。我看到它吃掉了一整支商队。}
{228}{}{我忘了。}
{229}{}{变种人摧毁了我们的商队？这几乎和关于死亡爪的传闻一样好笑。}
{230}{}{我不是在开玩笑。我找到了死亡爪并杀了它。但我也在那些超级变种人的尸体上发现了这个全息磁盘。}
{231}{}{看看这个全息磁盘。我从一个袭击的变种人身上拿到的。}
{232}{}{这是真的，我在现场。我会带回证据。}
{233}{}{我得走了。}
{234}{}{那么，你有任何关于是谁在捣乱我的，我是说，我们的商队的证据吗？}
{235}{}{有。这是我在那些……巨大的变种人尸体上找到的全息磁盘。}
{236}{}{没有，还在找。有什么建议吗？}
{237}{}{没有，我会通知你的。}
{238}{}{嘎！}
{239}{}{如果这个死亡爪真的存在，你可能想检查一下它的巢穴。那里可能有线索。}
{240}{}{你好，我能帮你什么忙？}
{241}{}{我查出了失踪商队的真相。}
{242}{}{哦，没什么。}
{243}{}{嘿！我听说你干掉了那些变种人的头目。干得好。你可能救了集市里所有人的命；但我想知道他们是从哪里来的。}
{244}{}{是啊！更多的东西可以杀！我想知道他们藏在哪里。}
{245}{}{是的，我必须彻底清除大师的邪恶造物。我想知道他们藏在哪里。}
{246}{}{你说得对！我想知道他们藏在哪里。}
{247}{}{我需要一些现金。有工作吗？}
{248}{}{这只是日常工作。再见！}
{249}{}{是的，我大显身手。哦，我是说……Gruk Chak！}
{250}{}{嘿，伙计。最近怎么样？}
{252}{}{嘿，美女。最近怎么样？}
{253}{}{我最喜欢的女士怎么样？}
{254}{}{很好，谢谢。还有其他工作吗？}
{255}{}{太好了！只是过来看看情况如何。}
{256}{}{尤格瓦？}
{257}{}{一切都很好！那些该死的变种人不再袭击我们，贸易恢复正常。实际上，贸易比以前更好了。谢谢关心。}
{258}{}{嘿，我听说你摧毁了那些该死的变种人聚集的基地！干得好！可惜没能找到他们的头目。}
{259}{}{是啊！又有东西可以消灭了。我想知道主人藏在哪里。}
{260}{}{是的，我必须摧毁主人。我不能让邪恶再扩散。我想知道主人藏在哪里。}
{261}{}{主人即将见到他的造物主。}
{262}{}{你说得对！我想知道主人藏在哪里。}
{263}{}{我需要一些现金。有什么工作吗？}
{264}{}{是啊，我大显身手了。哦不，我是说...Gruk Chak！}
{265}{}{嗯，我听说有人在西北方向很远的地方看到了一些零散的变种人群体，远远超过了钢铁兄弟会。}
{266}{}{你知道，自从变种人被消灭后，大教堂的孩子们表现得非常奇怪。我实际上听到一个人在谈论你。他们似乎在拼命找你。}
{267}{}{其实，情况不太好。那些变种人仍然在对我们的商队造成麻烦。我们不得不暂停几乎所有的商队。不过还是谢谢你的关心。}
{268}{}{当然，我们可以在我们的商队中用到你。你做过护卫工作吗？工资是标准的400 Hub币。有兴趣吗？}
{269}{}{当然}
{270}{}{不。}
{271}{}{什么？失踪的商队怎么办？}
{272}{}{加入商队是找到盗贼的最佳方式。}
{273}{}{我会留意的，但我需要一些钱。}
{274}{}{算了。}
{275}{}{好的，但如果你改变主意请告诉我。大多数时候这都是轻松赚钱的机会。}
{276}{}{太好了，只要和前门的商队司机谈谈，看看下次商队什么时候出发。只要你表现好，我们的司机就会雇用你。}
{277}{}{我再给你一次机会。工资是400 Hub币。去和前门的商队司机谈谈，看看下次什么时候出发。}
{278}{}{抱歉，我已经给过你机会。我想你应该离开了。}
{279}{}{你在开玩笑吗？虽然我对你所做的事情非常感激，但恐怕这无法改变过去。我想你应该离开。}
{280}{}{你没听到我说的吗？我们不会雇用你。请离开。}
{281}{}{我觉得这可能不太有效，不过如果你愿意，可以试试看。}
{282}{}{你为什么这么说？}
{283}{}{你说得对，让我再多打听一下。}
{284}{}{没问题，我接下这份工作。}
{285}{}{太好了。记得多问问其他人。}
{286}{}{好的。准备好出发时，只需和前门的商队司机谈谈。只要你表现好，我们的司机就会雇用你。}
{287}{}{当然！你不需要和我说话。直接找我们的商队司机就行。}
{288}{}{[更多]}
{289}{}{当然，我们可能损失了很多商队，但这在我们整体业务中占的比例很小。你所在的商队被完全捕获或摧毁的可能性很低。不管是谁或什么在做这件事，肯定有一支相当庞大或非常致命的力量。}
{290}{}{哦，好吧。我想我会再多问问。}
{291}{}{嗯，我需要钱。}
{292}{}{又见面了。我能为你做些什么？}
{293}{}{很高兴再次见到你。}
{294}{}{我想知道，你们运送水吗？}
{295}{}{我是来应聘公告上的工作的。}
{296}{}{我在找工作。}
{297}{}{你们是做什么的？}
{298}{}{抱歉，我得走了。}
{299}{}{拉尔瓦。}
{300}{}{是啊，你到底想要什么？}
{301}{}{我真是受够你了。又怎么了？}
{302}{}{什么！}
{303}{}{你总是这么烦人吗？}
{304}{}{什么事，伙计？！}
{305}{}{我想知道，你们运送水吗？}
{306}{}{我是来应聘公告上的工作的。}
{307}{}{我在找工作。}
{308}{}{你们是做什么的？}
{309}{}{抱歉，我得走了。}
{310}{}{图卡？}
{311}{}{你惹恼了老大。赶紧滚出去！}
{312}{}{我想我可能已经弄清楚失踪商队的情况了。}
{313}{}{太好了！去告诉布奇你发现了什么，他会告诉我你是否能获得奖励。}
{314}{}{格尔德尔 斯纳普！！！}
{315}{}{抱歉，我们不和……嗯……智力有问题的人打交道。}
