{100}{}{你看到莎莉。}
{101}{}{为什么大家跟我说话都怪怪的？？}
{102}{}{变种人无视了你。}

{1000}{}{芯片}
{1001}{}{死城}
{1002}{}{赛特}
{1003}{}{水坝}
{1004}{}{大厅}
{1005}{}{卢}
{1006}{}{食尸鬼}
{1007}{}{正常人}

{1100}{}{我不知道。}
{1101}{}{你就站在这里。}
{1102}{}{他是个懦夫。我们应该干掉他和他的食尸鬼。}
{1103}{}{就是这里。}
{1104}{}{我不知道。}
{1105}{}{他是哈利的老板。}
{1106}{}{软弱的东西。}
{1107}{}{比食尸鬼还软弱。}
