{100}{}{你看到撒玛尔，来自阿迪顿的拾荒者之一。}
{101}{}{你看到一个穿着深蓝色衣服的邋遢男人。}
{102}{}{嘿，我想我们还没见过。你是？}
{103}{}{我是}
{104}{}{。}
{105}{}{谁在问？}
{106}{}{嗯？}
{107}{}{很高兴认识你。我叫撒玛尔。}
{108}{}{你在这里做什么？}
{109}{}{很高兴和你聊天。}
{110}{}{没什么特别的。算了。}
{111}{}{我是个拾荒者——专门搜寻废土中有用物品和信息的工作。危险的活计。}
{112}{}{为什么危险？}
{113}{}{你怎么避开死亡爪？}
{114}{}{你侦查过其他地区吗？}
{115}{}{谢谢，再见。}
{116}{}{回头见。如果你能看到我。呵呵。}
{117}{}{嗯，外面有死亡爪，而在阿迪顿这边有监管者。两者都不怎么宽容。}
{118}{}{你怎么避开死亡爪？}
{119}{}{你侦查过其他地区吗？}
{120}{}{谢谢，再见。}
{121}{}{我们只在晚上工作，而且我们很擅长自己的工作。但我承认并不是每个人都能回来。我上周派了个人去给迈尔斯找些零件，从那以后就没听到他的消息。他最后的传讯是他找到了零件，正在回来的路上。}
{122}{}{我做过一些侦查。你想知道关于谁的？}
{123}{}{刀锋帮。}
{124}{}{死亡爪。}
{125}{}{枪械跑商。}
{126}{}{启示录的追随者。}
{127}{}{大教堂的孩子们。}
{128}{}{没人，谢谢。}
{129}{}{刀锋帮看起来真是一群可怜的人。不过他们还过得去，有些人如果同意监管者的条件就会来到阿迪顿。}
{130}{}{如果你以前没见过它们，那可要小心了。它们凶狠无比，最喜欢的就是撕掉可怜拾荒者的心脏。}
{131}{}{我听说在刀锋帮东边有个它们的巢穴，但我自己没见过。}
{132}{}{不久前，枪械行者搬进了东北方的一个大工厂。我不能告诉你太多，因为那里有个充满放射性污泥的护城河，而且你得穿过死亡爪才能到达。}
{133}{}{追随者们宣扬和平与宽容。想法不错，但不切实际。他们住在我们西北方的一个大图书馆里。}
{134}{}{大教堂的孩子们以南边的一座大教堂为基地。那里发生了一些奇怪的事情。我看到有些不像人类的生物进进出出。}
{135}{}{如果传闻属实，那座教堂是建在一个旧避难所上，而阿迪顿的前身就住在那里。}
{136}{}{嘿，我们又见面了。有什么事吗？}
{137}{}{你之前的工作是什么来着？}
{138}{}{没事，谢谢。}
{139}{}{哦，我明白了。好吧，再见！}
