{100}{}{你看到萨米。}
{101}{}{洞穴.map}
{102}{}{去和长老谈谈。他有重要的事情要先告诉你。}
{103}{}{跟我来。我知道去巢穴的路。}
{104}{}{小子，我真希望你有胆量帮我们一把。}
{105}{}{准备好了吗？一旦我们到了巢穴，任务完成前就不能回头。}
{106}{}{是}
{107}{}{否}
{108}{}{洞穴.map}
{109}{}{小子，我真希望你有胆量帮我们一把。}
{110}{}{跟我来。我知道去巢穴的路。}
{111}{}{准备好了吗？一旦我们到了巢穴，任务完成前就不能回头。}
{112}{}{是}
{113}{}{否}
{114}{}{好的，我会在这里等。准备好了告诉我。}
