{100}{}{天啊！你杀了他！}
{101}{}{嗯！}
{102}{}{真倒霉。}
{103}{}{他是我的敌人，我必须杀了他。}
{104}{}{对不起，我不知道他对你如此重要。}
{105}{}{你不该杀他的！[莎拉抽泣。] 离我远点。}
{106}{}{他是我的爱人，也是我最好的朋友。我无法相信你对他做了这种事。}
{107}{}{再次道歉。我怎么知道他对你如此重要？看看他，他是个变种人。}
{108}{}{我要杀光他那类人。}
{109}{}{他曾是个人类。为了生存，他不得不被浸泡。你杀了他。}
{110}{}{抱歉。}
{111}{}{哦，好吧。至少我的击杀计数器又加了一人。}
{112}{}{混蛋。}
{113}{}{你怎么离开了你的保护室？}
{114}{}{扎格-扎格！}
{115}{}{随便走走。}
{116}{}{我不是这里的囚犯。}
{117}{}{不用了，我已经有男朋友了。}
{118}{}{你应该待在你的房间里。守卫是为了保护我们。机器人被编程为攻击没有护送的普通人。一旦我被浸泡，我就能为统一体贡献力量。}
{119}{}{好吧，随便你。玩得开心。}
{120}{}{你想这么做吗？}
{121}{}{当然，这是人类生存的最佳机会。}
{122}{}{哇！我觉得你可能会惹上大麻烦。请别在我附近逗留。}
{123}{}{能让一下吗，我们在谈话！}
