{100}{}{抄写员}
{101}{}{研究是我最喜欢做的事情之一。我感觉自己像是在解开一个谜团。}
{102}{}{成为抄写员是最棒的。你可以研究所有的旧技术，并尝试开发新的技术。}
{103}{}{这些终端需要一些改进。也许我们应该把显示器放在这里。}
{104}{}{抱歉，我正处于一个可能的突破中。现在不能交谈。}
{105}{}{嘿，新兵。如果你还没决定，不妨考虑训练成为一名抄写员。}
{106}{}{我们抄写员设计所有的装备、武器和补给。这非常令人兴奋。}
{107}{}{请不要打扰我。我正在努力完成我的研究。}
{108}{}{那就是Vree。她也是一名抄写员。}
