{100}{}{抄写员}
{101}{}{Vree是我的偶像。}
{102}{}{Vree真漂亮。}
{103}{}{Sophia真是个好人。}
{104}{}{Derek真是个了不起的人。}
{105}{}{宇宙会继续膨胀，还是最终会崩溃回到自身？}
{106}{}{我喜欢那些旧书和杂志，但它们太难找了。}
{107}{}{知识就是力量。}
{108}{}{笔比剑更强大。}
{109}{}{科技必须被保存。}
{110}{}{科学真有趣。}
{111}{}{我见过外星飞船。}
{112}{}{你知道太阳其实是一个巨大的核反应吗？类似于毁灭旧世界的东西，不过是聚变，不是裂变。}
{113}{}{你知道黑洞其实是通往另一个宇宙的入口吗？我已经在纸上推导出来了。可惜在我死之前不会再有太空旅行了。}
{114}{}{你知道氢原子有99.9843425%的空间是空的？}
{115}{}{时间旅行有一天会成为可能，我们也许能阻止过去毁灭世界的灾难。但那样的话……如果问题被解决了，我们还怎么回去……哦，我的头好痛。}
