{100}{}{你看到一个夜行者的侦察兵。}
{101}{}{这是什么？一个普通人。我想你应该跟我走。}
{102}{}{不。}
{103}{}{好的。}
{104}{}{我为什么要这样做？}
{105}{}{再想想！}
{106}{}{这其实很简单。如果你跟我走，我可以帮助你。}
{107}{}{好吧。我会跟你走。}
{108}{}{直接带我去找领袖。}
{109}{}{绝不可能！}
{110}{}{尽快行动。去找乌瑟恩。他会给你指明方向。}
{111}{}{乌瑟恩想见你。看来他听说过你。}
