{100}{}{你看到一个微弱发光的电脑。}
{101}{}{有少量电力输入。大部分电力似乎被分配去维持那些仍在半运作状态的系统。}
{102}{}{你没有发现任何异常。}
{103}{}{这台电脑发出奇怪的嗡嗡声。}
{104}{}{连接到这台电脑的显示器不断打印“系统故障”字样。}
{105}{}{这台电脑似乎遭到了一只食尸鬼的攻击。}
{106}{}{这台电脑上的灯光在闪烁，但对你来说似乎是随机的。}
{107}{}{当你触摸这台电脑时，它给了你一个无害的电击。}
{108}{}{检查后你注意到这台电脑曾被老鼠当作家。}
{109}{}{连接到这个系统的屏幕上打印着随机数字。}
{110}{}{这台电脑发出你听过的最糟糕的噪音，显示器上显示着“Jared”这个词。}
{111}{}{这台电脑的一半因旧火灾而变得黑乎乎的，焦黑一片。}
