{100}{}{这个技能在这里没用。}
{101}{}{你发现一个简陋的爆炸装置连接在脚锁箱上。}
{102}{}{你触发了一个爆炸陷阱！}
{103}{}{你成功拆除了陷阱。}
{104}{}{你没有成功拆除陷阱。}
{105}{}{你不小心引爆了炸弹！}
{106}{}{你不小心引爆了炸弹，因为你足够聪明找到了它，但不够聪明不去碰它。}
{107}{}{哎哟！}
{108}{}{啊啊啊！}
{109}{}{你看到塞特的保险箱。}
