{100}{}{你看到了一堵坚固的墙。}
{101}{}{这段墙看起来有些奇怪。}
{102}{}{你看到了一扇滑动门。}
{103}{}{门被锁住了。}
{104}{}{你触发了门上的陷阱。}
{105}{}{ 检测到门上有一个陷阱。}
{106}{}{你检测到门上有一个陷阱。}
{107}{}{这没有任何效果。}
{108}{}{门已经解锁了。}
{109}{}{你在这个难开的锁上弄坏了你的撬锁工具。}
{110}{}{你没能打开这个锁。}
{111}{}{你撬开了门上的锁。}
{112}{}{这个锁对你来说太难了，现在无法撬开。}
{113}{}{你注意到这个锁住的门上有一个高爆炸性的陷阱。}
{114}{}{你注意到这个门上有一个高爆炸性的陷阱。}
{115}{}{你注意到这个锁住的门上有一个陷阱。}
{116}{}{你注意到这个门上有一个陷阱。}
{117}{}{你没有发现这个锁住的门有什么特别之处。}
{118}{}{你没有发现这个门有什么特别之处。}
