{100}{}{你看到雪莉。}
{101}{}{你看到一个帮派成员。}
{102}{}{}
{103}{}{你是谁？在这里干什么？}
{104}{}{我是}
{105}{}{。我是这个镇的新面孔。}
{106}{}{不关你的事，泼妇！}
{107}{}{啥？}
{108}{}{显然是这样，因为大家都知道这里是骷髅帮的地盘。你最好赶紧走，不然有人会对你不客气的。}
{109}{}{来啊！}
{110}{}{抱歉，我以为这是厕所。再见。}
{111}{}{骷髅帮？他们是谁？}
{112}{}{是啊，我知道。我就是随便逛逛。}
{113}{}{快滚蛋，蠢货，不然我们有人会决定揍你一顿。}
{114}{}{哎呀，抱歉。}
{115}{}{是吗？来试试啊！}
{116}{}{你这可怜虫。你该走了。这里不安全，尤其是对你这种不懂事的人。}
{117}{}{就是我们！我们是镇上最凶的帮派。其实，我们是唯一的帮派。没人敢惹我们。}
{118}{}{所以你们基本上掌控了整个小镇，是吧？}
{119}{}{真不错。再见。}
{120}{}{哦。那你最好别这样。我是说，你不是骷髅帮的人，这里是我们的地盘。所以，你最好快点消失，不然维克托会动手的。}
{121}{}{其实，我想留下来。}
{122}{}{维克托是谁？}
{123}{}{好吧，我走了。}
{124}{}{好吧。那是你自找的。}
{125}{}{维克托就在那边。他是我们中最凶的。他喜欢折磨他抓到的鬣蜥。说实话，我不太喜欢他，但他是我们的人。}
{126}{}{嗯，有维克托，还有鲨鱼，他常在污秽坑酒吧晃荡。还有维尼，以及其他几个偶尔过来的家伙。}
{127}{}{污秽坑酒吧在哪儿？}
{128}{}{哦，污秽坑酒吧是个肮脏的酒吧，在北边，靠近吉兹莫的赌场。}
{129}{}{当然！没人敢惹我们！嗯，除了基利安，但他人挺好的。他就像个治安官。我们想干什么就干什么。}
{130}{}{我们就只是闲逛，有时候会在吉兹莫的地方玩游戏，或者去Skum Pitt找点乐子。有时我们会为吉兹莫或一些旅行者做些零活。维克多喜欢跟踪别人。想想看，你最好离他远点。}
{131}{}{你为吉兹莫工作？能告诉我关于他的事吗？}
{132}{}{你们到底是做什么的？}
{133}{}{帮派里都有谁？}
{134}{}{你为什么和这些人混在一起？}
{135}{}{我们就像个家庭！我们互相照顾。嗯，除了鲨鱼，他总是搞破坏。还有维克多，他看人的眼神很奇怪。但维尼很酷。我们一起做事情。你懂的，就像朋友一样。}
{136}{}{哦，又是你！你知道，如果你不是Skulz的一员，待在这里可能不太健康。而你不是。}
{137}{}{是吗？你们Skulz可能连一头睡着的布拉明都打不过，更别说对付我了。}
{138}{}{你最近在忙什么？}
{139}{}{真的吗？我们走着瞧！维克多！}
{140}{}{其实没什么。没多少事情可做。我是说，鲨鱼像往常一样在Skum Pitt惹事，但除此之外还能做什么呢？}
{141}{}{呃，我想没什么吧。}
{142}{}{你可以尝试做些别的事情。你一定有些才能或爱好。}
{143}{}{嗯，我有点喜欢画画。维尼说我厨艺不错。不过，我是说，嘿，我们玩得很开心，你懂的？}
{144}{}{我想这是可以理解的。}
{145}{}{但是当你老了以后怎么办？你的人生将走向何方？你将如何赚钱？}
{146}{}{呃，我从没多想过。我是说，维尼和维克多赚点钱，鲨鱼偶尔为这里的访客做保镖。我不知道。}
{147}{}{你最好趁早离开。}
{148}{}{嘿，别管我！你听起来像维尼的父母以前那样。我们都互相支持，好吗？所以别再说了。}
{149}{}{我想是吧。我从没多想过。}
{150}{}{嗨！你怎么样？好久不见。}
{151}{}{我还好，谢谢。}
{152}{}{我过得不太好。}
{153}{}{还行。你呢？}
{154}{}{很遗憾听到这个！也许你该找个房间休息一下。去找马塞勒斯。哦，如果你愿意，我可以给你做点吃的。}
{155}{}{那太好了，谢谢。}
{156}{}{不用了，不过我们以后再见。}
{157}{}{哦，我好多了，谢谢！我现在在Skum Pitt和Crash House做些烹饪。有时候晚上会有点累，但我喜欢做饭，而且能遇到各种有趣的人。我还能拿到报酬。谢谢你的帮助。}
{158}{}{给你。享用吧。我们以后见！}
{159}{}{他是个大胖子，经营着赌场。他想掌控废城，但基利安一直压制着他。不过他付的钱相当不错。有时他会雇维尼或维克多去处理一些对他有问题的人，比如几周前来这里的一个陌生人。}
{160}{}{你想让我出卖我的朋友？！}
{161}{}{是的，我需要你的信息。}
{162}{}{抱歉，请忘了我问过。}
{163}{}{他们一直在伤害别人，如果不阻止他们，他们会继续这样。你已经改变了自己的生活，现在你有机会帮助改善他人的生活。}
{164}{}{嗯，他们是我的朋友。但我想他们不应该再这样伤害别人。我信任你，因为你帮助过我。好吧。}
{165}{}{不，我不能那样做！那些是我的朋友！虽然我不再是Skul帮的一员，但我不会背弃我的老朋友。}
{166}{}{我需要你的帮助。我需要你的证词来彻底铲除Skulz。}
