{100}{}{你看到希德，贝丝的助手。}
{101}{}{早上好。}
{102}{}{下午好，先生！}
{103}{}{下午好，女士！}
{104}{}{晚上好。}
{105}{}{我知道，我知道……[小声] 她话真多，不是吗。}
{106}{}{欢迎光临贝丝的武器店和八卦中心。}
{107}{}{贝丝，有人来看你。}
{108}{}{欢迎来到贝丝的欢乐宫。}
{109}{}{你带礼物来了吗？}
{110}{}{[小声] 别告诉她你不想让全城知道的事。}
{111}{}{又来了？}
{112}{}{免费武器！快来领取！}
{113}{}{三号通道有特别优惠。}
{114}{}{她是我的，别想打主意！}
{115}{}{她喜欢欲擒故纵。}
{116}{}{早餐时间。}
{117}{}{午餐时间！}
{118}{}{晚上好。}
{119}{}{不错的蓝色套装，嘿。13是你的幸运数字吗？}
{120}{}{哦，是神秘的男人！}
{121}{}{哦，是神秘的女人！}
{122}{}{你会看手相吗？}
{123}{}{哦，贝丝就是喜欢皮革！}
{124}{}{嘿亲爱的，给我买下他的皮夹克。}
{125}{}{嘿亲爱的，给我买下她的皮夹克。}
{126}{}{不错的尖刺护甲！}
{127}{}{这是伪装，你融入得太好了。等等！你去哪了？}
{128}{}{嘿，这套衣服真是锋利。}
{129}{}{才不是！}
{130}{}{嘿！是那只金属罐！你怎么样？}
