{100}{}{你看到辛西亚，一个诱人的卖笑女。}
{101}{}{你看到一个撅嘴的丰满女人。}
{102}{}{嘿，亲爱的，你好吗？}
{103}{}{好的，再见。}
{104}{}{还不错，但可以更好。}
{105}{}{呃。}
{106}{}{哦，宝贝，我明白。你得回家找妈妈。好吧，当你需要爱的时候再来找我！}
{107}{}{是啊，甜心，你也是。}
{108}{}{亲爱的，你会找到你想要的东西或人，那会让你感觉好很多，我敢肯定。}
{109}{}{也许我可以帮你。}
{110}{}{也许你可以。你收费多少？}
{111}{}{我连我的狗都不会让它碰你。}
{112}{}{哦，宝贝，如果你得问的话……那就是你负担不起的。也许下次吧，甜心。回头见。}
{113}{}{哦，甜心，那真是太恶心了。}
{114}{}{哦，天啊，请帮帮我。}
{115}{}{请不要让他杀了我。}
{116}{}{我还太年轻，不想死。}
{117}{}{哦，天啊，我太漂亮了，不想死。}
{118}{}{谢谢你所做的一切。以前从来没有人这样照顾过我。}
{119}{}{我以后可以好好照顾你。}
{120}{}{不客气。}
{121}{}{嗯。}
{122}{}{再次感谢。}
{123}{}{这就是你能想到的全部吗？天啊。有些人真是的。}
{124}{}{我的老板甚至没有派他的打手来帮忙。你以为我给那个废物赚了那么多钱，他至少会履行他的承诺。}
{125}{}{你的老板是谁？}
{126}{}{什么承诺？}
{127}{}{当然是吉兹莫。他掌控着这个镇上的所有罪恶。基利安肯定不会容忍我或我这样的人。如果不是因为我给吉兹赚了很多钱，我就得对他做其他事情。}
{128}{}{而且，亲爱的，那些想法让我胃里很不舒服。}
{129}{}{吉兹莫还控制着什么？}
{130}{}{你应该放下过去，继续你的生活。}
{131}{}{你说得对。但我还能做什么呢？感觉我的人生就像被别人设计好的一样。唉，女孩总得谋生。}
{132}{}{不过甜心，这次是免费的。}
{133}{}{再次感谢你，亲爱的。我们女人得互相扶持。}
{134}{}{几乎这镇上所有坏事他都干过。他拥有赌场，控制着我和其他一些女孩，甚至还有些小孩。我听说他还想接管酒吧。}
{135}{}{你离他远点，好吗？听我的，他不是你想象中的那种好人。远离他。}
{136}{}{基兹想对付基里安，你懂我的意思。}
{137}{}{亲爱的，我照顾男人，他们也回报我。基兹拿走25%，说是给我提供保护。你也看到了，效果如何，对吧？}
{138}{}{基兹还控制着什么？}
{139}{}{你想再去找辛西亚。}
{140}{}{也许辛西亚需要个伴……}
{141}{}{你这个混蛋！你杀了他！你为什么要杀他？你这个混蛋！我真不敢相信你杀了他。他只是想找个人聊聊而已。你根本不在乎人命，是吗？}
{142}{}{你这个混蛋！你杀了他！你为什么要杀他？你这个贱人！我真不敢相信你杀了他。他只是想找个人聊聊而已。你根本不在乎人命，是吗？}
{143}{}{滚出我的房间！}
{144}{}{你杀了他！我真不敢相信你杀了他。他只是想找个人聊聊而已……}
{145}{}{他没死。他醒来时只是会头疼。}
{146}{}{嗯。}
{147}{}{好吧，随便。滚出我的房间！}
{148}{}{哦，抱歉。我以为他死了。我以为你杀了他。他其实不是个坏人，只是有点孤独。}
{149}{}{没问题。}
{150}{}{又是你。这次有什么需要帮忙的吗？}
{151}{}{只是来看看你过得怎么样。}
{152}{}{我有40美元，如果你有十分钟的话。}
{153}{}{我需要更多关于你老板的信息。}
{154}{}{啊，亲爱的，我不这么认为。想想孩子们会变成什么样。}
{155}{}{多亏了你，亲爱的，我过得不错。}
{156}{}{你想知道什么？但请快点，亲爱的，我在工作中。}
{157}{}{他有多少保镖？}
{158}{}{他把钱藏在哪里？}
{159}{}{他有什么弱点吗？}
{160}{}{谢谢，宝贝，但我不需要知道其他的了。}
{161}{}{嗯。我个人认识八个，如果你懂我的意思。我想他还有另外十个左右。}
{162}{}{钱？我怎么会知道？他只拿我的钱，从不让我看他的。我猜可能在他的卧室，但他也可能藏在一个阳光照不到的地方。对于吉兹来说，那可是个大地方。}
{163}{}{他只觉得自己没有。嗯，还有他是个胖懒鬼，动都动不了。他得让他的保镖帮他移动。即便如此，他们还得用个小三轮车。呵呵。}
{164}{}{甜心，你有约会了。}
{165}{}{当然，亲爱的，为了你。}
{166}{}{我会让你玩得开心。}
{167}{}{亲爱的，你需要再多点钱。我喜欢你，但女孩也得谋生。}
{168}{}{我保留拒绝入内的权利，亲爱的，你可别想靠近我！}
{169}{}{辛西亚正在睡觉。}
{170}{}{辛西亚正忙着。}
{171}{}{辛西亚拒绝与你交谈。}
{172}{}{抱歉，亲爱的，我不接待怪胎。}
{173}{}{把你的钱、态度和小家伙带到别处去吧！}
{174}{}{哦，天哪，谁来帮帮我！}
{175}{}{你获得}
{176}{}{经验，因为成功救了辛西亚。}
{177}{}{守卫在袭击者昏迷时将他拖走。}
