{100}{}{你看到斯拉皮。}
{101}{}{波吉，波吉，波吉。}
{102}{}{小蜘蛛，砸啊，砸啊。}
{103}{}{来玩全球热核战争吧。}
{104}{}{我的小毯子在哪儿！？！}
{105}{}{哒... 哒... 哒...}
{106}{}{月亮就在外面。}
{107}{}{给我糖，宝贝。}
{108}{}{哦，好漂亮的东西。为什么是月亮？}
{109}{}{我和哈罗德聊过了。死亡爪听起来很可怕。你能告诉我些什么？}
{110}{}{贝丝让我来找你谈谈死亡爪。}
{111}{}{你在这里做什么？}
{112}{}{你有什么问题？}
{113}{}{月亮大，我喜欢月亮！}
{114}{}{一片光明，全都是光明，光明降临，然后我们就完蛋了。}
{115}{}{啊。}
{116}{}{死亡爪，死亡爪，哒哒死亡爪。}
{117}{}{拜托，你知道关于死亡爪的什么？}
{118}{}{你有什么问题？}
{119}{}{别逼我揍你！}
{120}{}{我做，我做，然后你做，然后我们都做。}
{121}{}{不，真的，你做什么。}
{122}{}{你是个疯子。}
{123}{}{问题就像汤碗，宽而浅。}
{124}{}{更像是你的脑子。}
{125}{}{死亡爪很吓人，真的很吓人。不过看起来很酷。想去看看吗？}
{126}{}{你能带我去见死亡爪？}
{127}{}{绝对不行！}
{128}{}{是的，死亡爪，死亡爪，去看死亡爪。}
{129}{}{闭嘴，带我去。}
{130}{}{啊，算了。你保重。}
{131}{}{我做这个，然后做那个。你见过哈罗德吗？哈罗德很有趣，他的头发会掉，随风飘扬。看，它走了……风，风。}
{132}{}{随便。}
{133}{}{砰砰砰，砰砰砰。}
{134}{}{为什么会有风？为什么为什么为什么。}
{135}{}{贝丝，贝丝，咻沙贝丝。像哈罗德一样，你去找哈罗德聊聊。哈罗德会给你讲故事。然后斯拉皮帮你。}
{136}{}{好的，我先去找哈罗德聊聊。}
