{100}{}{你看到一些变种人和孩子在视频屏幕前跪着。}
{101}{}{和我们一起祈祷和平吧，孩子。}
{102}{}{如果我们足够强大，统一体就会胜利。冥想力量的品质。}
{103}{}{拯救人类的使命需要信仰。和我们一起祈祷。}
{104}{}{异教徒！亵渎者！你将受到惩罚！}
{105}{}{我们必须祈祷以变得强大。改变即将来临。}
{106}{}{统一体是我们的未来，兄弟。}
{107}{}{统一体是我们的未来，姐妹。}
{108}{}{我相信主宰者。他的意志是我们的救赎。}
