{100}{}{你看到索菲娅，她是钢铁兄弟会新兵的教官。}
{101}{}{好了，有人有问题吗？}
{102}{}{如果有不明白的地方，记得要问问题。不要害羞。}
{103}{}{复习你的笔记。}
{104}{}{我们明天会为第14节的同学进行另一次测试。}
{105}{}{抱歉，我现在不能说话。我有课要上。}
{106}{}{我知道你有东西要给我。}
{107}{}{是的。给你。}
{108}{}{是的，但我现在没带在身上。}
{109}{}{你。}
{110}{}{抱歉，我有课要上。请不要打扰我。}
{111}{}{你不应该在这里。弗里不喜欢晚上被打扰。这是我们冥想的时间。}
{112}{}{我们正在冥想。请离开。早上再来。}
{113}{}{离开我们。}
{114}{}{请尊重一点。不要在别人冥想时打扰他们。}
{115}{}{你们这些新兵还有很多要学。请离开。}
{116}{}{不要打扰我。}
{117}{}{晚上我们不接待任何人。请早上再来。}
{118}{}{现在是晚上。你应该去睡觉，除非你有守卫任务，那你应该在岗位上。}
{200}{}{你好，新兵。我能帮你什么忙？}
{201}{}{我知道你有东西要给我？}
{202}{}{是的，给你。}
{203}{}{是的，但我现在没带在身上。}
{204}{}{我？不，抱歉。你一定认错人了。}
{205}{}{呃。}
{206}{}{非常感谢。你能送来这些真是太好了。}
{207}{}{嗯，谢谢。你还好吗？不管怎样，你能送来这些真是太好了。}
{208}{}{没有这些，我的研究会被耽搁。很高兴看到我们有这样值得信赖的新兵。我就知道找个外人不是个坏决定。如果你去找迈克尔，他会给你一些东西。}
{301}{}{你好。我以前没见过你，你迷路了吗？需要我帮忙吗？}
{302}{}{呃……}
{303}{}{你能告诉我图书馆怎么走吗？}
{304}{}{我在找弗瑞。}
{305}{}{这里是什么地方？}
{306}{}{如果我迷路了，我才不会问你这种笨蛋！}
{307}{}{我真不敢相信我们现在竟然接受这种人做见习者。天啊，保佑我们。}
{308}{}{这是图书馆。我们在这里保存所有关于武器和技术的技术数据，当然还有兄弟会的历史。}
{309}{}{我需要修理一个水芯片。你能帮我吗？}
{310}{}{我想了解更多关于你们这里制造的武器。}
{311}{}{这是我能找到全息磁盘的地方吗？}
{312}{}{没事了，谢谢你的时间。}
{313}{}{我在找一把大枪来提升我的杀人技巧。}
{314}{}{我是弗瑞的助手。弗瑞就在那边。}
{315}{}{谢谢。}
{316}{}{作为弗瑞的助手，你的工作是什么？}
{317}{}{我的专长是兄弟会的历史。听起来像是制造问题，也许你应该问弗瑞？}
{318}{}{我以为抄写员懂这些东西。}
{319}{}{我想了解兄弟会的历史。}
{320}{}{你真是帮了大忙！}
{321}{}{好的，谢谢你的帮助。}
{322}{}{你必须和首席抄写员弗瑞谈谈。我有更重要的事情要做。}
{323}{}{我会去找弗瑞。}
{324}{}{更重要的事情？比如什么？}
{325}{}{你不认为兄弟会的武器很重要吗？}
{326}{}{我们图书馆有很多全息磁盘。它们分为历史、技术和武器设计。}
{327}{}{我想看看关于你们技术的全息磁盘。}
{328}{}{我想看看关于武器设计的全息磁盘。}
{329}{}{我想看看关于兄弟会历史的全息磁盘。}
{330}{}{我被派来问弗瑞关于兄弟会的历史。}
{331}{}{我的专长是兄弟会的历史。看来这里有些人已经忘记了我们历史的重要性。}
{332}{}{你能告诉我一些关于兄弟会历史的事情吗？}
{333}{}{还有什么比历史更重要的呢？}
{334}{}{看来你快到那几天了，是吧？}
{335}{}{我想问问关于武器的事情。}
{336}{}{就像维护兄弟会的历史。看来这里有些人已经忘记了我们的历史有多重要。}
{337}{}{Vree似乎认为新武器的研究和从变种人尸检中获得的信息比我们的历史更重要。她已经忘记了我们的历史是我们生活的重要组成部分。情况已经糟糕到很多新加入的成员甚至不知道Roger Maxson是谁，或者他为我们做了什么。}
{338}{}{我想更多地了解兄弟会的历史。你能给我一些信息吗？}
{339}{}{嗯，看起来Vree是我想要谈话的人。再见。}
{341}{}{听起来Vree的想法很对！谁需要知道这些垃圾信息呢！？}
{342}{}{我同意历史很重要，但我更关注新技术和更好的武器。}
{343}{}{你需要和Vree谈谈这方面的事情。}
{344}{}{这些东西只有抄写员和骑士才能接触。Vree可能能帮到你。}
{345}{}{谢谢，我去问问Vree。}
{346}{}{有没有我可以访问的全息磁盘？}
{347}{}{显然你不是我该谈话的人。再见。}
{348}{}{嗯，很高兴看到有人对我们伟大的历史感兴趣。不像这里的其他人。给你。这是我们最早期的一些文献的磁盘。}
{349}{}{谢谢你。}
{350}{}{我对这些垃圾不感兴趣。谢谢你什么都没给我。}
{351}{}{我们的历史对所有人开放。这样他们就可以了解我们的伟大历史……不过好像没人看。}
{352}{}{我想看看你们关于兄弟会历史的任何资料。}
{353}{}{真的吗？我也不在乎，只要给我看看武器。}
{354}{}{你好。我以前没见过你，你迷路了吗？需要我帮忙吗？}
{355}{}{呃……}
{356}{}{你能指引我去图书馆吗？}
{357}{}{我被派来和Vree谈谈兄弟会的历史。}
{358}{}{如果我迷路了，我才不会问你这种笨蛋！}
{359}{}{你没能谈成吧？Vree忙着她的“实验”，已经不再关心历史了。}
{360}{}{那么我可以和谁谈谈兄弟会的历史呢？}
{361}{}{是啊，兄弟会里似乎都是笨蛋。}
{362}{}{我也不在乎。再见。}
{363}{}{我不想和你说话。}
{364}{}{我能帮你什么忙？}
{365}{}{你在这里做什么工作？}
{366}{}{你能告诉我关于兄弟会的历史吗？}
{367}{}{抱歉，我认错人了。再见。}
{368}{}{我是Vree的助手。}
{369}{}{谢谢你。}
{370}{}{作为Vree的助手，你具体做些什么？}
{371}{}{很高兴看到有人对我们的伟大历史感兴趣。不像这里的其他人。给你，这是我们早期一些文献的磁盘。}
{372}{}{谢谢你。}
{373}{}{我对这些废话不感兴趣。谢谢你什么都没给。}
{374}{}{我给了你一张包含我们早期文献的磁盘。只需在你的PIPBoy 2000中加载它，你就能阅读。}
{375}{}{谢谢你。}
{376}{}{我对这些废话不感兴趣。谢谢你什么都没给。}
{377}{}{我不喜欢你的态度，我选择不和你说话。}
{378}{}{那就这样吧。再见！}
{379}{}{对不起，我刚才很无礼，我向你道歉。}
{380}{}{我接受你的道歉。现在我能帮你什么忙？}
{381}{}{你在这里做什么工作？}
{382}{}{你能告诉我关于兄弟会的历史吗？}
{383}{}{抱歉，我认错人了。再见。}
{384}{}{我是Vree的助手。Vree在学习中心。}
{400}{}{你看到一位兄弟会新兵的教官。}
