{100}{}{你看到斯塔普尔顿夫人，图书管理员。}
{101}{}{你看到一位中年女性。}
{102}{}{你好，欢迎来到图书馆。我想我以前没见过你。你在寻找什么知识呢？}
{103}{}{很高兴再次见到你。今天你想找些什么呢？}
{104}{}{你这里有什么书？}
{105}{}{我在找一个水芯片。}
{106}{}{没什么，谢谢。}
{107}{}{好吧，让我给你看看我的藏书。}
{108}{}{在我的研究中，我确实遇到过关于这种东西的参考资料。实际上，我手上有一个全息磁盘，其中包含一些你可能觉得有用的信息。}
{109}{}{全息磁盘，那是什么？}
{110}{}{我可以要这个全息磁盘吗？}
{111}{}{全息磁盘上存有信息，但只能通过某些电子设备读取。我看到你有一个PIP Boy，你可以用它来解码、查看和存储全息磁盘上的信息。}
{112}{}{听起来不错！我可以要这个全息磁盘吗？}
{113}{}{在这个时代，信息很难获得。我需要向你收取750胡贝币。}
{114}{}{好的，这是钱。}
{115}{}{如果我见过旧全息磁盘，那这看起来就是一个。我给你500。}
{116}{}{要不我用喷灯把这地方全烧了！怎么样，女士？！}
{117}{}{抱歉，我没带够钱。}
{118}{}{抱歉，我只能接受全额付款。请等你有足够的钱再来。}
{119}{}{很抱歉，但请你把纵火的念头收起来。请离开。}
{120}{}{[斯塔普尔顿夫人收下了你的钱。]}
{121}{}{你说得对，这个磁盘确实有些旧了。既然如此，我接受500。 [斯塔普尔顿夫人收下了你的钱。]}
{122}{}{通常我不会屈服于这种方法，但为了保护我的藏书免受威胁，我会给你磁盘。作为交换，我希望你永远不要再来这里。}
{123}{}{如我所解释的，你需要使用这个，然后通过你的PIP Boy访问信息。 [斯塔普尔顿夫人把全息磁盘交给你]}
{124}{}{请原谅，我还有研究要做。}
{125}{}{鲁克？}
{126}{}{抱歉，我听不懂你说的话。我这里有一个学习英语的全息磁盘，如果你有兴趣的话。}
{127}{}{再见。}
{128}{}{谢谢。}
{129}{}{呃。}
{130}{}{你有没有一套化学期刊？阿迪顿的迈尔斯说你可能会有。}
{131}{}{是的，我已经从迈尔斯那儿听说了，我有他需要的那几本。价格是750块钱。}
{132}{}{给你，先生。替我向迈尔斯问好。}
{133}{}{抱歉，你的钱不够。请凑够钱之后再来吧。}
