{100}{}{你看到面前的塔利乌斯，他是追随者的一员。}
{101}{}{请离开。我想在这里休息。白天再来吧。}
{102}{}{你好，姐妹。我叫塔利乌斯。今天有什么可以帮到你的吗？}
{103}{}{你好，兄弟。我叫塔利乌斯。今天有什么可以帮到你的吗？}
{104}{}{嗯？}
{105}{}{我}
{106}{}{。我}
{107}{}{。}
{108}{}{我是}
{109}{}{。你在这里做什么？}
{110}{}{你可以去死！}
{111}{}{不用担心我，变种！你是怎么进来的？}
{112}{}{也向你问好。我被称作}
{113}{}{。你是如何进入追随者的领域的？}
{114}{}{你能告诉我一个像你这样被改造过的人是如何进入追随者的吗？}
{115}{}{我看你有点迟钝。我也曾和你一样，但通过追随者的教导，我已经超越了我的缺陷。}
{116}{}{不知道。}
{117}{}{太聪明了。现在去死。}
{118}{}{抱歉。我有时会忘乎所以。你需要一些脑力帮助吗？}
{119}{}{是的，你的！}
{120}{}{你帮忙。你帮忙！}
{121}{}{这里。拿这些漂亮的药丸。让你更聪明。}
{122}{}{是的，}
{123}{}{。我很高兴你承认你的名字。今天早上有什么可以帮到你的吗？}
{124}{}{什么？}
{125}{}{脑袋疼。我杀了你。拿脑袋。}
{126}{}{我在这里帮助这些好人理解大教堂之子的运作。}
{127}{}{所以你是大教堂之子的间谍？}
{128}{}{你怎么会知道大教堂之子的事情？}
{129}{}{你能做什么？你是个变种人。}
{130}{}{不，我不是间谍。虽然很多人这样认为。在我们这所 humble abode 里确有一名间谍。但我们无法将其揪出来。}
{131}{}{那你如何帮助追随者？}
{132}{}{告诉我你知道的关于这名间谍的事。或许我能帮忙。}
{133}{}{真倒霉，变种儿！}
{134}{}{我想我找到了间谍。现在我要解决这个问题。}
{135}{}{曾经，我和你一样。但由于在亡灵之城的隐形食尸鬼的相遇，我变成了这样。}
{136}{}{那真是太糟糕了。不过，倒霉了。再见。}
{137}{}{你为什么在亡灵之城？}
{138}{}{你原本来自哪里？}
{139}{}{现在我将再次改变你。安息吧。}
{140}{}{不久前，我住在远在北方的一个地方。他们的供水出了问题，寻找能解决问题的人。}
{141}{}{所以你自愿去了。}
{142}{}{是什么地方？}
{143}{}{你找到解决问题的方法了吗？}
{144}{}{为什么是亡灵之城？}
{145}{}{是的。社区的监督者给了我一把散弹枪和一些子弹。然而，多年前这些东西丢失了。我既没找到任何东西，也没法回去。}
{146}{}{那真的很糟糕。我希望能帮上忙。}
{147}{}{真不幸。我得走了。}
{148}{}{是哪里？}
{149}{}{你找到解决供水问题的方法了吗？}
{150}{}{你为什么去亡灵之城？}
{151}{}{有一种方法你可以帮忙。必须阻止那个让我变成这样的家伙。}
{152}{}{是谁？}
{153}{}{他们的领导是一个变种人大军的头目。他抓住纯人类并转变他们。我不是很确定，因为我在过程中昏过去了。}
{154}{}{那我就为你去干掉他们。}
{155}{}{这听起来太冒险了。我要走了。}
{156}{}{感谢你的好意。你帮了我大忙。请收下这个作为善意的象征。我是从一个死去的叛逃者身上拿到的。}
{157}{}{那就平安离开吧。我理解你的不安。或许会有其他人来帮忙消除这个威胁。祝你好运。}
{158}{}{我来自远在北方的山里。那里有个小型避难所，许多人住在那里。}
{159}{}{你找到解决供水问题的方法了吗？}
{160}{}{你为什么去死城？}
{161}{}{这个避难所叫什么名字？}
{162}{}{听起来不错。我得走了。}
{163}{}{很遗憾，我没有。我听说有其他人从避难所被派去寻找修理水泵的方法。}
{164}{}{我再也没有听到他们的消息。}
{165}{}{你为什么去死城？}
{166}{}{这个避难所叫什么名字？}
{167}{}{听起来不错。我得走了。}
{168}{}{我从其他旅行者那里听说死城有一种不费力气就能生产水的方法。}
{169}{}{所以，我去了那里看看他们在做什么。}
{170}{}{你发现了什么？}
{171}{}{你把他们都杀了吗？}
{172}{}{在那里感觉像家吗？}
{173}{}{我在那里发现了很多变种人。是他们困住了我，并把我变成了现在的样子。}
{174}{}{显然，他们搞砸了，因为我走上了一条不同的进化道路，而不是增强型的。}
{175}{}{真是个糟糕的遭遇。再见。}
{176}{}{我会小心他们的。谢谢你的信息。}
{177}{}{谁领导他们？}
{178}{}{没有。我只杀了一些变种人。有个叫赛特的食尸鬼变种人帮我干掉了大部分。}
{179}{}{我最后知道的情况是只剩下六个变种人了。}
{180}{}{听起来不错。那么，再见。}
{181}{}{剩下的都没了。赛特过得不错。}
{182}{}{这真是个好消息。我很高兴听到一个邪恶被消灭，一个城镇获得自由。请收下这个。}
{183}{}{讽刺和轻蔑不会改变我仁慈的态度。是时候告别了。祝好。}
{184}{}{我的避难所没有名字。它只是编号13。}
{185}{}{我就是从那里来的。}
{186}{}{从没听说过这个地方。}
{187}{}{谢谢你的信息。现在我要告诉那些变种人。}
{188}{}{真的吗？监督者终于同意让人们离开避难所了吗？}
{189}{}{没有，他仍然害怕外面的世界。}
{190}{}{不，他担心居民的安全。}
{191}{}{是的，他认为一切都很安全。}
{192}{}{我也是这样认为的。他一直是个谨慎的人。我为他的责任感到遗憾。希望你在这愚蠢的任务中比我更顺利。}
{193}{}{很高兴听到他终于清醒过来，允许人们出去。虽然外面远不安全，但这有助于再次恢复大地。再见，我的朋友。}
{194}{}{我怀疑你会这样做，毕竟你来自外面的世界。现在，我必须退下了。请在外面小心那些想要毁灭的生物。}
{195}{}{不，我怀疑你能做到这一点。}
{196}{}{试试看阻止我。}
{197}{}{你为什么这么说？}
{198}{}{因为我会阻止你。}
{199}{}{我了解得很少。我只知道我们的侦察兵是唯一能去观察“儿童”的人。因为危险，其他人都不被允许。}
{200}{}{那可能是个侦察兵。我会调查这个。}
{201}{}{我认为是你。现在去死吧！}
{202}{}{我希望你能更聪明些。没关系，我很快就会解决你。}
{203}{}{我所知道的“儿童”是他们与这些夜行者，超级变种人有联系。}
{204}{}{是他们在死城把我从原来的状态变成了现在这样。}
{205}{}{真可怕。不过，运气不好。再见。}
{206}{}{你为什么在死城？}
{207}{}{你原本来自哪里？}
{208}{}{现在我将再次改变你。安息吧。}
{209}{}{虽然我外形不同，但我有很多知识可以传授给愿意倾听的人。}
{210}{}{我没时间听这些，我要走了。}
{211}{}{你能告诉我什么？}
{212}{}{那些被追随者和“儿童”称为夜行者的并非表面看起来那样。他们是由一个叫中尉的人创造的。我相信他可能还听命于另一个人。}
{213}{}{有些信息。好吧，我要走了。}
{214}{}{你能告诉我关于这个中尉的事吗？}
{215}{}{关于他我知道的不多。上次见到他是在我不幸变异之前，他在寻找纯种人类。}
{216}{}{我会考虑这个问题。谢谢你。}
{217}{}{你能猜测一下为什么会这样吗？}
{218}{}{目前我还不确定。也许另一个试图破坏他们计划的组织会知道。}
{219}{}{谢谢。祝你愉快。}
{220}{}{很遗憾，我无法容忍无礼。离开吧。}
{221}{}{我加入追随者的过程其实很简单。正是追随者救我于变成可怕怪物的完全转化中。}
{222}{}{我不太明白。请继续。}
{223}{}{曾经，我和你一样，是个纯粹的人类。但在夜行者的干预下，我被带到一个离这里很远的地方。}
{224}{}{请继续。}
{225}{}{我当时的状态无法观察发生了什么。我只知道我在这里醒来，并得到了好医生的照料。}
{226}{}{听到你的困境我感到非常遗憾。我会找到那些对你做出这种事的人，并解决这个问题。}
{227}{}{很遗憾听到这个。唉，我正忙于求生。再见。}
{228}{}{请惩罚那些试图破坏追随者信任的亵渎者。}
{229}{}{你成功地清除了我们中间的伪装者希瑟，干得好。}
{230}{}{你看到一个可怕的食尸鬼。}
{231}{}{不知为何，他让你想起了某个人。}
{232}{}{唉，我没有更多时间留给你了。祝你好运。}
