{100}{}{你看到坦迪。}
{101}{}{这附近还有什么地方？}
{102}{}{这里发生了什么事？}
{103}{}{你听说过南边的故事吗？}
{104}{}{你觉得这里怎么样？}
{105}{}{嗯，就这样吧。感谢你的时间。}
{106}{TAND_1}{Hi!  I heard there was a traveller in town, but I was
 kinda skeptical until I saw you.  My name's Tandi, what's yours?}
{107}{}{我的名字是}
{108}{}{。}
{109}{}{我叫}
{110}{}{。记住这个名字。}
{111}{}{呃？}
{112}{tand_2}{Well..how do you like our little town?  Bored yet?}
{113}{}{没关系。不过我可以问你几个问题吗？}
{114}{}{当然可以。这里除了看辐射牛交配就没别的事了。}
{115}{}{我觉得还行吧。}
{116}{}{嗯，是有点无聊。}
{117}{TAND_3}{ Sure, I guess.  I've never been out of here, so I don't know
 what help I can be.  So, what'cha need?}
{118}{TAND_4}{Yeah.  Well you don't
 live here.  There's nothing interesting to do, and believe you me, Brahma
 Tipping gets old real fast.}
{119}{}{如果你这么无聊，为什么不离开呢？}
{120}{}{我相信你是在夸张。}
{121}{}{这里看起来不错而且安全。}
 {122}{TAND_5}{Me, leave?  I wish.  I don't know
 enough to leave alone and no one else wants to go, and worst of all, my father
 says he would have a heart attack if something happened to me! }
{123}{}{情况挺艰难的。不过我可以问你几个问题吗？}
{124}{}{糟了，我得走了。祝好运。}
{125}{TAND_6}{Uh...I have to stand over here now. }
{126}{TAND_12}{You live here all your life and see how you like it!  Anything
 else you want to know?}
{127}{TAND_13}{Yeah, real safe...and so boring I think my brain's going to
 leak out of my ear at any moment.}
{128}{}{你为什么不离开？}
{129}{}{很遗憾听到这个，但我时间不多。我可以问你几个问题吗？}
{130}{TAND_14}{Finally!  Someone else who
 sees! Of course, you've probably been everywhere, so this must be hell for
 you.}
{131}{}{如果你这么无聊，为什么不离开呢？}
{132}{}{我相信你是在夸张。}
{133}{}{这里看起来不错而且安全。}
{134}{TAND_15}{Junktown's to the southwest, but I don't know how far.
 Then there's some weird place below that called the City of Death.  Oh, oh
 yeah there's this other place...Oh, shoot, what was that?  Oh, yeah, the
 Hub.}
{135}{tand_15a}{There's a bunch of cities down south.  But since you're such a
 great traveler, I'm sure you know that already.}
{136}{}{谢谢。}
{137}{TAND_16}{No problem. Anything else?}
{300}{tand_16a}{Yeah, whatever.}
{138}{TAND_20}{We got Rad
 Scorpions!  I mean, I know it's not a good thing, but no one's died from the
 stings.  And it's the closest thing to excitement we've got here!}
{139}{TAND_21}{Nothing much, since you whomped those Rad Scorpions. Gee, I
 wish I could have seen that.}
{140}{TAND_22}{Same as always.  Bo-ring.}
{142}{tand_23b}{Just stuff.}
{141}{tand_23g}{The weirdest story I've heard is about the Death Claw.}
{143}{}{谢谢。}
{144}{}{死亡爪？}
{145}{TAND_24}{It's okay, I guess.  I mean, it is home and all, but it's so
 boring!  You know, I want to see the world.}
{146}{}{如果你这么无聊，为什么不离开呢？}
{147}{}{我相信事情没那么糟。}
{148}{}{这里看起来很安全。}
{150}{tand_27f}{Listen...uh...but I...uh...I-I like guys, okay?  Whew!  Uh,
 excuse me, I got stuff to do.}
{149}{tand_27m}{I'm not that kind of girl,
 mister. Go find a Brahma or something.}
{151}{TAND_28}{Well, thanks for talking.
 We don't get many strangers here, so it's always good to talk to new people.
 Well, see ya! }
{152}{}{再见。}
{153}{TAND_29}{Uh, listen.  I have to go take care of the
 Brahmas.  It was, uh, nice talking to ya. }
{154}{tand_30a}{Hello again!  What
 can I help you with now?}
{155}{}{我可以再问几个问题吗？}
{156}{}{没事了。再见。}
{157}{TAND_35}{Uh...hey, thanks. Later.}
{158}{TAND_36}{Hi!  I was afraid that you
 were gone and I wasn't going to get a chance to thank you for rescuing me.
 Aw!  That was great!  Action, adventure...Anyway, if there's anything that I
 can do for you, you just ask.}
{159}{}{再问几个问题怎么样？}
{160}{}{你觉得我们两个……呃，你知道的……在一起怎么样？}
{161}{}{不，这就够了，谢谢。}
{162}{}{呃！！}
{163}{TAND_37}{Who are you?  What do you want?}
{164}{}{我的名字是}
{165}{}{，你父亲派我来的。}
{166}{}{我是你的仙女教母。看起来像什么？}
{167}{}{呃。}
{168}{TAND_38}{Father sent you!?  Are you here to get me out?}
{169}{}{是的，坐稳了。我会带你出去。}
{170}{}{不，他只是让我来看看你。}
{171}{TAND_39}{Well, what's your plan?}
{172}{}{等门一开就跑出去！}
{173}{}{我要和可汗首领决斗来换取你的自由。}
{174}{TAND_40}{That's it?  That's your plan.
 Ugh!  All right.  But hurry.  I heard them talking and I didn't like their
 plans. }
{175}{TAND_41}{You?  Fight him?  You
 got to be kidding me!  [Sigh] Listen, if you come up with another plan, let me
 know, okay? }
{176}{TAND_42}{Oh, aren't we the sarcastic one?  Are you going to
 get me out, or what!?}
{177}{}{是的，坚持住，看到门开了就跑！}
{178}{}{我要和可汗首领决斗来换取你的自由。}
{179}{TAND_43}{Oh, it's you again! Are you going to get
 me out?}
{180}{}{是的，坐稳了。我会带你出去。}
{181}{}{不，我只是路过打个招呼。}
{182}{}{呃。}
{183}{tand_43a}{Hello, anybody home?  Could you get me out of here?
 Could you GET ME OUT OF HERE!}
{184}{tand_43b}{This is no time to talk, we have to get out of here.}
{185}{TAND_44}{Aradesh is my father.  He's okay, as far as dad's go.}
{186}{TAND_45}{That's me.  Who else did you think it was?}
{187}{TAND_46}{Razlo's the old guy on the east side of town.  He's a pretty
 good doctor, though, even if he is a fossil. }
{188}{TAND_47}{Seth's the captain of the guards.  My father tried to set
 us up once, but he is not my type.}
{189}{TAND_48}{Agatha's the oldest one here.  We all love her, especially
 her stories.  Go by and see her if you want a good yarn.}
{190}{TAND_49}{Pretty
 bad bunch or so I've heard.  My father knows more about them.  He never tells
 me much about the outside world.}
{191}{TAND_50}{That's where we get all our water. It's been here since before I was born.}
{192}{TAND_51}{I've actually seen one, even if it was from far away. They're
 nasty creatures, with claws and a big stinger.  And their poison can be
 deadly if it isn't treated.  You should talk to my dad, Aradesh, he knows
 more about them. }
{193}{TAND_52}{I heard a tale from a traveller up from the south.  He said the
 Death Claw was a creature that killed people at night.  He said no one can
 catch it, because it can disappear like smoke.  Not that I believe it, of course.}
{194}{TAND_53}{Junktown's a small city to the southwest. It's supposed to
 have pretty good trading, but my father won't even look into it.  He says we
 need to stay 'protected'.  Yeah, right.  Caged is more like it. }
{195}{TAND_54}{The Hub is supposed to be a great city to the south.  I've
 always wanted to see it, but I've never got the chance. }
{196}{TAND_55}{I don't
 know, but the guy who told me about it was really scared of it.  He said that
 the undead walked the streets! }
{197}{TAND_62}{I don't know.  You might want to ask Seth or my father about it, though.}
{198}{TAND_63}{Hmm...Doesn't ring a bell. }
{199}{TAND_64}{Hm...nope.  I never heard of it. }
{200}{TAND_65}{Hey!  What do you think you're doing?  Put that back! }
{201}{TAND_66}{That's it!  I'm going to tell my father! }
{202}{TAND_67}{What the hell do you think you're doing?  Stop that! }
{203}{TAND_68}{What are you doing here? You better leave
 before my father wakes up.}
{204}{TAND_69}{Like I said...}
{205}{TAND_70}{Listen, I already told you... }
{206}{TAND_71}{Again?  Hello?  How many times have I
 have to tell you this?  You have too much wax in your ears or something?}
{207}{TAND_72}{Oh yeah, I heard of that, but you should go talk to Agatha.
 She'd know more than I would.}
{208}{}{我们快离开这里。}

{300}{}{哇！这和阴影镇完全不一样。}
{301}{}{嘿，那边是什么？}
{302}{}{我迫不及待想告诉阴影镇的人外面的世界。}
{303}{}{你见过更多的辐射蝎子吗？}
{304}{}{我们现在要去哪儿？}
{305}{}{我们什么时候能到？}


{980}{TAND_62}{I don't know.  You might want to ask Seth or my father about it, though.}
{981}{TAND_63}{Hmm...Doesn't ring a bell. }
{982}{TAND_64}{Hm...nope.  I never heard of it. }

{1000}{}{阿拉德什}
{1001}{}{坦迪}
#{1002}{}{Razlo}
{1002}{}{赛斯}
{1003}{}{掠夺者}
{1004}{}{好吧}
{1005}{}{蝎子}
{1006}{}{爪子}
{1007}{}{废城}
{1008}{}{枢纽}
{1009}{}{城市}
{1010}{}{蝎子}
{1011}{}{可汗}

{1100}{TAND_44}{Aradesh is my father.  He's okay, as far as dad's go.}
{1101}{TAND_45}{That's me.  Who else did you think it was?}
#{1102}{TAND_46}{Razlo's the old guy on the east side of town.  He's a pretty
# good doctor, though, even if he is a fossil. }
{1102}{TAND_47}{Seth's the captain of the guards.  My father tried to set
 us up once, but he is not my type.}
{1103}{TAND_49}{Pretty bad bunch or so I've heard.  My father knows more
 about them.  He never tells me much about the outside world.}
{1104}{TAND_50}{That's where we get all our water. It's been here since before I was born.}
{1105}{TAND_51}{I've actually seen one, even if it was from far away. They're
 nasty creatures, with claws and a big stinger.  And their poison can be
 deadly if it isn't treated.  You should talk to my dad, Aradesh, he knows
 more about them. }
{1106}{TAND_52}{I heard a tale from a traveller up from the south.  He said the
 Death Claw was a creature that killed people at night.  He said no one can
 catch it, because it can disappear like smoke.  Not that I believe it, of course.}
{1107}{TAND_53}{Junktown's a small city to the southwest. It's supposed to
 have pretty good trading, but my father won't even look into it.  He says we
 need to stay 'protected'.  Yeah, right.  Caged is more like it. }
{1108}{TAND_54}{The Hub is supposed to be a great city to the south.  I've
 always wanted to see it, but I've never got the chance. }
{1109}{TAND_55}{I don't know, but the guy who told me about it was really
 scared of it.  He said that the undead walked the streets! }
{1110}{TAND_51}{I've actually seen one, even if it was from far away. They're
 nasty creatures, with claws and a big stinger.  And their poison can be
 deadly if it isn't treated.  You should talk to my dad, Aradesh, he knows
 more about them. }
{1111}{TAND_49}{Pretty bad bunch or so I've heard.  My father knows more
 about them.  He never tells me much about the outside world.}
