{100}{}{你看到一个留着短发的开朗男子。}
{101}{}{你看到镇上的商人，泰恩。}
{102}{}{我们这里不常有陌生人来。你想要什么？}
{103}{}{你好，陌生人！今天有什么我能帮你的？}
{104}{}{我的名字是}
{105}{}{。}
{106}{}{我可以问你关于集市商人的事吗？}
{107}{}{我想做些交易。}
{108}{}{你对阿迪特姆怎么看？}
{109}{}{没什么。}
{110}{}{是的，我和他们有交易。}
{111}{}{我偶尔和他们做些交易。主要是用子弹换食物。}
{112}{}{我是泰恩。你有生意要谈吗？}
{113}{}{很高兴认识你。我是泰恩。}
{114}{}{很高兴和你做生意。欢迎再来。}
{115}{}{随便。}
{116}{}{保持联系！}
{117}{}{什么？}
{118}{}{又见面了！有什么我能帮你的吗？}
{119}{}{这是个不错的小镇。如果监管者们不那么严厉的话，可能会更快乐。不过，这就是他们的风格。}
{120}{}{这不是个坏小镇。齐默曼是个公正的人，虽然可能不太聪明。当然，我们还有迈尔斯，可能是方圆百里内唯一懂科学的人。}
