{100}{}{你看到了特蕾莎。}
{101}{}{你好，}
{102}{}{。你的旅程如何？}
{103}{}{还不错，谢谢。}
{104}{}{不太好。}
{105}{}{呼！}
{106}{}{很高兴听到这个。我就知道外面的世界不会像大家说的那么糟。我是说，我们的祖先不就是在外面生活的吗？但那个偏执的监督者就是不让我们出去。}
{107}{}{监督者可能有他的理由。}
{108}{}{其实，外面还挺糟的。}
{109}{}{你说得对，外面的世界并没有那么糟糕。}
{110}{}{监督者只是想保护我们。外面的世界对没有准备的人来说很危险。}
{111}{}{哦，听到这个我很遗憾。希望你能尽快找到芯片。}
{112}{}{应该没问题。}
{113}{}{遇到这么多危险，可能需要一些时间。}
{114}{}{嗯。我本来希望外面的世界能教会你如何交流。算了。}
{115}{}{我想他选择你出去是因为他知道你在他的掌控之下！他其实就是不想放弃对我们的控制。}
{116}{}{我对你的话感到不满！}
{117}{}{其实，我认为他觉得在这里安全的时候没有理由冒险去外面。}
{118}{}{嗯。根据我读到的，外面其实没有那么危险。但我想你比我更清楚，不是吗？}
{119}{}{我就知道外面不会太糟。这就是为什么我一直在试图说服一些人和我一起出去。我认为我们在外面生存的机会更大。}
{120}{}{你在说什么！？}
{121}{}{这可能是个好主意。}
{122}{}{我想也是。我一直以为他只是有某种权力欲。但我想如果他不是真正关心我们的福利，他就不会是监督者，对吧？我想我们应该等着看你能不能找到芯片。}
{123}{}{别担心，我会处理的。}
{124}{}{哦，拜托！醒醒吧！如果他认为外面那么危险，那他为什么派你出去？那个人就是有控制欲。你是个愚蠢的工具，你甚至都不知道！}
{125}{}{说实话，如果他认为外面那么危险，他会派一整个装备齐全的团队，而不是只派你。但你是他的棋子，因为他不想让任何人意识到他们错过了什么。}
{126}{}{哦，现实点吧！你真的认为我们可以一代又一代地生活在这个避难所里吗？也许你能找到一个新的芯片，但当下一个东西坏了怎么办？再下一个呢？}
{127}{}{嗯，我想你说得对。}
{128}{}{也许我们不能永远待在这里。但毫无准备地冲出去，并且没有团队的同意，这不是答案。}
{129}{}{我们很多人都这么想。这就是为什么我们计划在几天内带上一些补给出发。说，你有什么建议吗？}
{130}{}{抱歉，我在外面没找到什么有用的东西。}
{131}{}{你可以去一个叫阴影沙地的小村庄，就在东边几天的路程。他们或许能帮你。}
{132}{}{好的，谢谢。}
{133}{}{哦，走开！我们不需要监督者的棋子来帮忙！}
{134}{}{欢迎参加我们的会议！既然你被监督者选中去外面，也许你能在我们也准备移居到外面之前给我们一些建议。}
{135}{}{不要喝发光的水。}
{136}{}{嗯……还是别去了。}
{137}{}{我觉得你们的离开计划是不明智的。}
{138}{}{呜——！}
{139}{}{非常感谢。我看得出你会是个大帮手。你为什么不干脆离开呢？}
{140}{}{抱歉，我是来听这些的。}
{141}{}{好吧。}
{142}{}{真的吗？考虑到我们的处境，我们缺水的情况，以及这个避难所的初衷，你为什么认为我们应该留下？}
{143}{}{这只是个糟糕的主意，仅此而已。}
{144}{}{外面的世界对没有准备的人来说太危险了。最好有时间做好充分的准备再出去。监督者正试图给避难所争取所需的时间。}
{145}{}{好吧，考虑到你对外面有一些经验，也许你有一些有价值的观点。}
{146}{}{外面太危险和敌对了。你们撑不了多久。}
{147}{}{我只需要多一点时间来找到水芯片。}
{148}{}{如果你不能给我们不离开的好理由，我们就不会在这里等着被水中毒死。请不要妨碍我们。}
{149}{}{抱歉，各位，我不能让你们这样做。}
{150}{}{好吧。这是你们的选择。}
{151}{}{我们在这里的水迟早会用完。但这个避难所从来不是为了让人们永远待在里面！我们现在有足够的人和物资可以搬到外面去。我们有更好的机会。}
{152}{}{外面太危险了。}
{153}{}{避难所是为了让居民作为一个整体一起出去，而不是作为一个容易被压倒的小团体。}
{154}{}{嗯，也许你是对的。外面可能还有其他幸存者，他们也可能是敌对的。我想我们需要等到其他人都准备好。}
{155}{}{我们现在准备得很好。我们有设备和模拟训练。外面的一些危险总比慢慢渴死要好！}
{156}{}{抱歉，我现在不能让你们离开。}
{157}{}{那么，祝你好运。}
{158}{}{我不喜欢这样，但我想我们会等到大家都准备好一起离开。}
{159}{}{这是最好的选择。相信我，我知道自己在说什么。}
{160}{}{感谢大家再次到来。}
{161}{}{我们的计划仍在推进中。}
{162}{}{我们每周都在吸引更多的追随者。}
{163}{}{很快，我们将获得所需的装备。}
{164}{}{水芯片仍未找到。我们必须尽快行动。}
{165}{}{监督者无法反对如此庞大的队伍。}
{166}{}{耐心点。我们只需再等几周。}
{167}{}{到那时，我们终于可以摆脱避难所和监督者的束缚。}
{168}{}{记得在模拟器中练习你的野外技能！}
{169}{}{大家保重。}
{170}{}{请加快寻找水芯片的速度。我们等不了太久。}
{171}{}{别担心，我会的。}
{172}{}{我本以为你不会成功，但你做得很好。谢谢你拯救了我们所有人。}
{173}{}{你因和平平息避难所的革命派系而获得750点经验值。}
{174}{}{叛徒！你为什么还要回来？现在大家都要死了！}
{175}{}{我们之前已经讨论过了。别再打扰我们。}

# Theresa's tell-me-abouts
{1000}{}{芯片}
{1001}{}{避难所}
{1002}{}{战争}
{1003}{}{外面}
{1004}{}{监督者}
{1005}{}{水}
{1006}{}{水芯片}

{1100}{}{没有它，我们就没有饮用水。我们需要结束对这种设备的依赖，转而自给自足。}
{1101}{}{避难所已经是我们的家很久了，但现在是时候走出去。}
{1102}{}{我认为我们已经吸取了教训。现在是时候建立一个新世界，而不是担心旧世界。}
{1103}{}{外面才是我们应该去的地方！这是一次伟大的冒险，重新开始，靠自己的技能和智慧生活！}
{1104}{}{他沉迷于过去。他不愿接受我们该创造自己的未来。}
{1105}{}{没有它，我们就没有饮用水。我们需要结束对这种设备的依赖，转而自给自足。}
{1106}{}{没有它，我们就没有饮用水。我们需要结束对这种设备的依赖，转而自给自足。}
