{100}{}{你看到托马斯兄弟。}
{101}{}{好了，孩子们。今天我们要学习一些武术。}
{102}{}{在近身战中，你使用的技巧取决于对手的体型、攻击范围和速度。}
{103}{}{如果有机会，试探一下你的对手。}
{104}{}{不要急于攻击。}
{105}{}{好了，我的小家伙，试着伤到可怜的老爷爷吧。}
{106}{}{啊！}
{107}{}{呃。}
{108}{}{好了，现在就到这里，让我们复习一下。}
{109}{}{你看到他是怎么失去平衡的吗？}
{110}{}{过度伸展会让你容易受到反击。}
{111}{}{攻击时一定不要过度伸展。}
{112}{}{为什么过度伸展这么糟糕？}
{113}{}{如果有机会击杀，不应该去尝试吗？}
{114}{}{这是拿你的生命冒很大的风险。}
{115}{}{过度伸展会让你的内侧容易受到反击，并让你失去平衡。}
{116}{}{轻轻一推就能让你摔个四脚朝天。}
{117}{}{好吧，让另一个年轻小子试试对付老爷爷。}
{118}{}{看看你是否从上一个例子中学到了什么。}
{119}{}{不错，最后那招差点就打到我了。}
{120}{}{你确定想成为一个抄写员见习生吗？}
{121}{}{这些才能浪费了可惜。}
{122}{}{我们会把你留作后备。好吗？}
{123}{}{我只是跟你开个玩笑。}
{124}{}{你可能要重新考虑成为一名骑士。}
{125}{}{好好想想。}
{126}{}{谢谢托马斯兄弟。}
{127}{}{我希望你们都注意到安东尼兄弟没有过度伸展。}
{128}{}{他还试图利用我的体重和笨重来对付我。}
{129}{}{武术有其优点和缺点。}
{130}{}{我们将学习多种风格，以更好地理解它们的优缺点。}
{131}{}{好的。让我看看你的本事。}
{132}{}{很好。你坚持的时间比我预想的要长。}
{133}{}{你可以回到队伍中。}
{134}{}{希望你们这些孩子能看懂刚才发生的事情。}
{135}{}{他是个天生的斗士。}
{136}{}{再来一个。}
{137}{}{仔细观察……}
{138}{}{记住要始终打穿你的目标。}
{139}{}{假装你的目标在冲击点的几英寸之外。}
{140}{}{嗯，托马斯兄弟？}
{141}{}{是的，我的小泥块。}
{142}{}{我们踢的时候也应该这样做吗？}
{143}{}{当然。}
{144}{}{很好。我想我们会让你活下去。}
{145}{}{开个玩笑，偶尔微笑一下。}
{146}{}{这不是生死攸关的情况。}
{147}{}{以后会有很多这样的机会。}
{200}{}{不错。}
{201}{}{那相当不错。}
{202}{}{好，你在学习。}
{203}{}{保持专注。}
{204}{}{眼睛盯着我。}
{205}{}{不要过度伸展。}
{206}{}{永远不要从对手身上移开视线。}
{207}{}{练习你的格挡。}
{208}{}{保持重心低。}
{209}{}{太棒了！}
{210}{}{完美的姿势。}
{211}{}{我印象深刻。}
{300}{}{你通过观看训练获得了500点经验。}}
