{100}{}{你看到索恩戴克。}
{101}{}{我不会用我的技能来治疗敌人。离开这里。}
{102}{}{我听说过你。你是个冷酷无情的杀手。我不会治疗伤害过那么多人的人。离开这里。}
{103}{}{先生，我是个治疗者。你不需要我的服务。}
{104}{}{女士，我是个治疗者。你不需要我的服务。}
{105}{}{告诉我你的工作。}
{106}{}{这里是做什么的？}
{107}{}{你的服务收费多少？}
{108}{}{也许以后吧。}
{109}{}{你知道，我可以帮你招揽生意。我很擅长伤害人！}
{110}{}{嗯？}
{111}{}{先生，我已经给过你药了。我不敢现在再给你第二剂。}
{112}{}{女士，我已经给过你药了。我不敢现在再给你第二剂。}
{113}{}{告诉我你的工作。}
{114}{}{这里是做什么的？}
{115}{}{这药效真差。也许你该找点更强的？}
{116}{}{抱歉打扰了，医生。}
{117}{}{你知道，我可以帮你招揽生意。我很擅长伤害人！}
{118}{}{嗯？}
{119}{}{先生，你受伤了。如果你愿意，我可以治疗你。我是个治疗者。}
{120}{}{女士，你受伤了。如果你愿意，我可以治疗你。我是个治疗者。}
{121}{}{告诉我你的工作。}
{122}{}{这里是做什么的？}
{123}{}{多少钱？}
{124}{}{继续。}
{125}{}{不用了，谢谢。}
{126}{}{我讨厌医生！}
{127}{}{哦哦！哎哟！}
{128}{}{吼！！！}
{129}{}{先生，你伤得很重。我强烈建议你让我治疗你。我是个治疗者。}
{130}{}{女士，您受了重伤。我强烈建议您允许我为您治疗。我是一名治疗者。}
{131}{}{告诉我关于您的工作的事情。}
{132}{}{这个地方是做什么的？}
{133}{}{多少钱？}
{134}{}{不用了，谢谢。}
{135}{}{我讨厌医生！}
{136}{}{哎哟！好痛！}
{137}{}{吼！！！}
{138}{}{圣火命令我去治疗他人。它的智慧是无可争议的，所以我服从。我已经学到了很多关于大教堂之外的世界的知识。}
{139}{}{告诉我关于大教堂的事情。}
{140}{}{你学到了什么？}
{141}{}{这个地方是做什么的？}
{142}{}{抱歉打扰您了，医生。}
{143}{}{那一定是某种神圣的火焰！}
{144}{}{先生，请原谅，我没有耐心进行长时间的交谈。还有其他人可能比我更适合指导您。请原谅。}
{145}{}{女士，请原谅，我没有耐心进行长时间的交谈。还有其他人可能比我更适合指导您。请原谅。}
{146}{}{对我来说，先生，这里是一个施展治疗天赋的地方。对其他人来说，这里是一个可以收集迷途灵魂并引导他们走上正轨的地方。请原谅，我没有耐心进行长时间的交谈。还有其他人可能比我更适合指导您。请原谅。}
{147}{}{对我来说，女士，这里是一个施展治疗天赋的地方。对其他人来说，这里是一个可以收集迷途灵魂并引导他们走上正轨的地方。请原谅，我没有耐心进行长时间的交谈。还有其他人可能比我更适合指导您。请原谅。}
{148}{}{古代有一些智者相信美德本身就是回报。我也持有这样的信念。或许如果更多人分享这个观点，就不需要圣火了。请原谅，我没有耐心进行长时间的交谈。还有其他人可能比我更适合指导您。请原谅。}
{149}{}{再见。如果您需要我，我会在这里。我真心希望您不再需要见到我。}
{150}{}{这是一项服务，不是生意。您的才能不是我会夸耀的。现在请原谅我。}
{151}{}{唉，您的伤势可能超出了我的治疗能力。据说圣火可以引导那些被愚蠢诅咒的人走向救赎；我会为您祈祷。}
{152}{}{您受伤了。闲聊留到以后吧。请让我为您治疗。}
{153}{}{您不太擅长安慰病人，是吧，医生？}
{154}{}{我真的很想了解这个。}
{155}{}{您收费多少？}
{156}{}{请继续。}
{157}{}{不用了，谢谢。}
{158}{}{我讨厌医生！}
{159}{}{我是治疗者，不是放贷者。大教堂满足我的需求，所以我可以满足他人的需求。现在，让我来看看您的伤势，好吗？}
{160}{}{继续。}
{161}{}{很好。}
{162}{}{算了吧。你再不靠谱一点就该去池塘里游泳了。}
{163}{}{我讨厌医生！}
{164}{}{我建议你休息几天，虽然没人听我的建议。现在，离开这里。}
{165}{}{随你选择。如果你改变主意，我会在这里。}
{166}{}{[微笑] 可怕的人。我完全同情。[微笑消失] 如果你改变主意，我会在这里。你可以走了。}
{167}{}{我就当你是同意了。请不要杀我……}
{168}{}{哎哟！！[咆哮！]}
{169}{}{可怜的生物。像你这样智力低下的野兽，即便是圣火的治愈力量也难以应付。离开这里。}
{170}{}{我就当你是不同意。你可以走了……呃，你现在走吧！}
{171}{}{这是个非常美丽的地方，虽然现在有点拥挤。它在我们南边很远的地方。我们信徒聚集在一起赞美我们的主人，圣火，并祈求和平与统一。现在，如果这就是全部的话。}
{172}{}{告诉我关于和平与统一的事情。}
{173}{}{这个地方具体在哪里？}
{174}{}{是什么导致了拥挤？}
{175}{}{我讨厌医生！}
{176}{}{我了解到我们是一个充满怨恨、暴力和愚蠢的物种，不配拥有圣火。我到处看到贪婪和邪恶。除非我们采取激烈措施，否则我们将再次被圣火焚烧。}
{177}{}{告诉我更多关于圣火的事情……}
{178}{}{你的宗教真是糟糕透顶，伙计！}
{179}{}{有多少宗教承诺过人们会被焚烧？}
{180}{}{给我定义一下“激烈措施”。}
{181}{}{我讨厌医生！}
{182}{}{确实如此，但这里还有其他人能比我更有说服力地阐述它的辉煌。再见。}
{183}{}{你打断了我的思考！你到底想不想被治愈？}
{184}{}{你为什么这么激动？}
{185}{}{你看起来一开始就没什么集中力！}
{186}{}{继续。}
{187}{}{不用了，谢谢。}
{188}{}{我讨厌医生！}
{189}{}{和平总是由战争和艰难困苦铸造而成，统一也是如此。唉，我的能力在未来的日子里会被需要。}
{190}{}{告诉我关于战争的事？}
{191}{}{统一值得这样的代价吗？}
{192}{}{为什么每个人都认为战争是通往和平的答案？}
{193}{}{让我弄清楚。你在为一个计划死亡和毁灭的宗教服务，而你对此没有问题？你真是个白痴！}
{194}{}{旧世界充满了邪恶和堕落。圣火摧毁了它。我们可以选择畏惧圣火，或者崇拜它并试图理解它。孩子们选择了理解。虽然我们不希望再次看到圣火被释放。}
{195}{}{你怎么知道旧世界是什么样的？}
{196}{}{崇拜？炸弹？炸弹有什么好？}
{197}{}{如果圣火如此伟大，为什么你不想一直看到它？}
{198}{}{让我弄清楚。为了理解某样东西，你必须崇拜它？}
{199}{}{你们这些人真是疯了！}
{200}{}{当我要求别人做事时，我不希望被忽视。如果你选择忽视我的愿望，我也可以忽视你的伤势。再见。}
{201}{}{你以为你是谁？从我眼前消失，你这个小暴徒！}
{202}{}{你今天从我这里打探了足够多的信息。再见，先生。}
{203}{}{你今天从我这里打探了足够多的信息。再见，女士。}
{204}{}{圣火是旧世界死亡和新世界开始的隐喻。它是生与死的力量。还有什么比这更值得崇拜的呢？}
{205}{}{我的枪也有生杀大权，但你没见哪个疯狂的教派去崇拜它！}
{206}{}{也许你是对的。我得好好想想。}
{207}{}{呃，还有食物、性爱和一把大枪，我能想到很多更值得崇拜的东西！}
{208}{}{你不常出门，是吧？}
{209}{}{你不太有说服力，医生。}
{210}{}{这场辩论让我厌倦了。请离开我。}
{211}{}{我还记得你的侮辱，先生。在我治疗你之前，你可以在辐光中腐烂。}
{212}{}{我还记得你的侮辱，女士。在我治疗你之前，你可以在辐光中腐烂。}
{213}{}{贾因母亲希望没人和你说话。再见。}
{214}{}{白痴。你看不出他需要休息吗？}
