{100}{}{你看到赛拉克斯，一个思考者夜行者。}
{101}{}{你看到贾斯汀，一个思考者夜行者。}
{102}{}{你看到赛琳，一个思考者夜行者。}
{103}{}{你看到多尔卡恩，一个思考者夜行者。}
{104}{}{你看到霍特，一个思考者夜行者。}
{105}{}{你看到克里斯，一个思考者夜行者。}
{106}{}{你看到胡安妮塔，一个思考者夜行者。}
{107}{}{你看到莱斯利，一个思考者夜行者。}
{108}{}{你看到伦菲尔德，一个思考者夜行者。}
{109}{}{你看到提摩西，一个思考者夜行者。}
{110}{}{欢迎哦，庞特一号。你来的正是时候，可以帮助我们。}
{111}{}{嗯？}
{112}{}{当然，没问题。}
{113}{}{抱歉，我太忙了。}
{114}{}{我为什么要帮助你们？}
{115}{}{没关系，简单的人。跟我来，我会带你去工作地点。}
{116}{}{这不是请求。你的到场是必须的。}
{117}{}{你不是那个想为废土带来和平的人吗？}
{118}{}{是的，不过我不明白帮助你们怎么能实现这一点。}
{119}{}{不，我更喜欢大规模破坏。}
{120}{}{我们相信如果所有人，变种人和人类，能够学会合作，那么许多问题都能得到解决。}
{121}{}{听起来不错，算我一个。}
{122}{}{算了吧。}
{123}{}{这听起来有点不对劲。}
{124}{}{一切都很好。也许是你头脑的局限性阻碍了你的思维进步。}
{125}{}{你可能是对的，算我一个。}
{126}{}{也许吧。让我检查一下你的头骨。}
{127}{}{如果这是你的愿望，那你就会如愿以偿。}
{128}{}{欢迎回来。你现在将协助我们。}
