{100}{}{你看到特莉莎，来自污秽坑酒吧的女服务员。}
{101}{}{你在我房间里干什么？}
{102}{}{咕！}
{103}{}{哎呀，抱歉。我以为这是我的房间。}
{104}{}{抱歉。再见。}
{105}{}{没门！我对这个没兴趣！去找走廊尽头的辛西亚聊聊吧。她可能有空，但绝不会免费。}
{106}{}{好吧，随便你。这是我的房间。滚出去。}
{107}{}{你在我房间里干什么？}
{108}{}{咕噜！}
{109}{}{哎呀，抱歉。我以为这是我的房间。}
{110}{}{你认识一个叫索尔的人吗？}
{111}{}{我以前是这么认为的。现在，我不太确定。}
{112}{}{他真的很在乎你。}
{113}{}{我觉得你应该甩了他。}
{114}{}{他说是这样。如果真在乎，他就不会做那些事。}
{115}{}{什么事？}
{116}{}{是他的拳击，对吧？}
{117}{}{你会这么说。你是想取代他的位置，对吧？}
{118}{}{不。你太不靠谱了。}
{119}{}{当然。}
{120}{}{别烦我。}
{121}{}{也许你说得对。也许我该理解他在做什么，然后就这样吧。}
{122}{}{当然是他的打斗。我不明白。}
{123}{}{这是男人的事。}
{124}{}{当然不是，亲爱的。}
{125}{}{当然是他的拳击。他是个很好的人，但他需要在这事要了他命之前退出。}
{126}{}{也许这就是他想做的。}
{127}{}{嘿，我在污秽坑见过你。你在我房间里干什么？}
{128}{}{柏拉图}
{129}{}{我想更仔细地看看你。}
{130}{}{我想从你这儿打听点消息，我不想在那个酒保面前说。}
{131}{}{别来烦我，你这个废物。辛西亚可能适合你，但我可不是。}
{132}{}{你最好别来烦我。我真的不想跟你说话。}
{133}{}{抱歉打扰你了。}
{134}{}{离开我的房间！}
{135}{}{我要去找玛塞尔，她会收拾你的。}
{136}{}{我男朋友能揍扁你。}
{137}{}{听着，这是我的房间。请离开。}
{138}{}{谢谢你帮了索尔。他真是个好人。}
{139}{}{你害死了我男朋友。我本该恨你，但我知道迟早会发生。请别再打扰我。}
{140}{}{嘿，谢谢你在那些骷髅帮袭击我时帮了我。现在愿意这么做的人不多了。}
{141}{}{嗯。}
{142}{}{不客气。回头见。}
{143}{}{不客气。我能问你几个问题吗？}
{144}{}{我想可以。}
{145}{}{酒吧是谁的？}
{146}{}{谁是吉兹莫？}
{147}{}{你为什么要为索尔尖叫？}
{148}{}{谢谢，再见。}
{149}{}{尼尔是酒吧的老板。他是个好人，总是对我很好。我们以前约会过，但他对我太认真了，我不想成为寡妇。}
{150}{}{哦！索尔，你在哪儿？！?}
{151}{}{Zzzz}
{152}{}{抱歉，我们关门了。请稍后再来。}
{153}{}{没事，谢谢。}
{154}{}{吉兹莫经营赌场。他想接管尼尔的酒吧，但尼尔不想卖。}
{155}{}{基利安和吉兹莫互相看不顺眼。两人中要么一个离开小镇，要么被埋在这里。}
{156}{}{欢迎来到污泥坑。我能给你来点喝的吗？}
{157}{}{好的，你们有什么？}
{158}{}{索尔是我男朋友。他对我很好。}
{159}{}{其实，我能问你几个问题吗？}
{160}{}{不，你确实不能。如果你不打算点饮料，那你来错地方了。}
{161}{}{你想要点什么？}
{162}{}{Gizmo，嗯，Gizmo想接管酒吧。如果Neal不卖，我敢打赌会发生一些不好的事情。}
{163}{}{总有一天，会有个混蛋为了杯水或其他愚蠢的理由杀了Neal。要是你没注意到，现在经营酒吧可不容易。}
{164}{}{Nuka-Cola，3瓶盖。}
{165}{}{啤酒，5瓶盖。}
{166}{}{烈酒，20瓶盖。}
{167}{}{你看到一个女服务员。}
{168}{}{不过，为Gizmo工作会要了他的命。}
{169}{}{不，但你不能改变他，他也不能改变你。如果你不喜欢他做的事，那你应该另找出路。}
{170}{}{嗯哼！呼！}
{171}{}{抱歉，看起来你已经有点醉了。}
{172}{}{你因帮助在酒吧斗殴中击败Skulz获得300经验值。}
{173}{}{你因挽救Saul和Trish的关系获得250经验值。}
{174}{}{给你。请享用。}
