{100}{}{你看到特洛伊。}
{101}{}{恭喜你，人类。你被选中加入一个精英崇拜者团体。跟我来。}
{102}{}{这不会和那个关于超级变种人大军肆虐的传闻有关吧？}
{103}{}{我们要去哪儿？}
{104}{}{你还在等什么？我们走吧！}
{105}{}{我不这么认为。}
{106}{}{这股可怕又恶心的尸臭是什么？哦，原来是你！}
{107}{}{呃？}
{108}{}{跟我来你就会知道。或者换句话说，跟我来才能活，蠢货！}
{109}{}{所以如果我不去，我就死？这听起来不太像宗教。}
{110}{}{你说服我了。我们快走吧！}
{111}{}{我不这么认为。}
{112}{}{别开始你完不成的事，怪胎！}
{113}{}{太好了！}
{114}{}{你不该拿简女士或孩子们开玩笑。}
{115}{}{你不该侮辱你无法杀死的东西。现在，你是要跟我走活命，还是留在这里等死？}
{116}{}{我来了！}
{117}{}{算了。}
{118}{}{天啊，有些变种人真是开不起玩笑！}
{119}{}{如果我继续闻到你的味道，我反正也会倒下！}
{120}{}{你这愚蠢的野兽！你是来还是留？}
{121}{}{呃……来！}
{122}{}{呃……我留！}
{123}{}{别用犹豫来烦我！你的答案是什么，人类？}
{124}{}{我跟你走。我们走吧。}
{125}{}{算了。}
{126}{}{你敢推我！没人能命令我！}
{127}{}{无礼的狗！你现在就得死！}
{128}{}{别用你的玩笑烦我！你的答案是什么，人类？}
{129}{}{我跟你走。我们走吧。}
{130}{}{算了吧。}
{131}{}{别逼我，伙计。我还在想个聪明的回嘴呢……}
{132}{}{变种人无视了你。}
