{100}{}{你看到一个穿着尘土飞扬的皮甲，披着风衣，戴着防毒面具的男人。}
{101}{}{你看到泰科。}
{102}{}{又一个新面孔。这里的旅行者多如牛毛。不过你看起来有些与众不同。要不要和我一起喝一杯？}
{103}{}{抱歉，我现在时间比较紧张。}
{104}{}{好的。}
{105}{}{呃，什么？}
{106}{}{太好了。我希望你不介意喝点稀释过的酒——他们这里对啤酒的照顾就像对盆栽一样。}
{107}{}{那么，你的故事是什么？}
{108}{}{是啊，喝水。算了吧。}
{109}{}{我也可以问你同样的问题。为了友好起见，我先说。我叫泰科，来自东边，以前叫内华达的地方。}
{110}{}{那可是段很长的旅程。}
{111}{}{你是怎么在那么多危险中活下来的？}
{112}{}{是啊，确实是。我决定暂时放松一下。这个地方有些潜力，只要有人能清理掉一些渣滓。}
{113}{}{为什么你不去做呢？}
{114}{}{是啊，我注意到了。你对那些混蛋知道些什么？}
{115}{}{接受过不错的训练，还有些好武器。我爷爷以前是个游侠，他把所有知道的都教给了我父亲。父亲又传授给了我。所以我知道不要喝发光的水，打个比方。}
{116}{}{有趣。谢谢你的酒。}
{117}{}{真的吗？现在生存很艰难。你一定很有见识。}
{118}{}{这不是我的职责。毕竟，我不想和基利安对着干。他会在有空的时候清理这个镇子。是个好人，记住我的话。但要小心那个叫吉兹莫的家伙。他让我想起我父亲在拉斯维加斯告诉我的另一个肥胖怪物。}
{119}{}{谢谢你的建议和酒。}
{120}{}{这里有两种等级的渣滓。其中一种是骷髅帮，他们在马塞尔的破屋后面聚集。只是些二流货。但另一种是听命于一个肥胖怪物的，你应该能猜到他的名字。他经营赌场。那些家伙组织严密，非常危险。}
{121}{}{我明白了。谢谢你的信息。}
{122}{}{是啊，我的家人教会了我所有关于生存的知识。比如，不要喝那些完全清澈，没有昆虫和苔藓的水。在荒野中，只有有毒或放射性的水才会那么干净。还有很多其他小细节需要注意。}
{123}{}{比如什么？}
{124}{}{如果你有时间，我可以给你讲一些要点。}
{125}{}{当然，那太好了。}
{126}{}{抱歉，我现在时间有点紧。}
{127}{}{哇，别那么快。我们还没介绍完呢，记得吗？你的名字是什么，陌生人？}
{128}{}{我是}
{129}{}{。}
{130}{}{不关你的事，你这个疯子。}
{131}{}{很高兴见到你。小心行事，朋友。}
{132}{}{现在，现在，没必要这么无礼。但你这种态度最好还是走吧。}
{133}{}{咬我啊。}
{134}{}{随便。再见。}
{135}{}{你想要什么？}
{136}{}{抱歉打扰你的私人时间。去别的地方自娱自乐吧。}
{137}{}{我需要关于这里流氓的信息。}
{138}{}{我需要关于这个镇子的信息。}
{139}{}{又见面了。我能帮你什么忙？}
{140}{}{基利安让我来清理这个镇子，我希望你能帮忙。}
{141}{}{这里是斯卡姆酒吧，一个罪恶的巢穴。往西是吉兹莫的赌场，听说那里的游戏都是作弊的。再往南是崩溃旅馆，由马塞尔经营，住一晚要花很多瓶盖。再过去是基利安的店，他经营一家杂货店，同时也是这里的执法者——是个好人。再往南是莫比德医生，他的诊所有些古怪，你懂我的意思。}
{142}{}{希望我的小课程对你有帮助。}
{143}{}{}
{144}{}{听说你和吉兹莫有接触。如果我是你，会小心那个肥桶。}
{145}{}{我的事不关你的事。}
{146}{}{是的，我现在为吉兹莫工作。关你什么事？}
{147}{}{说得过去。但小心点。吉兹莫可不以关心员工著称。}
{148}{}{只要说你的雇主在这个镇子上已经制造了太多的痛苦和纷争。别指望能从任何人那里得到帮助，尤其是吉兹莫。真可惜，你本可以让这个镇子变得更好。}
{149}{}{我能为你做些什么？}
{150}{}{有什么建议吗？}
{151}{}{谢谢你的帮助。我想是时候分道扬镳了。}
{152}{}{是啊，我会远离制造这个东西的东西。说真的，我从没见过这样的东西。我想我们最好的选择就是赶紧离开。}
{153}{}{好的。我必须说这是一种荣幸和乐趣。}
{154}{}{小心放射性热点。这个地方显然遭受过直接的核打击，二次辐射可能很严重。如果可以，我建议完全避开这个地方。}
{155}{}{注意这里相当远的地方都没有动物生命。还有那些骨堆。住在这里的东西真是个怪物。把武器准备好。}
{156}{}{像这样的军事基地一定有一个中央指挥室。}
{157}{}{我打赌我们可以通过一些热接线穿过那些力场发生器，或者找到力场控制电脑。}
{158}{}{关于死城的奇怪传闻有很多。保持警惕，因为情况可能会很快变得危险。}
{159}{}{我需要改变队形。}
{160}{}{你希望我保持什么距离？}
{161}{}{保持靠近。}
{162}{}{保持适中距离。}
{163}{}{移到远距离。}
{164}{}{你学过哪些武器技能？}
{165}{}{相当不错的游侠训练：我当然可以使用长矛；我也擅长使用小型手枪和步枪。}
{166}{}{呃，没事。}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#

{167}{}{是的，如果你喜欢烤得很熟的蜥蜴。}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{168}{}{终于到了。带路吧，我的朋友，让我们来清扫街道。如果可以的话，我建议先对付吉兹莫。}
{169}{}{终于到了。带路吧，我的朋友，让我们来清扫街道。如果可以的话，我建议先对付吉兹莫。}

{170}{}{有什么事吗？}
{171}{}{我觉得我们还是在一起比较好。}
{172}{}{没什么。算了。}
{173}{}{你获得了300点经验值，因为招募了沙漠游侠泰克。}

#
# Tycho tell-me-abouts
#

{1000}{}{废城}
{1001}{}{游侠}
{1002}{}{芯片}
{1003}{}{战争}
{1004}{}{荒地}
{1005}{}{追随者}
{1006}{}{大教堂}
{1007}{}{加尔}
{1008}{}{大师}
{1009}{}{统一}
{1010}{}{塞特}
{1011}{}{水坝}
{1012}{}{墓园}
{1013}{}{大厅}
{1014}{}{图书馆}
{1015}{}{监督者}
{1016}{}{医疗}
{1017}{}{治疗}
{1018}{}{避难所}
{1019}{}{避难所13}
{1020}{}{避难所13}
{1021}{}{基利安}
{1022}{}{吉兹莫}
{1023}{}{荒园}
{1024}{}{阴影}
{1025}{}{沙地}
{1026}{}{中心城}
{1027}{}{赌场}
{1028}{}{商店}
{1029}{}{死亡爪}
{1030}{}{出埃及记}
{1031}{}{新兵}
{1032}{}{圣骑士}
{1033}{}{文士}
{1034}{}{孩子们}
{1036}{}{兄弟会}
{1037}{}{水罐}
{1038}{}{军事}
{1039}{}{基地}
{1041}{}{末日浩劫}
{1042}{}{变种人}
{1043}{}{莫菲斯}
{1044}{}{可汗}
{1045}{}{坦迪}
{1046}{}{艾莉娅}
{1047}{}{黛安娜}
{1048}{}{格温}
{1049}{}{佩特罗克斯}
{1050}{}{托利亚}
{1051}{}{酒类}
{1052}{}{化学药品}
{1053}{}{塞斯}
{1054}{}{阿拉迪什}
{1055}{}{拉兹洛}
{1056}{}{齐默尔曼}
{1057}{}{治安维持者}
{1058}{}{拾荒者}
{1059}{}{刀锋帮}
{1060}{}{妮可}
{1061}{}{中尉}
{1062}{}{精神控制者}
{1063}{}{实验}
{1064}{}{警察}
{1065}{}{商人}

{1100}{}{嗯，废城并不算是我的家，但它是个有趣的城市。它有潜力，尽管我不认为用过去的废料去打造未来是最佳方法。}
{1101}{}{我们游骑兵来自东部，曾被称为内华达的地方。我们的传统可以追溯到德克萨斯游骑兵时代。我们学习生存和战斗技能，以便在世界上有更多的生存和改善机会。}
{1102}{}{我很长时间没见过老科技的遗物，比如水处理芯片了。个人而言，依靠自己要比依赖那些无法修复的科技装置要好。}
{1103}{}{战争是人类贪婪和疯狂的证明。希望我们已经吸取了足够的教训，不再重蹈覆辙。}
{1104}{}{废土充满敌意和危险，即便是警觉的旅行者也难以幸免。辐射和怪异生物都会带来伤害。谨慎行事，并记住你所见所闻都是线索。}
{1105}{}{对不起，我帮不了你。}
{1106}{}{对不起，我帮不了你。}
{1107}{}{对不起，我帮不了你。}
{1108}{}{对不起，我帮不了你。}
{1109}{}{对不起，我帮不了你。}
{1110}{}{对不起，我帮不了你。}
{1111}{}{对不起，我帮不了你。}
{1112}{}{死亡之城这个名字取得很贴切。它位于曾经的小镇贝克斯菲尔德。如今，这里却成了尸鬼和更糟糕东西的家园。}
{1113}{}{抱歉，我帮不了你。}
{1114}{}{抱歉，我帮不了你。}
{1115}{}{抱歉，我帮不了你。}
{1116}{}{抱歉，我帮不了你。}
{1117}{}{抱歉，我帮不了你。}
{1118}{}{我听说过那些伟大的地下避难所。不过，我对它们了解不多。}
{1119}{}{我听说过那些伟大的地下避难所。不过，我对它们了解不多。}
{1120}{}{我听说过那些伟大的地下避难所。不过，我对它们了解不多。}
{1121}{}{基利安是个好人，正在做一份艰难的工作。}
{1122}{}{吉兹莫嘛……他给我的感觉就是个骗子。最终他会自食其果。}
{1123}{}{骨园？我听说那是个帮派横行、生活艰难的地方，靠近海岸。}
{1124}{}{抱歉，我帮不了你。}
{1125}{}{抱歉，我帮不了你。}
{1126}{}{集市是一个巨大的商业社区，就在垃圾镇南边不远。}
{1127}{}{吉兹莫的赌场可能是我最不想去的地方之一，除非我打算踩在吉兹莫的脖子上。当然，我可能连脚都伸不过他那一身肥肉。}
{1128}{}{基利安在垃圾镇有一家不错的杂货店。}
{1129}{}{听说有种东西比任何活物都更快、更大、更凶猛。听到的传闻不多，这意味着它留下的幸存者不多。大爪子，凶狠的性情。}
{1130}{}{抱歉，我帮不了你。}
{1131}{}{抱歉，我帮不了你。}
{1132}{}{抱歉，我帮不了你。}
{1133}{}{抱歉，我帮不了你。}
{1134}{}{抱歉，我帮不了你。}
{1136}{}{抱歉，我帮不了你。}
{1137}{}{抱歉，我帮不了你。}
{1138}{}{我知道军方有几个秘密基地分布在各地。但我不知道具体位置。}
{1139}{}{我知道军方有几个秘密基地分布在各地。但我不知道具体位置。}
{1141}{}{核末日是傲慢和愚蠢的结果。现在，我们正在为此付出代价。}
{1142}{}{外面确实有些奇怪的东西。我见过变异的蝎子和牛，还听说死城是尸鬼的家园，他们看似人类但却大相径庭。}
{1143}{}{抱歉，我帮不了你。}
{1144}{}{抱歉，我帮不了你。}
{1145}{}{抱歉，我帮不了你。}
{1146}{}{抱歉，我帮不了你。}
{1147}{}{抱歉，我帮不了你。}
{1148}{}{抱歉，我帮不了你。}
{1149}{}{抱歉，我帮不了你。}
{1150}{}{抱歉，我帮不了你。}
{1151}{}{我更喜欢喝浓烈的黑啤酒，或者来瓶核子可乐。}
{1152}{}{如果我是你，我会远离化学药品。虽然它们能让你短暂提升，但最终总要付出代价。}
{1153}{}{抱歉，我帮不了你。}
{1154}{}{抱歉，我帮不了你。}
{1155}{}{抱歉，我帮不了你。}
{1156}{}{抱歉，我帮不了你。}
{1157}{}{抱歉，我帮不了你。}
{1158}{}{抱歉，我帮不了你。}
{1159}{}{抱歉，我帮不了你。}
{1160}{}{抱歉，我帮不了你。}
{1161}{}{抱歉，我帮不了你。}
{1162}{}{你是说心灵感应？呵呵……说真的，我不相信。}
{1163}{}{抱歉，我帮不了你。}
{1164}{}{抱歉，我帮不了你。}
{1165}{}{一些来自枢纽的商人定期访问废城和其他城市。}
