{100}{}{你面前是尤瑟恩，超级变种人的领袖。}
{101}{}{普通人！你怎么敢进入比你更优越者的领地？}
{102}{}{嗯？}
{103}{}{像你这样的渣滓永远不可能比人类更好！}
{104}{}{去死吧，变种怪！！}
{105}{}{真的吗？你自称更优越，但有什么证据呢？}
{106}{}{如果你认为自己比其他人更优越，那你就陷入了过度概括的谬误。}
{107}{}{真是奇迹，你们的种族竟然存活了这么久。我会从你开始进行清洗。}
{108}{}{你用无聊的评论只证明了我的观点。我个人不愿见到你，但我的主人想和你谈谈。}
{109}{}{带我去见你的主人。}
{110}{}{试试这句话——去死吧！}
{111}{}{你这样的聪明人应该能看出，这样的行为解决不了任何问题。}
{112}{}{乐意效劳。}
{113}{}{你是在说谈话解决不了问题吗？你比我想的还要愚蠢。}
{114}{}{虽然你很愚蠢，我指的是你说话的方式。}
{115}{}{啊，笨蛋终于意识到了一些东西。}
{116}{}{言语只能解决有限的问题。这会解决更多。}
{117}{}{我开始觉得你可能还有点优良血统。让我来确认一下。}
{118}{}{确实如此，因为死亡将是你的救赎。}
{119}{}{这是给你的最简单证明。我比你更聪明、更强壮、更敏捷。要不要来试试我的技能？}
{120}{}{不用了，谢谢。我相信你。}
{121}{}{你忘了自大、愚蠢和丑陋。}
{122}{}{当然。让我看看你能做什么。}
{123}{}{很好。你想要获得更强大力量的机会吗？}
{124}{}{当然想！}
{125}{}{绝不可能！}
{126}{}{我不太确定。}
{127}{}{去死吧！}
{128}{}{那么我就带你去见我的主人。}
{129}{}{几乎令人遗憾。没关系，这不会花很长时间。}
{130}{}{给予你世间所有的力量，你却仍然恐惧。我会帮助你做出决定。}
{131}{}{这样的评论只证明我比你聪明得多。现在，你将为你的无礼付出代价！}
{132}{}{你接受信用卡，还是只收瓶盖？}
{133}{}{绝不！！}
{134}{}{抱歉，我现在瓶盖有点紧。能给我个延期吗？}
{135}{}{什么？我觉得可以这么概括——你现在要跟我走。}
{136}{}{很高兴再次见到你。我听说你在这里游荡。我奉命带你回去。}
