{100}{}{你看到了一位13号避难所的居民。}
{101}{}{我们没想到你会回来。你的房间真不错，而我们和她的父母住得有点挤。我希望你不介意。}
{102}{}{当然介意。离开我的房间！}
{103}{}{没关系，我不在乎。好好享受这个房间吧。}
{104}{}{我希望能有自己的房间。请找其他地方住。}
{105}{}{哼。}
{106}{}{听着，我不想和你争论，但显然你不再配得上这个房间。请离开。}
{107}{}{我们真的很需要这个空间。希望你能重新考虑。}
{108}{}{好吧，让我想一想。嗯，不行。出去！}
{109}{}{好吧，你比我更需要这个地方。}
{110}{}{谢谢！我们真的很感激。你的东西放在箱子里了。}
{111}{}{嗯，我不知道。你似乎不常用这个房间，而我们确实需要这个空间。}
{112}{}{好吧，给你。}
{113}{}{我需要这个地方来记住我的根。而且，这也是个休息的好地方。}
{114}{}{天哪，我没想到你还会在意这个地方，听说你已经不在乎了。祝你有个好日子。我们会回到她母亲那里。}
{115}{}{我们真的很喜欢这里。}
{116}{}{你应该离开。这里不再属于你。}
