{100}{}{你看到范斯。}
{101}{}{我能为你做些什么？}
{102}{}{我买东西。}
{103}{}{你是谁？}
{104}{}{这栋楼里有什么活动？}
{105}{}{我听说你有我需要的东西。我能买点吗？}
{106}{}{没事了。再见。}
{107}{}{我叫范斯，这就是你需要知道的全部。我能为你准备点什么吗？}
{108}{}{如果你不告诉我你在卖什么，我怎么知道呢？}
{109}{}{很高兴认识你，范斯。你有什么要卖的？}
{110}{}{空}
{111}{}{没事了。再见。}
{112}{}{如果你不知道，那你不该在这里。现在离开。}
{113}{}{我想去哪就去哪！去死吧！}
{114}{}{好吧。我会离开的。}
{115}{}{没事了就是没事了！现在滚出去！}
{116}{}{来试试看……如果你敢的话，怪胎！}
{117}{}{好好好……我走。}
{118}{}{你看起来还不错。这是我有的东西。}
{119}{}{<交易>}
{120}{}{我能为你做些什么？}
{121}{}{想要更多。}
{122}{}{我想买更多东西。}
{123}{}{我不喜欢你这种人。}
{124}{}{那边的朋友是谁？}
{125}{}{后房的朋友是谁？}
{126}{}{只是闲逛。}
{127}{}{很遗憾听到这个。现在离开。}
{128}{}{不！}
{129}{}{我走了。}
{130}{}{那是贾斯汀和查德。他们在这里确保没人捣乱。}
{131}{}{他们看起来像一对娘娘腔。}
{132}{}{很高兴认识你们。}
{133}{}{我就待一会儿，如果你们没意见的话。}
{134}{}{只是我的一些朋友。你只需要知道这些。别问太多问题。}
{135}{}{好的。你有什么要卖的？}
{136}{}{我知道你在这里做什么，我不喜欢。}
{137}{}{我就待一会儿，如果你们没意见的话。}
{138}{}{我们来谈正事吧。}
{139}{}{好吧，你有什么货？}
{140}{}{我想我就待一会儿。}
{141}{}{你不受欢迎。现在给我滚出去！}
{142}{}{我要送你下地狱，那才是你该去的地方。}
{143}{}{抱歉，打扰了。}
{144}{}{嘿，冷静点。我们只是误会了。来谈谈吧。}
{145}{}{我不想惹麻烦，所以我觉得你最好离开，免得我做出让你后悔的事。}
{146}{}{不——！}
{147}{}{哦，好吧。我走。}
{148}{}{我不在乎你怎么想。}
{149}{}{算了。再见。}
{150}{}{别一次用完。}
{151}{}{谢谢。}
{152}{}{呃。}
