{100}{}{你看到一个大教堂之子的成员。}
{101}{}{我不与像你这样的异教徒交谈。}
{102}{}{你的报告，范哈根。}
{103}{}{主人对你的进展感到满意，但他的需求很大，时间有限。}
{104}{}{主人应该知道原材料有限。没有更多的储备，我们无法创造士兵。}
{105}{}{他知道你的问题。我们正在解决。}
{106}{}{告诉我他的计划。如果统一要成功，我们需要协调行动。}
{107}{}{主人发现了一个未被发现且仍在运作的避难所。有了这么多原材料，我们可以创造一支强大的力量。根据预测软件，这将是我们成功所需的数量。}
{108}{}{太好了。这真是太幸运了。居民是否受到污染？}
{109}{}{哦，这是最精彩的部分。如果他们的代表是个例子，他们是干净的。纯种。}
{110}{}{哦，这真是令人兴奋。我们要掠夺哪个避难所？}
{111}{}{避难所13。我们很快就会得到他们。非常快。}
{112}{}{你因偷听到关于你所在避难所的整个对话而获得1000经验值。}
