{100}{}{你看到瓦斯奎兹，一个雇佣兵亡命之徒。}
{101}{}{你看到一个外表邋遢的枪手。}
{102}{}{你想要什么？}
{103}{}{你是谁？}
{104}{}{哼。}
{105}{}{我不为愚蠢的人工作。你现在就离开。}
{106}{}{你没听说过我？我很受伤！我叫瓦斯奎兹·维拉诺瓦·埃尔南德斯·奥尔特加。我是个有名的亡命之徒，朋友。如果你需要，我可以被雇佣。}
{107}{}{真的吗？你要多少钱？}
{108}{}{也许再见吧……祝好运。呵呵。}
{109}{}{啊，直截了当，朋友。很好。我会为你在镇上提供帮助，每周只需区区500美元。我的服务不便宜，但我值得这个价。}
{110}{}{太好了，我雇你。这是500美元。}
{111}{}{抱歉打扰了，但我觉得我不需要你的服务。}
{112}{}{抱歉，朋友，我不为虚拟的钱工作。我需要冷冰冰的现金。}
{113}{}{太好了。我是你的。我们走吧，这地方让我厌烦。}
{114}{}{带路吧，我听从你的指挥！}
{115}{}{我们去喝点什么吧！}
{116}{}{我们先去哪儿？}
{117}{}{只要你待在废城，我就是你的。我不喜欢离开这个镇。}
{118}{}{你知道我头上有悬赏吗？不过太少了。}
{119}{}{啊，我的朋友。很高兴再次见到你。}
{120}{}{我想雇你一周。}
{121}{}{很高兴再次见到你。}
{122}{}{哼。}
{123}{}{好吧，也许再次见到你并不那么好。祝你有个好日子。}
{124}{}{当然。我的费用很低，而我的价值却很高。500美元，请。}
{125}{}{给你。}
{126}{}{你不该这么做，我即将死去的朋友。}
