# TRANSLATION NOTES
# Vinnie is a gang leader, who is young and ruthless. He tries to sound tough
# and is quite mean. He only respects people who are as ruthless and violent as
# himself.

{100}{}{你看到骷髅帮的维尼。}
{101}{}{你看到一个有纹身且态度恶劣的年轻人。}
{102}{}{我想加入你们。}
{103}{}{这里是骷髅帮的地盘，陌生人。你最好快点说。}
{104}{}{抱歉，走错房间了。}
{105}{}{骷髅帮？你们是谁？}
{106}{}{呃？}
{107}{}{没错，你确实走错房间了！}
{108}{}{我们是唯一的废城帮派。我们掌控街道，夜晚统治这座城市。}
{109}{}{哦。抱歉。再见。}
{110}{}{你连学校操场都管不了，傻瓜。}
{111}{}{我以为这座城市晚上是由基兹莫掌控的。}
{112}{}{滚出去，白痴！}
{113}{}{那个废物连站都站不稳。我们才是这城里的力量。我们拿我们想要的。}
{114}{}{我明白了。}
{115}{}{你和基利安有什么交易吗？}
{116}{}{什么？！你会为这句话付出代价的！}
{117}{}{我们不打扰基利安，他也不打扰我们，只要我们低调行事。明白吗？}
{118}{}{明白了。再见。}
{119}{}{我明白了，你们得躲着他。}
{120}{}{我们不怕任何人，尤其是基利安！就因为他自以为是个光荣的治安官，并不代表他能控制骷髅帮！}
{121}{}{抱歉，不想惹你生气。}
{122}{}{所以，他妨碍了你的风格，是吧？我也是。事实上，我在考虑干掉他。你想加入吗？}
{123}{}{你想干掉基利安？伙计，你疯了。伙计，我不知道……好吧，我加入。}
{124}{}{你这个失败者，你说我们要干掉基利安。滚出去。}
{125}{}{来吧，让我们干掉基利安。}
{126}{}{你现在想要什么？}
{127}{}{没什么。抱歉。}
{128}{}{我在找人帮我干掉基利安。骷髅帮看起来是个不错的选择。}
{129}{}{该死，我没想到你会干！现在骷髅帮统治这座城了！哇！}
{130}{}{我们之前就走过这条路。你当时没那个胆量，现在也没有，滚出去！}
{131}{}{你想加入我们，是吧？我们怎么知道你够不够硬气成为一名Skul？}
{132}{}{我会让你见识到什么叫硬气，你这个混蛋！}
{133}{}{让我向你证明我的实力。}
{134}{}{相信我，我够硬气。}
{135}{}{[Vinnie看着你大笑。] 我不这么认为。}
{136}{}{我会向你证明的。}
{137}{}{够了，你该死了。}
{138}{}{你说得对，我这就离开。}
{139}{}{Skulz凭什么这么硬气？}
{140}{}{[Vinnie想了一下。] 如果你想证明你属于Skulz，我要你去偷那个老家伙妻子的骨灰。呵呵。[Vinnie嘟囔着] 让Neal在最后的几个小时里受苦吧……}
{141}{}{好吧，我会去做。}
{142}{}{绝对不行。}
{143}{}{呃，我觉得我做不到。}
{144}{}{我已经偷到了。}
{145}{}{这没你想的那么难。我已经干掉了那个混蛋。}
{146}{}{如果你真有那么硬气，或许你真能成为一名Skul。拿到后带来给我。}
{147}{}{我就知道你不是Skulz的料。滚出去。}
{148}{}{你拿到了吗？}
{149}{}{是的。}
{150}{}{没有。}
{151}{}{我为了拿到它不得不杀了Neal。他哭得像个小女孩。}
{152}{}{哈哈！让那个老家伙受苦，直到今晚我们干掉他——你加入吗？}
{153}{}{我决定不想和你们这些渣滓有任何关系。}
{154}{}{让我们干掉他。}
{155}{}{我还有些其他事要做——我会在那里和你们碰面。}
{156}{}{你浪费我时间干什么？}
{157}{}{这会让那个老家伙明白的。谢谢你替我们解决了他。[Vinnie眼中含泪。] 你现在是个Skul了。}
{158}{}{呃，好吧……稍后见，但别拖太久。}
{159}{}{很快，Neal就要遭殃了，是吧？}
{160}{}{我们说过我们会回来的，你这个老家伙！}
{161}{}{酒吧来了很多人……}
{162}{}{去你的，警察！}
{163}{}{你偷走了尼尔的骨灰盒，获得400经验点。死者将永不安息。}
{164}{}{你干掉了尼尔，获得300经验点，你这个骷髅帮。}
{165}{}{你准备好干掉尼尔了吗？}
{166}{}{是的，让我们干掉这个混蛋。}
{167}{}{不，我还有些事情要做。}
{168}{}{不行，我要退出。}
{169}{}{太晚了，伙计。你退出了，就彻底退出了。}
{170}{}{我们统治这个城镇。}
{171}{}{嘿，兄弟，我们统治这个城镇！}
