{100}{}{你看到一个商队司机。}
{101}{}{嗨，如果你想在我们的商队找份工作，你应该去找主商人谈谈。她在东边那栋建筑里。}
{102}{}{抱歉，你需要和主商人谈谈。}
{103}{}{很好，你得到了许可。我就知道不会有问题。自从达伦·海塔沃开始躲在办公室里，她最近忙得不可开交。怪人。我们大约每五天出发一次。就是1号、5号、10号、15号、20号和25号。目前我们只去废城和洛杉矶墓园。}
{104}{}{那么工资是多少？}
{105}{}{嗯。}
{106}{}{我们的工资是200中心币。虽然不算高，但我们出发频繁，路线也不太危险。是的，和其他人一样，这是单程的工资，不过当然你不必来回都走。}
{107}{}{我们今天出发。你有兴趣吗？}
{108}{}{我们在}
{109}{}{空}
{110}{}{}
{111}{}{。你有兴趣吗？}
{112}{}{即便如此，我还是愿意给你一份工作。你有兴趣吗？}
{113}{}{当然。}
{114}{}{不。}
{115}{}{也许吧。}
{116}{}{是的。}
{117}{}{什么？}
{118}{}{哦，好吧。没问题。如果你改变主意，请告诉我。}
{119}{}{我希望你能下定决心。}
{120}{}{好吧，如果你决定为我们工作，就过来找我。就是1号、5号，以此类推。再见。}
{121}{}{抱歉，除非你能和其他队员清楚沟通，否则我不能雇用你。}
{122}{}{请在你感觉好些的时候再来。}
{123}{}{呃，你还好吗？我觉得你需要吃点东西，但别去鲍勃那儿。}
{124}{}{我说过滚开！}
{125}{}{我对你偷东西感到非常失望！你为什么要这么做？}
{126}{}{因为我是来自外太空的绿色怪物，我很坏！}
{127}{}{我不想这样，但我快饿死了，还有孩子要养。}
{128}{}{我会用勺子挖出你的心！}
{129}{}{（投降）}
{130}{}{（攻击）}
{131}{}{我试图帮助你，但看来有些人已经无药可救。很遗憾，我得用暴力解决这个问题。}
{132}{}{我理解，但这不能成为理由。我还是得请你离开。我们不能雇佣无法控制自己欲望的人。}
{133}{}{你真的以为我会相信这种鬼话吗？卫兵！}
{134}{}{很抱歉，有时候关一段时间能让人清醒。卫兵！尽量别杀了她。你愿意向我的卫兵投降吗？}
{135}{}{地狱见！}
{136}{}{是的，很抱歉。}
{137}{}{什么？你又要打架吗？}
{138}{}{很抱歉，但你必须立刻离开，否则我将不得不报警！}
{139}{}{卫兵！警察！}
{140}{}{我想你应该离开。}
{141}{}{抱歉，我不能雇佣你。}
{142}{}{拜托，你这样让我很为难。}
{143}{}{请离开。}
{144}{}{有趣，但你不是我的菜。}
{145}{}{太棒了！报酬是200胡币。你想选择哪条路线？}
{146}{}{太好了。请在}
{147}{}{1号}
{148}{}{5号}
{149}{}{10号}
{150}{}{15号}
{151}{}{20号}
{152}{}{25号}
{153}{}{来。你将从那时出发。报酬依旧是200胡币。}
{154}{}{好的。}
{155}{}{抱歉，不能等。}
{156}{}{真是悲剧。我们失去了整个商队，但你活下来了？这不应该发生。我不知道外面发生了什么，但我们不能再雇佣你了。很抱歉。}
{157}{}{废城}
{158}{}{洛杉矶墓园}
{159}{}{呃，现在不行。也许下次吧。}
{160}{}{太好了，我去叫其他人。}
{161}{}{很好。}
{162}{}{出发吧，祝好运！}
{163}{}{尽量避免麻烦，不要主动去找事。}
{164}{}{小心点，我不喜欢墓园的样子，感觉很诡异。}
{165}{}{不错。那些黑色的通道虽然很奇怪，但用来旅行很方便。}
{166}{}{我觉得那里有些帮派。和人说话时要非常小心。}
{167}{}{很好。废城是个不错的地方。}
{168}{}{哦，替我向那个Kill...问好？我忘了他的名字，但他是个不错的人。我很好奇他最近怎么样。}
{169}{}{有趣的地方。我听说那里有个邪恶的医生能让死人复活，或者类似的事情。}
{170}{}{你为什么离开了上次的商队？虽然没发生什么可怕的事，但可能会有。}
{171}{}{我可以再有一次机会吗？}
{172}{}{没什么。}
{173}{}{我才不在乎！}
{174}{}{Ig wa neeka rooola?}
{175}{}{Lig。}
{176}{}{抱歉，你又让我失望了。你似乎不太负责任，这对我们的工作来说不是个好组合。}
{177}{}{我为什么要这样做？}
{178}{}{你不应该。}
{179}{}{因为如果你不这样做，我就要在你脑袋上开个洞。}
{180}{}{我有更重要的事要做，不想在某个愚蠢的商队上浪费时间。}
{181}{}{我不知道我不能离开。一切看起来都没问题。}
{182}{}{我看你是嗑药了。好吧，如果你愿意过这样的生活。}
{183}{}{很遗憾你这么想。}
{184}{}{我很惊讶你以前从没做过商队，不过既然没出什么事，那好吧。我再给你一次机会。}
{185}{}{你干得不错！想再接一个商队吗？}
{186}{}{当然。}
{187}{}{不。}
{188}{}{也许吧。}
{189}{}{呀！}
{190}{}{Lub。}
{191}{}{准备好了吗？我们今天就要出发。}
{192}{}{是的。}
{193}{}{不！}
{194}{}{哎呀！}
{195}{}{否则我就把这个机会给别人，不用担心。在你跟随商队出发之前，你没有义务，对吧？}
{196}{}{你来得有点早。下一次商队出发要到}
{197}{}{1号}
{198}{}{5号}
{199}{}{10号}
{200}{}{15号}
{201}{}{20号}
{202}{}{25号}
{203}{}{。如果你还想要这份工作，到时候再来吧。}
{204}{}{一月}
{205}{}{二月}
{206}{}{三月}
{207}{}{四月}
{208}{}{五月}
{209}{}{六月}
{210}{}{七月}
{211}{}{八月}
{212}{}{九月}
{213}{}{十月}
{214}{}{十一月}
{215}{}{十二月}
