{100}{}{你看到水卫兵。}
{101}{}{你好，}
{102}{}{。}
{103}{}{你好。你最近怎么样？}
{104}{}{啊！}
{105}{}{嗯，啊！还给你……很遗憾你从未学会说话。我们本可以成为好朋友的。}
{106}{}{呃。}
{107}{}{我感觉不太好。有人用大铁管打了我的头。我去看了医生，但头还是很痛。真希望有人能抓住打我的混蛋。}
{108}{}{他们为什么这么做？}
{109}{}{咕。}
{110}{}{嗯，他们是在一个晚上很晚的时候袭击我的。通常我八点左右就回家了，但那天我待得晚了一些，因为有人偷了些水，我在检查我们的储备。接下来我就醒来发现自己在医疗室，头上起了个大包。这里的情况越来越疯狂了。很快就会有人为了水而丧命，我不知道我们能做些什么。}
{111}{}{我会看看能做些什么。}
{112}{}{抱歉。希望你能快点好起来。}
{113}{}{这是你的水。}
{114}{}{这是你今天的配给。}
{115}{}{嘿！你以为你在干什么？！}
{116}{}{请不要拿太多物资。我们需要这些。}
{117}{}{你在图书馆的计算机系统中记录了你的报告。你应该回去找监督者完成你的进度。}
# TRANSLATION NOTE
# The player-character's name is inserted by code between lines 118 and 119.
{118}{}{你好，}
{119}{}{。}
{120}{}{嗨。最近情况怎么样？}
{121}{}{说说，你在这里做什么？}
{122}{}{嗯，当然大家都很紧张，但我们没有遇到太多麻烦。希望你能尽快找到新的芯片。}
{123}{}{当然，我负责分发水的配给。我还要确保没有人拿超过他们份额的水，不过我觉得我们不会有太多麻烦。}
{124}{}{嗯，继续保持良好的工作。}
{125}{}{你也是。希望你能尽快找到那个芯片，这样我们都能恢复正常生活。}
{126}{}{如果你需要物资可以拿一些，因为你的工作很重要，但请不要拿太多。我们的存货不多了。}
{127}{}{我可以拿一些物资吗？}

{1000}{}{配给}
{1001}{}{配给}
{1002}{}{物资}
{1003}{}{水}

{1100}{}{我早上会分发水配给。既然你要去外面，你应该不再需要它们了。}
{1101}{}{我早上会分发水配给。既然你要去外面，你应该不再需要它们了。}
{1102}{}{我们的物资所剩无几。如果你需要它们来执行任务，可以拿一些，但请不要拿太多。}
{1103}{}{我早上会分发水配给。既然你要去外面，你应该不再需要它们了。}
