{100}{}{你看到扎克。}
{101}{}{你看到一个枪械跑商。}
{102}{}{嗨，我是扎克。你想买武器吗？让我看看你有什么可以交易的。}
{103}{}{不。}
{104}{}{好的。}
{105}{}{能给我打个折吗？}
{106}{}{你想买武器吗？让我看看你有什么可以交易的。}
{107}{}{抱歉打扰了。}
{108}{}{很高兴和你做生意。}
{109}{}{}
{110}{}{好的。如果需要什么再来找我。}
{111}{}{你最好快点决定。你是来买装备的，还是只是来这里找死的？}
{112}{}{你这态度可真有问题。}
{113}{}{抱歉，也许我确实需要一些装备。}
{114}{}{那你到底来这里干什么？}
{115}{}{没什么。}
{116}{}{当然。}
{117}{}{是啊，除非加布里埃尔说了算，否则你得像其他人一样付全价。}
{118}{}{我不太确定。}
{119}{}{不管怎样，给我看看你有什么。}
{120}{}{太好了！给我看看你有什么。}
{121}{}{我以后再来拿那个折扣。}
{122}{}{能给我更好的折扣吗？}
{123}{}{抱歉。我已经给了你最大的折扣了。}
