{100}{}{你看到一个暴徒。}
{101}{}{嘿，你不就是那个一直在找我们麻烦的混蛋吗？你来错地方了！}
{102}{}{嘿，你不就是那个一直在找我们麻烦的女人吗？你来错地方了，女士，这会让你付出代价！}
{103}{}{我现在是你这边的。所以让开！}
{104}{}{你搞错了。在废土上大家看起来都差不多。}
{105}{}{来错地方？我觉得挺对的！}
{106}{}{你想找事，我保证在我动手之前你先倒下。来吧，小子，动手吧！让我看看你的胆量！}
{107}{}{来错地方？我没迷路！}
{108}{}{是的。你想要什么？}
{109}{}{伙计，我只是想和一个真正的人说话。这些僵尸让我毛骨悚然。}
{110}{}{兄弟，你愿意和我一起赞美主人吗？}
{111}{}{嘿，只是想找个友好的人聊聊。}
{112}{}{我想见主人。}
{113}{}{我想看到一个山谷，里面插满了敌人的头颅。一个寂静的山谷，只有风在他们的耳边呼啸。}
{114}{}{食物！我要吃的！}
{115}{}{嘿，我是不是听说过你？你杀过不少东西，是吧？你来这里干什么？}
{116}{}{我听说这里发生了一些奇怪的事情。到底怎么回事？}
{117}{}{和平、统一之类的东西。}
{118}{}{主人在哪儿？}
{119}{}{只是找个朋友。找个人聊聊。}
{120}{}{我听说这儿的酒不错。}
{121}{}{我的脚。}
{122}{}{你想说话，最好把武器从我脸上拿开！现在放下！}
{123}{}{这是习惯。你放下态度，我就放下武器。}
{124}{}{我还没死，所以我不会放下。}
{125}{}{有什么问题？我只是想聊聊。}
{126}{}{我在站岗。}
{127}{}{你说什么？}
{128}{}{有话快说。}
{129}{}{这里发生了什么事？}
{130}{}{我想和主教谈谈。}
{131}{}{我想和这里的负责人谈谈。}
{132}{}{它！它-它-它-它-它-它-它！}
{133}{}{一堆狗屎。和平。统一。爱。很多傻子像僵尸一样到处乱跑。墨菲斯在楼上数他的瓶盖。拉舍名副其实。你想要加入吗，欢迎之至？}
{134}{}{我听说你们做的很多事情可不是什么和平与爱。}
{135}{}{墨菲斯在搞什么鬼？}
{136}{}{这个拉舍是什么人？}
{137}{}{好吧。你想要什么？}
{138}{}{你注意到这里有什么异常情况吗？}
{139}{}{这里到底发生了什么？}
{140}{}{主教在哪里？}
{141}{}{只是找个朋友。}
{142}{}{为了完成核爆开始的事情。}
{143}{}{伙计，离他远点！他完全是……我不知道该怎么形容。想象一下地球上你最不想认识的人。拉舍比那还糟。}
{144}{}{他和墨菲斯合得来吗？}
{145}{}{他做了什么？为什么他这么坏？}
{146}{}{你还没见过我呢，伙计。}
{147}{}{去找墨菲斯谈谈，希望他不会因为你问这个而杀了你。}
{148}{}{我想他不会这么做。我有重要的信息。}
{149}{}{他为什么要这么做？}
{150}{}{这和墨菲斯有什么关系？}
{151}{}{嗯，这个世界就是‘杀或被杀’，而我还活着！}
{152}{}{是什么样的信息？}
{153}{}{这里有间谍。我需要马上见负责人。}
{154}{}{我可以告诉你，但我得杀了你。}
{155}{}{呃……好吧……我不能谈这个。}
{156}{}{大教堂里有人快死了。也许会有很多人。}
{157}{}{好吧。我不在乎你是谁。现在从我面前消失！}
{158}{}{大家！把这个混蛋干掉！}
{159}{}{先生，你疯了！为什么不离开这里呢？}
{160}{}{女士，你疯了吧！你为什么不离开这里？}
{161}{}{因为我玩得很开心。你有什么问题？我还没把你开膛破肚呢——还不够胆吗？}
{162}{}{因为我还没杀了你！}
{163}{}{是啊，我真想要你的陪伴。就像上次我多享受一样！滚开！}
{164}{}{你好。你的武器不错。现在试着放下它。}
{165}{}{这是一种习惯。你放下态度，我就放下武器。}
{166}{}{我还没死，所以我不会放下。}
{167}{}{有什么问题吗？我只是想聊聊。}
{168}{}{我在执行守卫任务。}
{169}{}{谢谢你的夸奖。笨蛋。}
{170}{}{你说什么？}
{171}{}{好吧。你想要什么？}
{172}{}{你有没有注意到这里有什么异常情况？}
{173}{}{这里发生了什么事？}
{174}{}{主人在哪儿？}
{175}{}{只是找个朋友。}
{176}{}{想看你的头从肩膀上掉下来，这样我就可以像踢足球一样在房间里踢来踢去，直到你的头骨被完全砸碎！}
{177}{}{如果你没穿那些长袍，我早就杀了你。既然如此，我还是想杀了你。离我远点。现在。}
{178}{}{你不是夜行者。守卫！我们有间谍……}
{179}{}{他们到底从哪儿把你挖出来的？你为什么不回到你来的地方？滚出去！}
{180}{}{我们在为战争做准备！我们要拯救世界！这样我们就可以用这些和平与统一的废话来填满它。}
{181}{}{战争？第一步在哪儿？}
{182}{}{废话？告诉我你在开玩笑！这一定是真的！[眨眼]}
{183}{}{废话？告诉我你在开玩笑！这一定是真的！[面无表情]}
{184}{}{如果是废话，你为什么在这里？}
{185}{}{只要我有机会杀点东西就行。}
{186}{}{我不知道！唯一见过他的人是墨菲斯，他在他的塔楼上。伙计，你让我毛骨悚然！}
{187}{}{我有时会有这种效果。你继续合作，就没有理由害怕。}
{188}{}{告诉我更多关于墨菲斯的事！}
{189}{}{这个地方还有谁重要？}
{190}{}{你帮了大忙。谢谢你，朋友。}
{191}{}{你得多和人交流。你知道他们把酒藏在哪儿吗？}
{192}{}{真遗憾。我还以为你们这些呆子会有点胆量呢。}
{193}{}{我还以为我疯了呢！你最好赶紧离开这里，不然会被人干掉的！}
{194}{}{请不要杀我！我会告诉你你想知道的。}
{195}{}{这里发生了什么事？}
{196}{}{主人在哪儿？}
{197}{}{这里谁负责？}
{198}{}{谁会想知道这些？我只是喜欢在杀人前闻到他们的恐惧。真是爽！}
{199}{}{我听说我们要往北迁移，或者很快就要计划往北走。他们只告诉我们一些老套的废话。但我们在这儿谈论这些，你一定是疯了！}
{200}{}{[笑] 我宁愿去占别人便宜，而不是被占便宜。但我们不该在这儿公开谈论这些。那些僵尸可不喜欢。}
{201}{}{你知道吗，这里还有很多人和你想的一样。去烦他们吧。}
{202}{}{我什么都不想告诉你，伙计。去死吧。}
{203}{}{那家伙穿着黑衣服，做他的传教表演，然后上楼数他的剧本。天啊，我真希望我也能这么轻松！不过我最好别在背后说他坏话，不然夜行者会听到。}
{204}{}{你怕什么？}
{205}{}{我想知道更多。}
{206}{}{这里的瓶盖都在哪儿？}
{207}{}{他在传什么教？}
{208}{}{来吧！我正好需要点刺激！}
{209}{}{那是拉舍。伙计，离他远点！他完全是……我不知道该怎么形容他。想象一下地球上你最不想认识的人。拉舍比那还糟。}
{210}{}{他和莫菲斯合得来吗？}
{211}{}{他在这计划中扮演什么角色？}
{212}{}{他干了什么？为什么这么坏？}
{213}{}{嘿，你还没见过我呢，伙计！}
{214}{}{以后找别人去烦。}
{215}{}{天啊，我真希望我们有那些东西！听了几个小时的‘赞美这个’和‘和平’，‘统一’，还有那些废话，我也想喝醉！}
{216}{}{你在开玩笑吧。这地方是个教堂！肯定有酒！}
{217}{}{没有酒？见鬼！}
{218}{}{如果我喝不到足够的酒，我就开始喝血。}
{219}{}{那是莫菲斯。我们的领袖。我想他在塔上。}
{220}{}{领袖？他要带你们去哪儿？}
{221}{}{拜托，伙计。这什么都没告诉我。说点内幕消息吧！}
{222}{}{还有谁在这地方重要？}
{223}{}{你帮了大忙。谢谢你，朋友。}
{224}{}{他身上有酒吗？这地方有酒吗？}
{225}{}{嗯，一个不错的私人地方，没人打扰我杀掉他。}
{226}{}{你一定在开玩笑。夜行者是杀手。你看错他们一眼，他们就会割掉你的身体部位，煮熟了，一块一块喂给你。他们是杀不死的。他们是主宰的执行者，会为他撕裂这个世界。我什么都不再说了！}
{227}{}{没什么好说的了，如果你聪明，你也不会想知道！}
{228}{}{我不知道。我自己也找过！我听说莫菲斯有一批，但主要的都由夜行者看守。我认识一些去找秘密通道的人，再也没见过他们。我过了一阵子就不找了，如果你聪明，你也别开始！不值得！}
{229}{}{你一定在开玩笑。去问那些僵尸吧，伙计！}
{230}{}{也许你们本来就该在一起！}
{231}{}{这里没有酒，伙计！生活比拉舍还要糟！现在你为什么不去找别人聊天，小混蛋？滚开！}
{232}{}{别给我废话，老兄。你到底想要什么？}
{233}{}{你注意到这里有什么异常情况吗？}
{234}{}{这里到底发生了什么？}
{235}{}{主宰在哪儿？}
{236}{}{只是找个朋友。}
{237}{}{我只想要点酒。也许来点辐射蝎子汁？}
{238}{}{我想要一个态度恶劣的小子惹我生气到我会割掉他的舌头，把它保存起来，挂在项链上，提醒我人有多愚蠢。}
{239}{}{主宰可以去吻我的屁股。只要我站在胜利的一方，我才不在乎。你明白吗，僵尸！}
{240}{}{终于！我在这地方找到一个真正的人类了！}
{241}{}{我的朋友？为什么你的生活充满了痛苦和折磨？向主宰敞开心扉吧！}
{242}{}{你怎么能用这种态度在这里生存？}
{243}{}{你说得很清楚。}
{244}{}{我在乎。如果有人自称“主宰”并试图吻我的屁股，我会杀了他。}
{245}{}{因为我工作做得好。我上个月杀了三个末日教徒。没人敢惹我。你想试试吗？}
{246}{}{我印象深刻。像你这样的人一定知道这里的真相。}
{247}{}{末日教徒，是吗？他们应该很厉害？}
{248}{}{才三个？就这些？你应该看看我的战绩！}
{249}{}{没有。}
{250}{}{我敢打赌，你的没我这边叫得响。我就喜欢听他们尖叫。}
{251}{}{嘿！拿着武器的人还是拿着武器的人！你觉得你能做得更好吗？}
{252}{}{不，我的朋友。我致力于和平、爱与团结。}
{253}{}{拿着武器的人很危险。拿着武器又有头脑的人才致命。}
{254}{}{拿着武器的人很危险。拿着武器又有头脑的人才致命。}
{255}{}{是的，我能做得更好。}
{256}{}{无法判断。你想试试吗？}
{257}{}{想？谁需要想？我直接让你见识一下。去死吧，混蛋！}
{258}{}{我可没听说过你，伙计，所以别废话，离我远点。}
{259}{}{我就知道。为什么你不回去继续你的僵尸咒语，把真正的工作留给像我这样的人。}
{260}{}{是的。我听说过你。你可能杀过不少辐射蝎子，但我更狠！你有什么企图？你来这里干什么？}
{261}{}{你注意到这里有什么异常情况吗？}
{262}{}{这里发生了什么事？}
{263}{}{主宰在哪里？}
{264}{}{我在找一个朋友。}
{265}{}{我听说这里的酒不错。}
{266}{}{等一下，你不就是那个...哦，见鬼，我走了！}
{267}{}{等一下，你不就是那个...哦，见鬼，我走了！}
{268}{}{我不是任何人的朋友。我不是那种人。[长时间停顿]我建议你现在让开。}
{269}{}{我们在这里动手，夜行者会把我们撕成碎片。也许我们可以稍后在外面见面。}
{270}{}{也许吧。或者我们都收起态度，聊聊别的。比如这里发生了什么。}
{271}{}{懦夫！}
{272}{}{当然。可能会很有趣。}
{273}{}{现在就来吧。}
{274}{}{你这个混蛋！}
{275}{}{因为得罪他的人活不长！}
{276}{}{[完成]}
