{100}{}{你看到一个阿迪顿的居民。}
{101}{}{看起来要下雨了……和往常一样。}
{102}{}{抱歉，我得走了。还有工作要做。}
{103}{}{我们这里不常见到外来者。}
{104}{}{得回去工作了。}
{105}{}{如果我是你，我会回中心城。}
{106}{}{日安……如果这算是个好日子的话。}
{107}{}{嗯……随便吧。}
{108}{}{没时间说话。}
{109}{}{现在不能说话。}
{110}{}{希望今天的雨不像昨天那样发光。}
{111}{}{看样子我们又要缺粮了。}
{112}{}{希望商队能快点再经过这里。}
{113}{}{我们现在有机会成功了。}
{114}{}{阿迪顿会成为我们理想中的城镇。}
{115}{}{谢谢你的帮助。}
{116}{}{感谢你铲除了治安官。}
{117}{}{感谢你为我们带来了自由。}
{118}{}{治安官不在了真是太好了。}
{119}{}{欢迎来到新阿迪顿。}
