{100}{}{你看到一个超级变种人。他正在守卫气闸门。}
{101}{}{你看到一个超级变种人守卫。}
{102}{}{杰里迈亚，你可以通过。}
{103}{}{继续前进。}
{104}{}{快点，信使。}
{105}{}{普通人不能在这里携带武器！停下并表明身份！}
{106}{}{咆哮！}
{107}{}{呃，对不起。我会收起来的。}
{108}{}{我只是路过，不需要身份验证。}
{109}{}{死吧！死吧！死吧！我一直想这么说。}
{110}{}{不许这样跟我说话。你会受到惩罚。}
{111}{}{停下！你来这里有什么事，“孩子”。}
{112}{}{哼！}
{113}{}{我，呃，正在做些事情。}
{114}{}{我有重要的事情要办。你无权阻止和质问我。}
{115}{}{别跟我说话，大块头。}
{116}{}{你的回答不能让我安心。快点清楚地说，否则我会认为你来这里是为了不良目的。我保证你不会喜欢那样……}
{117}{}{呃，不，真的，老实说。我在做事情。}
{118}{}{我在给我们的领袖送信。}
{119}{}{我感受到你话语中的虚假。你不会被允许进入。这是我向你保证的……}
{120}{}{你可以通过，但下次请遵循正确的程序……}
{121}{}{好的，谢谢。回头见。}
{122}{}{那是什么？}
{123}{}{祝福你，兄弟。}
{124}{}{真正的主宰追随者会知道这些。你是个入侵者！}
{125}{}{继续前进。我没时间回答你的问题。}
{126}{}{你在惹恼我。}
{127}{}{我有工作要做。你呢？}
{128}{}{你来这里是个错误。解释清楚，否则就灭亡……}
{129}{}{呐吉！}
{130}{}{我无话可说。}
{131}{}{我来这里是为了保护人类免受你们的侵害。}
{132}{}{哦，闭嘴！}
{133}{}{别装傻来骗我。我厌倦了……}
{134}{}{这是什么愚蠢的偏见，我们是“人类”。我们和你一样是人类。}
{135}{}{这是什么鬼话？}
{136}{}{你绝对不可能是人类。}
{137}{}{我叫凯尔。我和你一样有父母。主宰只是监督了我的重生。这些肌肉，这皮肤，这力量并不让我比你更不人类。我不喜欢统一体的所有主张，但这是我们拥有的最好的和平机会。}
{138}{}{在我看来不是。我来这里是为了终结你和你们的种类。}
{139}{}{你可能是人类，但这并不代表你的统一体是对的。我想我们会成为敌人。}
{140}{}{你这样做真是遗憾，但你不会再进一步……}
{141}{}{看到你的头被插在长矛上真是遗憾。}
{142}{}{入侵者！}
{143}{}{我不跟你说话。}
{200}{}{你获得}
{201}{}{经验值，因为你骗过了守卫。}
