{100}{}{你看到一个追随者的成员。}
{101}{}{你看到追随者的艾伦兄弟。}
{102}{}{嘿，问候你，祝你有个美好的一天，伙计。有什么事吗？}
{103}{}{嗨，我能为你做些什么？}
{104}{}{你好。}
{105}{}{嘿，问候你，祝你有个美好的一天，小姐。有什么事吗？}
{106}{}{哦哦哦！}
{107}{}{嗨。}
{108}{}{我见过一些追随者。你们到底是做什么的？}
{109}{}{我正在试图找出你们中的间谍，但运气不太好。我可以问你几个问题吗？}
{110}{}{哦，我主要研究哲学之类的东西。我的意思是，如果我们要实现和平，那我们需要一个好的基础，对吧？}
{111}{}{这是一个值得追求的目标。}
{112}{}{你唯一需要的哲学就是一把大枪！}
{113}{}{嗯，好吧。我想我以后再找你聊。}
{114}{}{哇哦！嘿，我想我帮不了你。}
{115}{}{嘿，正是这种态度导致了所有这些麻烦。放轻松，好吗？}
{116}{}{呵，我只是开玩笑的。}
{117}{}{让我给你一点和平……永恒的和平。}
{118}{}{呃，当然，请问吧。}
{119}{}{你还想知道什么？}
{120}{}{你和大教堂的孩子们有过接触吗？}
{121}{}{你有离开过图书馆吗？}
{122}{}{你知道有谁经常外出吗？}
{123}{}{绝对没有。我听说他们都是怪胎。我才不想和他们说话。}
{124}{}{没有，我为什么要呢？我只是喜欢读书。而且，只有侦察员才真正能到处走。}
{125}{}{嗯，只有侦察员和守卫。守卫偶尔会出去巡逻。我想当守卫，但……嗯，我在徒手格斗中被打得很惨，所以不能去。嗯，侦察员，他们走得更远，有时我想他们甚至到过大教堂。}
{126}{}{没有更多问题了，谢谢。}
{127}{}{[更多]}
