{100}{}{你看到翡翠。}
{101}{}{你看到贝卡。}
{102}{}{}
{103}{}{}
{104}{}{你看到一个刀锋帮成员。}
{105}{}{你看到一个刀锋帮成员。}
{106}{}{你觉得那可能是书虫。}
{107}{}{你觉得那可能是伤疤。}
{108}{}{你觉得那可能是枪手。}
{109}{}{你觉得那可能是抽搐。}
{110}{}{你觉得那可能是铁锤。}
{111}{}{你觉得那可能是剃刀。}
{112}{}{这些是休息区。现在赶紧离开，否则我就踢你的屁股。}
{113}{}{试试看。}
{114}{}{抱歉。再见。}
{115}{}{我可以在这里休息吗？}
{116}{}{不行。这是给真正的刀锋帮成员的，不是给胆小鬼的。}
{117}{}{嘿，老兄！怎么样？如果需要安全的地方，可以在这里休息。}
