{100}{}{你看到比利。}
{101}{}{你好啊。}
{102}{}{嗨，你在做什么？}
{103}{}{我可以要一头辐射牛吗？}
{104}{}{你好。呃，再见。}
{105}{}{啊！}
{106}{}{再见。}
{107}{}{你为什么想要一头辐射牛？你有商队吗？不过这不重要。我只是负责照看它们，丹才是它们的主人；不过他不会卖的。}
{108}{}{为什么？}
{109}{}{我只是开玩笑。}
{110}{}{因为有很多商队失踪了。他没有多余的辐射牛，商队用掉了大部分。其他的则被卖掉当食物。好吧，我得停止聊天了；丹看到我跟陌生人说话会生气的。}
{111}{}{哦，好的。}
{112}{}{没什么……我是说，我在照看辐射牛。}
{113}{}{矛是用来干什么的？它们很危险吗？}
{114}{}{什么是辐射牛？}
{115}{}{什么是辐射牛？你一定是在开玩笑。它们是这里主要的食物来源和交通工具之一。它们拉商队。丹说这是个非常重要的工作，但这就是骨头。}
{116}{}{哦，我知道了！}
{117}{}{丹说得对。你做得很好。}
{118}{}{是啊，看起来是这样。玩得开心。}
{119}{}{嘿，你是那些流浪汉之一吧？}
{120}{}{真的吗？你这么认为？哇，谢谢。}
{121}{}{你不是本地人吧？给你个建议：别被抓到偷东西！}
{122}{}{当然，谢谢。}
{123}{}{我绝不会偷东西。偷东西是不对的。}
{124}{}{是啊，我想我开始同意你的看法了。其实这工作还不错。出于某种原因，这让我感觉很好。好吧，我得走了，不然会惹麻烦的。}
{125}{}{请不要伤害我或我的辐射牛。}
{126}{}{别伤害我！}
{127}{}{住手！}
{128}{}{请别打扰我。}
{129}{}{你吓到我了。}
{130}{}{嘿，你想干什么？我没有你想要的东西。}
{131}{}{住手！}
{132}{}{危险？不，实际上不太危险。它们可能会给你一口狠的，但它们挺酷的。它们经常放屁和打嗝。我不知道为什么。}
{133}{}{那矛是用来干什么的？}
{134}{}{好的，谢谢。}
{135}{}{哦，它们有时候非常固执，我想让它们做点什么时就这样。我只是轻轻戳它们让它们动起来……而且我不想靠得太近；它们有时会踢人。}
{136}{}{请不要跟我说话。丹又要对我发火了。他真的很生气——我是说——当我不专心工作时。}
{137}{}{他只是想帮忙。努力工作，我相信他会对你更好的。}
{138}{}{来，小子，拿着50块钱，离开这个混蛋。}
{139}{}{好的。}
{140}{}{啊啊啊！}
{141}{}{嗯？}
{142}{}{请不要这样，我已经够麻烦的了。}
{143}{}{我正在努力工作！}
{144}{}{对不起，我不是那个意思。他只是想帮你。}
{145}{}{不，你没有，你这个懒惰的小家伙！}
{146}{}{好的。}
{147}{}{是啊，也许你是对的……其实，他看起来挺酷的，但我希望他不要总是对我大喊大叫。}
{148}{}{是啊，对。}
{149}{}{去你的，老家伙！}
{150}{}{去你的，老巫婆！}
{151}{}{哇！我可以靠这个过一辈子！非常感谢，先生！}
{152}{}{哇！我可以靠这个过一辈子！非常感谢，女士！}
{153}{}{哇！谢谢……嗯？……你只是想让我再次惹麻烦！}
{154}{}{请不要跟我说话，丹真的很生气。}
{155}{}{别担心。我跟他谈过了，他会对你更好的。}
{156}{}{他应该这样！你是个糟糕的孩子！}
{157}{}{哇。}
{158}{}{嗨！}
{159}{}{那边的女孩们真笨。}
{160}{}{又见面了。}
{161}{}{辐射牛真酷。}
{162}{}{如果我做得好，丹会带我去猎鹰酒吧。}
{163}{}{丹有一天会带我去商队！}
{164}{}{我长大后要成为一个冒险家。}
{165}{}{真的吗？哦，好的。我希望你没有伤害他。他其实没那么坏。他只是喊得多。}
{166}{}{又见面了。}
{167}{}{你是做什么的来着？}
{168}{}{我可以要一头辐射牛吗？}
{169}{}{只是过来看看情况。再见。}
{170}{}{啊！}
{171}{}{再见。}
{172}{}{我最好回去工作了。}
{173}{}{那边的女孩们真笨。}
{174}{}{又见面了。}
{175}{}{我长大后要成为一个冒险家。}
{176}{}{辐射牛真是……呃，拉很多便便。}
{177}{}{我现在不能说话。}
{178}{}{我不想惹麻烦。}
