{100}{}{你看到鲍勃。}
{101}{}{绝对不可能让你抢劫我！}
{102}{}{嘿，我不想惹麻烦！}
{103}{}{给我来一串蜥蜴肉。}
{104}{}{你能告诉我关于水芯片的事吗？}
{105}{}{你能告诉我关于德克的事吗？}
{106}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{107}{}{你知道关于失踪的商队的事吗？}
{108}{}{什么，我惹麻烦？你为什么这么想？}
{109}{}{我饿了！咕噜！}
{110}{}{你好，欢迎来到鲍勃的蜥蜴小吃店，家庭餐饮场所。我可以为你点餐吗？}
{111}{}{给我来一串蜥蜴肉。}
{112}{}{你能告诉我关于水芯片的事吗？}
{113}{}{你能告诉我关于德克的事吗？}
{114}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{115}{}{你知道关于失踪的商队的事吗？}
{116}{}{集市上有什么有趣的事情发生吗？}
{117}{}{我饿了！咕噜！}
{118}{}{抱歉，我们的蜥蜴肉卖完了。}
{119}{}{我们只有整串蜥蜴肉，每串二十块钱。}
{120}{}{我们只有精选优质肉，不过味道很好。每份八块钱。}
{121}{}{当然，我们有整串蜥蜴肉二十块钱，还有精选优质肉每份八块钱。}
{122}{}{我要一整串蜥蜴肉。}
{123}{}{我要你的精选优质肉。}
{124}{}{你知道吗，我听说你的精选肉尝起来像鸡肉。}
{125}{}{不要小份的！我要整串蜥蜴肉！呃！}
{126}{}{嗯，闻起来不错！精选肉让肚子很满足！}
{127}{}{我们这里不供应那个。还有别的吗？}
{128}{}{给我来一串蜥蜴肉。}
{129}{}{你能告诉我关于德克的事吗？}
{130}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{131}{}{你知道关于失踪的商队的事吗？}
{132}{}{集市上有什么有趣的事情发生吗？}
{133}{}{我饿了！咕噜！}
{134}{}{德克先生是个在不太体面的生意中很有声望的商人。还有别的吗？}
{135}{}{我想了解莫比德医生的信息。}
{136}{}{给我来一串蜥蜴肉。}
{137}{}{没什么。}
{138}{}{他是个狠角色，任何不为他死去而高兴的人都是个该死的骗子。我可以为你点餐吗？}
{139}{}{给我来一串蜥蜴肉。}
{140}{}{告诉我一些关于水商的事情。}
{141}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{142}{}{你知道关于失踪的商队的事吗？}
{143}{}{集市上有什么有趣的事情发生吗？}
{144}{}{我饿了！咕噜！}
{145}{}{我不知道你在说什么。好吧，我给你一百块钱，如果你闭嘴。拿着钱滚出去。}
{146}{}{我要两百。}
{147}{}{我拿一百。}
{148}{}{我要去找警察。}
{149}{}{现在就停止销售。}
{150}{}{真是可怕的事情。那些可怜的人们啊。失去生命是多么可怕的事情！还有什么我能为你做的吗？比如给你吃的？}
{151}{}{给我来一串蜥蜴肉。}
{152}{}{你能告诉我关于水芯片的事吗？}
{153}{}{你能告诉我关于德克的事吗？}
{154}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{155}{}{集市上有什么有趣的事情发生吗？}
{156}{}{没什么。抱歉提起这个。我只是听说了一些故事。还有什么我能为你做的吗？}
{157}{}{给我来一串蜥蜴肉。}
{158}{}{你能告诉我关于水芯片的事吗？}
{159}{}{你能告诉我关于德克的事吗？}
{160}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{161}{}{你知道关于失踪的商队的事吗？}
{162}{}{集市上有什么有趣的事情发生吗？}
{163}{}{有人杀了德克。我们正在哀悼，至少在集市的酒喝完之前。}
{164}{}{有人射杀了格林警长。不知道副警长怎么样了。}
{165}{}{达伦·海塔沃被谋杀了。所有的钱都救不了他。讽刺，不是吗？}
{166}{}{有人真的惹恼了某个重要人物，因为我听说有个大悬赏在某个可怜的家伙头上。}
{167}{}{有人从海塔沃家偷了条项链。天啊，他们真是犯了大错。他们死定了。}
{168}{}{有人在大教堂杀了简。我听说她是个真正的泼妇！}
{169}{}{嗯，唯一的新鲜事是大教堂的孩子们接管了医院。最近这里相当无聊。说真的，他们是一群奇怪的人。}
{170}{}{还有别的吗？}
{171}{}{给我来一串蜥蜴肉。}
{172}{}{你能告诉我关于水芯片的事吗？}
{173}{}{你能告诉我关于德克的事吗？}
{174}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{175}{}{你知道关于失踪的商队的事吗？}
{176}{}{抱歉，你付不起。}
{177}{}{一整串蜥蜴肉，马上来！还有别的吗？}
{178}{}{再给我来一串蜥蜴肉。}
{179}{}{你能告诉我关于水芯片的事吗？}
{180}{}{你能告诉我关于德克的事吗？}
{181}{}{你知道关于失踪的商队的事吗？}
{182}{}{集市上有什么有趣的事情发生吗？}
{183}{}{我还要一串蜥蜴肉！}
{184}{}{我吃饱了！嗝！}
{185}{}{抱歉，你付不起。}
{186}{}{一份精选优质肉，马上来！还有别的吗？}
{187}{}{再给我来一串蜥蜴肉。}
{188}{}{你能告诉我关于水芯片的事吗？}
{189}{}{你能告诉我关于德克的事吗？}
{190}{}{你知道关于失踪的商队的事吗？}
{191}{}{集市上有什么有趣的事情发生吗？}
{192}{}{我还要一串蜥蜴肉！}
{193}{}{我吃饱了！嗝！}
{194}{}{谢谢，欢迎再来！}
{195}{}{如果你问我关于水商的事，那你一定是新来的。水就是生命。而掌握生死的人最有权力。}
{196}{}{给我来一串蜥蜴肉。}
{197}{}{我想我们需要谈谈莫比德医生和你的一些秘密配料。}
{198}{}{你知道关于失踪的商队的事吗？}
{199}{}{集市上有什么有趣的事情发生吗？}
{200}{}{我饿了！咕噜！}
{201}{}{你这个贪婪的混蛋！}
{202}{}{你这个贪婪的婊子！}
{203}{}{好吧，你赢了。给你钱。拿着钱别再回来！}
{204}{}{如果我是你，我会改变主意的，朋友。在集市里，很多人因为更少的事情而丧命。现在滚出去别再回来！}
{205}{}{也许我用了些有问题的材料。但这又不是我在杀人。莫比德的东西本来就是死的，不是吗？}
{206}{}{我相信是这样的，鲍勃。我相信警察也会同意。}
{207}{}{食人是对人类的犯罪，鲍勃。我会让你为此付出代价。}
{208}{}{也许是，也许不是。我不在乎。这是不道德的。停止它。}
{209}{}{不可能！我不会让你坑我的！吃这个！}
{210}{}{我不会因为你的良心破产，但你会因为它而死！吃这个！}
