{100}{}{你看到一个严肃的年轻见习生，手里拿着一本书。}
{101}{}{你看到见习生布伦登。}
{102}{}{您好，我能为您提供什么帮助？}
{103}{}{我在找书记官大师弗瑞。}
{104}{}{我在找将军马克森。}
{105}{}{我在找骑士长隆布斯。}
{106}{}{你在读什么？}
{107}{}{呃。}
{108}{}{嗯，看起来我帮不上忙。}
{109}{}{书记官大师弗瑞在三层的计算机实验室。}
{110}{}{将军马克森通常在四层的议会厅。}
{111}{}{骑士长隆布斯大部分时间在一层的物资室。}
{112}{}{还有什么我可以帮您的吗？}
{113}{}{谢谢，祝您愉快。}
{114}{}{实际上，这是我在写的一本日志。我正在撰写一篇关于兄弟会社会动态的论文。}
{115}{}{嗯，听起来很有趣。}
{116}{}{所以，重点是什么？}
{117}{}{确实如此。我一直在研究关于我们战前前辈的信息以及外部世界的社会。我认为兄弟会的组织结构最接近于所谓“黑暗时代”的圣殿骑士团。}
{118}{}{你为什么决定研究这个？}
{119}{}{圣殿骑士团？}
{120}{}{虽然兄弟会非常重视硬科学和应用技术，但在心理学和社会学等软科学方面的研究却很少。为了获得全面的教育，我们必须将科学思维应用于所有领域。}
{121}{}{那么你发现了什么？}
{122}{}{我得出的结论是，兄弟会主要像一个伪宗教组织。我们有强大的军事等级制度，结合了从祖先传下来的荣誉准则。结合我们的技术技能，我认为兄弟会有两条发展路径：一个科技宗教独裁或一个仁慈的研究社会。}
{123}{}{什么会影响兄弟会的发展？}
{124}{}{最终，我们有一个指挥层级，长老们在最高层。最有影响力的职位是长老和大长老。一个有魅力的大长老几乎可以完全引导兄弟会。我们需要小心，确保我们有一个既强大又有远见的领袖。幸运的是，我认为将军马克森符合这个描述。}
{125}{}{根据我的研究，圣殿骑士团是一个专注于财富和知识获取的军事兄弟会。虽然他们的结构中有一些宗教色彩，但他们对知识的追求最终使他们成为一个世俗组织。我认为如果他们对财富和权力更感兴趣，他们会成为一个更神权的组织，因为那个时代的教会主要涉及对黄金和土地的控制。}
{126}{}{这与兄弟会有什么关系？}
{127}{}{我们必须了解过去，才能认清未来的方向……不过我相信你不会理解这一点。}
