{100}{}{你看到一个神情专注的年轻人。}
{101}{}{你看到迈克尔。}
{102}{}{你好，我想我之前没见过你。有什么需要我帮忙的吗？}
{103}{}{又见面了，我能为你做些什么？}
{104}{}{你能告诉我一些关于骨园的事吗？}
{105}{}{你是谁？}
{106}{}{你们为什么住在这里？}
{107}{}{没什么，谢谢。}
{108}{}{当然。南边是阿迪特姆，东北方向是枪手，不过你得穿过死亡爪才能到达他们那里。西边是启示录追随者，而在更南边我听说有个教堂。}
{109}{}{我是迈克尔。我和我的妻子克里斯汀住在这里，作为刀锋帮成员尽力帮助大家。}
{110}{}{情况没那么糟。治安官和死亡爪会制造麻烦，但我们的领袖剃刀在过去几个月里帮了我们很多。最近，麦克雷还教我们如何更好地保护自己。}
{111}{}{感谢你帮我们清除阿迪特姆的治安官。这是我们能提供的物资，希望能帮助你继续旅程。}
{112}{}{这没什么。谢谢你的补给。}
{113}{}{不客气，请把这些补给留给自己。}
{114}{}{我坚持。}
{115}{}{[迈克尔递给你一些刺激药和瓶盖]}
{116}{}{又见面了。祝你旅途顺利。}
