{100}{}{我是凯莱布，监管者的领袖。}
{101}{}{你看到一个三十多岁的严肃男人。}
{102}{}{你应该知道我们这里不喜欢陌生人。你想要什么？}
{103}{}{你好，我能帮你什么忙？}
{104}{}{我是}
{105}{}{你看起来像个重要人物。}
{106}{}{你能告诉我一些关于阿迪顿的事情吗？}
{107}{}{你能告诉我这里骨园发生了什么吗？}
{108}{}{监管者的历史是什么？}
{109}{}{告诉我更多关于圣堂儿童和启示录追随者的事。}
{110}{}{我在哪里可以找到齐默尔曼？}
{111}{}{祝你有美好的一天。谢谢。}
{112}{}{这是个不错的小镇。我和监管者们努力保持它的样子。你想了解谁？}
{113}{}{谁管理阿迪顿？}
{114}{}{这里谁做交易？}
{115}{}{没有其他事了，谢谢。}
{116}{}{别惹麻烦，明白吗？我是凯莱布，这个名字你要记住，因为如果你搞砸了，我会来找你。}
{117}{}{我是凯莱布。我负责训练和组织这里的监管者。}
{118}{}{是的，我想是吧。你往北走会看到刀锋帮，一群可怜的人，还有往北再往东一点穿过死亡爪游乐场就是枪械商。}
{119}{}{另外，往南走有圣堂儿童，他们经营一家医院和一座大教堂。往北再往东一点是启示录追随者，他们都是和平主义者。}
{120}{}{别惹麻烦。}
{121}{}{你也有个好日子。}
{122}{}{你又回来了？}
{123}{}{我能帮你什么，孩子？}
{124}{}{我能为你做些什么，小姐？}
{125}{}{你最好在镇上把武器收好。}
{126}{}{咕嘎咕。}
{127}{}{抱歉，我没时间理你。快走吧。}
{128}{}{阿迪顿由乔恩·齐默尔曼管理。他是个正直的人，把镇子照顾得很好。你应该去见见他。还有别的事吗？}
{129}{}{泰恩在大门附近开了一家店，就在小地堡下面。他负责与枢纽城和像你这样的外来者交易。还有别的事吗？}
{130}{}{我们是阿迪顿的警察。这里的大多数人都知道不要惹麻烦。}
{131}{}{我负责训练监管者，确保流浪者努力工作，并且没有人侵占我们的地盘。还有别的事吗？}
{132}{}{圣堂儿童都住在一个大黑色教堂式的建筑里。他们有某种大神，并且到处试图让人们加入他们的教派。}
{133}{}{你会在西南的大建筑里找到他。他可能能凑够几个句子告诉你我们正在找人帮忙对付刀锋帮。}
{134}{}{刀锋帮发生了什么事？}
{135}{}{我能再问你点别的事吗？}
{136}{}{谢谢你的信息。再见。}
{137}{}{当然。你还想知道什么？}
{138}{}{他们对齐默尔曼的傻儿子做了些什么。但就像我说的，去找齐默尔曼谈谈。}
{139}{}{我能再问你点别的事吗？}
{140}{}{好吧，我明白了。我会去找齐默尔曼谈谈。}
{141}{}{所以，齐默尔曼告诉你关于刀锋帮的事了。不管怎样，我相信他会想知道你完成任务后的情况。}
{142}{}{刀锋帮在哪里？}
{143}{}{你们为什么不自己解决这个问题？}
{144}{}{好吧，等我完成任务后再回来。}
{145}{}{他们都在这里的北边。你不会错过他们的臭味。还有别的事吗？}
{146}{}{因为这对我们来说是浪费时间。我有更重要的事情要做，而不是出去杀几个流浪者。洗澡花的时间比处理他们还多。还有别的事吗？}
{147}{}{所以你回来了。去找齐默尔曼谈谈吧。}
