{100}{}{你看到一个商队顾客。}
{101}{}{他们从来没有我想要的东西。}
{102}{}{我觉得他们的商品越来越差了。}
{103}{}{抱歉，我不应该和外人说话。}
{104}{}{我总是找不到我想要的东西。}
{105}{}{如果你看到任何雷达莱克的东西，告诉我一声。}
{106}{}{这些价格真是越来越离谱了。}
{107}{}{我很高兴那些水商不再来这里了。}
{108}{}{如果你有问题，可以去找卡博特或达雷尔。}
{109}{}{卡博特是我们的接待员。你应该去找他或达雷尔。}
{110}{}{我更喜欢红色商队的商品。}
{111}{}{远行贸易公司的那帮人真是和气。}
{112}{}{红色商队对我来说太粗俗了。}
