{100}{}{你看到了一位商队领队。}
{101}{}{好了，我们到了。这是你的报酬}
{102}{}{瓶盖。[他拿出一个旧的折角钱袋，把钱给了你。] 如果你和我们一起回到枢纽，还能再拿到}
{103}{}{瓶盖。我们会在这里休息一会儿，但别走太远，否则商队会丢下你。}
{104}{}{啊... 好吧。}
{105}{}{商队什么时候出发？}
{106}{}{你能告诉我关于废城的情况吗？}
{107}{}{你能告诉我关于尸坑的情况吗？}
{108}{}{你能告诉我关于钢铁兄弟会的情况吗？}
{109}{}{我不知道你能不能理解，但我们会在两小时后或你准备好时出发。}
{110}{}{嗯...}
{111}{}{嗯？}
{112}{}{走。好。}
{113}{}{天啊，我们最近雇的人真笨。}
{114}{}{我们通常在到达两小时后离开。不过这里没什么新鲜的，所以如果你想早点走，我们随时可以出发。}
{115}{}{我想在离开前四处看看。待会见。}
{116}{}{好吧。我们回枢纽吧。我在这儿也没什么想看的。}
{117}{}{你能告诉我关于废城的情况吗？}
{118}{}{你能告诉我关于尸坑的情况吗？}
{119}{}{你能告诉我关于钢铁兄弟会的情况吗？}
{120}{}{嗯，实际上和枢纽差不多。这里也有它的问题：帮派、暴徒、小偷，你知道的...常见的问题。总的来说，我喜欢这个地方。[笑]}
{121}{}{商队什么时候出发？}
{122}{}{我想在离开前四处看看。待会见。}
{123}{}{尸坑的这一部分叫做阿迪特姆。尸坑基本上由帮派控制。这里比较混乱，所以走路小心点。阿迪特姆由监管者掌控。他们在努力维持这个地方，面对所有的帮派战争。他们对陌生人持怀疑态度，所以如果你还没和他们说过话，我建议你先去打个招呼再四处走动。}
{124}{}{空}
{125}{}{商队什么时候出发？}
{126}{}{我想在离开前四处看看。待会见。}
{127}{}{关于他们我没什么好说的。兄弟会大多保持低调。很多人对他们评价不高，但据我所知，他们是好人。也许有点狂热，但都是好人。}
{128}{}{商队什么时候出发？}
{129}{}{我想在离开前四处看看。待会见。}
{130}{}{你准备好出发了吗？}
{131}{}{走！}
{132}{}{没有。我还在四处看看。}
{133}{}{是的。我们可以走了。}
{134}{}{尸坑的这一部分叫做阿迪特姆。尸坑基本上由帮派控制。这里比较混乱，所以走路小心点。}
{135}{}{商队什么时候出发？}
{136}{}{我想在离开前四处看看。待会见。}
{137}{}{好吧。你做到了。这是你的}
{138}{}{瓶盖。如果你想要更多工作，就去找老板谈。我很乐意再和你合作。我会在老板面前为你美言几句。保重。}
{139}{}{再见。}
{140}{}{再见。}
{141}{}{嘿，最近怎么样？}
{142}{}{如果你想要更多工作，去找老板。}
{143}{}{你有什么问题吗？}
{144}{}{你真是个疯子！}
{145}{}{我不跟你合作！}
{146}{}{200}
{147}{}{400}
{148}{}{600}
{149}{}{你能告诉我关于死城的情况吗？}
{150}{}{那地方真是个可怕的地方，伙计！}
{151}{}{商队已经离开。}


{200}{}{哼...}
{201}{}{嗯... 我希望我能读懂。}


{300}{}{管好你自己的事，好吗？}

{400}{}{我不是来聊天的。}
