{100}{}{你面前站着一个夜行者。}
{101}{}{去死吧！}
{102}{}{离开我，否则死！}
{103}{}{我不喜欢你的语气。如果我的信息无法传达给主宰，我会让你的死变得缓慢而痛苦。}
{104}{}{我只是想赞美一下你背上的那个漂亮的驼峰。不过你的口气需要改善一下……}
{105}{}{能告诉我负责人在哪里吗？}
{106}{}{兄弟，你比我更需要喝一杯！}
{107}{}{我不走！}
{108}{}{好吧。我走。}
{109}{}{和夜行者玩游戏是不明智的。快滚出去！}
{110}{}{我不这么认为。}
{111}{}{我会很享受看你死去的过程！}
{112}{}{你没听到吗？忽视夜行者是不明智的。}
{113}{}{我必须和你谈谈。这很紧急！}
{114}{}{从来没人说过我聪明！}
{115}{}{我只是想和负责人说话！}
{116}{}{你以为自己很厉害吗？}
{117}{}{对不起！祝你有个好日子。}
{118}{}{你想看看什么是不明智吗？对我无礼就是不明智，混蛋！}
{119}{}{上楼去吧。我的同类会评估你的信息价值。}
{120}{}{这是你最后的警告！}
{121}{}{当然是！大不了……}
{122}{}{我真的需要和负责人谈谈！}
{123}{}{好吧！好吧！对不起！祝你有个好日子。}
{124}{}{你知道你的错误是什么吗？你会给警告，而我不会。去死吧！}
{125}{}{[完成]}
