{100}{}{你看到一个态度很差的孩子。}
{101}{}{滚开，混蛋！}
{102}{}{离我远点！}
{103}{}{你到底想干嘛？}
{104}{}{我在哪里可以见到那个主人？}
{105}{}{想知道这里发生了什么。}
{106}{}{这里谁负责？}
{107}{}{嘿，冷静点！来喝一杯吧！}
{108}{}{把你的耳朵加入我的收藏。}
{109}{}{我不想去地狱！蠢货！}
{110}{}{在地狱见，废物。}
{111}{}{你总是问这种蠢问题吗，废物？}
{112}{}{当然不是你，小混混。}
{113}{}{你凭什么觉得我想跟你喝酒，呕吐物！}
{114}{}{滚开，不然我宰了你！}
{115}{}{[完成]}
