{100}{}{你看到辛迪。}
{101}{}{她在哭泣。}
{102}{}{你好，}
{103}{}{。你找到水芯片了吗？}
{104}{}{还没有。我运气不太好。}
{105}{}{还没找到，但我相信一定能找到。顺便问一下，你还好吗？}
{106}{}{乌鲁！}
{107}{}{哦……你听不懂我说的话。我想我们真的没有多少希望了。请原谅我，我要哭一会儿。}
{108}{}{呃！}
{109}{}{请在我们渴死之前找到它。}
{110}{}{你一定要找到它！别让我们这样死去！}
{111}{}{继续努力。我相信你。我知道你会尽一切努力来拯救我们。}
{112}{}{你觉得可能是谁干的？}
{113}{}{我很害怕发生的事情。有人在偷水，现在每个人都很紧张。}
{114}{}{谁会做这种事？}
{115}{}{发生了什么事？}
{116}{}{有些人被指控，甚至为此打了起来，但没有人真的知道真相。}
{117}{}{好的，谢谢。}
{118}{}{有人报告说他们的水被偷了。他们没有得到更多的水，但一些朋友分享了他们的水。之后，大家都变得非常多疑，开始守护自己的水。几天后，有人在配给区打晕了守卫，偷走了水。}
{119}{}{太糟糕了！我能做些什么？}
{120}{}{也许你可以阻止这个人。}
{121}{}{我会四处看看。}
{122}{}{你是偷水贼？！你怎么能这样？}
{123}{}{非常感谢你拯救了我们所有人。}
{124}{}{你抓住了小偷，干得好。请尽快找到水芯片。}
{125}{}{你怎么能背叛我们？现在这里的每个人都会死！但你不在乎，是吗？}
{126}{}{我很害怕。我不知道我们会怎么样。请不要让我们失望。}
{127}{}{别担心，我会尽力的。你们会没事的。}
{128}{}{好吧，随便你。}
