{100}{}{你看到克里奥。}
{101}{}{不退缩，不投降，伙计。}
{102}{}{不退缩，不投降，女士。}
{103}{}{你不是正要离开吗？快走吧。}
{104}{}{你想要什么？}
{105}{}{告诉我关于洛克斯利的事。}
{106}{}{告诉我关于茉莉的事。}
{107}{}{告诉我关于圆环的事。}
{108}{}{告诉我关于德克的事。}
{109}{}{告诉我关于失踪商队的事。}
{110}{}{嗨。}
{111}{}{呃，唉！}
{112}{}{嘿！发生什么事了？}
{113}{}{告诉我关于洛克斯利的事。}
{114}{}{告诉我关于茉莉的事。}
{115}{}{告诉我关于圆环的事。}
{116}{}{告诉我关于德克的事。}
{117}{}{告诉我关于失踪商队的事。}
{118}{}{告诉我关于失踪商队的事。}
{119}{}{嗨。}
{120}{}{呃，唉！}
{121}{}{他是老板。还有什么好知道的？}
{122}{}{告诉我关于茉莉的事。}
{123}{}{告诉我关于圆环的事。}
{124}{}{告诉我关于德克的事。}
{125}{}{告诉我关于失踪商队的事。}
{126}{}{嗨。}
{127}{}{呃，唉！}
{128}{}{她是老板的助手。不是个坏姑娘。}
{129}{}{告诉我关于洛克斯利的事。}
{130}{}{告诉我关于茉莉的事。}
{131}{}{告诉我关于圆环的事。}
{132}{}{告诉我关于德克的事。}
{133}{}{告诉我关于失踪商队的事。}
{134}{}{嗨。}
{135}{}{呃，唉！}
{136}{}{如果你幸运的话，到今天结束时你会觉得自己是我们的一员。就像在家里，成为家具的一部分，你懂的？}
{137}{}{告诉我关于洛克斯利的事。}
{138}{}{告诉我关于茉莉的事。}
{139}{}{告诉我关于德克的事。}
{140}{}{告诉我关于失踪商队的事。}
{141}{}{嗨。}
{142}{}{呃，唉！}
{143}{}{我们在礼貌的场合不讨论德克先生。}
{144}{}{告诉我关于洛克斯利的事。}
{145}{}{告诉我关于茉莉的事。}
{146}{}{告诉我关于圆环的事。}
{147}{}{告诉我关于失踪商队的事。}
{148}{}{嗨。}
{149}{}{呃，唉！}
{150}{}{我们和那件事无关！}
{151}{}{告诉我关于洛克斯利的事。}
{152}{}{告诉我关于茉莉的事。}
{153}{}{告诉我关于圆环的事。}
{154}{}{告诉我关于德克的事。}
{155}{}{嗨。}
{156}{}{呃，唉！}
{157}{}{你好。}
{158}{}{你为什么还要和人说话，白痴？}
{159}{}{一个伟大的领袖。他正在努力搞垮该搞垮的人，并维持集散地的稳定——当然，要收取一点小费。}
{160}{}{告诉我关于茉莉的事。}
{161}{}{告诉我关于圆环的事。}
{162}{}{告诉我关于德克的事。}
{163}{}{告诉我关于失踪商队的事。}
{164}{}{告诉我关于失踪商队的事。}
{165}{}{嗨。}
{166}{}{呃，唉！}
{167}{}{这既是一份工作也是一场冒险。帮助穷人，冒着生命危险，结识新朋友。我们就是这样，好人！}
{168}{}{告诉我关于洛克斯利的事。}
{169}{}{告诉我关于茉莉的事。}
{170}{}{告诉我关于德克的事。}
{171}{}{告诉我关于失踪商队的事。}
{172}{}{告诉我关于失踪商队的事。}
{173}{}{嗨。}
{174}{}{呃，唉！}
{175}{}{我有个朋友曾为他工作过。当任务失败时，他跑回去找德克寻求增援。德克叫他傻瓜，并把他当作例子给其他人看，给他做了脑叶切除术。我们这里不太喜欢德克。}
{176}{}{你想听什么传闻？水商在玩游戏。德克在勒索商人以获取更多保护。大教堂的孩子们把它献祭给他们的神。死亡爪吃掉了它。传闻一文不值。世界充满了传闻和怀疑，却没有真相。寻找事实，而不是虚构。但你为什么问？你在商队上有朋友吗？}
{177}{}{我不能谈论我的理由。}
{178}{}{我答应朋友要调查这件事。}
{179}{}{我的城镇需要水，不能让商队消失。}
{180}{}{是的，我有个朋友。}
{181}{}{好吧。我也有秘密。祝你好运，朋友。}
{182}{}{抱歉我帮不上更多忙。哦，还有关于外星飞船的传闻。我想有人玩了太多鲁弗斯的愚蠢游戏。}
{183}{}{真的吗？你从哪里来？}
{184}{}{阴影沙地。}
{185}{}{阴影沙地北边的一个地方。}
{186}{}{13号避难所。}
{187}{}{到处走走。我为那些让我留下来的地方做些零工。}
{188}{}{很遗憾听到这个。我也失去过几个好朋友，其中一个比死还惨，但我不想多谈。}
{189}{}{我们不是已经讨论过了吗？你真是个一根筋的家伙。}
{190}{}{如果你喜欢沙子，那还不错。对我来说有点太干燥和荒凉了。至少在集散地你不用担心游荡的辐射蝎子。我想我们有足够的掠食者。}
{191}{}{你来自避难所？别开玩笑了！别拿这些胡话来糊弄我。}
{192}{}{我不羡慕你。当然，如果你成名了，你可以成为那些荒野战斗传奇人物之一，比如马格南·汤姆·戈达德或蝎子乔·科尼利厄斯。那一定很棒！}
