{100}{}{你看到丹。}
{101}{}{救命！}
{102}{}{嘿，朋友，欢迎来到中心城。让我自我介绍一下，他们叫我“丹，养牛达人！”我在这里和所有商人打交道，以低廉的价格提供我的服务。那么，我能为你做些什么呢。}
{103}{}{年轻人？}
{104}{}{兄弟？}
{105}{}{小姑娘？}
{106}{}{我想加入商队。}
{107}{}{呃，你到底提供什么服务？}
{108}{}{你为什么要对那个可怜的孩子大喊大叫？！}
{109}{}{呃。}
{110}{}{我负责照顾这片地区几乎所有商队的货车和辐射牛。如果他们的商队需要什么东西，都会来找我。嘿，三大商会都只和我打交道。}
{111}{}{三大商会是谁？}
{112}{}{你还真重要。}
{113}{}{真的吗？不错。我想加入商队。}
{114}{}{好吧，我得走了。再见。}
{115}{}{什么？滚开，混蛋！居然浪费我的时间在你这种低贱的人身上。}
{118}{}{天啊，伙计。你是不是一辈子都被关在洞里？三大商会是世界上最大的三个商人团体。好吧，也许不是整个世界，但他们确实覆盖了很大一部分地区，几乎你能看到的地方都有。}
{119}{}{天啊，姑娘。你是不是一辈子都被关在洞里？三大商会是世界上最大的三个商人团体。好吧，也许不是整个世界，但他们确实覆盖了很大一部分地区，几乎你能看到的地方都有。}
{120}{}{去你的，养牛怪物。}
{121}{}{哦，是他们啊。我还以为你在说别的呢。那么我怎么才能加入商队呢？}
{122}{}{好的，谢谢。再见。}
{123}{}{养牛怪物？这是在侮辱我吗？我建议你对遇到的人礼貌一点，陌生人。我无所谓，但这座城市里有各种各样的杀人不眨眼的家伙，如果你看错了他们，他们会毫不犹豫地割断你的喉咙。}
{124}{}{天啊，你真是个丑陋的混蛋！}
{125}{}{我害怕了。再见。}
{126}{}{特别没有，幸运有；除非你想倒霉，否则你最好对遇到的人礼貌一点。我无所谓，但这座城市里有各种各样的杀人不眨眼的家伙，如果你看错了他们，他们会毫不犹豫地割断你的喉咙。}
{127}{}{天啊，你真是个丑陋的混蛋！}
{128}{}{如果你这么说。}
{129}{}{至少我脸上没有变异的屁股。你妈一定是辐射牛，你爸是老鼠；这就是你怎么能长得这么丑的原因。嘿，你比我还丑！}
{130}{}{没人能这么说我妈！准备去死吧！}
{131}{}{嗯，还不错。我有地方要去，有人要揍。再见，丹。}
{132}{}{是啊，挺不错的台词，但大家都用。你开玩笑吧？你不会对可怜的老丹动手吧。}
{133}{}{台词？动手？你想得美。我会对你即将死去的尸体做更多的事。}
{134}{}{哈哈！不过我让你上当了，不是吗？}
{135}{}{是啊，也许有一点。你还不错，孩子。但记住要管好你的嘴。我不想看到一个好嘴白白浪费掉。}
{136}{}{当然，随你说。再见，丹。}
{137}{}{那么，我怎么才能加入商队呢？}
{138}{}{再见。离我的辐射牛远点，你这个肮脏的小混蛋。}
{139}{}{再见。离我的辐射牛远点，你这个肮脏的小婊子。}
{141}{}{警卫！警察！有个疯子想杀我！}
{142}{}{嗯，我这里没有空缺，但你可以去三大商会看看。在商人市场有个招聘公告可能对你有帮助。那里是他们和其他人招人的地方。}
{143}{}{哦，抱歉……当然还有女性。}
{144}{}{你没有空缺？你也是商人吗？}
{145}{}{商人市场怎么走？}
{146}{}{好的，谢谢。}
{147}{}{嗯，不完全是。我和大多数小商人团体关系密切，不过我知道我们没有在招聘。}
{148}{}{是你的损失。}
{149}{}{好的，回头见，丹。}
{150}{}{那么商人市场在哪儿？}
{151}{}{沿着这条路直走。就在中心城的正中央——你不会错过的。}
{152}{}{这不关你的事，陌生人。}
{153}{}{我会让它成为我的事，“陌生人”！}
{154}{}{抱歉打扰。}
{155}{}{哦，又见面了！你过得怎么样？}
{156}{}{我想加入商队。}
{157}{}{呃，你到底提供什么服务？}
{158}{}{你为什么要对那个可怜的孩子大喊大叫？！}
{159}{}{好吧。再见。}
{160}{}{呃。}
{161}{}{现在怎么了？}
{162}{}{你为什么要对那个可怜的孩子大喊大叫？！}
{163}{}{没什么。}
{164}{}{呃。}
{168}{}{看，那孩子偷东西被抓了。警察把他交给我来管教。}
{169}{}{这不是对他那么刻薄的理由。}
{170}{}{偷东西有什么不对？}
{171}{}{哦，那不一样！给他点颜色看看！}
{172}{}{你傻了吗？这是个快速腐烂在牢房里或被流放没有食物、衣服或武器的办法。}
{173}{}{这仍然不能证明你对待他的方式是对的！}
{174}{}{哦，好吧。}
{175}{}{我可能不是这该死城市里最好的榜样，但我是唯一一个关心并愿意尝试帮助的人。你为改善社会做了什么？}
{176}{}{我杀了很多东西！}
{177}{}{对不起，我误解你了。}
{178}{}{你应该直接杀了那个小子！}
{179}{}{嗯，也许你可以对他稍微好一点。我觉得他在努力。}
{180}{}{你应该好好教训他一顿！}
{181}{}{你以为杀人能解决真正的问题吗？}
{182}{}{是的！}
{183}{}{到目前为止对我来说一直有效！}
{184}{}{嗯，也许不是。}
{185}{}{我不知道。}
{186}{}{你让我失望了。你看起来挺聪明的。杀了他们可能暂时解决问题，但你得找到问题的根源才能真正有所改变。}
{187}{}{好吧，随便。}
{188}{}{呃，好吧。再见。}
{189}{}{你是个白痴。}
{190}{}{嗯（他停下来望向远方）……也许你是对的，伙计。我会记住这一点，但我不保证什么。}
{191}{}{你开玩笑吗？那只会让他更反抗！我的方法可能不完美，但至少我知道这会让他更强壮、更负责。}
{192}{}{没错。杀掉带病的人不是最好的办法。你得找到治愈方法，因为它肯定会再次出现。}
{193}{}{没错，爱因斯坦。}
{194}{}{别吵了！你让我头疼！}
{195}{}{呃，是的，当然，伙计。我得走了。}
{196}{}{好吧，尽量不要用枪解决所有问题。再见。}
{197}{}{今天真热啊！}
{198}{}{比利！你最好别捣乱，你这个小混蛋！}
{199}{}{比利！你最好确保今晚辐射牛保暖，否则就等着挨揍吧！}
{200}{}{该死，你这个小子！别吵了，开始工作！}
{201}{}{我告诉过你别捣乱！}
{202}{}{我警告你，比利！}
{203}{}{你不想走硬道理吧？}
{204}{}{抱歉，孩子，不能聊。我有生意要做。}
{208}{}{抱歉，不能聊。我有生意要做。}
{209}{}{你最好别去烦比利；他今天有一大堆工作要做。}
{210}{}{滚开，我很忙。}
{211}{}{为什么总有人来烦我？看不出我在工作吗？}
{212}{}{想找工作就去找商人。我不招聘。}
{213}{}{为什么不去马耳他之鹰玩玩？我很忙。}
{214}{}{你在这里干什么？滚出去！}
{215}{}{我说滚出去！我不是开玩笑！我会打爆你的脑袋！}
{216}{}{你们这些小混混永远学不会，是吗？}
