{100}{}{你看到达雷尔。}
{101}{}{你看到一个骑士。}
{102}{}{欢迎来到钢铁兄弟会。}
{103}{}{呃……}
{104}{}{钢铁兄弟会是什么？}
{105}{}{你知道哪里能找到水芯片吗？}
{106}{}{你知道关于失踪商队的事吗？}
{107}{}{没事了。}
{108}{}{（嘲笑你）朋友，我觉得你没机会进来。长老们对新成员有最低智商要求。}
{109}{}{是的……呃……不。只是人们根本不试图了解我们。}
{110}{}{兄弟会是一个致力于保存科技的男女集体。}
{111}{}{我听说你们会献祭小狗。}
{112}{}{你穿的是什么类型的护甲？}
{113}{}{我如何了解你们的科技？}
{114}{}{再见。}
{115}{}{不……我从没听说过。我们的一位首席抄写员可能知道。也许你可以问问他们。如果你加入我们的话。}
{116}{}{加入？我该如何加入？}
{118}{}{你们什么都不知道。}
{119}{}{献祭小狗！！！你从哪听来的？别相信荒原上的流言，他们都是一群可怜的疯子。}
{120}{}{其实我觉得那样挺酷的。}
{121}{}{抱歉让你不安。}
{122}{}{钢铁兄弟会之外的人都是疯子？}
{123}{}{想了解我们更多，唯一的方法就是加入我们。我的朋友卡博特可以帮你。}
{125}{}{兄弟会里有水芯片吗？}
{126}{}{你需要和卡博特谈谈。}
{127}{}{钢铁兄弟会到底是干什么的？}
{128}{}{没关系……只是人们根本不试图了解我们。}
{129}{}{有什么好了解的？}
{130}{}{嗯？我觉得你们有点古怪。}
{131}{}{科技。这就是所有人需要了解的。加入我们，你就会明白。}
{132}{}{如何加入兄弟会？}
{133}{}{你们对我来说有点太偏激了。}
{134}{}{很遗憾你这么想。}
{135}{}{这是动力战斗步兵护甲T-51b型号，通常称为动力装甲。}
{136}{}{我在荒原上游荡了好几周，从没见过这样的护甲。}
{137}{}{看起来穿着会很笨重。}
{139}{}{兄弟会是荒原上唯一拥有动力装甲的人。只有最尊贵的骑士才能有幸穿上这种终极护甲。}
{140}{}{这仍然不能解释我为什么从没见过。}
{141}{}{如何加入兄弟会？}
{143}{}{异教徒曾试图从我们这里夺走动力装甲。他们得杀掉一个兄弟才能得到他的遗产，但如果真到了那一步，护甲会损坏到无法使用。}
{144}{}{我想试着从你冰冷的尸体上夺走它。}
{145}{}{再见。}
{146}{}{我需要献祭小狗才能加入吗？}
{147}{}{笨重？一点也不。神圣的护甲经过精密设计，仿佛是穿戴者身体的延伸。它能大幅增强力量，并帮助抵御辐射，以便更有效地为兄弟会服务。没有我的神圣护甲，我会感到不完整。}
{148}{}{为什么荒原上没人有这种护甲？}
{149}{}{我想要一套。}
{151}{}{如果你想加入，需要和卡博特谈谈。}
{152}{}{我不敢相信。他们竟然派他去那里？}
{153}{}{我不敢相信。他们竟然派她去那里？}
{154}{}{所以你接受了著名的辉光任务。（笑）}
{155}{}{不……我要去古代秩序。}
{156}{}{辉光是什么？}
{157}{}{这不关你的事。}
{158}{}{是的，我接受了。再见。}
{159}{}{辉光，古代秩序是同一个地方。那不是个好去处。}
{160}{}{你为什么这么说？}
{161}{}{能有多难。我只需去拿点东西再带回来。这是新手任务。}
{162}{}{为什么有两个名字？}
{163}{}{这个地方有什么特别的？}
{164}{}{辉光是地表人所知的名字，据说是当时最先进武器的研发地。至少古代文献是这么说的。现在我们能看到的就是一个充满辐射的大坑。我想长老们派想加入的兄弟会成员去那里只是为了摆脱他们。}
{165}{}{其他人？在我之前还有其他人？}
{166}{}{我要去古代秩序。它在哪里？}
{167}{}{你说得对。这不关我的事。}
{168}{}{嗯？首先，从这里出发要向东南走10天的路程。然后还有辐射。我们从来没有去过“古代秩序”是有原因的。如果没有Rad-X，你还没意识到就会被辐射烤熟。}
{170}{}{让我理清一下……}
{171}{}{大多数地表人认为那只是一个巨大的放射性坑。因此它被称为辉光，或者有些人称为热点。我们兄弟会知道真相。根据古代文献，这个地方是我们所有科技的来源。谁知道那里还会有什么。}
{173}{}{让我理清一下……}
{174}{}{其他人试过。我们再也没有听到他们的消息。}
{175}{}{你几乎让我不想加入兄弟会了。}
{176}{}{他们太弱了。我会再见到你的。}
{177}{}{我去那里时应该注意什么？}
{179}{}{辉光和古代秩序是同一个地方。}
{180}{}{辉光是什么？}
{181}{}{别误会，加入兄弟会是个好选择。这里是荒原中最安全的地方。没有其他地方能找到更好的武器和护甲。我们服务于科技，科技也服务于我们。}
{182}{}{听起来不错，我要走了。}
{183}{}{你能告诉我关于辉光的事吗？}
{184}{}{听起来不值得去。}
{185}{}{什么？……}
{186}{}{为什么古代秩序有两个名字？}
{187}{}{古代秩序在哪里，危险是什么？}
{189}{}{大多数地表人认为那只是一个巨大的放射性坑。因此它被称为辉光，或者有些人称为热点。我们兄弟会知道真相。根据古代文献，这个地方是我们所有科技的来源。谁知道那里还会有什么。}
{190}{}{我还有个问题。}
{191}{}{我能帮你吗？}
{192}{}{没事了。再见。}
{193}{}{当然，请问。}
{194}{}{你好。}
{195}{}{是的，鲁特格不久前亲自来过，这不像他的风格。他想查明他的商队发生了什么。我不知道是什么原因。其他人说他们在集散地附近看到过什么，但在靠近之前就消失了。这一切都很让人不安，希望能尽快解决。}
{196}{}{我听说你们进行动物献祭！也许你们用这些商队进行黑暗仪式！}
{197}{}{有什么怀疑吗？}
{198}{}{如果你看到什么，请告诉我。我也想尽快弄清楚。}
{199}{}{不太确定，但我怀疑是恶意行为……不过话说回来，荒原上有很多奇怪而危险的生物。可能只是某种生物，或者更可能是一群。希望这能帮到你。祝你好运。}  {201}{}{感谢你的时间。再见。}


{201}{}{谢谢你的时间。再见。}
{202}{}{好的，谢谢。再见。}
{203}{}{谢谢你的信息。再见。}
{204}{}{谢谢，再见。}
{205}{}{好的……谢谢你的信息。}
{206}{}{谢谢你的警告。再见。}
{207}{}{谢谢你。再见。}
{208}{}{谢谢你的时间。}



{209}{}{如果你想要更好的武器，也许你应该去南边的辉光看看。（达雷尔指向南方）}
{210}{}{拿着这些Rad-X。（达雷尔给你一些药片）}
{211}{}{像这样吞下去。（达雷尔做出吃药的动作并揉揉肚子）嗯，真好吃。}
{212}{}{等等，还没到时候！（达雷尔阻止你吃药）等到你到了辉光再吃。}
