{100}{}{这个人看起来可能是来自钢铁兄弟会。}
{101}{}{你在想是什么导致了这位兄弟会成员遭受如此重创。}
{102}{}{无论是谁干的，这个人似乎已经不在这里了。}
{103}{}{无论是谁干的，可能潜伏在这个设施的更深处。也许你应该在这里行走时保持警惕。}
{104}{}{你在想是什么导致了这个机器人的损毁。}
{105}{}{你在想是不是爆炸导致了这个机器人的毁坏。}
{106}{}{这看起来像是科学家们在这里研究的某个项目。}
