{100}{}{你看到一个哈布人。}
{101}{}{我简直不敢相信我还活着，更不敢相信你竟然把他们全都干掉了！等等，我在说什么？我还活着，不是吗？现在你说什么我都信。}
{102}{}{我要杀了你。}
{103}{}{把你的钱全给我！}
{104}{}{收拾好你的生活，赶紧离开这里，否则我也会解决掉你！}
{105}{}{呃？}
{106}{}{呃，但是？你？（叹气）好吧，请快点动手。我讨厌疼痛。}
{107}{}{别伤害我！}
{108}{}{好的。（他给了你20个哈布币。）我可以走了吗？}
{109}{}{可以。}
{110}{}{不行。}
{111}{}{呃，为什么？}
{112}{}{因为我说了算！你有意见吗？}
{113}{}{好吧，你可以走了。}
{114}{}{不，不好意思，先生！请不要伤害我——我不喜欢疼痛！}
{115}{}{不，不好意思，女士！请不要伤害我——我不喜欢疼痛！}
{118}{}{你是傻了吗？我是说，非常感谢您救了我，善良的先生。我得走了，再见。}
{119}{}{你是傻了吗？我是说，非常感谢您救了我，善良的女士。我得走了，再见。}
{122}{}{是的……是的……是的，先生。我再也不会做坏事了！我……我不会作弊，不会撒谎、勒索、抢劫、谋杀或绑架。}
{123}{}{是的……是的……是的，女士。我再也不会做坏事了！我……我不会作弊，不会撒谎、勒索、抢劫、谋杀或绑架。}
{126}{}{赶紧滚出这里！}
{127}{}{你是个骗子！}
{128}{}{是的，先生！}
{129}{}{是的，女士！}
