{100}{}{你看到一个傻瓜。}
{101}{}{你看到一个帮派成员。}
{102}{}{他们叫我们傻瓜，但你才是傻子，居然敢来这里。}
{103}{}{你想跟我们找麻烦吗？}
{104}{}{这里不是你的地盘。}
{105}{}{别以为你能随便走进来找事。}
{106}{}{小心点，否则你会进墓地，墓地。}
{107}{}{是啊，我们要对付那些墓地帮。}
{108}{}{没有那些墓地帮，废料场就不一样了。它会是我们的！}
{109}{}{哈哈哈！哈哈哈哈！}
{110}{}{傻瓜！傻瓜！傻瓜！没错！}
{111}{}{听过那个关于鸡和战壕的笑话吗？}
{112}{}{冷静点。}
{113}{}{笑到最后的人才笑得最好。}
{114}{}{生活就是个笑话，尽情享受吧。}
{115}{}{要不是那些墓地帮，我们就能统治这个镇。至少可以踢伦尼一脚。}
{116}{}{做个傻瓜吧。}
{117}{}{你觉得那件破皮衣能救你不被巴卡打吗？}
{118}{}{怎么回事？你妈生你的时候把你摔了？}
{119}{}{如果我长得那么丑，我早就自杀了。}
{120}{}{你们墓地帮看起来就像刚从坟墓里出来一样。}
{121}{}{只有傻瓜才会做这么蠢的事。哦，等等，我就是个傻瓜。}
