{100}{}{你看到一个农民。}
{101}{}{哦，是啊，大人物被一只可怕的狗吓得跑掉了。菲尔，你真是好样的。是的，真是好样的。}
{102}{}{你在干什么，菲尔？你是在检查运动鞋的鞋底吗？}
{103}{}{伙计，那只狗看起来很饿。它肯定想活生生地吃掉你，菲尔。}
{104}{}{对于一只可怜又无辜的动物来说，这是不是有点小题大做了？}
{105}{}{你那只狗真不错。}
{106}{}{如果你能帮菲尔解决掉他的狗，他一定会很感激。}
{107}{}{谢谢你处理掉那只狗。}
{108}{}{你获得了50点经验值。}
