{100}{}{你看到一个地穴成员。}
{101}{}{你看到一个帮派成员。}
{102}{}{欢迎加入我们的帮派，伙计。}
{103}{}{我们地穴帮会埋葬那些傻瓜。}
{104}{}{很高兴你站在我们这边。}
{105}{}{有了你的帮助，我们可以干掉那些傻瓜。}
{106}{}{这座城镇现在是我们的了。}
{107}{}{我喜欢你的风格。}
{108}{}{你得弄件皮夹克。你现在是地穴帮的一员了。}
{109}{}{我们不欢迎你这种人在这里，傻瓜。}
{110}{}{滚出去，不然我们就把你扔出去。}
{111}{}{如果你惹事，整个地穴帮都会对付你。}
{112}{}{你做了错误的选择。现在你要被埋葬了。}
{113}{}{你在这里干什么？}
{114}{}{废料场是我们的地盘。}
{115}{}{在废料场，如果你不和我们一伙，你要么是个失败者，要么是个傻瓜。你是哪种？}
{116}{}{你在跟我说话吗？你在跟我说话吗？}
{117}{}{这可不是游戏，伙计。你要么是地穴帮的一员，要么就等着被埋。}
{118}{}{只有地穴帮才有资格穿皮夹克。}
{119}{}{跑吧，傻瓜们，趁你们还有活命的机会。}
{120}{}{嘿，Rayze，狩猎季刚开始，傻瓜们在蠢动物名单上。}
{121}{}{嘿，伙计们，留个傻瓜给我来解决。}
