{100}{}{你看到龙。}
{101}{}{}
{102}{}{}
{103}{}{你看到一个刀锋帮的成员。}
{104}{}{你看到一个刀锋帮的成员。}
{105}{}{你觉得那可能是书本。}
{106}{}{你觉得那可能是伤疤。}
{107}{}{你觉得那可能是枪手。}
{108}{}{你觉得那可能是抽搐。}
{109}{}{你觉得那可能是锤子。}
{110}{}{你觉得那可能是剃刀。}
{111}{}{滚开！你看不出来我在休息吗！}
{112}{}{你在这儿游荡干什么？}
{113}{}{只是看看星星。}
{114}{}{出来找你。}
{115}{}{狩猎。}
{116}{}{你这次找错地方了。说实话，也许你还能活命。}
{117}{}{我其实是来杀你的。}
{118}{}{我想结束帮派战争。}
{119}{}{只是找个家。就在那儿，月亮。}
{120}{}{我可能会为此感到遗憾，但我不在乎死人。}
{121}{}{没门。现在，赶紧滚开，否则我叫夜班守卫来收拾你。}
{122}{}{哎呀，你似乎不怎么享受生活。我来帮你结束它。}
{123}{}{你找到我了。现在，走开或者死！}
{124}{}{我想我还是走吧。}
{125}{}{我宁愿活着。}
{126}{}{撕裂者帮有什么动静？}
{127}{}{他们要杀了你！}
{128}{}{他们死了。看到了吗？}
{129}{}{暂时没有。}
{130}{}{太好了。去告诉剃刀。}
{131}{}{别骗我。滚出去！}
{132}{}{那就赶紧滚出去，干掉那个混蛋！}
{133}{}{哟，伙计！你对撕裂者帮干得漂亮！}
