{100}{}{你看到了长老。}
{101}{}{很高兴见到你。希望你对这个小村庄的印象还不错。}
{102}{}{是的。}
{103}{}{不，这里太平静了，没什么刺激。}
{104}{}{太好了。我有个请求，希望你能帮忙。我保证你会为你的服务得到丰厚的回报。}
{105}{}{请详细说说……}
{106}{}{这只是个演示，但也许你会喜欢接下来我要说的。}
{107}{}{我洗耳恭听……}
{108}{}{我们被辐射蝎子困扰已久。所有被派去消灭这些怪物的人都没有回来。如果你愿意跟随我的向导去它们的巢穴并消灭它们，我会给你武器和护甲。}
{109}{}{听起来不错。}
{110}{}{不，谢谢。}
{111}{}{真遗憾。请离开。}
{112}{}{太好了。萨米会带你去巢穴。拿上这些物品——它们会派上用场。}
{113}{}{请尽快帮助我们。时间不等人。}
{114}{}{我不跟你这种人说话，陌生人。}
