{100}{}{你看到一个疲惫的渔夫。}
{101}{}{先生，我听说过你。我希望你能让我和我的孩子安静地待着。}
{102}{}{女士，我听说过你。我希望你能让我和我的孩子安静地待着。}
{103}{}{你好，先生。我很少在这儿见到陌生人。有需要我帮忙的吗？}
{104}{}{你好，女士。我很少在这儿见到陌生人。有需要我帮忙的吗？}
{105}{}{你知道哪里能找到水芯片吗？}
{106}{}{你知道关于变种人大军的事情吗？}
{107}{}{你来自哪里？}
{108}{}{捕鱼怎么样？}
{109}{}{把你所有的东西交出来，否则我就杀了你！}
{110}{}{鲁克！}
{111}{}{等一下，你不就是那个在废土上四处游荡、打怪物屁股的人吗？需要我帮忙吗？}
{112}{}{等一下，你不就是那个在废土上四处游荡、打怪物屁股的姑娘吗？需要我帮忙吗？}
{113}{}{我的补给有点紧张……}
{114}{}{从来没有人说我不友好，我也不想重复女人们对我的评价，但我正在钓鱼，需要绝对的安静才能抓到那些该死的鱼，所以请保持安静。}
{115}{}{有人告诉过你，你说话很啰嗦吗？}
{116}{}{好的。}
{117}{}{我在找一些信息。}
{118}{}{我看起来像个拾荒者吗？好吧，也许有点像，但那是因为我花了很多时间在废土上教我儿子捕鱼和成长。}
{119}{}{我已经六年没去拾荒了。辐射蝎子太多了，外面到处都是那些害虫，一个人可能会被杀。}
{120}{}{大约八年前，我在废城卖过一些芯片。我不知道它们是干什么用的，其中一个可能是水芯片，不过我不敢肯定。}
{121}{}{总之，我需要安静来钓鱼，所以希望你能保持安静，让我回去工作，否则我和我的孩子会饿死。}
{122}{}{变种人大军？这地方没有。普通军队就够糟糕的了，呵呵。}
{123}{}{你知道这世界上的政治太多了。我一直告诉我儿子，这些政客迫不及待地想再把世界炸掉。这就是我靠土地生活的原因，远离政客！这是唯一的生活方式。}
{124}{}{这是相当私人的问题。我曾因为别人问得更少而杀了人，问问我儿子就知道了。不过我觉得你看起来很诚实，所以这次我就不计较了。}
{125}{}{我在这儿钓了五年鱼，情况越来越糟。我想是臭鼬，那只三眼巨型鲶鱼，把所有东西都吓跑了。}
{126}{}{但我一定会抓到那条鱼，你等着瞧。这已经是我们之间的私人恩怨了，只有一个能活着离开，相信我。我比钢铁兄弟会还认真。}
{127}{}{你可能会杀了我，但如果我不反抗你，我会给孩子树立一个坏榜样。你明白我的困境吗？为什么不走开，让我们都轻松点！}
{128}{}{我不会走开，除非你照我说的做，否则你就别想活着走。}
{129}{}{闭嘴去死吧！}
{130}{}{好吧。我会让你安静。}
{131}{}{小子，我觉得你在荒野上流浪得太久了。}
{132}{}{小姐，我觉得你在荒野上流浪得太久了。}
{133}{}{尝尝这个。}
{134}{}{尝尝这个……哦，该死，我把它放哪了……}
{135}{}{我听说在东边有个大避难所，还有传闻说在南边某处有个秘密避难所。也许在废城和枢纽镇能找到一些芯片。希望这对你有帮助。}
{136}{}{我不想显得不友好，但我需要安静来钓鱼，所以如果你能保持安静让我继续工作，我会很感激的，不然我和我儿子就要饿死了。祝你好运，消灭那些害虫。}
{137}{}{变种人大军？普通的军队就已经够糟糕了。我听说有人在死城骚扰食尸鬼，但那是很久以前的事了。}
{138}{}{这是个私人问题。我的出生地当然是我母亲的子宫，不过这有点太随意了。我已经没有家了，我和我儿子只是四处流浪，努力生存。}
{139}{}{我确实知道一些储藏点的位置，但那是我的秘密。}
{140}{}{这里是杀或被杀——荒野法则——但我告诉你，你继续杀怪物，我就给你一些补给。}
{141}{}{是的，你是。但“runk”到底是什么意思？不管是什么，我希望它是友好的。}
{142}{}{现在我受伤了。我好心好意地想要友好相处，你却指责我唠叨！哼！我不容易被冒犯，但你让我生气到想核平某人。}
{143}{}{不管怎样，你还是离开这里吧。走吧！}
{144}{}{非常感谢。}
{145}{}{你想聊些什么？}
{146}{}{我在找一个水芯片。}
{147}{}{我在打听一些变种人大军的消息。}
{148}{}{你能告诉我关于兄弟会的事情吗？}
{149}{}{你能告诉我关于尸骨城的事情吗？}
{150}{}{抱歉，朋友，我想我帮不了你。}
{151}{}{“runk”可不等于保持安静。现在闭上你的嘴，离开这里。}
{152}{}{好吧。拿你想要的，然后离开。}
{153}{}{你真的不太友好，是吗？}
{154}{}{如果我没有表现得更感激，请原谅，但我觉得你还是离开吧。}
{155}{}{如果可以，我尽量避免他们。如果他们不喜欢你，他们的巡逻队会非常麻烦。}
{156}{}{那是在海岸边。我听说那里的帮派横行，还有各种我不想让孩子看到的事情，所以我远离那个地方！}
{157}{}{把那东西收起来，免得伤到人。武器在手的时候，没法进行文明的对话。}
{158}{}{小子，没有什么比人与鱼之间的较量更精彩的了。}
{159}{}{小子，我有没有告诉过你我抓到巨鳗的那次……}
{160}{}{儿子，不要和你爸顶嘴！}
{161}{}{也许这次我能抓到那只三眼鲶鱼。}
{162}{}{晚餐马上就好！}
{163}{}{没有什么比在篝火上烤一条多汁的鱼更美味了。}
{164}{}{安静，儿子，你把鱼吓跑了。}
