{100}{}{你看到弗利普。}
{101}{}{你看到一个巨大的变种人。}
{102}{}{啊啊啊！去死吧，异教徒！}
{103}{}{你应该在控制室。不要耽搁。}
{104}{}{哦，人类。这很有趣。你要么跟我去见中尉，要么就死在这里。}
{105}{}{绝不！}
{106}{}{好吧，我投降。我们走吧。}
{107}{}{洛普！}
{108}{}{很好。想活命就跟我来。}
{109}{}{好的。我们走吧。}
{110}{}{你先请。}
{111}{}{你以为我像其他同类一样愚蠢。你大错特错。这是个致命的问题，我明白。}
{112}{}{我们又见面了。这次你逃不掉。}
{113}{}{别靠近她！我会先杀了你！}
{114}{}{弗利普，我什么时候能离开这里？}
{115}{}{很快。很快。你的时间快到了。}
{116}{}{我迫不及待想再次和你在一起。}
{117}{}{你不会后悔你的决定，亲爱的。浸泡是痛苦的……}
{118}{}{希望不要太痛。}
{119}{}{FEV非常痛苦，但你会活下来。}
{120}{}{你会加入我们。身心合一。}
{121}{}{我们会再次在一起吗？}
{122}{}{是的，亲爱的。是的。}
{123}{}{我爱你。}
{124}{}{我也爱你。}
