{100}{}{你看到追随者侦察队的杰瑞。}
{101}{}{你看到追随者侦察队的巴斯贝尔。}
{102}{}{你看到追随者侦察队的理查德。}
{103}{}{你看到追随者侦察队的杰森。}
{104}{}{你看到追随者侦察队的影子。}
{105}{}{你看到追随者侦察队的琳恩。}
{106}{}{你看到追随者侦察队的格温多琳。}
{107}{}{你看到追随者侦察队的罗莎。}
{108}{}{你看到追随者侦察队的伊丽莎白。}
{109}{}{你看到追随者侦察队的丽贝卡。}
{110}{}{是谁在追随者的大厅中行走？}
{111}{}{嗯？}
{112}{}{我是}
{113}{}{。我来此和平相见。}
{114}{}{我是}
{115}{}{。你的毁灭者。}
{116}{}{追随者是谁？}
{117}{}{好吧。我看你有点慢。你是谁？}
{118}{}{我}
{119}{}{。你死定了。}
{120}{}{我}
{121}{}{。我帮忙。}
{122}{}{我杀！}
{123}{}{我}
{124}{}{。我走了。}
{125}{}{你想帮忙？如果你想帮助我们，我想你需要去找妮可或杰克谈谈。他们有更多时间处理慢一点的人。}
{126}{}{好吧。只要别在这里惹麻烦。}
{127}{}{你是想要终结儿童的邪恶吗？}
{128}{}{是的。我想消灭那些渣滓。}
{129}{}{不。我宁愿杀了你们这些懦夫。}
{130}{}{这些“孩子”是谁？}
{131}{}{我为什么要杀孩子？}
{132}{}{太好了！去找妮可，她会告诉你如何帮助我们。}
{133}{}{这些“孩子”是一个崇拜黑暗神灵的邪教组织。就我个人而言，我觉得他们身上有种邪恶的味道。}
{134}{}{我会杀了他们。}
{135}{}{我不知道。他们听起来太强大了。}
{136}{}{我能做些什么来帮忙？}
{137}{}{算了吧！我绝不会帮你们的。}
{138}{}{他们确实很强大，但我认为以你的能力，应该能潜入并帮助我们摧毁他们。}
{139}{}{那我就去做。}
{140}{}{不。我想我不会帮忙。}
{141}{}{随便你。如果他们占领了废土，别说我们没警告过你。}
{142}{}{如果你去找妮可，她会告诉你更多关于如何阻止他们的事情。}
{143}{}{谢谢。再见。}
{144}{}{不是孩子。我们不会想伤害他们。不。这些是大教堂的“孩子”。一群讨厌的人。}
{145}{}{如果是这样，当然——我会干掉他们。}
{146}{}{哦。我以为你在说小孩。算了。我想我不会帮忙。}
{147}{}{你能告诉我关于这些“孩子”的事吗？}
{148}{}{我们是“启示录追随者”。我们试图为废土带来和平。}
{149}{}{听起来是个好主意。祝你好运。}
{150}{}{你打算怎么做到这一点？}
{151}{}{这似乎不太可能。}
{152}{}{我们正在努力让废土上的人们对那些因人类破坏性本质而变异的不幸者更加包容。}
{153}{}{那就祝你好运吧。}
{154}{}{在整个历史中，我们从未能获得包容。你认为战争为什么会发生？}
{155}{}{这简直是一派胡言。}
{156}{}{你说得对，我们人类确实心胸狭隘。然而，总是有希望的。}
{157}{}{那就祝你好运吧。}
{158}{}{我觉得你说得对。来，让我用这个让你更加开明。}
{159}{}{尽管如此，我们并没有征求你的意见。再见。}
{160}{}{我们中间有个愤世嫉俗者。我相信你有你的理由。不管怎样，我相信我们可以达成某种理解。}
{161}{}{祝你好运。那么，再见。}
{162}{}{我听说儿童会已经获取了我们的一些秘密。我想知道这是怎么发生的？}
{163}{}{我相信这里有一个间谍。}
{164}{}{我知道。我正在把你的秘密卖给他们。}
{165}{}{我肯定你只是想象的。他们怎么可能知道任何事情？}
{166}{}{真的吗？我自己也是这么想的，但我担心我永远无法在这个理论上获得太多支持。}
{167}{}{你有没有什么线索是谁？}
{168}{}{很高兴知道这些。谢谢你的时间。}
{169}{}{你就是那个双面间谍！！！}
{170}{}{其实没有。我能想到的唯一可能是，那个人必须能够接触到一些信息并能与外界联系。你可能要关注一下新兵或侦察兵。}
{171}{}{谢谢。再见。}
{172}{}{那么，妮可会很高兴知道我杀了那个特工。}
{173}{}{你一定是对的。谢谢你让我看清事实。}
{174}{}{我觉得你就是那个双面间谍。想要骗我，是吧。那么你去死吧！}
{175}{}{干得好，消灭了那个特工。现在我们可能有机会对抗那些儿童会了。}
{176}{}{祝你好运。}
{177}{}{我可以帮你训练，让你在战斗中更有效率。}
{178}{}{真的吗？那太好了。}
{179}{}{给你。也许这会帮助你在战斗中。}
