{100}{}{你看到一个专心学习的启示录追随者。}
{101}{}{请安静，我正在学习。}
{102}{}{我们寻求知识以保护我们免受儿童会的威胁。}
{103}{}{妮可说了解敌人的知识将帮助我们取得胜利。}
{104}{}{你好。}
{105}{}{欢迎来到启示录追随者。请尊重我们图书馆的神圣。}
{106}{}{祝你有个光辉的一天。}
{107}{}{所有的知识都是神圣的。}
{108}{}{我们必须保护自己。}
{109}{}{谁知道儿童会大教堂下面发生了什么？}
{110}{}{知识就是生命。}
{111}{}{妮可帮助我们理解知识的神圣。}
{112}{}{妮可推动我们复兴失落的东西。}
{113}{}{我必须为妮可找到那本书。}
{114}{}{卡佳一定在这里的某个地方。卡佳！}
{115}{}{儿童会已被逐出大教堂。}
{116}{}{是你做的，对吧？}
{117}{}{现在，我们可以安全地探索重建文明所需的知识。}
{118}{}{儿童会不再是威胁，这难道不是件光辉的事吗？}
{119}{}{祝你有个光辉的一天。}

