{100}{}{你看到一个食尸鬼帮派成员。}
{101}{}{你在这里干什么？好好回答——这可能是你唯一的机会……}
{102}{}{我在找老大。}
{103}{}{这栋楼已经被查封了——我来送最后通牒。}
{104}{}{抱歉，只是随便看看。}
{105}{}{呃。}
{106}{}{Set不在这儿，快走。}
{107}{}{哦，好吧。再见。}
{108}{}{好吧，当我找到那个混蛋时，我会让他永远消失。}
{109}{}{那么，你就得当我的沙袋了。}
{110}{}{你脑子有问题吧。Set不会让你这种废物搞垮他的。他有保镖，还有枪。}
{111}{}{有多少保镖？}
{112}{}{你在这里干什么？}
{113}{}{Set身边总有至少两个保镖，但他可以召唤超过十个。如果他在他的王座室，那十个保镖随时待命。}
{114}{}{那你在这里干什么？}
{115}{}{我才不告诉你呢。你以为我是傻子吗？快走……}
{116}{}{我负责确保没人通过。这是僵尸的地盘。}
{117}{}{什么是僵尸？}
{118}{}{好吧，祝你有个愉快的一天。}
{119}{}{不是“什么”……是“谁”。我们是僵尸。如果我们表现好，Set会让我们成为他的保镖。现在我就告诉你这些。}
{120}{}{你为什么想成为他的保镖？}
{121}{}{再见。}
{122}{}{我说过我就告诉你这些。快走。}
{123}{}{你疯了。你以为这里是什么？你最好离开。}
{124}{}{不，我想进去。}
{125}{}{好吧，我这就走。}
{126}{}{我可不这么想。赶紧滚，不然我叫兄弟们来踩扁你。}
{127}{}{这是威胁吗？}
{128}{}{好吧。}
{129}{}{是威胁。现在是事实。僵尸！}
{130}{}{如果你珍惜自己的命，就离这个地方远点。}
{131}{}{嘿，僵尸们，我们找到一个沙袋了！}
{132}{}{你该走了。}
