{100}{}{你激怒了加里！}
{101}{}{你看到了加里。}
{102}{}{嘿！只有食尸鬼才能领取水配给。}
{103}{}{闭嘴！}
{104}{}{变种人无视了你。}

{1000}{}{水}
{1001}{}{死城}
{1002}{}{塞特}
{1003}{}{水坝区}
{1004}{}{大厅}
{1005}{}{卢}
{1006}{}{食尸鬼}
{1007}{}{正常人}
{1008}{}{芯片}

{1100}{}{我不知道。}
{1101}{}{你就在这儿。}
{1102}{}{他是个懦夫。我们应该干掉他和他的食尸鬼。}
{1103}{}{就是这里。}
{1104}{}{我不知道。}
{1105}{}{他是哈里的上司。}
{1106}{}{软弱的东西。}
{1107}{}{比食尸鬼还软弱。}
{1108}{}{我不知道。}
