{100}{}{守卫愤怒地开始攻击。}
{101}{}{守卫被你的力量吓到了。}
{102}{}{只有影剑能凭借气场震慑这个守卫。你必须用言语来做到这一点。}
{103}{}{你成功地从守卫那里偷走了一些东西。}
{104}{}{你被发现了。}
{105}{}{守卫身上没有其他东西了。}
{106}{}{守卫没有受到影响。}
{107}{}{一个废城的门卫。}
{108}{}{你在废城干什么，陌生人？}
{109}{}{找点乐子。}
{110}{}{把你所有的东西都给我！}
{111}{}{你能帮我弄点装备吗？}
{112}{}{没事。谢谢。再见。}
{113}{}{这里有很多事情可以做。让我想想。你可以练习射击奶牛，或者在废城里四处逛逛，看看风景，只要你不惹麻烦就行。}
{114}{}{这附近还有其他什么地方吗？}
{115}{}{好吧！把你所有的东西都给我！}
{116}{}{谢谢。再见。}
{117}{}{嗯，据说有个老住户在他房子里藏了一把厉害的枪，在西北边。不过从来没人找到过。}
{118}{}{好的。谢谢你的时间。}
{119}{}{还有其他事情吗？}
{120}{}{好吧，好吧，好吧。求你别伤害我。}
{121}{}{没门！去死吧，渣滓！！}
{122}{}{嗯，据说以前住在西北边建筑里的家伙有把相当厉害的枪。也许你能找到它。}
{123}{}{抱歉，我只是个守卫。试着和其他居民聊聊。}
{124}{}{这只是完整版游戏中你能做的事情的一部分。你可以：杀掉挡路的一切，偷窃和潜行解决问题，或者通过交谈化解麻烦并赢得他人的好感。}
{125}{}{完整版游戏发布后，你将能更充分地利用你的技能。}
