{100}{}{去死吧，你这条狗！}
{101}{}{我的失败会被复仇的！}
{102}{}{站住，见习者！你有什么报告？}
{103}{}{西线一切安好。}
{104}{}{辐射蝎子和难以忍受的高温。呃……长官。}
{105}{}{其实，我想知道你有没有听到什么消息。}
{106}{}{没有报告，长官！}
{107}{}{嗯？}
{108}{}{站住！我认得你——你去过钢铁兄弟会。有些人可能信任你，但我不信。说明你的来意！}
{109}{}{我的事是我的，就像你的事是你的。}
{110}{}{我想见到一个友好的面孔。}
{111}{}{在废土上游荡，努力生存。}
{112}{}{我在消灭沙漠害虫。你不赞成吗？}
{113}{}{我只会对你们的首领说明。带我去钢铁兄弟会。}
{114}{}{什么事？}
{115}{}{站住！我认得你，我不信任你。我警告你：如果你给我们惹麻烦，你会被当场击毙。现在走！}
{116}{}{站住！谁在那里！报上你的名字和来意！}
# TRANSLATION NOTES
# The player-character's name is inserted after line 117, and then has
# line 118, 119, 120, or 121 appended.
{117}{}{我是}
{118}{}{，我在为我的避难所寻找一个水芯片。你能帮我吗？}
{119}{}{，我在寻找变种人袭击的源头。}
{120}{}{，这不关你的事！}
{121}{}{，我在寻找冒险。}
{122}{}{去你的，士兵小子。}
{123}{}{呃！}
{124}{}{停下！这些土地属于钢铁兄弟会。立刻离开，否则我们会把你当作入侵者击毙。}
{125}{}{很好。继续，见习者。}
{126}{}{我明白了。继续，见习者。}
{127}{}{有报告称大型变种人袭击旅行者，所以我们加强了警戒。密切关注区域，如有必要，撤回基地。见习者，解散！}
{128}{}{这是动荡的时期，见习者！变种人正在进军，袭击商队！我们需要情报，现在就需要！没有报告是不够的！}
{129}{}{赶紧滚出去，给我们带回一些有用的情报！见习者，解散！}
{130}{}{哦，是的，我听说过你。智商不高，但战斗力惊人。真可惜。}
{131}{}{这是我们的地盘，在这里，你的事就是我们的事。我再问一次，说明你的来意。}
{132}{}{我在为我的避难所寻找一个水芯片。你能帮我吗？}
{133}{}{我正在寻找变种人袭击的源头。}
{134}{}{这可能是你的地盘，但我不是你的奴隶。}
{135}{}{我在荒地上游荡了很久。我想知道你们有没有什么消息。}
{136}{}{友好的面孔？那不会是我。我建议你离开。}
{137}{}{我们都是如此。只要你不对钢铁兄弟会不利，你就不会受到伤害，但要小心行事。}
{138}{}{这取决于你是否把我们当成害虫。如果你攻击我们的敌人，你可以在我们的领土上行走。如果你冒犯我们，你会死。你被警告了。}
{139}{}{这是个合理的请求。加入我们。}
{140}{}{水芯片？我希望你不是认真的！你还不如在地表挣扎求生，也不要把自己束缚在一块机器上。}
{141}{}{我们也是。最普遍的理论是他们来自辉光，但我怀疑即使是变种人也无法在那里生存太久。如果你发现了什么，告诉我们。}
{142}{}{你怎么敢指责我这样的事情！钢铁兄弟会从未强迫任何人违背意愿为我们服务。这违背了我们的一切信念。滚出我的视线！}
{143}{}{我们在西边一天路程的地方发现了一支被毁的商队。我们找到了一个幸存者——可怜的女孩。她声称他们是被拥有惊人力量的变种人类袭击的。}
{144}{}{我们听到了足够多的报告，以至于我们……感到担忧。如果我是你，我会小心行事。}
{145}{}{我得教教你一些礼貌，男孩。这应该会是个轻松的娱乐。}
{146}{}{我得教教你一些礼貌，女孩。这应该会是个轻松的娱乐。}
{147}{}{你的心智完全崩溃了。可怜的生物。}
{148}{}{别浪费我的时间，蠢货！}
{149}{}{你想要什么？}
{150}{}{没什么。}
{151}{}{那我建议你离开。}
