{100}{}{你看到一个骑士。}
{101}{}{抱歉，见习者，我现在不能说话。}
{102}{}{你好。}
{103}{}{你知道吗，穿着动力装甲可以在没有水的情况下生存数周？}
{104}{}{你不觉得打一场好仗很过瘾吗？}
{105}{}{我很喜欢新的激光步枪，但旧的激光手枪才是我的最爱。}
{106}{}{夜间的外围巡逻非常危险。如果我是你，我不会在晚上走得太远。}
{107}{}{小心点，外面的世界很致命。}
{108}{}{我觉得我的盔甲上有个污点！}
{109}{}{兄弟会真是太棒了。我没有在外面生活过，但这里已经是最好的了。}
{110}{}{你好，见习者。}
{111}{}{如果你需要什么，可以去找弗瑞。}
{112}{}{弗瑞就在那边，如果你需要找人谈谈。}
{113}{}{我得在巡逻和训练之间找时间继续学习。我觉得我有点生疏了。}
{114}{}{见习者，你必须时刻保持身心的最佳状态。}
{115}{}{做一个骑士不仅仅是战斗，我的孩子。}
{116}{}{做一个骑士不仅仅是战斗，我的女士。}
