{100}{}{这个掠夺者因为害怕加尔而不再与你交谈。}
{101}{}{你看到一个强悍的沙漠掠夺者。}
{102}{}{是死神之手，他回来了！}
{103}{}{打扰了，死神之手。很抱歉打扰你。}
{104}{}{你是回来杀掉你的儿子吗？}
{105}{}{哎呀！鬼啊！}
{106}{}{死人又活过来了！死神之手回来了！}
{107}{}{很高兴见到你。}
{108}{}{嗨。}
{109}{}{我在等加尔摧毁阴影镇。我想要一些战利品。}
{110}{}{欢迎，朋友。}
{111}{}{很高兴你能回来拜访。}
{112}{}{除非你想找麻烦，最好把那东西收起来。}
{113}{}{想聚会吗？不然就把武器收起来。}
{114}{}{哦，看起来挺强硬的，是吧？}
{115}{}{加尔·死神之手爱他的战士。把那东西收起来，然后去找他说话。}
{116}{}{所以，你觉得自己很厉害，是吧？惹我试试看，我们都能知道结果。}
{117}{}{我不喜欢你的样子。}
{118}{}{走开！}
{119}{}{你想要什么？}
{120}{}{我在找一个叫坦迪的女人。见过她吗？}
{121}{}{没什么，只是随便看看。}
{122}{}{嗯？}
{123}{}{哦，你一定是来找工作的。去大房间找加尔，别打扰我们。}
{124}{}{那就去别处做。}
{125}{}{没见过。你问这个干嘛？}
{126}{}{没什么，只是找我的一个朋友。}
{127}{}{她的脑袋值赏金。如果我能杀了她，我能赚不少钱。}
{128}{}{你在撒谎。她在哪儿？}
{129}{}{啊，好吧。}
{130}{}{真的吗？她长什么样？}
{131}{}{大约六英尺高。金发。她来自阴影沙地。}
{132}{}{是的，她在这里。她在大房子里。你知道，如果我们告诉加尔，他会想要分一杯羹。你可能需要考虑一下。}
{133}{}{你听起来不像是认真的。我觉得你在搞什么鬼。如果你说的是真的，那我就自己去拿赏金。}
{134}{}{我……我不能再说了，否则加尔会杀了我。}
{135}{}{去你的！}
{136}{}{我不喜欢你的样子。你最好离我远点。}
{137}{}{什么？走开！}
