{100}{}{你看到一个食尸鬼管理员。}
{101}{}{你在这里干什么？}
{102}{}{寻找未来过去的遗迹。}
{103}{}{我是个探险者。}
{104}{}{关你什么事，虫脸？}
{105}{}{呃……}
{106}{}{你说什么？}
{107}{}{没什么。}
{108}{}{我在寻找失落的科技。}
{109}{}{我就知道你会这么说。快滚出我的地盘。}
{110}{}{哦，这里没有那种东西。也许在上面的神庙或者水处理厂。快走吧。}
{111}{}{哎！别碰我的东西。快滚！我是说真的。}
{112}{}{别在我面前嚣张。我才是这里的老大。}
{113}{}{哦，是吗。}
{114}{}{我要把你的脸塞到你的……}
{115}{}{哎！好吧，我认输。我走。}
{116}{}{你没资格命令我。拿这个去吧！}
{117}{}{我不想跟你说话。}
