{100}{}{你看到一个食尸鬼难民。}
{101}{}{请不要杀我。}
{102}{}{闭嘴，我可能会让你活命。}
{103}{}{别担心，你不值得我动手。}
{104}{}{这里发生了什么？}
{105}{}{呃。}
{106}{}{你……你反正会杀了我！}
{107}{}{啊，哦。好吧。}
{108}{}{很好，就保持这样。}
{109}{}{现在，告诉我这里发生了什么。}
{110}{}{你要杀了我！}
{111}{}{啊，你不是刚让我闭嘴吗？}
{112}{}{你现在就得死。}
{113}{}{是的，现在我想知道这里发生了什么。}
{114}{}{超级变种人袭击了。我们被屠杀了。他们有枪和炸弹，甚至还有一些蒸汽卡车。他们杀了我的朋友。变种人就像屠宰我们一样，可能你也会这样对我。}
{115}{}{超级变种人袭击了。我们被屠杀了。他们有枪和炸弹，甚至还有一些蒸汽卡车。他们杀了我的朋友。变种人就像屠宰我们一样。}
{116}{}{什么是蒸汽卡车？}
{117}{}{你是怎么活下来的？}
{118}{}{你知道为什么吗？}
{119}{}{我不知道。}
{120}{}{谢谢。}
{121}{}{你真没用。}
{122}{}{我听说他们很生气，因为有个普通人杀了他们的人。}
{123}{}{哦，呃，还有别的吗？}
{124}{}{嗯。好吧。滚吧。}
{125}{}{没有。}
{126}{}{谢谢。}
{127}{}{你真没用。}
{128}{}{我听说有些下水道的食尸鬼可能活了下来，但我不喜欢那里。}
{129}{}{好的，谢谢。}
{130}{}{就这样？}
{131}{}{对，就这样。}
{132}{}{好的，谢谢。}
{133}{}{我躲起来直到大部分变种人离开了。}
{134}{}{还有别的吗？}
{135}{}{有个大东西，好像在没人拉的情况下自己转动轮子。}
{136}{}{嗯，好的。还有别的吗？}
{137}{}{真傻。}
{138}{}{嘿，那你为什么问这个？}
{139}{}{够了！你太放肆了！}
{140}{}{只是随便问问。就这样。}
{141}{}{又是你？现在你想干什么？}
{142}{}{有什么新消息吗？}
{143}{}{就聊聊天。}
{144}{}{没有。嗯，其实我听说会有更多超级变种人过来。但我不知道什么时候。}
{145}{}{嗯，好吧。}
{146}{}{那去别处聊天吧。我得保持低调。}
