{100}{}{你看到一扇看起来非常坚固的门。}
{101}{}{技能对这扇门没有效果。}
{102}{}{你被安保系统电击，受到}
{103}{}{点伤害。}
{104}{}{你用红色通行卡解锁了这扇门。}
{105}{}{这个物品对门没有效果。也许其他物品会更有用。}
{106}{}{你被安保系统电击，受到}
{107}{}{点伤害。}
{108}{}{这扇门似乎被能量场保护着。也许你可以想办法关闭它。}
{109}{}{这扇门似乎有一个次级锁。}
{110}{}{你注意到门上有一些红色标记。}
{111}{}{你注意到门上有一些红色标记。}
{112}{}{你想知道什么能解锁这扇门。}
{113}{}{你成功绕过了安保系统。}
{114}{}{你激活了安保系统，被电击，受到}
{115}{}{点伤害。}
{116}{}{你没有检测到门上有任何陷阱。}
{117}{}{你成功绕过了安保系统。}
{118}{}{你激活了安保系统，被电击，受到}
{119}{}{点伤害。}
{120}{}{你没有检测到门上有任何陷阱。}
{121}{}{你被安保系统电击，受到}
{122}{}{点伤害。}
{123}{}{这扇门似乎被能量场保护着。也许你可以想办法关闭它。}
{124}{}{你成功解锁了这扇门。}
{125}{}{你未能撬开这扇门的锁。}
