{100}{}{这个安全门的框架上有蓝色油漆的残留。}
{101}{}{你被门上的电场轻微电击，受到一点伤害。}
{102}{}{你被门上的电场强烈电击。你受到}
{103}{}{点伤害。}
{104}{}{你强行打开了门。}
{105}{}{门被锁住了。}
{106}{}{授权已授予。正在解除电场。}
{107}{}{你没有进入这个房间的权限。}
{108}{}{这个物品对安全系统没有影响。}
{109}{}{你撬开了安全门的锁。}
{110}{}{这扇门似乎有某种安全措施。}
{111}{}{你未能撬开门锁。}
{112}{}{这个技能对门没有效果。}
{113}{}{你解除掉了门上的电场安全系统。}
{114}{}{你增强了电场的力量。}
{115}{}{你未能解除电场。}
{116}{}{你在没有触发安全系统的情况下撬开了门锁。}
{117}{}{你未能撬开门锁，并受到安全系统的严重伤害。}
{118}{}{你未能撬开门锁，并受到安全系统的伤害。}
{119}{}{你被安全系统电击，失去撬锁的专注力。}
{120}{}{你被安全系统强烈电击，失去撬锁的专注力。}
{121}{}{你完全无法撬开这个锁，并损坏了你的撬锁工具。}
{122}{}{你未能撬开这个锁。}
{123}{}{你看到一扇坚固、生锈的门。}

{124}{}{你看到一扇未上锁的红色油漆门。}
{125}{}{你看到一扇未上锁的红色油漆门。}
{126}{}{你看到一扇未上锁的门，前面有一个移动的红色场。}
{127}{}{你看到一扇未上锁的门，上面有高压安全系统。}
{128}{}{你看到一扇红色油漆的门。}
{129}{}{你看到一扇红色油漆的门。}
{130}{}{你看到一扇门，前面有一个移动的红色力场。}
{131}{}{你看到一扇门，上面装有高压安全系统。}
{132}{}{你看到一扇上锁的门，上面有红色油漆。}
{133}{}{你看到一扇上锁的门，上面有红色油漆。}
{134}{}{你看到一扇上锁的门，前面有一个移动的红色力场。}
{135}{}{你看到一扇上锁的门，上面装有高压安全系统。}
{136}{}{这扇红色门的锁似乎需要一个特殊的钥匙卡。}
{137}{}{这扇红色门的锁似乎需要一个特殊的钥匙卡。}
{138}{}{这扇门的锁似乎需要一个特殊的钥匙卡。此外，你注意到门前有一个闪烁的红色力场。}
{139}{}{这扇门的锁似乎需要一个特殊的红色钥匙卡。此外，你注意到上面装有高压安全系统。}

{140}{}{你看到一扇未上锁的门。}
{141}{}{你看到一扇未上锁的门。}
{142}{}{你看到一扇未上锁的门，前面有一个移动的力场。}
{143}{}{你看到一扇未上锁的门，上面装有高压安全系统。}
{144}{}{你看到一扇门。}
{145}{}{你看到一扇门。}
{146}{}{你看到一扇门，前面有一个移动的力场。}
{147}{}{你看到一扇门，上面装有高压安全系统。}
{148}{}{你看到一扇上锁的门。}
{149}{}{你看到一扇上锁的门。}
{150}{}{你看到一扇上锁的门，前面有一个移动的力场。}
{151}{}{你看到一扇上锁的门，上面装有高压安全系统。}
{152}{}{这扇门的锁似乎需要一个特殊的钥匙卡。}
{153}{}{这扇门的锁似乎需要一个特殊的钥匙卡。}
{154}{}{这扇门的锁似乎需要一个特殊的钥匙卡。此外，你注意到门前有一个闪烁的力场。}
{155}{}{这扇门的锁似乎需要一个特殊的钥匙卡。此外，你注意到上面装有高压安全系统。}

{156}{}{你看到一扇未上锁的门，上面有蓝色油漆。}
{157}{}{你看到一扇未上锁的门，上面有蓝色油漆。}
{158}{}{你看到一扇未上锁的门，前面有一个移动的蓝色力场。}
{159}{}{你看到一扇未上锁的门，上面装有高压安全系统。}
{160}{}{你看到一扇涂有蓝色油漆的门。}
{161}{}{你看到一扇涂有蓝色油漆的门。}
{162}{}{你看到一扇门，前面有一个移动的蓝色力场。}
{163}{}{你看到一扇门，上面安装了高压安全系统。}
{164}{}{你看到一扇上锁的蓝色门。}
{165}{}{你看到一扇上锁的蓝色门。}
{166}{}{你看到一扇上锁的门，前面有一个移动的蓝色力场。}
{167}{}{你看到一扇上锁的门，上面安装了高压安全系统。}
{168}{}{这扇蓝色门的锁似乎需要一个特殊的钥匙卡。}
{169}{}{这扇蓝色门的锁似乎需要一个特殊的钥匙卡。}
{170}{}{这扇门的锁似乎需要一个特殊的钥匙卡。此外，你注意到门前有一个闪烁的蓝色力场。}
{171}{}{这扇门的锁似乎需要一个特殊的钥匙卡。此外，你注意到上面安装了高压安全系统。}

{172}{}{你看到一扇未上锁的蓝色门。}
{173}{}{你看到一扇未上锁的蓝色门。}
{174}{}{你看到一扇未上锁的门，前面有一个移动的蓝色力场。}
{175}{}{你看到一扇未上锁的门，上面安装了高压安全系统。}
{176}{}{你看到一扇涂有蓝色油漆的门。}
{177}{}{你看到一扇涂有蓝色油漆的门。}
{178}{}{你看到一扇门，前面有一个移动的蓝色力场。}
{179}{}{你看到一扇门，上面安装了高压安全系统。}
{180}{}{你看到一扇上锁的蓝色门。}
{181}{}{你看到一扇上锁的蓝色门。}
{182}{}{你看到一扇上锁的门，前面有一个移动的蓝色力场。}
{183}{}{你看到一扇上锁的门，上面安装了高压安全系统。}
{184}{}{这扇蓝色门的锁似乎需要一个特殊的钥匙卡。}
{185}{}{这扇蓝色门的锁似乎需要一个特殊的钥匙卡。}
{186}{}{这扇门的锁似乎需要一个特殊的钥匙卡。此外，你注意到门前有一个闪烁的蓝色力场。}
{187}{}{这扇门的锁似乎需要一个特殊的蓝色钥匙卡。此外，你注意到上面安装了高压安全系统。}

{188}{}{你看到一扇涂有红色油漆的门。}
{189}{}{你看到一扇门，前面有一个移动的红色力场。}
{190}{}{你看到这扇红色门上有一个高压安全系统。}
{191}{}{你看到这扇红色门上有一个高压安全系统。你想知道是否有通行钥匙可以绕过它。}

{192}{}{你看到一扇门。}
{193}{}{你看到一扇门，前面有一个移动的力场。}
{194}{}{你看到这扇门上有一个高压安全系统。}
{195}{}{你看到这扇门上有一个高压安全系统。你想知道是否有通行钥匙可以绕过它。}

{196}{}{你看到一扇涂有蓝色油漆的门。}
{197}{}{你看到一扇门，前面有一个移动的蓝色力场。}
{198}{}{你看到这扇蓝色门上有一个高压安全系统。}
{199}{}{你看到这扇蓝色门上有一个高压安全系统。你想知道是否有通行钥匙可以绕过它。}

{200}{}{你看到一扇涂有蓝色油漆的门。}
{201}{}{你看到一扇门，前面有一个移动的蓝色力场。}
{202}{}{你看到这扇蓝色门上有一个高压安全系统。}
{203}{}{你看到这扇蓝色门上有一个高压安全系统。你想知道是否有通行钥匙可以绕过它。}

{204}{}{你注意到这扇门上有一个陷阱。}
{205}{}{电梯无法运作。它似乎需要比应急电源更多的电力。}
