{100}{}{一个废城的守卫。}
{101}{}{这里是废城。只要你不惹麻烦，这里是个不错的居住地。}
{102}{}{小心吉兹莫和他的手下。}
{103}{}{我喜欢我的老板。}
{104}{}{你最好把那东西收起来。废城是个友好的地方，朋友，我们希望保持这种状态。}
{105}{}{把什么收起来？}
{106}{}{别告诉我该怎么做，废物。}
{107}{}{听起来不错。顺便问一下，这里的武器法律是什么？}
{108}{}{哦哦。}
{109}{}{你的武器，笨蛋。基利安不会没收你的武器，但你最好把它们放在枪套里。}
{110}{}{哦，抱歉。}
{111}{}{不可能！我不会为任何人放下我的枪！}
{112}{}{你最好守规矩，因为这是法律，而我是执法者。把武器收起来，除非自卫，否则不要拔出武器，这样你就不会和我们这些守卫有麻烦。}
{113}{}{[更多]}
{114}{}{违反法律，我们会让你回到无序的废土——生死由你。}
{115}{}{好吧，既然你这么说。}
{116}{}{去你的法律！}
{117}{}{嗯，呃，对我来说没问题。但你最好小心点。}
{118}{}{好吧，那就这样。呵呵。}
{119}{}{问得好。除非自卫，否则不能拔出武器。如果你挑起争斗，那就是你的责任。除此之外，你有权携带武器。只是不要无缘无故拔刀或枪。祝你有美好的一天。}
{120}{}{谢谢——你也是。}
{121}{}{嘿，你，禁止携带武器！我不管你小时候是不是被你妈摔过。禁止携带武器。}
{122}{}{笨蛋！}
{123}{}{你因杀死守卫获得150点经验值。}
