# Beth is female. She speaks with a normal accent.  She is a friendly person
# who is mostly interested in selling equipment and information.
{100}{}{你看到贝丝，武器店的老板。}
{101}{}{你好，我能帮你什么忙？}
{102}{}{我可以问你一些问题吗？}
{103}{}{我可以再问你一些问题吗？}
{104}{}{我想买点东西。}
{105}{}{我有东西要卖。}
{106}{}{在这里怎么赚钱？}
{107}{}{没事，再见。}
{108}{}{鲁克？}
{109}{}{关于失踪的商队，街上有什么传闻吗？}
# the Deathclaw is male
{110}{}{你对死亡爪了解多少？}
{111}{}{你能再告诉我关于死亡爪的事吗？}
# Decker is male
{112}{}{你能告诉我关于德克的事吗？}
{113}{}{你能告诉我关于不同商人的事吗？}
{114}{}{你听到什么好传闻了吗？}
{115}{}{谢谢，就这样。再见。}
{116}{}{嗯，没事了。}
# Jain is a female religious figure
{117}{}{嗯，我不喜欢八卦，但我听说德克的死跟对简的暗杀有关。}
# The Maltese Falcon is a bar
{118}{}{嗯，我通常不背后议论别人，但我认识一个人，他说在谋杀发生前看到三个极其高大的披袍人物走进马耳他之鹰。}
# the Children of the Cathedral is an organization - religious
{119}{}{嗯，我通常不背后议论别人，但有人杀了大教堂之子的高阶女祭司简。我自己不喜欢他们，但我不知道她做了什么值得被这样对待。}
# The Brotherhood of Steel is an organization - religious
{121}{}{嗯，我通常不背后议论别人，但我的一个商人朋友看到一群变种人在钢铁兄弟会以北的沙漠中游荡。}
{122}{}{嗯，我通常不背后议论别人，但大教堂之子一直在打听你的下落。你要小心。他们是个奇怪的团体。}
{123}{}{嗯，我不喜欢八卦，但我听说德克的死跟对简的暗杀有关。}
{124}{}{还有别的。我认识一个人，他说在谋杀发生前看到三个极其高大的披袍人物走进马耳他之鹰。}
{125}{}{还有别的。有人杀了大教堂之子的高阶女祭司简。我自己不喜欢他们，但我不知道她做了什么值得被这样对待。}
{126}{}{还有别的。我的一个商人朋友看到一群变种人在钢铁兄弟会以北的沙漠中游荡。}
{127}{}{还有别的。大教堂之子一直在打听你的下落。你要小心。他们是个奇怪的团体。}
{128}{}{还有别的吗？}
{129}{}{谢谢，我可以再问一个问题吗？}
{130}{}{好的，谢谢。}
{131}{}{抱歉，你刚才说什么？}
# Klug and Ruk are a stupid person saying something incomprehensible
{132}{}{克鲁格？}
{133}{}{鲁克！}
{134}{}{抱歉，我听不懂。等你感觉好些再来吧。}
# The Merchant Market is a location
{135}{}{我这儿不招人，不过商人市场中心有个招聘启事，你可以去看看。}
{136}{}{好的，谢谢。}
{137}{}{不，至少暂时没有好消息。给我点时间调查一下。<她向你眨了眨眼>还有别的事吗？}
{138}{}{有。}
{139}{}{没有。}
{140}{}{还有什么我可以帮你的吗？}
{141}{}{当然可以，别傻了。}
{142}{}{当然，我很乐意帮忙。你想知道什么？}
{143}{}{好的，和你聊天很愉快，祝你有美好的一天。}
{144}{}{没有了，那你还有别的想聊的吗？}
{145}{}{有。}
{146}{}{没有。}
{147}{}{那就快回来吧。别做个陌生人。}
{148}{}{那个人可千万别惹，他让我害怕。他“拥有”马耳他之鹰。}
{149}{}{你为什么那么说？他“拥有”马耳他之鹰。}
{150}{}{他为什么让你害怕？}
{151}{}{抱歉，这让我想起了一个曾经拥有它的朋友。德克非常想要它，但我朋友不肯卖。两天后，他们在旧城区的小巷里发现他死了。}
{152}{}{你为什么认为是德克干的？}
{153}{}{他本该知道不要惹德克的。}
{154}{}{抱歉，我得走了。}
{155}{}{我朋友是个洁癖，他绝不会靠近旧城区。他是被马格南手枪打死的，旧城区没人买得起那种枪。而且，他头部中了一枪，背部中了两枪。这像是抢劫吗？我朋友只是想重新掌控自己的生活。}
{156}{}{嘿，我喜欢他的风格。杀了他后，把他的尸体放在他最讨厌的地方。}
{157}{}{重新掌控生活？}
{158}{}{听到这个我很遗憾。}
{159}{}{哦，好的。}
{160}{}{你可能不明白，但我们大多数人都期待有一天能掌控自己的生活，不再属于商人或放贷者。}
{161}{}{哦，谢谢。}
{162}{}{你就不能闭嘴吗？！}
{163}{}{这是我听过最蠢的话！}
{164}{}{还有什么我能帮你的吗？}
{165}{}{好吧，抱歉。是你问的。}
{166}{}{他是集市上最致命的人；大多数人都说是他在掌控这里，而不是商人或警察。如果你惹到他，小心点。}
{167}{}{这并不意味着他有权杀人。}
{168}{}{你让我恶心，请离开。我相信他一定很想念你的陪伴。}
{169}{}{嗯，这里有三个主要的商人集团。有水商会、赤色商队和远行商队。他们也掌控着市议会。你想了解哪个？}
{170}{}{水商会。}
{172}{}{赤色商队。}
{173}{}{远行商队。}
{174}{}{市议会。}
{175}{}{就这些。谢谢你的信息。}
{176}{}{其实，算了。}
{177}{}{他们掌控着所有的水。贪婪的人，我不想为他们工作。工资最差，工作也一样糟糕。}
{178}{}{他们一直控制着所有的水吗？}
{179}{}{他们是失踪商队的幕后黑手吗？}
{180}{}{谢谢，还有一个关于商人的问题……}
{181}{}{谢谢，再见。}
{182}{}{你还想了解什么？}
{183}{}{没有。据我所知，很久以前一群商人占领了水塔，自称是水商会，人们必须从他们那里获取水。商人战争持续了多年，直到一个叫罗伊·格林的人——对，就是贾斯汀的祖父——帮助谈判达成协议，结束了战争。}
{184}{}{什么样的协议？}
{185}{}{该死！抱歉我问了。}
{186}{}{谢谢，还有一个关于商人的问题……}
{187}{}{谢谢，再见。}
{188}{}{他成立了市议会，并限制了水价。个人认为他们应该狠狠教训他们——哦，抱歉。我是说他们应该让他们知道谁是老大。}
{189}{}{太好了。我不需要那么多信息，但还是谢谢你。}
{190}{}{谢谢，还有一个关于商人的问题……}
{191}{}{谢谢，再见。}
{192}{}{抱歉，我有时候说得太多了。还有什么是你想知道的吗？}
{193}{}{红色商队是一群疯狂的人。他们什么活都接，不管风险多大。我很惊讶他们丢失的商队没有更多。}
{194}{}{他们也丢失商队吗？}
{195}{}{有多危险？}
{196}{}{谢谢，还有关于商人的问题……}
{197}{}{谢谢，再见。}
{198}{}{他们会穿过一个已知会被袭击的区域。他们收费很高，所以可以雇更多人手。报酬很高，但你得活着才能花，对吧？}
{199}{}{他们也丢失商队吗？}
{200}{}{谢谢，还有关于商人的问题。}
{201}{}{谢谢，再见。}
{202}{}{其实所有商人都有一些商队失踪。我想远行商队只是运气不好。}
{203}{}{有多危险？}
{204}{}{谢谢，还有关于商人的问题……}
{205}{}{谢谢，再见。}
{206}{}{远行商队的报酬不错，工作也不算太危险。布奇是这家店的老板，是个好人。他们很公平，让我在这里随心所欲地工作；我喜欢和他们一起工作。而且如果你为布奇工作，买东西还能打折。}
{207}{}{我个人不这么认为。我觉得是死亡爪或者可能是钢铁兄弟会。}
{208}{}{你为什么不认为是水商人？}
{209}{}{死亡爪到底是什么？}
{210}{}{你能再告诉我关于死亡爪的事吗？}
{211}{}{钢铁兄弟会是谁？}
{212}{}{你为什么认为是钢铁兄弟会？}
{213}{}{谢谢，我们回到商人话题。}
{214}{}{好吧，我得走了。}
{215}{}{有些人认为是水商人干的，但我不这么认为。我觉得是该死的死亡爪，或者可能是钢铁兄弟会的人。}
{216}{}{嗯，我以为是它在毁掉商队，但看来不是。不过它还在外面。流言太多了，不可能不存在。}
{217}{}{我觉得是它在袭击商队。也可能是钢铁兄弟会；他们是一群怪人。有些人认为是水商人，但他们错了。}
{218}{}{当然。}
{219}{}{因为，正如我告诉每个人的，他们也有一些商队失踪。虽然不像远行商队那么严重，但他们也受到了影响。}
{220}{}{他们可能在撒谎，或者这可能是他们计划的一部分，让你相信他们。}
{221}{}{为什么远行商队比其他人更容易出事？}
{222}{}{关于失踪商队的另一个问题……}
{223}{}{谢谢，我们回到商人那边吧。}
{224}{}{你满嘴胡扯！}
{225}{}{谢谢，但我得走了。}
{226}{}{不好意思！你判断得也太快了吧，你是害怕真相吗？}
{227}{}{有六位代表，每个主要商人集团两位。任何事情都需要至少四票才能通过。他们从来无法达成一致。}
{228}{}{想法不错，但我非常怀疑。他们互相破坏多年，但这不是他们的风格。他们不会花那么多钱来对付商队。而且所有商队都有重兵护卫。你会想有人能逃出来。他们没有足够的人力或资金来做到这一点。至少会有一个幸存者。}
{229}{}{是啊，但为什么这种事在远行贸易公司的商队上发生得比其他的多？}
{230}{}{关于失踪商队的另一个问题……}
{231}{}{谢谢，我们回到商人那边吧。}
{232}{}{谢谢，但我得走了。}
{233}{}{运气不好？我不知道，也许他们走的路线和其他人不同。也许是因为他们的护卫不如红色商队那么严密，但……他们的货物可能比水商人更好。谁知道呢。三者之间似乎没有明显的区别。}
{234}{}{水商人可能在撒谎，或者这可能是他们的计划之一，让你相信他们。}
{235}{}{关于失踪商队的另一个问题……}
{236}{}{谢谢，我们回到商人那边吧。}
{237}{}{你从来不停下来吗！}
{238}{}{谢谢，但我得走了。}
{239}{}{不好意思！你随时可以离开。如果你不想要答案，就不该问。}
{240}{}{死亡爪是战争后从废墟中崛起的最邪恶的东西。有人说它是战争中徘徊在这片土地上的强大幽灵。它不是幽灵，它和你我一样真实。它有20英尺高，牙齿和你的手臂一样大。它是某种恶魔，在世界被火焰吞噬时找到了这里。}
{241}{}{呃，抱歉我问了。}
{242}{}{你疯了！我现在就该结束你的痛苦。}
{243}{}{你还知道关于死亡爪的其他事情吗？}
{244}{}{哇！你知道它在哪吗？}
{245}{}{嗯，我知道旧城区有个叫哈罗德的老变种人。他见过它。他是唯一一个见过它并活下来的人。}
{246}{}{唯一一个见过它并活下来的人？}
{247}{}{是啊，当然，我就是死亡爪的爸爸。}
{248}{}{是啊，当然，我就是死亡爪的妈妈。}
{249}{}{关于失踪商队的另一个问题……}
{250}{}{谢谢，我们回到商人那边吧。}
{251}{}{我会去看看。再见。}
{252}{}{老城区的斯拉皮大叔有时会谈起这事，但他只是个疯疯癫癫的老傻瓜。}
{253}{}{关于失踪商队的另一个问题……}
{254}{}{谢谢，我们回到商人那边吧。}
{255}{}{谢谢。我会去看看。再见。}
{256}{}{你会看到的！}
{257}{}{是啊，挺神奇的，不是吗？它在西南方向的某个地方。老城区有个叫哈罗德的老变种人，他亲眼见过这东西的巢穴。他是我认识的最和善的废土流浪者。}
{258}{}{关于失踪商队的另一个问题……}
{259}{}{谢谢，我们回到商人那边吧。}
{260}{}{谢谢。我会去看看。再见。}
{261}{}{钢铁兄弟会全是些崇拜科技的疯子；他们在这里的西北方向。他们进行人祭，还做其他各种可怕的事情。}
{262}{}{这太荒谬了！谁告诉你的？}
{263}{}{关于失踪商队的另一个问题……}
{264}{}{谢谢，我们回到商人那边吧。}
{265}{}{这太可怕了，谢谢你的警告。再见。}
{266}{}{嗯，我不记得了，但无论是谁说的都不会撒谎……我是说，这可能是真的！你还是小心点好。}
{267}{}{关于失踪商队的另一个问题……}
{268}{}{好吧，我们回到商人那边吧。}
{269}{}{你是个白痴！}
{270}{}{看看时间，我得走了！再见。}
{271}{}{为什么，你不知道吗？[低声]我听说他们进行人祭，还做其他各种可怕的事情！}
{272}{}{是的，我们确实这样做。那有什么问题吗？}
{273}{}{作为钢铁兄弟会的“成员”，我可以向你保证，绝对没有这样的事情发生！}
{274}{}{真的吗？我去过那里，他们看起来很奇怪，但没那么糟糕。}
{275}{}{真的吗？我完全不知道。}
{276}{}{好像你不知道似的。你显然是他们中的一员，穿着那套金属盔甲到处走。你们都是一群病态的人。}
{277}{}{我不知道你在暗示什么，但我可以向你保证，兄弟会里没有任何“病态”的事情发生。}
{278}{}{是啊，那又怎样。我们不都是吗？}
{279}{}{我完全不知道。}
{280}{}{对不起，先生。请放下你的武器。}
{281}{}{对不起，女士。请放下你的武器。}
{282}{}{抱歉，但除非你收起武器，否则我不会帮助你。这是商店，不是竞技场。}
{283}{}{呃……嗯，是的……嗯，你……我……你还需要什么吗？}
{284}{}{你永远不知道一个人在私下里是什么样子。你得小心选择交往的对象。你还需要什么吗？}
# Not believing the player for a moment, then getting nervous
{285}{}{你是个……？我是说。我不是那个意思……嗯……今天天气真好。你不觉得吗？那么，我还能为你做些什么？}
{286}{}{又一个关于失踪商队的问题……}
{287}{}{谢谢，我们回到商人那边吧。}
{288}{}{不，就这样。再见。}
{289}{}{当然，随你说。我还能为你做些什么？}
{290}{}{太好了！让我给你看看我有什么。}
{291}{}{我有最好的货物，你在找什么？}
{292}{}{这正是我想听的！你需要什么？}
{293}{}{让我们开始谈生意吧。}
{294}{}{如果你有钱，我就有兴趣。}
{295}{}{我最喜欢这样的顾客！}
{296}{}{你想买点什么？也许我对你有误解。}
{297}{}{哦，对了。你为布奇工作，你可以享受15%的折扣。}
{298}{}{我还是会给你15%的折扣，因为我喜欢你。}
{299}{}{抱歉，你不再享有折扣了。}
{300}{}{给我看看你有什么。}
{301}{}{你有好东西吗？}
{302}{}{那么，让我看看。}
{303}{}{当然。}
{304}{}{今天你有什么好东西给我？}
{305}{}{太好了。我总是需要更多的商品。}
{306}{}{我很乐意看看你有什么。}
{307}{}{别想坑我。}
{308}{}{我可能会让你卖给我点东西，最好是好货。}
{309}{}{你最好别浪费我的时间。}
{310}{}{希望这次你有我需要的东西。}
{311}{}{又见面了。很高兴见到你。今天我能为你做些什么？}
{312}{}{你好！很高兴再次见到你。今天有什么可以帮你的吗？}
{313}{}{真希望能休息一天，外面天气太好了。}
{314}{}{又见面了，今天看起来真精神啊？}
{315}{}{这么快就回来了？}
{316}{}{你刚走就想我了？}
{317}{}{这么快就需要什么了吗？}
{318}{}{好久不见，今天需要点什么？}
{319}{}{有段时间没见了，希望你一切都好。}
{320}{}{还活着啊，我都开始担心了。今天需要点什么？}
{321}{}{你来了。上次来已经超过一周了。一定要保持联系，你可是我最喜欢的顾客！}
{322}{}{是吗？}
{323}{}{什么事？}
{324}{}{你是来买东西的吗？}
{325}{}{这是我的店，最好规矩点。}
{326}{}{什么事！}
{327}{}{又是你？}
{328}{}{时间就是金钱，有什么事？}
{329}{}{需要什么吗？}
{330}{}{你听说了吗？他死了！我太高兴了！这是这个城市发生过的最好的事情。}
{331}{}{我已经告诉过你了。他死了！我们就忘了他吧，他的名字只会带来不好的回忆。}
{332}{}{哦，是啊。}
{333}{}{是的，他活该，我一点都不觉得内疚。}
# Sid works for Beth. Sid is male.
{334}{}{是你干的？真的？我爱你！[贝丝看向希德] 别想太多，聪明人……这是给你的谢礼…… [贝丝给了你六个治疗针] 这不多，但我真的很感激！}
{335}{}{是你干的？真的？你真棒！你不知道听到他死了我有多高兴。拿着这些…… [贝丝给了你六个治疗针] 这不多，但我真的很感激！}
{336}{}{抱歉，我这里没有你喜欢的东西。}
{337}{}{没看到喜欢的？我会努力进更好的货。}
{338}{}{抱歉你不喜欢我的报价，但我得能赚点利润。}
{339}{}{不想卖了？没关系。}
{340}{}{抱歉没能帮上你。祝你有美好的一天。}
{341}{}{也许下次吧。再见。}
{342}{}{希望下次能更好地帮助你。}
{343}{}{别浪费我的时间。}
{344}{}{如果不买东西，请离开。}
{345}{}{如果不想买东西，我希望你能让我一个人待着。}
{346}{}{如果不卖东西，请离开。}
{347}{}{如果不想卖东西，就别打扰我。}
{348}{}{请离开。}
{349}{}{我就知道你又要浪费我的时间。}
{350}{}{果然，我就知道你没钱。}
{351}{}{谢谢你的光顾，也许我今天可以早点回家。}
{352}{}{你几乎把我这儿的东西都买光了！}
{353}{}{希望你能带得动这些东西！}
{354}{}{谢谢，希望我能把这些东西都卖掉！}
{356}{}{这些应该会卖得不错，谢谢。}
{357}{}{这些我能用上。谢谢。}
{358}{}{希望我有地方放下这些东西！}
{359}{}{非常感谢！希望你有个美好的一天！}
{360}{}{感谢你的光顾，欢迎随时再来。}
{361}{}{你随时欢迎光临，当然是在营业时间内。}
{362}{}{谢谢你，祝你有美好的一天。}
{363}{}{再见！谢谢！}
{364}{}{就这些弹药？我有点失望。嗯，下次你得多花点钱！}
{365}{}{囤积弹药？这是个好主意。弹药永远不嫌多。}
{366}{}{只买必需品，对吧？再见！}
{367}{}{我还真没想到你会买东西。}
{368}{}{感谢你的光顾，你还不错。}
{369}{}{谢谢你的货物。}
{370}{}{祝你有美好的一天。}
{371}{}{再见。}
{372}{}{谢谢你。}
{373}{}{感谢您的购买，祝您有美好的一天。}
{374}{}{我听到了！}
{375}{}{不是开玩笑。}
{376}{}{希德！别这样！}
{377}{}{如果你不闭嘴，我就送你个礼物。}
{378}{}{我听到了！你被解雇了！}
{379}{}{别理他，我一直都不理。}
{380}{}{哦，你真是太搞笑了，希德。}
{381}{}{你想得美。}
{382}{}{闭嘴。}
{383}{}{嘿。待在原地，希德。}
{384}{}{我不这么认为，聪明鬼。}
{385}{}{如果你不离开我的顾客，我就让你变得很惨。}
{386}{}{请原谅我那‘讨厌’的保安。}
{387}{}{你真是个笨蛋！}
{388}{}{希德！}
{389}{}{亲爱的？你怎么想出这些奇怪的名字的？}
{390}{}{[贝丝叹气] 我}
{391}{}{应该把他锁起来。你觉得呢？}
{392}{}{我觉得他是嫉妒了！}
{393}{}{希德！不要对顾客无礼！}
{394}{}{你还知道谁可能有关于死亡爪的信息吗？}
{395}{}{再见。}
{396}{}{谢谢。}
{397}{}{哦。}
{398}{}{镇上有没有什么地方我应该避开的？}
{399}{}{哦，有的。你最好尽可能远离马耳他之鹰。德克和他那油腻的走狗凯恩可不是什么好东西。如果不小心，他们会把你吃得骨头都不剩。我也建议你离友好贷款公司的洛伦佐远一点。}
