{100}{}{你看到一个守卫。}
{101}{}{嘿！你不是这里的员工。}
{102}{}{你没看到我在休息吗。}
{103}{}{是时候休息放松一下了。}
{104}{}{我们不招人，去找商人谈谈。}
{105}{}{最近守卫任务挺平静的。}
{106}{}{这里是守卫宿舍！不准闲杂人等。}
{107}{}{你是新来的吗？}
{108}{}{别烦我，我累了。}
{109}{}{有人想玩牌吗？}
{110}{}{谁愿意替我上夜班？}
{111}{}{明天去猎鹰酒吧吧。}
{112}{}{当然。}
{113}{}{这周谁想去猎蝎子？}
{114}{}{我的脚好疼。}
{115}{}{我应该去睡一会儿。}
{116}{}{发工资了吗？}
{117}{}{我怀念护送商队的日子。}
