# These are people who are running caravans. either gender, but majority Male
# Tone of voice similar to truck drivers of California-- rough and partially
# harsh.

{100}{}{你看到一个商队司机。}
{101}{}{今天会是漫长的一天！}
{102}{}{我真不想今天工作。}
{103}{}{希望我们不会被袭击，或者更糟。}
# attacked by raiders

{104}{}{抱歉，我想我们不需要更多的护卫了。}
{105}{}{抱歉，我们已经满员了。}
# we have enough people for this trip

{106}{}{如果你想找工作，可以去商人市场看看。}
# Merchant Market is a section of town in which people gather.

{107}{}{希望我们能卖光所有东西。}
{108}{}{我等不及要结束了。}
# finish this job.

{109}{}{我们上路吧。}
{110}{}{我准备好大干一场了。}
# i'm ready for some brawling

{111}{}{我们要出发了！}
{112}{}{今天真热啊。}
{113}{}{天啊，我好渴。}
# i am very thirsty

{114}{}{今天星期几？}
{115}{}{一结束我就去猎鹰酒馆！}
# Falcon is short for Maltese Falcon--Drinking and gambling hall

{116}{}{抱歉，我们刚从一条路线回来。}
{117}{}{如果你想找工作，可以去商人市场看看。}
# Merchant Market is a section of town in which people gather.

{118}{}{今天是发薪日！}
{119}{}{我直奔鲍勃那里！}
# Bob's is short for Bob's Iguana Bits -- eating establishment
{120}{}{我今天得还贷款！}
{121}{}{我好累。}
{122}{}{真是漫长的旅程！}

{123}{}{该休息了，我想。}
{124}{}{明天见，各位。}
{125}{}{天啊，昨晚真是疯狂。}
{126}{}{我老了。}

{200}{}{你看到马特。}
{201}{}{明天见，大家。别让臭虫咬你。}
{202}{}{那真是个奇怪的梦。}

{203}{}{是吗？我能为您效劳什么？}
{204}{}{呃？}
{205}{}{这是个什么地方？}
{206}{}{你能告诉我哪里能找到水芯片吗？}
{207}{}{这些货车都在这里做什么？}
{208}{}{哦，抱歉，我以为你是别人。再见。}
{209}{}{是的。你可能会死。}

{210}{}{在荒地待太久了吧？那真不幸。}
{211}{}{这里是枢纽城。它是荒地的贸易中心。我所知道的最大城市，你几乎可以在这里找到任何你想要的东西。如果你在找工作，这里就是你该来的地方。看起来这里的每个人都在找人帮忙，不管是合法的还是非法的。}

{212}{}{你能告诉我哪里能找到水芯片吗？}
{213}{}{这些货车都在这里做什么？}
{214}{}{贸易？你们交易什么？}
{215}{}{我该去哪里找工作？}
{216}{}{再见。}

{217}{}{水芯片？哇，你难住我了。我从没听说过这种东西。也许你应该去市中心的杂货店看看，他们可能能帮到你。}
{218}{}{这些货车都在这里做什么？}
{219}{}{谢谢。再见。}

{220}{}{这些是商队。我们把货物运送到荒地的各个角落。废城、兄弟会、阴影沙地，还有很多其他地方。只有死城和辉光是我们避开的地方。我负责这个商队，我们很快就要出发了。街对面的商队刚刚到达。}
{221}{}{这看起来像是我之前见过的那个商队？}
{222}{}{你们交易什么？}
{223}{}{这是个什么地方？}
{224}{}{我该去哪里找工作？}
{225}{}{谢谢。再见。}

{226}{}{嗯……很多东西。人们生活所需的基本物资，食物、水，很多水。水可能是荒地中最稀缺的商品。}
{227}{}{你能告诉我哪里能找到水芯片吗？}
{228}{}{我该去哪里找工作？}
{229}{}{谢谢。再见。}

{230}{}{你几乎可以问枢纽城里的任何人。或者你可以查看工作公告板，枢纽城里有几个。这里的工作绝对比人多。}
{231}{}{这是个什么地方？}
{232}{}{你能告诉我哪里能找到水芯片吗？}
{233}{}{这些货车在这里干什么？}
{234}{}{谢谢你。再见。}

{235}{}{[笑] 是的，你可以这么说。过了一段时间，它们看起来都差不多。但相信我，它们并不一样。}
{236}{}{你竟敢嘲笑我，你该死！！！}
{237}{}{我该去哪里找工作？}
{238}{}{再见。}

{300}{}{你看到卢克。}
{301}{}{这些是商队。我们把货物运送到废土的各个角落。废城、兄弟会、阴影沙地，还有其他很多地方。我们刚刚回来，旅途漫长。街对面的那组人正准备出发。}

{400}{}{你看到约翰。}
{401}{}{你这么晚在这里干什么？}
{402}{}{你是个白痴。滚开，你这个废物。}
{403}{}{水芯片？我从没听说过这种东西。}
{404}{}{这些是我负责护卫的商队。商人们把货物运送到废土的各个角落，废城、兄弟会、阴影沙地，还有其他很多地方。}
{405}{}{嗯……很多东西。人们生活所需的基本物资，食物、水，很多水。因为水可能是废土中最稀缺的资源。}
{406}{}{你几乎可以问这里集市上的任何人。或者你可以查看工作公告板，集市上有几个这样的板子。}
{407}{}{我是被商人雇来保护这些货物的保安。危险的工作，但报酬不错。就在前几天晚上，我的一个同事在看守商队时被杀了。}
{408}{}{什么是商队？}
{409}{}{啊……[讽刺] 真是个悲惨的故事。你想和你的朋友团聚吗。}
{410}{}{再见。}

