{100}{}{你看到达伦·海塔沃。}
{101}{}{你是谁？！谁让你进来的？}
{102}{}{我带来了一个朋友的消息。}
{103}{}{你的生命有危险，我需要和你谈谈。}
{104}{}{我的名字是}
{105}{}{。是里昂让我进来的。}
{106}{}{我的名字是……死神！}
{107}{}{我是你最可怕的噩梦。}
{108}{}{波波？}
{109}{}{我没有朋友。你的消息是什么？}
{110}{}{德克向你问好。}
{111}{}{嗯……鲍勃让我来的……啊……他说你多给了他100瓶盖，让我来还给你。}
{112}{}{其实没有什么消息，我只是想找个借口脱身。}
{113}{}{我爱你。}
{114}{}{说点我不知道的，白痴！}
{115}{}{白痴？我是在帮你。你可以下地狱了。}
{116}{}{德克想要你死，他雇我来干掉你。}
{117}{}{你显然不知道你马上就要死了！}
{118}{}{算了，我只是想帮忙。}
{119}{}{很高兴见到你}
{120}{}{。现在我的助手里昂会送你离开我的家。}
{121}{}{我不认识什么鲍勃，但我会收下这100瓶盖，你可以走了。}
{122}{}{去死吧！}
{123}{}{好的，给你。感谢你的时间。}
{124}{}{呃……那个混蛋鲍勃没给我足够的瓶盖！我会帮你拿回来的，海塔沃先生，我保证！}
{125}{}{别放在心上。我一直很享受陌生人来我家送钱。里昂，把这个傻瓜送出去！再来一次，我的护卫会取你性命！}
{126}{}{里昂，把这个傻瓜送出去！再来一次，我的护卫会取你性命！}
{127}{}{护卫！刺客！}
