{100}{}{你看到雅各布，武器商人。}
{101}{}{嗨！欢迎来到杰克的店。我这里有一些很棒的商品，随便看看吧。}
{102}{}{我想和你做个交易。}
{103}{}{你在这里卖些什么？}
{104}{}{你能告诉我关于水芯片的事吗？}
{105}{}{告诉我关于你自己的事。}
{106}{}{没事了，再见。}
{107}{}{想要。}
{108}{}{不想要。}
{109}{}{我专营高端武器。这边荒野上最好的货色，兄弟会那边不和外人做生意，所以我得说我是最好的。我有狙击步枪，你很难在其他地方找到火焰喷射器的燃料。哦对了，我还有盖革计数器，非常稀有。}
{110}{}{让我看看你有什么。}
{111}{}{告诉我更多关于狙击步枪的事。}
{112}{}{我需要盖革计数器做什么？}
{113}{}{也许我稍后再来找你。再见。}
{114}{}{伙计，你还真喜欢稀有货！几年前我卖贫铀弹的时候你在哪儿？不过我不做芯片生意，没市场。还有别的需要吗？}
{115}{}{让我看看你有什么。}
{116}{}{那就告诉我你有什么吧。}
{117}{}{告诉我关于你自己的事。}
{118}{}{嗯，我见多识广。以前是原子工人联盟的成员，有点像兄弟会，但不那么友好。他们想自成一派，而我嘛，我想看看世界，自己当老板，所以我离开了。}
{119}{}{让我看看你有什么。}
{120}{}{告诉我你有什么。}
{121}{}{你能告诉我关于水芯片的事吗？}
{122}{}{很高兴认识你，朋友。也许我以后会再来。再见。}
{123}{}{啊，DKS是一把优秀的远程武器。它原本是.308口径，但我们改成了更常见的.223口径。我们也调校了枪管。最重要的是，看看这个扳机。顺滑吧？现在扳机的触发非常完美。总的来说，这是猎杀任何动物的好选择……}
{124}{}{听起来不错。看看我们能不能达成交易。}
{125}{}{我需要盖革计数器做什么？}
{126}{}{也许我稍后再来找你。再见。}
{127}{}{你需要盖革计数器做什么！？[笑] 虽然炸弹落下已经80年了，但辐射仍然存在，你这傻瓜。你看不见，从来都看不见，但它就在那儿。嘿，我敢打赌你现在身上就有一些辐射计数。生活在荒野的人都有一些辐射计数。}
{128}{}{让我看看你有什么卖的。}
{129}{}{告诉我更多关于辐射的事。}
{130}{}{盖革计数器是怎么工作的？}
{131}{}{笨蛋！？你总是这样侮辱顾客吗？如果你以为我现在会从你这儿买东西，那你就大错特错了。}
{132}{}{嗯，有些人称它为“幽灵死神”，因为它就是那样的。你看不见它，听不见它，甚至闻不到它。它基本上会在你的体内积累。你永远不会感觉到它，直到为时已晚。你去辐射区的次数越多，它积累得越多，而且永远不会从你的系统中消失。辐射量会一直增加。除非……你能弄到一些辐射清除剂。}
{133}{}{看看我们能不能做个交易。}
{134}{}{盖革计数器是怎么工作的？}
{135}{}{我在哪里能找到辐射清除剂？我没见过很多地方在卖。}
{136}{}{哇，你知道的真多。听起来你见多识广。}
{137}{}{谢谢你的信息。再见。}
{138}{}{其实很简单。你用它，它会告诉你有多少辐射量。只要保持辐射量在100以下，你就没事。超过100就有麻烦了。最糟糕的是，你甚至不知道自己吸收了辐射，直到几天后才会察觉。超过1000，你就完蛋了——除非你能弄到大量的辐射清除剂。}
{139}{}{看看我们能不能做个交易。}
{140}{}{你能告诉我关于辐射的事情吗？}
{141}{}{我不喜欢这种强买强卖的手段。再见。}
{142}{}{算了。}
{143}{}{}
{144}{}{走吧。}
{145}{}{我要走了。}
{146}{}{是的。}
{147}{}{不，只是随便看看。}
{148}{}{我不想惹麻烦。如果你想做生意，那就来吧。不然的话，走开。}
{149}{}{走吧。}
{150}{}{我要走了。}
{151}{}{让我看看你有什么。}
{152}{}{你可以去死。我想去哪就去哪，想什么时候去就什么时候去！}
{153}{}{我走了。}
{154}{}{你到底在这里干什么！？！？}
{155}{}{我不卖这个。我找到的都留给自己。就在这条街上，有个人可能能帮你。他叫范斯。别问他太多问题。就说这是他的专长。告诉他雅各布让你来的，他会好好招待你的。}
{156}{}{盖革计数器是怎么工作的？}
{157}{}{谢谢你的信息。再见。}
{158}{}{这是我有的东西。}
{159}{}{再见。}
{160}{}{谢谢。}
{161}{}{哦。}
{162}{}{大约十年前，变种人把他们全灭了，所以我想我做出了正确的决定。我最终在这里安顿下来。警察不喜欢我的生意，我也被赶走过不止一次，但我比这里的大多数商人要诚实得多。}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{163}{}{嘿，朋友，最近怎么样？想买点什么吗？}
{164}{}{嘿，朋友，最近怎么样？想买点什么吗？}
{165}{}{你的货不错，但我想找点更有威力的东西。你知道我该去哪儿找吗？}
{166}{}{嗯，你可以去骨园的枪械跑商那里看看，他们可能有适合你的东西。我听说钢铁兄弟会的人也有些相当强力的装备，你也可以去找他们看看。}
