{100}{}{你看到一个矮壮的男人。}
{101}{}{我们不欢迎你这种人在这里。}
{102}{}{你好，陌生人。你看起来像是新来的。你叫什么名字？}
{103}{}{我的名字不重要。}
{104}{}{我叫}
{105}{}{。}
{106}{}{嗯？}
{107}{}{那么，你也不重要。}
{108}{}{很高兴见到你。我叫伊恩。}
{109}{}{你在这里做什么？}
{110}{}{我想了解更多关于这个地方的信息。你能帮忙吗？}
{111}{}{抱歉，我没空浪费在傻瓜身上。}
{112}{}{我曾是集市商人的护卫。不过，我在一次土匪袭击中受了枪伤。我一直待在这里，因为这里的人们帮助我恢复。尽管如此，我对外界的了解和经验在这里很有用。阴影镇现在是我的家。有时，我还会去废城或集市做些交易，因为我是这里唯一真正离开过小镇的人。}
{113}{}{你看到伊恩。}
{114}{}{很遗憾听到你的伤情。}
{115}{}{集市和废城在哪里？}
{116}{}{你能告诉我关于土匪的事吗？}
{117}{}{阴影镇是个小而自给自足的社区。这里唯一的麻烦是土匪和辐射蝎。}
{118}{}{为什么辐射蝎是个麻烦？}
{119}{}{有很多土匪吗？}
{120}{}{有好几个。他们来自不同的团伙。他们偷我们的食物，有时还会打伤几个人。赛斯组织了守卫来帮助抵抗他们。}
{121}{}{你能告诉我关于赛斯的事吗？}
{122}{}{有不同的团伙？他们都是谁？}
{123}{}{辐射蝎非常危险。它们的尾巴有毒刺，而且动作很快。阿拉德什一直在想办法除掉它们。如果你够勇敢，可以去找阿拉德什谈谈。}
{124}{}{谢谢。伤口恢复得不错，多亏了拉兹洛。}
{125}{}{赛斯是个非常勇敢的战士。他偶尔会去辐射蝎洞穴杀掉一些辐射蝎，但它们总是会回来。数量实在太多了，他一个人对付不了。}
{126}{}{辐射蝎真的那么危险吗？}
{127}{}{我能帮你什么忙？}
{128}{}{有三个团伙：可汗、毒蛇和豺狼。他们基本上互相仇恨，但都会袭击阴影镇。}
{129}{}{告诉我更多关于阴影镇的事。}
{130}{}{他站姿自信而放松，显然是个经验丰富的战士。}
# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 131 and 132.
{131}{}{那么，}
{132}{}{，我能为你做些什么？}
{133}{}{告诉我关于掠夺者的事。}
{134}{}{告诉我关于辐射蝎的事。}
{135}{}{告诉我关于阴影沙漠的事。}
{136}{}{告诉我关于赛斯的事。}
{137}{}{你能给我指路去商队城和废城吗？}
{138}{}{没什么，谢谢。}
{139}{}{商队城是阴影沙漠南方的一个大型贸易中心，由几个不同的商队团体管理：水商、深红商队和远行商队。废城在南边稍微偏西一点。虽然小一些，但仍是个喝酒的好地方。由一个叫基利安·黑水的人管理，他是当地的店主、治安官和市长。}
{140}{}{谢谢。}
{141}{}{我可能不再是个很好的战士，但对付你这种人还是绰绰有余！}
# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 142 and 143.
{142}{}{我能为你做些什么，}
{143}{}{？}
{144}{}{嗯，没事。算了，伊恩。}
{145}{}{你可以走了。}
{146}{}{你能给我指路去商队城和废城吗？}
{147}{}{好吧，既然你问了，行吧。回头见。}
{148}{}{不，谢谢。我在这里有事。}
{149}{}{你能帮我一点忙吗？你的经验会很有用。}
{150}{}{走吧。重新行动起来会很不错！}
{151}{}{这是基利安的杂货店。基利安是个好人，他们的货物很充足。}
{152}{}{吉兹莫的赌场。一个赌博和地下活动的温床。小心点，据说那些游戏都是设好的。}
{153}{}{这个地方让我毛骨悚然。}
{154}{}{这里到底发生了什么？}
{155}{}{这将是个难啃的骨头。}
{156}{}{嗯，有点诱人，因为这个地方很无聊。这样吧，标准价。100瓶盖，成交。}
{157}{}{成交。}
{158}{}{不，谢谢。}
{159}{}{不如给我分一杯羹，怎么样？}
{160}{}{好吧，我会帮你，但我要分一杯羹。}
{161}{}{不，我不这么认为。等你有瓶盖再来找我。}
{162}{}{这是武器店，由贝丝经营。她不仅卖枪，还很会八卦。}
{163}{}{杰克的武器店。价格高，但枪真的不错。}
{164}{}{这是水商办公室。他们是集市的大玩家，因为他们供应维持一切运转的水。}
{165}{}{这是赤色商队。我曾为他们工作过。他们接很多高风险的活。}
{166}{}{远行商人，由巴奇·哈里斯经营。如果你懂我的意思，他不太聪明。}
{167}{}{啊，马耳他之鹰是个好去处。音乐好，酒好，朋友也好。}
{168}{}{那真是个丑八怪！}
{169}{}{你说服伊恩加入你的任务，获得100经验值。}
{170}{}{以前听说过这些地方，但从没进去过。看起来不错，很干净……对我来说有点太干净了。}
{171}{}{虽然你没问我，但那人需要给你一点喘息空间。}
{172}{}{你知道，那女人连探戈都不会领，更别说革命了。}
{173}{}{你擅长使用什么武器？}
{174}{}{我几乎能用任何手枪射得很好，也会用冲锋枪。我还会用刀。}

#
# Translation note
# The following line is directed at Katja, a female scavenger, not at the player.
# Ian is noting that he thinks that the Boneyard was a worse place than the
# mutants' military base.
#

{175}{}{我以为骨园更糟。}


{200}{}{下次战斗时拿出你最好的武器。}
{201}{}{当然。}
{202}{}{在我走之前，我能为你做些什么吗？}
{203}{}{嗯，是的。我想我们还是应该在一起。}
{204}{}{呃，不用了，谢谢。}

#
# Ian tell-me-abouts
#

{1000}{}{水}
{1001}{}{战争}
{1002}{}{阴影镇}
{1003}{}{废城}
{1004}{}{集市}
{1005}{}{掠夺者}
{1006}{}{商队}
{1007}{}{芯片}
{1008}{}{沙地}
{1009}{}{追随者}
{1010}{}{大教堂}
{1011}{}{加尔}
{1012}{}{主宰}
{1013}{}{统一体}
{1014}{}{集合}
{1015}{}{水坝}
{1016}{}{死城}
{1017}{}{大厅}
{1018}{}{图书馆}
{1019}{}{监督者}
{1020}{}{医护}
{1021}{}{治疗}
{1022}{}{避难所}
{1023}{}{避难所13}
{1024}{}{避难所13}
{1025}{}{基利安}
{1026}{}{吉兹莫}
{1027}{}{坟场}
{1028}{}{赌场}
{1029}{}{商店}
{1030}{}{死亡爪}
{1031}{}{流亡}
{1032}{}{新兵}
{1033}{}{骑士}
{1034}{}{抄写员}
{1035}{}{孩子们}
{1036}{}{兄弟会}
{1037}{}{熔池}
{1038}{}{军事}
{1039}{}{基地}
{1041}{}{末日启示录}
{1042}{}{变种人}
{1043}{}{莫菲斯}
{1044}{}{汗帮}
{1045}{}{坦迪}
{1046}{}{艾莉娅}
{1047}{}{戴安娜}
{1048}{}{格温}
{1049}{}{佩特罗克斯}
{1050}{}{托利亚}
{1051}{}{酒}
{1052}{}{化学品}
{1053}{}{赛斯}
{1054}{}{阿拉德什}
{1055}{}{拉兹洛}
{1056}{}{齐默尔曼}
{1057}{}{监管者}
{1058}{}{拾荒者}
{1059}{}{刀锋帮}
{1060}{}{妮可}
{1061}{}{中尉}
{1062}{}{心灵感应者}
{1063}{}{实验}
{1064}{}{警察}
{1065}{}{商人}

{1100}{}{不知道水芯片是什么。抱歉，朋友。}
{1101}{}{发生在几十年前。基本上，一些国家变得有些紧张，然后一切都BOOM了！}
{1102}{}{一个小而和平的村庄。可能是废土中最有前途的社区。}
{1103}{}{一个由废料建成的中等规模小镇，由名叫基利安的治安官管理。就在阴影沙漠的西南几天路程。}
{1104}{}{中心城是新西部最大的贸易中心。主要由一个叫水商会的组织管理，但那里也有其他一些商人。这个城市发展迅速，但商人之间的政治斗争很多。}
{1105}{}{外面有几个不同的掠夺者团伙。组织最严密的叫可汗，他们似乎认为自己能征服世界。}
{1106}{}{大多数商队都来自中心城，他们到处旅行。我以前为一个叫赤色商队的组织工作，直到我不幸受伤。}
{1107}{}{不知道什么是水芯片。抱歉，朋友。}
{1108}{}{一个小而和平的村庄。可能是废土中最有前途的社区。}
{1109}{}{抱歉，伙计。不太清楚。}
{1110}{}{抱歉，伙计。不太清楚。}
{1111}{}{加尔是个蠢货，他以为能靠他那帮烂掠夺者征服世界。是啊，随便他吧。}
{1112}{}{抱歉，伙计。不太清楚。}
{1113}{}{抱歉，伙计。不太清楚。}
{1114}{}{抱歉，伙计。不太清楚。}
{1115}{}{抱歉，伙计。不太清楚。}
{1116}{}{那不是传说中的死城吗？}
{1117}{}{抱歉，伙计。不太清楚。}
{1118}{}{抱歉，伙计。不太清楚。}
{1119}{}{抱歉，伙计。不太清楚。}
{1120}{}{拉兹洛是个好医生。如果你受伤了，应该去找他。}
{1121}{}{拉兹洛在治疗方面很在行，他的菌加汁也很值得一试！}
{1122}{}{抱歉，伙计。不太清楚。}
{1123}{}{抱歉，伙计。不太清楚。}
{1124}{}{抱歉，伙计。不太清楚。}
{1125}{}{基利安是废城的市长，他也在那里开了一家店。他是个不错的人。虽然没为他工作过，但他看起来还不错。}
{1126}{}{基莫在废城经营一家赌场。我听说那赌场有猫腻。}
{1127}{}{抱歉，伙计。不太清楚。}
{1128}{}{赌场是基莫在废城的大项目。吸引了很多游客和资金，但也带来了问题。}
{1129}{}{基利安在废城经营着一家不错的杂货店。}
{1130}{}{抱歉，伙计。不太清楚。}
{1131}{}{抱歉，伙计。不太清楚。}
{1132}{}{抱歉，伙计。不太清楚。}
{1133}{}{抱歉，伙计。不太清楚。}
{1134}{}{抱歉，伙计。不太清楚。}
{1135}{}{是啊，阴影沙漠有些孩子。那又怎样？他们可不是我的。}
{1136}{}{抱歉，伙计。不太清楚。}
{1137}{}{抱歉，伙计。不太清楚。}
{1138}{}{抱歉，伙计。不太清楚。}
{1139}{}{抱歉，伙计。不太清楚。}
{1141}{}{你知道的，战争总会存在。只不过下一场战争可能会用棍棒打。}
{1142}{}{我在为集散地护送商队时看到过一些奇怪的东西。变异的土狼、螳螂和蝎子之类的。}
{1143}{}{抱歉，伙计。不太清楚。}
{1144}{}{他们是一群可悲的掠夺者，袭击阴影沙漠，还妄想征服世界之类的。}
{1145}{}{她是阿拉迪什的女儿。她很可爱，但我在家里已经有人等我了。}
{1146}{}{抱歉，伙计。不太清楚。}
{1147}{}{抱歉，伙计。不太清楚。}
{1148}{}{抱歉，伙计。不太清楚。}
{1149}{}{抱歉，伙计。不太清楚。}
{1150}{}{抱歉，伙计。不太清楚。}
{1151}{}{有啤酒吗？}
{1152}{}{我曾在一次商队袭击中用过狂暴药，结果让我很紧张。真奇怪。}
{1153}{}{赛斯是警卫队长。你我之间说，他连钉在腿上的水果都看不住。}
{1154}{}{阿拉迪什是阴影沙漠的领袖。一个善良而有耐心的人，虽然有点疯。}
{1155}{}{嘿，如果你需要帮助，去找拉兹洛。他是个好医生。}
{1156}{}{抱歉，伙计。不太清楚。}
{1157}{}{抱歉，伙计。不太清楚。}
{1158}{}{抱歉，伙计。不太清楚。}
{1159}{}{抱歉，伙计。不太清楚。}
{1160}{}{抱歉，伙计。不太清楚。}
{1161}{}{抱歉，伙计。不太清楚。}
{1162}{}{我不知道。我觉得有点道理，但证据不够。}
{1163}{}{抱歉，伙计。不太清楚。}
{1164}{}{抱歉，伙计。不太清楚。}
{1165}{}{有些商人从枢纽城来废城进行交易。这就是我所知道的全部。}}
