{100}{}{你看到一个追随者杰克。}
{101}{}{你看到一个末日信徒的追随者。}
{102}{}{欢迎，我的朋友！今天有什么我可以帮你的？}
{103}{}{我帮你！我帮你！}
{104}{}{我听说你是个不错的战士。让我们来看看吧。}
{105}{}{我听说你需要帮助。有什么问题？}
{106}{}{你能告诉我关于追随者的事情吗？}
{107}{}{你想帮忙。我觉得你还不够格去帮我。去找尼尔谈谈吧。}
{108}{}{我很想和你打，但我现在忙着帮妮可。}
{109}{}{果然。你看起来就像个懦夫。}
{110}{}{随便你。再见。}
{111}{}{像你这样的懦夫是怎么成为二把手的？}
{112}{}{嘿。只是因为我不想打架并不意味着我是懦夫。我只是没这个心情。}
{113}{}{我说对了。就是个懦夫。}
{114}{}{我们中有些人会用脑子在这个世界上走得更远。很多事情可以通过和平和思考来解决。}
{115}{}{那你什么时候打算用你的脑子呢？}
{116}{}{你说得对。我很抱歉。}
{117}{}{够了。我不想再跟你说话了。}
{118}{}{这样好多了。现在。我这里有个间谍的问题。你愿意帮我吗？}
{119}{}{好的。是什么问题？}
{120}{}{如果你这么厉害，那就自己解决吧。}
{121}{}{我刚才说我们这里有个间谍。我认为可能是某个守卫是间谍。不过也可能是侦察兵。这是唯一两个能接触到孩子们的群体。}
{122}{}{好的。我会去找出间谍并解决问题。}
{123}{}{对这个间谍有什么线索吗？}
{124}{}{算了。我不会帮你。}
{125}{}{非常感谢。现在去吧！}
{126}{}{其实没什么。我唯一知道的是很多低级别的信息正在传给孩子们。这可不妙。希瑟认为可能是尼尔或彼得。}
{127}{}{好的。我会去调查。}
{128}{}{算了。我不会帮你。}
{129}{}{那我不能让你离开。}
{130}{}{那我就告辞了。再见！}
{131}{}{我们的一些信息泄露给了儿童组织。我觉得是有间谍。}
{132}{}{好吧。那么问题是什么？}
{133}{}{好的，我会处理这个间谍。}
{134}{}{有任何线索了吗？}
{135}{}{算了吧。我不会帮你。}
{136}{}{目前我不能告诉你任何事情。祝你有个好日子。}
{137}{}{我在试着睡觉。别打扰我。}
{138}{}{快点找到那个卑鄙的家伙！}
{139}{}{我一直知道是希瑟。她从一开始就不诚实。我应该早点告诉大家我的想法。}
{140}{}{我从来没有从你那里学到任何东西。你的训练毫无用处。}
{141}{}{我有一个加布里尔给你的包裹。}
{142}{}{嗯。我明白了。谢谢。}
{143}{}{滚出去。}
{144}{}{总是难上加难。}
