{100}{}{你看到一个旅行者。}
{101}{}{你想要什么，陌生人？}
{102}{}{你是谁？}
{103}{}{你在这里做什么？}
{104}{}{最近的城镇在哪里？}
{105}{}{没事，谢谢。}
{106}{}{呃……}
{107}{}{我是一个侦察兵。}
{108}{}{我在这里警戒掠夺者和怪物。}
{109}{}{那是废城。从这里不远。}
{110}{}{你看到一个来自废城的守卫。}
