{100}{}{你想要什么？}
{101}{}{你的守卫说你有工作给我。}
{102}{}{我不喜欢你的态度，老头。}
{103}{}{没什么。}
{104}{}{呃。}
{105}{}{也许吧……你以前对付过凶残的盗贼团伙吗？}
{106}{}{别告诉我，你有帮派问题。}
{107}{}{这里到底怎么回事？荒原上有没有不被帮派困扰的地方？}
{108}{}{我处理过几个。}
{109}{}{呃……你以前对付过帮派？}
{110}{}{可以这么说。}
{111}{}{你有什么问题，老头？我不是刚说过我处理过吗？}
{112}{}{没有，我不打算现在开始。再见，先生。}
{113}{}{很好，那你知道他们有多么无情和嗜血。刀锋帮是最糟糕的，我怕。我们是一个谦卑、敬畏上帝的小镇，只想活下去，而这些……这些……怪物……却以我们为猎物……[他低声耳语]还有我们的孩子……}
{114}{}{好吧，好吧，那很棒。工作内容是什么，报酬多少？}
{115}{}{你说的“以你们为猎物”是什么意思？}
{116}{}{为什么不让你的守卫去对付他们？}
{117}{}{嗯，治安官们阻止他们直接攻击我们，但他们只能勉强保护我们的社区。他们试图在夜间潜入杀害我们的市民，或者，绑架我们的孩子……[他停顿了一下，整理情绪后继续]就在上周，有一个人半夜冲破北门，身上绑着炸药，想炸掉治安官的营房……无疑是想削弱我们，以便发动全面攻击。}
{118}{}{他怎么样了？}
{119}{}{这听起来有点极端，不是吗？}
{120}{}{幸运的是，治安官们在他完成计划之前就杀了他。我亲眼看到他的尸体。}
{121}{}{我明白了。你希望我怎么做？}
{122}{}{所以你实际上没有看到这个人带着炸药冲进你的镇子？}
{123}{}{我给你2000瓶盖去杀掉他们的头目！我要那个贱人的脑袋！}
{124}{}{你似乎对她有个人恩怨。}
{125}{}{为什么只杀头目？}
{126}{}{听起来不错。}
{127}{}{没有她……她……邪恶的影响，他们就会瓦解。}
{128}{}{听起来是个有趣的女孩。}
{129}{}{我听够了。我会去做的。}
{130}{}{呃，对。我不想参与这种病态的事情。}
{131}{}{她绑架了我的儿子，折磨并杀害了他。他们把他钉在城门外的柱子上。}
{132}{}{这些变态混蛋……我接下这个任务。}
{133}{}{我想我还是不接这个任务了。}
{134}{}{感谢诸神。终于，我的儿子可以得到复仇了。刀锋帮的营地就在北边。完成任务后回来找我。}
{135}{}{正如我告诉你的，那是半夜。我正在睡觉。幸运的是，治安官通常会在这些野蛮人进入我们镇之前就抓住他们。}
{136}{}{是啊，真幸运。也很方便。}
{137}{}{我不喜欢这一切的感觉。我退出。}
{138}{}{那就滚吧！如果你不帮助阿迪顿，阿迪顿也不需要你！}
{139}{}{我没时间浪费在蠢货身上。滚出去。}
{140}{}{如果你来解决我的问题，我可能会忽略你的评论。}
{141}{}{什么问题？}
{142}{}{什么，你是说你又老又蠢？}
{143}{}{你以前处理过凶残的杀人盗贼团伙吗？}
{144}{}{别告诉我。你有帮派问题。}
{145}{}{这里是什么地方？荒原上有没有不受帮派困扰的地方？}
{146}{}{我处理过几个。}
{147}{}{又一个偏僻小镇的帮派问题！真荒谬！}
{148}{}{方便的做法是彻底结束他们的恶行！}
{149}{}{让我猜猜——你想让他们死。}
{150}{}{我能帮什么忙？}
{151}{}{这里发生的事情比我想知道的要多。我现在要走了。}
{152}{}{什么？！又是你？你现在想要什么？}
{153}{}{我重新考虑了。我接下这个任务，老头。}
{154}{}{我不喜欢你的态度，老头。}
{155}{}{没什么。}
{156}{}{[他警惕地看着你。]……刀锋帮的营地就在北边。完成任务后回来找我，我会给你2000瓶盖。}
{157}{}{你为什么还没解决这个问题？}
{158}{}{我改变主意了。}
{159}{}{我正在处理。}
{160}{}{嘿，老头，退后。}
{161}{}{快点干活。别再来烦我，直到你结束了她那悲惨的生命！}
{162}{}{你做到了吗？！她死了吗？她死了吗？}
{163}{}{你需要帮忙，老头。是的，她死了。}
{164}{}{当然。我让她受尽折磨，算是给你的私人恩惠。}
{165}{}{是的。}
{166}{}{感谢上天！！！这是你的钱。你永远欢迎来阿迪坦，我的孩子。}
{167}{}{她终于尝到了地狱之火的滋味！祝福你，我的孩子。[他擦去一滴泪] 这是额外的500瓶盖，感谢你的额外努力。你永远欢迎来这里。}
{168}{}{你做到了吗？！她死了吗？她死了吗？}
{169}{}{擦掉你嘴边的口水，坐下，老头。我们需要谈谈。}
{170}{}{我有些事情你需要听。}
{171}{}{我受够了你的放肆！她死了没有？！}
{172}{}{来，听这个。}
{173}{}{[当他听着全息磁盘时，他开始颤抖并变得通红。你觉得他可能会因为极度的仇恨而当场死去。] 我要杀了你们这些混蛋！}
{174}{}{你这个混蛋！你把恶魔带到了我们的家！}
{175}{}{你看到一个穿着便服的中年男人。}
{176}{}{你看到阿迪坦的市长乔恩·齐默尔曼。}
{177}{}{是的，你想要什么？}
{178}{}{我有关于你儿子的事情你应该听听。}
{179}{}{没事。}
{180}{}{布洛布。}
{181}{}{你是谁？}
{182}{}{我是乔恩·齐默尔曼，阿迪坦的市长。关你什么事？}
{183}{}{你好。}
{184}{}{很高兴见到你。}
{185}{}{感谢你的所有帮助。}
{186}{}{我儿子现在可以安息了。}
{187}{}{我儿子得到了复仇。}
