{100}{}{他看起来像个经验丰富的守卫。}
{101}{}{你最好在这里小心点。}
{102}{}{这不是个惹麻烦的好地方。}
{103}{}{老实点，我们就不会对你不客气。}
{104}{}{你还不错。}
{105}{}{继续保持。}
{106}{}{今天天气不错，是吧？}
{107}{}{这里是废城。只要你不惹我们，这里是个不错的居住地。}
{108}{}{小心Gizmo和他的一伙人。}
{109}{}{我喜欢我的老板。}
{110}{}{你最好把那东西收起来。废城是个友好的地方，朋友，我们希望保持这样。}
{111}{}{把什么收起来？}
{112}{}{别告诉我该怎么做，废物。}
{113}{}{听起来不错。顺便问一下，这里的武器法律是什么？}
{114}{}{呃，哦。}
{115}{}{你的武器，笨蛋。Killian不会收走你的武器，但你最好把它们放在枪套里。}
{116}{}{哦，抱歉。}
{117}{}{没门！我不会为任何人放下我的枪！}
{118}{}{你最好守规矩，因为这是法律，而我是执法者。把武器收起来，除非是自卫，不要拔出来，这样你就不会和我们这些守卫有麻烦。违反法律，我们会让你回到无序的荒地——生死由你。}
{119}{}{好吧，既然你这么说。}
{120}{}{去你的法律！}
{121}{}{嗯，呃，对我来说没问题。但你最好小心点。}
{122}{}{问得好。除非是自卫，否则不能拔出武器。如果你挑起争斗，那是你的责任。除此之外，你有权携带武器。只是不要无缘无故拔刀或枪。祝你有美好的一天。}
{123}{}{喂你，不能带武器！我不管你小时候是不是被你妈摔过。禁止携带武器。}
{124}{}{嘿！你！你在这里鬼鬼祟祟地干什么？}
{125}{}{没干什么。}
{126}{}{我没有鬼鬼祟祟。我只是喜欢谨慎行事。}
{127}{}{呃。}
{128}{}{不管你在做什么，别在这个镇上做。}
{129}{}{守卫盯着你看了一会儿。你看到他脸上露出认出的表情，然后他拔出了武器。}
{130}{}{好吧，呃，行吧。随便你。只要别做出格的事。}
{131}{}{谢谢，再见。}
{132}{}{当然。我会不顾一切，先生。}
{133}{}{当然。我会不顾一切，女士。}
{134}{}{把武器收起来，否则后果自负！}
{135}{}{好了，警告够了。立刻离开镇子，永远别回来，否则后果自负！}
{136}{}{嘿！你以为你在干什么？}
{137}{}{够了，你完蛋了，伙计。}
{138}{}{你现在麻烦大了……}
{139}{}{你们这些骷髅帮被逮捕了！}
