{100}{}{你看到一个似乎疯狂的袭击者。}
{101}{}{就是这样！别再靠近，否则我就干掉她。我发誓。}
{102}{}{呜哼！}
{103}{}{别这样！}
{104}{}{如果你不放了她，我就杀了你。}
{105}{}{没必要动武。我们可以谈谈。}
{106}{}{什么？你就是想杀我，对吧？记住，这是你的错。}
{107}{}{为什么不呢？她不过是个妓女。}
{108}{}{她和你一样有活下去的权利。}
{109}{}{不，不可能。不是这个贱人。}
{110}{}{你活在哪个世界？在这真实的世界里，血流成河，伙计。如果你不离开，这里就会血流成河。}
{111}{}{我们可以好好谈谈。我能做些什么来帮忙？}
{112}{}{好吧，好吧。我退后。你不用担心我。}
{113}{}{天哪，真好笑。谁说我想要帮助了？}
{114}{}{是你。你劫持这个女人就是在求助。我可以帮你。}
{115}{}{我得想想。给我点时间。}
{116}{}{好吧。别耍花招，否则她就完了。}
{117}{}{男人}
{118}{}{女人}
{119}{}{哦，大男人。来试试吧。不过首先……}
{120}{}{哦，大女人。来试试吧。不过首先……}
{121}{}{别过来……我不想伤害她，但我会的。}
{122}{}{别这样，否则我会伤害你。}
{123}{}{你为什么要伤害她？}
{124}{}{试试看，她先死。你刚才说什么？}
{125}{}{有个洞在你头上，你就很难伤害她了。}
{126}{}{好吧，但你得继续跟我说话。}
{127}{}{什么洞？}
{128}{}{我现在就给你来一个。}
{129}{}{只要你继续说，我就继续听，但要是耍花招，她就完了。}
{130}{}{我什么都不需要做。是你得去做，但你做得不怎么样。}
{131}{}{她嘲笑我。他们都嘲笑我。我发誓我要让他们付出代价。}
{132}{}{我信任你。我们一起解决这个问题，好吗？}
{133}{}{也许吧。我不知道。}
{134}{}{伙计}
{135}{}{姑娘}
{136}{}{你听起来是个不错的伙计。以前从来没有人愿意帮我。我想我们可以再聊聊。}
{137}{}{你听起来是个不错的姑娘。以前从来没有人愿意帮我。我想我们可以再聊聊。}
{138}{}{别管我。我恨你！你就是个恶魔。我不会听你的。}
{139}{}{随你的便。}
{140}{}{你必须听我说。你的命，还有那个女孩的命，都取决于此。}
{141}{}{放轻松。我不会伤害你。我只是想听听你要说什么。}
{142}{}{你又来了，威胁我。去死吧！！}
{143}{}{我不会听你的。你只是想用花言巧语骗我。我不相信你。走开。}
{144}{}{你可能有道理。证明给我看。}
{145}{}{接下来我们该怎么办？}
{146}{}{你告诉我。你说了算。}
{147}{}{我想要点钱，然后平安离开这里。没人跟踪我。}
{148}{}{抱歉，我们做不到。}
{149}{}{当然。}
{150}{}{没有钱，但你可以直接走。没人会动你。我保证。}
{151}{}{可以，但你得先放了那个女孩。给我点信任，我也会信任你。}
{152}{}{你骗了我！}
{153}{}{好。我想要100美元。然后我们走出这里。没人跟踪我，到镇边时我就放了她。}
{154}{}{这是你的钱。}
{155}{}{我身上没有那么多钱。}
{156}{}{那我想她就得倒霉了。}
{157}{}{那也行，我想。}
{158}{}{我不喜欢这样。你怎么保证我走出这里时你不会从背后开枪？}
{159}{}{我不会开枪的。相信我。}
{160}{}{没什么，你只需要相信我说的话。}
{161}{}{不可能！我不信任你！}
{162}{}{好吧。我们拭目以待。}
{163}{}{给你100美元。祝你有个好日子。}
{164}{}{你可以和平离开。}
{165}{}{我要我的钱。我想要200美元。}
{166}{}{我钱不够。}
{167}{}{给你。}
{168}{}{在我看来你就是个骗子。}
{169}{}{彼此彼此，伙计。放了那个女孩。}
{170}{}{男人}
{171}{}{女人}
{172}{}{为什么不来找我，看看真正的男人能做什么。}
{173}{}{为什么不来找我，看看真正的女人能做什么。}
{174}{}{不！别告诉我该怎么做！你不能命令我！}
{175}{}{是的，我会让你看看。}
{176}{}{你刚刚害死了这个妓女！}
{177}{}{别烦我，见鬼！}
{178}{}{劫匪专注于他的事情，忽视了你。}
{179}{}{嗯。。。}
{180}{}{嘿，宝贝，来玩玩吧。我有钱，只要你有时间。}
{181}{}{别这样跟我说话，贱人！没人敢这样跟我说话！}
{182}{}{这会让你丢掉性命！}
{183}{}{你精准的一击将劫匪打晕，他像个破布娃娃一样倒下。}
{184}{}{如果你小心点，或许能悄悄接近劫匪。}
