{100}{}{你看到凯莉。}
{101}{}{你是谁？如果想找工作，去找德米特谈。}
{102}{}{我说了，要找工作去找我爸，不是我。}
{103}{}{所以，那老家伙同意让你为我们工作了，是吧？那你一定是个硬汉。我很佩服，不过还得看看你的表现。我们每月只在3号和17号出发。你能应付吗？我们去所有当地的热门地点：钢铁兄弟会、废城、死城和墓园。}
{104}{}{所以，那老家伙同意让你为我们工作了，是吧？那你一定胆识过人。我很佩服，不过还得看看你的表现。我们每月只在3号和17号出发。你能应付吗？我们去所有当地的热门地点：钢铁兄弟会、废城、死城和墓园。}
{105}{}{工资呢？}
{106}{}{呃。}
{107}{}{我们的工资是最高的，600纸币，是单程的价格，但你不必两趟都做。这趟商队旅程相当艰难，几乎肯定会遇到一些袭击者或更糟的情况。我的商队不欢迎胆小鬼，你最好准备充足的弹药。}
{108}{}{我们今天就要出发。你有兴趣吗？}
{109}{}{我们出发在}
{110}{}{空}
{111}{}{空}
{112}{}{。你有兴趣吗？}
{113}{}{我们今天都要出发。}
{114}{}{我们要在}
{115}{}{}
{116}{}{}
{117}{}{你有兴趣吗？}
{118}{}{如果你有兴趣，我还是会给你这个工作。}
{119}{}{当然。}
{120}{}{不。}
{121}{}{我觉得我对你感兴趣。}
{122}{}{可能吧。}
{123}{}{呃。}
{124}{}{哈，我以为你是个胆小鬼！如果你鼓起勇气，过来找我，我可能还会给你工作。我们在3号和17号出发，如果你愿意，可以那天直接来。我们总是需要更多的枪手。}
{125}{}{你就是喜欢浪费我的时间，对吧。}
{126}{}{随便。如果你想找点刺激，回来找我，我会给你安排下一趟商队。}
{127}{}{嘿！我知道这里能搞到好药，但我不能雇你，除非你清醒。}
{128}{}{我说了，别碰药，伙计！}
{129}{}{我说了，别碰药，臭娘们！}
{130}{}{哎呀，我不想承认，但我听说过你。你在私下里也像在公众面前一样强悍吗？让我们看看吧。（她带你绕到角落）}
{131}{}{（回来的路上，她偷偷给了你一些东西。）}
{132}{}{嗯，你还真能坚持一段时间。}
{133}{}{嗯，你很有趣，而且和大多数人非常不同，来让我看看你的本事吧，硬汉。（她带你绕到角落）}
{134}{}{（回来的路上，她偷偷给了你一些东西。）}
{135}{}{嗯，你还真能坚持一段时间。}
{136}{}{嘿，老爹，看起来我们这里有个小偷！你有什么话要说，混蛋？}
{137}{}{对不起。我再也不会这样做了。}
{138}{}{有本事就来抓我啊}
{139}{}{我不喜欢安静！来抓我啊！}
{140}{}{（点头表示同意）}
{141}{}{OOOGABOOOGA！！！}
{142}{}{嘿，老爹，这个蠢货上次没学到教训。她又想偷我的东西。让我们揍她一顿。}
{143}{}{嘿，老爹，这个蠢货上次没学到教训。他又想偷我的东西。让我们揍他一顿。}
{144}{}{我知道偷东西的诱惑很大，但我给你个机会。别再在这里露面，我就不报警。现在滚吧。}
{145}{}{哦，我们会确保这一点，对吧，老爹？}
{146}{}{去死吧！}
{147}{}{我想是吧。}
{148}{}{你死定了。}
{149}{}{我说过滚出去！}
{150}{}{警察！}
{151}{}{抱歉，我们不再和你交易。}
{152}{}{这里没有工作，滚吧。}
{153}{}{别惹我生气。}
{154}{}{白痴。}
{155}{}{有趣，但你不是我的菜。}
{156}{}{很好。就像我之前说的，我们支付600筹码。你想走哪条路线？}
{157}{}{酷。下一个出发时间是}
{158}{}{。到时候回来，我会安排你上商队。和往常一样，报酬是600筹码。}
{159}{}{好的。}
{160}{}{抱歉，我不能等那么久。}
{161}{}{我真想把你吊起来！因为你，我们损失了一整个该死的商队！滚出我面前！这次我要背大锅了。}
{162}{}{我真想把你吊起来！因为你，我们损失了一整个该死的商队！滚出我面前！这次我要背大锅了。}
{163}{}{钢铁兄弟会}
{164}{}{废城}
{165}{}{死城}
{166}{}{骨园}
{167}{}{算了，我还有点事要做。}
{168}{}{准备好，我们要离开这个鬼地方了！}
{169}{}{如果有什么好玩的事发生，告诉我一声，老爸让我待在仓库。}
{170}{}{太好了！其他疯子们也准备好了。我们马上出发。}
{171}{}{酷，我需要几分钟把疯子们聚集起来。}
{172}{}{钢铁兄弟会，我们来了！虽然我不跟你去，但你懂我的意思。}
{173}{}{好了，快走吧。那些兄弟会的狂热分子在等你。}
{174}{}{希望你喜欢山地！你将直接进入那里。应该会有很多行动。}
{175}{}{准备好了，你将直接穿越山脉！这会很刺激！}
{176}{}{废城挺平静的。我更喜欢危险的路线。}
{177}{}{听说那里有个疯狂的医生，你应该去看看。他叫莫比德医生。}
{178}{}{去废城是个短途旅行，你很快就会回来。}
{179}{}{小心点，死城不是个友好的地方。}
{180}{}{赛特是这个镇的领袖。至少我上次去的时候是。}
{181}{}{那镇子满是流浪汉！好吧，我得让你出发了。}
{182}{}{洛杉矶挺酷的。你会喜欢的，但一定要等商队到达后再离开。对商队来说不太安全。}
{183}{}{希望你有机会看看，那里南边几英里还有个很酷的教堂。不过那的人有点怪。}
{184}{}{据说骨园以前叫洛杉矶。我不知道那个人的缩写代表什么，但那地方很酷。}
{185}{}{你到底想要什么？}
{186}{}{闭嘴，滚开，我没心情！}
{187}{}{我想要另一份工作。}
{188}{}{没什么。}
{189}{}{扎格。}
{190}{}{呃。}
{191}{}{是啊对！这样你就可以再抛弃一个商队了？你真幸运，他们居然能安然无恙地到达。}
{192}{}{我幸运？你应该庆幸我没揍扁你的脸！}
{193}{}{嘿！我有地方要去，还有事情要做！}
{194}{}{嘿！你没说我不能离开！又不是他们正在战斗中。}
{195}{}{滚开！你让我恶心！这就是你离开商队的原因？我敢打赌你是嗑药了！}
{196}{}{是吗？那你现在就去吧！你永远从我们的名单上除名了。}
{197}{}{什么？你以前没做过商队工作？真不敢相信我爸居然会雇你！滚吧！我们只雇佣有经验的人员！这就是为什么我们支付高薪！}
{198}{}{你上次的工作干得不错。你在找新的工作吗？}
{199}{}{当然。}
{200}{}{不。}
{201}{}{可能吧。}
{202}{}{呃。}
{203}{}{笨蛋。}
{204}{}{准备好了吗？我们今天出发。}
{205}{}{准备好了！}
{206}{}{还没。}
{207}{}{嗯？}
{208}{}{你来早了一天。如果你还想要这份工作，明天再来。如果不想，就别来。我才不在乎。}
{209}{}{嘿，你来早了。我不会派他们出去直到}
{210}{}{3号}
{211}{}{17号}
{212}{}{。如果你还想要这该死的工作，那时候再来。我真的不在乎你来不来。但如果你还想要，就那时候再来。}
{213}{}{还没。}
{214}{}{爸，闭嘴！}
{215}{}{嘿，老头，我饿了！我要休息一下！}
{216}{}{我讨厌做账。}
{217}{}{一月}
{218}{}{二月}
{219}{}{三月}
{220}{}{四月}
{221}{}{五月}
{222}{}{六月}
{223}{}{七月}
{224}{}{八月}
{225}{}{九月}
{226}{}{十月}
{227}{}{十一月}
{228}{}{十二月}
{229}{}{你得到3个化学药品包。}
