{100}{}{骑士}
{101}{}{我喜欢研究新的原型。}
{102}{}{当我们的物资有限时，找到利用现有资源的方法确实是个挑战。}
{103}{}{我搞不懂为什么我最后的原型没能成功。}
{104}{}{抱歉，我现在没空聊天。}
{105}{}{Vree就在那边。}
{106}{}{我把那个文件放哪了？}
{107}{}{那个原理图在哪？}
{108}{}{嗯，电脑显示应该能行。那我到底哪里出错了？}
