{100}{}{你看到一个巨大的变种人。}
{101}{}{站住！你无法逃脱！}
{102}{}{你不应该在这里。这片区域禁止儿童进入。}
{103}{}{为什么？这里是什么地方？}
{104}{}{我有终极通行证。见识一下我的枪吧！}
{105}{}{哼。}
{106}{}{你太笨了，根本不像个儿童。你一定是入侵者！}
{107}{}{这是囚犯牢房。在这里我们关押人类，直到把他们浸泡。不错吧？}
{108}{}{什么是浸泡？}
{109}{}{好的，谢谢。}
{110}{}{你需要离开。}
