{100}{}{你看到一个骑士。}
{101}{}{你好，新兵。我是拉里，有什么我能帮你的吗？}
{102}{}{维瑞说你可以给我看看激光手枪？}
{103}{}{维瑞说你可以给我一把激光手枪。}
{104}{}{呃。}
{105}{}{呃，好吧...}
{106}{}{呃，是的。这些东西很棒。它的射程...嗯，只要你能看到的地方。（拉里继续讲了似乎几个小时，但你似乎学到了一些关于能量武器的使用。）}
{107}{}{什么？但她知道这些还没准备好...哦，她一定是说展示。是的，我可以给你看看。你看，它是用能量电池驱动的，这些电池是由...（拉里继续讲了似乎几个小时，但你似乎学到了一些关于能量武器的知识。）}
{108}{}{当然她说过。我觉得你应该离开，外来者。}
{109}{}{我不喜欢撒谎的人，请离开。}
{200}{}{这完全不对。}
{201}{}{搞定了。}
{202}{}{发射机制总是卡住。}
{203}{}{好多了。}
{204}{}{快搞定了。}
{205}{}{这会需要一段时间。}
{206}{}{这就是问题所在！}
{207}{}{约翰，我想我找到了问题所在。}
{208}{}{该死！}
{209}{}{糟糕！}
{210}{}{是我的错！}
{211}{}{我没事。}
{212}{}{好吧，这很疼。}
{213}{}{我故意的。}
{214}{}{为什么总是这样？}
{215}{}{我的眼睛！}
{216}{}{你不是骑士。}
{217}{}{我需要和骑士谈谈。}
{218}{}{我不明白，电池总是短路。}
{219}{}{你最好站远一点，这些可能很危险。}
{220}{}{请不要打扰我。}
{221}{}{注意你站的位置。}
{222}{}{你迷路了吗？}
{223}{}{抱歉，我现在不能说话。}
{300}{}{能量武器技能提升5%。}
