{100}{}{这台计算机保存了大量大战前的信息。}
{101}{}{你使用了避难所的计算机教学系统。}
{102}{}{你在避难所的计算机教学系统上花了一些时间，但没有学到重要的东西。外面的世界才是你的老师。}
{103}{}{你花了一些时间研究了一些重要的信息。}
{104}{}{你在网络上闲逛了一段时间，没有做任何重要的事情。}
{105}{}{你稍微摆弄了一下计算机，但需要一些科学技能才能从终端中获取有用的信息。}
