{100}{}{你看到一个黑发的年轻女子。}
{101}{}{你看到洛琳，一个来自阿迪顿的拾荒者。}
{102}{}{嗨，你是新来的吗？}
{103}{}{是的，你能给我介绍一下吗？}
{104}{}{是的，我是。我叫}
{105}{}{。}
{106}{}{什么？}
{107}{}{我想是吧。你想了解什么？}
{108}{}{你是谁？}
{109}{}{你能给我一些关于骨园的信息吗？}
{110}{}{告诉我一些关于阿迪顿其他居民的事情。}
{111}{}{你是做什么工作的？}
{112}{}{没事，谢谢。}
{113}{}{我是洛琳。}
{114}{}{我可以问你几个问题吗？}
{115}{}{我是个拾荒者。我和萨玛尔一起从废墟中收集物资，用来建造或交易。}
{116}{}{为什么这里不是每个人都这样做？}
{117}{}{这里有多少拾荒者？}
{118}{}{我可以问你其他事情吗？}
{119}{}{很高兴和你聊天。}
{120}{}{外面有死亡爪，还有监管者会抽成，再加上在阿迪顿的保护费。估计大家没有足够的现金，或者没有勇气直面死亡爪。}
{121}{}{监管者是怎么回事？}
{122}{}{你们怎么避开死亡爪的？}
{123}{}{我可以问你其他事情吗？}
{124}{}{谢谢，再见。}
{125}{}{哦，我们有六个人。萨玛尔是第一个，也是最厉害的。}
{126}{}{我可以问你其他事情吗？}
{127}{}{有趣，谢谢。}
{128}{}{他们在这里维持和平，控制所有进出的资金。这里的其他人基本上都为监管者工作，那不是最宽容的工作。很多人从未看到围绕这个地方的围栏之外。}
{129}{}{这一切让人不禁想知道朱莉安娜在想什么。}
{130}{}{你指的是关于朱莉安娜的事吗？}
{131}{}{真糟糕。我可以问点别的事吗？}
{132}{}{谢谢你的提醒。}
{133}{}{哦，她前阵子爱上了一个刀锋帮的人。可怜的姑娘当然不能离开小镇，而卡莱布见到那个年轻人就会杀了他。真是悲剧。}
{134}{}{呃……如果你这么说的话。}
{135}{}{我可以问些其他问题吗？}
{136}{}{嗯，谢谢你告诉我这些。再见。}
{137}{}{我们只在晚上去废土拾荒。而且我们很擅长这事。萨玛尔有个小测试，他喜欢在让人加入拾荒者之前考验他们。}
{138}{}{是什么测试？}
{139}{}{听起来还是很危险。}
{140}{}{我明白了。介意我们回到之前的话题吗？}
{141}{}{有趣。再见。}
{142}{}{萨玛尔让人在白天藏在阿迪顿的某个地方。如果他一个小时内找不到这个人，就让他加入下次的拾荒队伍。}
{143}{}{真是个愚蠢的系统！}
{144}{}{看起来挺有效的。你还活着。}
{145}{}{嗯。我可以问你其他事情吗？}
{146}{}{有趣。再见。}
{147}{}{拜托，你心里就没有一点浪漫情怀吗？真遗憾。单相思什么的，真是悲剧。}
{148}{}{哼，看来你知道得不多。去告诉萨玛尔吧。如果你能找到他的话。}
{149}{}{是的，虽然有点艰难。这很危险，尤其是被抓住的话。}
{150}{}{毫无疑问。我可以问点别的事吗？}
{151}{}{谢谢你的信息。}
{152}{}{哇，我想你有点超出我的能力范围了。}
{153}{}{这里曾经是个大城市，叫洛杉矶。但炸弹袭击得很厉害。现在，只剩下天使坟场。我们阿迪顿人只是想在废墟中生存。}
{154}{}{你能多告诉我一些关于洛杉矶的事吗？}
{155}{}{我明白了。谢谢。}
{156}{}{这里住过很多人。据我所知，幸存者藏在一个叫避难所的大地方，几年后才出来。他们中的一些人成立了监管者，然后建立了阿迪顿，而}
{157}{}{其他人则组成了刀锋帮。枪械商人原本不是来自这里。}
{158}{}{这个避难所在哪里？}
{159}{}{监管者是怎么回事？}
{160}{}{枪械跑商来自哪里？}
{161}{}{}
{162}{}{谢谢你的帮助。}
{163}{}{嗯，据说他们来自这里南边的某个地方，但我不太清楚。我想大家都离开了，因为那里已经废弃了。}
{164}{}{我可以再问你一些问题吗？}
{165}{}{嗯，谢谢。}
{166}{}{我不太确定。我想他们来自这里北边的某个地方。}
{167}{}{你对治安官了解多少？}
{168}{}{我可以问些其他事情吗？}
{169}{}{谢谢你的信息。}
{170}{}{你想了解谁？}
{171}{}{乔恩·齐默曼。}
{172}{}{卡莱布。}
{173}{}{迈尔斯。}
{174}{}{泰恩。}
{175}{}{史密蒂。}
{176}{}{没有人。}
{177}{}{齐默曼负责管理我们的城镇。他确保每个人都有饭吃，并且每个人都有工作。}
{178}{}{卡莱布是治安官的领袖。他的职责是保护阿迪特姆。他似乎有点过于享受这份工作。}
{179}{}{啊，我们的驻地化学家。迈尔斯制造子弹，他还建造了水蒸馏器，确保我们从井里得到干净的水。他现在正在研究一个地下农场，但他缺少一些零件。}
{180}{}{泰恩经营商店。就在靠近大门的掩体里。他为我们与集散地的商人进行交易。}
{181}{}{嗯，史密蒂算是个修理工。他擅长修理工作。他铸造子弹并修理镇上的破损物品。}
{182}{}{我可以问问其他人吗？}
{183}{}{我们可以谈论其他话题吗？}
{184}{}{}
