{100}{}{你看到莱尔。}
{101}{}{所以你就是那个偷水贼！你这个叛徒！}
{102}{}{我真高兴这场磨难终于结束了。谢谢你。}
{103}{}{你好，}
{104}{}{。}
{105}{}{你好，莱尔。你最近怎么样？}
{106}{}{我们这里还算过得去。但我希望你能尽快找到水芯片。大家都很紧张，我们的时间不多了。}
{107}{}{哇——！}
{108}{}{不太好。自从前几天我的一份水配给被偷后，事情就一直在走下坡路。大家都很害怕，不知道该怎么办。}
{109}{}{那真是太糟糕了。希望情况能好转。}
{110}{}{我会看看能做些什么。}
{111}{}{是啊，我也希望如此。}
{112}{}{谢谢。我真希望你能查明真相。请尽快找到新的水芯片。如果我们有一个正常的芯片，这些疯狂的事根本不会发生！}
{113}{}{谢谢你抓住了那个小偷。你做得很好。但请尽快找到芯片，否则一切都无济于事！}
{114}{}{你怎么能这样背叛我们？别来烦我！}
