{100}{}{我真不敢相信你做的那些事情。}
{101}{}{我不在乎。我受伤了，治好我。}
{102}{}{嗯哼！}
{103}{}{不。我发誓不伤害生命，但我也不会帮助你。}
{104}{}{缺乏智力不是你所做之事的借口。走开，我不想再和你说话。}
{105}{}{哦天哪，你伤得很重。来，让我帮你。}
{106}{}{欢迎回来，}
{107}{}{。搜寻进展如何？}
{108}{}{还不错。}
{109}{}{我需要帮助。}
{110}{}{哈哈？}
{111}{}{啊，是的。我找到了这些。需要时试试它们。}
{112}{}{很好，继续保持。如果需要什么，告诉我。}
{113}{}{我能为你做些什么？}
{114}{}{我需要治疗。}
{115}{}{我需要一些药物。}
{116}{}{我需要更多的治疗针。}
{117}{}{哎呀！}
{118}{}{呃！}
{119}{}{我没有授权给你。抱歉。}
{120}{}{无论如何，谢谢。}
{121}{}{我急需这些药物。没有它们，避难所的安全将受到威胁。}
{122}{}{抱歉，我不能给你。}
{123}{}{嗯，既然你这么说了。但别告诉别人我给了你这些。它们会让人上瘾，使用时很危险。}
{124}{}{谢谢。}
{125}{}{治疗针正在配给中。你可以从墙上的医疗箱中取用。需要多少拿多少，但请节约使用。我们需要一段时间才能再补给。}
{126}{}{嗯，让我看看你是否受伤。}
{127}{}{我看你没事。如果需要治疗，回来找我。}
{128}{}{你看起来受伤了。来，我帮你。}
{129}{}{如果需要治疗，来找我或者使用我们的治疗针。你可以从墙上拿更多的治疗针。}
{130}{}{请躺下，我们将开始治疗过程。}
{131}{}{你已经完全康复。以后要多加保重，如果需要更多治疗，欢迎再来。}
{132}{}{医疗扫描仪检测到致命的辐射中毒。你希望我们尝试治疗吗？这将需要一些时间。}
{133}{}{医疗扫描仪检测到严重的辐射中毒。你希望我们尝试治疗吗？这将需要一些时间。}
{134}{}{医疗扫描仪检测到较重的辐射中毒。你希望我们尝试治疗吗？这将需要一些时间。}
{135}{}{医疗扫描仪检测到轻微的辐射中毒。你希望我们尝试治疗吗？这将需要一些时间。}
{136}{}{你看到13号避难所的医生。}
{137}{}{}
{138}{}{不。}
{139}{}{好的，开始吧。}
{140}{}{需要多长时间？}
{141}{}{需要多长时间，你们能去除多少辐射？}
{142}{}{不。}
{143}{}{是。}
{144}{}{这是你的身体。}
{145}{}{这将需要}
{146}{}{分钟。你想开始治疗吗？}
{147}{}{不。}
{148}{}{是。}
{149}{}{这将需要}
{150}{}{分钟。可以去除大约}
{151}{}{百分比。你想开始治疗吗？}
{152}{}{不。}
{153}{}{是。}
{154}{}{这会非常非常痛苦。}
{155}{}{好的，这应该一点都不痛。}
{156}{}{好了，你应该感觉好多了。外出时要小心。}
{157}{}{我听说了你拯救避难所的事。谢谢你。}
{158}{}{[更多]}
{159}{}{医生拒绝与你交谈。}
{160}{}{请不要这样做。}

# Medic tell-me-abouts

{1000}{}{医护人员}
{1001}{}{治疗}
{1100}{}{我随时都在这里，为您提供帮助和治疗。}
{1101}{}{如果您受伤了，我可以为您治疗。}
