{100}{}{你看到迈克尔。}
{101}{}{嗯，我想这就是问题所在。你应该去找医生，她在二层。}
{102}{}{据我所知，你没事。}
{103}{}{储藏室不对外开放，我的孩子。只有我和另外两个人可以进入。如果你需要什么东西，得跟我说。}
{104}{}{储藏室不对外开放，女士。只有我和另外两个人可以进入。如果你需要什么东西，得跟我说。}
{105}{}{你没听到我说的吗？我说房间不对外开放。}
{106}{}{你好，兄弟。我能帮你什么忙？}
{107}{}{请原谅我的冒昧，你在兄弟会中负责什么工作？}
{108}{}{你在这里做什么？}
{109}{}{我受伤了。你能治愈我吗？}
{110}{}{乌拉克·楚法！}
{111}{}{抱歉，我不明白你想要什么。如果你需要物资，你需要有授权。}
{112}{}{塔加·马。}
{113}{}{卡鲁！}
{114}{}{我还是不明白你。也许你需要去找医生，她在二层。}
{115}{}{你应该去找医生。她在二层。}
{116}{}{哦，没什么像我们圣骑士那样光荣的。我只是管理储藏室，负责给人们分发设备和其他物资。}
{117}{}{我是...鲍勃派来的。他让我给他拿...那个新的高科技武器。他说要我马上带过去。}
{118}{}{我想借点东西。该怎么做？}
{119}{}{哦，那不错。再见。}
{120}{}{[撒谎失败] 鲍勃？哪个鲍勃？你在说什么？什么新高科技武器？我需要更具体的信息，而且你必须让那个人给我提供适当的授权。没有授权我不能给任何东西。}
{121}{}{[撒谎成功] 哦，你是说激光手枪？好的，请稍等。我没有收到任何来自鲍勃的授权来给任何人激光枪。哦，等一下。我明白了。楼下那些女孩真觉得自己很搞笑，不是吗？我希望她们别再打扰我了。}
{122}{}{嗯，你知道的。她们告诉我不要告诉你，但只是因为她们很喜欢你。我想其中一个对你有好感。}
{123}{}{抱歉，我不知道她们在搞什么鬼。她们让我上来告诉你这个，说你会觉得很有趣。}
{124}{}{对不起，这是个糟糕的玩笑。我只是跟你开个玩笑。}
{125}{}{[撒谎失败] 你又来了！别再折磨我了！她们太残忍了！我真不敢相信你会跟她们同流合污。我们这些家伙应该团结一致。}
{126}{}{你在撒谎！你和她们是一伙的。你怎么能这么残忍？}
{127}{}{[撒谎成功] 真的吗？你不会又在骗我吧？不，你看起来是个好小伙。她们可能是逼你这么做的。你知道，我在训练时看到拉拉看着我。我打赌是她，对吧？}
{128}{}{是的，你说对了。就是她。别告诉她我告诉你的。她会杀了我的。}
{129}{}{不，对不起。我只是跟你开玩笑。没有人派我来。}
{130}{}{你又来了！别再折磨我了！你们女人真是太残忍了！}
{131}{}{[成功撒谎] 真的吗？你不会又在捉弄我吧？不，你看起来像个好姑娘。他们可能是逼你这么做的。你知道，我在训练的时候看到拉拉看着我。我敢打赌是她，对吧？}
{132}{}{没错，就是她。别告诉她是我说的，她会杀了我的。}
{133}{}{不，对不起。我只是跟你开玩笑。没有人让我来这里。}
{134}{}{嗯，我不知道该说什么。我一直对她有点好感，但我不敢行动，因为我不知道她是否也有同样的感觉。下次见到她，我想我会约她出去。也许我会试着和她一起巡逻，然后给她一个浪漫的晚餐惊喜。非常感谢。你真的让我今天很开心。来，拿着这些。你应该能用得上。这些是脉冲手雷，对付机器人非常有用。希望你永远不需要用到它们。再见。}
{135}{}{你这样说可不太好。为什么要说这种不是真的话呢？有些人真是的！}
{136}{}{哦。你的幽默感真奇怪。好吧，除非有事情要检查，否则别来打扰我。}
{137}{}{哦，那些女孩总是给我找麻烦。我不知道她们为什么要这样做。那个拉拉真可爱。我喜欢她已经有一段时间了。我认识她的时候她还小。她那时候真是个小可爱。现在她长大了，却对我这么刻薄。我从来没做过什么值得这样对待的事。}
{138}{}{嗯，也许她喜欢你。你有没有想过这个？她可能只是不知道怎么接近你。你应该问问她。如果你真的喜欢她，有什么可失去的呢？}
{139}{}{也许她喜欢你。}
{140}{}{呃，是的。好吧。再见。}
{141}{}{你知道，你说得对。我有什么可失去的呢？下次见到她，我想我会约她出去。也许我会试着和她一起巡逻，然后给她一个浪漫的晚餐惊喜。非常感谢。你真的让我今天很开心。来，拿着这些。你应该能用得上。它们是灵活性增强剂。小心使用，因为它们可能会让你产生依赖。再见。}
{142}{}{不，这不太可能。女人有时候真让我困惑。我能读懂任何新的图纸，但一涉及到女人，我就完全不知所措。还是谢谢你。}
{143}{}{不，这不太可能。你们女人有时候真让我困惑。我能读懂任何新的图纸，但一涉及到女人，我就完全不知所措。还是谢谢你。}
{144}{}{你需要有适当的授权。只有特定的人可以授权从供应室借出物品。}
{145}{}{哦。好的，谢谢。那么我需要找谁呢？}
{146}{}{我已经获得了授权来借出一些东西。你能检查一下终端看看是否已经通过了吗？}
{147}{}{谁能给我授权？}
{148}{}{嗯，实际上有不少人可以；但塔勒斯是你应该找的人。你也可以去找玛西亚，她可能也能帮你。}
{149}{}{玛西亚在哪里？}
{150}{}{塔勒斯在哪里？}
{151}{}{好的，谢谢。}
{152}{}{玛西亚是马克森的助理。她实际上是高阶长老的助理，但她和其他长老们一起工作。她通常在长老们的房间里。那在四楼。}
{153}{}{好的。塔勒斯在哪里？}
{154}{}{好的。谢谢。再见。}
{155}{}{哦，他在我左边的训练室里。}
{156}{}{太好了。那你能告诉我玛西亚在哪里吗？}
{157}{}{玛西亚呢。}
{158}{}{谢谢。以后再聊。}
{159}{}{是的，白天她通常在长老们的房间里。那在四楼。}
{160}{}{谢谢。你帮了大忙。}
{161}{}{好了，这是你有授权的化学药品。小心使用。用多了可能会上瘾。解毒和休息可不是什么好玩的事，不过我想它们基本上是一样的。使用风险自负。还有什么我可以帮你的吗？}
{162}{}{没有了，谢谢。}
{163}{}{是的，我还有其他东西要取。}
{164}{}{好了，这是你想要的化学药品。这东西很有用，我相信它会派上用场。你还需要别的东西吗？}
{165}{}{没有了，谢谢。}
{166}{}{是的，我还有其他东西要取。}
{167}{}{好的，我这里有一些。子弹永远不嫌多，对吧？给你。还有别的需要吗？}
{168}{}{没有了，谢谢。}
{169}{}{是的，我还有其他东西要取。}
{170}{}{哦，这些东西真的很危险。确保在它们爆炸时你离得足够远。给你。还有别的需要吗？}
{171}{}{没有了，谢谢。}
{172}{}{是的，我还有其他东西要取。}
{173}{}{啊，没有什么比身边有一把好武器更安心的了。还有别的需要吗？}
{174}{}{没有了，谢谢。}
{175}{}{是的，我还有其他东西要取。}
{176}{}{最好的防御就是进攻。或者是反过来？算了，无所谓。这是你的护甲。一定要好好保管。我不能再给多一套。还有其他需要的吗？}
{177}{}{没有了，谢谢。}
{178}{}{是的，我还有其他东西要取。}
{179}{}{嗯，这东西在合适的人手里会很有用。给你。还有别的需要吗？}
{180}{}{没有了，谢谢。}
{181}{}{是的，我还有其他东西要取。}
{182}{}{哦，还有别的东西？抱歉，我可能漏掉了。让我看看。}
{183}{}{你好，又见面了。今天过得怎么样？有什么我可以帮你的吗？}
{184}{}{有什么我可以帮你的吗？你看起来好像很忙。}
{185}{}{我有东西要取。}
{186}{}{没什么，再见。}
{187}{}{你能帮我什么忙吗？我不这么认为。让开。}
{188}{}{好的，让我看看。}
{189}{}{啊，是的。你确实有授权可以取东西。}
{190}{}{其实是这样的。索菲娅需要一些脉冲手雷，但我还没来得及送给她。你能帮我送过去吗？}
{191}{}{当然。给我吧。}
{192}{}{抱歉，我没时间。希望你能找到其他人。}
{193}{}{我看起来像是你的跑腿的吗？}
{194}{}{好吧，给你。索菲娅是弗里两位助理大师抄写员之一。她通常在三楼的图书馆。}
{195}{}{你为什么还没送我给你的物品？索菲娅在等着呢。}
{196}{}{抱歉，你能再告诉我她在哪里吗？}
{197}{}{我弄丢了。能再给我一些吗？}
{198}{}{抱歉，我忘了时间。}
{199}{}{哈！你以为我真的会送吗？你比看起来还要傻！}
{200}{}{她通常在三楼的图书馆。}
{201}{}{警卫！我们有个小偷！告诉他背叛兄弟会的下场。}
{202}{}{警卫！我们有个小偷！告诉她背叛兄弟会的下场。}
{203}{}{抱歉，我不想跟你这种人说话。}
{204}{}{真是个借口。我就知道不该信任你这样的人。}
{205}{}{我真不敢相信你还敢露面。我希望那些手雷对你有用，你再也不会从我这里得到任何东西了。我不在乎是谁给你授权的。}
{206}{}{你好啊。索菲娅说你送了手雷。你真是太好了。她正在研究一个更好的版本，需要看看电路是否兼容。}
{207}{}{你想要什么。}
{208}{}{把我要拿的东西给我，我就不打扰你了。}
{209}{}{没什么。}
{210}{}{好吧。让我检查一下看有没有订单。}
{211}{}{好的，你需要一些弹药吗？你需要哪种？}
{212}{}{我不知道。}
{213}{}{10毫米被甲空尖弹。}
{214}{}{10毫米穿甲弹。}
{215}{}{44马格南被甲空尖弹。}
{216}{}{44马格南全金属被甲弹。}
{217}{}{14毫米穿甲弹。}
{218}{}{.223全金属被甲弹。}
{219}{}{5毫米被甲空尖弹。}
{220}{}{5mm穿甲弹。}
{221}{}{霰弹枪子弹。}
{222}{}{在我能给你弹药之前，你需要先找出你需要哪种弹药。检查一下你申请弹药的武器吧。搞清楚后再来找我。}
{223}{}{啊，火箭发射器......身边有个好武器是很不错的。这样可以了吗？}
{224}{}{不，就这些了。谢谢。}
{225}{}{是的，我还有其他东西要取。}
{226}{}{啊，对，这就是你要的精良手枪。这样可以了吗？}
{227}{}{不，就这些了。谢谢。}
{228}{}{是的，我还有其他东西要取。}
{229}{}{最好的进攻就是防守。或者说反过来？好吧，没关系。这是你的护甲。一定要好好保养，我不能给你多于一套装备。还有别的需要吗？}
{230}{}{不，就这些了。谢谢。}
{231}{}{是的，我还有其他东西要取。}
{232}{}{嗯……动力装甲。一定要好好保养，我不能给你多于一套装备。还有别的需要吗？}
{233}{}{不，就这些了。谢谢。}
{234}{}{是的，我还有其他东西要取。}
{235}{}{如果落在合适的人手里，这是个很有用的东西。拿去吧，还有其他的吗？}
{236}{}{不，就这些了。谢谢。}
{237}{}{是的，我还有其他东西要取。}
{240}{}{我在找一个收缩动力器。}
{241}{}{你有合适的授权吗？}
{242}{}{有。我是被派来取收缩动力器的。}
{243}{}{没有，但我必须得到这个部件。}
{244}{}{凯尔让我来拿这个部件。}
{245}{}{没有。怎么才能得到授权？}
{246}{}{让我看看。（他检查他的终端）我这边没有看到有任何收缩动力器的请求。你需要取得适当的授权。}
{247}{}{听着！我不想惹麻烦。把该死的部件给我吧。}
{248}{}{拜托？我真的需要这个部件。}
{249}{}{好的。抱歉打扰了。}
{250}{}{你没有？军械库本该昨天就送一个下来。听着，能帮帮我吗？如果我拿不到这个部件，我就完了。表格今天晚些时候肯定会到的。}
{251}{}{好的，给你。别告诉任何人我给了你这个。罗姆布斯知道我未经授权就把这部件给你，他会宰了我的。}
{252}{}{谢谢你。再见。}
{253}{}{如果可以，我会给你。但我不能。没有适当的授权是不行的。}
{254}{}{你知道吗，迈克尔，你可能是我在这里遇到的最聪明的人之一。但我不明白你为什么要这么为难我。我真的很需要那个零件。}
{255}{}{哦..好吧。我想我明白了。不过我不知道该怎么办。}
{256}{}{就给我吧。}
{257}{}{如果你没有授权，就不能获得替换零件。} {258}{}{拜托？求你了。我真的很需要这个零件。}
{258}{}{拜托，求你了。我真的需要这个零件。}
{259}{}{好的。打扰了。再见。}
{260}{}{凯尔？是关于那套旧的动力装甲吗？}
{261}{}{是的。}
{262}{}{不是。}
{263}{}{你可以告诉他，当他把那套装备恢复到原来的荣耀时，只有那时他才能获得所需的授权。再见。}
{264}{}{你不能。首先凯尔需要查看需要修理的装备。如果他认为修理是合理的，他会提交一个零件请求。罗姆布斯会审核请求并决定哪些是可行的。去找凯尔吧。再见。}
{265}{}{再见。}
{266}{}{哦...对，凯尔让我来的。你能再检查一下你的终端吗？}
{267}{}{但罗姆布斯派我来的。}
{268}{}{你拿不到零件，这就是最终决定。我已经告诉你需要做什么了，我不会再重复一遍。}
