{100}{}{你看到米歇尔。}
{101}{}{}
{102}{}{}
{103}{}{你看到一个刀锋帮成员。}
{104}{}{你看到一个刀锋帮成员。}
{105}{}{你觉得那可能是书虫。}
{106}{}{你觉得那可能是伤疤。}
{107}{}{你觉得那可能是枪手。}
{108}{}{你觉得那可能是抽搐。}
{109}{}{你觉得那可能是锤子。}
{110}{}{你觉得那可能是剃刀。}
{111}{}{你在这里干什么？}
{112}{}{嗯嗯。}
{113}{}{没什么。真的。}
{114}{}{我只是随便看看。}
{115}{}{这个！*啪*}
{116}{}{白痴。我觉得你最好赶紧离开这里。否则，你可能会成为靶子。}
{117}{}{嗷！}
{118}{}{嗷嗷。}
{119}{}{没什么，是吧？我觉得你在隐瞒什么。说出来，否则你会看到你的肠子。}
{120}{}{我其实是个火星人。}
{121}{}{我来这里是为了阻止帮派战争。}
{122}{}{我没在搞什么鬼。}
{123}{}{我在搞这个！*啪*}
{124}{}{大家都知道没有火星人。所有真正的外星人都来自金星。现在，你去死吧！}
{125}{}{当然，我是墨西哥女王。}
{126}{}{真的。我想要停止战争，这样我才能帮助阿迪图姆。}
{127}{}{陛下，我真的想结束战争。}
{128}{}{如果你的智商更高，我会试着解释和平的好处。}
{129}{}{如果你是来做这个的，那你需要去找剃刀。她会告诉你我们对此的看法。}
{130}{}{呃，谢谢。我想。}
{131}{}{好的。再见。}
{132}{}{嘲笑我吗？我想我该料到一个小孩会这样。哦，顺便说一下。给你！}
{133}{}{花言巧语在这里可没用。在这里，它只会让你进坟墓。}
{134}{}{如果你无所事事，那我们就给你找点事做。我觉得“靶子”是个不错的选择。}
{135}{}{你看了。现在，你想要什么？想快点。这可能决定你是能走出去还是成为永久居民。}
{136}{}{我想住在这里。}
{137}{}{其实我是伪装成的撕裂者。}
{138}{}{我想为帮派带来和平。}
{139}{}{离开。}
{140}{}{没什么特别的。只是看看要回收的垃圾。}
{141}{}{我们可没说过住。你只会在这里待着。无限期地。好好享受你的逗留吧。}
{142}{}{很高兴你这么说。我正想磨磨这个。}
{143}{}{很快我就会有皮来磨了。}
{144}{}{没那么快。离开这里的唯一方法是成为刀锋帮的一员，或者被装进袋子里。}
{145}{}{那我想成为刀锋帮的一员。}
{146}{}{这个袋子有多大？}
{147}{}{你忘了第三个选择。我！}
{148}{}{机会渺茫。不过，这里有个测试。如果你能找到剃刀，你可以和她谈谈。}
{149}{}{大到足够装下你的尸体，等我们完事后。}
{150}{}{我不是睡美人。我不需要被唤醒。滚出去，否则就死。}
{151}{}{听说你要去取那混蛋的头。替我多捅他一刀。}
{152}{}{欢迎回来。洞穴已经准备好再次接待你了。}
