{100}{}{你看到一个守卫。}
{101}{}{你来这里有什么事？}
{102}{}{呃？}
{103}{}{我只是随便看看。}
{104}{}{我想买些武器。}
{105}{}{}
{106}{}{}
{107}{}{我没心情开玩笑。如果你不马上离开这里，我就开枪了！}
{108}{}{我们不喜欢多管闲事的人。现在走开，我就不对你开枪。}
{109}{}{}
{110}{}{}
{111}{}{你闻起来像头布拉明，但我敢打赌你没它聪明。}
{112}{}{}
{113}{}{啊，很好。顾客永远是受欢迎的。进来吧，但请保持你的武器入套。去找扎克，他会帮你搞定你需要的东西。}
{114}{}{}
{115}{}{我需要和你的老板谈谈。这很重要。}
{116}{}{哦，好吧。加布里埃尔会和你谈的。进去吧。}
{117}{}{是的，我记得你。进去吧。}
{118}{}{我需要和加布里埃尔谈谈。这很重要。}
{119}{}{我想从扎克那里买武器。}
