{100}{}{在你面前的是一台Mach IV计算机。}
{101}{}{系统似乎正在重启状态。}
{102}{}{系统似乎已经死机。}
{103}{}{显示器闪烁着。}
{104}{}{屏幕上显示出奇怪的色彩图案。}
{105}{}{电脑屏幕上显示着无数小绿弹不断坠向地面。}
{106}{}{你无法破解屏幕密码。}
{107}{}{你访问了一些电子笔记。最有趣的是一封来自中尉的请求，要求“……更多的人类实验对象进行浸泡。立即送往军事基地。”}
