{100}{}{你看到了莫菲斯。}
{101}{MORP02}{I don't remember inviting anyone to my room?  And yet I have a
 visitor. Why?}
{102}{}{哦，抱歉。我好像迷路了。}
{103}{}{因为我有个好交易要给你……}
{104}{}{我是}
{105}{}{。你叫什么名字？}
{106}{}{有个兄弟派我来这里。}
{107}{}{妈妈？}
{108}{MORP02A}{No.  I'm Father Death...}
{109}{MORP03}{Well, my child, it's quite dangerous to explore
 places where you do not belong.  Where were you heading that you ended up in
 my private chambers?}
{110}{}{我是新来的，我在找洗手间。一个高级祭司让我上来的。}
{111}{}{我在找忏悔室，一个高级祭司让我上来的。很抱歉我走错了！}
{112}{}{其实，我并没有迷路。}
{113}{}{我是来这里杀你的。}
{114}{}{我忘了。我这就走。}
{115}{MORP04}{ Ahh...Heh, heh heh. That would be Lasher.  He so loves getting the worshipers
 in trouble.  This is your lucky day, my ignorant little friend.  You may leave
 now without incident. }
{116}{MORP04A}{ You were warned.  Guards! }
{117}{MORP05A}{ You are a pathetic liar.  Tell me the real reason you
 are here now...before I have you skinned alive. }
{118}{}{真的！我迷路了！}
{119}{}{好吧，你抓到我了。我是来给你提供一个交易的。}
{120}{}{我只是随便看看。}
{121}{MORP06}{ I suspect you
 are a spy, sent by the Followers.  I may be wrong, but I do not take chances.
 You must be eliminated. }
{122}{MORP07}{ What could you possibly offer me? }
{123}{}{我来自一个避难所。你知道那是什么，对吧？}
{124}{}{我想提供一些关于你敌人的信息。}
{125}{}{我是被主人派来的。他要我监视你。}
{126}{morp08}{Go on.}
{127}{}{我想给你的主人提供一些关于我避难所的信息。}
{128}{}{我有一些关于我避难所的信息要给主人。}
{129}{}{慢着。我想知道我能从我的信息中得到什么。}
{130}{MORP09}{ I do not have a master, you imbecile! }
{131}{}{那你怎么称呼主人？难道他不控制你吗？}
{132}{}{看起来主人确实控制着你。}
{133}{}{嘿。注意你的侮辱！！}
{134}{}{看来我戳到痛处了。}
{135}{MORP10}{ No one
 controls me.  He and I are...partners. }
{136}{}{是啊，对。你就是条短绳上的小狗。}
{137}{}{这不重要。我有关于一个避难所的信息，他会感兴趣的。}
{138}{}{他下命令，对吧？而你不问任何问题就执行。}
{139}{MORP11}{ I do not tolerate
 insults. Guards! }
{140}{MORP12}{ Fine. I will take you to the Master. But if
 you are lying, he will know. }
{141}{}{好吧，行。}
{142}{}{你哪儿也带不走我！}
{143}{MORP13}{ That is none of your concern.  But
 if you are truly from a Vault, the Master will find out.  Guards!  Come along.}
{144}{MORP14}{You may keep your life.  Now, tell me what you know. }
{145}{}{我来自一个避难所，我愿意告诉主宰者位置。}
{146}{}{否则呢？}
{147}{}{我什么都不会告诉你。}
{148}{MORP15}{ No? Then I will take the information from you.  Guards! }
{149}{MORP16}{ And who might my enemies be? }
{150}{}{比如说，追随者。}
{151}{}{从我的角度来看，似乎是所有人。}
{152}{MORP17}{ Tell me what you know. }
{153}{}{我不这么认为。带我去见主宰者。我只会告诉他。}
{154}{}{就说我知道一些能帮你对付他们的事情。}
{155}{MORP18}{ Give me the information or die a slow...lingering...death. }
{156}{}{你觉得杀了一个避难所居民，主宰者会高兴吗？}
{157}{}{我只跟主宰者说话。}
{158}{MORP19}{ Ahh...So you are the Vault dweller I've been hearing about.
 Surprised?  I have my sources. Now, I will take you as a gift to the Master.
 He'll be very pleased. }
{159}{}{那我们就把你装进袋子里带走，怎么样？}
{160}{}{我也是。}
{161}{MORP20}{ A spy? Very foolish of you.  It will be
 difficult to report to him when you are dead, won't it? }
{162}{MORP21}{ You are
 a bad liar. Now, tell me what you want. }
{163}{}{我来自一个避难所。你知道那是什么，对吧？}
{164}{}{我想提供一些关于你敌人的信息。}
{165}{MORP23}{ How surprising.  Now
 tell me why you are here. }
{166}{}{我来自一个避难所，我愿意告诉主宰者位置。}
{167}{}{我想提供一些关于你敌人的信息。}
{168}{}{你一点也不吓人。}
{169}{}{我什么都不会告诉你。}
{170}{MORP24}{ Oh, really?  And how do you plan to do
 that? With your stunning wit and sharp tongue? }
{171}{}{不，用这个……}
{172}{}{对付你太简单了。我会选择更有挑战性的方式。}
{173}{}{我想一颗子弹就够了。}
{174}{MORP26}{ Here's your deal.
 Tell me what you know, and you'll be able to walk out of here on both legs.}
{175}{}{我来自一个避难所，我愿意告诉主宰者位置。}
{176}{}{我想提供一些关于你敌人的信息。}
{177}{}{你一点也不吓人。}
{178}{}{我什么都不会告诉你。}
{179}{MORP27}{ I ask the questions, not you.  Now, tell me what you are doing
 here. }
{180}{}{我只是迷路了。}
{181}{}{我来跟你做个交易。}
{182}{morp28}{Yes?}
{183}{}{你好。我是新加入的孩子，想问你几个问题。}
{184}{}{没事。}
{185}{}{嗯？}
{186}{morp29}{Of course, my child.}
{187}{}{谢谢……}
{188}{}{算了。}
{189}{}{孩子们的计划是什么？}
{190}{}{我改变主意了。没有更多问题了。}
{191}{}{如果我告诉你我来自一个避难所，你会怎么说？}
{192}{MORP31}{ Our plans?  We are the messengers of evolution, my child.
 We follow the Master in his endless quest to heal the land and the people.}
{193}{}{真的吗？你们教授的究竟是什么样的进化？}
{194}{}{什么样的治疗？}
{195}{MORP32}{ We know there is a higher level, a glorious place humanity
 should strive to reach.  Ours is the goal to find the life better, more
 fulfilling, than the present one, marred by hardship and strife. }
{196}{}{你在开玩笑吧？}
{197}{}{你们找到这个更高的层次了吗？}
{198}{MORP33}{[Angry]Why you!...[Calmly]You are forgiven. Not everyone is
 capable of seeing the light. But, tell me my child, why did you join us? }
{199}{}{我得看看这是不是像我听说的那样荒谬。现在我知道了。}
{200}{}{抱歉。我想我有点失礼了。}
{201}{morp34}{You know nothing.}
{202}{MORP35}{ Yes, you
 were, but you are forgiven.  Now, if there are no more questions, I have work
 to do. }
{203}{}{其实，还有一些问题。}
{204}{}{不用了，谢谢。}
{205}{MORP36}{ Of course. Please.  Continue.}
{206}{MORP37}{ Yes, but you
 are...forgiven.  Go in peace, my child. }
{207}{MORP38}{ No, but with faith and
 hope, we're certain to find it. But all this should be known to you, my
 child.}
{208}{}{我知道，但请再回答几个问题。}
{209}{}{我知道了。再见。}
{210}{MORP39}{ We cure the physical body to start.  You've certainly
 seen our hospitals.  Then we offer hope and healing for the spirit. }
{211}{}{哇。我差点就信了。你真厉害！}
{212}{}{这些医院在哪里？}
{213}{MORP40}{ Our glorious effort has just reached Adytum and, of course, the
 Hub shines with our efforts there.  But, I have a feeling there's more you
 wish to ask. }
{214}{MORP41}{ These are wondrous days.  Junktown now joins in
 Adytum and the Hub in our quest to save body and soul.  Is there more you wish
 to know, my child? }
{215}{}{事实上……}
{216}{}{没什么。我得走了。}
{217}{MORP42}{ The Children's vision now stretches from Adytum, to the Hub, Junktown, and now
 gently caresses Shady Sands.  Why do you ask? }
{218}{}{只是好奇。我可以再问几个问题吗？}
{219}{}{没什么。我得走了。}
{220}{MORP42A}{ You are what? }
{221}{}{你听见了。带我去见大师，现在！}
{222}{MORP42B}{ Uh, yes.
 Well.  Please follow me. }
{223}{MORP42C}{ Oh, my child, you make no sense
 whatsoever.  please, find one of our physicians and get help. }
{224}{MORP45}{ My child, talk to
 Lasher.  He'll help you with that. }
{225}{MORP46}{ I said... }
{226}{MORP47}{ Are
 you deaf?  I said...}
{227}{MORP48}{ I will not repeat myself again! }
{228}{MORP49}{ I will not say it again! }
{229}{MORP50}{The Nightkin came to us a while ago.  They might be hideous
 mutants but they are extremely loyal to the Children.  As we all are.}
{230}{MORP51}{It is he who brought me the
 vision of the Unity and it is he who will bring peace to this troubled land.}
{231}{MORP52}{My child, you should know the Auditorium.  I give my sermons
 there. }
{232}{MORP53}{Don't concern yourself with that.  Only the High Priests may enter. }
{233}{MORP54}{I am but a humble servant of the Unity. }
{234}{MORP55}{We are the high priests of the great Dark God. Thirteen of us
 are so blessed to pass his mighty words to the rest of the Children. }
{235}{MORP56}{I've no idea what you're talking about. }
{236}{MORP57}{The Children of the Cathedral hospitals provide the best care
 in all of this blasted, torn land. This care is vital to the Unity.}
{237}{MORP58}{The Unity is our search for a higher level of life, and unity with our fellow man. }
{238}{MORP59}{He is another High Priest.  He spends much of his time in the studies. }
{239}{MORP60}{My heart bleeds for them.  Led down a false path.  They don't
 know their efforts will bring only pain and suffering to their fellow beings.}
{240}{MORP61}{Nicole is the unfortunate, confused leader of the Followers of
 the Apocalypse. }
{241}{MORP62}{Adytum is the city to the northeast of us. }
{242}{MORP63}{That's not important. }
{243}{MORP64}{That's nothing.  You may ask something else. }
{244}{morp65}{Nothing to be concerned with.}
{245}{}{大师，我相信您会喜欢这个……}
{500}{}{你因摧毁大教堂的孩子们的领袖而获得1000经验值。}


# Morpheus Tell-Me-Abouts generic responses
{980}{MORP63}{That's not important. }
{981}{MORP64}{That's nothing.  You may ask something else. }
{982}{morp65}{Nothing to be concerned with.}


#
# Morpheus Tell-Me-Abouts
#


{1000}{}{夜行者}
{1001}{}{大师}
{1002}{}{礼堂}
{1003}{}{圣殿}
{1004}{}{莫菲斯}
{1005}{}{秩序}
{1006}{}{商队}
{1007}{}{医院}
{1008}{}{统一体}
{1009}{}{鞭笞者}
{1010}{}{追随者}
{1011}{}{妮可}
{1012}{}{阿迪图姆}
{1013}{}{末日}
{1014}{}{变种人}
{1015}{}{圣焰}
{1016}{}{儿童}
{1017}{}{基地}
{1018}{}{芯片}

{1100}{MORP50}{The Nightkin came to us a while ago.  They might be hideous
 mutants but they are extremely loyal to the Children.  As we all are.}
{1101}{MORP51}{It is he who brought me the
 vision of the Unity and it is he who will bring peace to this troubled land.}
{1102}{MORP52}{My child, you should know the Auditorium.  I give my sermons
 there. }
{1103}{MORP53}{Don't concern yourself with that.  Only the High Priests may enter. }
{1104}{MORP54}{I am but a humble servant of the Unity. }
{1105}{MORP55}{We are the high priests of the great Dark God. Thirteen of us
 are so blessed to pass his mighty words to the rest of the Children. }
{1106}{MORP56}{I've no idea what you're talking about. }
{1107}{MORP57}{The Children of the Cathedral hospitals provide the best care
 in all of this blasted, torn land. This care is vital to the Unity.}
{1108}{MORP58}{The Unity is our search for a higher level of life, and unity with our fellow man. }
{1109}{MORP59}{He is another High Priest.  He spends much of his time in the studies. }
{1110}{MORP60}{My heart bleeds for them.  Led down a false path.  They don't
 know their efforts will bring only pain and suffering to their fellow beings.}
{1111}{MORP61}{Nicole is the unfortunate, confused leader of the Followers of
 the Apocalypse. }
{1112}{MORP62}{Adytum is the city to the northeast of us. }
{1113}{MORP60}{My heart bleeds for them.  Led down a false path.  They don't
 know their efforts will bring only pain and suffering to their fellow beings.}
{1114}{MORP50}{The Nightkin came to us a while ago.  They might be hideous
 mutants but they are extremely loyal to the Children.  As we all are.}
{1015}{morp65}{Nothing to be concerned with.}
{1016}{morp65}{Nothing to be concerned with.}
{1017}{morp65}{Nothing to be concerned with.}
{1018}{morp65}{Nothing to be concerned with.}
