{100}{}{这是一个核弹头。}
{101}{}{有电缆从控制计算机连接到后面的核弹头。}
{102}{}{你已经启动了核弹头。一个四分钟的倒计时已经开始。}
{103}{}{你已经拆除了核弹头的引信。}
{104}{}{轰隆隆！[你引爆了核弹！]}
{105}{}{这似乎不起作用。}
{106}{}{倒计时仍在继续……也许你应该剪掉那根红色电线。}
{107}{}{也许你还需要使用钥匙。}
{108}{}{这是一个核弹头。它由连接的电缆控制的计算机操控。}
{109}{}{这个核弹头上没有需要修理的地方。}
{110}{}{这个核弹头上没有可以撬锁的地方。}
{111}{}{这是一个非常大的陷阱，无法在这里解除或启动。}
