{100}{}{骑士}
{101}{}{你好，见习者。}
{102}{}{如果你需要什么，可以去找维莉。}
{103}{}{维莉就在那边，如果你需要找人谈话。}
{104}{}{我得在巡逻和训练之间抽时间来保持学习。我觉得自己有点生疏了。}
{105}{}{见习者，你必须时刻保持身心的最佳状态。}
{106}{}{我们抄写员负责设计所有设备、武器和物资。这相当令人兴奋。}
{107}{}{成为一名骑士不仅仅是战斗，孩子。}
{108}{}{成为一名骑士不仅仅是战斗，女士。}
