{100}{}{骑士}
{101}{}{新兵，你不应该在这里。}
{102}{}{你在这里干什么？}
{103}{}{警卫室是给警卫用的。你不是警卫。你在警卫室。所以，你应该离开。}
{104}{}{请离开。你不应该在这里。}
{105}{}{嘿，新兵不能进来。}
{106}{}{这里不是图书馆，小伙子。如果你想闲逛，请去图书馆。}
{107}{}{这里不是图书馆，小姑娘。如果你想闲逛，请去图书馆。}
