{100}{}{你看到一个骑士守卫。}
{101}{}{嘘，看到什么好交易了吗？}
{102}{}{抱歉，我在执勤。现在不能聊天。}
{103}{}{多么美好的一天。希望今天不会有袭击。}
{104}{}{有些商队的商人有点奇怪。}
{105}{}{你好。}
{106}{}{嗨，你好，漂亮的。}
{107}{}{问候，见习者。}
{108}{}{如果你对我们的组织有任何疑问，应该去找卡博特，他在门边。}
{109}{}{卡博特是你要找的人；他是门边的年轻人。}
{110}{}{嘘，看到什么好交易了吗？}
{111}{}{如果你是来交易的，那你找错人了。}
{112}{}{什么？}
{113}{}{别打扰我，蠢货。}
{114}{}{我看起来像对你可能提供的东西感兴趣吗？}
{115}{}{哼。真是无礼。}
{116}{}{见习者，你应该知道在我们值班时不要打扰我们。}
{117}{}{如果你对组织有任何疑问，应该去找卡博特，在门边。}
{118}{}{见习者，你不应该去做些有用的事情吗？}
{119}{}{我觉得你不应该在这里，陌生人。}
