{100}{}{你看到一个穿着铆钉皮甲的男人，身上带着各种奇怪的小玩意。}
{101}{}{你看到帕特里克，那个凯尔特人。}
{102}{}{你好，旅行者。是什么让你来到这么远的地方？}
{103}{}{只是随便走走。}
{104}{}{呃，你为什么带着那么多杂物？}
{105}{}{我需要找到一个水净化控制芯片。}
{106}{}{我在射程内杀掉所有人。准备受死吧。}
{107}{}{鲁布！}
{108}{}{我明白了，和我很像。}
{109}{}{哦？你不是这里的某个社区的人吗？}
{110}{}{你能告诉我附近的定居点在哪里吗？}
{111}{}{那你的故事是什么？}
{112}{}{好吧，再见。}
{113}{}{这不是杂物！这是交易货物！}
{114}{}{呃，好吧。再见。}
{115}{}{嗯哼。那你的故事是什么？}
{116}{}{嗯。以前没见过这种东西。有什么问题吗？}
{117}{}{这个芯片控制我避难所的水净化。不过它坏了。}
{118}{}{它坏了。}
{119}{}{我四处游荡，以音乐和一点修理工作为生。}
{120}{}{你做什么样的工作？}
{121}{}{你唱什么样的音乐？}
{122}{}{很高兴见到你。再见。}
{123}{}{以海岸线为参考，你往内陆走一周左右就是阴影镇，再往南几天是废城。再往南几天就是枢纽。不过要避开东边的死城，不值得去。}
{124}{}{你对阴影镇了解多少？}
{125}{}{你对废城了解多少？}
{126}{}{你对枢纽了解多少？}
{127}{}{你对死城了解多少？}
{128}{}{我恐怕帮不了你。我没怎么研究过战前的避难所技术。}
{129}{}{主要是一些电气和机械的修理。我帮废城修了灯，还给阴影镇的人展示了更好的炉灶设计。}
{130}{}{真的吗？你觉得你能修好一个水芯片吗？}
{131}{}{哦，主要是一些老民歌和凯尔特音乐。换个口味。}
{132}{}{你知道一首叫《Na Gheala Mbeadh》的歌吗？}
{133}{}{我明白了。你还做些什么？}
{134}{}{阴影镇是一个小型自给自足的社区，由阿拉德什领导，他是个善良且有力的领袖。他们和平而勤劳，可能是这里新文明的最佳希望。}
{135}{}{阴影镇是一个小型农业社区。曾由一个好人阿拉德什领导，但我听说他已经不在了。真遗憾。没有他，我不知道他们能否生存下去。}
{136}{}{废城？一个小型贸易城市。刚去时感觉很奇怪，习惯就好。由市长基利安·黑水管理，他是个严厉但公正的人。}
{137}{}{废城？一个小型贸易城市。刚去时感觉很奇怪，习惯就好。由赌博大亨和犯罪头目吉兹莫掌控。}
{138}{}{废城？一个小型贸易城市。没什么特别的。}
{139}{}{中心城是一个主要的贸易中心。据说在那里可以找到任何东西，我觉得这话不假。}
{140}{}{死城是亡者之城。居住着一些食尸鬼，他们是曾在那里的避难所中寻求庇护的人类后裔。据说避难所出了问题，所以现在唯一的居民是食腐的怪物。}
{141}{}{我听说那里最后被一支变种人军队占领了。如果我是你，我会远离那里。}
{142}{}{你觉得那个避难所有我能回收的零件吗？}
{143}{}{可能吧，但我个人不会冒险去面对那些食尸鬼。最新消息是他们有了某种强大的新领袖。}
{144}{}{当然。你想听吗？}
{145}{}{当然。}
{146}{}{算了。}
{147}{}{[帕特里克唱起了歌，你们两人回忆了好几个小时。你感到精神焕发。]}
{148}{}{你好，又见面了。我能帮你吗？}
{149}{}{是的，你能给我指个方向吗？}
{150}{}{不用了，谢谢。}
