{100}{}{你看到骑士保罗。}
{101}{}{啊哈，你就是新来的见习者。欢迎加入。有什么我可以帮你的吗？}
{102}{}{你是谁？你在这里做什么？}
{103}{}{我在哪里可以弄到武器？}
{104}{}{Vree告诉我可以看看新武器。}
{105}{}{你们有水芯片吗？}
{106}{}{你们有动力装甲的零件吗？}
{107}{}{什么？}
{108}{}{没事，谢谢。}
{109}{}{我是保罗，负责能量武器开发。}
{110}{}{什么类型的能量武器？}
{111}{}{你有Vree设计的激光手枪吗？}
{112}{}{激光、等离子……你能想到的我都造过……或者至少是重造过。}
{113}{}{我有机会得到一把吗？}
{114}{}{太好了。继续努力。再见。}
{115}{}{你得去找迈克尔领取武器。不过他不能给你授权，你得去找塔勒斯。}
{116}{}{好吧，我在哪里能找到他们？}
{117}{}{好的。谢谢你的信息，再见。}
{118}{}{他们都在基地的一楼。塔勒斯通常在训练室，而迈克尔则在储藏室外值班。}
{119}{}{谢谢。我能再问几个问题吗？}
{120}{}{谢谢。我这就走了。}
{121}{}{当然。我能帮你什么？}
{122}{}{我在哪里可以弄到新武器？}
{123}{}{你们有水芯片吗？}
{124}{}{你们有动力装甲的零件吗？}
{125}{}{我可以看看新的激光手枪吗？}
{126}{}{其实，我得走了。再见。}
{127}{}{是的。这是最新的手持激光技术。[他从工作台上拿起一把小手枪递给你]}
{128}{}{这不错，我可以留下吗？}
{129}{}{这对人能造成什么样的伤害？}
{130}{}{这个对你没什么用。它还缺少镜片和放大器。[他从你手中拿回手枪并放在工作台上]如果你真的想要一个，去找塔勒斯或迈克尔吧。}
{131}{}{谢谢，我在哪能找到他们？}
{132}{}{谢谢，我该走了。}
{133}{}{我能再问你几个问题吗？}
{134}{}{水芯片？是那些旧Vault-Tec避难所里的？}
{135}{}{是的！你有吗？}
{136}{}{没有。那些东西都是垃圾，容易出故障。我们这里不处理自己的水净化。我们通过商队从集散地运水过来。}
{137}{}{好的，谢谢。我得继续找一个。再见。}
{138}{}{我能再问你几个问题吗？}
{139}{}{在一个熟练的战士手中，它可以把人一劈两半。光束切割肉体的速度比你用手指划过沙子还快。}
{140}{}{我能留着这个吗？}
{141}{}{不能。我只负责能量武器。如果你有关于动力装甲的问题，应该去找凯尔。}
{142}{}{实际上凯尔没有零件，所以我才在找。}
{143}{}{谢谢。再见。}
{144}{}{嗯，我帮不了你。抱歉。}
{145}{}{谢谢。我得走了。再见。}
{146}{}{我能再问你几个问题吗？}
{147}{}{又见面了，见习者}
{148}{}{。我能帮你什么？}
{149}{}{你是谁，在这里做什么？}
{150}{}{我在哪里能弄到武器？}
{151}{}{Vree告诉我可以来看一件新武器。}
{152}{}{你有水芯片吗？}
{153}{}{你有动力装甲的零件吗？}
{154}{}{什么？}
{155}{}{没什么，谢谢。}
{156}{}{嗯...请离开，免得你在重要东西上流口水。}
