{100}{}{你看到一个被囚禁的辐射生物。}
{101}{}{你想干什么。}
{102}{}{呃，没什么。}
{103}{}{哼。}
{104}{}{我来放你出去。}
{105}{}{你还期待什么。}
{106}{}{嘿，我不在乎那些，快让我出去！}
{107}{}{太好了！快行动吧！}
{108}{}{我偷了些水。嘿，我口渴了！又不是伤害了谁。}
{109}{}{你拿了超过你应得的份额。}
{110}{}{啊，那没什么。我会放你出去。}
{111}{}{没有水我会死的。只是一杯水，刚好让我活下来。你得把我放出去！我快疯了。}
{112}{}{好吧，稍等一下。}
{113}{}{我想还是让当局来处理你吧。}
{114}{}{请放我走。}
{115}{}{谢谢你放我出来。}
{116}{}{没问题。}
{117}{}{水是从哪里来的？}
{118}{}{是啊。}
{119}{}{他们从下面的井里抽水。隔壁牢房有个井盖通向旧避难所，那是水的来源。如果不是下面那些家伙，我们的日子会好过很多。}
{120}{}{什么意思？}
{121}{}{谢谢。}
{122}{}{有时候让旧技术正常运作很困难。发光者每次我们下去都会攻击我们。我们这些辐射生物就不去招惹他们。而那些大变种人似乎一点都不在乎。}
{123}{}{祝好运。再见。}
{124}{}{你获得了}
{125}{}{经验点数，因为释放了辐射生物囚犯。}
{126}{}{再次感谢。}
