{100}{}{你看到吉迪恩，一个看起来很普通的人。他戴着一顶王冠。}
{101}{}{杰森是活生生的神！只有被消除的人才能通过！}
{102}{}{被消除？他们是用你身上戴的那些装置来限制你的心灵力量吗？}
{103}{}{杰森是谁？}
{104}{}{你说的被消除是什么意思？}
{105}{}{我刚刚杀了他，所以他现在是个死神。你想加入他吗？}
{106}{}{嗯？}
{107}{}{墙壁也有思想……我看到你……明天？}
{108}{}{像你这样的人在墙里？}
{109}{}{算了。}
{110}{}{我现在想杀了你。你能打开这个力场吗？}
{111}{}{打开力场，我就放你出去。}
{112}{}{呃，是的。你是我在找的“实验品”吗？}
{113}{}{杰森？杰森是谁？}
{114}{}{你刚才说了……算了。}
{115}{}{愚蠢。}
{116}{}{是的，墙里充满了那些曾经来过的人。}
{117}{}{他们发生了什么事？}
{118}{}{呃，我得走了。}
{119}{}{灵魂的聚会……融合以保护万物之主。}
{120}{}{我明白了。如何保护自己不受万物之主的守护者伤害？}
{121}{}{战争之犬呢？}
{122}{}{我需要保护万物之主。我该如何找到他？}
{123}{}{我可以杀掉任何人或任何东西。打开这个力场，我来展示一下。}
{124}{}{再见。}
{125}{}{只有和平与融合……代价……痛苦……必须盲目……被消除。}
{126}{}{好吧，我需要加入。我在哪里可以拿到那些时髦的消除器？}
{127}{}{太好了！我该如何加入？}
{128}{}{我想把我的枪和你的头结合在一起！}
{129}{}{我没时间跟你废话。再见。}
{130}{}{我将为你施洗... 我必须给予我不该给予的。}
{131}{}{谢谢。}
{132}{}{没人能给我施洗，你这个疯子！}
{133}{}{施洗？用什么给我施洗？}
{134}{}{不，谢谢。}
{135}{}{你无法杀死...全体的天才...你...嘿哈！}
{136}{}{是的，但我可以让它痛苦不堪。}
{137}{}{我不想杀戮。我想要崇拜。}
{138}{}{显然。再见。}
{139}{}{痰！无实质的发展...交流，空...死亡的终结。}
{140}{}{墙壁也有思想...我见过你...是明天吗？}
{141}{}{我就当你是说“是”。}
{142}{}{太好了！我该如何加入？}
{143}{}{亵渎的...分解...死亡将是...救赎...强大！}
{144}{}{思想...墙壁...在伟大者面前。}
{145}{}{那些走在前面的人...必须阻止你的旅程。}
{146}{}{我需要改变这一点。}
{147}{}{我必须完成我的旅程，主人命令的。}
{148}{}{谁？做了什么？}
{149}{}{是的，但我可以让他们非常痛苦。}
{150}{}{抱歉再次打扰你。再见。}
{151}{}{我想帮你逃走。}
{200}{}{你看到摩尔，一个邋遢的家伙。他戴着一个王冠。}
{201}{}{你看到一个邋遢的家伙。}
{202}{}{沥青将变得血红！！我会粉碎！}
{203}{}{正是。}
{204}{}{你在说什么？}
{205}{}{嗯，是的，会被你的血染红。}
{206}{}{呃，是的。再见。}
{207}{}{呃！}
{208}{}{我要停止引擎！主人赋予了我力量...}
{209}{}{好的，汉克。我想见主人，我该怎么去？}
{210}{}{什么引擎？}
{211}{}{当然！我完全明白...}
{212}{}{我真想劈开你的脑袋，你这个白痴。}
{213}{}{哦，又是你。再见。}
{214}{}{只有强者才能通过，但他们会被阻挡。}
{215}{}{打开这个力场，我要展示我的力量。}
{216}{}{但我必须见主人！}
{217}{}{你能告诉我怎么做吗？}
{218}{}{吉迪恩...吉迪恩知道路。}
{219}{}{没错。}
{300}{}{你看到露西，一个看起来正常的人类女性。她戴着一个皇冠。}
{301}{}{你看到一个人类女性。她盯着你的鞋子。}
{302}{}{没有地方像家，没有地方像家，没有地方像家... [来回踱步]}
{303}{}{嗯！}
{304}{}{住手！}
{305}{}{那这个地方呢？这不是你的家吗？}
{306}{}{我同意。完全同意。你说得对... [她停顿了一下] 你刚才说什么？哦，算了。}
{307}{}{[紧盯着你] 我要为此杀了你！我要让你的血流成红色。等一下。血本来就是红色的，我怎么能让它流成红色呢？我不能这样做。嗯，我得想想这个。走开！}
{308}{}{我的家是，呃，是的。这里。是的，就是这里。这是我的家！[她跳上跳下] 我太高兴了！你无法想象这让我多么高兴。我想我要去撞墙一会儿。}
{309}{}{我很忙。我几乎找到了解决这个世界环境问题的方法，但我总是想着紫色恐龙。这是个问题吗？}
{310}{}{别烦我，我在思考...}
{400}{}{你看到维格姆，一个彻底的失败者。他戴着一个皇冠。}
{401}{}{你看到一个看起来像彻底失败者的人。}
{402}{}{我累了。}
{403}{}{我的生活就是地狱。}
{404}{}{我厌倦了生活。}
{405}{}{黑暗来临。}
{406}{}{随便。}
{500}{}{墙上的标牌写着：‘警告！请勿打扰！’}
