{100}{}{无线电}
{101}{}{[一阵静电噪音后，你听到一个低沉的声音从收音机中传来。] 指挥部呼叫巡逻队，指挥部呼叫巡逻队。你们的状态如何？完毕。}
{102}{}{吱！}
{103}{}{呃，这里没什么问题。我们很好，呃，你怎么样？}
{104}{}{指挥部，我们遭到一大群武装人类的袭击。请求支援。完毕。}
{105}{}{救命！未知攻击者！严重损坏！坐标如下：10 . . . 啊！}
{106}{}{收到，巡逻队。我们正在派遣支援。完毕。}
{107}{}{你是谁？你的目的是什么？}
{108}{}{我的目的是闭嘴。}
{109}{}{我，呃，哦，算了。我反正要杀了你们所有人。}
{110}{}{这里是，嗯，弗雷德。我的任务是巡逻。我想我有点晕，刚才摔了一跤。}
{111}{}{收到，巡逻队。你们的坐标是多少？}
{112}{}{224 乘 104。}
{113}{}{南南西四英里。}
{114}{}{伽马区，奥米克戎-德尔塔-贝塔。}
{115}{}{收到，巡逻队。指挥部结束。}
{116}{}{收到，巡逻队。我们正在派遣增援。}
{117}{}{啊，这就说得通了。我们现在派遣支援。}
{118}{}{收到，巡逻队。我们现在派遣支援！坚持住！}
{119}{}{收音机中只有静电噪音。}
{120}{}{你听到收音机中有一些交谈。你听了一会儿，发现没有什么重要信息。}
{121}{}{收音机上有一个红色闪烁的灯。你听到扬声器中传来尖锐的噪音。}
{122}{}{听起来像是加密的音频。}
{123}{}{你发送了命令代码以切换力场设置。}
{124}{}{收音机频道中只有安静的静电噪音。}
{125}{}{收音机无法正常工作。}
{126}{}{这台收音机状态良好。问题的来源一定是外部的。}
{127}{}{收音机中只有加密数据的尖锐噪音。}
{128}{}{[吱-啪-噗] 指挥部在此，请讲，巡逻队。}
{129}{}{哎！}
{130}{}{呃，抱歉，指挥部。我不小心按到了通话按钮。}
{131}{}{基地有入侵者！拉响警报！}
{132}{}{收到，巡逻队，指挥部结束。}
{133}{}{[你调整无线电频率到安全控制频道] [咔哒！] 输入访问号码。[咔哒！]}
{134}{}{嗯！}
{135}{}{呃，69。}
{136}{}{5566534571}
{137}{}{结束访问。}
{138}{}{自动关闭安全频道。}
{139}{}{你通过欺骗变种人守卫获得了1,500点经验值。}
{140}{}{你成功潜入军事基地深处而未被发现（暂时）获得了2,000点经验值……}
