{100}{}{你看到辛迪在哭。}
{101}{}{你看到丽莎在哭。}
{102}{}{你看到桑迪在哭。}
{103}{}{你看到玛丽在哭。}
{104}{}{你看到斯泰西在哭。}
{105}{}{你看到苏珊在哭。}
{106}{}{你看到辛迪。}
{107}{}{你看到丽莎。}
{108}{}{你看到桑迪。}
{109}{}{你看到玛丽。}
{110}{}{你看到斯泰西。}
{111}{}{你看到苏珊。}
{112}{}{你好，}
{113}{}{。你找到水芯片了吗？}
{114}{}{还没有。}
{115}{}{我会找到的。你还好吗？}
{116}{}{乌鲁格！}
{117}{}{哦……你听不懂我说的话。我想我们真的没有太多希望了。请原谅我，我要哭了。}
{118}{}{乌格！}
{119}{}{请在我孩子渴死之前找到它。}
{120}{}{[完成]}
{121}{}{你一定要找到它！不要让我们这样死去！}
{122}{}{[完成]}
{123}{}{继续努力。我相信你。我知道你会尽一切努力来拯救我们。}
{124}{}{[完成]}
{125}{}{我很害怕现在发生的事情。有人在偷水，现在每个人都很紧张。}
{126}{}{谁会做这种事？}
{127}{}{发生了什么事？}
{128}{}{有些人被指控，甚至因此打了起来，但没人真正知道真相。}
{129}{}{好的，谢谢。}
{130}{}{有些人报告说他们的水被偷了。他们没有得到更多的水，但一些朋友分享了他们的水。之后，每个人都变得非常警惕，开始守护自己的水。几天后，有人在配给区打晕了守卫，偷走了水。}
{131}{}{这太糟糕了！我能做些什么？}
{132}{}{也许你可以阻止这个人。}
{133}{}{我会四处看看。}
