{100}{}{你好，我能为你做些什么？}
{101}{}{你是谁？}
{102}{}{你是这个帮派的头目吗？}
{103}{}{没事了。}
{104}{}{啊...什么？}
{105}{}{我叫剃刀。我算是我们这里的头目。}
{106}{}{所以你是这个帮派的头目？}
{107}{}{南边那个围起来的地方是什么情况？}
{108}{}{很高兴认识你。我是}
{109}{}{很高兴认识你。但我得走了。}
{110}{}{帮派？我们算不上帮派。不过我确实是这里的头目。}
{111}{}{如果你们不是帮派，那你们是什么？}
{112}{}{嗯，在我看来你们就是个帮派。}
{113}{}{再见}
{114}{}{那是阿迪特姆。是一个由监管者组织管理的奴隶劳工营，但他们告诉所有人那是个“城镇”。他们来这里抓走我们的人去干活，直到他们死去。然后再来抓更多的人。}
{115}{}{你们不能进去解救你们的人吗？}
{116}{}{那我跟你说这些干嘛？那些人才是我需要联系的人。}
{117}{}{我要去看看能不能打听到关于阿迪特姆的消息。再见。}
{118}{}{那么，是什么把你带到这片荒地的？}
{119}{}{我在找一个水芯片。你知道哪里能找到吗？}
{120}{}{我只是四处走走。}
{121}{}{只是随便看看。再见。}
{122}{}{我们只是想活下去的人。阿迪特姆让我们陷入这种境地。他们压制我们，把我们的朋友和家人当作牲畜使用。我们甚至没有办法自卫。}
{123}{}{你们为什么不反抗他们？}
{124}{}{你们要防备谁？}
{125}{}{嗯，阿迪特姆的人比你们更强壮更聪明，他们有权利剥削弱者。}
{126}{}{我要去四处看看能发现什么。再见。}
{127}{}{我真希望我们是个帮派。至少那样我们会有像样的武器来保护自己。}
{128}{}{你们要防备谁？}
{129}{}{好吧，你们骗不了我。你们就是一群堕落者，我觉得你们没安好心。}
{130}{}{你们看起来就像是一伙帮派。}
{131}{}{这个我帮不了你。}
{132}{}{南边那个围栏区域有什么故事？}
{133}{}{你是这个帮派的头目吗？}
{134}{}{我们需要更好的武器。离这里不远的枪械商有武器，但我们无法接近他们。}
{135}{}{为什么不行？}
{136}{}{我去看看能了解些什么情况。}
{137}{}{是那些监管者。他们才是真正掌控阿迪坦的人，不是齐默曼。他们来这里，把我们的人拖回阿迪坦当奴隶。我们试图反抗时，他们就杀了我们。有时他们只是来杀几个我们的人，然后带到齐默曼那里，说我们试图闯入他们的城镇，或者编造其他荒谬的故事。那些混蛋甚至杀了齐默曼的儿子！}
{138}{}{齐默曼的儿子？他们为什么要杀他？}
{139}{}{你是说你们从来没有对阿迪坦做过什么吗？}
{140}{}{我们和他们之间有一个死亡爪的巢穴。我们甚至从未和任何枪械商交谈过。监管者有足够的火力清除死亡爪，但他们却没有这么做。}
{141}{}{我在哪里可以找到枪械商？}
{142}{}{好的，再见。}
{143}{}{乔希和我住在这里...呃...我...我是说我们。他知道事情的真相。监管者告诉他，如果他试图联系他的父亲或返回阿迪坦，他们就会杀了他。}
{144}{}{他们杀了他？他做了什么？}
{145}{}{我要去阿迪坦调查一下。}
{146}{}{某天深夜，他试图潜入城镇告诉他的父亲事情的真相。我那晚在监听监管者的无线电通讯...他们...他被抓住了。[她低下头，缓缓摇头。]这里，这个全息磁盘里有全部记录。}
{147}{}{你为什么没有把这个交给乔希的父亲？}
{148}{}{我们甚至无法接近阿迪坦。我们还没到城门就会被射杀。}
{149}{}{为什么我不把磁盘交给他呢？}
{150}{}{为什么不召集一大群人，用武力夺回阿迪坦？}
{151}{}{你愿意冒生命危险来帮助我们吗？}
{152}{}{当然。任何能帮上忙的事情。}
{153}{}{我可能会。我需要先去调查一下情况再做决定。}
{154}{}{谢谢你。这真的能帮到我们。祝好运。[她把全息磁盘递给你。]}
{155}{}{回头见。}
{156}{}{好的，希望你做出正确的决定。}
{157}{}{再见。}
{158}{}{枪械商在这里的东边，然后往北。但要小心——死亡爪不是好惹的。我见过死亡爪一爪就把一个人撕成两半。}
{159}{}{我去看看能找到什么。}
{160}{}{很遗憾你这么想。我觉得你最好还是离开吧。}
{161}{}{再见。}
{162}{}{我能帮你吗？}
{163}{}{你是这个帮派的头目吗？}
{164}{}{没事了。}
{165}{}{啊...什么？}
{166}{}{帮派？我们算不上是帮派。但我是他们都来寻求指引的人。}
{167}{}{齐默曼派我来的。}
{168}{}{嗯，你们在我看来就像个帮派。}
{169}{}{再见}
{170}{}{（看起来有些紧张）什么？他...}
{171}{}{是来给你一颗子弹的。}
{172}{}{是来为他儿子的死报仇的。}
{173}{}{什么！！！那些该死的混蛋！我要杀了他们，把他们全送下地狱！！}
{174}{}{不，你才是要下地狱的人。}
{175}{}{呃...你要把谁送下地狱？}
{176}{}{...是治安官。他们才是杀了乔什的人！我绝不会伤害乔什。是治安官在掌控阿迪顿，不是齐默曼。}
{177}{}{这是个可悲的借口，想要蒙混过关。}
{178}{}{治安官为什么要杀齐默曼的儿子？}
{179}{}{乔什和我...呃...和我们住在一起。他知道事情的真相。治安官告诉他，如果他试图联系他父亲或回到阿迪顿，他们就会杀了他。他们嘲笑他...他们确信他无法联系到他父亲....}
{180}{}{他们杀了他？他做了什么？}
{181}{}{我们的计划进行得怎么样了？}
{182}{}{我还在努力解决一切。}
{183}{}{啊...什么？}
{184}{}{我不太确定如果没有暴力威胁的支持，这会有多大帮助。我们真正需要的是从枪械商那里得到一些武器。}
{185}{}{那么，这些枪械商在哪里？你为什么不从他们那里弄些武器呢？}
{186}{}{哦，好吧，我已经提出了。再见。}
{187}{}{他们在这里稍微偏东一点，但我们和他们之间有个死亡爪的巢穴。我们从未和任何枪械商交谈过。}
{188}{}{好吧，把全息磁盘给我，我会在找齐默曼之前去和枪械商谈谈。}
{189}{}{希望你能找到办法帮助我们。再见。}
{190}{}{怎么了？}
{191}{}{他们杀了齐默尔曼！}
{192}{}{啊……什么？}
{193}{}{……现在我们只能从枪械跑商那里得到武器了。你愿意帮助我们吗？}
{194}{}{是的。}
{195}{}{不。}
{196}{}{谢谢你。愿众神护佑你的旅程。}
{197}{}{感谢你的帮助。我们要进攻阿迪特姆，需要像你这样的人加入我们。}
{198}{}{不，谢谢，这周我已经见识够多了。}
{199}{}{好的，我很愿意来对付监管者。}
{200}{}{啊……什么？}
{201}{}{我想先和齐默尔曼谈谈。}
{202}{}{好吧，再次感谢你的帮助。再见。}
{203}{}{太好了。我们出发吧。}
{204}{}{我不认为这是个好主意，但你尽管试试。}
{205}{}{你（男）混蛋！（女）婊子！没有了枪械跑商，我们甚至没有机会武装自己。滚出去，这里不欢迎你。}
{206}{}{我很抱歉。}
{207}{}{去死吧。}
{208}{}{我要去找齐默尔曼，给他这张全息盘，一切都会好的。}
{209}{}{你知道吗？我要杀了你。}
{210}{}{啊……什么？}
{211}{}{去吧。反正是你自己的葬礼。没有那些枪，我们啥都撑不住。}
{212}{}{走开！}
{213}{}{这里不欢迎你。}
{214}{}{离开。}
{215}{}{谢谢。}
{216}{}{我的人民获得自由了。}
{217}{}{你好。}
{218}{}{你怎么了，有人打了你的头吗？}
{219}{}{嗯？}
{220}{}{你看到剃刀，刀锋帮的领袖。}
{221}{}{你看到一个非常美丽的女人，眼中流露出悲伤的神情。}
{222}{}{请离开。我很忙。}
{223}{}{感谢你帮我们对付了治安官。请随意在这里停留。你可能想去找迈尔斯和史密提，他们或许能在你接下来的旅途中帮上忙。}
{224}{}{你好，我能帮你吗？}
{225}{}{你是谁？}
{226}{}{胡兹帕！}
{227}{}{我叫剃刀，是你看到的这些人的领袖。我们在阿迪顿的治安官的摆布下生活。}
{228}{}{治安官？我已经解决了他们。这有问题吗？}
{229}{}{你把他们全干掉了？这完全没问题。我的人现在可以和阿迪顿的人自由地生活了。}
{230}{}{我简直不敢相信。你竟然能把他们全干掉。刀锋帮和我感谢你。}
{231}{}{我听说治安官仍然控制着阿迪顿。你是不是没能像希望的那样干掉他们。}
{232}{}{别担心，我会处理的。}
{233}{}{我觉得我可能做不到。}
{234}{}{我们本来可以和你一起去，但没有武器治安官会杀了我们。也许还有另一种可能性【剃刀思考了一会儿】如果你能让枪械商人给我们提供武器，我们中有些人可以和你一起去。}
{235}{}{听起来不错。我去跟他们谈谈。}
{236}{}{我会再试着自己解决治安官。}
{237}{}{又见面了，我听说你一直在对付治安官。我想感谢你解决了他们。我的人现在可以和阿迪顿的人自由生活了。}
{238}{}{我会自己解决治安官。}
{239}{}{你会吗？如果你需要帮助或者已经解决了，回来找我聊聊。}
