{100}{}{从情况来看，他们不可能走得太远。他们的巢穴一定就在附近。}
{101}{}{他们似乎是从附近某个地方过来的。}
{102}{}{看起来他们是从这里以北的远处来的。}
{103}{}{显然，他们只是漫无目的地在废土中游荡。}
{104}{}{你偶然发现了一场激烈的战斗，辐射蝎子和鼹鼠正在厮杀。}
{105}{}{埋伏！！！}
{106}{}{你偶然发现了一大群辐射蝎子！}
{107}{}{你偶然发现了一群辐射蝎子。}
{108}{}{你偶然发现了一家鼹鼠。}
{109}{}{你通过寻找水源避免了严重的脱水。搜索花费了额外的一小时。}
{110}{}{你通过寻找水源避免了严重的脱水。搜索花费了额外的}
{111}{}{ 小时。}
{112}{}{你的水供应不足，经过一小时的搜索未能找到更多水源。严重的脱水导致你受到}
{113}{}{ 点生命值伤害。}
{114}{}{你的水供应不足，经过}
{115}{}{ 小时的搜索未能找到更多水源。严重的脱水导致你受到}
{116}{}{ 点生命值伤害。}
{117}{}{你在高地沙漠中寻找水源一小时，但未能找到足够的水来完全解渴。你受到了一点生命值伤害。}
{118}{}{你在高地沙漠中寻找水源一小时，但未能找到足够的水来完全解渴。你受到了}
{119}{}{ 点生命值伤害。}
{120}{}{你在高地沙漠中寻找水源}
{121}{}{ 小时，但未能找到足够的水来完全解渴。你受到了一点生命值伤害。}
{122}{}{你在高地沙漠中寻找水源}
{123}{}{ 小时，但未能找到足够的水来完全解渴。你受到了}
{124}{}{ 点生命值伤害。}
{125}{}{由于你的水供应，你避免了脱水。}
#{12600}{}{Radscorpions hunt Mole rats among the ruined city walls.}
{126}{}{你遇到了一些正在猎杀鼹鼠的辐射蝎子。}
{127}{}{瘦弱的绿色皮肤敌对人形生物靠近。}
{128}{}{废弃物和石头散落一地。}
{129}{}{一只孤独的辐射蝎子袭击了你！}
{130}{}{你注意到这里有一具被部分吃掉的尸体。}
{131}{}{惊慌逃窜！！！}
{132}{}{你偶然发现了一大群辐射蝎子！}
{133}{}{袭击者伏击了你！}
{134}{}{一群凶恶的辐射蝎子从沙漠中袭来！}
{135}{}{你遇到了一队巡逻的守卫。}
{136}{}{你遇到了一位商人和几个护卫。}
{137}{}{你看到一个农民在放牧几头双头牛。}
{143}{}{袭击者！！！}
{144}{}{你偶然发现了一大群鼹鼠。}
{145}{}{你遇到了一群野生辐射蝎子。}
{146}{}{你遇到了一些正在遭受攻击的农民。}
{169}{}{你偶然闯入了一家辐射蝎子。}
{170}{}{你遇到了一位旅行商人和护卫。}
{171}{}{你遇到了一名死去的旅行者。}
#{17100}{}{You encounter a traveler.}
#{17200}{}{You have stumbled across a small patch of ruined and deserted buildings.}
{172}{}{你偶然发现了一些散落在地上的物品。}
{173}{}{你发现了一支被袭击者洗劫的商队残骸。}
{196}{}{辐射蝎子来了！}
{197}{}{糟糕……一支袭击队！}
{198}{}{你在远处看到一个孤独的袭击者。}
{199}{}{你来到一个战场的遗迹，尸体遍地。}
{200}{}{辐射蝎子来了！}
{223}{}{你看到一群游荡的野生郊狼。}
{224}{}{你注意到几个人在四处侦查。}
{225}{}{你遇到了一小队商人和护卫。}
{226}{}{你看到一场小规模战争——人类对抗变种人！}
{227}{}{一大群辐射蝎子正朝这边来！}
{250}{}{几名穿着动力装甲的人正向你走来。}
{251}{}{你看到一群商人和护卫。}
{252}{}{你看到一场激烈的战斗正在进行，几名沙漠袭击者与一群穿着动力装甲的人激烈交战。}
{253}{}{你看到几个变种人在探索一片危险的土地。}
{254}{}{你看到前方有一些奇怪的生物……}
{25500}{}{你发现了一座小村庄的废墟。}
{255}{}{你找到了一些物品。}
{256}{}{一支超级变种人巡逻队正从附近经过！}
{279}{}{前方的沙地上散落着一些垃圾。}
{280}{}{你偶然遇到了一支超级变种人战斗小队。}
{281}{}{你偶然遇到了一群奇异的生物。}
{282}{}{你偶然遇到了一群饥饿的辐射蝎。}
{283}{}{你感到恶心，空气似乎因热浪而扭曲。}
{284}{}{你偶然发现了一个奇异的漂浮生物。}
{285}{}{你遇到了一个仿佛从老科幻电影中走出来的东西。}
{286}{}{死亡爪！！}
{287}{}{你误入了一群迁徙中的辐射蝎。}
{288}{}{你遇到了一只沙漠中的变异生物。}
{299}{}{你看到几只辐射蝎在远处。}
{300}{}{你遇到一个衣衫褴褛的农民。}
{301}{}{你遇到了一只鼹鼠。}
{302}{}{死亡爪！！}
{303}{}{你误入了一群迁徙中的辐射蝎。}
{304}{}{场景_类型 ==}
{305}{}{你发现了商人杜克的敌对护卫的遗骸。}
{306}{}{一支变种人巡逻队正从附近经过，随行的还有一些奇怪的生物！}
{307}{}{你遭到了一支小型超级变种人战斗小队的伏击。}
{308}{}{看起来你卷入了一场凶狠的帮派战争！}
{309}{}{一群敌对的帮派成员突然出现！}
{310}{}{一小群袭击者发动了攻击！}
{311}{}{一小群帮派成员发动了攻击！}
{312}{}{你突然遭到老鼠的袭击！}
{313}{}{你突然遭到一群螳螂的袭击！}
# Some special encounter text
{314}{}{嘿！他们真的在那里。}
{315}{}{你看到远处有一辆翻倒的卡车。}
{316}{}{你在荒地中偶然发现了一些损毁的车辆。}
{317}{}{在东北方向，你发现了一个警亭。}
{318}{}{你遇到了一群野生布拉明。你感觉有些不对劲……}

