{100}{}{你看到罗梅罗。}
{103}{}{你看到一个刀锋帮成员。}
{104}{}{你看到一个刀锋帮成员。}
{105}{}{你觉得那可能是书本。}
{106}{}{你觉得那可能是伤疤。}
{107}{}{你觉得那可能是枪手。}
{108}{}{你觉得那可能是抽搐。}
{109}{}{你觉得那可能是锤子。}
{110}{}{你觉得那可能是剃刀。}
{111}{}{站住！}
{112}{}{什么？你什么意思？}
{113}{}{绝不！}
{114}{}{我来谈和平。}
{115}{}{好吧。}
{116}{}{这里我来问问题。你来这里干什么？}
{117}{}{我来找一个朋友。}
{118}{}{我来谈和平。}
{119}{}{我想结束帮派战争！}
{120}{}{我想喝刀锋帮的血！}
{121}{}{那你找错地方了。滚开。}
{122}{}{你一定是那些软弱的小紫袍之一。滚开，否则我们就把你打飞。}
{123}{}{等等！我不知道你在说什么。我是为阿迪特姆来的。他们要我让大家别打扰他们。}
{124}{}{和平这个！}
{125}{}{抱歉。我这就走。}
{126}{}{嗯。如果你真是来自阿迪特姆，那你还是个失败者。只要那些撕裂者还在，就不可能有和平。}
{127}{}{你什么意思？}
{128}{}{呃，当然。}
{129}{}{去问剃刀。她会解释那些嗜血的近亲繁殖者。}
{130}{}{滚开！}
{131}{}{嘿，既然你现在是刀锋帮的一员，我需要你帮个忙。}
{132}{}{当然。}
{133}{}{有什么事？}
{134}{}{不可能。}
{135}{}{太好了。把这个项链交给朱莉安娜。告诉她我希望能很快见到她。}
{136}{}{看来我爱上了阿迪顿的一个女孩。因为治安官们一见到我们就开枪，我无法接近她。}
{137}{}{我能帮什么忙？}
{138}{}{继续说。}
{139}{}{真是倒霉。}
{140}{}{如果你能把这条项链交给朱莉安娜，我会感激不尽。}
{141}{}{没问题。}
{142}{}{找别人吧。}
{143}{}{有你这样的盟友，谁还需要敌人？再见！}
{144}{}{我想她也爱我，但我不确定。刀锋帮不会冒险让我尝试潜入阿迪顿。}
{145}{}{真是倒霉。}
{146}{}{好吧，我来帮你。}
{147}{}{谢谢你！她给我写了封信。我们打算在追随者的地方见面并结婚。}
{148}{}{欢迎回来。}
{149}{}{非常感谢。我们现在会和追随者们待在一起，在这里幸福地结婚。}
