{100}{}{你看到史密蒂。}
{101}{}{你看到一个高大、肌肉发达的男人。}
{102}{}{你好，有什么我可以帮忙的吗？}
{103}{}{你想要什么？}
{104}{}{我可以问一下你的名字吗？}
{105}{}{我需要你帮我修理这些零件，这样我才能修复你的水培农场。}
{106}{}{我想买点东西。}
{107}{}{我可以问你几个问题吗？}
{108}{}{没事，谢谢。回头见。}
{109}{}{呃……}
{110}{}{我建议你去看看泰恩的商店，就在大门旁边。我这里其实不卖东西；我把东西交易给泰恩或集市的商人。}
{111}{}{为什么，大家都叫我‘史密蒂’。可能因为我是这里的铁匠。}
{112}{}{尽管问吧。}
{113}{}{你的店铺设备是从哪里来的？}
{114}{}{你在这里都做些什么？}
{115}{}{你能制造枪支和子弹吗？}
{116}{}{没别的了，谢谢。}
{117}{}{抱歉，我想我帮不了你。试试找齐默曼。}
{118}{}{当然。}
{119}{}{为什么，任何有能力的铁匠都能自己做铁砧！当然，我基本上是通过实践学会这门手艺的，但我大部分工具都是自己做的。}
{120}{}{我主要在这里制造和修理工具和器具。我也为集市的商人修东西。在化学家迈尔斯的帮助下，我偶尔会重新装填子弹。}
{121}{}{嗯，制造枪支和弹壳需要机械加工，而我没有那样的工具。但在化学家迈尔斯的帮助下，我可以重新装填旧的弹壳，因为我能铸造子弹。}
{122}{}{是的，我可以修好这个。给我点时间。}
{123}{}{给你。 [史密蒂把修好的零件递给你。]}
{124}{}{我已经修好了零件。你现在需要把它们交给迈尔斯。}
{125}{}{谢谢你修好了农场。如果你有一天找到一把等离子步枪，带回来给我。我知道一些关于注射器的小技巧。}
{126}{}{嗯，我这里正好有一把。}
{127}{}{所以你找到了一把等离子步枪！}
{128}{}{把它给我，我来看看。 [史密蒂从你手中接过等离子步枪，拿出工具，开始摆弄它。]}
{129}{}{好了，我想这就行了。 [史密蒂把等离子步枪还给你。] 试试看效果如何。}
{130}{}{就像我之前说的，如果你能弄到一把等离子步枪并带回来，我可以帮你改装一下。}
{131}{}{很高兴再次见到你。希望你一切都好。}
