{100}{}{我可以做到。}
{101}{}{这很简单。}
{102}{}{让我来展示怎么做。}
{103}{}{不错。}
{104}{}{啊，我明白了。}
{105}{}{哦，动作不错。}
{106}{}{原来是这样做的。}
{107}{}{我永远做不到。}
{108}{}{动作到位。}
{109}{}{确实。}
{110}{}{注意看。}
{111}{}{别无礼。}
{112}{}{听着。}
{113}{}{嘘！}
{114}{}{请让开。}
{115}{}{谢谢。}
