{100}{}{你看到卡特琳娜。她有一个非常迷人的微笑。}
{101}{}{我没有武器，请把你的武器收起来。}
{102}{}{哼！}
{103}{}{我为什么要这样做？这个世界看起来很危险。}
{104}{}{为什么这么说？}
{105}{}{也许我会，也许我不会。}
{106}{}{我就当你是答应了。}
{107}{}{通常来说，我会同意你的看法。旅行时没有武器确实很危险。但这里是阴影镇，我们是一个和平的村庄。在这里不需要武器。}
{108}{}{好的，谢谢。}
{109}{}{如果你不把武器收起来，我就不和你说话。很多人都和我一样。只有在必要时才应该使用武力。}
{110}{}{嗯，好吧。}
{111}{}{欢迎来到阴影镇，旅行者。我叫卡特琳娜。我的工作是迎接陌生人并帮助他们了解我们的村庄。如果你听我说的话，我们的问题会少很多。}
{112}{}{乌巴！}
{113}{}{告诉我更多关于你的事情。}
{114}{}{请帮帮我……}
{115}{}{我在找一个水芯片。见过吗？}
{116}{}{我需要帮助找坦迪。}
{117}{}{我正在处理你们的蝎子问题。有线索吗？}
{118}{}{谢谢，也许以后吧。}
{119}{}{很遗憾你有些愚钝。我们之间的交流会有困难。我希望你们避难所的其他人不像你这样。}
{120}{}{乌巴-瓦？}
{121}{}{是的，我能看出你来自避难所。你有那种特征。我来自东边的15号避难所。但我不得不离开家，现在住在这里。希望你能找到你要找的东西，即使只是另一个居住的地方。我希望你的避难所不是因为你的智力而把你赶出来的。我真心希望有其他原因。}
{122}{}{哼。}
{123}{}{你需要找到其他方法来获得答案，因为你无法很好地沟通。希望你在旅途中不要伤害太多人。请对这里的人友好，我们对你没有恶意。}
{124}{}{啊。}
{125}{}{我很乐意帮助你。我自己曾经也像你一样。希望我的知识对你有用。}
{126}{}{如果我受伤了该怎么办？}
{127}{}{我在哪里能找到更好的装备？}
{128}{}{告诉我关于这个地方的情况。}
{129}{}{告诉我关于这个世界其他地方的情况。}
{130}{}{告诉我关于你自己的事。}
{131}{}{现在就这样吧，谢谢。}
{132}{}{如果你无法找到医生，你需要自己疗伤。刺激药是常见的治疗物品。使用它们可以治疗轻伤。急救虽然较慢，但总是可用的。对于严重的伤，比如骨折，你需要使用医疗技能。}
{133}{}{你得像我们一样。搜集或交易。如果你被攻击，你的敌人可能会提供装备，前提是你能活着抢到。我们是个和平的社区，所以大多通过以物易物来获取我们无法生产的物品。}
{134}{}{告诉我更多关于以物易物的事。}
{135}{}{你现在站在阴影镇。我们只是这个大世界中的一个小镇。我们只想安静地生活。除了变异动物和其他沙漠生物，只有掠夺者会给我们带来麻烦。阿拉迪什是我们的领袖，他在中央的大房子里，去找他说话。}
{136}{}{我对外面的世界知之甚少。我从一个避难所逃出来时遭到了攻击。不幸的是，我受了重伤，对发生的事情记不太清。但达摩在看护着我，阴影镇的人们找到了我。我现在住在这里。你和伊恩谈过了吗？他是个商队护卫，受了伤，正在那边的警卫室恢复。[她指向东边]他比我见多识广。}
{137}{}{我的生活曾经非常无聊。我在避难所长大，在那里生活了很多年。不幸的是，我们人满为患，生活很糟糕。发生了分裂，很多人带着最好的设备离开了。尽管如此，我们中的一些人还是试图留在避难所。但后来我们遭到了攻击。我受了伤，最后到了这里。现在我尽力帮助他人……}
{138}{}{你的避难所在哪里？}
{139}{}{以物易物就是交换物品。你给我一些物品，我用其他物品和你交换。既然是你发起的交易，我会让你挑选你想要的东西。但交易必须是我认为合适的，所以你可能需要用更有价值的物品来换取你想要的便宜物品。如果你没有足够的物品来交易，还有瓶盖。瓶盖是这里唯一通用的货币，由集散地的商人们担保，所以你可以在任何地方用它们交易。}
{140}{}{是15号避难所，就在这里的正东方向。我们试图与其他避难所联系，但总是失败。我想是掠夺者袭击了我的同胞。小心点！}
{141}{}{希望你能找到她。她就像我的小妹妹。我想是某个掠夺者团伙抓走了她。尽可能多地了解他们的信息，并在去找他们之前装备好自己。但不要急于动武，有时他们也会听从理智……}
{142}{}{赛斯一直在试图追踪辐射蝎。他声称甚至知道它们巢穴的路，但我觉得他有点害怕去那里。他的兄弟被一个变种人严重伤害，赛斯不知道该怎么办。}
{143}{}{事实上，是的。我的老家，15号避难所，有一个。我自从受伤后就没去过那里，但你可能会在那里找到你要找的东西。有人说他们试图去避难所看看，但那里很黑，电梯坏了。希望你准备得更充分。}
{144}{}{又见面了。希望你一切都好。我能帮你什么吗？}
{145}{}{你难道从不睡觉吗？}
{146}{}{嗯，当你不在的时候我会打个盹。而且，我觉得沙漠的空气非常提神健康。我从不厌倦看星星。你能想象一辈子都看不到夜空吗？[她停顿了一下，看着你]哦，我想你能。}
{147}{}{啊，是的。谢谢。}
{148}{}{这里有医生吗？}
{149}{}{像阴影镇这样的小地方如果没有治疗者是无法生存的。我们的医生拉兹洛住在最南边的房子里。如果你伤得很重，去找他。尽量不要在晚上打扰他。他没睡够的时候脾气很差。}
{150}{}{你因为从卡特琳娜那里获得的知识而获得了250点经验值。}
{151}{}{这里通常会绞死小偷。要乖哦。}
