{100}{}{你看到特里。}
{101}{}{水配给是在晚上发放的……嘿，你不是个食尸鬼！}
{102}{}{这不重要。重要的是老大的位置。}
{103}{}{不，我不是。}
{104}{}{嗯。}
{105}{}{我带你去见他。来，我帮你一把。}
{106}{}{我最好带你去找哈利，他会知道怎么处理你。}
{107}{}{嘿，别说话！这会打扰我思考。}
{108}{}{现在是什么时间？}
{109}{}{变种人无视了你。}

{1000}{}{芯片}
{1001}{}{死城}
{1002}{}{赛特}
{1003}{}{水坝区}
{1004}{}{大厅}
{1005}{}{卢}
{1006}{}{食尸鬼}
{1007}{}{正常人}

{1100}{}{我不知道。}
{1101}{}{你就站在这里。}
{1102}{}{他是个软蛋。我们应该直接干掉他和他的食尸鬼。}
{1103}{}{就是这里。}
{1104}{}{我不知道。}
{1105}{}{他是哈利的老大。}
{1106}{}{软弱的东西。}
{1107}{}{比食尸鬼还软弱。}
