{100}{}{你看到一个阴影镇的守卫。}
{101}{}{嘿，我觉得你最好离开。我们不欢迎你这种人。}
{102}{}{真不敢相信坦迪失踪了。我希望你能找到她。如果她出了什么事，阿拉戴什会很伤心的。}
{103}{}{谢谢你带回坦迪。这对未来是个好兆头，不是吗？}
{104}{}{坦迪的事真让人遗憾。我希望阿拉戴什能撑住。}
{105}{}{欢迎，陌生人。我们这里不常见到你这样的人。}
{106}{}{呃，谢谢。再见。}
{107}{}{为什么不？}
{108}{}{哼！}
{109}{}{慢着！这是个小社区。我们不常见到陌生人，也不太需要他们，你明白我的意思。如果你没有正当理由留在这里，最好还是继续赶路吧。}
{110}{}{嘿，我不会伤害任何人。}
{111}{}{呃。}
{112}{}{我不是说你会。你最好还是别打扰我们。}
{113}{}{我会尽量不惹麻烦。}
{114}{}{我受够了你的废话。准备见上帝吧。}
{115}{}{听着，阴影镇不需要你这种来自枢纽城或废城的人。我们自己过得挺好。}
{116}{}{上次从枢纽城来的商人卖给我们一个坏掉的灌溉泵。我们受够你们这些肮脏的交易了。}
{117}{}{你搞错了。我不是那样的人。}
{118}{}{是吗？你这么说。别惹麻烦，行吗？}
{119}{}{没问题。}
{120}{}{好吧，随便你。}
{121}{}{也许你不是。你看起来有点与众不同。我告诉你，你应该去找阿拉戴什谈谈。他在镇中心。}
{122}{}{我们不欢迎你这种人。回你来的地方去吧。}
{123}{}{嘿，不需要武器。我们这里不太喜欢那些。}
{124}{}{嘿，你最终并不是个坏人。祝你有美好的一天。}
{125}{}{我真希望你能离开这个镇。}
{126}{}{[更多]}
