{100}{}{你看到托利亚，一个沙漠强盗。}
{101}{}{你好，我是托利亚。看起来你刚从沙漠中走出来。你是谁？}
{102}{}{我是}
{103}{}{。你是做什么的？}
{104}{}{你能告诉我关于你们营地的事吗？}
{105}{}{嗯？}
{106}{}{作为一个掠夺者，我在土地上探索寻找新的补给。有些城镇曾受到过我们的光临。}
{107}{}{换句话说，你们就是从你们拜访的人那里偷东西。}
{108}{}{嘿，那真是太好了。我相信加尔一定对你很满意。}
{109}{}{你去过哪些地方？}
{110}{}{来吧，加尔告诉我不要和陌生人说话。你至少应该愿意告诉我你的名字。}
{111}{}{你说得对。我是}
{112}{}{。你能告诉我一些关于你们帮派的事吗？}
{113}{}{听着，白痴，我没有必要告诉你任何事情。}
{114}{}{滚开，蠢货。}
{115}{}{我们从不偷窃。我们只是拿走别人多余的东西，然后在我们饥饿的人中重新分配。}
{116}{}{所以，基本上，你们就是在偷。}
{117}{}{听起来真是个好主意。}
{118}{}{我去过废土的许多地方。最近的地方是阴影镇和废城。他们对我们的拜访非常感激。}
{119}{}{你们去过阴影镇？}
{120}{}{废城在哪里？}
{121}{}{你现在开始让我烦了。我想我会解决这个小问题。}
{122}{}{我们是可汗，我们的首领是加尔。我们是废土中最令人畏惧的团体，这是有充分理由的。我们想要什么就拿什么，挡我们路的人会付出代价。}
{123}{}{是的，我们不时去阴影镇。这给所有相关的人带来了一点刺激。}
{124}{}{那废城呢？}
{125}{}{哦，废城就在这里南边一点。走几英里，在快枯死的仙人掌那里右转。你不会错过的！}
{126}{}{你也说过你们去过阴影镇。}
{127}{}{现在别打扰我。我正在为下次袭击做准备。}
