{100}{}{离我远点！别来烦我！}
{101}{}{你好，陌生人。你不该在这里，这里只有死亡！}
{102}{}{你知道关于失踪商队的事吗？}
{103}{}{你是谁？}
{104}{}{什么样的死亡？}
{105}{}{我需要一些补给。交出来！}
{106}{}{我在找一个水芯片。你能帮我吗？}
{107}{}{我想知道你对死亡爪了解多少。}
{108}{}{咕？嗅？}
{109}{}{你想干什么！别来烦我！}
{110}{}{咕。嗤。}
{111}{}{大！大！像三个人那么大！爪子有我前臂那么长！撕碎了！撕碎了！}
{112}{}{是的。还有呢？}
{113}{}{冷静点，伙计。你现在安全了。}
{114}{}{伙计，那听起来真是个丑陋的怪物！}
{115}{}{你杀了它吗？}
{116}{}{我是特伦特。我是水商的护卫。我们的商队被袭击了……被一个怪物！如此巨大，如此迅速。它吃掉了乔，中了几枪都不动！太大了！}
{117}{}{是什么袭击了你们？}
{118}{}{听起来像是一种变种怪物。}
{119}{}{那听起来像是死亡爪！}
{120}{}{好吧，这会教会你别再抬高价格了！}
{121}{}{好吧。反正我也不再需要它们了。}
{122}{}{水芯片！我是护卫，不是工程师！去中心城找水商，他们可能知道！}
{123}{}{死亡爪！}
{124}{}{你在干什么？别来烦我！}
{125}{}{我……我不知道。我已经很久没睡了。又饿又渴又累。我得回家。}
{126}{}{}
{127}{}{巨大的角，病态的红皮，像是从恶魔故事里出来的东西，三口就吃掉了乔……}
{128}{}{没人安全！没人安全了，我该怎么办……}
{129}{}{你疯了吗！我用沙漠之鹰打了它三枪，它连动都不动！}
{130}{}{我不在乎它是变种人、外星人，还是来自地狱的恶魔，我这辈子再也不想看到那种东西了！}
{131}{}{我只是个守卫，天啊！别怪我！而且他们给我报酬很高！我对他们没有任何意见！}
{132}{}{我能帮你什么忙？}
{133}{}{是死亡爪干的。我原以为那只是传说，但……你不会相信它们有多大，或者有多快。我们先是闻到了它们的味道，然后它们就从山脊上冲下来撕扯我们。我们都跑了，我不知道怎么逃出来的。}
{134}{}{特伦特，特伦特·巴里斯特。我住在集散地。最近工作越来越少，而我枪法不错，所以我就给水商当了守卫。薪水不错，风险低——至少我是这么想的。}
{135}{}{我一点头绪都没有。那是老技术，不是吗？我想拾荒者偶尔可能会找到一个，但我不知道从哪里开始找。没人再用了——是吗？}
{136}{}{它们很大。像大蜥蜴，但皮革般的。巨大的爪子和牙齿，还有巨大的角，它们喜欢人肉的味道。而且速度快，天啊，它们太快了。我很庆幸它们没追我，否则我就死定了。}
{137}{}{谢谢。也许发生的事情只是个误会。我没多少钱，但现在是你的了。}
{138}{}{谢谢。哦，天啊，这太好了……我没多少钱，但现在是你的了。}
{139}{}{谢谢。也许发生的事情只是个误会。我没多少钱，但……该死！我一定是掉了。现在是你的了。}
{140}{}{谢谢。哦，天啊，这太好了……我没多少钱，但……该死！我一定是掉了。现在是你的了。}
{141}{}{救救我！}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{142}{}{死亡的气息，我的朋友。死亡的气息……}
{143}{}{死亡的气息，我的朋友。死亡的气息……}
