{100}{}{地板下藏有一枚手雷。}
{101}{}{ 它没有被引爆。}
{102}{}{你成功拆除了陷阱，并取下了等离子手雷。}
{103}{}{你正要从引爆开关上拆下绊线时，不小心掉了保险销，引爆了手雷！}
{104}{}{你试图稍微抬起面板并拆除陷阱，但无法在不拉动绊线的情况下抬起。}
{105}{}{你撬起了面板，但无法牢牢抓住手雷。}
{106}{}{你抬起了面板，但在移除之前绊线从你手中滑落。}
