{100}{}{你看到一个女人。}
{101}{}{先生，我不想死。我不是士兵。}
{102}{}{女士，我不想死。我不是士兵。}
{103}{}{开始说话，我就让你活命。}
{104}{}{我也不是。我只在必要时才杀人。}
{105}{}{你难道不该赞美主宰或者什么的吗！}
{106}{}{我用你的命换一杯烈酒。他们把酒藏在哪儿？}
{107}{}{晚安，贱人！}
{108}{}{我大兵！哈哈哈！}
{109}{}{很高兴你来找我谈话。我听说了你对劳拉说的话。你不能这么做。}
{110}{}{你觉得我会做什么？}
{111}{}{劳拉？劳拉是谁？}
{112}{}{哦，哦。}
{113}{}{哦，那是个大错误！你会付出代价的。}
{114}{}{什么说？嗷！}
{115}{}{我想我们已经说完了。再见。}
{116}{}{我不和拿武器指着我的人说话。放下武器，我们再谈。}
{117}{}{又见面了。希望你觉得这个地方有趣。}
{118}{}{我见过更高雅的娱乐。}
{119}{}{当然，姐妹。赞美主宰！赞美圣焰！}
{120}{}{你知道吗，每次我和人说话，人们总是反复重复他们说的话。}
{121}{}{娱乐？酒在哪儿！}
{122}{}{这个地方真无聊！血呢？死亡呢？}
{123}{}{问候，见习者。我能为你做些什么？}
{124}{}{我对我们的长远计划有点担心。}
{125}{}{这里发生了什么？}
{126}{}{主宰在哪儿？}
{127}{}{这里谁负责？}
{128}{}{别开玩笑了，姐妹。没人会在没有枪指着头的情况下为别人服务！}
{129}{}{您好，先生。您的名声在外！有什么我可以帮您的吗？}
{130}{}{您好，小姐。您的名声早已传遍四方！有什么我可以帮您的吗？}
{131}{}{我想知道大教堂是做什么的。}
{132}{}{如何成为一名信徒？}
{133}{}{大师在哪里？}
{134}{}{这里由谁负责？}
{135}{}{别开玩笑了，姐妹。没有人会在没有枪指着头的情况下为别人服务！}
{136}{}{您好，先生。您的名声早已传遍四方！有什么我可以帮您的吗？}
{137}{}{您好，小姐。您的名声早已传遍四方！有什么我可以帮您的吗？}
{138}{}{我想知道大教堂是做什么的。}
{139}{}{如何成为一名信徒？}
{140}{}{大师在哪里？}
{141}{}{这里由谁负责？}
{142}{}{别开玩笑了，姐妹。没有人会在没有枪指着头的情况下为别人服务！}
{143}{}{我知道你是谁。请原谅我的无礼，但我不和精神病杀手说话。再见。}
{144}{}{我的名声被大大夸大了。大教堂是根据传闻和暗示来评判人的吗？}
{145}{}{精神病杀手？谁，难道是我！}
{146}{}{宝贝，我不是疯子，我只是有点疯狂，如果你不回答我的问题，我会证明给你看！}
{147}{}{我不轻易建立忠诚的纽带，也不轻易打破它们。我什么都不会告诉你。}
{148}{}{很好。那我们就互不打扰，算是扯平了。}
{149}{}{赞美大师无法保住我的性命。来吧，动手吧。我无能为力。}
{150}{}{在远离大教堂的地方有个酿酒厂。他们不允许这里有化学品或酒精。}
{151}{}{试图从莫菲斯那里拿到秘密入口的钥匙并杀掉大师。}
{152}{}{我为什么不想这么做？}
{153}{}{我不知道你在说什么。}
{154}{}{我为什么要这么做？}
{155}{}{你听说过知道太多的事吗？}
{156}{}{在冥想室中的那个启示录追随者的间谍。}
{157}{}{这里有间谍？我们必须立刻通知大祭司！}
{158}{}{我不知道你在说什么。}
{159}{}{我为什么要监视你们？}
{160}{}{你听说过知道得太多吗？}
{161}{}{这个地方不是为了娱乐，而是为了启迪。更重要的是，这里是为了为世界的命运做出正确的选择。回头见。}
{162}{}{对，当然。回头见。}
{163}{}{我知道。当我无话可说时，我也常这样。回头见。}
{164}{}{拥有圣焰精神的人不需要其他精神。或者他们是这么说的。你知道这意味着什么_}
{165}{}{在楼上。让夜行者帮你流点血，他们会很乐意效劳。}
{166}{}{因为主宰是必要的恶。因为必须有人来统一这个世界，而他是唯一有机会做到这一点的人。}
{167}{}{有人告诉过你，统一被高估了吗？}
{168}{}{为什么？}
{169}{}{我不相信必要的恶。}
{170}{}{我觉得这个世界挺好。}
{171}{}{我不喜欢这个话题。}
{172}{}{好吧，如果你不承认你说过的话，我就不帮你。再见。}
{173}{}{因为你认为孩子们不该入侵我们的邻居。因为你认为杀掉主宰会阻止这一切。}
{174}{}{如果我相信这一点，那我为什么会错呢？}
{175}{}{那是亵渎！}
{176}{}{如果你认为我相信这些，为什么不把我交出去？}
{177}{}{我看起来像是介意杀戮的人吗？}
{178}{}{你听说过自不量力吗？不管装备多好或训练多精良，没有人能打败半打夜行者。我是个和平主义者，我在试图救你。}
{179}{}{看看那些引发末日的人！他们不相信和平与统一，看看他们对我们做了什么！统一是防止这种情况再次发生的唯一方法，而统一必须现在就实现，在世界其他避难所有机会集结力量之前。}
{180}{}{你看起来比这群僵尸聪明多了。}
{181}{}{你想让每个人都像这个房间里的人一样？那比死了还糟！}
{182}{}{你疯了！那只会导致另一个末日。}
{183}{}{为什么主宰是最适合领导我们的人？}
{184}{}{你从来没杀过人？你没有足够的火力让钢铁兄弟会嫉妒？别再虚伪了！你觉得自卫是正当的。主宰是在保护人类免于再次自我毁灭。这都是一样的！}
{185}{}{你怎么知道外面没有更好的人选？}
{186}{}{也许我该考虑一下。}
{187}{}{所以只要是为了拯救世界，大屠杀就可以吗？}
{188}{}{胡说八道，女士！}
{189}{}{你以为这个世界是什么样的？外面简直是个噩梦！}
{190}{}{你怎么知道外面没有更好的东西呢？}
{191}{}{也许我应该考虑一下。}
{192}{}{一个我可以自由选择自己生活的世界。}
{193}{}{生活从来都不美好，姐妹。过去不是，将来也不会是。}
{194}{}{很难。我不喜欢辐射和FEV病毒，但我没有选择。这个世界上你不能总是得到你想要的。有时候你得妥协，有时候你得接受那些不愉快的想法。}
{195}{}{有趣。我没看到主宰允许他的信徒这样做。}
{196}{}{妥协和种族灭绝是两回事。}
{197}{}{离我远点！}
{198}{}{我现在唯一关心的选择就是你还能活多久。}
{199}{}{也许当主宰掌权时，我会变得如此聪明，可以有所作为。也许你也可以！加入我们！加入我们，改变世界！只要考虑一下，这就是我唯一的请求！}
{200}{}{任何社会都有工蜂。忘了他们吧！我们需要工蜂，但我们也需要战士和女王。而你看起来至少是个好战士。考虑一下你能做什么，你可以对我们的事业非常有用。帮助我们。想想我说的话，这就是我唯一的请求！}
{201}{}{或者也许我们可以在他们有时间重新集结之前压倒他们的防御。也许我们可以用一次迅速而干净的打击来团结其他避难所和城市。一个团结的世界不会完美，但它更有可能维持下去。想想吧！}
{202}{}{我观察过当地人。钢铁兄弟会和启示录之子只想独善其身。商人城以为他们能买下世界——真是一群傻瓜！只有主宰有力量去做必须做的事。想想吧！}
{203}{}{很高兴听到这个。希望你能做出正确的决定。}
{204}{}{不。这并不完全正确。但这是唯一有可能长期拯救我们的选择，这就是我和这些人在一起的原因。没有更好的办法！想想吧！}
{205}{}{是吗？好好想想。如果你继续反对我们，你会死的。你见过我们的力量，你知道还有更多。很多更多！你阻止不了我们！但如果你加入我们，你可以拯救生命。好好想想！}
{206}{}{我不知道。但如果我看到我喜欢的人，我会帮助他们。当地人没有机会。他们都死了，或者如果幸运的话被转化。你可以成为幸运的人之一。加入我们。好好想想！}
{207}{}{世界不会一直这样。它从来不会。如果我们只建立强大的飞地，最终其中一个会变得足够强大，再次引发末日。加入我们，在这发生之前团结世界！好好想想！}
{208}{}{这只是一个懦弱的借口，解决不了任何问题。如果生活很糟糕，我们应该努力改变它。我们欠自己和我们的孩子。你认为当我们分裂成交战的碎片时，世界会保持不变吗？好好想想！}
{209}{}{或者也许有一种伪装成种族灭绝的救赎。也许如果人们为主宰的愿景而努力，世界就不会那么糟糕。也许我们甚至可以找到更少流血的方法。好好想想！}
{210}{}{好吧。但如果你继续现在的道路，你会死的。我觉得我应该警告你。}
{211}{}{你可以杀了我。当然，你会证明我的观点，但我还是会死。这是你的选择。}
{212}{}{因为末日！看看它对我们做了什么！团结是防止这种情况再次发生的唯一方法，团结必须现在就发生，在世界其他避难所有机会集结力量之前。}
{213}{}{你看起来比这群僵尸聪明多了。}
{214}{}{你想让每个人都像这个房间里的人一样？那比死还糟！}
{215}{}{我会考虑的。}
{216}{}{你疯了！那只会导致另一次末日。}
{217}{}{为什么主宰是带领我们的最佳人选？}
{218}{}{我不是哲学家女士。我只是个擅长杀人的人。}
{219}{}{因为你是一个聪明而勇敢的人，可以对我们有很大帮助。是的，我们做的一些事情很可怕。但我们的总体目标不仅是好的，而且对人类的生存是必要的。不要急于帮助追随者。他们没有所有的答案！}
{220}{}{你看起来比这群僵尸聪明多了。}
{221}{}{你想让所有人都像这个房间里的人一样？那比死了还糟糕！}
{222}{}{我会考虑的。}
{223}{}{你疯了！那只会导致另一次末日。}
{224}{}{为什么大师是最适合领导我们的人？}
{225}{}{我不是哲学家女士。我只是个擅长杀戮的人。}
{226}{}{我们都有自己的角色。有些人是无脑的工蜂，做着那些愚蠢的工作。有些人是思想者。有些人是杀手。如果你愿意，这里有你的一席之地。请考虑一下！}
{227}{}{我们计划了很多事情。圣火首先降临，净化了世界的邪恶。然后是大师的出现。现在是统一的时刻，我们努力克服世界的分裂。在统一之后将迎来和平。和平时代是我们所有奋斗的原因。}
{228}{}{为什么为了获得和平要死这么多人？}
{229}{}{听起来真不错。赞美大师！}
{230}{}{但末日之火不是邪恶的吗？}
{231}{}{这听起来像是胡扯。}
{232}{}{我相信你。紧张是一种明智的情绪，它让我们不去探究不愉快的角落，并防止我们做傻事。再见。}
{233}{}{初学者在寻找问题的答案。这正是你应该做的。再见。}
{234}{}{我不知道。人们相信他的灵魂就在这些墙内。对我来说确实听起来像这样。}
{235}{}{人们对他的实体形态怎么说？}
{236}{}{我听到了一丝怀疑吗？}
{237}{}{真的有大师，还是这只是个骗局？}
{238}{}{这是个让人恼火的模糊答案。}
{239}{}{谢谢你，姐妹。}
{240}{}{大教堂的高阶祭司是墨菲斯。他在上层圣殿，但不接受私人会见。你可以试着说服拉舍神父为你担保，他在下面的教区办公室。}
{241}{}{墨菲斯？他是个好人吗？}
{242}{}{为什么他们叫他拉舍？}
{243}{}{那大师呢？}
{244}{}{还有什么我应该知道的吗？}
{245}{}{谢谢你，姐妹。}
{246}{}{你可能会改变主意。或者你可能会失去生命。这一切取决于你的行动和观点。再见。}
{247}{}{我们有非常相似的兴趣。你杀死了怪物和强盗，让世界变得更安全。我们计划在更大范围内做同样的事情。}
{248}{}{什么样的范围？}
{249}{}{你们计划要消灭的怪物和强盗是谁？}
{250}{}{这和我一直听说的圣焰有什么关系吗？}
{251}{}{抱歉女士，我不相信你说的任何话。}
{252}{}{多么美妙啊。赞美大师！赞美圣焰！}
{253}{}{当然是和平、爱与统一。我们还能追求什么呢？不过你可以自己去发现这些。再见。}
{254}{}{你应该在这里进行几周的冥想和禁食，然后去找一位长老。或者你可以志愿参加服务工作。}
{255}{}{我注意到你们的人在其他城镇出现过……}
{256}{}{我该找谁报名志愿服务？}
{257}{}{几周！那可真长。}
{258}{}{哪位长老比较适合接触？}
{259}{}{服务工作？比如说消灭你们的敌人？}
{260}{}{我很抱歉。至少，你可能真心在为自己的罪行寻求救赎。我能帮你什么忙？}
{261}{}{我想知道大教堂是怎么回事。}
{262}{}{怎么成为一名入门者？}
{263}{}{大师在哪里？}
{264}{}{这里谁负责？}
{265}{}{别开玩笑了，小姐！没人会在没有枪指着头的情况下为别人服务！}
{266}{}{让疯狗进家门是危险的，只因为你看不到它的口水。再见。}
{267}{}{那么你被诽谤了，因为整个骨园都在讲述关于你的恐怖故事。我不想知道这些故事是真是假。再见。}
{268}{}{没有斗争是没有代价的，而最大的斗争必然带来最大的代价。这就是和平的悖论，我恐怕。无论如何，值得思考的话。再见。}
{269}{}{这是一个悖论。当然如此，但最大的邪恶可以引导出最大的善良。所需的只是幸存者的智慧和勇气。无论如何，值得思考的话。再见。}
{270}{}{我们不应该以外貌来评判人。大师的目标是高尚的，这就是我所需要知道的。至于其他人说什么，去问他们吧。}
{271}{}{也许有一点。大师的愿景如此宏大和辉煌，我想我可以被原谅一些疑虑。如果我让你失望了，我很抱歉。我建议你去找比我更坚强的人学习。再见。}
{272}{}{当然有大师！为什么不会有呢？我们做了很多事情，甚至有些我并不完全自豪，但欺骗不是其中之一。大师的和平与统一愿景是真实的。再见。}
{273}{}{“我不知道”没有什么模糊的。再见，先生。}
{274}{}{“我不知道”没有什么模糊的。再见，小姐。}
{275}{}{不客气，先生。愿大师赐予你智慧。}
{276}{}{不客气，小姐。愿大师赐予你智慧。}
{277}{}{他是个聪明人，并且得到大师的信任。这就足够了。愿大师赐予你智慧。再见。}
{278}{}{他教育孩子们，而且非常严格。还有其他问题吗？}
{279}{}{莫菲斯？他是个好人吗？}
{280}{}{为什么要允许拉舍伤害孩子？}
{281}{}{那主人呢？}
{282}{}{还有什么是我应该知道的吗？}
{283}{}{谢谢你，姐姐。}
{284}{}{我无法告诉你任何你不知道的事情。很抱歉。}
{285}{}{我相信有很多事情，但这些答案最好由我们自己发现，而不是通过谣言和暗示。再见。}
{286}{}{不客气，先生。}
{287}{}{不客气，小姐。}
{288}{}{尽可能广泛。世界处于混乱之中，需要秩序，否则将无法存续。我们将带来秩序，防止怪物再度如末日那样伤害它。无论如何，这是值得思考的事情。再见。}
{289}{}{那些让自私欲望对抗人类更大利益的人。末日是由人类自私引起的。如果世界要存活，这种疯狂必须从人类心中清除。无论如何，这是值得思考的事情。再见。}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{曾经有迪肯·奥利弗；不，她已经不在了_还有皮诺切神父_不，他也不再可用了。我犹豫说起拉舍，但现在他是唯一剩下的。好吧，我相信你会找到办法的。祝好运。}
{295}{}{死亡从不是一种服务，即便在必要时也是如此。再见，先生。}
{296}{}{死亡从不是一种服务，即便在必要时也是如此。再见，小姐。}
{297}{}{这是我自己也想知道的问题。但我确信这种批评是不必要的。也许你该去问问孩子们。}
{298}{}{[完成]}
{299}{}{我走。}

{300}{}{我们曾更早地接收过新成员，但教会正在进行一些重大十字军行动，我想我们对新成员的选择比往常更谨慎了。但信仰会坚持，耐心是一种美德。祝好运，我的朋友。}
{301}{}{我们曾更早地接收过新成员，但教会正在进行一些重大十字军行动，我想我们对新成员的选择比往常更谨慎了。但信仰会坚持，耐心是一种美德。祝好运，我的朋友。}
{302}{}{我不知道有再次召唤圣火的计划。圣火之所以神圣，只是因为它给予我们一个净化世界不完美之处的机会。是我们的行为使火焰神圣。我们必须将世界的邪恶变成善良的工具。正如你的武器保卫你的生命，我们的行为保卫世界。再见，朋友。}
{303}{}{我不知道有再次召唤圣火的计划。圣火之所以神圣，只是因为它给予我们一个净化世界不完美之处的机会。是我们的行为使火焰神圣。我们必须将世界的邪恶变成善良的工具。正如你的武器保卫你的生命，我们的行为保卫世界。再见，朋友。}
{304}{}{我们为人们提供了许多服务。治愈病人，充饥解渴，教育年轻人。我对此感到非常自豪。如果你找到莫菲厄斯神父，他也许能告诉你如何参与我们的救济院。再见，朋友。}
{305}{}{我们为人们提供了许多服务。治愈病人，充饥解渴，教育年轻人。我对此感到非常自豪。如果你找到莫菲厄斯神父，他也许能告诉你如何参与我们的救济院。再见，朋友。}
{306}{}{如果你找到莫菲厄斯神父，他也许能告诉你如何参与我们的救济院。再见，朋友。}
{307}{}{如果你找到莫菲厄斯神父，他也许能告诉你如何参与我们的救济院。再见，朋友。}
