{100}{}{你注意到并成功避开了一根横跨走廊的单分子丝线。}
{101}{}{你感到腿部剧痛。你被一根单分子丝线划开了伤口。}
{102}{}{它严重伤害了你的右腿。}
{103}{}{它严重伤害了你的左腿。}
{104}{}{你拆除了单分子丝线陷阱，并在割伤手之前安全地处理了丝线。}
{105}{}{你尝试拆除丝线，但无法很好地掌握。你在被割伤前及时收手。}
{106}{}{你尝试拆除丝线，但不小心滑到，被它割伤了。}
