{100}{}{这完全不对。}
{101}{}{这样就对了。}
{102}{}{发射机制总是卡住。}
{103}{}{好多了。}
{104}{}{快搞定了。}
{105}{}{这需要点时间。}
{106}{}{问题就在这儿！}
{107}{}{约翰，我想我找到了问题所在。}
{108}{}{该死！}
{109}{}{糟糕！}
{110}{}{是我的错！}
{111}{}{我没事。}
{112}{}{好痛。}
{113}{}{我本来就是这么打算的。}
{114}{}{为什么总是这样？}
{115}{}{我的眼睛！}
{116}{}{你不是骑士。}
{117}{}{我需要找个骑士谈谈。}
{118}{}{我不明白，能量电池总是短路。}
{119}{}{你最好站远点，这很危险。}
{120}{}{请不要打扰我。}
{121}{}{注意你站的位置。}
{122}{}{你迷路了吗？}
{123}{}{抱歉，我现在没空说话。}
