{100}{}{你看到一个水商的守卫。}
{101}{}{停下。非商会成员不得靠近水塔或水泵。}
{102}{}{你不被允许进入这里，马上离开！}
{103}{}{此区域禁止进入！远离水泵。}
{104}{}{如果你珍惜自己的命，就退后。}
{105}{}{最后警告！离开。}
{106}{}{趁你还可以，最好赶紧离开。}
{107}{}{你只有几秒钟时间离开，否则就地枪决。}
{108}{}{你聋了吗？马上离开！}
{109}{}{就是这样。}
{110}{}{你得学点教训。}
{111}{}{你就是不听。}
{112}{}{给他点教训。}
{113}{}{给她点教训。}
{114}{}{非商会成员不得靠近水塔或水泵。}
{115}{}{你应该离开。}
{116}{}{我们不信任任何人，当然也包括你。}
{117}{}{最好远离水泵。}
{118}{}{如果你需要什么，去商会大厅。}
{119}{}{我们会开枪。别想尝试。}
{120}{}{我们不会让任何人危及枢纽的生命之源。}
