{100}{}{你看到一个昏昏欲睡的避难所居民。}
{101}{}{你看到一个行为可疑的避难所居民。}
{102}{}{他似乎在躲避你的目光。}
{103}{}{你发现了偷水贼！}
{104}{}{你通过杀死小偷，终结了对避难所水配给的威胁，获得了500点经验值。}
{105}{}{感谢你解决了这个案件。这对士气有很大帮助。}
{106}{}{你成功抓住了偷水贼，获得了1000点经验值。}
{107}{}{你好，}
{108}{}{。}
{109}{}{你好。你这么晚在这里做什么？}
{110}{}{啊！}
{111}{}{我担心避难所，做了个噩梦。无法入睡，所以出来走走放松一下。}
{112}{}{好的。}
{113}{}{你在这附近看到其他人了吗？}
{114}{}{抱歉，我在找偷水贼，需要检查一下你携带的东西。}
{115}{}{是的，有个人在水配给室附近行为可疑。他吓到我了。我希望他没看到我。}
{116}{}{他长什么样子？}
{117}{}{抱歉，我还是需要检查一下你携带的东西。}
{118}{}{我没看清，因为我跑掉了。}
{119}{}{好的。不管怎样，谢谢你。}
{120}{}{当然。我没什么可隐瞒的。}
{121}{}{[搜查他]}
{122}{}{别碰我！我什么都没有。现在离我远点！}
{123}{}{好的，抱歉。}
{124}{}{你是想要脑袋中弹吗？}
{125}{}{我偷了水。我很抱歉。请不要伤害我！}
{126}{}{我要带你去见警官。}
{127}{}{好吧，好吧。我没什么可隐瞒的。你自己看吧。}
{128}{}{那么，晚安。}
{129}{}{晚安。}
{130}{}{你什么也没找到。}
